format:
  html:
    css: styles.css
    number-sections: false
    theme: cosmo
    toc: true
    toc-depth: 3
project:
  title: The Letters of Charlotte Mary Yonge
  type: website
website:
  description: A digital collection of the correspondence of Charlotte Mary Yonge
    (1823-1901), English novelist and educator.
  navbar:
    left:
    - href: /
      text: Home
    - href: letters-index
      text: Letters
    - href: persons
      text: Persons
    - href: books
      text: Books
    - href: references
      text: References
    - href: about
      text: About
    title: Yonge Letters
  search: true
  title: The Letters of Charlotte Mary Yonge
