---
title: "Books by Charlotte Mary Yonge"
---

This page contains information about Charlotte Mary Yonge's published works mentioned in her correspondence.

##   Fiction (by others) 

### Storehouse of Stories, A Edited by Charlotte M. Yonge. First series  {#83}

**Date:**  1870   
**Publisher:**  London and New York: Macmillan and Co   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

This was an anthology of reprinted eighteenth- and early nineteenth-century children’s stories by various hands; a second series appeared in 1872.

The stories were ‘The History of Philip Quarll’, ‘The Renowned History of little Goody Two-Shoes’, ‘The Governess, or, The Little Female Academy’, ‘Jemima Placid, or, The advantage of good-nature’, ‘The Life and Perambulations of a Mouse’, ‘The Village School’, ‘The Little Queen’ and ‘The History of little Jack’.

##  Edited fiction (by others)

### Warne’s Victoria Tales and Stories series. Edited by the author of “The Heir of Redclyffe.  {#211}

**Date:**  n.d. [1868-1871]   
**Publisher:**  London: Frederick Warne and Co.   
**Format:**  Edited booklet series   
**Serialization:**    
**Illustrator:**  Illustrated by the Dalziel Brothers.   

The volumes in this series are not by CMY, but are sometimes catalogued as by her.

Titles include Ella’s Dream [1870], Mary, Mary, Quite Contrary [1870], Cloudland, Esther Stanhope, or, The Crowning Delight, Lost in the Lebanon, The Knight of the Feathery Sword, Sarah Watkins, or, Crumbs for the Birds.

By E. E. G. B., Hasty Harry, A Bit of Fun, The Old School-room Piano, The Virtue of Patience, Alice\'s Watch, Wax Matches and Wooden Ones, Carrie\'s Two Victories, Harry\'s Snow-shoes, Lost on the Line, Summer Arithmetic and The Flax Gatherers.

The MP (April 1871), 418, recommended Mrs Filby\'s Maria and Silvertongue from the same series.

The former is referred to in a letter by CMY and was probably by her correspondent Anne Mercier.

Although neither of the latter has a separate entry in either COPAC or WorldCat, Cambridge University Library holds a group catalogued as \'Victoria Tales and Stories, Packet F\', 12 volumes in paper wrapper, which consist of: A Bit of Fun, Cloudland, Found in the Fog, Hasty Harry, Lost on the Line, The Flax Gatherers, Wax Matches and Wooden Ones, The Old Bottle, Mrs.

Filley\'s Maria, The Hunt Ribbon, The story of Dog Acis, Silver Tongue and Responsibility It also holds a similar \'Packet N\', consisting of Alice\'s Watch, Carrie\'s Two Victories, Ella\'s Dream, The Old Schoolroom Piano, The Knight of the Feathery Sword, A Girl\'s Adventure, To-Morrow, The Virtue of Patience, Lost in the Lebanon, Henry\'s Snow-Shoes, Mary, Mary, quite Contrary and Summer Arithmetic

See also Warne’s Star of Hope series, for another group of tales sometimes erroneously attributed to CMY.

##  Edited fiction (by others) 

### Warne’s Star of Hope series. Edited by the author of “The Heir of Redclyffe “.  {#212}

**Date:**  n.d.   
**Publisher:**  London: Frederick Warne and Co., Bedford Street, Covent Garden.   
**Format:**  Edited booklet series   
**Serialization:**    
**Illustrator:**    

This series includes Mary and Norah, or, Queen Katherine’s School; Willie’s trouble, and How He Came Out of it; New Friends, or, St Cadog’s Well; King Tolv’s Bride; Thomas Green’s Adventure, or, A Young Quixote; and Alice, or, The Little Sentinel.

See also Warne’s Victoria Tales and Stories, for another group of texts sometimes erroneously attributed to CMY.

The Virtue of Patience, Esther Stanhope and Lost on the Line appear in both series.

##  Edited translation 

### Behind the Hedges, or, The War in La Vendée. By Madame de Witt, the translation edited by Charlotte M. Yonge, author of "The Heir of Redclyffe"  {#162}

**Date:**  1882   
**Publisher:**  London: Frederick Warne and Co., Bedford Street, Covent Garden.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**  Illustrated   

Later editions credit the translator as E[mily]. M[illard]., who translated a number of other works by Henriette de Witt.

### Catharine of Aragon and the Sources of the English Reformation. By Albert Du Boys. Edited from the French, with notes, by Charlotte M. Yonge, author of “The Heir of Redclyffe” &c. &c.. 2 vols  {#151}

**Date:**  1881   
**Publisher:**  London : Hurst and Blackett, 13 Great Marlborough Street.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



### Dames of High Estate By Henriette de Witt.  The translations edited by Charlotte M. Yonge.  {#100}

**Date:**  1869   
**Publisher:**  London: Frederick Warne and Co., Bedford Street, Covent Garden.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



### Life and Adventures of Count Beugnot . Edited by Charlotte M. Yonge. 2 vols.  {#92}

**Date:**  1871   
**Publisher:**  London : Hurst and Blackett.   
**Format:**  Edited book   
**Serialization:**  Translation of Comte Jacques-Claude Beugnot,<i> Mémoires du comte Beugnot, ancien ministre</i> (178  
**Illustrator:**    

Probably translated by Julian Yonge

### Man of Other Days. Recollections of the Marquis Henry Joseph Costa de Beauregard, A. 2 vols.  {#123}

**Date:**  1877   
**Publisher:**  London : Hurst and Blackett.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

Probably translated by Julian Bargus Yonge.

### Marie Therèse de Lamourous: foundress of the house of La Miséricorde at Bourdeaux [sic]. A biography abridged from the Fr. [of F. Pouget] by the author of ‘The Heir of Redclyffe’.  {#31}

**Date:**  1858   
**Publisher:**  John W Parker and Son West Strand, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The title page may that CMY translated this work herself, which is not the case with all the translations from the French described as ‘edited’ by her.

### Memoirs of Marshal Bugeaud from his private correspondence and original documents 1784-1849.  By the Count H. D’Ideville. Edited from the French by Charlotte M. Yonge,  2 vols  {#179}

**Date:**  1884   
**Publisher:**  London : Hurst and Blackett, 13 Great Marlborough Street.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

Probably translated by Julian Bargus Yonge.

### Population of an Old Pear Tree, or, Stories of Insect Life, The From the French of Ernest van Bruyssel.  Edited by the author of “The Heir of Redclyffe”.  {#84}

**Date:**  1870   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

These translations \'edited\' by CMY were not translated by her, but she corrected the text.

This was almost certainly translated by Julian Bargus Yonge; see the letters to Alexander Macmillan dated

### Recollections of Colonel de Gonneville.  Published by his daughter, the Countess de Mirabeau. Edited, from the French, by Charlotte M. Yonge {#114}

**Date:**  1875   
**Publisher:**  London : Hurst and Blackett 13 Great Marlborough Street.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

Probably translated by Julian Bargus Yonge.

### Recollections of a Page at the Court of Louis XVI. Edited, from the French, by Charlotte M. Yonge.  {#103}

**Date:**  1873   
**Publisher:**  London : Hurst and Blackett.   
**Format:**  Edited book   
**Serialization:**  A translation of a work by Félix, Comte de France d’Hézecques   
**Illustrator:**    

Probably translated by Julian Bargus Yonge.

### Sparks of Light for Everyday. Collected by Madame Guizot de Witt, done into English by the translator of ‘Gold Dust’ [E.L.E.B.]. Edited by Charlotte M. Yonge.  {#161}

**Date:**  1882   
**Publisher:**  London: J. Masters & Co., 78, New Bond Street   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

E.L.E.B. is possibly CMY’s neighbour Ella L.E.Burlton.

### Two years of School Life by Madame de Pressensé. Edited by the author of “The Heir of Redclyffe.”  {#77}

**Date:**  1869   
**Publisher:**  London: Frederick Warne and Co., Bedford Street, Covent Garden.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**  Illustrated   

A translation of Élise Françoise de Pressensé, Deux ans au lycée.

### Youth of Queen Elizabeth 1533-1558, The By Louis Wiesener  {#133}

**Date:**  1879   
**Publisher:**  London : Hurst and Blackett.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



##  Fiction

### Christmas Mummers and Other Stories, The By Charlotte M. Yonge.  {#117}

**Date:**  1876  
**Publisher:**  London: Mozley and Smith   
**Format:**  Book  
**Serialization:**    
**Illustrator:**    

Reprints ‘The Christmas Mummers’, ‘The Railroad Children’, ‘Leonard the Lion-Heart’, ‘Ben Sylvester’s Word,’ ‘Midsummer Day, or, The Two Churches’, ‘Harriet and her Sister’ and ‘London Pride’.

##  Fiction 

###  Story in Just One More Tale:  A Second Collection of Stories for Children from Four to Twelve Years of Age.  Being a Companion volume to “Please Tell Me a Tale”  {#191}

**Date:**  1886   
**Publisher:**  London:  Skeffington & Son   
**Format:**  Story in collection   
**Serialization:**    
**Illustrator:**    

### Bye-words: A Collection of Tales Old and New.  {#135}

**Date:**  1880   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:** Collected from various sources.  
**Illustrator:**    

The stories included were ‘The Boy Bishop’ (first publishedin MP Christmas 1878, 620-624); ‘One will and three ways’ (MP Christmas 1877) 124-8; ‘Kaspar\'s summer dream’ (MP Christmas 1876, 16-34); ‘Buy a Broom’; ‘The Travels of Two Kits’; Selma\'s secret sighs’ (published under the pseudonym \'Euphemia Arrowsmith\' in MP Christmas 1874, 97-108); ‘Our ghost at Fantford; ‘Anna\'s Wedding Cake’; ‘Autobiography of Patty Applecheeks’; and ‘A Holiday Engagement; or, The Campbells are Coming’

### Christmas Mummers, The By the author of “The Heir of Redclyffe.”  {#30}

**Date:**  1858   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, May 1857 to March 1858   
**Illustrator:**    



### Cross Roads, or, A Choice in Life: A Story for Young Women and Older Girls, The  {#221}

**Date:**  October 1892   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Lads and Lasses of Langley. By Charlotte M. Yonge, author of “Langley School”  {#139}

**Date:**  1881   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The stories are ‘Cheap Jack’, ‘Frank’s Debt’, ‘Curiosity Trap’, ‘Drumbledore Bill’ and ‘Wolf’.

### Langley School. By the author of “The Kings of England.” Reprinted from the Magazine for the Young.  {#9}

**Date:**  1850   
**Publisher:**  John and Charles Mozley, Paternoster Row, London, and Joseph Masters, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young,</i> Sept. 1846 to Dec. 1848   
**Illustrator:**    

Twenty-seven Langley stories were published in the Magazine for the Young of which fifteen were reprinted in Langley School.

### Little Rick-Burners, The  {#187}

**Date:** 1886   
**Publisher:**  London: William Skeffington, 163 Piccadilly.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    



### Millar, a Mollar, a Ten o’clock Scholar, A  {#155}

**Date:**  n.d.   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Booklet   
**Serialization:**  Also in collection, <i>Langley Little Ones</i> (1882)   
**Illustrator:**    



### Miz Maze, or, The Winkworth Puzzle: A Story in Letters by Nine Authors, The  {#165}

**Date:**  1883   
**Publisher:**  Macmillan and Co., London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The signatures of the nine authors appear on the reverse of the title page.

They are: Frances Awdry, Mary Bramston, Christabel Rose Coleridge, A.E.

Mary Anderson Morshead, Charlotte Mary Yonge, Frances Mary Peard, Mary Susanna Lee, Eleanor C.

Price, Florence Wilford.

### More Bywords. By Charlotte M. Yonge, author of ‘The Heir of Redclyffe’, ‘Unknown to History,’ etc.. {#209}

**Date:**  1890   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Book   
**Serialization:** various  
**Illustrator:**    

Like Bye-Words (sic note different spelling), a collection of stories earlier printed elsewhere: ‘The price of blood’, ‘The cat of Cat Copse’, ‘De facto and de jure’, ‘Sigbert\'s Guerdon’, ‘The beggar\'s legacy’, ‘A review of nieces’, ‘Come to her kingdom’, ‘Mrs.

Batseyes’, and ‘Chops’.

### Nurse’s Memories.  {#200}

**Date:**  1888   
**Publisher:**  London: Eyre and Spottiswoode   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by Frederick Marriott and Florence Maplestone.   



### Rubies of St Lô, The  {#234}

**Date:**  1894   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Booklet   
**Serialization:**  Originally published in<i> MP</i> (Christmas 1892)   
**Illustrator:**    



### Sea Spleenwort and Other Stories, The. By the author of “The Heir of Redclyffe.”  {#47}

**Date:**  1862   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  Appeared originally in the Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.   
**Illustrator:**    

This contained ‘The Sea Spleenwort’, ‘The Mice at Play’ and ‘The Strayed Falcon’. A number of other Magnet stories by others seem also to have been bound up in this way and published in Groombridge’s gift book series (in which Historical Dramas also appeared).

### Sowing and Sewing: A Sexagesima Story. By Charlotte M. Yonge.  {#166}

**Date:**  1883   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Treasures in the Marshes, The By Charlotte M. Yonge, author of ‘The Cross Roads’ ‘The Constable’s Tower’ etc. {#227}

**Date:**  n.d. [September 1893]   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster, New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey  



### ‘Neighbour’s Fare’ in Stories Jolly, Stories New, Stories Strange & Stories True: A Series of New and Original Tales for Boys and Girls from Six to Fourteen Years Old  {#206}

**Date:**  1889   
**Publisher:**  London: Skeffington & Son   
**Format:**  Story in collection   
**Serialization:**    
**Illustrator:**    

### ‘Nurse’s Pocket’ in Jack Frost’s Little Prisoners. : A Collection of Stories for Children from Four to Twelve Years of Age. By Stella Austin. S. Baring-Gould. Caroline Birley. Lord Brabourne. ( {#192}

**Date:**  1886   
**Publisher:**  London: William Skeffington, 163 Piccadilly.   
**Format:**  Story in collection.   
**Serialization:**    
**Illustrator:**    



### ‘Pixie Lawn’ in Please Tell me a Tale: A Collection of Short Original Stories for Children from Four to Ten Years of Age   {#182}

**Date:** 1885   
**Publisher:**  London: Skeffington & Son   
**Format:**  Story in collection   
**Serialization:**    
**Illustrator:**    



##  Fiction (by others) 

### Storehouse of Stories, A Edited by C. M. Yonge. Second series  {#96}

**Date:**  1872   
**Publisher:**  London and New York: Macmillan and Company   
**Format:**  Edited book  
**Serialization:**    
**Illustrator:**    

Like its 1870 predecessor, this was a volume of reprinted children’s stories by other hands.

The stories were \'Family Stories\', \'Elements of Morality\', \'A Puzzle for a Curious Girl\' and \'Blossoms of Morality\'.

##  Fiction (drama) 

### Historical Dramas. By the author of “The Heir of Redclyffe, etc.”  {#55}

**Date:**  1864   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Book 8vo npn  
**Serialization:**  The plays appeared originally in the Magnet Stories for Summer Days and Winter Nights; 8 vols., 186  
**Illustrator:**  With the illustrations by D. H. Friston from the Magnet series.   

Contains The Mice at Play, The Apple of Discord, The Strayed Falcon. [plays] It was one of Groombridge’s gift book series.

### Strayed Falcon, The. By the author of “The Heir of Redclyffe.”  {#41}

**Date:**  1862   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Booklet   
**Serialization:**  No. 21 of the Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.   
**Illustrator:**  Illustrated. The frontispiece is signed D[avid] H[enry] Friston.   

Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.

Advertised as “A new story every month - Each complete in itself.”

##  Fiction (fantasy) 

### The Wars of Wapsburgh. By the author of  “The Heir of Redclyffe.”  {#56}

**Date:**  1864   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



##  Fiction (historical drama) 

###  Apple of Discord, The By the author of  “The Heir of Redclyffe.” [a play]  {#54}

**Date:** 1864   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.

Advertised as “A new story every month - Each complete in itself.”

### Mice at Play, The. By the author of  “The Heir of Redclyffe.”  {#35}

**Date:**  1860   
**Publisher:**  Groombridge and Sons, 5, Paternoster Row, London.   
**Format:**  Booklet   
**Serialization:**  No. 7 of the Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.   
**Illustrator:**  Illustrated. The frontispiece appears to be signed DHF, for David Henry Friston who also illustrated <i>The Strayed Falcon</i>.   

Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.

Advertised as “A new story every month - Each complete in itself.”

##  Fiction (historical)

### Chaplet of Pearls, or, The White and Black Ribaumont, The. By the author of  “The Heir of Redclyffe.”  {#69}

**Date:**  1868   
**Publisher:**  London: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialised in <i>Macmillan’s Magazine</i>, Vol 17, November, 1867 to Vol 19 December 1868   
**Illustrator:**    

Stray Pearls and The Release are sequels to this novel.

### Danvers Papers: An Invention, The By the author of  “The Heir of Redclyffe.”  {#63}

**Date:**  1867.   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Grisly Grisell, or, The Laidly Lady of Whitburn: A Tale of the Wars of the Roses. 2 vols.  {#228}

**Date:**  1893   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Herd-boy and His Hermit, The  {#248}

**Date:**  October 1899   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Kenneth, or, The Rear Guard of the Grand Army. By the author of  “Scenes and Characters,” “Kings of England,” etc.  {#10}

**Date:**  1850   
**Publisher:**  John Henry Parker, Oxford and London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Lances of Lynwood, The. By the author of “The Little Duke;” “Heartsease:” “Heir of Redclyffe;” Etc.  {#23}

**Date:** .1855   
**Publisher:**  John W Parker and Son West Strand, London.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, January 1853 to December 1854.   
**Illustrator:**  With Illustrations by J.B [Jemima Blackburn]   



### Prince and the Page: A Story of the Last Crusade, The By the author of “The Heir of Redclyffe.”  {#61}

**Date:**  1866   
**Publisher:**  London and Cambridge: Macmillan and Co.,   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, January to December 1865   
**Illustrator:**  With six illustrations by R. Farren.   



### Slaves of Sabinus, Jew & Gentile, The  {#207}

**Date:**  October 1890   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Unknown to History: A Story of the Captivity of Mary of Scotland. 2 vols.  {#157}

**Date:**  1882   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. Hennessy.   



##  Fiction (historical) 

###  Mystery of the Cavern, The (Published with reprint of Abbeychurch). By the author of “The Heir of Redclyffe.”  {#94}

**Date:**  1872   
**Publisher:**  John and Charles Mozley, Paternoster Row, London. Joseph Masters, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, January to December 1867.   
**Illustrator:**    



### Armourer’s \'Prentices, The  {#171}

**Date:** 1883   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>English Illustrated Magazine</i> Oct 1883-Aug 1884   
**Illustrator:**    



### Caged Lion, The By Charlotte M. Yonge, author of “The Heir of Redclyffe”.  {#81}

**Date:** 1870   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book   
**Serialization:** Serialized in<i> MP</i> July 1868-Dec 1869, and before that in the<i> Barnacle</i>, 1866-67.   
**Illustrator:** The illustrations are signed with a monogram.   

This seems to be the first publication with “Charlotte M.

Yonge” given as author.

### Carbonels, The By Charlotte M. Yonge, author of “Under the Storm,” “The Cook and the Captive,” etc. {#236}

**Date:** n.d. [September 1895]   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster, New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey.  

This story, and its sequel Founded on Paper are set in rural Hampshire, starting in the early 1820s, at the time CMY’s parents settled in Otterbourne.

### Constable’s Tower, or, The Times of Magna Charta, The By Charlotte M. Yonge, author of ‘The Heir of Redclyffe’ ‘Under the Storm’ etc. {#214}

**Date:** October 1891   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book 8vo 214pp  
**Serialization:**    
**Illustrator:**  Four illustrations signed C. O. Murray.  



### Cook and the Captive, or, Attalus the Hostage, The By Charlotte M.Yonge, author of ‘The Constable’s Tower’ ‘The Slaves of Sabinus’ etc. {#233}

**Date:** September 1894   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster, New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book 8vo 228pp   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey   



### Cunning Woman’s Grandson: A Tale of Cheddar a Hundred Years Ago, The  {#203}

**Date:**  1889   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

Leeds University Library has A Tale of Cheddar Caves One Hundred Years Ago, with illustrations by W. S.

Stacey, published in Wells: Dowman Woodhams n.d, which is presumably a reprint of this book.

### Dove In The Eagle’s Nest, The. 2 vols. By the author of  “The Heir of Redclyffe.”  {#62}

**Date:**  1866   
**Publisher:**  Cambridge and London: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in <i>Macmillan’s Magazine </i>May -Dec 1865   
**Illustrator:**    



### Little Duke, or, Richard the Fearless, The. By the author of “The Heir of Redclyffe”, “The Kings of England.”  {#20}

**Date:**  1854   
**Publisher:**  John W Parker and Son, West Strand, London   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, January to October 1851   
**Illustrator:**  With illustrations, drawn and lithographed by J.B. [Jemima Blackburn]   



### Love and Life: An Old Story in Eighteenth Century Costume. 2 vols.  {#137}

**Date:**  1880   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Modern Telemachus, A  {#185}

**Date:**  1886   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, as “A Modern Quest of Ulysses”, Jan-Dec 1886   
**Illustrator:**  Illustrated by W. J. Hennessy.  



### Patriots of Palestine: A Story of the Maccabees, The By Charlotte M. Yonge, author of ‘Under the Storm’ ‘The Slaves of Sabinus’ etc.  {#246}

**Date:**  October 1898   
**Publisher:** London: National Society’s Depository, Broad Sanctuary, Westminster, New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey.  



### Pigeon Pie, The By the author of “The Heir of Redclyffe.”  {#34}

**Date:**  1860   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, November 1851 to October 1852   
**Illustrator:**  Illustrated frontispiece, but no artist named.   



### Pilgrimage of the Ben Beriah: A Novel, The  {#243}

**Date:**  1897   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Originally published in the American children\'s magazine <i>St.Nicholas</i>?  
**Illustrator:**    



### Release, or, Caroline’s French Kindred, The {#239}

**Date:**  September 1896   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  The first chapter published as ‘Caroline’s Defiance’ in<i> MP</i> Dec 1894   
**Illustrator:**    

This is a sequel to The Chaplet of Pearls and Stray Pearls.

### Reputed Changeling, or, Three Seventh Years Two Centuries Ago, A 2 vols.  {#205}

**Date:**  1889   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Stray Pearls: Memoirs of Margaret de Ribaumont, Viscountess of Bellaise. 2 vols  {#170}

**Date:**  1883   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan 1881-May 1883   
**Illustrator:**  Illustrated by W.J. Hennessy.   

This is a sequel to The Chaplet of Pearls.

### The History of the Life and Death of the Good Knight Sir Thomas Thumb, with divers other matters concerning the court of good King Arthur of Britain. By the author of “The Heir of Redclyffe,” “ {#21}

**Date:**  1855   
**Publisher:**  Thomas Constable and Co., Edinburgh: Hamilton, Adams, and Co, London:.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by J.B [Jemima Blackburn]   



### Two Penniless Princesses.  {#216}

**Date:**  1891   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan-Dec 1890   
**Illustrator:**    



### Under the Storm, or, Steadfast’s Charge.  {#194}

**Date:**  1887   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Wardship of Steepcombe, The  {#238}

**Date:**  September 1896   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey.   



##  Fiction (modern)

### Abbeychurch, or, Self Control and Self Conceit.  {#2}

**Date:** 1844   
**Publisher:**  James Burns, Portman Street; London, and Henry Mozley and Sons, Derby.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Unsigned frontispiece  



### Cheap Jack.  {#147}

**Date:**  1881   
**Publisher:**  London: Walter Smith (late Mozley), 34 King Street, Covent Garden.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

Also in collection, Lads and Lasses of Langley (1881)

### Countess Kate. By the author of “The Heir of Redclyffe.”  {#44}

**Date:**  1862   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, October 1861 to December 1862   
**Illustrator:**    

The heroine also appears in The Pillars of the House.

### Daisy Chain, or, Aspirations: A Family Chronicle, The. By the author of “The Heir of Redclyffe.” 2 Vols  {#24}

**Date:**  1856   
**Publisher:**  John W Parker and Son, West Strand, London.   
**Format:**  Book   
**Serialization:**  Part 1 serialized in<i> MP</i>, July 1853 to December 1855.   
**Illustrator:**    

The May family appear again in The Trial and other novels.

### Disturbing Element, or, Chronicles of the Blue-bell Society, The By Charlotte M. Yonge, author of “The Heir of Redclyffe”  {#125}

**Date:**  1878   
**Publisher:**  London: Marcus Ward & Co., 67, 68 Chandos Street and Royal Ulster works, Belfast   
**Format:**  Book 8vo 240pp  
**Serialization:**    
**Illustrator:**  Illustrated by Percy Macquoid.   

One of the Blue-Bell series of 14 one-volume novels.

### Dynevor Terrace, or, The Clue of Life. 2 vols. By the author of “The Heir of Redclyffe.” .  {#27}

**Date:**  1857   
**Publisher:**  John W Parker and Son West Strand, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Frank’s Debt  {#146}

**Date:**  1881   
**Publisher:**  London: Walter Smith (late Mozley), 34 King Street, Covent Garden.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

Also in collection, Lads and Lasses of Langley (1881)

### Henrietta’s Wish, or, Domineering: A Tale.  By the author of  “Scenes and Characters”.  {#11}

**Date:**  1850   
**Publisher:**  Joseph Masters, Aldersgate Street, and New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in <i>The Churchman’s Companion</i>, January 1849 to May 1850   
**Illustrator:**  Unsigned Frontispiece   



### Hopes and Fears, or, Scenes from the Life of a Spinster. By the author of “The Heir of Redclyffe,” “Heartsease,” Etc.  {#37}

**Date:**  1860   
**Publisher:**  London: John W Parker and Son, West Strand.   
**Format:**  Book   
**Serialization:** Part serialized in the<i> Constitutional Press</i>, Jun 1859-Dec 1860   
**Illustrator:**    

The Rev.

Robert Fulmort and other characters recur in The Pillars of the House.

### Mrs Elderney’s School  {#12}

**Date:**  1850   
**Publisher:**  Published in the <i>Magazine for the Young</i> Jan 1850-Jan 1852   
**Format:**  Serial in Journal   
**Serialization:**  only appeared as a serial  
**Illustrator:**    

### New Ground (Kaffirland). “By the author of “The Heir of Redclyffe.”  {#68}

**Date:**  1868   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, Masters and Co., 78, New Bond Street   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, January 1863 to November 1866.   
**Illustrator:**    



### Railroad Children, The. By the author of “The Heir of Redclyffe,” “Scenes and Characters,” &c.  {#22}

**Date:**  1855   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London; Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in <i>the Magazine for the Young</i> April - December 1849.   
**Illustrator:**    



### Six Cushions, The By the author of “The Heir of Redclyffe.”  {#67}

**Date:**  1867   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan-December 1866   
**Illustrator:**  The single frontispiece seems to be signed G Peen.   



### Stokesley Secret, The. By the author of “The Heir of Redclyffe.”  {#40}

**Date:**  1861   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, January 1860 to April 1861   
**Illustrator:**    



### Strolling Players: A Harmony of Contrasts. By Charlotte M. Yonge and Christabel R. Coleridge.  {#229}

**Date:**  1893   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan 1892-Mar 1893   
**Illustrator:**    

It includes some of the Merrifield family from The Stokesley Secret and The Two Sides of the Shield.

### That Stick.  {#226}

**Date:**  1892   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, January to December 1891   
**Illustrator:**    



### Two Guardians; or, Home in this World, The By the author of “Henrietta’s Wish,” “Kenneth,” etc.  {#13}

**Date:**  1852   
**Publisher:**  Joseph Masters, Aldersgate Street, and New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Churchman’s Companion</i> July 1850-Feb 1852   
**Illustrator:**    



### Wolf.  {#145}

**Date:**  1881   
**Publisher:**  London: Walter Smith (late Mozley), 34 King Street, Covent Garden.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

Also in collection, Lads and Lasses of Langley (1881)

##  Fiction (modern) 

### Astray: A Tale of a Country Town. By Charlotte M. Yonge, Mary Bramston, Christabel Coleridge, Esmé Stuart.  {#193}

**Date:** 1887   
**Publisher:**  London: Hatchards, Piccadilly. Serialized in<i> MP</i>, July 1885 to February 1886   
**Format:**  Book 8vo 407pp  
**Serialization:**    
**Illustrator:**  The single frontispiece is signed G B 86.  



### Beechcroft at Rockstone. 2 vols.  {#201}

**Date:** 1888   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> January 1887- Dec 1888   
**Illustrator:**    

This is a sequel to Scenes and Characters and The Two Sides of the Shield.

### Ben Sylvester’s Word. By the author of “The Heir of Redclyffe,” “The Railroad Children,” &c.  {#25}

**Date:** 1856   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Booklet   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, March to June 1856   
**Illustrator:**    



### Burnt Out: A Story for Mothers’ Meetings.  {#128}

**Date:** 1879   
**Publisher:**  Walter Smith (late Mozley), 6 Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Castle Builders, or, The Deferred Confirmation, The. By the author of “Heartsease,” “The Heir of Redclyffe,” “Scenes and Characters,” etc.  {#18}

**Date:**  1854   
**Publisher:**  John and Charles Mozley, 6 Paternoster Row, London   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, April 1851 to May 1853.   
**Illustrator:**    

The character of Constance recurs in The Pillars of the House.

### Chantry House.  By Charlotte M. Yonge. author of “The Heir of Redclyffe,” “Unknown to History,” etc.. 2 vols  {#186}

**Date:**  1886   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Château de Melville, ou, Recréations du cabinet d’étude, Le  {#1}

**Date:**  1839   
**Publisher:**  Chez Jacob & Johnson, Impremeurs, a Winchester: et chez Harris, St. Paul\'s Church-yard, a Londres.  
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

One of CMY’s rarest works, there are copies at Girton College, Cambridge and in the Bodleian Library.

The characters reappear under other names in Scenes and Characters.

Although it was printed privately, it seems to have been advertised for sale by Simpkin, who may perhaps have bought what was left of the stock.

### Clever Woman of the Family, The. 2 vols. By the author of  “The Heir of Redclyffe.”  {#58}

**Date:**  1865   
**Publisher:**  London and Cambridge: Macmillan and Company   
**Format:**  Book   
**Serialization:**  Serialised in<i> Churchman’s Family Magazine</i>, Jan 1864 to April 1865   
**Illustrator:**    



### Founded on Paper, or, Uphill and Downhill between the Two Jubilees. By Charlotte M. Yonge, author of ‘Under the Storm,’ ‘The Carbonels,’ etc. {#242}

**Date:**  October 1897   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey.  

This is a sequel to The Carbonels.

### Friarswood Post Office. By the author of “The Heir of Redclyffe.”  {#36}

**Date:**  1860   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, August 1858 to August 1859.   
**Illustrator:**  There is one frontispiece signed F. Anderson Sc..  



### Harriet and her Sister.  {#7}

**Date:**  1848   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London, and Joseph Masters, 78, New Bond Street, London   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**  One unsigned plate  

There are copies in the NLW and Lambeth Palace Library.

It was reprinted in The Christmas Mummers and Other Stories (1876).

### Heartsease, or, The Brother’s Wife. 2 vols. By the author of “The Heir of Redclyffe.”  {#19}

**Date:**  1854   
**Publisher:**  John W Parker and Son West Strand, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

‘Last Heartsease Leaves’ is a short sequel which seems to have been the original ending of the novel.

### Heir of Redclyffe, The By the author of “The Two Guardians,” “Henrietta’s Wish,” “The Kings of England.” 2 vols.  {#15}

**Date:**  1853   
**Publisher:**  John W Parker and Son, West Strand, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Lady Hester, or, Ursula’s Narrative.  {#110}

**Date:**  1874   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The Tauchnitz edition of this book (Leipzig 1874) also includes The Mouth of the Leamy.

### Langley Little Ones: Six Stories by Charlotte M. Yonge  {#152}

**Date:**  1882   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London   
**Format:**  Book   
**Serialization:**  The stories are ‘Quack, Quack’; ‘Bully Brindle’; ‘Snowdrop’s Eggs’; ‘Fanny’s Doll’; ‘A Miller, a Mo  
**Illustrator:**    



### Last Heartsease Leaves. By the author of “The Heir of Redclyffe.”  {#45}

**Date:**  1862   
**Publisher:**  500 printed privately for sale for a charity.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

Reprinted as “Lost Heartsease Leaves” in last number of Events of the Month, Jan 2, 1865, pp. 615-618.

The letters from Keble reprinted in Musings over the Christian Year make it clear that this was originally written as the ending of Heartsease, and was not an afterthought.

### Leonard the Lion-Heart  {#26}

**Date:**  1856   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London; Masters and Co., 78, New Bond Street, London   
**Format:**  Booklet   
**Serialization:**  Serialized in the <i>Magazine for the Young</i>, March to June 1856   
**Illustrator:**    



### Little Lucy’s Wonderful Globe.  {#86}

**Date:**  1871   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by Lorenz Froelich   

This is a fictionalized geography book.

### London Pride.  {#8}

**Date:**  1848   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London, and Joseph Masters, 78, New Bond Street, London   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Frontispiece   

Copies in Lambeth Palace Library, University of Sheffield Library and the University of Delaware Library.

It was reprinted in The Christmas Mummers and Other Stories (1876).

### Long Vacation, The  {#237}

**Date:** 1895   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

This includes characters from Scenes and Characters, The Pillars of the House, The Two Sides of the Shield and Beechcroft at Rockstone.

### Magnum Bonum, or, Mother Carey’s Brood. 3 vols.  {#131}

**Date:**  1879   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> January 1877-December 1879   
**Illustrator:**    



### Making of a Missionary, or, Daydreams in Earnest, The By Charlotte M. Yonge, author of ‘The Herd Boy and his Hermit’ ‘The Patriots of Palestine’ etc. {#250}

**Date:** n.d. [October 1900]   
**Publisher:**  National Society’s Depository, Broad Sanctuary, Westminster, New York: Thomas Whittaker, 2 & 3 Bible House.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by W. S. Stacey.  



### Midsummer Day, or, The Two Churches.  {#5}

**Date:**  1848   
**Publisher:**  John and Charles Mozley, Paternoster Row, London, and Joseph Masters, New Bond Street, London.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

This story was later reprinted in The Christmas Mummers.

### Modern Broods, or, Developments Unlooked For.  {#251}

**Date:** 1900  
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

This includes characters from The Castle Builders, The Daisy Chain, The Stokesley Secret, Hopes and Fears, The Pillars of the House, The Two Sides of the Shield, Beechcroft at Rockstone, The Long Vacation and ‘Come to her Kingdom’.

### My Young Alcides: A Faded Photograph. 2 vols  {#112}

**Date:**  1875   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Nuttie’s Father.  {#183}

**Date:**  1885   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Our New Mistress, or, Changes at Brookfield Earl. By Charlotte M. Yonge.  {#198}

**Date:**  1888   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated by C.J. Staniland.   



### Pickle and his Page Boy, or, Unlooked For: A Story.  {#154}

**Date:**  1882   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Pillars of the House, or, Under Wode, Under Rode, The. 4 vols.  {#109}

**Date:**  1874   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> January 1870-December 1873   
**Illustrator:**  Illustrated by Herbert Gandy.   

Characters from Countess Kate, The Pillars of the House and The Castle Builders appear in this novel.

### P’s and Q’s, or, the Question of Putting Upon. By Charlotte M. Yonge, author of “The Heir of Redclyffe.”  {#95}

**Date:**  1872   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book 8vo 150pp   
**Serialization:**    
**Illustrator:**  The illustrations appear to be signed C. O. Murray.  



### Scenes and Characters, or, Eighteen Months at Beechcroft. By the author of “Abbey Church, or, Self Control and Self Conceit.”  {#3}

**Date:**  1847   
**Publisher:**  James Burns, Portman Street; London; Henry Mozley and Sons, Derby.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The Mohun family appear in the later novels Beechcroft at Rockstone and The Two Sides of the Shield.

### Three Brides, The 2 vols  {#120}

**Date:**  1876   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan 1874-June 1876   
**Illustrator:**    



### Trial: More Links of the Daisy Chain, The 2 vols. By the author of “The Heir of Redclyffe.”  {#53}

**Date:**  1864   
**Publisher:**  London and Cambridge: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, Jan 1862-April 1864   
**Illustrator:**    

This is a sequel to The Daisy Chain.

Characters reappear in Modern Broods and The Long Vacation.

### Two Sides of the Shield, The By Charlotte M. Yonge, author of “The Heir of Redclyffe,” “Unknown to History,” etc.. 2 vols.  {#184}

**Date:**  1885   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book 8vo 2 vols 208, 209 pp  
**Serialization:**  Serialized in<i> MP</i> Jan 1884-Jun 1885   
**Illustrator:**    

This is a sequel to Scenes and Characters and The Stokesley Secret.

### Young Step-mother, or, A Chronicle of Mistakes, The By the author of “The Heir of Redclyffe,” “Heartsease,” etc.  {#38}

**Date:**  1861   
**Publisher:**  London: Parker, Son, and Bourn, West Strand.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i>, April 1856 to Dec 1860   
**Illustrator:**    



##  Fiction, history 

### Selections from the Hursley Magazine for the Years 1848 & 1849: With Facsimiles of the Original Title Pages and Other Illustrations. [Edited by Selina, Lady Heathcote]  {#39}

**Date:**  1861   
**Publisher:**  Hursley: Hursley Park, privately printed.   
**Format:**  contributions to collection   
**Serialization:**    
**Illustrator:**  Illustrated.   

‘Miss Yonge’ is credited with ‘Post Script’ [editorial], ‘A Legend of Hursley’ [historical fiction], ‘Funeral of Henry II’.

##  Fiction:  

### Langley Adventures. By Charlotte M. Yonge, author of “Langley School”  {#163}

**Date:**  1883   
**Publisher:**  Walter Smith (late Mozley), 34, King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**  ‘Burrs’ seems to have been published slightly earlier in a parish magazine.   
**Illustrator:**    

Contains: ‘A Patchwork fever’; ‘Widow Wilder’s Windfall’; ‘Burrs’; ‘Left Out’; and ‘Horse Sausage’.

##  Non-Fiction: criticism 

### \'Cawnpore\' {#60}

**Date:** 1865   
**Publisher:**  Not reprinted in volume form   
**Format:**  Article in Journal   
**Serialization:**  <i>Literary Churchman</i>   
**Illustrator:**    

This was a review of Cawnpore by George Otto Trevelyan.

The author was not named.

##  Non-Fiction: theology 

### Questions on the Prayer Book.  {#142}

**Date:**  1881   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Questions on the Psalms.  {#141}

**Date:**  1881   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction, biography, criticism 

### Women Novelists of Queen Victoria’s Reign : A Book of Appreciations by Mrs. Oliphant et aliae CMY contributed essays on Lady Georgiana Fullerton, Julia Stretton and Anne Manning. {#244}

**Date:**  1897   
**Publisher:**  London: Hurst & Blackett, Limited.   
**Format:**  Contributions to collection.   
**Serialization:**    
**Illustrator:**    



##  Non-fiction, criticism, biography 

### Musings over the “Christian Year” and “Lyra Innocentium” by Charlotte Mary Yonge together with a few gleanings of Recollections of the Rev. J. Keble, gathered by several friends.  {#88}

**Date:**  1871   
**Publisher:**  Oxford and London: James Parker and Co.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Nov 1868-Nov 1870.   
**Illustrator:**    

The other contributors were the Rev. T.

Simpson Evans, Frances Maria Wilbraham and M.T..

##  Non-fiction, history, edited selection 

### English History Reading Books, Adapted to the Requirements of the New Code. With “the Advanced Part”.  {#181}

**Date:**  1885   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction, reminiscences, natural history 

### Old Woman’s Outlook in a Hampshire Village, An  By Charlotte M. Yonge. {#225}

**Date:**  1892   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Serialized in<i> MP</i> Jan-Dec 1892   
**Illustrator:**    



##  Non-fiction, theology, advice to church workers 

### How to Teach the New Testament. By Charlotte Mary Yonge (author of “The Heir of Redclyffe”) A Teacher of Many Years’ Standing.  {#144}

**Date:**  1881   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

In a series of Religious Manuals for Sunday and Day School Teachers.

### Practical Work in Sunday Schools. By Miss Yonge, author of “The Heir of Redclyffe”. {#140}

**Date:**  1881   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Booklet   
**Serialization:**  In a series of <i>Religious Manuals for Sunday and Day School Teaching</i>   
**Illustrator:**    



##  Non-fiction: advice book 

### Girl’s Little Book, The  {#231}

**Date:**  1893   
**Publisher:**  London: William Skeffington, 163 Piccadilly.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

This is an advice book and has been reprinted in the microfilm series Women and Victorian Values, 1837-1910 Advice Books, Manuals and Journals for Women.

### Talks about the Laws we Live under, or, At Langley Night-School.  {#160}

**Date:**  1882   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Womankind. By Charlotte Mary Yonge.  {#115}

**Date:**  1876   
**Publisher:**  London: Mozley and Smith, 6 Paternoster Row.   
**Format:**  Book 327pp   
**Serialization:**  Serialized in<i> MP</i> January 1874 to June 1877   
**Illustrator:**    



##  Non-fiction: advice book (by another) 

### Spring Buds: Counsels for the Young. Translated and abridged from the French, by E. L. E. B. With a preface by Charlotte M. Yonge.  {#173}

**Date:**  1883   
**Publisher:**  London: J. Masters & Co., 78, New Bond Street   
**Format:**  Preface  to book   
**Serialization:**    
**Illustrator:**    

E.L.E.B..is possibly CMY’s neighbour Ella L.E.Burlton.

##  Non-fiction: advice to aspirant writers 

### “Authorship” in Ladies at Work: Papers on Paid Employments for Ladies by Experts in the Several Branches ed. Lady Jeune  {#230}

**Date:** 1893   
**Publisher:**  London: A.D. Innes & Co.   
**Format:**  Book   
**Serialization:**  Published in<i> MP</i> September 1892.   
**Illustrator:**    



##  Non-fiction: advice to charity workers 

### Given to Hospitality.  {#159}

**Date:**  1882   
**Publisher:**  Walter Smith (late Mozley), 34 King Street, Covent Garden, London.   
**Format:**  Pamphlet   
**Serialization:**  Reprinted from<i> MP</i> May 1882   
**Illustrator:**    

A pamphlet encouraging people to have convalescents to stay.

### Parent’s Power, The Address to the Conference of the Mother’s Union  {#204}

**Date:**  1889   
**Publisher:**  Winchester: Warren   
**Format:**  Pamphlet   
**Serialization:**    
**Illustrator:**    



### What Books to Lend and What to Give.  By Charlotte M. Yonge, author of ‘The Heir of Redclyffe’ ‘Cameos from English History’ etc., {#196}

**Date:**  1887   
**Publisher:**  London: National Society’s Depository, Sanctuary, Westminster.   
**Format:**  Pamphlet, 126pp   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: biography

### Biographies of Good Women, chiefly by contributors to ‘The Monthly Packet’. Edited by the author of “The Heir of Redclyffe.” First Series.  {#43}

**Date:** 1862  
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London; Masters and Co., 78, New Bond Street, London.   
**Format:**  Contributions to collection, edited collection   
**Serialization:**    
**Illustrator:**    

The biographies of Lady Grisell Baillie, Lady Fanshawe, the Countess of Balcarres, Elizabeth Smith and Madame Swetchine are “By the author of ‘The Heir of Redclyffe’”.

Olympia Morata and Amalie Sieveking are signed E.T. and the work of Emily Taylor.

So, according to CMY, is the unsigned article on Mum Bet (perhaps unsigned because derivative of the work of Harriet Martineau).

Anna Gurney is signed by Sarah Austin.

Princess Galitzin is signed H. D..

Mrs Hutchinson, Caroline Perthes and Lady Russell are attributed to \'the author of Magdalen Stafford\', who may have been Mrs Bromfield.

Elizabeth Carter and Anne Grant of Laggan are unsigned and the work of Ann Carter Smith.

Elizabeth Fry is unsigned.

A second series of biographies was published in 1865.

##  Non-fiction: biography 

### Biographies of Good Women, chiefly by contributors to ‘The Monthly Packet’. Second series. Edited by the author of “The Heir of Redclyffe.”  {#57}

**Date:**  1865   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Contributions to collection, edited collection   
**Serialization:**  The biographies of Mrs Trimmer, Hannah More, The Five Sisters of Noailles, and Sarah Martin  are “B  
**Illustrator:**    



### Hannah More. By Charlotte M. Yonge. Eminent Women Series.  {#199}

**Date:**  1888   
**Publisher:**  London : W. H. Allen & Co., 13 Waterloo Place, S.W.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

The Eminent Women series was edited by John H.

Ingram.

### Life of H.R.H. the Prince Consort.  {#208}

**Date:**  1890   
**Publisher:**  London: W. H. Allen   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Life of John Coleridge Patteson, Missionary Bishop of the Melanesian Islands, The 2 vols  {#102}

**Date:**  1873   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Lord Seaton and his Regiment (Author not named)  {#66}

**Date:**  1867   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Christian Remembrancer</i>, Vol 54, pp. 239-285.   
**Illustrator:**    



### Memoir of Bishop Mackenzie. (Author not named)  {#52}

**Date:**  1864   
**Publisher:**  <i>Christian Remembrancer</i> Vol 47. pp. 401-426   
**Format:**  Article in Journal   
**Serialization:**    
**Illustrator:**    



### Pioneers and Founders, or, Recent Workers in the Mission Field. By C. M. Yonge, author of “The Heir of Redclyffe”. {#90}

**Date:** 1871  
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book   
**Serialization:**  It appeared in Macmillan\'s Sunday Library of Household Reading  
**Illustrator:**  The title page has an engraved portrait of Bishop Reginald Heber.   

The preface is dated 17 March 1871.

### Seven Heroines of Christendom.  {#215}

**Date:**  September 1891   
**Publisher:**  London: Sonnenschein   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: critical anthology

### New National Poetry Cards, Standards 6 and 7.  Edited and Annotated by Charlotte M. Yonge. {#164}

**Date:**  1883   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster.  
**Format:**  18cm [???]  
**Serialization:**    
**Illustrator:**    

##  Non-fiction: critical anthology 

### Aunt Charlotte’s Evenings at Home with the Poets : A Collection of Poems for the Young, with Conversations, Arranged in Twenty-Five Evenings. By Charlotte M. Yonge, author of “The Heir of Redcl {#143}

**Date:**  1881   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**  Illustrated by Mrs J. W. Whymper.  



### Historical Ballads Arranged to meet the New Code of 1882, Schedule II, English.  {#156}

**Date:**  1882   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

This seems to have been a work in three parts of which the first two were entitled Historical Ballads, and the third (aimed at older children) Historical Poetry.

Historical Ballads: Part I., for Standards II. and III
Historical Ballads: Part II., for Standards IV. and V.

Historical Poetry: Part III, for Standards VI. and VII edited and annotated by Charlotte M.

Yonge, author of \'Cameos from English history\', \"The heir of Redclyffe\', &c.; arranged to meet the New Code of 1882, Schedule II., English.

##  Non-fiction: critical preface 

### Whispers of Love and Wisdom. Collected and arranged by Annie Cazenove; with a preface by C.M. Yonge.  {#153}

**Date:**  1882   
**Publisher:**  Griffith and Farran, London.   
**Format:**  Preface to book  
**Serialization:**    
**Illustrator:**    



##  Non-fiction: criticism

### Quentin Durward by Sir Walter Scott Edited, with a historical introduction, by CMY  {#210}

**Date:** 1890  
**Publisher:**  Boston: Ginn and Company   
**Format:**  Preface to book   
**Serialization:**    
**Illustrator:**    

Ginn’s Children’s Classics series, in which The Talisman also appeared with a preface by CMY, although she is not credited as its editor.

### Talisman, The by Sir Walter Scott, preface by CMY, edited by Dwight Holbrook {#188}

**Date:**  1886  
**Publisher:**  Boston: Ginn & Co.  
**Format:**  Preface to book  
**Serialization:**    
**Illustrator:**    

Like Quentin Durward, this appeared in Ginn’s ‘Classics for Children’ series.

##  Non-fiction: criticism 

### Eugénie de Guérin. (Author not named)  {#50}

**Date:**  1864   
**Publisher:**  <i>Christian Remembrancer</i>, Vol. 47, pp. 1-26.   
**Format:**  Article in Journal   
**Serialization:**    
**Illustrator:**    



### Sintram and his Companions and Undine By Friedrich, Baron La Motte Fouqué. With introduction by Charlotte M. Yonge. {#241}

**Date:**  1896   
**Publisher:**  London: Gardner, Darton & Co.   
**Format:**  Preface to book   
**Illustrator:**  Illustrated by Gordon Browne.  



### The La Ferronnays Family (Author not named)  {#64}

**Date:**  1867   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in journal  
**Serialization:**   <i>Christian Remembrancer</i>, Vol 53, pp-353-388   
**Illustrator:**    

.

### \'Diplomate on the Fall of the First Empire, A\' (Author not named)  {#85}

**Date:**  1871   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Macmillan’s Magazine.</i> 24 August 1871   
**Illustrator:**    



### “Children’s literature of the last century: I. - Nursery books of the eighteenth century.” by Miss Yonge  {#74}

**Date:** 1869   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Macmillan’s Magazine.</i> 20 (May, 1869): 229-237   
**Illustrator:**    

An early instance of CMY allowing her name to appear, though not in the form she ultimately adopted.

### “Children’s literature of the last century: II. - Didactic fiction.” By Miss Yonge.  {#75}

**Date:**  1869   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Macmillan’s Magazine.</i> 20 (1869): 302-310   
**Illustrator:**    



### “Children’s literature of the last century: III. - Class literature of the last thirty years.” By Miss Yonge.  {#76}

**Date:**  1869   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Macmillan’s Magazine.</i> 20 (Oct, 1869): 448-456   
**Illustrator:**    



##  Non-fiction: edited drama 

###  Shakespeare’s Plays for Schools.  Prepared and annotated for school use by Charlotte M. Yonge. 5 vols  {#167}

**Date:**  1883-5   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster.  
**Format:**  Book, 5 vols   
**Serialization:**    
**Illustrator:**    

Contains Henry IV parts I and II, Henry V, Richard II and Julius Caesar.

##  Non-fiction: edited selection 

### Higher Reading-Book for Schools, Colleges and General Use. Edited with introduction and notes by Charlotte M. Yonge.  {#180}

**Date:**  1885   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: edition (by another) 

###  Chips from the Royal Image,  Being fragments of the Eikon Basilike of Charles I.  Arranged by A. E. M. Anderson Morshead.  Edited by Charlotte M. Yonge. {#195}

**Date:** 1887   
**Publisher:**  London: J. Masters & Co.  
**Format:**  Edited book  
**Serialization:**    
**Illustrator:**    

##  Non-fiction: history

### Kings of England: A History for Young Children.  {#6}

**Date:**  1848   
**Publisher:**  John and Charles Mozley, Paternoster Row, London, and Joseph Masters, New Bond Street, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: history 

###  English Church History, Adapted for Use in Day and Sunday Schools and for General Family Reading.   By Charlotte M. Yonge, author of “The Heir of Redclyffe.” {#169}

**Date:**  1883   
**Publisher:**  London. National Society’s Depository,  Sanctuary, Westminster.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of American History for the Little Ones. By Charlotte M. Yonge and H. Hastings Weld, D.D..  {#168}

**Date:** 1883   
**Publisher:**  London: Marcus Ward & Co., Chandos St, W.C. ; and at Belfast and New York  
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of English History for the Little Ones.  {#101}

**Date:** 1873   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of French History for the Little Ones.  {#107}

**Date:** 1874   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of German History for the Little Ones.  {#122}

**Date:** 1877   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of Greek History for the Little Ones.  {#116}

**Date:** 1876   
**Publisher:**  London: Marcus Ward & Co., Chandos St, Strand; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Aunt Charlotte’s Stories of Roman History for the Little Ones.  {#121}

**Date:** 1877   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Book of Golden Deeds of all Times and all Lands Gathered and Narrated by the author of “The Heir of Redclyffe, A”  {#51}

**Date:** 1864   
**Publisher:**  London and Cambridge: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:** Title page engraving of a statue of Florence Nightingale   

Several abridged editions of this work were published.

### Book of Worthies, gathered from the Old Histories and now written out anew, A By the author of “The Heir of Redclyffe.”  {#80}

**Date:** 1869   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Cameos from English History: I. From Rollo to Edward. By the author of “The Heir of Redclyffe.”  {#73}

**Date:**  1868   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: II. The Wars in France. By the author of “The Heir of Redclyffe.”  {#93}

**Date:**  1871   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: IV. Reformation Times. By the author of “The Heir of Redclyffe.”  {#134}

**Date:**  1879   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: IX. The Eighteenth Century. By the author of “The Heir of Redclyffe.”  {#249}

**Date:**  1899   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:** Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: The Wars of the Roses. Third Series. By the author of The Heir of Redclyffe.  {#124}

**Date:**  1877   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: V. England and Spain. By the author of “The Heir of Redclyffe.”  {#174}

**Date:**  1883   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: VI. Forty Years of Stewart Rule. By the author of “The Heir of Redclyffe.”  {#197}

**Date:**  1887   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: VII. The Rebellion and Restoration. By the author of “The Heir of Redclyffe.”  {#213}

**Date:** 1890   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Cameos from English History: VIII. The End of the Stewarts. By the author of “The Heir of Redclyffe.”  {#240}

**Date:**  1896   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**  Individual cameos appeared in<i> MP</i>, irregularly from 1856 to 1889.   
**Illustrator:**    



### Eighteen Centuries of Beginnings of Church History.  {#119}

**Date:**  1876   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  <i>Monthly Paper of Sunday Teaching</i>  
**Illustrator:**    



### English History Reading Books, adapted to the requirements of the New Code. Parts 1-5. Part 6: The Young Student’s History Reading Book.  {#150}

**Date:**  1881-1883   
**Publisher:**  London: National Society’s Depository, Broad Sanctuary, Westminster.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Folk Lore and Old Stories (Author not named)  {#65}

**Date:**  1867   
**Publisher:**  Not reprinted in volume form  
**Format:**  Article in Journal   
**Serialization:**  <i>Christian Remembrancer</i>, Vol. 54, pp.33-83.   
**Illustrator:**    



### Hanoverian Period, with Biographies of Leading Persons, The Part 6 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#224}

**Date:**  1892   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### History of France. Pt. 8 in A Historical Course for Schools, edited by E.A. Freeman  {#99}

**Date:** 1879  
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

Although this book is dated 1872 both by Coleridge, Life and in A Chaplet for Charlotte Yonge, followed by NCBEL, that seems to be the date of the commencement of Freeman\'s \'Historical Course for Schools\' series rather than of the publication of CMY\'s France.

It was advertised as published \'this day\' in John Bull (26 April 1879) 257.

It is to be distinguished from the work of the same title, published in 1878, also by Macmillan, which CMY contributed to the \'History Primers\' series edited by J. R.

Green.

The latter has eight chapters rather than ten and is aimed at younger children.

### Landmarks of History 1. Ancient History from the Earliest Times to the Mahometan Conquest. By the author of “The Kings of England.”  {#14}

**Date:**  1852   
**Publisher:**  John and Charles Mozley, Paternoster Row, London; J.H. Parker, Oxford; and 337, Strand; London; and Joseph Masters, 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Landmarks of History 2. Middle Ages: from the Reign of Charlemagne to that of Charles V. By the author of “The Kings of England,” etc.  {#16}

**Date:**  1853   
**Publisher:**  John and Charles Mozley, Paternoster Row, London; J.H. Parker, Oxford; and 337, Strand; London; Joseph Masters, 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Landmarks of History III. Modern History: From the Reformation to the Fall of Napoleon. By the author of “The Heir of Redclyffe” and “The Kings of England.”  {#28}

**Date:**  1857   
**Publisher:**  John and Charles Mozley, 6 Paternoster Row, London. Masters and Co. 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Landmarks of Recent History, 1770-1883.  {#172}

**Date:**  1883   
**Publisher:**  Walter Smith, 34 King Street, Covent Garden, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Old Times at Otterbourne.  {#218}

**Date:**  [September] 1891   
**Publisher:**  Winchester: Warren and Son, Printer and Publisher, High Street, London: Simpkin and Co. Limited, Stationers’ Hall Court  
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Parallel History of France and England, consisting of Outlines and Dates, A By C.M. Yonge.  {#89}

**Date:**  1871   
**Publisher:**  London: Macmillan and Co.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Pictorial History of the World’s Great Nations, from the Earliest Dates to the Present Time, A. 2 vols {#158}

**Date:**  1882   
**Publisher:**  New York: Selmar Hess.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Pupils of St. John the Divine, The By the author of “The Heir of Redclyffe.”   {#72}

**Date:**  1868   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:** Macmillan\'s Sunday Library  
**Illustrator:**  Edward Armitage  

Macmillan’s Sunday Library (originally the Sunday Library for Household Reading) was published in monthly parts at 1s. each (of which the Pupils formed the first 3 parts) and quarterly volumes at 4s. each (of which it formed volume I).

### Simple Stories Relating to English History, Part 1 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#217}

**Date:**  1891   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Stewart Period, with Biographies of Leading Persons, The, Part 5 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#223}

**Date:**  1892   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Story of the Christians and the Moors in Spain, The.  {#126}

**Date:**  1878   
**Publisher:**  London and New York: Macmillan and Company.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Tudor Period, with Biographies of Leading Persons, ThePart 4 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#222}

**Date:**  1892   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Twelve Stories from Early English History, Part 2 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#219}

**Date:**  1891   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Twenty Stories and Biographies from 1066 to 1485, Part 3 of the Westminster Historical Reading Books, Adapted to the Requirements of the New Code of 1891.  {#220}

**Date:**  1891   
**Publisher:**  National Society’s Depository, Broad Sanctuary, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Victorian Half-Century: A Jubilee Book, The By Charlotte M. Yonge, author of ‘The Heir of Redclyffe,’ ‘Unknown to History,’ etc.. {#189}

**Date:**  1886   
**Publisher:**  London and New York: Macmillan and Company   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  With a portrait of her Majesty the Queen   

The preface is dated December 1886.

This is a historical survey of Queen Victoria’s reign.

##  Non-fiction: history (by others)

### European History: Narrated in a series of Historical Selections from the Best Authorities 2 vols. Selected and arranged by E.M. Sewell and C.M. Yonge  {#82}

**Date:**  1870   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

The first volume of this title is a renamed version of Historical Selections: A Series of Readings from the Best Authorities in English and European History (1868).

##  Non-fiction: history (by others) 

### Historical Selections: A Series of Readings from the Best Authorities in English and European History. Selected and arranged by E.M. Sewell and C.M. Yonge  {#71}

**Date:**  1868   
**Publisher:**  London: Macmillan and Company   
**Format:**  Edited book  
**Serialization:**    
**Illustrator:**    

Probably the earliest instance of CMY’s name being attached to one of her published works.

##  Non-fiction: history, onomastics. 

### History of Christian Names, A. 2 vols. By the author of “The Heir of Redclyffe,” “Landmarks of History.”  {#48}

**Date:**  1863   
**Publisher:**  John W Parker and Son West Strand, London   
**Format:**  Book   
**Serialization:**  Part appeared in<i> MP</i> as ‘Name-Fancying’, May 1852 to August 1862   
**Illustrator:**    

A revised edition was published in 1884.

The book drew on a long-standing interest of CMY\'s, which she had expressed in a series of articles on \'Name-fancying\', published in MP (May 1852-August 1862).

##  Non-fiction: history, theology 

### Chosen People: A Compendium of Sacred and Church History for School Children, The. By the author of the “Heir of Redclyffe.”  {#42}

**Date:**  1859   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London. Masters and Co., 78, New Bond Street, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: history, topography 

### John Keble’s Parishes: A History of Hursley and Otterbourne. By Charlotte M. Yonge, An Old Inhabitant.  {#247}

**Date:**  1898   
**Publisher:**  London and New York: Macmillan and Co.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



##  Non-fiction: instructions to charity workers 

### Girls’ Friendly Society: A Short Account of its Working in the Diocese of Winchester to the end of the year 1878, The  {#132}

**Date:**  1879   
**Publisher:**  Winchester: privately printed.   
**Format:**  Pamphlet   
**Serialization:**    
**Illustrator:**    

There is a copy of this pamphlet in Lambeth Palace Library.

##  Non-fiction: natural history 

### Herb of the Field, The By the author of “The Kings of England”, “Langley School”, “Scenes and Characters”, etc..  {#17}

**Date:** 1853   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  Serialized as “Chapters on Flowers” in the<i> Magazine for the Young,</i> Feb 1850-Dec 1852   
**Illustrator:**    



### Instructive Picture Book, or, Lessons from the Vegetable World, The. By the author of “The Heir of Redclyffe,” and “The Herb of the Field”,  {#29}

**Date:**  1857   
**Publisher:**  Edmonston & Douglas, 87 Princes Street, Edinburgh.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated with 31 coloured plates arranged by Robert M. Stark, Fellow of the Botanical and Royal Physical Societies, Edinburgh and author of “A Popular History of British Mosses”.   



##  Non-fiction: preface

### Journal of the Lady Beatrix Graham, Sister of the Marquis of Montrose [Preface by CMY] {#91}

**Date:**  1871   
**Publisher:**  London: Bell and Daldy, York Street, Covent Garden   
**Format:**  Preface to book  
**Serialization:**    
**Illustrator:**  Unsigned decorations   

This was an anonymous novel by Jane Mary Dampier.

The preface is dated August 1870.

It was reviewed in ‘Hints on Reading’ MP (April 1871) 420: \'Journal of Lady Beatrix Graham (Bell and Daldy) is a charming picture of the life of the great Marquis of Montrose and his loving admiring young sister, during the interval between his loyal exploits in Scotland and his death.

We like it the best of all the imaginary diaries that have been so numerous.’ .

### Sketches of the Rites and Customs of the Greco-Russian Church By H. C. Romanoff.  With introduction by the author of “The Heir of Redclyffe”. {#70}

**Date:** 1868   
**Publisher:**  London: Rivingtons   
**Format:**  preface to book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: preface 

###  History of the Universities’ Mission to Central Africa 1859-1896, The  By A.E.M. Anderson-Morshead.  With a Preface by Charlotte Mary Yonge.  {#245}

**Date:** 1897   
**Publisher:**  London: The Universities’ Mission to Central Africa.   
**Format:**  Preface to book  
**Serialization:**    
**Illustrator:**  with maps  

### Gold Dust : A Collection of Golden Counsels for the Sanctification of Daily Life. Translated and abridged from the French, by E.L.E.B. With a preface by Charlotte M. Yonge.  {#138}

**Date:** 1880   
**Publisher:**  London: J. Masters & Co., 78, New Bond Street   
**Format:**  Preface to book  
**Serialization:**    
**Illustrator:**    

E.L.E.B. is possibly CMY’s neighbour Ella L.E.Burlton.

##  Non-fiction: preface, biography 

### ‘Memoir’ in Sermons. By the late Rev. George Collyer Harris, Prebendary of Exeter, and Vicar of St. Luke’s, Torquay.  With a memoir by Charlotte Mary Yonge.  {#113}

**Date:** 1875  
**Publisher:**  London: Macmillan and Co.   
**Format:**  preface to book   
**Serialization:**    
**Illustrator:**    

##  Non-fiction: selection 

### Chimes for the Mothers: A Reading for Each Week in the Year. By Charlotte M. Yonge {#232}

**Date:**  November 1893   
**Publisher:**  London: Wells Gardner, Darton.   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: theology 

###  Reasons why I am a Catholic and not a Roman Catholic. By the late Charlotte Mary Yonge. With a preface by G. M. Ireland Blackburne.  {#252}

**Date:** 1901   
**Publisher:**  London: Wells Gardner, Darton & Co.   
**Format:**  Pamphlet   
**Serialization:**  Originally serialized in <i>The Churchwoman</i>, edited by G. M. Ireland Blackburne.   
**Illustrator:**    



### Aunt Charlotte’s Stories of Bible History for the Little Ones. By Charlotte M. Yonge, author of “The Heir of Redclyffe,” “Stories of English History,” &c. {#111}

**Date:** 1875   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Illustrated   



### Charity: Scripture Texts and Sacred Song.  {#178}

**Date:**  1884   
**Publisher:**  Griffith and Farran, London.   
**Format:**  Edited selection   
**Serialization:**    
**Illustrator:**    



### Conversations on the Catechism: Means of Grace. By the author of “The Heir of Redclyffe.”  {#49}

**Date:**  1863   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  Series appeared in<i> MP</i>, 1851 to 1857.   
**Illustrator:**    



### Conversations on the Catechism: The Commandments. By the author of “The Heir of Redclyffe.”  {#32}

**Date:**  1859   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  Appeared in<i> MP</i>, 1851 to 1857   
**Illustrator:**    



### Conversations on the Catechism: To the end of the Creed. By the author of “The Heir of Redclyffe.”  {#33}

**Date:**  1859   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**  Appeared in<i> MP</i>, 1851 to 1857   
**Illustrator:**    



### Faith: Scripture Texts and Sacred Song.  {#175}

**Date:**  1884   
**Publisher:**  Griffith and Farran, London.   
**Format:**  Edited selection   
**Serialization:**    
**Illustrator:**    



### Hope: Scripture Texts and Sacred Song.  {#176}

**Date:**  1884   
**Publisher:**  Griffith and Farran, London.   
**Format:**  Edited selection  
**Serialization:**    
**Illustrator:**    



### Key-notes of the First Lessons for Every Day in the Year. By Miss Yonge  {#79}

**Date:**  1869   
**Publisher:**  Published under the Direction of the Tract Committee. London: Society for Promoting Christian Knowledge. Sold at the Depositories 77 Great Queen’s Street, Lincoln’s Inn Fields Inn fields; 4 Royal Exc  
**Format:**  Book   
**Serialization:**    
**Illustrator:**  Not illustrated, but each page surrounded with a red line with a cross on each corner. The lesson for the day at the top and the commentary below.   

An early instance of CMY allowing her name to appear, though not in the form she ultimately adopted.

### Mercy and Peace: Scripture Texts and Sacred Song.  {#177}

**Date:**  1884   
**Publisher:**  Griffith and Farran, London.   
**Format:**  Edited selection   
**Serialization:**    
**Illustrator:**    



### Militant Here on Earth By Charlotte M. Yonge.  {#149}

**Date:** 1882-3   
**Publisher:**  Not separately published   
**Format:**  Articles in journal  
**Serialization:**  <i>The Watchword</i> (printed by Warren, Winchester, for the SWW) 1882-3  
**Illustrator:**    

The Watchword was the journal of the Society of Watchers and Workers: An Association of Mutual Help and Service for Invalids, founded by Edith Sophia Jacob in 1879.

These articles may have been reprinted from elsewhere (perhaps from the Monthly Paper of Sunday Teaching?).

### Preparation of Prayer-Book Lessons.  {#202}

**Date:**  1888   
**Publisher:**  London: Smith and Innes   
**Format:**  Book   
**Serialization:**  <i>MP</i> (January 1884-October 1888)  
**Illustrator:**    

### Questions on the Collects. By the author of “The Heir of Redclyffe.” (Preface signed C.M. Yonge)  {#106}

**Date:**  1874   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Questions on the Epistles. By the author of “The Heir of Redclyffe.” (Preface signed C.M. Yonge)  {#104}

**Date:**  1874   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Questions on the Gospels. By the author of “The Heir of Redclyffe.” (Preface signed C.M. Yonge)  {#105}

**Date:**  1874   
**Publisher:**  John and Charles Mozley, 6, Paternoster Row, London.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Scripture Readings for Schools and Families. With Comments. From Joshua to Solomon.  {#97}

**Date:**  1872   
**Publisher:**  London and New York: Macmillan and Company   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    

“Reading” about a page in small type. “Comment” slightly more in larger type.

### Scripture Readings for Schools and Families. With Comments. The Kings and the Prophets.  {#108}

**Date:**  1874   
**Publisher:**  London and New York: Macmillan and Co   
**Format:**  Selection with comments   
**Serialization:**    
**Illustrator:**    



### Seal, or, The Inward Spiritual Grace of Confirmation, The by C.M. Yonge.  {#78}

**Date:**  n. d. (1869)   
**Publisher:**  London: John and Charles Mozley, 6, Paternoster Row. Masters and Son, 78, New Bond Street.   
**Format:**  Booklet   
**Serialization:**    
**Illustrator:**    

An early instance of CMY allowing her name to appear, though not in the form she ultimately adopted.

### Story of Easter, The  {#235}

**Date:**  1894   
**Publisher:**  Marcus Ward & Co., Chandos St, W.C. London; and Royal Ulster Works, Belfast.   
**Format:**  Book   
**Serialization:**    
**Illustrator:**    



### Teachings on the Catechism for the Little Ones. By Charlotte Mary Yonge. {#190}

**Date:**  1886  
**Publisher:**  London: Walter Smith, 34 King Street, Covent Garden   
**Format:**  Book  
**Serialization:**  Serialized in the <i>Monthly Paper of Sunday Teaching   
**Illustrator:**    

The preface is dated 30 December 1885, and explains that these lessons had appeared originally in the Monthly Paper of Sunday Teaching.

##  Non-fiction: theology (Bible selections)

### Scripture Readings for Schools and Families. With Comments. Apostolic Times.  {#129}

**Date:**  1879   
**Publisher:**  London and New York: Macmillan and Co   
**Format:**  Edited book  
**Serialization:**    
**Illustrator:**    

“Reading” about a page in small type. “Comment” slightly more in larger type.

##  Non-fiction: theology (bible selections) 

### Scripture Readings for Schools and Families. With Comments. Fourth Series--The Gospel Times  {#118}

**Date:**  1876   
**Publisher:**  London and New York: Macmillan and Co   
**Format:**  Edited book   
**Serialization:**    
**Illustrator:**    

“Reading” about a page in small type. “Comment” slightly more in larger type.

### Scripture Readings for Schools and Families. With comments by Charlotte M. Yonge. 5 vols  {#87}

**Date:**  1871-1879   
**Publisher:**  London and New York: Macmillan and Co   
**Format:**  Edited book  
**Serialization:**    
**Illustrator:**    

Two versions were available: the teacher\'s with comments at 3s. 6d. and a cheaper one for the pupils without comments at 1s. 6d..

In the former the \'Reading\' consists of about a page in small type; the \'Comment\' slightly more in larger type.

##  Non-fiction: theology (by another) 

### Beneath the Cross: Readings for Children in Our Lord’s Seven Sayings. By Florence Wilford. Edited by Charlotte M. Yonge. With a preface by the Rev. R.F. Wilson, M.A., Vicar of Rownhams.  {#148}

**Date:**  1869   
**Publisher:**  London: J. Masters & Co., 78, New Bond Street   
**Format:**  edited book   
**Serialization:**    
**Illustrator:**    



##  Non-fiction: theology (verse) 

### Verses on the Gospels for Sundays and Holydays By Charlotte M. Yonge.  {#136}

**Date:**  1880   
**Publisher:**  London: Walter Smith   
**Format:**  16pp  
**Serialization:**    
**Illustrator:**    



##  Non-fiction; biography 

### In Memoriam Bishop Patteson: Being with Additions the Substance of a Memoir Published in the ‘Literary Churchman’.  {#98}

**Date:**  1872   
**Publisher:**  London: William Skeffington, 163 Piccadilly.   
**Format:**  Booklet   
**Serialization:**  Based on the memoir CMY had published in the <i>Literary Churchman</i>   
**Illustrator:**    



## Fiction

### \'Mothers in Council\' {#356}

**Date:** <i>MP</i> (June 1886), 572-577.  
**Format:** Article in Journal  

Written in collaboration with Christabel Coleridge.

## Fiction (modern)

###  ‘Forewarned, Forearmed: In the Person of a Thoughtful Aunt.’ By C.M. Yonge   {#344}

**Date:** 1901  
**Publisher:** <i>Mothers in Council</i> 11.40 (Jan. 1901) 21-26  
**Format:** Short Story in Journal  

### Sea Spleenwort, The. By the author of “The Heir of Redclyffe.”  {#46}

**Date:** 1862   
**Publisher:** Groombridge and Sons, 5, Paternoster Row, London.   
**Format:** Booklet   
**Serialization:**    
**Illustrator:**  Illustrated. The frontispiece is signed with a monogram and ‘E.Whimper Sc.’ ( the engraver).   

Magnet Stories for Summer Days and Winter Nights; 8 vols., 1860-5.

Advertised as “A new story every month - Each complete in itself.”

### \'A wheel and a fall\'. By C.M. Yonge {#321}

**Date:** 1898  
**Publisher:** <i>Friendly Leaves</i> (December 1898) 2-9.  
**Format:** Short Story in Journal  

### \'G.F.S. Holiday visits of two London girls\'. By Miss Yonge. {#318}

**Date:** 1897  
**Publisher:** <i>Friendly Leaves</i> (July 1897) 232-4.  
**Format:** Short Story in Journal  

In the form of 2 letters sent from \'Langley\' showing contrasting responses to the country: one bored, one enchanted.

### \'Three Generations- Crude Girlhood\' by C. M. Yonge {#267}

**Date:** 1895  
**Publisher:** <i>Mothers in Council</i> 5:20 (October 1895) 217-226  
**Format:** Short Story in Journal  

### \'Three Generations- Heredity\' by C. M. Yonge {#265}

**Date:** 1895  
**Publisher:** <i>Mothers in Council</i> 5:18 (April 1895) 74-78  
**Format:** Short Story in Journal  

### \'Three Generations: Humanity\' {#320}

**Date:** 1897  
**Publisher:** <i>Mothers in Council</i> 7.27 (July, 1897) 173-178  
**Format:** Short Story in Journal  

No author is given but it is part of a series written by CMY

### \'Three Generations: In Praise of Dulness\' {#322}

**Date:** 1898  
**Publisher:** <i>Mothers in Council</i> 8.29 (Jan 1898) 38-46  
**Format:** Short Story in Journal  

No author is given but it is part of a series written by CMY

### \'Three Generations: Marriage\' {#323}

**Date:** 1898  
**Publisher:** <i>Mothers in Council</i> 8.31 (July 1898) 141-151  
**Format:** Short Story in Journal  

No author is given but it is part of a series written by CMY

### \'Three Generations: So-so or Cela Fera\' {#316}

**Date:** 1896  
**Publisher:** <i>Mothers in Council</i> 6.24 (Oct 1896) 215-220  
**Format:** Short Story in Journal  

No author is given but it is part of a series written by CMY

### \'Three Generations: The Book Box\'  By The Editor {#313}

**Date:** 1896  
**Publisher:** <i>Mothers in Council</i> 6.21 (Jan, 1896) 14-21   
**Format:** Short Story in Journal  



### \'World, The\' by C. M. Yonge {#259}

**Date:** 1893  
**Publisher:** <i>Mothers in Council</i> 3:9 (April 1893) 65-7  
**Format:** Short Story in Journal  

### ‘Forget-Me-Nots.\' By Charlotte M. Yonge {#330}

**Date:** 1900  
**Publisher:** <i>Friendly Leaves</i> (January -November 1900)   
**Format:** Serial story in journal  
**Serialization:** Not reprinted in volume form  

## Fiction, didactic allegory

### \'Preface- Arachne in her spectacles\' {#273}

**Date:** 1875  
**Publisher:** MP (Christmas 1875) [v-vi]  
**Format:** Article in Journal  

## Non-Fiction, reminiscences.

### \'Real Childhood, A\' By Miss Yonge {#254}

**Date:** 1892  
**Publisher:** <i>Mothers in Council</i> 2:5 (April 1892) 87-94  
**Format:** Article in Journal  

## Non-Fiction: criticism 

### \'Cawnpore\'  {#59}

**Date:** 1865  
**Publisher:** <i>Macmillan’s Magazine</i> 12 (July 1865) 267-274   
**Format:**  Article in Journal   

This was a review of Cawnpore by George Otto Trevelyan.

The author was not named.

## Non-fiction

###    ‘A Lot in Life.’ By C.M. Yonge  {#345}

**Date:** 1901  
**Publisher:**  <i>Mothers in Council</i> 11.41 (April 1901) 21-26   
**Format:** Article in Journal  



###  ‘A few thoughts on bulbs.’ By C.M. Yonge   {#335}

**Date:** 1900  
**Publisher:** <i>Mothers in Council</i> 10.37 (April 1900) 119-121    
**Format:** Article in Journal  

###  ‘A very friendly leaf.’  {#337}

**Date:** 1901  
**Publisher:** <i>Friendly Leaves</i></i> (January 1901) 45-46.   
**Format:** Article in Journal  

This series, \'Leaves for the Months\', is identified as by CMY in an obituary in Friendly Leaves, April 1901.

###  ‘Leaves of promise.’ Signed C.M. Yonge. {#338}

**Date:** 1901  
**Publisher:** <i>Friendly Leaves</i> (February 1901) 83-4.  
**Format:** Article in Journal  

In series \'Leaves for the Months\', several which are unsigned, but which are attributed to CMY in her obituary in Friendly Leaves.

###  ‘Modern Perplexitie.’ By C.M. Yonge  {#336}

**Date:** 1900  
**Publisher:** <i>Mothers in Council</i> 10.38 (July 1900) 159-167  
**Format:** Article in Journal  

###  ‘Patient Leaves.’ Unsigned. {#339}

**Date:** 1901  
**Publisher:**  <i>Friendly Leaves</i> (April 1901)  136-7.  
**Format:** Article in Journal  

This series \'Leaves for the Months\' is identified as by Yonge in the obituary in Friendly Leaves (April 1901).

###  ‘Princess Mary Adelaide.’ By C.M. Yonge {#331}

**Date:** 1900  
**Publisher:** <i>Friendly Leaves</i> (April 1900), 143-4.  
**Format:** Article in Journal  



###  ‘Sweet yet Prickly Leaves: June’. Unsigned. {#342}

**Date:** 1901  
**Publisher:** <i>Friendly Leaves</i> (July 1901) 242-3  
**Format:** Article in Journal  

This series, \'Leaves for the Months\', is identified as by CMY in the obituary in Friendly Leaves, April 1901. A footnote to this paper says ‘This is the last paper Miss Yonge wrote for us.’

###  ‘The Empress Elizabeth: A bit of true history.’  {#332}

**Date:** 1900  
**Publisher:** <i>Friendly Leaves</i> (January 1900) 48-49.  
**Format:** Article in Journal  

Signed C.M.

Yonge.

###  ‘Wind-flower Leaves: May.’ Signed C.M. Yonge. {#341}

**Date:** 1901  
**Publisher:**  <i>Friendly Leaves</i> (May 1901) 171-3.  
**Format:** Article in Journal  

This series, \'Leaves for the Months\', some of which are unsigned, is attributed to CMY in her obituary in Friendly Leaves (April 1901).

### The Queen-Woman.\' By C.M. Yonge {#325}

**Date:** 1899  
**Publisher:** <i>Mothers in Council</i> 9.34 (April 1899) 65-71.  
**Format:** Article in Journal  



### \'Authorship\' [12 in the series \'Work and Workers, by the actual Workers\'] {#276}

**Date:** 1892  
**Publisher:** MP (September 1892) 296-304  
**Format:** Article in Journal  

Reprinted in Battiscombe and Laski, 185-92.

### \'Books Recommended\'  By Lady Frederick Bruce and Miss Yonge {#315}

**Date:** 1896  
**Publisher:** <i>Mothers in Council</i> 6.23 (July, 1896) 182-188   
**Format:** Article in Journal  

Very short notices of a large number of books.

### \'Books for Young People\' {#310}

**Date:** 1887  
**Publisher:** <i>Girls\' Friendly Society Associates\' Journal and Advertiser</i> (June 1887) 75  
**Format:** Article in Journal  

The article is signed C.M.

Yonge.

### \'Books\'  By Mrs. Sumner, Lady Frederick Bruce and Miss Yonge {#317}

**Date:** 1896  
**Publisher:** <i>Mothers in Council</i> 6.24 (Oct 1896) 241-248  
**Format:** Article in Journal  

Very short notices of a large number of books.

### \'Conversation on the Girls\' Friendly Society, A\' By the Editor {#281}

**Date:** 1882  
**Publisher:** MP (September 1882) 254-261  
**Format:** Article in Journal  

### \'Conversation on the Mothers\' Union\' by the Editor {#283}

**Date:** 1887  
**Publisher:** MP (September 1887) 287-292  
**Format:** Article in Journal  

### \'Cumberland Street Children\'s Hospital, The\' {#284}

**Date:** 1871  
**Publisher:** <i>MP</i> (January 1871) 92-96  
**Format:** Article in Journal  

### \'Dulness.\' By C.M. Yonge {#326}

**Date:** 1899  
**Publisher:** <i>Mothers in Council</i> 9.35 (July 1899) 157-165.   
**Format:** Article in Journal  

### \'East Winds of Lent, The\' by C. M. Yonge {#285}

**Date:** 1891  
**Publisher:** MP (March 1891) 272-6  
**Format:** Article in Journal  

### \'Fairford and Hursley Windows, The\' {#298}

**Date:** 1866  
**Publisher:** <i>MP</i> (June 1866) 483-90  
**Format:** Article in Journal  

### \'Great Old Books.\' By C.M. Yonge {#327}

**Date:** 1899  
**Publisher:**  <i>Mothers in Council</i> 9.35 (July 1899) 174-178.  
**Format:** Article in Journal  



### \'Hints on Writing\' {#299}

**Date:** 1861  
**Publisher:** MP (July 1861) 109-13  
**Format:** Article in Journal  

### \'Introductory Letter\'  {#288}

**Date:** 1851  
**Publisher:** MP (January 1851) i-iv  
**Format:** Article in Journal  

### \'Ladies\' Association, or, Great Causes helped by Small Means, The\'  by the Editor {#289}

**Date:** 1867  
**Publisher:** MP (May 1867) 510-14  
**Format:** Article in Journal  

### \'Letter from Arachne\' in \'Two Girls\' views of the Girlhood Question\' {#291}

**Date:** 1886  
**Publisher:** MP (May 1886) 482-84  
**Format:** Article in Journal  

### \'Manners and Morals\'. By Miss Yonge {#309}

**Date:** 1884  
**Publisher:** <i>Girls\' Friendly Society Associates\' Journal and Advertiser</i> (March 1884) 34-35  
**Format:** Article in Journal  

### \'Meeting at Sion College, The\' by C. M. Yonge {#256}

**Date:** 1892  
**Publisher:** <i>Mothers in Council</i> 2: 8 (October 1892) 193-194  
**Format:** Article in Journal  

### \'Mothers to the Front\' by C. M. Yonge {#261}

**Date:** 1893  
**Publisher:** <i>Mothers in Council</i> 3:10 (April 1893) 67-73  
**Format:** Article in Journal  

### \'New Year\'s Words\' from the Editor {#293}

**Date:** 1886  
**Publisher:** MP (January 1886) 41-8  
**Format:** Article in Journal  

### \'Nous avons change tout cela, 1850-1890\' by the Editor {#294}

**Date:** 1891  
**Publisher:** MP (January 1891) 25-30  
**Format:** Article in Journal  

### \'On my Word and Honour\' {#312}

**Date:** 1891  
**Publisher:** <i>Friendly Leaves</i> (1891) 336-7  
**Format:** Article in Journal  

The article is signed Charlotte M.

Yonge.

### \'Our Tender Ones.\' By C.M. Yonge {#324}

**Date:** 1899  
**Publisher:** <i>Mothers in Council</i> 9.33 (Jan 1899) 20-27  
**Format:** Article in Journal  

### \'Preface - Noblesse Oblige\'  {#295}

**Date:** 1876  
**Publisher:** MP (Christmas 1876) 588-91  
**Format:** Article in Journal  

CMY\'s introduction to the Christmas number opens with a poem, entitled \'Noblesse Oblige\' which is signed E. E. B. and therefore not by her.

### \'Real Childhood- Young Ladyhood, A\' by C. M. Yonge {#262}

**Date:** 1893  
**Publisher:** <i>Mothers in Council</i> 3:12 (October 1893) 218-223  
**Format:** Article in Journal  

### \'Stepmothers\' By C. M. Yonge {#314}

**Date:** 1896  
**Publisher:** <i>Mothers in Council</i> 6.23 (July, 1896) 130-135   
**Format:** Article in Journal  

### \'The American Sanitary Commission\' {#303}

**Date:** 1866  
**Publisher:** <i>Christian Remembrancer</i> Vol 52 (Oct. 1866): 296-323  
**Format:** Article in Journal  

Identified in a letter (20-03-1869) to Alexander Macmillan, MS British Library Add MSS 54920: 227-8

### \'The Anatomy of Prigs\'. By C.M. Yonge {#328}

**Date:** 1899  
**Publisher:** <i>Mothers in Council</i> 9.36 (Oct 1899) 202-207.   
**Format:** Article in Journal  

### \'The Trusty Servant\' {#311}

**Date:** 1890  
**Publisher:** <i>Friendly Leaves</i> (1890) 143-145   
**Format:** Article in Journal  

The article is signed Charlotte M.

Yonge.

### \'The truest gentility.\' By Charlotte M. Yonge {#319}

**Date:** 1897  
**Publisher:** <i>The Girls\' Quarterly</i> (April 1897)124-5  
**Format:** Article in Journal  

### \'What can be done for our women?\' By C. M. Yonge {#264}

**Date:** 1894  
**Publisher:** <i>Mothers in Council</i> 4:14 (April 1894) 115-123  
**Format:** Article in Journal  

### ‘In Time of War.’ By C.M. Yonge {#333}

**Date:** 1900  
**Publisher:** <i>Mothers in Council</i> 10.37 (Jan. 1900) 3-4.      
**Format:** Article in Journal  

### ‘Leaves of Promise: April.’ Unsigned. {#340}

**Date:** 1901  
**Publisher:**  <i>Friendly Leaves</i> (April 1901) 138-9.  
**Format:** Article in Journal  

This series, \'Leaves for the Months\', is identified as by Yonge in the obituary in Friendly Leaves (April 19010.

### ‘Reviews\'. By Miss C.M. Yonge {#343}

**Date:** 1901  
**Publisher:**   <i>The Girls\' Quarterly</i> (January 1901) 107-8.   
**Format:** Article in Journal  

### ‘Temper.’ By Charlotte M. Yonge  {#334}

**Date:** 1900  
**Publisher:** <i>Mothers in Council</i> 10.37 (Jan. 1900) 26-33    
**Format:** Article in Journal  



### ‘\"With All My Mind\": A Few Words on Reading.’ By C.M. Yonge  {#329}

**Date:** 1899  
**Publisher:** <i>Mothers in Council</i>. 9.33 (Jan, 1899) 51-53   
**Format:** Article in Journal  



### “Female Education.” {#302}

**Date:** 1866  
**Publisher:** <i>Christian Remembrancer</i> Vol 51 (Jan. 1866): 21-49  
**Format:** Article in Journal  

Review of Principles of Education, drawn from Nature and Revelation and applied to Female Education in the Upper Classes by Elizabeth Missing Sewell (1865).

Identified in letter (20-03-1869) to Alexander Macmillan, MS British Library Add MSS 54920: 227-8

### “Manners and Morals. By Miss Yonge.”  {#306}

**Date:** 1884  
**Publisher:**  Girls’ Friendly Society Associates’ Journal and Advertiser. March 1884: 34-35   
**Format:** Article in Journal  

### “The Literature Department.”   The Girls’ Friendly Society. Sixth Winchester Diocesan Meeting.  {#305}

**Date:** 1882  
**Publisher:** Winchester: Warren & Son. October 1882: 41-42  
**Format:** article in conference proceedings  



### “The difficulty of obtaining places for our younger members. By Miss Yonge.” The Girls’ Friendly Society. Sixth Winchester Diocesan Meeting.  {#304}

**Date:** 1882  
**Publisher:** Winchester: Warren & Son. October 1882: 29-31   
**Format:** paper in conference proceedings  



## Non-fiction, art criticism

### \'Conversation on Pictures, A\' by C. M. Yonge {#282}

**Date:** 1882  
**Publisher:** MP (June 1882) 586-90  
**Format:** Article in Journal  

It describes her impressions of the Royal Academy Summer Exhibition of 1882.

### \'Thoughts on Pictures\' {#301}

**Date:** 1853  
**Publisher:** <i>Magazine for the Young</i> (March 1853-October 1856)  
**Format:** Article in Journal  

There is a fictional frame story into which the descriptions of pictures are fitted.

## Non-fiction, biographical article

### \'Easter-tide at Hursley (1866)\' {#297}

**Date:** 1866  
**Publisher:** MP (May 1866) 385-91  
**Format:** Article in Journal  

Obituary of the Rev.

John Keble.

### \'John Keble\' {#268}

**Date:** 1888  
**Publisher:** <i>Atalanta</i> (May 1888) 466-71  
**Format:** Article in Journal  

## Non-fiction, biography

### \'Biographies of Eminent Anglicans\' {#358}

**Date:** 1890s  
**Format:** MS Bodleian Library, unpublished  

CMY contributed to a series of short biographies of Anglican saints at the behest of the Rev. [J. F. W.

Bullock](../persons.html#221), Rector of Radwinter.

In 1902 he finally published the first three volumes of a projected six volume work called Daily Lections for every Morning and Evening throughout the Year (London: Rivington 1902).

Volume V of this work, described in his preface, was to have consisted of \'Lections on Anglican Worthies, arranged as additional Readings for Sunday\'.

These \'Biographies of Eminent Anglicans\' exist in MS and are catalogued under that name among the Bullock papers in the Bodleian Library, Oxford, but were never published, since no more of the Daily Lections ever appeared.

## Non-fiction, criticism

### Introduction to John Keble, The Christian Year {#351}

**Date:** 1894  
**Publisher:** London: Macmillan  
**Format:** Book  

This appeared in the \'Golden Treasury Series\'.

## Non-fiction, historical reference book

### Deacon\'s Book of Dates {#269}

**Date:** 1888  
**Publisher:** London: C.W.Deacon & Co  
**Format:** book  

## Non-fiction, history

### History of France {#353}

**Date:** 1878  
**Publisher:** Macmillan  
**Format:** Book  

This appeared in the \'History Primers\' series edited by J. R.

Green.

It had eight chapters, whereas the work of the same title, published in 1879, which CMY contributed to the \'Historical Course for Schools\' edited by E. A.

Freeman, had ten chapters.

The latter was also aimed at older children.

### Note to \'The Canterbury Relics\' {#277}

**Date:** 1888  
**Publisher:** MP (April 1888) 369  
**Format:** Article in Journal  

### \'Church of the Holy Trinity, Winchester\' by C. M. Y. [No. 11 in the Cathedral Sketches series] {#279}

**Date:** 1857  
**Publisher:** MP (March 1857) 303-18  
**Format:** Article in Journal  

## Non-fiction, literary criticism

### Review of Vanity and Vexation {#352}

**Date:** 1899  
**Publisher:** <i>The Guardian</i>  
**Format:** Article in Journal  

Referred to in a letter to Christabel Coleridge, October 1899, and presumably published about that time.

### \'Conversation on Books, A\' {#280}

**Date:** 1881-1890  
**Publisher:** MP  
**Format:** Articles in Journal  

This series of articles, consisting of a conversation about recent publications, ran frequently from January 1881 to June 1890.

By no means all the articles were written by CMY, for some are signed by others.

However, many are attributed to the Editor, and others include \'Arachne\' a character she assumed in dealings with the Spiders and who voices her opinions.

### \'George Eliot and her Critics\' By the Editor and the author of \'Charles Lowder\' [Maria Trench] {#286}

**Date:** 1885  
**Publisher:** MP (May 1885) 471-495  
**Format:** Article in Journal  

### \'Hackneys\' {#287}

**Date:** 1892  
**Publisher:** MP (October 1892) 413-417  
**Format:** Article in Journal  

The article discusses novel-writing cliches.

### \'Literature for Mothers and Children\' by C. M. Yonge {#263}

**Date:** 1894  
**Publisher:** <i>Mothers in Council</i> 4:13 (January 1894) 49-60  
**Format:** Article in Journal  

### \'My Reading\' By the Editor {#255}

**Date:** 1892  
**Publisher:** <i>Mothers in Council</i> 2:5 (April 1892) 87-94  
**Format:** Article in Journal  

### \'Seed time at Oxford\' {#296}

**Date:** 1891  
**Publisher:** MP (May 1891) 495-502  
**Format:** Article in Journal  

This is a review of Anne Mozley\'s edition of Newman\'s early correspondence and of R. W.

Church\'s The Oxford Movement.

## Non-fiction, natural history

### Conchology articles {#271}

**Date:** 1894-7  
**Publisher:** Monthly Packet  
**Format:** Articles in Journal  

This series of articles on shells, published without any overall title, consisted of the following:
\'The Sailors who Swim from the Head’ MP (September 1894) 310-7
‘Ancient Dyers’ MP (June 1895) 704-11
‘Marble Makers’ MP (September 1895) 331-6
\'Cameos and Porcelain\' MP (March 1896) 317-322
‘Snails’ MP (June 1896) 691-6
‘Venus and Hearts’ MP (March 1897) 324-7
‘The Sluggish Race’ MP (June 1897) 642-7
‘Bores and Borers’ MP (August 1897) 182-8.

### \'Householders\' {#357}

**Date:** 1856-1860  
**Publisher:** <i>Magazine for the Young</i> (January 1856-August 1860)  
**Format:** articles in journal  

A series of articles on shells.

## Non-fiction, obituary

### \'In memoriam Anne Mozley\' By the Editor {#272}

**Date:** 1891  
**Publisher:** MP (September 1891) 341  
**Format:** Article in Journal  

## Non-fiction, reminiscences

### \'Lifelong Friends\' {#292}

**Date:** 1894  
**Publisher:** MP (December 1894) 694-8  
**Format:** Article in Journal  

Reprinted in Battiscombe and Laski, 181-4.

### \'Real Childhood- My Play Times, A\'  {#257}

**Date:** 1892  
**Publisher:** <i>Mothers in Council</i> 2:8 (October 1892) 204-10  
**Format:** Article in Journal  

### \'Real Childhood- the Teens, A\' by C. M. Yonge {#258}

**Date:** 1893  
**Publisher:** <i>Mothers in Council</i> 3: 9 (January 1893) 15-21  
**Format:** Article in Journal  

## Non-fiction, report on submissions

### \'Arachne\'s Speech\' {#275}

**Date:** 1874  
**Publisher:** MP (Christmas 1874) 1-3  
**Format:** Article in Journal  

## Non-fiction, theology

### \'Doctrine and Practice\' by C. M. Yonge {#266}

**Date:** 1895  
**Publisher:** <i>Mothers in Council</i> 5:19 (July 1895) 151-157  
**Format:** Article in Journal  

## Non-fiction, theology, history

### \'Lectures on Church History, given at Winchester\'  by the Editor {#290}

**Date:** 1889  
**Publisher:** MP (January 1889-August 1890)  
**Format:** Articles in Journal  

These articles, which appear as both \'Lectures on church history\' and \'Lectures on English church history\' appeared in two series.

It is not clear who the original audience in Winchester were.

## Non-fiction, translation

### \'One Tragedy averted by Another\' {#300}

**Date:** 1880  
**Publisher:** MP (May 1880) 499-510  
**Format:** Article in Journal  

This is described as \'abridged from the French [of Emile Souvestre] by Charlotte M.

Yonge\'.

## Non-fiction; philology

### \'Polyglott Parsing\' {#348}

**Date:** 1869-1870  
**Publisher:** <i>MP</i> (July 1869-August 1870)  
**Format:** articles in journal  

## Other

### Historical Poetry see Historical Ballads {#270}

**Date:** 1883  

## anthology

### The Daisy Chain Birthday Book Gathered by Eadgyth {#355}

**Date:** 1885  
**Publisher:** London: Walter Smith  
**Format:** Book  

## fiction

### Buy a Broom {#354}

**Date:** 1880  
**Publisher:** Rochester NY: Fitch  
**Format:** Book  

This is am American reprint, possibly pirated. \'Buy a Broom\' has not been identified, but \'Kaspar\'s Summer Dream\' MP (Christmas 1876) 16-32, and \'Early Dew, or, the Boy Bishop\' MP (Christmas 1878), 6-20, were certainly by CMY.

## literary criticism

### Review of John Inglesant {#346}

**Date:** 1880?  
**Publisher:** <i>Guardian, The</i>  
**Format:** Article in Journal  

CMY refers to reviewing John Inglesant in The Guardian in a letter to Sir Walter Besant (?1899).

### \'paper on boy literature\' {#307}

**Date:** 1865  
**Publisher:** <i>Literary Churchman</i>  
**Format:** Article in Journal  

Mentioned to Alexander Macmillan and not yet identified.

## non-fiction, history

### article on French history {#350}

**Date:** 1892?  
**Publisher:** Cassell?  
**Format:** article in journal  

Letters to Arthur John Butler, then working for Cassell, suggest that CMY contributed an article on French mediaeval history to one of their journals in 1892.

## non-fiction, review

### \'Charles Kingsley\' by C. M. Yonge {#278}

**Date:** 1891  
**Publisher:** MP (September 1891) 283-290  
**Format:** Article in Journal  

## obituary

### Obituary of Anne Sturges Bourne {#349}

**Date:** 1891  
**Publisher:** possibly in <i>The Guardian</i>, perhaps 18 or 25 December 1891?  
**Format:** article in journal  

## theology

### Questions on the Catechism. Reprinted from The Monthly Paper of Sunday Teaching. {#253}

**Date:** 1869  
**Publisher:** London: J. and C. Mozley  
**Format:** book  
**Serialization:** The Monthly Paper of Sunday Teaching.  

CMY refers to this among her own works in a letter to Macmillan, so although the book is anonymous, and not listed by Coleridge, the attribution seems safe.

It is listed, undated, by Battiscombe and Laski as owned by a member of the CMY Society.

## translation

### \'Harvest Home in Normandy\' Translated by the Author of the \'Heir of Redclyffe\' from the French of Mde de Witt nee Guizot in Warne\'s Home Annual {#347}

**Date:** 1868  
**Publisher:** London: Warne  
**Format:** story in collection  

Warne\'s Home Annual ed.

Laura Valentine

## verse

### \'Annunciation, The\' by C.M.Yonge {#260}

**Date:** 1893  
**Publisher:** <i>Mothers in Council</i> 3:10 (April 1893) 65-67  
**Format:** Poem in Journal  

### \'Arachne\'s Farewell\' signed C. M. Y {#274}

**Date:** 1887  
**Publisher:** MP (April 1887) 394  
**Format:** Poem in Journal  

### \'The Little Maid\'s Text Book\' {#308}

**Date:** 1880  
**Publisher:** <i>Friendly Leaves</i> (December 1880), 268  
**Format:** poem in journal  

The poem is signed C. M.

Yonge

