---
title: "Institutions and Other References"
---

This page contains information about institutions, organizations, and other entities mentioned in Charlotte Mary Yonge's letters.

## organisation

### Cambridge University Press {#263}

Publishing company.

### Parker and Son {#152}

later Parker, Son and Bourn, publishers

## organization

###  Association for Promoting the General Welfare of the Blind {#1}

This charity was founded by Elizabeth Gilbert (1826–1885) in 1854.

Its archives are held by the London Metropolitan Archives.

Mentioned 3 June 1863.

###  Church of England Society for Providing Homes for Waifs and Strays {#2}

The Waifs and Strays' Society was founded in 1881 by Edward de Montjoie Rudolf (1852 -1933).

There is an interesting history at http://www.hiddenlives.org.uk/articles/history.html The organization survives as The Children’s Society, see http://www.childrenssociety.org.uk/

###  Great Ormond Street Hospital {#3}

A children’s hospital was founded in Great Ormond Street in 1852.

Individuals and groups could sponsor beds for sick children.

See Nicholas Baldwin, ‘The History of GOSH: The Whole Story’ at http://www.ich.ucl.ac.uk/about_gosh/gosh_history/

###  Huggens College {#4}

This was an Anglican charity and almshouse, founded by John Huggens in 1844.

Now Huggens College Retirement Community, it has a website at http://www.huggenscollege.org/

###  Keble College, Oxford {#5}

A college at Oxford opened in Keble’s memory, with the idea of widening and cheapening access to Oxford University, and bringing up a new generation of High Church clergymen. CMY attended the opening ceremony of its new buildings in 1876.

For the college’s early and subsequent history see http://www.keble.ox.ac.uk/about/past/

###  Lady Margaret Hall {#6}

Founded as a hall for women students in 1879, with Elizabeth Wordsworth as its Lady Principal, it became a college of Oxford University in 1959.

See www.lmh.ox.ac.uk

###  Newnham College {#7}

Founded as a hall for women students in 1871, and now a college of Cambridge University.

There is a history by Gillian Sutherland on its website at http://www.newn.cam.ac.uk/about-newnham/College-History/History/content/History-of-the-college

###  Norwich Union Insurance Company {#8}

Founded in 1797, the firm is now part of Aviva, see www.aviva.co.uk

###  Orthopaedic Hospital {#9}

The Royal National Orthopaedic Hospital, originally called the Infirmary for the Cure of Club Foot and other Contractions, and later the Orthopaedic Institution, was founded in 1838 and opened at Bloomsbury Square in 1840.

Its archives are in London Metropolitan Archives.

See http://www.rnoh.nhs.uk/about-the-rnoh/history-the-rnoh.

###  Otterbourne Penny Club {#10}

Mentioned in letter no 42. CMY mentions in Old Times at Otterbournethat a lending library for poor people was also run through the Penny Club with books originally given in memory of James Yonge by his grieving father the Rev.

John Yonge: ‘In 1834 their father gave what made, as it were the second foundation of the Lending Library, for there were about four-and-twenty very serious books, given in Archdeacon Heathcote’s time, kept in the vestry at the old Church.

They looked as if they had been read but only by the elder people who liked a grave book, and there was nothing there meant for the young people.

So there were a good many new books bought, and weekly given out at the Penny Club, with more or less vigour, for the next thirty years or so.’ The Club was evidently still going in 1870, when Mary Yonge seems to have taken over her sister Anne’s subscription of 2/2.

###  Sackville College {#11}

This is an almshouse in East Grinstead, founded in 1609, of which the Rev.

Dr.

John Mason Neale was Warden.

###  Sandwell Home {#12}

Founded in 1858 as Sandwell Hall Home for Widows and Orphans, Birmingham, by Laetitia Frances Selwyn (1807-1886), sister of the Rt.

Rev.

George Augustus Selwyn, it combined the functions of a convalescent home and an industrial school for the training of domestic servants.

Gentlewomen of small means lived in the Home and took responsibility for the supervision of the inmates.

Yonge introduced a proposal to establish a not dissimilar institution in the conclusion to The Clever Woman of the Family.

Selwyn is mentioned as training governesses (perhaps also in the Home?) and not letting them be paid less than £60 p.a. (23 March 1872).

The Home was in a large country house near Birmingham, donated by the Earl of Dartmouth.

###  St. Augustine’s College {#13}

This was a college for missionaries in Canterbury, founded in 1845, which survived until 1967.

The Warden 1880-1902 was the Rev. G. M.

Maclear.

Its buildings are now occupied by the King’s School, Canterbury, and its archive is held by Canterbury Cathedral Archives.

###  St. Hugh’s College {#14}

This was founded in 1886 as St.

Hugh’s Hall, for women students who were too poor to afford Lady Margaret Hall.

Its first principal was Annie Moberly.

It became a college of Oxford University in 1959.

Its website is www.st-hughs.ox.ac.uk

###  St. John’s College, Hurstpierpoint {#28}

This was one of the Woodard schools, founded to provide good cheap education for the middle classes.

Alice Coleridge lived there with her sister and brother-in-law, the Rev.

Edward Clarke Lowe, headmaster 1850-73.

The school’s website is http://www.hppc.co.uk/index.asp

###  St. Mark’s College, Chelsea {#66}

This was a training college for elementary schoolteachers, founded in 1841.

Its first head was the Rev.

Derwent Coleridge, son of the poet and father of Christabel Coleridge, who worked there until 1864.

The music teaching there was provided by his friend Thomas Helmore, and transformed English church services.

It is mentioned by the Rev.

Derwent Coleridge (15 November 1873).

###  St. Stephen’s Native Girls School {#15}

On the history of this school see Joan C.

Stanley, 'Kissling, Margaret 1808 - 1891'.

Dictionary of New Zealand Biography, www.dnzb.govt.nz/ Mentioned in no 87.

###  Surgical Aid Society {#16}

The Royal Surgical Aid Society was founded in 1862 to provide the poor with artificial limbs, trusses, ear trumpets, leg irons and boots.

With the institution of the NHS it began to run old people’s homes, and is now called AgeCare, see www.agecare.org.uk

###  Universities Mission to Central Africa {#42}

This was the charity, founded in 1858, which sent the Rt.

Rev.

Charles Frederick Mackenzie to the Zambezi.

It merged with the SPG in 1961.

###  Winchester College {#50}

A boys’ public school founded in 1382 by William of Wykeham, Bishop of Winchester.

In CMY’s youth it consisted of seventy scholars (chosen until 1855 by patronage rather than competition) living with the Second Master in College, and about 100 fee-paying boys living in ‘Commoners’ under the supervision of the Head Master.

There were 120 commoners on George Moberly’s arrival as Head Master in 1836, and numbers had declined by the 1850s.

Boarding houses did not exist until the 1850s.

The Warden of Winchester College, the head of the whole institution, who lived in lodgings on the site, was the Rev.

Robert Speckott Barter (1790-1861), a much-loved figure.

Moberly resigned and was succeeded in 1867 by his son-in-law George Ridding.

On Barter’s death in 1861 he was succeeded by the Rev.

Godfrey Bollis Lee (1817-1903).
http://www.winchestercollege.co.uk/history-of-the-college and ‘Winchester College and Commoners; Blackwood’s Magazine 95 (January 1864) 66-92.

###  Winchester Girls’ High School {#51}

This was a secondary school for girls founded in Winchester in 1884.

The prime movers in its foundation were Anna Rachel Bramston and her friend Amélie Claire Leroy. CMY was a member of the school’s Council of Management from the foundation.The school changed its name to St.

Swithun’s School in about 1930 and moved to the present site just outside the city in 1931.

See http://www.stswithuns.com/school_history.htm

### Band of Mercy {#265}

The Band of Mercy was an organization founded in 1875 to encourage kindness to animals.

### Bath Rheumatic Hospital {#189}

Founded as the Bath General Infirmary in 1742.

Now the Royal National Hospital for Rheumatic Diseases, see www.rnhrd.nhs.uk

### Belgrave Hospital for Children, The {#17}

This organisation, founded in Cumberland Street, Pimlico, in 1866, is referred to in MP (January 1871) and in a letter to an unknown woman (1 August ?1871).

It moved to Kennington in the twentieth century, merged in 1948 with King\'s College Hospital, which retains its archives, and was closed in 1985.

### Bell and Daldy {#135}

publishers.

Founded in 1839 by George Bell, it became Bell and Daldy in 1856, and after Daldy departure in 1873, George Bell and Sons.

### Blackwood {#214}

publisher

### British Institution, The {#18}

The British Institution for Promoting the Fine Arts, which flourished 1805-1867, had exhibition galleries at  52 Pall Mall.

### Cassell {#216}

publisher

### Church Army, The {#231}

### Church Missionary Society, The {#19}

This was an important missionary society, founded in 1799, whose supporters came from the Evangelical wing of the Church of England.

Its archives 1799-1959 are held by the University of Birmingham and have been partly published on microfilm.

The organisation still exists and is called the Church Mission Society.

### Church of England Women\'s Help Society, The {#222}

Founded in 1879.

### Community of St Michael and All Angels, Bloemfontein {#219}

This was a nursing sisterhood founded in 1874.

It still (2010) exists.
http://communities.anglicancommunion.org/communities/detail.cfm?ID=28&types=byname

### Community of St. John the Baptist, Clewer, The {#20}

In 1849 the Clewer House of Mercy was founded in Windsor by Mariquita Tennant, as a refuge for repentant prostitutes.

In 1852 this work was taken on by Harriet Monsell and the Rev.

Thomas Thellusson Carter, Rector of Clewer, who founded a group of Sisters of Mercy.

The organisation still exists as an Anglican sisterhood, and its website is http://www.gjm61.dial.pipex.com/

According to A.M.

Allchin, The Silent Rebellion: Anglican Religious Communities 1845-1900. (London: SCM Press, 1958), it became \'one of the most characteristically Victorian and nineteenth-century of all the sisterhoods\' undertaking as its primary work the restoration of \'fallen women\'.

### Community of St. Mary the Virgin, Wantage, The {#21}

This sisterhood was founded by the Rev. [W. J.

Butler](../persons.html#244) in 1848. CMY became an Associate, as did many members of the Gosling Society.

The community still exists and its website is http://orders.anglican.org/arcyb/csmv.html

### Dalziel Bros. {#163}

engravers

### Daniel Appleton and Co. {#142}

American publisher, based in New York

### Darton {#109}

### Dr. Barnardo\'s Homes {#115}

Founded by Thomas Barnardo in 1867, this organization ran orphanages and did welfare work among children.

See http://www.barnardos.org.uk/who_we_are/history.htm

### Earlswood Asylum for Idiots, The {#38}

The Rev.

Dr.

Andrew Reed had founded an ‘asylum for idiots’ in Highgate in 1847.

New premises were built in Earlswood (near Redhill).

The first Medical Superintendent there was Dr.

John Langdon Down who developed a compassionate and radical new model of care for the inmates, and who first identified the condition which has now become known as ‘Down’s Syndrome’.

This organization was later known as the Royal Earlswood Hospital.

It was closed in 1997.

Its archives are held by Surrey History Centre.

### Ecclesiological Society, The {#131}

Founded as the Cambridge Camden Society in 1839, it changed its name to the Ecclesiological Society in 1845.

It acted as a pressure group to encourage the use of Gothic architecture in church buildings, and research and preservation of mediaeval buildings, mainly through its journal The Ecclesiologist and other publications.

See James White, The Cambridge Movement: The Ecclesiologists and the Gothic Revival (Cambridge: Cambridge University Press 1962).

The society still exists.

Although CMY and her circle were much influenced by the ideas about design propagated by the society, they were not totally in sympathy with the movement; in The Pillars of the House Clement comments unsympathetically of a local antiquarian clergyman that he minds his ecclesiology more than his ecclesia.

### English Church Union, The {#22}

This organisation was founded in 1859 in protest at the government legislating on church matters.

It supported many of those accused of ritualism under the Public Worship Regulation Act (1874).

The organisation changed its name to the Church Union in 1933, and still exists as a High Church lobby group within the Church of England, currently (2009) resisting the arrival of women bishops.

Some archives are held by Lambeth Palace Library.

Its website is http://www.churchunion.co.uk/

### George Allen and Sons {#256}

A publishing firm founded by George Allen (1832-1907) in 1871.

### George Routledge & Sons {#258}

Publisher

### Girls\' Friendly Society Reading Union {#211}

### Girls’ Friendly Society, The {#23}

This organization was founded by Mary Elizabeth Townsend in 1875, as a response to the forlorn condition of young women working away from home, usually as servants and shop assistants.

It established a network of diocesan societies, within which Associates (ladies) provided support and facilities for Members (girls).

These were of very various kinds, including lodging, education, recreational facilities, convalescent homes, circulating libraries and employment bureaux. CMY was much involved in its work from its earliest years, and published a rare pamphlet, THe Girls\' Friendly Society: A Short Account of its Working in the Diocese of Winchester to the end of the year 1878 (1879), a copy of which is MS Lambeth Palace Library Tait 268 ff224-9.

At that date the diocese had 3,057 members and CMY was in charge of the circulating library.

The tribulations of those trying to administer the organization were amusingly described by CMY in MP in 1882 \'A Conversation on the Girls\' Friendly Society\'.

It ran The Girls\' Friendly Society Associates\' Journal for the Associates and Friendly Leaves for the Members. CMY’s kitchen maid, Rosina Dewsall, took the exams of the Girls’ Friendly Society Reading Union.

Its archive is held by the Women’s Library.

Brian Harrison, \'For Church, Queen and Family: The Girls\' Friendly Society 1874-1920\' Past and Present 61 (1973) 107-138 is informative.

The charity still exists and its website is http://www.gfsplatform.org.uk/

### Girton College {#201}

Founded in Hitchin in 1869 and moved to Cambridge in 1873.

### Griffith and Farran {#233}

publisher

### Groombridge {#148}

Publisher

### Guild of St. Alban, The {#24}

The Guild of St.

Alban the Martyr was founded in 1851 by Shirley Fielding Palmer and still existed in 1960; it consisted of male lay fellows who assisted clergy in social work; it also had a sisterhood; some archives are in London Metropolitan Archives.

### Hampshire Blind School, The {#25}

A report of its AGM in the Hampshire Telegraph (13 February 1897) speaks of the 33rd annual report, which would put its origin around 1864.

It seems to have been in Southsea.

### Harper & Bros {#248}

American publishers, founded in New York in 1817.

It is now (2011) part of HarperCollins, a division of News Corporation.

Its website is http://www.harpercollins.com/

### Heinemann {#230}

publisher

### Henry S. King {#242}

publisher

### Hindu College, Calcutta {#175}

The Hindu (later Presidency) College Calcutta, were in correspondence with CMY about the republication of her Landmarks of History, which was used as a textbook during the 1860s.

### Hoare\'s Bank {#169}

### Hogg {#159}

publisher

### Home for Incurable and Infirm Women, The {#26}

Mentioned 26 April 1864.

This was run by [Louisa Twining](../persons.html#1427), and operated from 21 Great Ormond Street.

Twining described its work in an article in MP (April 1864) 437-449; and further in a letter MP (August 1869) 205-6.

The latter gives the number of inmates as 27.

Some correspondence of the Charity Organization Society with an outfit of this name, running a home for respectable women in reduced circumstances at Whetstone, is held by the London Metropolitan Archives.

### Hospital of St. Cross and Almshouse of Noble Poverty, The {#130}

### Institution for the Employment of Needlewomen, The {#27}

This organization was the subject of articles in the Englishwoman’s Journal (1860) and the MP (August 1861).

### Isbister {#223}

publisher

### Jacob and Johnson {#187}

A Winchester bookseller, still (2010) in business as a stationer in the High Street, Winchester.

### Ladies\' Home, 21 Abbey Road, St. John\'s Wood, The {#191}

This charitable institution was described by [Caroline Alcock](../persons.html#19) in \'The Ladies\' Home\' MP (August 1867) 179-80.

### Little Sisters of the Poor, The {#197}

The Little Sisters of the Poor was a Roman Catholic charitable organization founded in France in 1839.

### London Library, The {#29}

This private circulating library was founded in 1841 and has been in St.

James’s Square since 1845. CMY joined in the early 1860s.

It still exists, though it does not have records of books borrowed by nineteenth-century members; see http://www.londonlibrary.co.uk/aboutus/history.htm

### Longman {#153}

publisher

### Macmillan and Son {#111}

### Marcus Ward and Co. {#236}

publisher of books and greetings cards 1802-1899.

### Masters {#112}

### Melanesian Mission, The {#30}

This organization, originally the Melanesian Mission Fund, was founded in 1854 to purchase the Southern Cross.

Its website today is www.melanesia.anglican.org/mmhome.html.

The British Museum holds an archive of photographs of the mission which it is putting online at www.britishmuseum.org in 2010. CMY’s was deeply interested in missions, and she was especially devoted to the idea of evangelizing the South Seas.

She gave the mission the profits of her novel [The Daisy Chain](../persons.html#24), in which an episode takes place in Melanesia.

Her [biography](../books.html#102) of Bishop Patteson brought her into contact with several members of the mission.

### Molyneux Female Blind Asylum {#166}

This Protestant charity seems likely to be the Dublin blind asylum CMY refers to.

### Mothers’ Union, The {#31}

This was founded by Mary Elizabeth Sumner in 1885. CMY became the first editor of Mothers in Council, the journal aimed at the upper-class ladies who supported it.

### Mozley {#108}

### Mudie\'s Circulating Library {#137}

Established in London in 1842.

### National Association for Promoting Freedom of Public Worship {#194}

Its full names was the National Association for Promoting Freedom of Public Worship in the Church of England by the Abolition of the Pew System and the General Adoption of the Weekly Offertory.

The President was the Hon.

Colin Lindsay; Robert Brett was one of the Hon.

Secretaries.

### National Society, The {#32}

The National Society for Promoting the Education of the Poor in the Principles of the Established Church, now National Society, Church of England, for Promoting Religious Education.

This charity, which was enormously influential in the Victorian educational world, was founded in 1811, and started or supported a very large number of Anglican schools for the working classes.

It also published textbooks and fiction, often used for school prizes, and CMY wrote many children’s books for them.

See http://www.natsoc.org.uk/society/history/

### Nelson {#226}

publisher

### Nutt and Wells {#178}

Probably the same as D.

Nutt, bookseller of College Street, Winchester.

### Orphans Home, Plymouth, The {#33}

This was founded by Lydia Sellon in the 1840s as part of the wide-ranging programme of her sisterhood, the Devonport Sisters of Mercy, later the Society of the Most Holy Trinity.

### Otterbourne School {#107}

This institution, now Otterbourne Church of England Primary School, has its origins in the school founded by CMY’s mother in about 1826 ‘the room built of cement, with two tiny ones behind for kitchen and bed- room for the mistress, and a brick floor’ (John Keble’s Parishes, 95).

The schoolmistress, however, could not keep the boys in order, and so a separate boys’ room was built near the church.

In 1838, when Otterbourne church was rebuilt on a new site, a boys’ school was ‘built on a corner of the ground intended as churchyard, and a larger room added to the girls\', the expense being partly defrayed by a bazaar held at Winchester, and in part by Charlotte Yonge\'s first book’ (John Keble’s Parishes, 103).

The National Society was also involved, and the school was sometimes called Otterbourne National School.

In 1871 a new girls’ school and a master’s house was built to commemorate the service of the Rev.

William Bigg Wither, curate of Otterbourne, and the school was moved ‘under government’ (Coleridge, Life, 263).

The school’s archives 1872-1979 are held by Hampshire Archives. A pamphlet by Lloyd Woodcock, Charlotte Yonge and Otterbourne Girls\' and Infants\' School, was published by Eastleigh and District Local History Society in 1987.

For the school website see http://www.otterbourneprimaryschool.com/

### Parents\' Educational Union, The {#34}

This organization (later the Parents\' National Education Union) was established in Bradford in 1887 by Charlotte Mason (1842-1923).

It was intended to encourage and support those educating their children at home, and prospers to the present day. CMY deplored the fact that it was non-denominational.

### Perry Mason & Co. {#249}

American publisher, based in Boston.

### Phelps {#164}

printer

### Primrose League, The {#255}

A political organisation founded in 1883 to encourage support for the Conservative party and disbanded in 2004.

### Queen\'s College, Harley Street {#206}

### R & R Clark {#251}

An Edinburgh printing firm.

They were the printers of [Stray Pearls](../books.html#170) (1883).

### Reeves and Turner {#239}

publishers

### Religious Tract Society, The {#35}

This was an evangelical charity founded in 1799 which published devotional works on a very large scale.

Although CMY did not write for it herself many of her friends did.

After mergers it is now known as the United Society for Christian Literature; its archives are held by SOAS and have been published on microfilm.

### Richard Bentley and Son {#168}

publisher

### Richard Clay & Sons {#173}

printers

### Royal Academy, The {#141}

### Royal Hampshire Hospital, The {#36}

CMY refers (10 January 1872) to the publication of Edward Faithfull’s poems as likely to add to its funds.

Many of her friends were involved with fundraising for its construction and she herself was a subscriber.

### Royal Hospital for Incurables, The {#37}

This charity, founded in 1854, is now known as the Royal Hospital for Neuro-disability.

See www.rhn.org.uk

### Royal Literary Fund, The {#257}

A charitable fund for published authors and their dependents in financial need, founded in 1790.

### Royal Society for the Prevention of Cruelty to Animals {#243}

Founded in 1824

### Royal Victoria Hospital, Netley, The {#39}

This was a military hospital founded in 1856.

Its first governor was CMY’s friend Colonel [Richard Wilbraham](../persons.html#1515).

It survived until 1978 and is now a country park.

See http://www3.hants.gov.uk/hampshire-countryside/rvcp/history-rvcp.htm
and Anne Summers, \'Ministering angels\'.

### Sanger\'s Circus {#117}

### Saunders and Otley {#144}

publisher

### Saville & Edwards {#162}

printers, of Chandos St., Covent Garden.

### Scribner {#204}

American publisher

### Skeffington {#110}

### Smith, Elder and Co. {#238}

publisher

### Society for the Promotion of Christian Knowledge, The {#40}

This charity, founded to promote Christianity at home and abroad in 1698, has long had and still has a substantial publishing arm. CMY planned to get it to publish a series of county histories (3, 5 November 1860).

Unlike many of her friends, she did not write for it.

Its archives are held in Cambridge University Library.

See http://www.spck.org.uk/about-spck/archives/

### Society for the Propagation of the Gospel, The {#41}

Founded in 1701, the SPG was the most congenial to High Church Anglicans of the missionary societies, the Church Missionary Society, being evangelical Anglican, and the London Missionary Society being non-denominational and including Nonconformists.

The SPG archives are held in Lambeth Palace Library.

It is now the United Society for the Propagation of the Gospel, having merged with the Universities Mission to Central Africa in 1961.

See http://www.uspg.org.uk/ Mentioned, No 64, No 82.

### Society of All Saints’s Sisters of the Poor, The {#43}

This sisterhood was founded in London in 1851 by Harriet Brownlow Byron, with the support of the Rev.

Upton Richards.

See http://orders.anglican.org/arcyb/assp.html

### Society of Authors, The {#44}

This professional society was founded by the novelist [Walter Besant](../persons.html#1652) in 1884 to protect the rights of authors.

It carries on this work today; see http://www.societyofauthors.org/about_the_society/index.html

### Society of St. Margaret, East Grinstead, The {#45}

This was an Anglican sisterhood founded by the Rev.

Dr.[ J. M.

Neale](../persons.html#1078) in 1855.

It still exists.

This sisterhood arose out of the need for nursing in the cottages of a scattered parish and home nursing was the first work of the sisters.

The rules were based on those of the Clewer sisterhood.

### Society of Watchers and Workers, The {#47}

This was founded in 1879 by [Edith Jacob](../persons.html#749) (1836-1918), who became seriously ill early in 1868; her disease was described as \'congestion of the spine\' and she spent most of the rest of her life in varying degrees of invalidism.

During this first attack, according to her brother, she reflected on the contribution which invalids could make to the life of the Church.

The result of this was a paper \'Thoughts on invalid life\' published at the suggestion of CMY and reviewed by her in the Church Quarterly Review.

This resulted in the foundation of the \'Society of Watchers and Workers\', an organisation to which Edith Jacob devoted her energies for the rest of her life, and of whose privately printed journal, the Watchword, she was editor.

The activities of the society, which included support for homebound \'invalids of the cultured classes\', enabling them to direct their energies in prayer and fundraising for charitable objects, are described in more detail in Kathleen Alice Orr, Letters (1907, 1909), a privately printed memoir of a deceased watcher with a memoir by Edith Jacob.

The Watchers were especially keen on missions.

### Society of Women Writers and Journalists, The {#234}

Founded in 1894.

See its website at http://www.swwj.co.uk/history.htm

### Society of the Most Holy Trinity, The {#46}

This was the sisterhood founded by [Lydia Sellon](../persons.html#1294) in Plymouth as the Devonport Sisters of Mercy, which took this name on merging in 1856 with the Park Village Sisterhood of the Holy Cross (founded 1845).

They were accused in 1849 by the Devonport Telegraphof adopting popish practices, see ‘The Sisters of Mercy at Devonport, Inquiry by the Bishop of Exeter’, Daily News (17 February 1849).

### Spider Society, The {#116}

In January 1873 the last page of the Monthly Packet included an announcement:

TO OUR READERS

COBWEBS OR, THE MONTHLY PACKET ESSAY SOCIETY.

Two Questions, to be Answered in Writing, on History, Literature, Art, or Science, will be proposed in each Number.

Answers to be directed to ARACHNE, CARE OF THE EDITOR OF THE MONTHLY PACKET.

If 200 of our Subscribers will send a Shilling’s worth of Postage Stamps to the above Address, we will print the best one of the Answers to each Question, provided it does not exceed 2000 words, at the end of the NOTICES TO CORRESPONDENTS in the Number for the second month after the Questions come out.

We do not offer a prize, as it is impossible to fix any limit as to age; but we hope sometimes to give a few words of help or criticism.
______________

SPIDER QUESTIONS

Give an account of the history and derivation of the words -- Vaunt, Brag, Bombast, and Rhodomontade.

Describe an Oak-leaf -- its growth, structure, and historical and poetical associations.

Essay societies of this kind, whether associated with a magazine or not, were tremendously popular at this period.

The background to Yonge’s foundation of the Cobwebs was her experience of running the Gosling Society between 1859 and 1877.

The MP Christmas number for 1872 had consisted (as Christmas numbers often did in those days) of a series of stories by divers hands with a link story.

In this case, the link story was the story of an essay society called ‘the Spiders’ ‘in graceful allusion to our being a fraternity of spinsters’.

The author of this story was perhaps Christabel Coleridge.

It gives an account, in fictional form, of a society which is plainly based on the Goslings.

The foundation, immediately afterwards, of the new Cobweb Society was undoubtedly moving what had been a private organization into a more public sphere.

When the Goslings were finally wound up in 1877 (after some years in which Yonge had been complaining about the quality of the work produced by recent members) the explanation which was given was that:

Having begun with 12 intimate friends & cousins who actually did 4 questions once a month it has come to only two once in two months & of those generally only one answered by a few - while there is little acquaintance between many[.] It seems therefore time to break it up, since there are other essay societies in plenty now and Mother Goose still superintends the Spiders.

The Spider essay society ran in MP until 1887, when it was wound up and CMY published a valedictory poem [\'Arachne\'s Farewell\'](../books.html#274) in the April issue.

### Spottiswoode {#183}

printers

### St. Andrew\'s College, Kohimarama {#139}

Founded by the Rev.

John Coleridge Patteson in 1859 at the place now called Mission Bay, Auckland, as a school for boys and girls from the South Sea Islands.

It was named after the church of St.

Andrew in The Daisy Chain and was built with CMY\'s donations from the profits of that novel.

However, it only lasted a short time in Auckland, which was too cold for the pupils, and removed to Norfolk Island.

The missionaries had second thoughts about the name.

The building is currently (2007) occupied by a cafe.

### St. John\'s College, Auckland {#138}

Founded as a school and theological college by the Rt.

Rev.

George Augustus Selwyn, Bishop of New Zealand, in 1844.

The website of the theological college is www.stjohnscollege.ac.nz. A picture of the buildings in 1862 drawn by Caroline Abraham iand now in the Alexander Turnbull Library is available at http://www.teara.govt.nz/en/auckland-places/13/4

### St. Michael\'s School, Bognor {#185}

St.

Michael’s, Bognor, later St.

Michael’s Petworth (closed in 1994), was founded by Mary Anne Rooper, and moved to Bognor in 1855.

Its headmistress was Lady Caroline Eliot, to whom there are a series of payments in CMY\'s bank account from 1856.

It may be that she paid a girl\'s school fees there.

St.

Michael\'s became one of the \'Woodard\' schools, under the superintendence of the Rev.

Nathaniel Woodard (1811–1891) who had founded a number of schools including St.

John\'s College, Hurstpierpoint, of which Alice Coleridge’s brother-in-law, the Rev.

Edward Lowe, was headmaster.

Lady Caroline retired shortly before her death in 1866 and was succeeded by Frances Wheeler who was headmistress until 1895.

### St. Peter\'s, Kilburn {#203}

### St. Thomas\'s Home, Basingstoke {#247}

This was the Diocesan Penitentiary for Friendless and Fallen Women. CMY sent them some of her books in 1878, to the care of the Rev.

Reginald Bigg Wither.

He was a nephew of the Rev.

William Bigg Wither, curate of Otterbourne, and he published a History of the foundation and of the chief incidents in the gradual establishment of St.

Thomas\' Home, Basingstoke, the Winchester Diocesan Penitentiary for Friendless and Fallen Women (Basingstoke: Jacob 1887).

### Thomas Constable & Co. {#136}

publishers

### Ticknor and Fields {#179}

American publisher.

They published the work of Henry Kingsley.

### W. F. Tillotson & Son {#260}

Publishers of syndicated fiction and newspapers.

### W. H. Smith and Son {#161}

### Ward, Lock & Co. {#235}

Publisher.

Founded in 1854 as Ward and Lock, it is now (2010) part of the Orion group.

### Wells, Gardner {#114}

publisher

### Wigram and Sons {#157}

shipbuilders.

They constructed the Southern Cross.

### William Clowes & Sons {#245}

printers

### Williams and Norgate {#165}

publisher.

They evidently acted as the London agents of Firma Tauchnitz of Leipzig.

### Winchester Diocesan Society for Higher Religious Education, The {#48}

### Winchester Female Refuge, The {#49}

The Hampshire Telegraph (23 January 1867) recorded that \'On Sunday last a sermon was preached by the Rev.

Dr.

Moberly, late head master of Winchester College, at the Church of Holy Trinity, in aid of the funds of the Winchester Female Refuge.’ It is mentioned in a letter to Edith Jacob (21 March 1867).

It is also found as the Government Female Refuge, Winchester and the Winchester Refuge for Fallen Women.

George Ridding and Josephine Butler seem both to have been interested in it.

The Winchester Refuge for abused women which exists today is not connected.

### Winchester Literary and Scientific Society {#208}

It was founded by the Rev.

Charles Alexander Johns in 1870. CMY was one of the earliest members.

### Winnington Hall School {#186}

This girls\' school was run by Margaret Alexis Bell, a friend of John Ruskin, who took a great interest in it.

### publisher {#215}

Cassell

## periodical

###   <i>Monthly Packet, The</i> {#52}

This monthly magazine was edited by CMY 1851-1890; edited by CMY jointly with C. R.

Coleridge 1891-3; edited by C. R.

Coleridge and A. D.

Innes 1894-9.

It was markedly High Church and aimed at a juvenile audience, mainly conceived of as girls in their teens, though in the early days CMY also hoped to make it entertaining to boys who had not yet gone to public school, and there is evidence that it was also read by adults of both sexes.

The magazine has been digitized in the series 19th Century UK Periodicals and is available at http://find.galegroup.com/ukpc/

###  <i>Atalanta</i> {#53}

This was a magazine for girls (1887-1896), edited until 1893 by L. T.

Meade, which CMY considered populist and trivial in comparison with the Monthly Packet.

She contributed to it ‘John Keble’ Atalanta (May 1888) 466-71. A conciliatory letter from Meade to CMY (MS Mrs Clare Roels, 4 September 1889) is evidently a reply to one in which CMY had complained of the ‘want of definite religion’ in the magazine.

###  <i>Aunt Judy’s Magazine</i> {#54}

This was a children’s magazine which ran 1866-1885.

It was edited by Margaret Gatty until 1873; from 1874-6 by her daughters Horatia Gatty and Juliana Ewing; from 1877-85 by Horatia Gatty.

###  <i>Barnacle, The</i> {#89}

This was a manuscript magazine circulating among members of the Gosling Society.

The surviving issues (incomplete series, 1863-1867)  are owned by Lady Margaret Hall, Oxford.

They are described by Julia Courtney, ‘The Barnacle: A manuscript magazine of the 1860s’, in The Girl’s Own: Cultural Histories of the Anglo –American Girl 1830-1915 ed.

Claudia Nelson and Lynne Vallone.

Arkansas and London, University of Georgia Press: 1994.

###  <i>British Quarterly Review, The</i> {#90}

Macmillan sent CMY a good review of The Dove in the Eagle’s Nest (4 July 1866).

###  <i>Cassell’s Magazine</i> {#55}

This magazine ran 1852-1934; Cassell’s also published several other magazines.

The editor 1874-94 was H. G. B.

Hunt.

Arthur Butler worked for Cassell’s c. 1890-4.

###  <i>Chambers’s Journal</i> {#56}

This journal was founded in 1832 as Chambers’ Edinburgh Journal and became in 1854 Chambers's Journal of Popular Literature, Science and Arts, under which name it ran until 1897. CMY refers to it in No 49 and also Nos 56, 124, 127.

###  <i>Children’s World, The</i> {#58}

This periodical was published by the Church Missionary Society (1895-1900).

###  <i>Christian Remembrancer, The</i> {#59}

This periodical had been published as a monthly magazine until 1844 when it was relaunched as a quarterly, at the height of the controversy over Newman’s conversion, as the organ of moderate Tractarian thought.

Its editor from 1841 the Rev.

William Scott (1813–1872), perpetual curate of Christ Church, Hoxton, and known as Scott of Hoxton; between 1844-55 he was joint editor with the Rev.

James Bowling Mozley.

It ran until 1868.

In 1853, John Duke Coleridge published ‘Miss Yonge’s Novels’, a largely favourable assessment which all the same led to his incurring the wrath of FMY and made his next visit to Otterbourne uncomfortable. CMY herself wrote several long articles for it in the 1860s, which she several times mentions in connection with attempts to have them published in a volume: on Elizabeth Sewell’s Principles of Education; on ghosts and folklore; on the Sanitary Commission in the American war; on Lord Seaton and his regiment; on Eugenie de Guérin; on Alexandrine de la Ferronays; and on the Life of Bishop Mackenzie.

###  <i>Churchman's Family Magazine, The</i> {#63}

This periodical seems to have run 1863-1873.

The publisher was Hogg.

The Clever Woman of the Family was serialized in it (January 1864-April 1865).

###  <i>Churchman\'s Companion</i> {#62}

This periodical, which ran 1847-1883, was published by Joseph Masters, and considered in the Yonges’ circle rather too controversial in its treatment of religious topics to be suitable for young people.

It thus inspired the foundation of the Monthly Packet. ‘Its tone was . . . extremely controversial, and it was given to insist more on the surface pecularities of the Church movement than the wiser members of that movement thought good.

The Dysons, and possibly others, suggested the putting forth of a magazine for young people, suited to the schoolroom rather than the village school, and which should avoid personal controversy as unsuited to the young.’ (Coleridge, Life 164). CMY’s story Henrietta’s Wish was serialized in it (January 1849-May 1850) and also her The Two Guardians (July 1850-February 1852).

The editor until 1858 was the Rev.

William Balmborough Flower.

He was followed by Masters\' partner until 1863, when Felicia Skene took over, editing it to 1880.

###  <i>Churchwoman, The</i> {#64}

Gertrude Ireland Blackburne was co-editor of The Churchwoman (1897-1905).

It may be the same as The English Churchwoman, which continued Our Paper : The monthly journal of the Church of England Women's Help Society and appears to have existed June 1883-December 1911.

###  <i>Constitutional Press</i> {#65}

This magazine, which ran 1859-60, was published by Saunders & Otley; they serialized Hopes and Fears.

###  <i>Cottagers' Monthly Visitor</i> {#67}

This was a periodical which ran 1821-1856, designed for working-class readers, in which the Rt.

Rev.

George Davys was much interested and to which he contributed. CMY mentions (5 December 1838) that her family had ‘hatched up amongst us’ some articles for it, which must have been among her earliest appearances in print.

###  <i>English Illustrated Magazine</i> {#68}

This was published monthly by Macmillan 1883-1913. CMY published The Armourer’s Prentices in it in 1884.

She wrote to G. L.

Craik (10 July 1884) protesting about the publication in it of Henry James’s ‘The Author of Beltraffio’on the grounds that it was calculated to ‘make sceptically inclined people averse from devout faith’.

###  <i>Events of the Month</i> {#69}

This periodical was advertised as Events of the Month: A Magazine of News, Literature, Science, and General Information; Designed for Youthful Readers to be published by John and Charles Mozley, starting January 1st, 1864.

Price sixpence.” It was edited by Henrietta Murray and ran from January 1864 to January 1865. CMY later described it to Macmillan (3 June 1864) as “a sort of school room Athenaeum”, and tried unsuccessfully to get him to take it over when the Mozleys abandoned it.(see Macmillan to CMY 17 January 1865). ‘Lost [sic] Heartsease Leaves’ was published in it in January 1865.

###  <i>Family Friend, The</i> {#70}

This magazine (1849-1921) was mentioned by CMY, letter no 56, as widely read in cottages.

See Charlotte Fell-Smith, ‘Philp, Robert Kemp Smith, ‘Philp, Robert Kemp (1819–1882)’, rev.

Stephen Roberts, Oxford Dictionary of National Biography, Oxford University Press, 2004.

###  <i>Friendly Leaves</i> {#71}

This was a periodical published by the Girls’ Friendly Society, and aimed at the working-class girls who were its members.

It ran 1876-1951, renaming itself first The G. F. S.

Magazine and then The Townsend.

Its first editor was Mary Elizabeth Townsend, the GFS\'s founder, and subsequently byAnne Mercier.

In 1885 Eliza Keary became editor, and was succeeded in 1890 by Henley I.

Arden, who was succeeded in 1899 by Christabel Rose Coleridge.

It was published quarterly until 1877 when it became a monthly magazine.

The charity also published The Girls\' Friendly Society Associates\' Journal aimed at the upper-class ladies known as ‘associates’ as opposed to ‘members’, and a quarterly magazine, at first entitled Friendly Work and then the Girls\' Quarterly, which was aimed at \'members\' who were rather better educated than those reading Friendly Leaves.

###  <i>Girls\' Friendly Society Associates\' Journal, The</i>  {#72}

This periodical (1883-1919) was aimed at the upper-class associates, not at the Members of the GFS, for whom the sister journals Friendly Leaves and Friendly Work existed.

Between 1881-3 it was entitled the Girls\' Friendly Society Advertiser.

It contains references to CMY\'s presence at meetings and comments by her, some letters from her (included in this edition) and articles signed by her.

An obituary of CMY, describing her GFS work, signed C. C. and probably the work of Christabel Coleridge, appeared in the issue for May 1901, p.75.

###  <i>Good Words </i> {#73}

Described by CMY as ‘so Scottish and Presbyterian’.

She wrote to Christabel Coleridge (11 August 1871) complaining that ‘respectable people’ could not be expected to read a love story by Matilda Betham-Edwards.

She advised Christabel (1 Jan 1872) to avoid writing for it.

Good Words was published from Jan 1860 to Apr 1911.

According to Mrs Gatty it paid much better than the MP: \'Why does an orthodox parson’s wife write for Good Words?

When orthodox magazines value her services at £1 per page and copyright reserved--instead of 2s.6d. (Monthly Packet !) --then you may wonder--but not till then.\' (Maxwell, Mrs.Gatty and Mrs.Ewing, 132)

###  <i>Great Grimsby Parish Magazine</i> {#74}

A letter (MS Bodleian Library 1 October 1883) to the Rev.

Charles Moor, who was curate of Great Grimsby 1882, suggests that she contributed a story from Langley Adventures to a magazine of some kind he was editing.

North East Lincolnshire Archives hold (their reference 1007/65-67) parish magazines for All Saints, Great Grimsby, 1887-1981, which might be the right one.

###  <i>Guardian, The</i> {#75}

This was a High Church weekly newspaper which ran 1846-1951, and is not to be confused with the daily newspaper formerly known as the Manchester Guardian which changed its name to The Guardian in 1959.

The High Church Guardian had been founded by a group of Tractarians including CMY’s friend Lord Blachford.

She herself seems to have regularly read it and also reviewed for it, but the precise extent of her involvement with it remains to be charted.

###  <i>Literary Churchman, The </i> {#76}

This periodical ran 1855-1892. CMY contributed to it a review of G. O.

Trevelyan’s Cawnpore as well as one to Macmillan’s Magazine (letter 29 May 1865).

She contributed an obituary of Bishop Patteson in 1871: ‘one that I could do from my heart of those vague In Memoriam things’ (mentioned to Fanny Patteson, 8 December 1871), and wrote other unidentified contributions, some sufficiently substantial for her to propose their inclusion in a projected volume of essays (To Alexander Macmillan, 20 March 1869).

Its editor 1864-1876 was the Rev.

Arthur Rawson Ashwell (1824–1879), of whom CMY thought very highly.

He contributed both to MP and to the Monthly Packet of Sunday Teaching.

###  <i>Little Folks</i> {#77}

This was a children’s magazine (1871-1933).

###  <i>Macmillan’s Magazine</i> {#78}

This magazine ran 1859-1907.

Two of CMY’s historical novels were serialized in it: The Dove in the Eagle’s Nest (May-December 1865) and The Chaplet of Pearls (November 1867-December 1868), and her series of articles ‘Children’s Literature of the Last Century’ (May-October 1869), 229-37, 302-10, 448-56.

###  <i>Magazine for the Young</i> {#79}

This periodical was founded by Mary Anne Dyson and her sister-in-law and published by James Burns, but edited from soon after the start by Anne Mozley (1809–1891), whose publisher brothers took over its publication in 1850; it ran 1842-1875.

It was known in CMY’s circle as ‘the Pink Mag’; it was a tiny duodecimo production with a pink paper cover. CMY published in this periodical ‘Chapters on Flowers’ (February 1850-December 1852), which later appeared as The Herb of the Field (1853); twenty-seven ‘Langley School’ stories (September 1846-December 1848), fifteen of which appeared as Langley School; ‘Mrs Elderney’s School’ which was never reprinted in volume form (January 1850-Jan 1852); ‘Thoughts on Pictures’ (1853), also never republished; Friarswood Post Office (August 1858-August 1859); Countess Kate (October 1861-December 1862); and New Ground (January 1863-November 1866).

###  <i>Mission Life, or, The Emigrant and the Heathen</i> {#80}

This was a periodical published by Rivington, which ran from 1866 to 1890.

It was edited by the Rev. [J. J.

Halcombe](../persons.html#604), editorial secretary to the SPCK.

It is not to be confused with the Mission Field, the organ of the SPG. CMY commented (1 Jan 1872) on the details of Bishop Patteson\'s death provided by Charles Hyde Brooke’s account in Mission Life.

###  <i>Month, The</i> {#91}

This Catholic journal ran 1864-2001.

Between 1865 and 1881 it was edited by CMY’s cousin Father Henry James Coleridge S. J., and became associated with the Society of Jesus.

She mentions it (27 April 1867).

###  <i>Monthly Paper of Sunday Teaching, The</i> {#81}

This was edited by CMY throughout its existence, 1860-1875, and was intended to provide suitable material for Sunday School teachers, as she described it (21 May 1860) to Anne Sturges Bourne: ‘I am intending to set up a Monthly sheet of questions for Sunday Schools on the Gospels for each Sunday in the month, also questions on the Catechism, and a small sort of reading to the girl pupils, on some subject connected with the day - as the history of the preservation & MSS of the Bible on the 2nd Sunday in Advent - the full Jewish passover on the 1st after Easter - the Eastern shepherding ways on the Shepherd Sunday.

Could you help me to any of these, adapted to the older classes of Sunday Schools just what you would say to your orphans.

Not quite a sermon but more entertaining to young people.

Septuagesima is to have the Isthmean games - and the 21st after Trinity the account of armour.

Any other Sunday in the year, or any subject is open. I should be very glad of help, specially yours.

Real anecdotes would do well, drawn into morals according with the Sunday, harvest or Christmas advice &c, but I forswear stories or I shall be eaten up and dissipated with them.

It is to be on the model of the National Society’s Sunday School paper, only taking in churchisms which they are afraid of.

The papers should not exceed a sheet of full sized note paper.’ Arthur Rawson Ashwell, Frances Mary Peard and Henrietta Fursdon are known contributors.

###  <i>Morning Herald, The</i> {#92}

This was a daily newspaper published in London which ran 1780-1869.

###  <i>Mothers in Council</i> {#82}

This quarterly was edited by CMY 1890-1901.

It ran until 1930.

It was aimed at the educated members of the Mothers’ Union, as distinct from The Mothers’ Union Journal, which was aimed at the working-class mothers.

###  <i>Mothers’ Union Journal, The</i>  {#93}

This periodical, which ran under this name 1888-1954, was aimed at the working-class members of the Mothers’ Union, as distinct from the educated readers of Mothers in Council.

It changed its name to Home and Family in 1954 and in 2008 to Families First and currently (2010) is also published online:
http://www.themothersunion.org/familiesfirst.aspx

The first editor was Madalene Sabine (Pasley) Jenkyns (1847/8-1935).

###  <i>Net Cast in Many Waters: Sketches from the Lives of Missionaries, The</i> {#94}

This periodical, which was founded in 1866 and continued after 1897 as The Net: The Monthly Magazine of the Zululand Missionary Association, was originally edited by CMY’s great friend Anne Mackenzie.

###  <i>Newbery Magazine</i> {#83}

This was a children’s magazine,

###  <i>Nonconformist, The</i> {#95}

This was a newspaper founded in 1841 by a dissenting clergyman, the Rev.

Edward Miall, who edited it until 1877.

It advocated non-payment of tithes and the disestablishment of the Church of England; CMY was as unlikely to sympathise with its views as it was with hers.

See D. W.

Bebbington, ‘Miall, Edward (1809–1881)’, Oxford Dictionary of National Biography, Oxford University Press, Sept 2004.

###  <i>Once a Week </i> {#84}

Mentioned (9 April 1860).

###  <i>Otterbourne Parish Magazine</i> {#85}

Hampshire Record Office holds a run of this periodical 1874-1932.

References to CMY and her family are very frequent; her contributions not infrequent.

Further investigation might be rewarding.

###  <i>Penny Post, The </i> {#96}

Mentioned by CMY, perhaps rather surprisingly, as reaching the same readers as the MP.

###  <i>Saturday Magazine, The</i> {#98}

This periodical was founded in 1832 as a penny magazine for the working classes, under the auspices of the SPCK; its publisher was John W.

Parker.

###  <i>Saturday Review, The</i> {#99}

This was a weekly magazine of conservative tendency, notorious for its trenchant reviews.

It was immediately successful on its foundation in 1855; its first editor was John Douglas Cook (1808?-1868).

###  <i>Sharpe’s Magazine</i> {#86}

Sharpe’s London Magazine of Entertainment and Instruction ran 1846-1870.

Menella Bute Smedley and her cousin Frank Smedley both wrote for it, and the latter was briefly its editor.

###  <i>St. Luke’s Magazine </i> {#87}

Referred to (25 April 1872) as publishing articles by the Rt.

Rev. C. J.

Abraham about Bishop Patteson.

The Exeter Diocesan Training College was known as St.

Luke’s between 1854 and 1978.

It seems probable that this periodical was associated with it, although no library with holdings from this period has been found.

###  <i>St. Nicholas</i> {#88}

An American magazine for children, it ran 1873-1941. CMY wanted The Release to be published in it, but this does not seem to have happened.

Louisa May Alcott, ‘Pansies’ St.

Nicholas 15 (November 1887) has a girl say: ‘” I love dear Miss Yonge and her books, with their nice, large families, and their trials, and their pious ways, and pleasant homes full of brothers and sisters, and good fathers and mothers. I'm never tired of them, and have read 'Daisy Chain' nine times at least.”’

###  <i>Watchword, The</i> {#100}

This periodical, the privately printed journal of the Society of Watchers and Workers, ran 1880-1972; the BL has only odd volumes, but there is an almost complete run in Lambeth Palace Library.

The BL\'s copies are bound with interesting rolls of members of the society; CMY is listed as a member of the executive committee.

Christina Rossetti was also a member.

The Watchword was initially edited by the society’s founder [Edith Jacob](../persons.html#749) (1836-1918).

### <i> Charm, The</i> {#57}

The Charm: A book for boys and girls Edited by J. C. was published by Addey and ran 1853-55.

It was described by CMY in a letter to Macmillan as ‘a Child’s Magazine . . . which was so contrived that each subject occupied a sheet in each monthly part, and so when bound up all the history could be put together - all the science - all the story.

But such a procrustean bed must have been misery to editor and contributors and I fancy was much aided by unlimited woodcut power.’

### <i> Church Quarterly Review, The</i> {#60}

This ran 1875-1968.

It was edited from its foundation until his death by the Rev. A. R.

Ashwell (1824–1879). CMY contributed a review of Edith Jacob’s ‘Thoughts on Invalid Life’.

### <i> Church Times, The</i> {#61}

This is a High Church Anglican weekly newspaper founded in 1863.

It still exists and its website is www.churchtimes.co.uk

### <i>Academy, The</i> {#246}

### <i>All Saints Magazine</i> {#254}

This was the parish magazine of the church of All Saints, All Saints Road, Cheltenham.

The British Library holds the new series 1886-1909, which is catalogued as edited by the Rev.

William Goldsborough Whittam who was curate there 1883-1888.

### <i>Athenaeum, The</i> {#170}

### <i>Blackwood\'s Edinburgh Magazine</i> {#146}

The magazine published fiction, reviews and articles, and ran 1817-1891.

### <i>Church Illustrated, The</i> {#229}

unidentified

### <i>Cornhill Magazine, The</i> {#156}

### <i>Edinburgh Review</i> {#132}

Its politics were not congenial to CMY, who used it as shorthand for dangerously liberal views in several works.

### <i>Fraser\'s Magazine</i> {#199}

### <i>Friendly Work</i> later the <i>Girls\' Quarterly</i> {#182}

This was a quarterly magazine published by the Girls\' Friendly Society 1883-1917.

It changed its name to the Girls\' Quarterly in December 1894.

It was edited initially by Mary Elizabeth Townsend, from 1893 by Louisa Fanny Field and from 1900 by Henley I.

Arden (i.e.

Henrietta Knight).

It was aimed at Members of GFS who were better educated than those who read the sister periodical Friendly Leaves.

### <i>Girls\' Realm, The</i> {#210}

### <i>Glasgow News, The</i> {#252}

A Conservative newspaper founded in 1873.

### <i>Gospel Missionary, The</i> {#227}

Published 1851-1901 by the Society for the Propagation of the Gospel.

### <i>Hampshire Chronicle, The</i> {#209}

### <i>Harper\'s Young People</i> {#250}

An American juvenile periodical which ran 1879-1895.

### <i>Lincoln Diocesan Magazine, The</i> {#228}

### <i>Literary Gazette, The</i> {#143}

A weekly journal published under various titles from 1817 to 1863.

### <i>Living Age, The</i> {#171}

This Philadelphia journal published serial fiction, and pirated many British writers, including CMY.

### <i>London Society</i> {#220}

### <i>Mission Field: A Monthly Record of the Proceedings of the Society for the Propagation of the Gospel at Home and Abroad, The</i> {#237}

This periodical was the organ of the Society for the Propagation of the Gospel in Foreign Parts from 1856-1941.

### <i>Morning Post, The</i> {#147}

A daily newspaper which ran 1772-1937.

### <i>National Review, The</i> {#259}

A conservative journal founded in 1883.

### <i>North American Review, The</i> {#200}

### <i>Pall Mall Gazette, The</i> {#192}

### <i>Parents\' Educational Union Monthly Journal</i> {#218}

### <i>Queen, The</i> {#241}

### <i>Reader: A review of current literature, science, and art, The</i> {#97}

Mentioned 11 August 1863.

It ran January 1863 - July 1866.

### <i>Record, The</i> {#253}

Weekly newspaper, published in London 1828-1948.

It was Evangelical and anti-Tractarian.

It merged with the Church of England Newspaper and ran 1949-1969 as the Church of England Newspaper and the Record.

### <i>Schoolmistress, The</i> {#212}

### <i>Spectator, The</i> {#180}

### <i>Sunday Magazine, The</i> {#232}

Published by Isbister until 1906.

### <i>Weekly Register, The</i> {#174}

A Roman Catholic Liberal newspaper owned and edited by Henry Wilberforce between 1855 and 1864.

### <i>Youth\'s Companion: An Illustrated Weekly Paper for Young People and All the Family, The</i> {#244}

An American children\'s magazine which ran 1827-1929

## place

### All Saints, Babbacombe {#195}

### All Saints\' Church, Hursley {#261}

The parish church of Hursley was substantially rebuilt in 1847-8 to the designs of William Harrison, under the supervision of the Rev.

John Keble, and partly funded from the profits of his bestselling volume of poetry [The Christian Year](../others.html#95). CMY describes the fittings of the interior and the symbolism of the stained glass in some detail in [John Keble\'s Parishes](../books.html#247) (1898), 115-124.

She emphasises that the work coincided with the Tractarian crisis following Newman\'s secession, so that the reconstruction was an act of faith at a time of great anxiety and doubt, while the movement was the target of vilification and suspicion.

She enumerates the gifts made by Keble\'s friends and supporters to beautify the building, and no doubt they symbolize among other things the dependence placed on him at that time.

### Ampfield {#124}

Ampfield is a village in Hursley parish.

At the instigation of Sir William Heathcote and the Rev.

John Keble a new church, St.

Mark, Ampfield, was built there, opened in 1841.

It was on a slope in a pinewood, which struck them as very beautiful.

### Beechwood {#126}

The home near Sparkwell in Devon of FMY\'s stepbrother Lord Seaton, and his family the Colbornes.

### Brighstone {#140}

A village on the Isle of Wight of which the Rev.

George Moberly was rector between 1868 and 1869.

### Church of the Resurrection, Eastleigh {#188}

Built in 1868 with a donation of £500 from CMY.

The architect was G. E.

Street.

It was destroyed by fire in 1985 and reconstructed as social housing flats in 2003.

See Tim Lambert, A Brief History of Eastleigh, Hampshire at www.localhistories.org/eastleigh

The Hampshire Advertiser (15 August 1868), 3, noted:
The consecration of the Church of the Resurrection, Eastliegh, took place on Thursday, by the Bishop of Mauritius.

The church has been erected principally by the liberality of Miss Yonge, of Otterbourne, and Mr. - Chamberlaine, of Eastleigh Parish, together with other contributors.

The Rev. W. A.

Longlands, of Eling, near Southampton, has been appointed incumbent. A choir of amateurs has been trained by Mr.

Somerford, of Winchester Cathedral. . .

The services were intoned, or read, by the Rev. W. A.

Longlands, incumbent, the Rev. W.

Harrison, Vicar, Eastmeon, the Ven.

Archdeacon Jacob, of Winchester, the Rev. R. F.

Wilson, &c.

### Cranbury Park {#119}

Cranbury Park, in Otterbourne parish, was the home of the principal landowner, Thomas Chamberlayne.

It is still (2010) inhabited by his family.

### Deer Park {#125}

Near Buckerell in Devon, it was the home of FMY\'s stepbrother Lord Seaton and his family before they bought Beechwood.

### Dogmersfield {#121}

Dogmersfield is a village near Hook in Hampshire. CMY\'s friend Mary Anne Dyson lived there with her half-brother the Rev.

Charles Dyson, Vicar of Dogmersfield.

### Hursley {#127}

At the time of CMY\'s birth the village she lived in, Otterbourne, was ecclesiastically part of the neighbouring parish of Hursley, where the principal landowner, Sir William Heathcote, Bt., lived at Hursley Park.

In her teenage years the Vicar of Hursley, the Rev.

John Keble, in collaboration with Heathcote and CMY\'s father, was engaged in a programme of church and school building, which eventually led to the creation of the new parishes of Ampfield and Otterbourne out of Hursley.

### Mota {#150}

An island in the Banks group, part of the Republic of Vanuatu.

Its language was chosen by Patteson as the medium for the conversion of wide areas of Melanesia to Christianity.

### Pitt Chapel {#133}

This chapel in an outlying hamlet of Hursley was built at CMY\'s expense.

It is now a private house.

### Puslinch {#123}

Puslinch, near Newton Ferrars in south Devon, was the home of the Rev.

John Yonge, cousin of CMY\'s father, his wife Alethea Henrietta Bargus, half-sister of CMY\'s mother, and their ten children.

### Rawalpindi {#262}

Town in the Punjab, site of an important army base, now in Pakistan and then in British India.

### Santa Cruz Islands {#122}

The island of Nakapu was the scene of the death of the Rt.

Rev.

John Coleridge Patteson in 1871.

It is an outlying island in the Reef (or Swallow) group of islands, which is in turn part of the group known as the Santa Cruz islands.

The Santa Cruz islands form politically the province of Temotu in the Solomon Islands.

The latter were declared a British protectorate in 1893 and achieved independence in 1978 as a constitutional monarchy with Queen Elizabeth II as head of state.

### Slade {#120}

Slade, near Cornwood in Devon, was the home of CMY\'s cousins the Pode family.

### Sorel {#181}

This was the home in Meadfoot Road, Torquay of the Rev.

Joseph Hemington Harris, and his wife Jane (Yonge) Harris, sister of \'Uncle Yonge\'.

It still stands and has been divided into flats.

### St. Matthew\'s Church, Otterbourne {#158}

### Twyford {#128}

### Tyntesfield {#207}

The home in Somerset of [William Gibbs](../persons.html#560) and his wife, CMY\'s cousin [Matilda Blanche Crawley Boevey](../persons.html#557).

### Val Richer {#205}

The home in Normandy of [Guizot](../persons.html#597) and his family.

### Weston, St. Marychurch, Torquay {#196}

The home of Joan and Fanny Patteson

## topic

###  Marriage between first cousins {#101}

CMY was against this, and such marriages are not encouraged in any of her novels, although they are a normal feature of nineteenth-century fiction by other writers (occurring for example without disapproval in Mansfield Park and Middlemarch), just as they were a commonplace feature of Victorian life.

The topic is mentioned (15, 20 March 1860) in letters to Ann Maria Carter Smith and discussed by CMY in ‘Three Generations’ Mothers in Council 5.17 (Jan 1895).

Her opinions were probably formed because of her family history.

In her autobiographical writing she observes of her grandmother’s family ‘the Crawleys were far too much addicted to marriages among cousins’.

This is in connection with the marriage of her uncle James Yonge to his first cousin Margaret Crawley; his sisters Catharina and Charlotte also married Margaret’s brothers Charles and George.

James Yonge was a physician in Plymouth, His three children all died within a year in 1830.

There was a growing scientific evidence against the excessive inbreeding, reinforced for the agriculture-minded landed gentry by the lessons drawn from experience with horses, dogs and farm animals.

Moreover there was also much discussion in religious circles of the prohibited degrees.

Pusey, giving evidence in 1847 to the Commission appointed to enquire into the state and operation of the law of marriage (which was much preoccupied with the deceased wife’s sister issue), cited St.

Augustine’s view that the marriage of first cousins, though lawful, was near to incest (Parliamentary Papers 1848, 40).

###  rate of payment of <i>MP</i> contributors {#102}

###  women publishing books with their names {#106}



### 70th Birthday Presentation to CMY {#225}

The presentation of an autograph album to CMY on her seventieth birthday, which was organized by the Moberly family, is described by Coleridge, [Life](../others.html#40), 281-2, and Battiscombe, [Charlotte Mary Yonge](../others.html#17), 159.

The following report appeared in The Times (16 August 1893), 8:

\'The 70th birthday of Miss Yonge has been marked by a presentation to her from admirers in all parts of the world.

An album containing 5.000 autographs and criticisms of her writings was left on her birthday at her dwelling in the village of Otterbourne.

On the front page is the following inscription in an illuminated border:- \"Charlotte Mary Yonge - We offer our hearty congratulations on your 70th birthday, and desire to express to you the great enjoyment we have received from your writings, and our belief that they have done much good in this generation.

August 11, 1893.\" Amongst the signatures are those of the Archbishop of York, the Earl of Selborne, the Marquis of Salisbury, Viscount Wolmer, the Bishops of London, Manchester, Salisbury, Chester, Bath and Wells, Chichester, Leicester, Reading, Southwell, Cape Town, Connecticut, and St.

Helena, Bishops Selwyn, Jenner and Hobhouse, the Deans of Winchester, Windsor and Salisbury, Canon Scott Holland, the Warden of Keble College, Mr.

Balfour and several members of Mr.

Gladstone\'s family, besides the local clergy and gentry.

The Queen of Italy sent a large photograph of herself, bearing her autograph and accompanied by a congratulatory note.

Local presentations were made to Miss Yonge on the eve of her birthday.\'

### American piracy {#172}

### Auckland Bells, The {#103}

This was an eventually successful campaign to raise money so that the sound of church bells should be heard in New Zealand: see MP (July 1857- February 1863).

### Books for the Chicago Exhibition {#221}

[Alice Gordon](../persons.html#572) had written to the Editor of The Times (5 January 1893): \'A library has been built in the Women\'s Building of the Chicago Exhibition, in which the best books written by women of all nations are to be exhibited.

We are anxious that English women\'s writings should be well represented. A committee has been formed consisting of Miss Agnes Clerke, Mrs. W. K.

Clifford, Mrs.

Green, Miss Kingsley, Mrs.

Humphry Ward, Miss Charlotte Yonge, and Mrs. J. E. H.

Gordon, to collect a representative library.\' She asked for the gift or loan of books or MSS.

### Bullock\'s proposed book of Anglican saints {#213}

### CMY\'s Collected Works {#264}

CMY was keen to see her works reprinted in a cheaper format, and she was evidently urging Alexander Macmillan to undertake a collected edition in the mid-1860s.

### CMY\'s literary earnings {#160}

### Charlotte Yonge Scholarship, The {#113}

In 1898 fund-raising began to provide a University Scholarship from Winchester High School for Girls in honour of CMY.

The appeal published in MP (April 1898) 469, in The Times (17 March 1898) 7, and elsewhere, signed ‘Esmé Stuart’, states ‘\'The sum of £6000 will be required in order to found an Annual Scholarship of £50 to be held for three years\'.

Actually about £1800 was raised, less than had been hoped, and the first recipient, [Amy Aubrey Locke](../persons.html#893), who was the daughter of the porter of Winchester College, was initially unable to take up the scholarship because it did not cover the entire expense. A presentation was made to CMY on 19 July 1899 in the school.

According to the report in The Times (22 July 1899) those present included Amelie Leroy (‘Esmé Stuart’), the Rev. J. H.

Merriott, the hon. treasurer of the committee, Miss Mowbray, the Sumners, the Hon.

Mrs Joyce, Mrs Harold Browne, Christabel Coleridge, Eleanor Price and Mrs Anderson Morshead.

The scholarship continued to be awarded at least until the 1930s.

### Church restoration {#198}

In Victorian England the question of the restoration of ancient churches involved several different considerations.

Just as there was an immense amount of new church building, in which the Tractarians took an enthusiastic part, so there was also a great deal of church rebuilding.

The Ecclesiological Society encouraged work which was Gothic, and supported on purist grounds the de-classicizing of many churches.

Indeed it sometimes supported the removal of genuinely mediaeval work and its replacement by work which was consistent with the original period of the building.

As well as this aesthetic and historicizing element, there was also a movement to open up churches to the poor, by removing the room-like pews rented by the gentry.

And liturgical considerations meant that the Tractarians in some cases reinstated features of mediaeval churches, such as rood screens, which had been absent since the Reformation. CMY\'s sense of reverence meant that she refers to these issues only in passing in her fiction, for example when Clement pulls down the church\'s black mourning drapery in [The Pillars of the House](../books.html#109), although other novels, from the Rev. F. E.

Paget\'s Milford Malvoisin (1842) to Thomas Hardy\'s Under the Greenwood Tree (1872), give a good idea of the ructions which these changes involved.

### Collection of British Authors {#224}

This was a series published by the Leipzig publisher Firma Tauchnitz, which circulated small paperback novels in English on the continent.

Travellers were not meant to bring them back to England, because of the law of copyright, but of course many did.

Many of CMY\'s works appeared in the series, and she received payments from Tauchnitz for many years.

### Gosling Society, The {#104}

The Gosling Society was an essay society run by CMY which operated 1859-1877

In 1859 CMY was encouraged by her cousin [Mary Coleridge](../persons.html#351) to start an essay society for a group of young girls who were in need of more mental stimulation than the life of a Victorian daughter at home afforded them.

They called her Mother Goose and they became the Goslings.

Each girl adopted a fancy pen-name such as ‘Hedge Rose’ or ‘Shamrock’.

Each wrote two essays a month for her, and the best essays were circulated among them all.

The foundation of the Gosling Society reflects the anxiety felt by many Victorians about the restricted educational opportunities for women.

Its existence coincided with the dramatic expansion of schools and universities open to women.

It doesn’t seem that any of the Goslings benefited personally from these developments, but, as Julia Courtney has argued in [ \'The Barnacle: A Manuscript Magazine\'](../others.html#190), they were of the generation who helped to bring such schools and universities into being.

Several of them followed Yonge’s example and became writers themselves.

Charlotte Yonge herself was not a wholehearted supporter of schools and universities for women, though her attitude mellowed over the years, but her intellectual standards were high, and members were required to research and compose two essays a month on such topics as ‘The distinguished Christian characters of Milan’ or ‘What parallel stories does folklore in different countries present to the adventures of Ulysses in the Odyssey?’ or ‘The citizen of Athens’.

Membership
The earliest known members of the Society were Mary’s niece Mildred Coleridge, two other cousins of hers, Paulina Martyn and Christabel Coleridge, two Devon neighbours, Charlotte and Henrietta Fursdon, and Charlotte Yonge’s friend and neighbour Emily Moberly.

Many of them were related to each other; all were drawn from a narrow social circle, mainly from clerical and gentry families.

They were probably all consciously High Church, and several of them, like Yonge herself, became Associate members of the Wantage sisterhood.

Over the years the membership fluctuated as girls grew up, lost interest or married, but it seems to have usually included about ten young women.

During the 1860s three other older women, Frances Peard, Florence Wilford, and Emily Synge, were recruited, the first certainly in response to Mary Coleridge’s loss of interest as Mildred grew up.

A list of the society\'s members will be found at http://www.dur.ac.uk/c.e.schultze/context/goslings.html

Sources
The only modern scholarly study is by Julia Courtney, ‘The Barnacle: A manuscript magazine of the 1860s’, in The Girl’s Own: Cultural Histories of the Anglo –American Girl 1830-1915 ed.Claudia Nelson and Lynne Vallone. (Arkansas and London: University of Georgia Press: 1994).

The main evidence about the Gosling Society comes from the surviving volumes of its manuscript magazine, The Barnacle (incomplete series, 1863-1867), in the library of Lady Margaret Hall, Oxford.

These have circulation lists at the front, which, in conjunction with two other surviving circulation lists for 1869 and 1876 (private collection), provide most of the information about membership.

There are interesting references to the Society in Christabel Coleridge\'s [Life](../others.html#40) of CMY and Mary J. Y.

Harris\'s, Memoirs of Frances Mary Peard.

One of Yonge’s stories, [The Disturbing Element, or, Chronicles of the Bluebell Society](../books.html#125) (1878) is about a middle-aged spinster who runs a reading group for a group of girls in a small resort in south Devon.

It seems to draw on some of her experiences with the Goslings.

Another fictional source is a story which appeared in MP (Christmas 1872), 1-3, entitled \'Our Essay Society, or, A Wet Day with the Spiders\'.

It may be by CMY, but is probably the work of Christabel Coleridge.

It reminisces fondly about the society\'s early days.

In the story the society the members are Spiders rather than Goslings, and that name was later adopted by the much larger essay society run out of MP.

There is also some discussion of essay societies in Yonge’s regular column on ‘Hints on Reading’ in MP 30 (August 1865), 221-2.

### Indian Mutiny, The {#134}

### Keble\'s funeral {#184}

Keble\'s funeral, which CMY described as a \'gathering of the good\' took place on Friday 6 April 1866 at the church of All Saints, Hursley. [Charlotte Keble](../persons.html#795) was not present as she was lying dangerously ill in Bournemouth.

A large congregation is recorded in the accounts in John Bull (7 April 1866) 234 and the Pall Mall Gazette (7 April 1866) 8.

The six former curates who carried the coffin were the Rev.

Peter Young, the Rev.

William Bigg Wither, the Rev.

Robert Francis Wilson, the Rev. C.

Le Geyt, the Rev. F. C.

Alderson and the Rev. S.

Scroggs.

The Bishop of Salisbury (Walter Kerr Hamilton) was the only English bishop present, illustrating the suspicion in which the Tractarians were still held in many circles, though Bishop Forbes of Brechin was there.

Cathedral clergy who did come included the Very Rev.

Dr Hook, the Dean of Chichester, the Very Rev.

Thomas Garnier, the aged Dean of Winchester, and the Ven.

Philip Jacob, the Archdeacon of Winchester.

Sir William Heathcote was there with his son-in-law Thomas Cooke Trench, as were Earl Nelson, Sir Frederic Rogers, General Wilbraham, Robert Brett, the Hon.

Colin Lindsay and William Butterfield.

Other well-known Tractarian clergy included the Rev. W. J.

Butler, the Rev. R. W.

Church, the Rev. C. F.

Lowder, Dr.

Pusey, Dr.

Moberly, the Ven.

Sir George Prevost, the Rev.

William Upton Richards and the Rev.

Henry Parry Liddon,

### Macmillan\'s Sunday Library {#145}

See Ellen Jordan, ‘“I am too high church and too narrow”; Charlotte Yonge, Macmillan and the Sunday Library.’ Charlotte M Yonge Fellowship Journal. 6 (2003): 12-25.

### Philological Society\'s proposed Dictionary, The {#151}

IN 1860, the Committee of the Philological Society resolved to produce a
dictionary of four volumes, covering the entire English language from past to present. CMY and her mother, encouraged by their cousin Henry Hucks Gibbs, were among the contributors of material in the 1860s, to what was, eventually, to become the New English Dictionary on Philological Principles.

### Risorgimento, The {#149}

### Scotch girl\'s novel {#193}

CMY asked Alexander Macmillan to read a manuscript novel by a Scots girl.

It may perhaps have been the work of Mary Frances Dundas.

### Winchester lectures for ladies {#240}

The Englishwoman’s Review 1 (January 1870), 27 notes, \'Lectures to ladies on English literature are to be given by Professor Morley, at Winchester in the autumn.\' There is a good description of the experience from Henry Morley\'s point of view in his 1898 biography by Henry Solly.

This development was part of the general movement for the higher education of women and the extension of university teaching to excluded groups.

The London Ladies\' Educational Association was founded in 1868-69.

See Carol Dyhouse, No Distinction of Sex?

Women in British Universities, 1870-1939 (London: UCL Press, 1995) pp. 13-17 and J.F.C.

Harrison, Learning and Living 1790-1960: A Study in the History of the English Adult Education Movement (London: Routledge and Kegan Paul, 1961) Chapter 6.

### \'Bethlehem\'  {#177}

This was a book project concerted between CMY and her publisher Alexander Macmillan, of which some seems to have been written and none published.

### advertisement for <i>Robert Elsmere</i> {#217}

At least one of the MP\'s readers objected to an advertisement for Mary Ward\'s novel Robert Elsmere which arrived with the magazine.

### avoiding accusations of Puseyism {#154}

### higher education of women, The {#105}



### illustration {#167}

### proposed guide to charitable institutions {#190}

CMY and Johanna Batty formed the intention of writing a guide to charitable institutions, but it does not seem to have been published.

### sales of CMY\'s works {#155}

### story of Indian life {#202}

The \'story of Indian life\' referred to in several of CMY\'s 1868 letters to Macmillan appears to have been called \'Wooed and Won\'.

