---
title: "Persons Referenced in the Letters"
---

- [Person 1957](/person/1957)
- [James](/person/753)
- [Linny](/person/882)
- [Lady Chichester Rosalie Amelia](/person/281)
- [Eugène Louis John Joseph](/person/1772)
- [Olive](/person/1102)
- [Prince Ernest Augustus](/person/394)
- [Albert Edward](/person/1876)
- [Alexander Lycurgus](/person/2265)
- [Alexandra Caroline Marie Charlotte Louise Julia](/person/1877)
- [Charles I](/person/1768)
- [Cherry](/person/2276)
- [Comte de Paris Louis-Philippe,](/person/1741)
- [Duc de Nemours Louis](/person/1738)
- [Eugénie](/person/1771)
- [Ferdinand I](/person/2042)
- [Gustavus Adolphus](/person/2419)
- [Hannah](/person/1821)
- [Hundulu](/person/2013)
- [Isabella](/person/2035)
- [Ivy](/person/2264)
- [Joséphine](/person/2415)
- [Larkie](/person/1795)
- [Louis Philippe](/person/2039)
- [Louise Marie Adelaide Eugènie d’Orléans](/person/2038)
- [Maria Antonietta](/person/2041)
- [Maria Carolina](/person/2040)
- [Maria Luisa Fernanda](/person/2036)
- [Marie Amelie](/person/1737)
- [Marie Antoinette](/person/2417)
- [Misey](/person/2293)
- [Mrs Richards](/person/1902)
- [Napoleon](/person/1735)
- [Napoleon III](/person/2295)
- [Pius IX](/person/1709)
- [Prince Albert](/person/1736)
- [Prince Arthur](/person/1997)
- [Princess Princess Christian o Helena Augusta Victoria](/person/2222)
- [Reverend Mother Susan](/person/1385)
- [Sister Ellen](/person/1807)
- [Speedwell](/person/2291)
- [Victoria](/person/1694)
- [Wilhelmina Helena Pauline Maria](/person/2249)
- [William](/person/1687)
- [\'Bath Brick\'](/person/1865)
- [duc de Chartres Robert](/person/1742)
- [duchesse d\'Orleans Helene](/person/1740)
- [duchesse de Nemours Victoire](/person/1739)
- [marquise de Montagu Anne-Paule-Dominique](/person/1921)
- [Jacques-Bénigne Bossuet](/person/2418)
- [Miss De Salis](/person/415)
- [Friedrich Wilhelm August Fröbel](/person/2333)
- [Thérèse Levasseur](/person/2422)
- [Anne-Paule-Dominique, Marquise de Montagu](/person/1922)
- [Aimable Jean Jacques Pélissier](/person/2045)
- [Arthur Llewelyn Roberts](/person/2384)
- [Charlotte de Mornay](/person/1880)
- [2nd Lord Heytesbury William Ashe A\'Court](/person/1641)
- [The Hon. Margaret A\'Court](/person/1639)
- [Caroline Harriet Abraham](/person/3)
- [The Rt. Rev. Charles John Abraham](/person/4)
- [Miss Abraham](/person/2108)
- [Sarah Angelina Acland](/person/8)
- [Sir Henry Wentworth Acland](/person/7)
- [Sir Thomas Dyke Acland](/person/9)
- [Lady Christian Henrietta Caroline Acland](/person/1829)
- [Frances Lydia Dyke Acland Troyte](/person/5)
- [Arthur Henry Dyke Acland Troyte](/person/6)
- [Adams](/person/10)
- [Charles Warren Adams](/person/12)
- [Charlotte Alethe Rosalie Adams](/person/14)
- [Georgina Alethe Adams](/person/13)
- [Mary Adams](/person/15)
- [Oscar Fay Adams](/person/16)
- [Mrs Adams](/person/11)
- [The Hon. Mildred Mary Adams](/person/17)
- [Joseph Addison](/person/1812)
- [The Ven. William Brise Ady](/person/2342)
- [Sir Andrew Agnew](/person/18)
- [Caroline Louise Alcock](/person/19)
- [Louisa May Alcott](/person/1649)
- [Lady Alderson](/person/20)
- [Cecil Frances Alexander](/person/21)
- [The Rt. Rev. William Alexander](/person/1840)
- [The Rt. Rev. Charles Richard Alford](/person/22)
- [The Very Rev. Henry Alford](/person/23)
- [Eliza Allen](/person/24)
- [Phoebe Anne Allen](/person/25)
- [Jean-Jacques Ampère](/person/26)
- [Anne Elizabeth Mary Anderson Morshead](/person/28)
- [Charlotte Anderson Morshead](/person/41)
- [Ernest Garstin Anderson Morshead](/person/29)
- [Frank Upton Anderson Morshead](/person/30)
- [Helen Beatrice Anderson Morshead](/person/31)
- [Henry Anderson Morshead](/person/32)
- [John Yonge Anderson Morshead](/person/33)
- [Julia H. Anderson Morshead](/person/34)
- [Leslie Anderson Morshead](/person/35)
- [Louisa E. Anderson Morshead](/person/36)
- [Pentyre Anderson Morshead](/person/39)
- [Pentyre Edmund Anderson Morshead](/person/38)
- [Alethea Anderson Morshead](/person/27)
- [Captain Pentyre Anderson Morshead](/person/40)
- [The Rev. Edmund Doidge Anderson Morshead](/person/42)
- [The Rev. John Philip Anderson Morshead](/person/43)
- [Elizabeth Anderson Morshead](/person/1716)
- [Mary Anderson Morshead](/person/2084)
- [The Rev. W. G. Andrewes](/person/44)
- [Agnes Henrietta Anson](/person/45)
- [Mornebel Anson](/person/46)
- [Joseph Anstice](/person/2285)
- [Sir Edward Antrobus](/person/47)
- [L. H. Apaque](/person/48)
- [George Latimer Apperson](/person/49)
- [William Henry Appleton](/person/1937)
- [Rose Arbesser](/person/1931)
- [Fulbert Archer](/person/51)
- [The Rev. Charles Harward Archer](/person/52)
- [The Rev. Samuel Harward Archer](/person/53)
- [Maria Georgina Archer Houblon](/person/50)
- [H. J. Arden](/person/55)
- [Edith Margaret Argles](/person/56)
- [Margaret Julia Argles](/person/57)
- [Mary L. Argles](/person/59)
- [The Very Rev. Marsham Argles](/person/58)
- [The Rev. Marsham Frederic Argles](/person/2413)
- [Edward Armitage](/person/60)
- [Annie Armitt](/person/61)
- [F. Arnold](/person/63)
- [James John Arnold](/person/62)
- [Dr. Thomas Arnold](/person/64)
- [Edward Augustus Arnold](/person/2211)
- [Ellen Arnold](/person/2158)
- [Sarah Arnold](/person/2055)
- [Thomas Arnold](/person/2023)
- [Mary Arthur](/person/65)
- [Mary Ash](/person/66)
- [Miss Ashington](/person/67)
- [The Rev. Canon Arthur Rawson Ashwell](/person/68)
- [Elizabeth Ashwell](/person/2329)
- [Miss Ashwell](/person/1863)
- [Don Duke of Cadiz Francisco Asís de Borbón](/person/69)
- [The Rev. Joseph Atkin](/person/1979)
- [Blanche Atkinson](/person/70)
- [J.C. Atkinson](/person/72)
- [Frances Hester Atkinson](/person/71)
- [The Rt. Rev. Thomas Atkinson](/person/73)
- [The Rev. Edward Atkinson](/person/2309)
- [Miss Attard](/person/74)
- [Mrs Attwood](/person/75)
- [Jane Austen](/person/76)
- [Charles Edward Austen Leigh](/person/77)
- [The Rev. James Edward Austen Leigh](/person/78)
- [Mary Augusta Austen Leigh](/person/2278)
- [Sarah Austin](/person/1879)
- [Bridget Hildred Vere Awdry](/person/79)
- [Charles Awdry](/person/80)
- [Frances Awdry](/person/82)
- [Frances Emily Awdry](/person/81)
- [Margaret Helen Awdry](/person/83)
- [The Rev. Vere Awdry](/person/84)
- [The Rt.Rev. William Awdry](/person/85)
- [Mary Louisa Awdry](/person/2214)
- [William Edmonstone Aytoun](/person/1875)
- [Fanny Backhurst](/person/86)
- [Mrs Backhurst](/person/87)
- [Mary Bacon](/person/88)
- [Mrs Bacon](/person/89)
- [John Bacon](/person/2196)
- [1st Lord Baden-Powel Robert Stephenson Smyth Baden-Powell](/person/2202)
- [Olave St. Clair Baden-Powell](/person/2232)
- [The Ven. Hopkins Badnell](/person/90)
- [Joanna Baillie](/person/91)
- [Lady Grisell Baillie](/person/1832)
- [E. J. C. Baird](/person/92)
- [Agnes Baker](/person/95)
- [Amy Susan Baker](/person/94)
- [Annie or Anne Baker](/person/97)
- [The Rev. James Baker](/person/96)
- [Harriet Emma Lockhart Baker](/person/2075)
- [Mrs Baker](/person/2428)
- [Sophia Baker](/person/1717)
- [Katharine Frances Baker Wilbraham](/person/93)
- [James Baldwin](/person/98)
- [Josephine Baldwin](/person/99)
- [S. Ballard](/person/100)
- [Mrs Ballard](/person/101)
- [The Rev. Charles Wareing Endell Bardsley](/person/102)
- [John Barfoot](/person/104)
- [Sarah Barfoot](/person/105)
- [Mary Bargus](/person/103)
- [The Rev. Thomas Bargus](/person/106)
- [Charlotte Bargus](/person/1660)
- [John Lock Bargus](/person/1662)
- [Richard Bargus](/person/1661)
- [Cordelia Bargus [formerly Colborne]](/person/1700)
- [Sir Thomas Baring](/person/1693)
- [Miss Barker](/person/107)
- [Mr Barker](/person/1678)
- [The Rt. Rev. Frederic Barker](/person/1906)
- [Ellen Barlee](/person/108)
- [Jane Barlow](/person/110)
- [Miss Barlow](/person/2079)
- [Charlotte Alington Barnard](/person/111)
- [William Barnes](/person/112)
- [Elizabeth Barnett](/person/113)
- [Herbert Rose Barraud](/person/1684)
- [Anna Meredith Barrett Lennard](/person/121)
- [Elspeth Catherine Barter](/person/114)
- [Catherine Barter](/person/116)
- [Katharine Barter](/person/117)
- [The Rev. Henry Barter](/person/115)
- [The Rev. Robert Speckott Barter](/person/118)
- [Mary Barter](/person/1755)
- [The Rev. Charles Barter](/person/1704)
- [The Rev. William Barter](/person/1703)
- [Mrs Barton](/person/2235)
- [Mrs Bartram](/person/1668)
- [Alexander Bassano](/person/2361)
- [Baldwin John Pollexfen Bastard](/person/120)
- [Edmund Rodney Pollexfen Bastard](/person/119)
- [Prince Leopold Henry Battenberg](/person/123)
- [Prince Maurice Battenberg](/person/124)
- [Prince Alexander Battenberg](/person/122)
- [Beatrice Braithwaite Batty](/person/125)
- [Johanna Batty](/person/126)
- [Ebba Bayley](/person/127)
- [Ada Ellen Bayly](/person/2228)
- [F. E. Beach](/person/1674)
- [Mrs Beach](/person/2369)
- [William Wither Bramston Beach](/person/2245)
- [The Rev. Canon Frederick Beadon](/person/2301)
- [Dorothea Beale](/person/128)
- [Caroline Jeannette (or Janetta) Beck](/person/130)
- [The Rev. Edward Josselyn Beck](/person/131)
- [The Rev. James Beck](/person/132)
- [Florence Belfield](/person/133)
- [Nancy Bell](/person/135)
- [Margaret Alexis Bell](/person/134)
- [George Bell](/person/1930)
- [Nona Maria Stevenson Bellairs](/person/136)
- [Miss Bennett](/person/138)
- [The Rev. Henry Bennett](/person/137)
- [Louisa Jane Bennett](/person/2356)
- [Mary Eleanor Benson](/person/141)
- [The Rev. Arthur Christopher Benson](/person/139)
- [The Rt. Rev. Edward White Benson](/person/140)
- [Mary Benson](/person/2350)
- [Margaret Benson](/person/1858)
- [John Jervis Beresford](/person/142)
- [Alexander James Beresford Beresford Hope](/person/1714)
- [Janet Sinclair Berger](/person/143)
- [The Rev. Edward Lyon Berthon](/person/144)
- [John Berwick](/person/145)
- [Sir Walter Besant](/person/1652)
- [Aline Grefil Best](/person/146)
- [Miss Best](/person/147)
- [John Bewick](/person/2050)
- [The Rev. Charles Bice](/person/2026)
- [The Rt. Rev. Edward Henry Bickersteth](/person/2244)
- [Alethea Bigg](/person/148)
- [Elizabeth Mary Bramston Bigg Wither](/person/1803)
- [Jane Dorothy Bigg Wither](/person/1765)
- [Lovelace Bigg Wither](/person/1763)
- [The Rev. Reginald Fitzhugh Bigg Wither](/person/2318)
- [Matthew R. Bigge](/person/2083)
- [The Rev. Louis Coutier Biggs](/person/149)
- [Harold Bindloss](/person/150)
- [Mina Bird](/person/151)
- [The Rev. George William Birkett](/person/152)
- [Caroline Birley](/person/153)
- [Miss Birley](/person/154)
- [Matilda Bishop](/person/156)
- [Isabella Lucy Bishop](/person/1817)
- [Otto Eduard Leopold von Bismarck](/person/2267)
- [Mrs Biss](/person/155)
- [Bjornsterne Bjornson](/person/157)
- [Clementina Maria Black](/person/158)
- [Jemima Blackburn](/person/159)
- [Hugh Blackburn](/person/1862)
- [Gertrude Mary Ireland Blackburne](/person/160)
- [Ann Blage](/person/1968)
- [William Blake](/person/1977)
- [Frances Sibyl Bland](/person/2326)
- [Miss Blatchford](/person/2355)
- [Sophia Bliss](/person/161)
- [Colonel Blois](/person/1776)
- [Emily Blunt](/person/163)
- [Lady Susanna Blunt](/person/164)
- [The Rev. Canon Alexander Colvin Blunt](/person/2077)
- [The Rt. Rev. George Francis Popham Blyth](/person/165)
- [Catharina Boevey](/person/1646)
- [Walter Deeble Boger](/person/166)
- [Francis Reginald Bogue](/person/170)
- [Edith Elizabeth Bogue](/person/169)
- [The Rev. John Richard Bogue](/person/168)
- [Mary Bogue](/person/1659)
- [Napoleon Bonaparte](/person/2207)
- [Prince Lucien Bonaparte](/person/1733)
- [Alethea Duke Bond](/person/171)
- [R.W. Bond](/person/172)
- [Martha Bone](/person/1967)
- [Ruggero Bonghi](/person/2387)
- [Joanna Hilary Bonham Carter](/person/1913)
- [E. C. Boothby](/person/173)
- [Hugo Borges](/person/174)
- [George William Bosanquet](/person/175)
- [Mrs Bothamly](/person/176)
- [Helen Mary Boulnois](/person/177)
- [William Butler Bourn](/person/178)
- [William St. Hill Bourne](/person/180)
- [Harriet Bowdler](/person/181)
- [Caroline Bowles](/person/109)
- [Cicely Gertrude Bowles](/person/183)
- [Eileen Helen Bowles](/person/188)
- [Louisa Alethea Bowles](/person/182)
- [Margaret Ernestine Bowles](/person/185)
- [Marjory Joan Georgina Bowles](/person/186)
- [Phyllis Alan Bowles](/person/187)
- [Reginald Julian Albany Bowles](/person/189)
- [The Rev. Henry Albany Bowles](/person/184)
- [The Rev. Henry Albany Bowles](/person/190)
- [Edward Bowles](/person/2226)
- [Miss Bowles](/person/2099)
- [The Rev. Canon Francis Alfred Bowles](/person/2144)
- [William Boxall](/person/1928)
- [Ethel Mary Boyce](/person/191)
- [Mary Christiana Boyle](/person/193)
- [Countess of Glasgow Montagu Boyle](/person/566)
- [The Very Rev. George David Boyle](/person/192)
- [Sir Henry Boynton](/person/1843)
- [Countess of Meath Mary Jane Brabazon](/person/985)
- [Mr. Brackenridge](/person/194)
- [Charles Bradlaugh](/person/2229)
- [Anna Rachel Bramston](/person/195)
- [Mary Eliza Bramston](/person/198)
- [The Rev. John Trant Bramston](/person/196)
- [Jane Bramston](/person/2303)
- [The Very Rev. John Bramston](/person/197)
- [Madeline Brandreth](/person/208)
- [Emily Charlotte Brandt](/person/1897)
- [Francis Brandt](/person/1896)
- [Margaret Adelaide Brandt](/person/1899)
- [Margaret Sophia Brandt](/person/1898)
- [Sir J. Brenton](/person/209)
- [Robert Brett](/person/210)
- [Miss Bridges](/person/1910)
- [The Rev. William Bright](/person/199)
- [Gabrielle Frances Brock](/person/200)
- [Hubert Carey Brock](/person/202)
- [The Rev. Henry Walter Brock](/person/201)
- [The Very Rev. Carey Brock](/person/2112)
- [Sir Benjamin Collins Brodie](/person/203)
- [Emily Hester Brodrick](/person/205)
- [The Rev. and Hon. Alan Brodrick](/person/204)
- [Mary Elizabeth Bromfield](/person/162)
- [Anne F. Bromhead](/person/206)
- [Charlotte Brontë](/person/1810)
- [Mrs Brook](/person/2221)
- [Mr Brooke](/person/1947)
- [The Rev. Charles Hyde Brooke](/person/1981)
- [Catherine Anna Mona Brougham](/person/207)
- [The Rt. Rev. William Grant Broughton](/person/1732)
- [Kate H. Brown](/person/212)
- [The Rev. John Cave Brown](/person/211)
- [Elizabeth Browne](/person/214)
- [The Rt. Rev. Edward Harold Browne](/person/213)
- [Katharine Charlotte Brownlow](/person/2022)
- [Mr Brownrigg](/person/2233)
- [Margaret Bruce](/person/215)
- [Robert Bruce](/person/1853)
- [7th Earl of Cardigan James Thomas Brudenell](/person/1789)
- [Mary R. L. Bryce](/person/216)
- [George Buchanan](/person/217)
- [Mr Buck](/person/2085)
- [Anna Jane Buckland](/person/2331)
- [Anne Badcock Buckle](/person/218)
- [Alice Maud Budd](/person/219)
- [Samuel Budgett](/person/220)
- [Mary Ann Buffham](/person/2048)
- [Lady Audrey Jane Charlotte Buller](/person/2223)
- [General Sir Redvers Buller](/person/2257)
- [The Rev. John Frederick Watkinson Bullock](/person/221)
- [Elizabeth Bullock](/person/2134)
- [Lady Elizabeth Bulteel](/person/1715)
- [The Rt. Rev. John Shaw Burdon](/person/224)
- [The Rev. John William Burgon](/person/222)
- [Anna Christian Burke](/person/223)
- [Ella Louisa Ellenborough Burlton](/person/225)
- [Burn](/person/226)
- [Sir Edward Coley Burne-Jones](/person/227)
- [James Burns](/person/228)
- [Montagu Burrows](/person/229)
- [Anna L. Burrows](/person/2253)
- [The Rev. Henry William Burrows](/person/1969)
- [Willoughby M. Burslem](/person/230)
- [Rachel Harriette Busk](/person/231)
- [Euphemia Emily Georgiana Bussell](/person/232)
- [Anne Mary Buston](/person/236)
- [Margaret Elizabeth G. Buston](/person/234)
- [Philip Thomas Buston](/person/235)
- [The Rev. Roger Buston](/person/233)
- [Anna Butler](/person/237)
- [Emma Butler](/person/240)
- [Frances Charlotte Butler](/person/241)
- [Mary Avice Butler](/person/242)
- [Mary Caroline Butler](/person/239)
- [William George Butler](/person/243)
- [Arthur John Butler](/person/238)
- [The Very Rev. William John Butler](/person/244)
- [Geraldine Butt](/person/246)
- [Beatrice May Butt](/person/245)
- [William Butterfield](/person/247)
- [Hezekiah Butterworth](/person/248)
- [Julia Clara Byrne](/person/249)
- [Emma Marie Caillard](/person/250)
- [Mary Calvert](/person/1919)
- [M. L. Cameron](/person/251)
- [Eliza Charlotte Canning](/person/1374)
- [Sir Stratford Canning](/person/1373)
- [Princess Olga Nikolaevna Cantacuzène](/person/252)
- [Mr Capes](/person/2167)
- [Hannah Carey](/person/253)
- [Rosa Nouchette Carey](/person/254)
- [Miss Carey](/person/2210)
- [Thomas Carlyle](/person/1972)
- [J. Carmichael](/person/256)
- [Mary Carmichael](/person/257)
- [Chiltern Carr](/person/258)
- [Harriet Catherine Carr](/person/259)
- [Joseph Comyns Carr](/person/2364)
- [Edith Carrington](/person/260)
- [Vaughan Carroll](/person/262)
- [The Rev. Canon Thomas Thellusson Carter](/person/268)
- [Elizabeth Carter](/person/1830)
- [Owen Browne Carter](/person/1886)
- [Ann Maria Carter Smith](/person/263)
- [Elizabeth Harriet Carter Smith](/person/265)
- [Edmond Henry Carter Smith](/person/264)
- [The Rev. Richard Carter Smith](/person/267)
- [Julia Mary Cartwright](/person/269)
- [S.E. Cartwright](/person/270)
- [Viscountess Falkland Lettice Cary](/person/2408)
- [Miss Cassell](/person/271)
- [Countess of Charlem Anne Caulfeild](/person/286)
- [Lord Frederick Charles Cavendish](/person/272)
- [Spencer Compton Cavendish](/person/2362)
- [Sidney Caxton](/person/273)
- [Annie Louise Cazenove](/person/274)
- [Mrs Cazenove](/person/275)
- [E.L. Chamberlain](/person/276)
- [Amelia Chamberlayne](/person/278)
- [Frederick Cranley Chamberlayne](/person/280)
- [Thomas Chamberlayne](/person/282)
- [Tankerville Chamberlayne](/person/2114)
- [Miss C. Chambers](/person/283)
- [Sir Edmund Kerchever Chambers](/person/284)
- [George H. Chambers](/person/2074)
- [Miss Chambers](/person/2133)
- [Elinor Champernowne](/person/285)
- [Mr Chandler](/person/1864)
- [Elizabeth Charles](/person/287)
- [J. E. Charles](/person/2251)
- [Maria Louisa Charlesworth](/person/2440)
- [E. F. Chawner](/person/288)
- [Miss Cheape](/person/289)
- [Eugénie-Caroline Chervet](/person/290)
- [Mrs Chester](/person/1682)
- [The Rev. Thomas Kelly Cheyne](/person/2103)
- [Beatrice Chichester](/person/2336)
- [Rosalie Amelia Chichester](/person/1744)
- [Sir Arthur Chichester](/person/2335)
- [M. F. Cholmondeley](/person/291)
- [Mary Cholmondeley](/person/292)
- [Alice M. Christie](/person/293)
- [Mary Elizabeth Christie](/person/294)
- [E. M. Church](/person/295)
- [Helen Frances Church](/person/296)
- [The Very Rev. Richard William Church](/person/297)
- [Charles Marcus Church](/person/2097)
- [General Sir Richard Church](/person/2098)
- [Mr. Churton](/person/303)
- [The Ven. Edward Churton](/person/298)
- [Chaloner William Chute](/person/299)
- [Charles Lennard Chute](/person/2113)
- [Eleanor Jane Chute](/person/2255)
- [Frances Mary Clarke](/person/301)
- [Theodora M. Louisa Lane Clarke](/person/300)
- [The Rev. James Langton Clarke](/person/2347)
- [Barbara Clay Finch](/person/302)
- [Mr. Cleaver](/person/304)
- [Mrs. Cleaver](/person/305)
- [Clare Cleland](/person/306)
- [Eliza Callahan Cleveland](/person/307)
- [Sarah Paine Cleveland](/person/1939)
- [M. F. Clifton](/person/308)
- [William Archibald Clowes](/person/309)
- [D. M. Clutterbuck](/person/310)
- [James Cobb](/person/311)
- [The Rev. Robert Henry Codrington](/person/312)
- [Mrs Codrington](/person/2294)
- [Lady Seaton Elizabeth Colborne](/person/314)
- [Field Marshal Sir 1st Lord Seaton John Colborne](/person/313)
- [Lady Seaton Charlotte Colborne](/person/316)
- [Major the Hon. 4th Lord Seaton James Ulysses Graham Raymond Colborne](/person/325)
- [The Hon. Alethea Elizabeth Catherine Colborne](/person/317)
- [The Hon. Cordelia Anne L'Estrange Colborne](/person/319)
- [The Hon. Edmund Colborne](/person/322)
- [The Hon. Elizabeth Colborne](/person/320)
- [The Hon. Francis Lionel Lydstone Colborne](/person/323)
- [The Hon. 2nd Lord Seaton James Colborne](/person/315)
- [The Hon. 3rd Lord Seaton John Reginald Upton Colborne](/person/318)
- [The Rev. and Hon. Graham Colborne](/person/321)
- [Colonel the Hon. John Colborne](/person/2357)
- [General the Hon. Sir Francis Colborne](/person/324)
- [The Hon. Alice Constantia Maria Colborne](/person/2104)
- [Nina Cole](/person/326)
- [The Rt. Rev. John William Colenso](/person/1872)
- [Thomas Drake Coleridge](/person/352)
- [Alice Mary Coleridge](/person/327)
- [Arthur Duke Coleridge](/person/328)
- [Christabel Rose Coleridge](/person/329)
- [David Hartley Coleridge](/person/330)
- [Edith Coleridge](/person/331)
- [Ellen Sophia Coleridge](/person/334)
- [Ernest Hartley Coleridge](/person/336)
- [Herbert Coleridge](/person/340)
- [Jane Fortescue Coleridge](/person/341)
- [John Derwent Coleridge](/person/342)
- [Margaret Eulalia Coleridge](/person/346)
- [Mary Alethea Coleridge](/person/927)
- [Mary Caroline Coleridge](/person/348)
- [Mary Coleridge](/person/347)
- [Mary Dorothea Moultrie Coleridge](/person/349)
- [Mary Elizabeth Coleridge](/person/350)
- [Mary Frances Keble Coleridge](/person/351)
- [Walter Henry Praed Coleridge](/person/353)
- [Amy Augusta Jackson Coleridge](/person/345)
- [3rd Lord Coleridge Geoffrey Duke Coleridge](/person/338)
- [Father Henry James Coleridge](/person/339)
- [Sir John Taylor Coleridge](/person/344)
- [Sir 1st Lord Coleridge John Duke Coleridge](/person/343)
- [The Rev. Edwin Ellis Coleridge](/person/333)
- [The Rev. Gerald Hartley Buchanan Coleridge](/person/337)
- [The Rt. Rev. William Hart Coleridge](/person/354)
- [Bernard John Seymour Coleridge](/person/2143)
- [Mary Simpson Coleridge](/person/1976)
- [Samuel Taylor Coleridge](/person/1667)
- [The Rev. Edward Coleridge](/person/332)
- [The Rev. Derwent Coleridge](/person/1900)
- [The Rev. James Duke Coleridge](/person/1892)
- [Margaret Collier](/person/355)
- [Mr. Collier](/person/356)
- [Anne Collins](/person/361)
- [Bessie Collins](/person/359)
- [Martha Collins](/person/360)
- [Elizabeth Collins](/person/358)
- [George Collins](/person/357)
- [Old Collins](/person/362)
- [Charles Collins](/person/1748)
- [Emma Collins](/person/2168)
- [Frances Collins](/person/2164)
- [George Collins](/person/1730)
- [Olive Collins](/person/1749)
- [Professor the Rev. William Edward Collins](/person/2250)
- [Amelia Collinson](/person/2021)
- [John Colson](/person/1887)
- [Betsy Comely](/person/363)
- [John Comely](/person/2176)
- [Agnes Charlotte Compton](/person/364)
- [Henry Francis Compton](/person/2118)
- [Mr Compton](/person/2174)
- [James Corry Connellan](/person/365)
- [Clara Eleanor Coode](/person/2385)
- [Caroline Elizabeth Cooke Trench](/person/367)
- [Thomas Richard Frederick Cooke Trench](/person/366)
- [Marie Corelli](/person/2135)
- [George Kestell Cornish](/person/2344)
- [Mr Cornthwaite](/person/1781)
- [Lodovico, Conte Corti](/person/2376)
- [James Sutherland Cotton](/person/2354)
- [Frances Charlotte Hilare Coulthard](/person/371)
- [James Batten Coulthard](/person/368)
- [James Batten Coulthard](/person/369)
- [Mary Coulthard](/person/370)
- [The Rev. Thomas Coulthard](/person/372)
- [The Rev. - Coward](/person/2129)
- [Mr Cowie](/person/373)
- [Jane Cowing](/person/374)
- [1st Lord Mount Temp William Francis Cowper-Temple](/person/1059)
- [Lady Mount Temple Georgiana Cowper-Temple](/person/1058)
- [Harriet Lucy Cox](/person/375)
- [The Rev. Joseph Mercer Cox](/person/376)
- [Miss ?Agnes Cox](/person/1642)
- [The Rev. Henry Octavius Coxe](/person/377)
- [Mr Coxwell](/person/1909)
- [Dinah Maria Craik](/person/378)
- [George Lillie Craik](/person/379)
- [Fanny Esther Craik](/person/2310)
- [Walter Crane](/person/2366)
- [Lady Crauford](/person/380)
- [Isolda Caroline Crauford](/person/2157)
- [Agnes Crawford](/person/2241)
- [Edith Crawley](/person/382)
- [Catharina Crawley](/person/1712)
- [Charlotte Elizabeth Crawley](/person/2073)
- [Sybella Mary Crawley Boevey](/person/381)
- [Arthur William Crawley Boevey](/person/1644)
- [Sir Martin Crawley Boevey](/person/1645)
- [Mary Albinia, Lady Crawley-Boevey](/person/2188)
- [Beatrix Feodore Cresswell](/person/383)
- [Maria Cristall](/person/384)
- [Croad](/person/1782)
- [Mrs Crocker](/person/2109)
- [Miss Crokat](/person/1711)
- [Mr Crokat](/person/1710)
- [Miss Croker](/person/385)
- [Henry Julian Cromie](/person/387)
- [Joanna Angela Cromie](/person/388)
- [Maurice Francis Cromie](/person/389)
- [Captain Charles Francis Cromie](/person/386)
- [Frances Eliza Crompton](/person/390)
- [Pieter Arnoldus Cronjé](/person/2213)
- [Mary Ann Cross](/person/2359)
- [The Rev. Canon John Henchman Crowfoot](/person/2230)
- [Charles George Crump](/person/391)
- [Annie Hall Cudlip](/person/392)
- [The Rev. Pender Hodge Cudlip](/person/393)
- [Elizabeth A. Curteis](/person/395)
- [Elizabeth Charlotte Curteis](/person/396)
- [Mrs. Curteis](/person/2034)
- [John Spencer Curwen](/person/2407)
- [The Rev. Henry Honywood D\'Ombrain](/person/2292)
- [Field Marshal Sir Richard James Dacres](/person/399)
- [Ann Biscoe Dallas](/person/400)
- [The Rev. Alexander Robert Charles Dallas](/person/401)
- [Mrs Dament](/person/402)
- [Emily Dampier](/person/404)
- [Margaret Sarah Dampier](/person/403)
- [William John Dampier](/person/2266)
- [Kate Danby](/person/405)
- [Georges Danton](/person/2421)
- [Monseigneur Georges Darboy](/person/406)
- [Cecil Darby](/person/407)
- [Miss Davies](/person/408)
- [Mr. Davies](/person/410)
- [The Rev. John Llewelyn Davies](/person/409)
- [Lucy Sarah Davies](/person/2180)
- [Sarah Emily Davies](/person/2014)
- [Mary Davis](/person/1752)
- [Thomas Davis](/person/2148)
- [Marianne Davys](/person/412)
- [The Rt. Rev. Dr. George Davys](/person/411)
- [Mrs Dawson](/person/413)
- [Vicomte Theodore Hersart De La Villemarqué](/person/414)
- [De Sombreuil](/person/416)
- [Thomasine Septima De Winton](/person/417)
- [Rachel De Witt](/person/429)
- [Conrad De Witt](/person/419)
- [Cornélis De Witt](/person/420)
- [Cornélis De Witt](/person/421)
- [Francois De Witt](/person/422)
- [Henriette Elizabeth De Witt](/person/423)
- [Jeanne De Witt](/person/424)
- [Marguérite De Witt](/person/425)
- [Marie De Witt](/person/426)
- [Pauline De Witt](/person/427)
- [Pierre De Witt](/person/428)
- [Robert De Witt](/person/430)
- [Suzanne De Witt](/person/431)
- [The Rt. Rev. William Heathcote DeLancey](/person/1728)
- [Mary Deane](/person/432)
- [Rachel Deedes](/person/433)
- [Charlotte Louisa Hawkins Dempster](/person/434)
- [The Rt. Rev. Edward Denison](/person/2137)
- [Mr Dennis](/person/435)
- [Mr Dennis](/person/2171)
- [Mrs Dennis](/person/2205)
- [Rosina Dewsall](/person/418)
- [Maidie Dickson](/person/436)
- [A. Diddams](/person/1681)
- [Venetia Digby](/person/1842)
- [William Chatterton Dix](/person/437)
- [Mr Dixon](/person/438)
- [The Rev. Charles Lutwidge Dodgson](/person/261)
- [Frances Jane Dodgson](/person/2423)
- [Florence N. Dodson](/person/439)
- [F. Malcolm Doherty](/person/440)
- [Mrs Donkin](/person/441)
- [The Rev. Mr Douglas](/person/442)
- [Emily Sophia Doyne](/person/2426)
- [Mary Drew](/person/443)
- [John Murray Drummond](/person/444)
- [Anna Harriet Drury](/person/445)
- [The Rev. James Thomas Houssemayne Du Boulay](/person/446)
- [Mary Du Boulay](/person/2247)
- [The Rev. Bemjamin Thornton Dudley](/person/1868)
- [Helena or Eleanor Dugay](/person/447)
- [The Rev. Canon James Duncan](/person/448)
- [A. Dundas](/person/449)
- [George Ralph Dundas](/person/451)
- [Louisa Dundas](/person/454)
- [Mary Frances Dundas](/person/455)
- [Lord Manour George Dundas](/person/452)
- [Captain James Dundas](/person/453)
- [Commander Colin MacKenzie Dundas](/person/450)
- [Elizabeth Christian Dundas](/person/2052)
- [Elizabeth Dundas](/person/1882)
- [Helen Anne Dundas](/person/2053)
- [Katherine Louisa Dundas](/person/2054)
- [The Rt. Rev. Andrew Hunter Dunn](/person/456)
- [Félix-Antoine-Philibert Dupanloup](/person/457)
- [Mrs Durndell](/person/459)
- [Mrs Edith Harriet Durst](/person/2442)
- [Miss Durton](/person/458)
- [Annie Victoria Dutton](/person/460)
- [Margaret Anne Dyer](/person/2274)
- [Elizabeth Dyson](/person/462)
- [Frank Dyson](/person/463)
- [Mary Anne Dyson](/person/464)
- [The Rev. Charles Dyson](/person/461)
- [Charlotte Elizabeth Dyson](/person/2016)
- [The Rev. Canon Francis Dyson](/person/1774)
- [Elsa D’Esterre-Keeling](/person/398)
- [Edward Eames](/person/465)
- [Annie Augusta H. Earle](/person/2319)
- [Elizabeth Eastlake](/person/1925)
- [Sarah Joan Easton](/person/466)
- [Sophia May Eckley](/person/467)
- [Horatia Katherine Frances Eden](/person/469)
- [The Rt. Rev. 3rd Lord Auckland Robert John Eden](/person/468)
- [Maria Edgeworth](/person/1819)
- [Richard Lovell Edgeworth](/person/1841)
- [Mrs Egerton](/person/470)
- [Horatia Sophia Elder](/person/471)
- [The Rev. Walter Francis Elgie](/person/478)
- [Arthur Elgie, later Elgee](/person/473)
- [Catharine Elgie, later Elgee](/person/474)
- [Catharine Elgie, later Elgee](/person/475)
- [Ernest Alfred Elgie, later Elgee](/person/476)
- [Hugh Francis Elgie, later Elgee](/person/477)
- [Isabel Charlotte Elgie, later Elgee](/person/479)
- [Cyril Hammond Elgie, later Elgee](/person/472)
- [Lady Caroline Georgiana Eliot](/person/480)
- [George Eliot](/person/1994)
- [The Rev. Canon Henry Nicholson Ellacombe](/person/481)
- [The Rt. Rev. Charles John Ellicott](/person/2141)
- [Mrs. Elphinstone](/person/482)
- [R. Fenwick Elrington](/person/483)
- [Fanny Maria Emery](/person/2106)
- [The Ven. Canon William Emery](/person/2107)
- [Emily](/person/484)
- [Queen Emma](/person/485)
- [Dr. William England](/person/488)
- [Dr. George Fuller Ashbridge England](/person/487)
- [Mrs England](/person/486)
- [Miss Ensor](/person/2280)
- [Miss Erle](/person/2010)
- [Miss Erskine](/person/489)
- [Margaret Evans](/person/490)
- [Mr Evans](/person/491)
- [Maria Evans](/person/1761)
- [M. C. Eve](/person/492)
- [Harry Sterling Crawfurd Everard](/person/493)
- [Frances Ann E. Ewan](/person/2248)
- [Juliana Horatia Ewing](/person/494)
- [Edward John Eyre](/person/1960)
- [Miss Eyre](/person/2008)
- [Father Frederic William Faber](/person/1859)
- [Sir 2nd Bt. Thomas Fairbairn](/person/496)
- [Allison Fairbairn](/person/2279)
- [Florence Margaret Fairbairn](/person/2439)
- [Edward Williams Faithfull](/person/497)
- [Miss Faithfull](/person/498)
- [Ann Fanshawe](/person/1835)
- [Robert B. Farren](/person/500)
- [Alice Farrer](/person/501)
- [Millicent Fawcett](/person/2380)
- [Miss Fawcett](/person/2395)
- [Anne Fay](/person/1679)
- [The Rev. William Andrewes Fearon](/person/502)
- [Anne Fellowes](/person/503)
- [K. S. Fenn](/person/504)
- [Gabriele Fiamma](/person/506)
- [J. E. Field](/person/508)
- [Louisa Fanny Field](/person/507)
- [Margaret Field](/person/509)
- [Judith Fielder](/person/1495)
- [Thomas Fielder](/person/1496)
- [Mr Fielder](/person/510)
- [Miss Finchcliffe](/person/511)
- [Marion Finlaison](/person/512)
- [Walter Fisher](/person/513)
- [Eliza? Fisher](/person/2394)
- [The Rev. J. Fletcher](/person/514)
- [The Rev. John William Fletcher](/person/1677)
- [Mr Flint](/person/515)
- [Elisabeth Jane Forbes](/person/517)
- [The Rt. Rev. Alexander Penrose Forbes](/person/516)
- [Miss Forrest](/person/2029)
- [H. J. Foster](/person/518)
- [H. M. Foster](/person/519)
- [Ellen Foster](/person/2353)
- [William Warde Fowler](/person/520)
- [William Fowlie](/person/521)
- [Otto Franke](/person/522)
- [Edward Augustus Freeman](/person/523)
- [Florence Freeman](/person/524)
- [Eleanor Freeman](/person/2383)
- [Elizabeth Freeman](/person/1846)
- [Major Freke](/person/1790)
- [Augusta Frederica Frere](/person/525)
- [Emily Georgiana Temple Frere](/person/526)
- [Gustav Freytag](/person/1918)
- [Francis Frith](/person/2195)
- [James Anthony Froude](/person/528)
- [William Froude](/person/530)
- [The Rev. Richard Hurrell Froude](/person/529)
- [The Ven. Richard Hurrell Froude](/person/527)
- [Elizabeth Fry](/person/1826)
- [Frederick James Furnivall](/person/531)
- [Adela Fursdon](/person/532)
- [Anna Wilhelmina Fursdon](/person/533)
- [Charlotte Sophia Fursdon](/person/534)
- [Edith Fursdon](/person/535)
- [Elizabeth Fursdon](/person/537)
- [Mary Penelope Fursdon](/person/539)
- [Henrietta Elizabeth Fursdon](/person/538)
- [The Rev. Edward Fursdon](/person/536)
- [Paul Féval](/person/505)
- [Rosa Gardiner](/person/2162)
- [Miss Garfit](/person/540)
- [Giuseppe Garibaldi](/person/1855)
- [Ellen Rayne Garnett](/person/543)
- [Lucy Mary Jane Garnett](/person/545)
- [Richard Garnett](/person/544)
- [The Very Rev. Thomas Garnier](/person/541)
- [The Very Rev. Thomas Garnier](/person/542)
- [Cordelia Garstin](/person/546)
- [Marchioness of Sal Georgina Caroline Gascoyne-Cecil](/person/548)
- [3rd Marquess of Sal Robert Arthur Talbot Gascoyne-Cecil](/person/547)
- [Elizabeth Cleghorn Gaskell](/person/1965)
- [General Sir William Forbes Gatacre](/person/2204)
- [Johanna Gatty](/person/550)
- [Margaret Gatty](/person/549)
- [The Rev. Alfred Gatty](/person/1823)
- [John Gaunt](/person/551)
- [Selina Gaye](/person/552)
- [Evelyn Gee](/person/553)
- [Caroline M. Gemmer](/person/554)
- [Dorothea Mary Stanislaus Gerard](/person/555)
- [Jane Emily Gerard](/person/556)
- [Henry Martin Gibbs](/person/559)
- [Matilda Blanche Gibbs](/person/557)
- [William Gibbs](/person/560)
- [1st Lord Aldenham Henry Hucks Gibbs](/person/558)
- [Albinia Anne Gibbs](/person/2373)
- [Antony Gibbs](/person/2371)
- [Janet Louisa Gibbs](/person/2372)
- [Louisa Anne Gibbs](/person/1856)
- [Agnes Giberne](/person/561)
- [William John Gibson](/person/562)
- [S. M. Gidley](/person/563)
- [Elizabeth Margaretta Maria Gilbert](/person/1878)
- [Tom Gilbert](/person/1725)
- [P. E. Gertrude Girdlestone](/person/564)
- [The Rt. Hon. William Ewart Gladstone](/person/1653)
- [Elizabeth Glaister](/person/565)
- [Alice Hilda Godman](/person/2410)
- [Margaret Godolphin](/person/1833)
- [Harriet Godwin](/person/2316)
- [Commodore James Goodenough](/person/2400)
- [A. M. Goodrich](/person/567)
- [Alice May Gordon](/person/572)
- [Jean Gordon](/person/570)
- [Mary Charlotte Julia Gordon](/person/569)
- [The Hon. Sir 1st Lord Stanmore Arthur Charles Hamilton Gordon](/person/568)
- [General Charles Gordon](/person/2090)
- [Constance Frederica Gordon Cumming](/person/571)
- [John Ellard Gore](/person/573)
- [G. Gorsuch](/person/574)
- [Laurent Gouvion](/person/2044)
- [Catherine Ponton Grant](/person/575)
- [1st Lord Glenelg Charles Grant](/person/576)
- [Anne Grant](/person/1825)
- [Sir Francis Grant](/person/1926)
- [Henry Graves](/person/577)
- [Sophia Wharton Gray](/person/579)
- [The Rt. Rev. Robert Gray](/person/578)
- [Sarah Ann Gream](/person/1816)
- [Samuel Stephenson Greatheed](/person/580)
- [Fanny L. Green](/person/581)
- [The Rev. John Richard Green](/person/582)
- [Mr Green](/person/1647)
- [Kate Greenaway](/person/2323)
- [The Hon. Mrs. Louisa Lilias Greene](/person/583)
- [Eleanor C. Gregory](/person/585)
- [The Rev. William Gresley](/person/1756)
- [Countess of Warwick Frances Evelyn Greville](/person/2198)
- [Sir George Grey](/person/1873)
- [Harriet Dyke Griffith](/person/1775)
- [Miss Grigg](/person/586)
- [Demetrius Grigorovitch](/person/587)
- [Mr Grimshaw](/person/2139)
- [Sir George Grove](/person/588)
- [Alice Grubbe](/person/589)
- [The Rev. Charles Septimus Grubbe](/person/590)
- [N.F.S. Grundtvig](/person/1770)
- [Charlotte Esther Sophia Guille](/person/1666)
- [Avice Mary Guinness](/person/592)
- [Elizabeth Maud Guinness](/person/593)
- [Grace Harriet Guinness](/person/594)
- [Henrietta Darley Guinness](/person/595)
- [Mary Geraldine Guinness](/person/596)
- [François-Pierre-Guillaume Guizot](/person/597)
- [Maurice Guillaume Guizot](/person/2047)
- [Sir William Withey Gull](/person/598)
- [Dr James Manby Gully](/person/599)
- [Maria Susan Gunner](/person/2172)
- [The Rev. William Henry Gunner](/person/1708)
- [Richard Thompson Gunton](/person/600)
- [The Rev. Alfred Gurney](/person/601)
- [Anna Gurney](/person/1824)
- [Mrs Guslett](/person/1669)
- [Eugénie de Guérin du Cayla](/person/1984)
- [Georges Maurice de Guérin du Cayla](/person/1985)
- [Seymour Haden](/person/602)
- [E. Hadwen](/person/603)
- [Henry Rider Haggard](/person/2156)
- [The Ven. Canon Henry Haigh](/person/2197)
- [The Rev. J. J. Halcombe](/person/604)
- [Miss Hale](/person/605)
- [Caroline Hale](/person/2173)
- [S. Elizabeth Hall](/person/607)
- [Fitzedward Hall](/person/2388)
- [Lt.-Col. Hall](/person/2429)
- [Miss Hall](/person/2396)
- [Caroline Maria Hallett](/person/608)
- [Edith Mary Halliday](/person/610)
- [Francis Noel Halliday](/person/612)
- [Gertrude Louisa Charlotte Halliday](/person/613)
- [Lionel Edward Halliday](/person/611)
- [Louisa Halliday](/person/616)
- [Medora Elizabeth Halliday](/person/615)
- [Violet Amy Halliday](/person/614)
- [General Francis Edward Halliday](/person/609)
- [James Orchard Halliwell](/person/1857)
- [Ethel Halsey](/person/617)
- [Ludovic Halévy](/person/606)
- [The Rt. Rev. Walter Kerr Hamilton](/person/2138)
- [Countess of Aberdeen Ishbel Maria Hamilton-Gordon](/person/2119)
- [The Hon. and Rev. Ca Douglas Hamilton-Gordon](/person/2130)
- [The Rev. Frederick Hammond](/person/618)
- [Lady Laura Elizabeth Hampton](/person/619)
- [George Frideric Handel](/person/1851)
- [The Rt. Hon Viscount Cranbrook, Gathorne Hardy](/person/620)
- [Mr Hare](/person/1791)
- [Claus Harmes](/person/621)
- [Joanna Dorothea Dyke Harper](/person/622)
- [The Rt. Rev. Henry John Chitty Harper](/person/623)
- [Jane Harper](/person/2360)
- [Jane Harris](/person/627)
- [Mary Josephine Yonge Harris](/person/626)
- [Percy Harris](/person/631)
- [William Harris](/person/632)
- [William Harris](/person/633)
- [Captain William Charles Harris](/person/624)
- [Dr. John Harris](/person/628)
- [Mrs Harris](/person/630)
- [The Rev. George Collyer Harris](/person/625)
- [The Rev. Joseph Hemington Harris](/person/629)
- [Edward Percy Harris](/person/2341)
- [George Montagu Harris](/person/2340)
- [Maria Matilda Harris](/person/1759)
- [F. Harrison](/person/637)
- [Robert Harrison](/person/635)
- [Sophia Jane Harrison](/person/638)
- [Fanny Harrison](/person/2260)
- [The Rev. William Dann Harrison](/person/636)
- [Thomas Elliot Harrison](/person/1971)
- [The Rev. Robert Everson Harrisson [sic]](/person/634)
- [Elizabeth Anna Hart](/person/639)
- [Mabel Hart](/person/640)
- [Mr Hart](/person/641)
- [Mrs Hartley](/person/642)
- [Mary Nunn Harvey](/person/643)
- [Harriet Harvey](/person/1751)
- [E. Hasell](/person/644)
- [Frances Ridley Havergal](/person/2091)
- [Mary Elizabeth Hawker](/person/499)
- [Mrs Hawkins](/person/645)
- [Anthony Hope Hawkins](/person/2155)
- [The Rev. John Hawksley](/person/646)
- [Clifford Hay](/person/647)
- [William Hay](/person/648)
- [William A. Haydn-Byrne](/person/649)
- [Florence H. Hayllar](/person/650)
- [Augusta C. Hayward](/person/651)
- [Henrietta Hazelby](/person/652)
- [Arthur Malcolm Heathcote](/person/653)
- [Beatrice Henrietta Heathcote](/person/655)
- [Caroline Heathcote](/person/657)
- [Elizabeth Heathcote](/person/658)
- [George Parker Heathcote](/person/660)
- [Grace Heathcote](/person/662)
- [Helena Mary Heathcote](/person/663)
- [Jennetta Alethea Heathcote](/person/656)
- [Letitia Maria Heathcote](/person/664)
- [Selina Frances Heathcote](/person/666)
- [Selina Heathcote](/person/665)
- [Major Charles George Heathcote](/person/670)
- [Sir Gilbert Redvers Heathcote](/person/671)
- [Sir William Arthur Heathcote](/person/672)
- [Sir William Heathcote](/person/669)
- [Sir William Perceval Heathcote](/person/668)
- [The Rev. Evelyn Dawsonne Heathcote](/person/659)
- [The Rev. Gilbert Vivyan Heathcote](/person/661)
- [The Rev. William Beadon Heathcote](/person/667)
- [Elizabeth Mary Heathcote](/person/1955)
- [Gertrude Mary Selina Heathcote](/person/2337)
- [Helen Mary Caroline Heathcote](/person/2338)
- [Isabella Margaretta Elizabeth Heathcote](/person/1690)
- [Margaret Mary Helen Heathcote](/person/2339)
- [Johann Peter Hebel](/person/673)
- [Anne Hedges](/person/674)
- [Margaret Heitland](/person/1895)
- [Fraulein Marie Heller](/person/1671)
- [Katherine Olive Helmore](/person/675)
- [Margaret Cecilia Helmore](/person/676)
- [Kate Wilson Helmore](/person/1934)
- [Sir Arthur Helps](/person/1814)
- [Felicia Dorothea Hemans](/person/1936)
- [William Henderson](/person/677)
- [The Rev. William George Henderson](/person/678)
- [Jane Henderson](/person/2401)
- [M. J. Herbert](/person/681)
- [Lady Lucy Caroline Herbert](/person/679)
- [Lady Harriet Jane Herbert](/person/680)
- [3rd Earl of Powis Edward James Herbert](/person/2076)
- [4th Earl of Carnarvo Henry Howard Molyneux Herbert](/person/2277)
- [Countess of Powis Lucy Herbert](/person/1871)
- [Elizabeth Mary Herbert](/person/1956)
- [The Hon. 1st Lord Herbert of Sidney Herbert](/person/1783)
- [Alexander Herculano de Carvalho e Araujo](/person/682)
- [L. Hereward](/person/683)
- [Hon. and Rt. Rev. Lo Arthur Charles Hervey](/person/2288)
- [A. M. Hewett](/person/684)
- [The Rev. William Edward Heygate](/person/685)
- [Charles Thomas John Hiatt](/person/2382)
- [Miss Hibberd](/person/2427)
- [C. Hibbert](/person/687)
- [Frances Alethea Hickes](/person/692)
- [Edmund Hicks](/person/689)
- [John Hicks](/person/688)
- [Mary Hicks](/person/690)
- [Mary Hicks](/person/691)
- [Anne Hicks](/person/2147)
- [Miss Higginbotham](/person/693)
- [Dorothy Higginson](/person/694)
- [Evelyn Matilda Hildyard](/person/695)
- [Miss Hill](/person/2102)
- [Katharine Hills](/person/696)
- [The Rev. William Jeffreys Hills](/person/697)
- [J. G. Hincks](/person/698)
- [Katharine Hinkson](/person/699)
- [Laura Hoare](/person/700)
- [Jane Hobart-Hampden](/person/701)
- [Sarah Maria Hobart-Hampden](/person/702)
- [The Rev. Alfred Bertie Hobart-Hampden](/person/703)
- [Violet Hobhouse](/person/704)
- [Elizabeth Hodson](/person/2020)
- [The Rev. Maurice Erskine Hoets](/person/705)
- [Edith Byard Hoets](/person/2238)
- [Mary Caroline Holbeach](/person/706)
- [Helen Holbeche](/person/2078)
- [Clifford Wyndham Holgate](/person/1643)
- [The Rev. Francis James Holland](/person/707)
- [Fanny Sophia Hollings](/person/708)
- [William Holman Hunt](/person/1912)
- [Dr Hood](/person/2275)
- [The Very Rev. Walter Farquhar Hook](/person/709)
- [Eliza Hooper](/person/710)
- [Jane Margaret Hooper](/person/711)
- [William Garrett Horder](/person/712)
- [John James Hornby](/person/1891)
- [Kezia Horne (or Herne?)](/person/713)
- [The Rev. John William Horsley](/person/2201)
- [A. F. Hort](/person/714)
- [Alice Horton](/person/715)
- [Robert Forman Horton](/person/716)
- [Ada Hoskins](/person/717)
- [Mr Hoskins](/person/718)
- [Eliza Hoskins](/person/2154)
- [D. Hoskyns](/person/719)
- [Walter Hotaswol](/person/1970)
- [Mr Houseman](/person/2146)
- [Alfred Edward Housman](/person/720)
- [Frances Ann How](/person/721)
- [The Rt. Rev. William Walsham How](/person/722)
- [Ellen Frances How](/person/2328)
- [Constance Howard](/person/723)
- [E. F. Howard](/person/724)
- [Francesca Maria Howard](/person/279)
- [7th Earl of Carlisle George William Frederick Howard](/person/255)
- [Catharine Augusta Howell](/person/725)
- [William Howitt](/person/726)
- [Mary Howitt](/person/1729)
- [Louis Huard](/person/2051)
- [Evariste Régis Huc](/person/728)
- [Emily Antoinette Hudson](/person/1959)
- [The Rev. Charles Hudson](/person/1958)
- [Thomas Hughes](/person/1924)
- [Flavien-Abel-Antoinin Hugonin](/person/2046)
- [Mary Emily Hullah](/person/729)
- [Ellen Humbert](/person/731)
- [Margaret Humbert](/person/732)
- [The Rev. Lewis Macnaughton Humbert](/person/730)
- [Ann Humbert](/person/2273)
- [Lewis Henry De Blois Humbert](/person/1995)
- [Alexander Humboldt](/person/733)
- [Sergeant Amos Humiston](/person/1941)
- [Margaret Huntingdon](/person/734)
- [The Rev. George William Huntingford](/person/1705)
- [The Rt. Rev. George Isaac Huntingford](/person/1706)
- [The Rev. George Huntington](/person/736)
- [Annie Groser Hurd](/person/737)
- [William Hurton](/person/738)
- [Miss Hutchins](/person/739)
- [The Rev. Henry Neville Hutchinson](/person/740)
- [Lucy Hutchinson](/person/1834)
- [Maria Elizabeth Hutchinson](/person/2009)
- [Thomas Henry Huxley](/person/2300)
- [Jean Ingelow](/person/741)
- [John Henry Ingram](/person/743)
- [The Very Rev. William Clavell Ingram](/person/742)
- [Arthur Donald Innes](/person/744)
- [Adeline Paulina Irby](/person/745)
- [Sidney Thomas Irwin](/person/746)
- [Miss Jackson](/person/1696)
- [Miss Jackson](/person/1861)
- [Edith Sophia Jacob](/person/749)
- [Gertrude Louisa Le Grand Jacob](/person/751)
- [The Rev. Eustace Wilberforce Jacob](/person/750)
- [The Rev. John Thomas Jacob](/person/747)
- [The Rt. Rev. Edgar Jacob](/person/748)
- [Major-General Sir George Le Grand Jacob](/person/2019)
- [Marianne Jacob](/person/2271)
- [The Ven. Canon Philip Jacob](/person/2018)
- [Mary Beatrice Jacson](/person/1962)
- [M. H. James](/person/752)
- [Wilhelmina Martha James](/person/754)
- [Kate Janvrin](/person/756)
- [The Rev. James Hemery Janvrin](/person/755)
- [The Rev. Canon George Edward Jelf](/person/757)
- [Madalene Sabine Jenkyns](/person/2379)
- [Elizabeth D. Jenner](/person/759)
- [Henry Jenner](/person/760)
- [Herbert S. Jenner](/person/761)
- [Katharine Lee Jenner](/person/764)
- [Katherine Amabel Jenner](/person/762)
- [Mary Jenner](/person/763)
- [Mildred J. Jenner](/person/765)
- [The Rt. Rev. Henry Lascelles Jenner](/person/758)
- [Mary Isabel Jenner](/person/2243)
- [The Hon. Caroline Mary Frances Jervis](/person/766)
- [Mrs Jewell](/person/767)
- [Charles Henry Johns](/person/770)
- [Edward Francis Johns](/person/771)
- [Ellen Julia Johns](/person/772)
- [The Rev. Charles Alexander Johns](/person/769)
- [Mary Johnson](/person/773)
- [Dr. Samuel Johnson](/person/1760)
- [The Rt. Rev. Edward Ralph Johnson](/person/2412)
- [Grace Leslie Keith Johnston](/person/774)
- [Priscilla Hannah Johnston](/person/775)
- [Agnes Johnstone](/person/277)
- [Grace Johnstone](/person/776)
- [Charlotte Jones](/person/777)
- [Dorothea Jones](/person/778)
- [Kate Emily Jones](/person/779)
- [M. Jones](/person/780)
- [Owen Jones](/person/782)
- [The Rev. Dr. John Collier Jones](/person/781)
- [Agnes Jones](/person/2011)
- [Amy Florence Jones-Bateman](/person/783)
- [Jessie Jones-Bateman](/person/784)
- [Rowland Jones-Bateman](/person/785)
- [Piet Joubert](/person/786)
- [The Rev. Benjamin Jowett](/person/1951)
- [Ellen Joyce](/person/787)
- [The Rev. John Julian](/person/788)
- [Richard F. Jupp](/person/790)
- [Miss Jupp](/person/789)
- [Maurice Justin](/person/791)
- [Dr Elisha Kent Kane](/person/1915)
- [Julia Kavanagh](/person/792)
- [Anna Maria Keary](/person/793)
- [Eliza Harriott Keary](/person/794)
- [John Keats](/person/1699)
- [Charlotte Keble](/person/795)
- [Elizabeth Jane Keble](/person/797)
- [Elizabeth Keble](/person/796)
- [Cornelia Sarah Keble](/person/800)
- [The Rev. John Keble](/person/798)
- [The Rev. Thomas Keble](/person/801)
- [The Rev. Thomas Keble](/person/799)
- [Henrietta Keddie](/person/802)
- [Thomas Keightley](/person/803)
- [Mrs Keir Moilliet](/person/804)
- [Charlotte Kekewich](/person/805)
- [Miss Kekewich](/person/806)
- [Lovedy Kelland](/person/1764)
- [H. W. Kelsey](/person/2071)
- [Elsie Kendall](/person/807)
- [May Kendall](/person/808)
- [Julia Elizabeth Kennedy](/person/2307)
- [Johannes Kepler](/person/1850)
- [8th Marquess of Lot William Schomberg Robert Kerr](/person/810)
- [Mch\'ness of Lothian Cecil Kerr](/person/809)
- [Admiral Lord Frederic Herbert Kerr](/person/811)
- [The Rev. Thomas Kerr](/person/1866)
- [Dorothy Kilner](/person/2095)
- [Sophia Agneta King](/person/812)
- [Frances Eliza Kingsley](/person/817)
- [The Rev. Charles Kingsley](/person/816)
- [Henry Kingsley](/person/1940)
- [Mr. Kingsman](/person/818)
- [Miss Kinloch](/person/813)
- [Miss Kirke](/person/2378)
- [Frances Anna Kitchener](/person/814)
- [The Very Rev. George William Kitchin](/person/815)
- [Miss Knapp](/person/2110)
- [1st Lord Brabourne Edward Hugessen Knatchbull-Hugessen](/person/819)
- [The Hon. Eva Mary Knatchbull-Hugessen](/person/820)
- [Edith Emma Knight](/person/822)
- [Henrietta Knight](/person/821)
- [Miss Knight](/person/1676)
- [Mrs Knight](/person/1767)
- [Henrietta Knight](/person/54)
- [Louisa Mary Knightley of Fawsley](/person/823)
- [Gertrude Caroline Knollys](/person/824)
- [Annie L. Knowles](/person/825)
- [Paul Kruger](/person/826)
- [Abraham Kuyper](/person/827)
- [Mary La Beaune](/person/1870)
- [Alexandrine de La Ferronnays](/person/1988)
- [J. La Peur](/person/828)
- [Edmund Henry Lacon Watson](/person/829)
- [Jean-Baptiste-Henri-Dominique Lacordaire](/person/830)
- [Ellen Laidlaw](/person/1820)
- [Margaret Elizabeth Laidlaw](/person/2269)
- [William Laidlaw](/person/2270)
- [Emily Cecilia Laing](/person/831)
- [Nesta Lake](/person/832)
- [Alphonse Lamartine](/person/833)
- [Henry Murray Lane](/person/836)
- [Andrew Lang](/person/834)
- [The Rev. William Cosmo Gordon Lang](/person/2089)
- [The Rev. Frederick Langbridge](/person/835)
- [Mrs Lange](/person/837)
- [Cora Langton](/person/838)
- [Amy Lascelles](/person/839)
- [Charlotte Latham](/person/840)
- [Diana Latham](/person/841)
- [Grace Latham](/person/842)
- [Dr. Peter Mere Latham](/person/844)
- [The Rev. Henry Latham](/person/843)
- [Mary Grace Latham](/person/2024)
- [Daniel Conner Lathbury](/person/2159)
- [Mary Elizabeth Latimer](/person/846)
- [Dr. (b.1859) Caroline Wormeley Latimer](/person/845)
- [Mrs Laurie](/person/847)
- [The Hon. Emily Lawless](/person/848)
- [Lieut.-Genl. Sir George St. Patrick Lawrence](/person/849)
- [Emily Lawrence](/person/2434)
- [Miss Lawrence](/person/2199)
- [Mr Layland](/person/850)
- [Charles Layton](/person/852)
- [Dorothea Layton](/person/851)
- [Monica Yonge Layton](/person/2200)
- [Miss Le Gallais](/person/855)
- [The Rev. Charles James Le Geyt](/person/856)
- [D. M. Leake](/person/857)
- [Mrs Percy Leake](/person/858)
- [Henrietta Louisa Lear](/person/859)
- [Major (later Lieut-C Alexander Learmonth](/person/1788)
- [Mary Susanna Lee](/person/861)
- [Catherine Harriet Lee](/person/860)
- [The Rev. Godfrey Bolles Lee](/person/2240)
- [Mr Lee or Lea](/person/853)
- [John Leech](/person/854)
- [Dora Leeke](/person/862)
- [Sophia Leeke](/person/1658)
- [Ella Napier Lefroy](/person/863)
- [Fanny Caroline Lefroy](/person/864)
- [Helena Lefroy](/person/865)
- [Marian Legge](/person/866)
- [E. M. Leigh](/person/867)
- [Prince Duke of Albany Leopold](/person/868)
- [Amélie Claire Leroy](/person/869)
- [Juliette Charlotte Leroy](/person/870)
- [Countess of Rothes Louisa Leslie](/person/1263)
- [Mrs Leslie](/person/871)
- [Frances Mary Levett](/person/872)
- [Miss Levett](/person/874)
- [Amy Judith Levy](/person/2381)
- [George Henry Lewes](/person/2160)
- [H.W. Lewis](/person/875)
- [Miss Lewis](/person/873)
- [The Rev. John Leybourne-Popham](/person/876)
- [The Rev. Canon John James Lias](/person/2227)
- [The Rev. Canon Henry Parry Liddon](/person/877)
- [Dame Light](/person/878)
- [Susan Light](/person/2149)
- [The Rev. Dr. John Prideaux Lightfoot](/person/879)
- [Lucy C. Lillie](/person/880)
- [Peter Lilly](/person/881)
- [Countess of Balcarre Elizabeth Lindsay](/person/1854)
- [Eliakim Littell](/person/883)
- [M. Little](/person/884)
- [The Rev. Dr. Richard Frederick Littledale](/person/885)
- [James Littlefield](/person/886)
- [Dr David Livingstone](/person/1935)
- [Miss Llewellyn](/person/2025)
- [Ann Catherine Lloyd](/person/887)
- [The Rev. John Henry Lloyd](/person/892)
- [The Ven. John Frederick Lloyd](/person/888)
- [The Rev. Walter Lock](/person/2140)
- [Amy Aubrey Locke](/person/893)
- [Elizabeth Crawford Lockhart](/person/889)
- [Daniel Logan](/person/2170)
- [Henry Wadsworth Longfellow](/person/1961)
- [The Rev. William Arthur Longlands](/person/890)
- [His Grace Charles Thomas Longley](/person/891)
- [Edith Agnes Longueville](/person/894)
- [Lucy Margaret Lonsdale](/person/896)
- [Sophia Lonsdale](/person/895)
- [The Rev. Canon John Gylby Lonsdale](/person/898)
- [Steven Lovelock](/person/2282)
- [Catherine Duke Low](/person/899)
- [Sampson Low](/person/1992)
- [Miss Lowden](/person/900)
- [The Rev. Edward Clarke Lowe](/person/901)
- [A. Lowndes](/person/902)
- [The Rev. Alfred Charles Lowth](/person/2215)
- [Charles-Jean-Marie Loyson](/person/903)
- [Clara Luard](/person/904)
- [Mr Lucas](/person/905)
- [Mildred Luckett](/person/906)
- [Ethel Anderdon Luke](/person/2321)
- [Alfred Lund](/person/908)
- [Mary Lund](/person/907)
- [Annie Lush](/person/909)
- [Elizabeth Lush](/person/1839)
- [The Rev. Vicesimus Lush](/person/1838)
- [Lionel William Lyde](/person/910)
- [Henry G. Lyford](/person/911)
- [6th Earl Beauchamp Frederick Lygon](/person/129)
- [Mrs Lynch](/person/2437)
- [Rear-Admiral Sir Edmund Lyons](/person/1757)
- [Annette M. Lyster](/person/912)
- [Mrs Lyth](/person/1920)
- [R. H. Lyttelton](/person/914)
- [4th Lord Lyttelton George William Lyttelton](/person/913)
- [The Rt. Rev. and Hon Arthur Temple Lyttelton](/person/2217)
- [John MacCulloch](/person/919)
- [Cecilia MacGregor](/person/921)
- [Anna Georgina Macaulay](/person/2352)
- [H. Macdonald](/person/920)
- [Alethea Buchanan Mackarness](/person/923)
- [Arthur John Coleridge Mackarness](/person/924)
- [Matilda Anne Mackarness](/person/928)
- [The Rt. Rev. John Fielder Mackarness](/person/926)
- [The Rt. Rev. George Richard Mackarness](/person/925)
- [Katharine Emily Margaret Mackarness](/person/2151)
- [The Rev. Charles Coleridge Mackarness](/person/1883)
- [Emily Mackay](/person/922)
- [Anne Mackenzie](/person/930)
- [Christina Mackenzie](/person/935)
- [Chrystal Mackenzie](/person/931)
- [Fergus Mackenzie](/person/932)
- [James Hay Mackenzie](/person/933)
- [John Mackenzie](/person/934)
- [The Rt. Rev. Charles Frederick Mackenzie](/person/929)
- [Donald J. Mackey](/person/936)
- [The Rev. Canon Donald John Mackey](/person/1683)
- [Sir James Mackintosh](/person/2208)
- [Miss Maclean](/person/2325)
- [The Rev. George Frederick Maclear](/person/937)
- [The Rev. A. Macleare](/person/938)
- [Alexander Macmillan](/person/939)
- [Caroline Macmillan](/person/940)
- [Frances Eliza Macmillan](/person/941)
- [Maurice Crawford Macmillan](/person/915)
- [Sir Frederick Orridge Macmillan](/person/942)
- [George Augustin Macmillan](/person/1946)
- [Malcolm Kingsley Macmillan](/person/1945)
- [The Rev. Hugh Macmillan](/person/2430)
- [William Alexander Macmillan](/person/1903)
- [Elizabeth Emily Maconchy](/person/945)
- [Katharine Sarah Macquoid](/person/943)
- [The Rt. Rev. William Kenneth Macrorie](/person/2027)
- [The Rev. Arthur Roland Maddison](/person/944)
- [Ella Fuller Maitland](/person/947)
- [Julia Charlotte Maitland](/person/946)
- [Edward Malleson](/person/948)
- [Richard Mallock](/person/2246)
- [Anne Manning](/person/949)
- [E. Australie Manning](/person/950)
- [Cardinal Henry Edward Manning](/person/951)
- [Captain Charles Augustus Manning](/person/1885)
- [Miss Manning](/person/2001)
- [Georgina Mansfield](/person/952)
- [Count Alessandro Manzoni](/person/953)
- [Charlotte Mapletoft](/person/954)
- [Evelyn March-Phillipps](/person/955)
- [Bertha, Baroness von Marenholtz-Bülow](/person/2332)
- [Queen Margherita](/person/956)
- [Maria Marriott](/person/958)
- [Mary Ann Marriott](/person/959)
- [Miss Marriott](/person/957)
- [The Rev. Charles Marriott](/person/961)
- [The Rev. John Marriott](/person/960)
- [Captain Frederick Marryat](/person/962)
- [Truda Marsh](/person/963)
- [Emma Marshall](/person/964)
- [Julia Elizabeth Marshall](/person/965)
- [Martha](/person/966)
- [Dora Frances Martin](/person/968)
- [Mary Anne Frances Martin](/person/971)
- [Caroline Martin](/person/967)
- [Jane Martin](/person/969)
- [Lady Mary Ann Martin](/person/970)
- [Sir William Martin](/person/972)
- [Miss Martin](/person/2105)
- [Sarah Martin](/person/1828)
- [Sir Richard Edward Rowley Martin](/person/1670)
- [Harriet Martineau](/person/1724)
- [Mary Sophia Paulina Martyn](/person/973)
- [Sophia Martyn](/person/974)
- [The Rev. Thomas Waddon Martyn](/person/1890)
- [The Rev. William Maskell](/person/975)
- [Mason](/person/978)
- [Alfred Edward Woodley Mason](/person/976)
- [Charlotte Frances Mason](/person/979)
- [Joseph Mason](/person/977)
- [Charlotte Mason](/person/2100)
- [Harry Mason](/person/1750)
- [Maria Mason](/person/1702)
- [David Masson,](/person/980)
- [Joseph Masters](/person/981)
- [Louisa Harriet Eyre Matcham](/person/982)
- [George Matcham](/person/1792)
- [Mrs A. M. Matthew](/person/1689)
- [Mrs Matthews](/person/983)
- [Henry Churchill Maxwell-Lyte](/person/2375)
- [Giuseppe Mazzini](/person/2368)
- [The Rt. Rev. Samuel Allen McCoskry](/person/984)
- [L.M. McCraith](/person/986)
- [M.C. McDougall](/person/987)
- [Harriette McDougall](/person/1949)
- [The Rt. Rev. Francis Thomas McDougall](/person/1948)
- [Blanche Catherine Medhurst](/person/988)
- [The Rev. John Medley](/person/916)
- [M. J.C. Meiklejohn](/person/989)
- [Madame Melon](/person/2031)
- [Sarah Anne Mercier](/person/990)
- [Jane Augusta Merriman](/person/992)
- [Miss Merriman](/person/991)
- [The Rev. Henry Gordon Merriman](/person/993)
- [R. Metcalfe](/person/994)
- [Francisque Michel](/person/2032)
- [Captain Middleton](/person/1780)
- [Evelyn Mary St. John Mildmay](/person/996)
- [The Ven. Carew St. John Mildmay](/person/995)
- [M Mildmay](/person/1697)
- [Euphemia Chalmers Millais](/person/1927)
- [Sir John Everett Millais](/person/1911)
- [Fanny Millar](/person/997)
- [C. Miller](/person/999)
- [G. Miller](/person/998)
- [Hugh Miller](/person/1813)
- [Ellen J. Millington](/person/1000)
- [Louise Jordan Miln](/person/1001)
- [Laura Milner](/person/1002)
- [H. Milnes](/person/1003)
- [A. Milukoff](/person/1004)
- [H. H. Minchin](/person/1005)
- [James Minipa](/person/2283)
- [Ellen Misselbrook](/person/1006)
- [Elizabeth Harcourt Mitchell](/person/1007)
- [Lilian Mary Mitchell](/person/1008)
- [Mrs Mitchell](/person/2317)
- [Mrs H. E. Moberley](/person/1010)
- [Alice Arbuthnot Moberly](/person/1025)
- [Arthur Moberly](/person/1011)
- [Charlotte Anne Elizabeth Moberly](/person/1024)
- [Edith Emily Moberly](/person/1012)
- [Edward Hugh Moberly](/person/1013)
- [George Herbert Moberly](/person/1014)
- [Harriet Rosa Moberly](/person/1022)
- [Henry Edward Moberly](/person/1016)
- [John Cornelius Moberly](/person/1017)
- [Louisa Henrietta Moberly](/person/1018)
- [Mary Ann Moberly](/person/1019)
- [Mary Grafton Moberly](/person/1023)
- [Walter Allan Moberly](/person/1027)
- [Selwyn William Moberly](/person/1026)
- [The Rev. Robert Campbell Moberly](/person/1021)
- [The Rt. Rev. George Moberly](/person/1015)
- [Alfred Moberly](/person/1860)
- [Charles Moberly](/person/1707)
- [Sir Walter Hamilton Moberly](/person/2239)
- [Mary Louisa Molesworth](/person/1028)
- [Olive Molesworth](/person/1029)
- [Helmuth Karl von Moltke](/person/2268)
- [1st Lord Houghton Richard Monckton Milnes](/person/2033)
- [William Cosmo Monkhouse](/person/1030)
- [E. Monro](/person/1031)
- [Caroline Albinia Monro](/person/1033)
- [The Rev. Percy Monro](/person/1032)
- [Charles-Forbes-René Montalembert](/person/1034)
- [? Montgolfier](/person/1035)
- [Jacques-Étienne Montgolfier](/person/1036)
- [Joseph-Michel Montgolfier](/person/1037)
- [Jessie Douglas Montgomery](/person/1040)
- [Kathleen Montgomery](/person/1038)
- [Letitia Montgomery](/person/1039)
- [Jane Montgomery Moore](/person/1042)
- [General Sir Alexander George Montgomery Moore](/person/1041)
- [Frances Dorothy Moor](/person/1044)
- [John Frewen Moor](/person/1045)
- [Philip Moor](/person/1047)
- [Selina Mary Moor](/person/1048)
- [Walter Vincent Wilberforce Moor](/person/1049)
- [The Rev. Charles Moor](/person/1043)
- [The Rev. John Frewen Moor](/person/1046)
- [John Frewen Moor](/person/2056)
- [Fanny G. Moore](/person/1052)
- [Mary Moore](/person/1051)
- [Stephen Roger Moore](/person/1050)
- [Miss Moorsom](/person/1053)
- [Olimpia Morata](/person/1849)
- [Hannah More](/person/1836)
- [Georgina S. Morgan](/person/1055)
- [The Rev. Arthur Middlemore Morgan](/person/1054)
- [Edith Moriston](/person/1056)
- [The Rev. Matthew Calley Morton](/person/1057)
- [Margaret Jane Mowbray](/person/1060)
- [Sir John Robert Mowbray](/person/2441)
- [Anne Mozley](/person/1061)
- [Charles Mozley](/person/1063)
- [Jemima Charlotte Mozley](/person/1064)
- [John Mozley](/person/1065)
- [Harriett Elizabeth Mozley](/person/1062)
- [The Rev. Thomas Mozley](/person/1066)
- [Miss Mudge](/person/1067)
- [Zachary Mudge](/person/1777)
- [Nitya Gopal Mukherji](/person/1068)
- [Mr Mules](/person/1069)
- [C. Wilhelm W. Muller](/person/1070)
- [John Mullins](/person/2189)
- [William Mulready](/person/2206)
- [Peter Andreas Munch](/person/1071)
- [Miss Munro](/person/2272)
- [Joachim Murat](/person/2416)
- [Edward A. Murray](/person/1072)
- [Henrietta Murray](/person/1073)
- [Sir James Augustus Henry Murray](/person/1074)
- [John Murray](/person/2312)
- [H. Musgrave](/person/1075)
- [William Henry Myers](/person/2115)
- [The Rt. Rev. Louis George Mylne](/person/1076)
- [Marianne von Nathusius](/person/1077)
- [The Rev. Dr. John Mason Neale](/person/1078)
- [Sarah Norman Neale](/person/1815)
- [Albertine-Adrienne Necker](/person/1080)
- [Suzanne Necker](/person/1079)
- [3rd Earl Nelson Horatio Nelson](/person/1081)
- [The Rev. 1st Earl Nelson William Nelson](/person/1082)
- [1st Viscount Nelson Horatio Nelson](/person/2043)
- [Countess Nelson Frances Elizabeth Nelson](/person/2219)
- [Mrs Newland](/person/1083)
- [Cardinal John Henry Newman](/person/1084)
- [Czar of Russia Nicholas I](/person/1085)
- [Florence Nightingale](/person/1086)
- [Frances Nightingale](/person/1087)
- [Edwin Nobbs](/person/1907)
- [The Rev. George Hunn Nobbs](/person/1986)
- [John Nonono](/person/2284)
- [Anne Norgate](/person/917)
- [Anne Norgate](/person/2122)
- [William Norgate](/person/2123)
- [Florence Gertrude Norsworthy](/person/1089)
- [Miss North](/person/1090)
- [The Rev. 6th Earl of Guilford Francis North](/person/591)
- [Earl of Iddesleigh Stafford Henry Northcote](/person/2363)
- [Northcote](/person/1692)
- [Caroline Elizabeth Sarah Norton](/person/1978)
- [The Rev. Dr. George Nott](/person/1091)
- [D. Nutt](/person/1092)
- [Oakley](/person/2194)
- [H. O. Ogilvie-Grant](/person/1098)
- [12th Earl of Airlie David William Stanley Ogilvy](/person/1094)
- [Countess of Airlie Mabell Frances Elizabeth Ogilvy](/person/1095)
- [Cordelia Anne Duke Oldfield](/person/1099)
- [Colonel John Rawdon Oldfield](/person/2128)
- [General John Oldfield](/person/1100)
- [Susan Oldfield](/person/2374)
- [Margaret Oliphant Oliphant](/person/1101)
- [The Rt. Rev. Benjamin Treadwell Onderdonk](/person/1727)
- [Blanche Oram](/person/1103)
- [duc de Montpensier Antoine Marie Philippe Louis Orleans](/person/918)
- [Mrs Orpen](/person/1104)
- [James Ripley Osgood](/person/2367)
- [Elizabeth Jane Oswald](/person/1105)
- [Amelia Jane Oswald](/person/1106)
- [Ymal Oswin](/person/1107)
- [Élise Charlotte Otté](/person/1923)
- [Helen Ouston](/person/1108)
- [A. C. Owen](/person/1110)
- [Mr. Owen](/person/1111)
- [The Rev. Nutcombe Oxenham](/person/1109)
- [Constance O’Brien](/person/1093)
- [John O’Donovan](/person/1916)
- [Kathleen O’Meara](/person/1096)
- [Moira O’Neill](/person/1097)
- [Penelope Anne Laura Packe](/person/1112)
- [H. Packer](/person/1120)
- [Sir George Paget](/person/1121)
- [Sir James Paget](/person/1802)
- [The Rev. Francis Edward Paget](/person/1758)
- [Cuthbert Macleod Paine](/person/1122)
- [Sara Hammond Palfrey](/person/1123)
- [Francis Turner Palgrave](/person/1124)
- [Mary E., Palgrave](/person/1127)
- [Sir Francis Palgrave](/person/1126)
- [Elizabeth Palgrave](/person/1125)
- [Louisa Catherine Palmer](/person/1131)
- [Mary Anne Palmer](/person/1132)
- [1st Earl of Selborn Roundell Palmer](/person/1129)
- [Lady Sophia Matilda Palmer](/person/1133)
- [The Rev. William Palmer](/person/1130)
- [The Ven Edwin Palmer](/person/1128)
- [Jessie Mary Ann Palmer](/person/2169)
- [Laura Palmer](/person/2299)
- [Sarah Matilda Palmer](/person/2064)
- [The Rev. John Palmer](/person/1884)
- [Charlotte Pantatun](/person/2065)
- [Emily Pantatun](/person/2061)
- [Fisher Pantatun](/person/2005)
- [Robert Pantatun](/person/2004)
- [Jane Ellen Panton](/person/1135)
- [N. Panton](/person/1134)
- [Cicely Gertrude Papillon](/person/1138)
- [E. T. Papillon](/person/1139)
- [Emily Caroline Papillon](/person/1136)
- [Muriel Caroline Papillon](/person/1137)
- [Beatrice Emily Papillon](/person/2263)
- [R. Pardepp](/person/1140)
- [John Henry Parker](/person/1142)
- [John William Parker](/person/1143)
- [John William Parker](/person/1144)
- [Ctss of Macclesfield Mary Parker](/person/1655)
- [James Parker](/person/2349)
- [C. Parkinson](/person/1141)
- [Elizabeth Parkinson](/person/1145)
- [Ann Parnell](/person/2070)
- [Harriet Parr](/person/1148)
- [Eleanor Victoria Parsons](/person/2305)
- [Charlotte Champion Pascoe](/person/1146)
- [The Rev. Thomas Pascoe](/person/1147)
- [Lydia Pasvorang](/person/2062)
- [William Pasvorang](/person/2059)
- [Arthur Paterson](/person/1149)
- [Frances Mary Patteson](/person/1150)
- [Frances Sophia Coleridge Patteson](/person/1151)
- [James Henry Patteson](/person/1152)
- [Janet Coleridge Patteson](/person/1153)
- [Joanna Elizabeth Patteson](/person/1154)
- [Miss Patteson](/person/335)
- [Sir John Patteson](/person/1156)
- [The Rt. Rev. John Coleridge Patteson](/person/1155)
- [Frances Duke Patteson](/person/1889)
- [Margaret Agnes Paul](/person/1157)
- [Elizabeth Pauli](/person/1113)
- [Reinhold Pauli](/person/1114)
- [H. Payne](/person/1158)
- [Mr Payne](/person/1809)
- [George Peabody](/person/1990)
- [Frances Mary Peard](/person/1160)
- [John Whitehead Peard](/person/1159)
- [Frances Cooke Peard](/person/2390)
- [Jane Frances Pearson](/person/1161)
- [Charles Henry Pearson](/person/2432)
- [J. Pedder](/person/1162)
- [Sir Robert Peel](/person/2037)
- [Mr Pell](/person/1701)
- [B. J. Pennington](/person/1163)
- [Fanny Emily Penny](/person/1164)
- [Teresa Penprase](/person/1796)
- [Frances Charlotte Perceval](/person/1166)
- [The Rev. and Hon. Arthur Perceval](/person/1165)
- [The Rt. Rev. and Hon Hugh Percy](/person/1726)
- [Mrs Perowne](/person/1663)
- [Alice Perrin](/person/1115)
- [Frances Elizabeth Perrin](/person/1116)
- [Mary Perry](/person/1167)
- [Caroline Perthes](/person/1827)
- [Jessie Peters](/person/1168)
- [Miss Peterson](/person/1169)
- [Lucy Phillimore](/person/1170)
- [Miss Phillpotts](/person/1171)
- [The Right Rev. Henry Phillpotts](/person/1778)
- [Amedée Pichot](/person/1172)
- [E.H. Pitcairn](/person/1173)
- [F.C. Playne](/person/1174)
- [Mary Plowman](/person/266)
- [1st Viscount Plumer Herbert Charles Onslow Plumer](/person/2203)
- [C. E. Plumptre](/person/1176)
- [The Very Rev. Edward Hayes Plumptre](/person/1175)
- [Henry Plumridge](/person/1177)
- [Mary Elizabeth Plumridge](/person/1178)
- [Anne Duke Pode](/person/1179)
- [Augusta Boevey Pode](/person/1180)
- [Beatrice Catharina Pode](/person/1181)
- [Charles Coleridge Pode](/person/1182)
- [Ernest Duke Yonge Pode](/person/1183)
- [John Duke Pode](/person/1184)
- [Alfred William Pollard](/person/1185)
- [John Hungerford Pollen](/person/1800)
- [Edith Caroline Pollock](/person/1186)
- [Catharina K. Polson](/person/1193)
- [Arthur Polson](/person/1190)
- [George Polson](/person/1191)
- [Georgiana Polson](/person/1194)
- [Rosalia Polson](/person/1192)
- [The Rev. Hugh Polson](/person/1195)
- [Bessie Annie Pond](/person/1648)
- [Edith Pond](/person/2231)
- [Sir Henry Ponsonby](/person/2365)
- [Alice F. S. Poole](/person/1188)
- [Harriet Poole](/person/1187)
- [Melville Portal](/person/1196)
- [Alfrey Porter](/person/1189)
- [Isa J. Postgate](/person/1197)
- [Lucilla Powell](/person/1198)
- [Thomas Powell](/person/1199)
- [Ethel Julia Pratt](/person/1204)
- [Fanny Mary Harriet Pratt](/person/1202)
- [Florence Maria Pratt](/person/1203)
- [Mary Josephine Pratt](/person/1205)
- [Mary Anne Pratt](/person/1201)
- [The Rev. Canon Henry Pratt](/person/1200)
- [Captain Prendergast](/person/1779)
- [Élise Françoise Louise Pressensé](/person/1206)
- [Constance Margaret Prevost](/person/1207)
- [The Rev. Sir George Prevost](/person/1713)
- [Eleanor Catharine Price](/person/1209)
- [The Rev. Bartholomew Price](/person/1208)
- [Prichard](/person/1893)
- [M. V. Prideaux](/person/1210)
- [Mary R. Pridham](/person/1211)
- [Lady Dalmeny Catherine Lucy Primrose](/person/1773)
- [The Rev. Lonsdale Pritt](/person/1867)
- [Richard A. Proctor](/person/1212)
- [Samuel Prout](/person/1213)
- [The Rev. George Rundle Prynne](/person/1214)
- [William Owen Pughe](/person/1917)
- [Lucy Maria Bouverie Pusey](/person/1216)
- [The Rev. Edward Bouverie Pusey](/person/1215)
- [George Palmer Putnam](/person/1217)
- [Emily Charlotte Pye](/person/1218)
- [Richard Quain](/person/1219)
- [Mabel Quiller Couch](/person/1220)
- [Raby](/person/1221)
- [Charles Raikes](/person/1223)
- [The Rev. Richard William Randall](/person/1222)
- [Robert Rawlinson](/person/1224)
- [Alice Julia Rawnsley](/person/1226)
- [Willingham Franklin Rawnsley](/person/1225)
- [Caroline Ray](/person/2190)
- [Charles Ray](/person/2111)
- [Dorothy Read](/person/1227)
- [Florence Reason](/person/1228)
- [Miss Redgrave](/person/2411)
- [Sir Thomas Reed](/person/1229)
- [Mrs Reeves](/person/1230)
- [Captain Thomas Mayne Reid](/person/1944)
- [Repton](/person/1888)
- [Amyas Revett](/person/1231)
- [Annie Reynolds](/person/2192)
- [The Rev. William Upton Richards](/person/1232)
- [Sir John Richardson](/person/1950)
- [D. Richmond](/person/1233)
- [George Richmond](/person/1731)
- [Edith C. Rickards](/person/1234)
- [Arthur Rickett](/person/1235)
- [Mrs. Ricketts](/person/1236)
- [Mary Louisa Ridding](/person/1020)
- [Lady Laura Elizabeth Ridding](/person/1238)
- [The Rt. Rev. George Ridding](/person/1237)
- [John Athelstan Laurie Riley](/person/1239)
- [Hon. Andalusia Laura Charlotte Georgina Riley](/person/2121)
- [Anne Isabella Ritchie](/person/1240)
- [Francis Hansard Rivington](/person/1991)
- [Sarah Cook Robbins](/person/1983)
- [Elizabeth H. Roberts](/person/1242)
- [Margaret Eliza Roberts](/person/1244)
- [Elizabeth P. Roberts](/person/1243)
- [Ralph Roberts](/person/1246)
- [Field-Marshall 1st Earl Roberts Frederick Sleigh Roberts](/person/2258)
- [The Rev. ? Roberts](/person/2236)
- [Miss Robertson](/person/1250)
- [Henrietta Robertson](/person/1952)
- [The Rev. R. I. Robertson](/person/1953)
- [Maximilien de Robespierre](/person/2420)
- [G. M. Robins](/person/1247)
- [Frederick S. Robinson](/person/1248)
- [Phil Robinson](/person/1249)
- [The Rev. John Medows Rodwell](/person/2386)
- [Charlotte Grenfell Bridgman Rogers](/person/1251)
- [Grace Rogers](/person/1255)
- [Mary Sophia Rogers](/person/1254)
- [Lady Blachford Georgiana Mary Rogers](/person/1253)
- [Sir 1st Lord Blachford Frederic Rogers](/person/1252)
- [Marcella Rogers](/person/2072)
- [Mr Rogers](/person/2049)
- [Alfred Rolfe](/person/1256)
- [Alice Rolfe](/person/1257)
- [Ethel Romanes](/person/1258)
- [George John Romanes](/person/2136)
- [Harriet Catherine Romanoff](/person/1259)
- [Margaret Roper](/person/1881)
- [William Roscoe](/person/1260)
- [Thomas Roscoe](/person/1974)
- [Beatrice Esther Rosenthal](/person/1262)
- [The Rev. Michael Rosenthal](/person/1261)
- [Miss Routledge](/person/1264)
- [Mrs Royle](/person/1265)
- [Margaret Blagrove Rudd](/person/1266)
- [Mr. Rudd](/person/1267)
- [Edward de Montjoie Rudolf](/person/1119)
- [John Ruskin](/person/1268)
- [William Howard Russell](/person/1270)
- [Rachel Russell](/person/1847)
- [J. Rutter](/person/1269)
- [Henry William Salmon](/person/2193)
- [George Sanger](/person/1271)
- [Sara Sarawia](/person/2002)
- [The Rev. George Sarawia](/person/1980)
- [Miss Saunders](/person/1282)
- [Elizabeth A. Savage](/person/2)
- [William Savage](/person/1283)
- [Marsden Sawa](/person/2060)
- [Rhoda Sawa](/person/2063)
- [The Rev. Stephen Henry Saxby](/person/2397)
- [J. B. Scarlett](/person/1284)
- [Major Robert Lawrence Scarlett](/person/1285)
- [Arabella Lucy Scarlett](/person/2218)
- [John Robson Scarlett](/person/2370)
- [The Rev. John Scarth](/person/1272)
- [Lina Schneider](/person/1286)
- [Catalina Schuyler](/person/1837)
- [Temple Scott](/person/1290)
- [Lady Annette Louisa Scott](/person/1288)
- [Lady Maria Henrietta Scott](/person/1287)
- [3rd Earl of Clonmell John Henry Scott](/person/1787)
- [Countess of Clonmell Anne Scott](/person/1794)
- [Lady Rachel Mary Scott](/person/1289)
- [Margaretta Scott](/person/2435)
- [Sir Walter Scott](/person/1672)
- [The Rev. Thomas Scott](/person/2315)
- [Mrs. Scroffs](/person/1291)
- [Emma Frances Scroggs](/person/1999)
- [The Rev. Sydney Malet Scroggs](/person/1998)
- [Daniel Sedgwick](/person/1292)
- [Rose E. Selfe](/person/1293)
- [Priscilla Lydia Sellon](/person/1294)
- [Sarah Harriet Selwyn](/person/1297)
- [The Rt. Rev. George Augustus Selwyn](/person/1295)
- [The Rt. Rev. John Richardson Selwyn](/person/1296)
- [Annie Catherine Selwyn](/person/1685)
- [Laetitia Frances Selwyn](/person/2281)
- [Captain Raphael Semmes](/person/1273)
- [Ivan Serg’eeff](/person/1298)
- [Mary Ellen Sewell](/person/1300)
- [Eleanor L Sewell](/person/1299)
- [Elizabeth Missing Sewell](/person/1301)
- [Ellen M. Sewell](/person/1302)
- [Emma F. Sewell](/person/1303)
- [Janetta Sewell](/person/1305)
- [The Rev. James Edwards Sewell](/person/1304)
- [The Rev. William Sewell](/person/1306)
- [Mrs Sewell](/person/2220)
- [Elizabeth Welman Seymour](/person/1307)
- [Anna Jane Seymour](/person/495)
- [Countess of Hertfor Emily Seymour](/person/1274)
- [Miss Seymour](/person/1308)
- [The Rev. George Augustus Seymour](/person/1309)
- [Countess of Hertford Frances Seymour](/person/1831)
- [Helen Frances Shadwell](/person/1808)
- [E. I. Shand](/person/1310)
- [Blanche Shelley](/person/1822)
- [John Shepherd](/person/2304)
- [Mary Martha Sherwood](/person/1869)
- [Anna Maria Shipley](/person/1314)
- [Conway Mordaunt Shipley](/person/1313)
- [The Rev. Charles Shipley](/person/1312)
- [The Rev. Orby Shipley](/person/1315)
- [Mrs Shipley](/person/2324)
- [A. C. Shipton](/person/1316)
- [Helen Shipton](/person/1317)
- [Mother Shipton](/person/2399)
- [Emily Anne Eliza Shirreff](/person/2330)
- [The Rt. Rev. Thomas Vowler Short](/person/1507)
- [Clement King Shorter](/person/1650)
- [Joseph Henry Shorthouse](/person/1654)
- [The Rev. Reginald Neale Shutte](/person/1318)
- [H. C. Shuttleworth](/person/1319)
- [Mr Siddon](/person/1320)
- [Amalie Sieveking](/person/1845)
- [Mr Sillence](/person/1321)
- [The Rev. Ernest Wollaston Silver](/person/2086)
- [James Sime](/person/2286)
- [Edith Jane Simeon](/person/1325)
- [Sarah Jane Simeon](/person/1323)
- [Winifred Louisa Simeon](/person/1324)
- [Captain Charles Simeon](/person/1322)
- [The Rev. Charles Simeon](/person/1275)
- [The Rev. Geoffrey Barrington Simeon](/person/2175)
- [Simmonds](/person/1762)
- [Mary Emily Simpson](/person/1326)
- [The Rev. Francis Simpson](/person/1844)
- [Janet M. Sinclair](/person/1327)
- [Felicia Mary Frances Skene](/person/1328)
- [John Skinner](/person/1330)
- [The Rev. James Skinner](/person/1329)
- [C. P. Slater](/person/1331)
- [The Rev. Charles Sloggett](/person/2314)
- [Jane Small](/person/1333)
- [Marianne Small](/person/1332)
- [Elizabeth Small](/person/1721)
- [Susan Smedes](/person/2398)
- [Menella Bute Smedley](/person/2346)
- [Sydney Smirke](/person/1334)
- [Elizabeth Smith](/person/1335)
- [Gerald W. Smith](/person/1336)
- [Goldwin Smith](/person/1343)
- [H. D’Artignan Smith](/person/1337)
- [M. Smith](/person/1338)
- [Mary Isabella Smith](/person/167)
- [Mary Smith](/person/1339)
- [Richard Smith](/person/1341)
- [W. Smith](/person/1342)
- [Walter Smith](/person/1344)
- [The Rev. Merton Smith](/person/1340)
- [Hannah Smith](/person/2297)
- [Major-General Sir Robert Murdoch Smith](/person/2125)
- [Robert Pearsall Smith](/person/2298)
- [Jane Mary Smith-Dampier](/person/1345)
- [Charles Smythe](/person/1346)
- [William Smythe](/person/1347)
- [Frederick John Snell](/person/1348)
- [Sophia Vernon Somerset](/person/1350)
- [Lord 1st Lord Raglan Fitzroy Somerset](/person/1276)
- [1st Marquess of Worc Henry Somerset](/person/1769)
- [Lucy Helen Muriel Soulsby](/person/1351)
- [Susan Sybilla Soulsby](/person/1352)
- [Marshal duc de Dalmatie Nicolas-Jean de Dieu Soult](/person/1349)
- [Robert Southey](/person/1722)
- [Emile Souvestre](/person/1353)
- [Marie Claire Souvestre](/person/1354)
- [The Very Rev. Henry Spence](/person/2142)
- [E. Spender](/person/1355)
- [Edward Harold Spender](/person/1356)
- [Lily Spender](/person/1357)
- [Emmeline Mary Spratt](/person/1358)
- [Harriet Spratt](/person/1359)
- [Sarah Mary Spratt](/person/1360)
- [Susan Spratt](/person/1361)
- [William Spratt](/person/1362)
- [Leslie William Spratt](/person/2287)
- [William Leslie Spratt](/person/2311)
- [Henrietta St.Lawrence](/person/727)
- [Miss Stanford](/person/2209)
- [Mr Stanier](/person/1695)
- [The Very Rev. Arthur Penrhyn Stanley](/person/1987)
- [Henrietta Eliza Vaughan Stannard](/person/2132)
- [Mrs Steele](/person/2405)
- [Francesca Maria Steele,](/person/1363)
- [Cordelia Yonge Steer](/person/1364)
- [Katharine Steer](/person/1365)
- [Dr. Adam William Thorburn Steer](/person/2145)
- [Mrs Stevenson](/person/1366)
- [The Rev. James Stevenson](/person/2126)
- [The Rev. Edward Steward](/person/1680)
- [J.A. Stewart](/person/1367)
- [Mildred Stewart](/person/37)
- [Mrs Stewart](/person/1369)
- [Admiral Sir Houston Stewart](/person/1277)
- [Charles William Vanustegen Stewart](/person/2358)
- [George Stirling-Horne-Drummond](/person/1370)
- [The Rev. Samuel John Stone](/person/1371)
- [Antonio Stoppani](/person/1372)
- [John St. Loe Strachey](/person/2406)
- [Sir Edward Strachey](/person/1989)
- [Alexander Stuart Strahan](/person/1278)
- [The Rev. William Champion Streatfeild](/person/2438)
- [George Edmund Street](/person/2028)
- [Agnes Strickland](/person/1376)
- [C. Sorel Strong](/person/1377)
- [Miss G. B. Stuart](/person/1378)
- [Anne Sturges Bourne](/person/1379)
- [William Sturges Bourne](/person/2150)
- [Florence Horatia Nelson Suckling](/person/1380)
- [Mary Elizabeth Sumner](/person/1381)
- [The Rt. Rev. Charles Richard Sumner](/person/1383)
- [The Rt. Rev. George Henry Sumner](/person/1382)
- [Mary Eleanora Sunderland](/person/1384)
- [James Sutcliffe](/person/1933)
- [Sophia Petrovna Swetchine](/person/1848)
- [Algernon Charles Swinburne](/person/1386)
- [Anna Lydia Keith Swinton](/person/1387)
- [Mrs Swinton](/person/1388)
- [Emily Synge](/person/1389)
- [Janet Syrett](/person/1390)
- [The Rev. Henry Tagalana](/person/1975)
- [E. C. Tait](/person/1392)
- [His Grace Archibald Campbell Tait](/person/1391)
- [Catherine Talbot](/person/1393)
- [Mrs J. C. Talbot](/person/1394)
- [The Hon. Lavinia Talbot](/person/2082)
- [The Rt. Rev. Edward Stuart Talbot](/person/1691)
- [Susanna Tandy](/person/2152)
- [Mary Elizabeth Tanner](/person/1395)
- [Thomas Slingsby Tanner](/person/2425)
- [Stephen Taroniara](/person/1279)
- [Emily Constance Taylor](/person/1398)
- [Emily Taylor](/person/1397)
- [Sir Henry Taylor](/person/1793)
- [Crona Temple](/person/1399)
- [His Grace Frederick Temple](/person/1400)
- [1st Lord Tennyson Alfred Tennyson](/person/1874)
- [Miss Terle](/person/2006)
- [Agnes Beatrice Jane Thicknesse](/person/1401)
- [Edith Thompson](/person/1402)
- [Ellen Perronet Thompson](/person/1403)
- [Miss Thompson](/person/1404)
- [Mrs Launt Thompson](/person/1405)
- [A.F. Thornton](/person/1406)
- [The Rt. Rev. Anthony Wilson Thorold](/person/1280)
- [George Herbert Thring](/person/1281)
- [Harriet Frances Thynne](/person/1407)
- [George Ticknor](/person/1408)
- [Margaret Tillard](/person/1409)
- [Thomas Capel Tilly](/person/1410)
- [Evelyn Tod](/person/1412)
- [Catherine Tolcher](/person/2087)
- [M. Tomlinson](/person/1413)
- [Cecil Townley](/person/1414)
- [Mary Elizabeth Townsend](/person/1415)
- [Meredith Townsend](/person/1942)
- [Mary Trebeck](/person/1416)
- [Maria Trench](/person/1418)
- [Lady Helena Trench](/person/1417)
- [The Rt. Rev. Richard Chenevix Trench](/person/1419)
- [Hannah More Trevelyan](/person/2431)
- [Sir George Otto Trevelyan](/person/1943)
- [Sarah Trimmer](/person/2092)
- [H.B. Tristram](/person/1420)
- [Mrs Tryen](/person/2212)
- [Urania Tucker](/person/1421)
- [Miss Tucker](/person/1424)
- [Miss Emma Tucker](/person/1422)
- [Miss Katherine Tucker](/person/1423)
- [Martin Tupper](/person/1801)
- [T. Turgenef](/person/1425)
- [Harold Pilkington Turner](/person/1426)
- [Francis Randle Twemlow](/person/2017)
- [Louisa Twining](/person/1427)
- [The Rev. Richard St. John Tyrwhitt](/person/1428)
- [M. F. Tytler](/person/1429)
- [Ludwig Uhland](/person/1430)
- [Harriet G. Utterton](/person/1431)
- [Emile Vaisse-Cibiel](/person/1435)
- [Laura Belinda Charlotte Valentine](/person/1437)
- [Margaret Vandegrift](/person/1436)
- [E. C. Vansittart](/person/1438)
- [Benjamin Vassil](/person/2066)
- [Marion Vassil](/person/2067)
- [John Vaughan](/person/1441)
- [The Rev. Charles John Vaughan](/person/1439)
- [Catherine Maria Vaughan](/person/1929)
- [The Rev. Edward Protheroe Vaughan](/person/2289)
- [The Rev. James Edward Vaux](/person/2403)
- [E. Vere](/person/1440)
- [The Hon. Caroline Mary Vernon Harcourt](/person/1442)
- [The Rev. Leveson Vernon Harcourt](/person/1443)
- [Linda Mary Villari](/person/1444)
- [Pasquale Villari](/person/2345)
- [The Rev. ? Villiers](/person/2252)
- [Jetty Vogel](/person/1445)
- [Elisa Von der Recke](/person/1446)
- [Caroline Wabisane](/person/1447)
- [H. M. Waithman](/person/1448)
- [The Rev. Rota Waitoa](/person/1747)
- [Viscount Chewton William Waldegrave,](/person/2161)
- [John Desborough Walford](/person/1449)
- [Lucy Bethia Walford](/person/1451)
- [Olive Montagu Walford](/person/1452)
- [The Rev. Oliver Walford](/person/1450)
- [M. Walker](/person/1454)
- [Alice Fielden Walker](/person/2166)
- [Maria Edith Walker](/person/2234)
- [Maria S. Wallace](/person/1455)
- [Percy M. Wallace](/person/1456)
- [The Rev. Dr. William Wallace](/person/1457)
- [William Wallace](/person/1852)
- [M. T. Wallas](/person/1458)
- [The Rev. Charles Henry Waller](/person/1460)
- [Countess of Portsmou Eveline Alicia Juliana Wallop](/person/2290)
- [Maud Walpole](/person/1469)
- [Spencer Horatio Walpole](/person/1432)
- [Lieutenant the Hon. Frederick Walpole](/person/1459)
- [Edward Charles Lethbridge Walter](/person/1464)
- [Herbert Simcoe Walter](/person/1463)
- [Gertrude Walter](/person/1462)
- [Lieutenant Colonel Edward Walter](/person/1461)
- [The Hon. Isabel Mary Warburton](/person/1465)
- [The Rev.Canon William Parsons Warburton](/person/1466)
- [Bartholomew Elliott George Warburton](/person/1720)
- [Mary Augusta Ward](/person/1467)
- [Miss Warenne](/person/2237)
- [C. M. Waring](/person/1468)
- [H. F. Waring](/person/1470)
- [Frederick Warne](/person/1433)
- [The Rev. Henry James Warner](/person/1472)
- [Edith Emma Warner](/person/2177)
- [Nathaniel Warren](/person/1474)
- [Susanna Warren](/person/1475)
- [Miss Warren](/person/1476)
- [Mrs Warren](/person/1473)
- [William Thorn Warren](/person/2377)
- [Mrs Wathen](/person/2165)
- [The Rev. Morgan George Watkins](/person/1477)
- [Miss Watkins](/person/2254)
- [Miss M. Watson](/person/2096)
- [A M. Wattus?](/person/1478)
- [The Rt. Rev. Alan Becher Webb](/person/1479)
- [Blanche C. Webber](/person/1480)
- [Francis P. Webber](/person/1481)
- [Gertrude Margaret Webber](/person/1482)
- [Alice Weber](/person/1483)
- [Mary Elizabeth Webster](/person/1)
- [T. Webster](/person/1484)
- [Isabella Weddle](/person/1485)
- [1st Duke of Welling Arthur Wellesley](/person/1486)
- [A. Werner](/person/1487)
- [Dr. Samuel Sebastian Wesley](/person/1488)
- [Mr West](/person/1489)
- [Sarah Westcombe](/person/1718)
- [The Rev. Thomas Westcombe](/person/1719)
- [Stanley John Weyman](/person/1490)
- [The Rev. Canon Edgar Wharton](/person/1675)
- [Jane Whately](/person/1798)
- [Mary Whately](/person/1799)
- [The Right Rev. Richard Whately](/person/1797)
- [Frances Wheeler](/person/1973)
- [William Whewell](/person/1818)
- [C. M. Whidborne](/person/1491)
- [Evelyn Whitaker](/person/1492)
- [Miss White](/person/1493)
- [Mrs White](/person/1494)
- [Ann White](/person/2392)
- [Mary White](/person/1753)
- [Thomas White](/person/2393)
- [Samuel Whitford](/person/1811)
- [Susan Whorley](/person/1497)
- [Little Whorley](/person/1498)
- [Jane Whorley](/person/1766)
- [Clara de Havilland Wickham](/person/1500)
- [Elizabeth Ann Wickham](/person/1505)
- [George Herbert Wickham](/person/1501)
- [Jane Susannah Wickham](/person/1502)
- [Laura Maria Wickham](/person/1504)
- [The Rev. Charles Wickham](/person/1499)
- [The Rev. Latham Wickham](/person/1503)
- [The Rev. Robert Wickham](/person/1506)
- [The Rev. Thomas Vowler Wickham](/person/1508)
- [Emily Eliza Wickham](/person/2302)
- [Sidney Katherine Wickham](/person/2185)
- [The Rev. Gordon Bolles Wickham](/person/2184)
- [Emilie Thal Wigan](/person/1509)
- [The Rev. Henry Wilberforce](/person/1510)
- [The Rt. Rev. Samuel Wilberforce](/person/1512)
- [The Ven. Robert Isaac Wilberforce](/person/1511)
- [Emily Wilbraham](/person/1514)
- [General Sir Richard Wilbraham](/person/1515)
- [Frances Maria Wilbraham](/person/1513)
- [Sibylla Wilbraham](/person/1982)
- [The Rev. Henry Wilbraham](/person/2433)
- [W. E. Wilcox](/person/1518)
- [Margaret Wilcox](/person/1517)
- [Ernest Shepley Wilcox](/person/2348)
- [Isabella Lucy Wilcox](/person/2120)
- [Mary Anne Wilcox](/person/2030)
- [Emma Wilford](/person/1519)
- [Florence Wilford](/person/1520)
- [Major-General Edmund Neal Wilford](/person/1521)
- [Leonard Williams](/person/1522)
- [Sarah Williams](/person/1525)
- [Mrs Williams](/person/1524)
- [The Rev. Isaac Williams](/person/1523)
- [Edmund Sydney Williams](/person/1964)
- [The Rev. Edmund Riland Williamson](/person/1527)
- [The Rev. Richard Williamson](/person/1528)
- [The Rev. William Williamson](/person/1529)
- [Mr Willis](/person/1530)
- [Lieutenant George Dobson Willoughby](/person/1904)
- [Jane Wills](/person/2163)
- [E. F. Wilson](/person/1535)
- [Francis Heathcote Wilson](/person/1533)
- [H. Mary Wilson](/person/1536)
- [J. M. Wilson](/person/1537)
- [Maria Wilson](/person/1539)
- [R. Wilson](/person/1538)
- [Thomas Percival Wilson](/person/1534)
- [Mrs Wilson](/person/1540)
- [The Rev. Robert Francis Wilson](/person/1541)
- [The Rev. Bernard Robert Wilson](/person/1532)
- [Dr George Wilson](/person/1932)
- [The Right Rev. Cecil Wilson](/person/1651)
- [John Winter](/person/1754)
- [Cardinal Nicholas Patrick Stephen Wiseman](/person/1542)
- [Charles Wither](/person/1543)
- [Guy Carleton Bigg Wither](/person/1545)
- [Marianne Bigg Wither](/person/1546)
- [The Rev. William Harris Walter Bigg Wither](/person/1544)
- [George Wither](/person/1686)
- [Jane Wither](/person/1743)
- [Lady Eleanor Wodehouse](/person/1547)
- [The Rev. Algernon Wodehouse](/person/1548)
- [Edward Wogale](/person/2003)
- [Charles Woleg](/person/2068)
- [Ellen Woleg](/person/2069)
- [Frances Hariott Wood](/person/1550)
- [Miss T? S. Wood](/person/1549)
- [Constantia Eleanor Wood](/person/1786)
- [Lady Constantia Wood](/person/1785)
- [Lieut-General Robert Blucher Wood](/person/1784)
- [Nathaniel Woodard](/person/1551)
- [Mr Woodcock](/person/1553)
- [Henrietta Newman Woodgate](/person/1554)
- [The Rev. Thomas Woodman](/person/1555)
- [The Rev. Charles Bathurst Woodman](/person/2322)
- [Herbert Hall Woodward](/person/1552)
- [Julia Lucy Woodward](/person/1657)
- [Charles Sylvester Wooldridge](/person/2093)
- [Charles Wooldridge](/person/2094)
- [Anne Catharina Woollcombe](/person/1556)
- [Edward Woollcombe](/person/1561)
- [Mary Woollcombe](/person/1558)
- [Richard Woollcombe](/person/1557)
- [William John Woollcombe](/person/1560)
- [Major Robert Woollcombe](/person/1559)
- [The Rev. George Ley Woollcombe](/person/1562)
- [Vice-Admiral Henry Bedford Woollcombe](/person/2088)
- [Dorothy Wordsworth](/person/1563)
- [Elizabeth Wordsworth](/person/1566)
- [Katherine Mary Wordsworth](/person/1568)
- [Susan Esther Wordsworth](/person/1569)
- [Susanna Wordsworth](/person/1570)
- [The Rt. Rev. Charles Wordsworth](/person/1564)
- [The Rt. Rev. Christopher Wordsworth](/person/1565)
- [The Rt. Rev. John Wordsworth](/person/1567)
- [P. S. Worsley](/person/1571)
- [Mr Wortley](/person/1698)
- [John P. Wright](/person/1572)
- [Melicent Wyan](/person/1573)
- [James Wyatt](/person/2424)
- [Thomas Henry Wyatt](/person/2296)
- [Lady Leconfield Constance Evelyn Wyndham](/person/1664)
- [Isabella Sophia Wynyard](/person/1575)
- [William Wynyard](/person/1574)
- [W. M. Wyse](/person/1576)
- [Adelaide Yard](/person/1577)
- [Eliza Yard](/person/1578)
- [Alethea Henrietta Yonge](/person/1580)
- [Alethea Yonge](/person/1581)
- [Alethea Yonge](/person/1584)
- [Anne Yonge](/person/1582)
- [Arthur Duke Yonge](/person/1583)
- [Catherine Yonge](/person/1585)
- [Charlotte Cordelia Yonge](/person/1587)
- [Charlotte Fortescue Yonge](/person/1588)
- [Charlotte Mary Yonge](/person/1589)
- [Cordelia Anne Margaret Yonge](/person/1592)
- [Cordelia Anne Yonge](/person/1591)
- [Cordelia Elizabeth Yonge](/person/1593)
- [Cordelia Yonge](/person/1590)
- [Duke Dowton Yonge](/person/1596)
- [Duke Mohun Yonge](/person/1595)
- [Edmund Charles Yonge](/person/1601)
- [Elizabeth Catharine Yonge](/person/1603)
- [Emma Frances Yonge](/person/1604)
- [Frances Elizabeth Yonge](/person/1605)
- [Frances Mary Yonge](/person/1606)
- [Francis Arthur Yonge](/person/1607)
- [George Alan [or Allan?] David Yonge](/person/1610)
- [George Edward Yonge](/person/1611)
- [Gwendolen or Gwendolene Violet Yonge](/person/1612)
- [Helen Emma Yonge](/person/1613)
- [James Yonge](/person/1615)
- [Jane Duke Yonge](/person/1616)
- [John Bargus Yonge](/person/1619)
- [John Yonge](/person/1617)
- [John Yonge](/person/1618)
- [Julian Bargus Yonge](/person/1624)
- [Margaret Yonge](/person/1625)
- [Mary Anne Yonge](/person/1627)
- [Mary Isabel Yonge](/person/1628)
- [Mary Yonge](/person/1626)
- [Maude Yonge](/person/1629)
- [Maurice Edward Yonge](/person/1630)
- [William Crawley Yonge](/person/1631)
- [William Coulthard Yonge](/person/1632)
- [Dr. James Yonge](/person/1614)
- [Lieut. Frederick Duke Yonge](/person/1608)
- [The Hon. Catherine Charlotte Yonge](/person/1621)
- [The Rev. Charles Yonge](/person/1586)
- [The Rev. Denys Nelson Yonge](/person/1594)
- [The Rev. Duke John Yonge](/person/1597)
- [The Rev. Duke Yonge](/person/1598)
- [The Rev. Duke Yonge](/person/1599)
- [The Rev. Duke Yonge](/person/1600)
- [The Rev. Geoffrey Yonge](/person/1609)
- [The Rev. John Eyre Yonge](/person/1620)
- [The Rev. John Yonge](/person/1623)
- [Vice-Admiral Edmund Yonge](/person/1602)
- [Anna Susanna Yonge](/person/2262)
- [Catharina Yonge](/person/1905)
- [Catherine Ada Helena Yonge](/person/2256)
- [Charles Duke Yonge](/person/2409)
- [Dr. John Francis Duke Yonge](/person/1622)
- [Elizabeth Birt Alice Yonge](/person/1723)
- [Emma Caroline Isabella Yonge](/person/2081)
- [Grace Yonge](/person/2216)
- [Isabella Sydney Yonge](/person/2178)
- [James Edmund Yonge](/person/1804)
- [Jane Ley Yonge](/person/2057)
- [John Harry Yonge](/person/2080)
- [Lucy Yonge](/person/2116)
- [Mary Yonge](/person/2127)
- [Samuel Humphreys Yonge](/person/2391)
- [Stephen Duke Yonge](/person/2183)
- [The Rev. Charles Burell Yonge](/person/1656)
- [The Rev. Charles Francis Lysaght Yonge](/person/2179)
- [The Rev. James Upton Yonge](/person/2306)
- [Caroline Young](/person/1633)
- [The Rev. James Gavin Young](/person/1634)
- [The Rev. James Young](/person/1635)
- [The Rev. Peter Young](/person/1636)
- [Anna Young](/person/2058)
- [Fisher Young](/person/1908)
- [Harry Gavin Young](/person/1996)
- [Sir Allen Young](/person/2308)
- [Mary Frances Younghusband](/person/1637)
- [Helen Zimmern](/person/1638)
- [F. de Normanville](/person/1088)
- [Aubrey Thomas de Vere](/person/2259)
- [Julia Cecilia de Winton, later Stretton](/person/2327)
- [Alice Mead du Boulay](/person/2343)
- [The Rev. M.M. ffinch](/person/1688)
- [Baron von Tauchnitz Christian Bernhard von Tauchnitz](/person/1396)
- [Baron von Tauchnitz Christian Karl Bernhard von Tauchnitz](/person/2124)
