---
title: "Institutions and Other References"
---

## Organisation

- [Association for Promoting the General Welfare of the Blind](/organisation/1)
- [Band of Mercy](/organisation/265)
- [Bath Rheumatic Hospital](/organisation/189)
- [Belgrave Hospital for Children, The](/organisation/17)
- [Bell and Daldy](/organisation/135)
- [Blackwood](/organisation/214)
- [British Institution, The](/organisation/18)
- [Cambridge University Press](/organisation/263)
- [Cassell](/organisation/216)
- [Church Army, The](/organisation/231)
- [Church Missionary Society, The](/organisation/19)
- [Church of England Society for Providing Homes for Waifs and Strays](/organisation/2)
- [Church of England Women\'s Help Society, The](/organisation/222)
- [Community of St Michael and All Angels, Bloemfontein](/organisation/219)
- [Community of St. John the Baptist, Clewer, The](/organisation/20)
- [Community of St. Mary the Virgin, Wantage, The](/organisation/21)
- [Dalziel Bros.](/organisation/163)
- [Daniel Appleton and Co.](/organisation/142)
- [Darton](/organisation/109)
- [Dr. Barnardo\'s Homes](/organisation/115)
- [Earlswood Asylum for Idiots, The](/organisation/38)
- [Ecclesiological Society, The](/organisation/131)
- [English Church Union, The](/organisation/22)
- [George Allen and Sons](/organisation/256)
- [George Routledge & Sons](/organisation/258)
- [Girls\' Friendly Society Reading Union](/organisation/211)
- [Girls’ Friendly Society, The](/organisation/23)
- [Girton College](/organisation/201)
- [Great Ormond Street Hospital](/organisation/3)
- [Griffith and Farran](/organisation/233)
- [Groombridge](/organisation/148)
- [Guild of St. Alban, The](/organisation/24)
- [Hampshire Blind School, The](/organisation/25)
- [Harper & Bros](/organisation/248)
- [Heinemann](/organisation/230)
- [Henry S. King](/organisation/242)
- [Hindu College, Calcutta](/organisation/175)
- [Hoare\'s Bank](/organisation/169)
- [Hogg](/organisation/159)
- [Home for Incurable and Infirm Women, The](/organisation/26)
- [Hospital of St. Cross and Almshouse of Noble Poverty, The](/organisation/130)
- [Huggens College](/organisation/4)
- [Institution for the Employment of Needlewomen, The](/organisation/27)
- [Isbister](/organisation/223)
- [Jacob and Johnson](/organisation/187)
- [Keble College, Oxford](/organisation/5)
- [Ladies\' Home, 21 Abbey Road, St. John\'s Wood, The](/organisation/191)
- [Lady Margaret Hall](/organisation/6)
- [Little Sisters of the Poor, The](/organisation/197)
- [London Library, The](/organisation/29)
- [Longman](/organisation/153)
- [Macmillan and Son](/organisation/111)
- [Marcus Ward and Co.](/organisation/236)
- [Masters](/organisation/112)
- [Melanesian Mission, The](/organisation/30)
- [Molyneux Female Blind Asylum](/organisation/166)
- [Mothers’ Union, The](/organisation/31)
- [Mozley](/organisation/108)
- [Mudie\'s Circulating Library](/organisation/137)
- [National Association for Promoting Freedom of Public Worship](/organisation/194)
- [National Society, The](/organisation/32)
- [Nelson](/organisation/226)
- [Newnham College](/organisation/7)
- [Norwich Union Insurance Company](/organisation/8)
- [Nutt and Wells](/organisation/178)
- [Orphans Home, Plymouth, The](/organisation/33)
- [Orthopaedic Hospital](/organisation/9)
- [Otterbourne Penny Club](/organisation/10)
- [Otterbourne School](/organisation/107)
- [Parents\' Educational Union, The](/organisation/34)
- [Parker and Son](/organisation/152)
- [Perry Mason & Co.](/organisation/249)
- [Phelps](/organisation/164)
- [Primrose League, The](/organisation/255)
- [Queen\'s College, Harley Street](/organisation/206)
- [R & R Clark](/organisation/251)
- [Reeves and Turner](/organisation/239)
- [Religious Tract Society, The](/organisation/35)
- [Richard Bentley and Son](/organisation/168)
- [Richard Clay & Sons](/organisation/173)
- [Royal Academy, The](/organisation/141)
- [Royal Hampshire Hospital, The](/organisation/36)
- [Royal Hospital for Incurables, The](/organisation/37)
- [Royal Literary Fund, The](/organisation/257)
- [Royal Society for the Prevention of Cruelty to Animals](/organisation/243)
- [Royal Victoria Hospital, Netley, The](/organisation/39)
- [Sackville College](/organisation/11)
- [Sandwell Home](/organisation/12)
- [Sanger\'s Circus](/organisation/117)
- [Saunders and Otley](/organisation/144)
- [Saville & Edwards](/organisation/162)
- [Scribner](/organisation/204)
- [Skeffington](/organisation/110)
- [Smith, Elder and Co.](/organisation/238)
- [Society for the Promotion of Christian Knowledge, The](/organisation/40)
- [Society for the Propagation of the Gospel, The](/organisation/41)
- [Society of All Saints’s Sisters of the Poor, The](/organisation/43)
- [Society of Authors, The](/organisation/44)
- [Society of St. Margaret, East Grinstead, The](/organisation/45)
- [Society of Watchers and Workers, The](/organisation/47)
- [Society of Women Writers and Journalists, The](/organisation/234)
- [Society of the Most Holy Trinity, The](/organisation/46)
- [Spider Society, The](/organisation/116)
- [Spottiswoode](/organisation/183)
- [St. Andrew\'s College, Kohimarama](/organisation/139)
- [St. Augustine’s College](/organisation/13)
- [St. Hugh’s College](/organisation/14)
- [St. John\'s College, Auckland](/organisation/138)
- [St. John’s College, Hurstpierpoint](/organisation/28)
- [St. Mark’s College, Chelsea](/organisation/66)
- [St. Michael\'s School, Bognor](/organisation/185)
- [St. Peter\'s, Kilburn](/organisation/203)
- [St. Stephen’s Native Girls School](/organisation/15)
- [St. Thomas\'s Home, Basingstoke](/organisation/247)
- [Surgical Aid Society](/organisation/16)
- [Thomas Constable & Co.](/organisation/136)
- [Ticknor and Fields](/organisation/179)
- [Universities Mission to Central Africa](/organisation/42)
- [W. F. Tillotson & Son](/organisation/260)
- [W. H. Smith and Son](/organisation/161)
- [Ward, Lock & Co.](/organisation/235)
- [Wells, Gardner](/organisation/114)
- [Wigram and Sons](/organisation/157)
- [William Clowes & Sons](/organisation/245)
- [Williams and Norgate](/organisation/165)
- [Winchester College](/organisation/50)
- [Winchester Diocesan Society for Higher Religious Education, The](/organisation/48)
- [Winchester Female Refuge, The](/organisation/49)
- [Winchester Girls’ High School](/organisation/51)
- [Winchester Literary and Scientific Society](/organisation/208)
- [Winnington Hall School](/organisation/186)
- [publisher](/organisation/215)

## Periodical

- [<i> Charm, The</i>](/periodical/57)
- [<i> Church Quarterly Review, The</i>](/periodical/60)
- [<i> Church Times, The</i>](/periodical/61)
- [<i>Academy, The</i>](/periodical/246)
- [<i>All Saints Magazine</i>](/periodical/254)
- [<i>Atalanta</i>](/periodical/53)
- [<i>Athenaeum, The</i>](/periodical/170)
- [<i>Aunt Judy’s Magazine</i>](/periodical/54)
- [<i>Barnacle, The</i>](/periodical/89)
- [<i>Blackwood\'s Edinburgh Magazine</i>](/periodical/146)
- [<i>British Quarterly Review, The</i>](/periodical/90)
- [<i>Cassell’s Magazine</i>](/periodical/55)
- [<i>Chambers’s Journal</i>](/periodical/56)
- [<i>Children’s World, The</i>](/periodical/58)
- [<i>Christian Remembrancer, The</i>](/periodical/59)
- [<i>Church Illustrated, The</i>](/periodical/229)
- [<i>Churchman's Family Magazine, The</i>](/periodical/63)
- [<i>Churchman\'s Companion</i>](/periodical/62)
- [<i>Churchwoman, The</i>](/periodical/64)
- [<i>Constitutional Press</i>](/periodical/65)
- [<i>Cornhill Magazine, The</i>](/periodical/156)
- [<i>Cottagers' Monthly Visitor</i>](/periodical/67)
- [<i>Edinburgh Review</i>](/periodical/132)
- [<i>English Illustrated Magazine</i>](/periodical/68)
- [<i>Events of the Month</i>](/periodical/69)
- [<i>Family Friend, The</i>](/periodical/70)
- [<i>Fraser\'s Magazine</i>](/periodical/199)
- [<i>Friendly Leaves</i>](/periodical/71)
- [<i>Friendly Work</i> later the <i>Girls\' Quarterly</i>](/periodical/182)
- [<i>Girls\' Friendly Society Associates\' Journal, The</i>](/periodical/72)
- [<i>Girls\' Realm, The</i>](/periodical/210)
- [<i>Glasgow News, The</i>](/periodical/252)
- [<i>Good Words </i>](/periodical/73)
- [<i>Gospel Missionary, The</i>](/periodical/227)
- [<i>Great Grimsby Parish Magazine</i>](/periodical/74)
- [<i>Guardian, The</i>](/periodical/75)
- [<i>Hampshire Chronicle, The</i>](/periodical/209)
- [<i>Harper\'s Young People</i>](/periodical/250)
- [<i>Lincoln Diocesan Magazine, The</i>](/periodical/228)
- [<i>Literary Churchman, The </i>](/periodical/76)
- [<i>Literary Gazette, The</i>](/periodical/143)
- [<i>Little Folks</i>](/periodical/77)
- [<i>Living Age, The</i>](/periodical/171)
- [<i>London Society</i>](/periodical/220)
- [<i>Macmillan’s Magazine</i>](/periodical/78)
- [<i>Magazine for the Young</i>](/periodical/79)
- [<i>Mission Field: A Monthly Record of the Proceedings of the Society for the Propagation of the Gospel at Home and Abroad, The</i>](/periodical/237)
- [<i>Mission Life, or, The Emigrant and the Heathen</i>](/periodical/80)
- [<i>Month, The</i>](/periodical/91)
- [<i>Monthly Packet, The</i>](/periodical/52)
- [<i>Monthly Paper of Sunday Teaching, The</i>](/periodical/81)
- [<i>Morning Herald, The</i>](/periodical/92)
- [<i>Morning Post, The</i>](/periodical/147)
- [<i>Mothers in Council</i>](/periodical/82)
- [<i>Mothers’ Union Journal, The</i>](/periodical/93)
- [<i>National Review, The</i>](/periodical/259)
- [<i>Net Cast in Many Waters: Sketches from the Lives of Missionaries, The</i>](/periodical/94)
- [<i>Newbery Magazine</i>](/periodical/83)
- [<i>Nonconformist, The</i>](/periodical/95)
- [<i>North American Review, The</i>](/periodical/200)
- [<i>Once a Week </i>](/periodical/84)
- [<i>Otterbourne Parish Magazine</i>](/periodical/85)
- [<i>Pall Mall Gazette, The</i>](/periodical/192)
- [<i>Parents\' Educational Union Monthly Journal</i>](/periodical/218)
- [<i>Penny Post, The </i>](/periodical/96)
- [<i>Queen, The</i>](/periodical/241)
- [<i>Reader: A review of current literature, science, and art, The</i>](/periodical/97)
- [<i>Record, The</i>](/periodical/253)
- [<i>Saturday Magazine, The</i>](/periodical/98)
- [<i>Saturday Review, The</i>](/periodical/99)
- [<i>Schoolmistress, The</i>](/periodical/212)
- [<i>Sharpe’s Magazine</i>](/periodical/86)
- [<i>Spectator, The</i>](/periodical/180)
- [<i>St. Luke’s Magazine </i>](/periodical/87)
- [<i>St. Nicholas</i>](/periodical/88)
- [<i>Sunday Magazine, The</i>](/periodical/232)
- [<i>Watchword, The</i>](/periodical/100)
- [<i>Weekly Register, The</i>](/periodical/174)
- [<i>Youth\'s Companion: An Illustrated Weekly Paper for Young People and All the Family, The</i>](/periodical/244)

## Place

- [All Saints, Babbacombe](/place/195)
- [All Saints\' Church, Hursley](/place/261)
- [Ampfield](/place/124)
- [Beechwood](/place/126)
- [Brighstone](/place/140)
- [Church of the Resurrection, Eastleigh](/place/188)
- [Cranbury Park](/place/119)
- [Deer Park](/place/125)
- [Dogmersfield](/place/121)
- [Hursley](/place/127)
- [Mota](/place/150)
- [Pitt Chapel](/place/133)
- [Puslinch](/place/123)
- [Rawalpindi](/place/262)
- [Santa Cruz Islands](/place/122)
- [Slade](/place/120)
- [Sorel](/place/181)
- [St. Matthew\'s Church, Otterbourne](/place/158)
- [Twyford](/place/128)
- [Tyntesfield](/place/207)
- [Val Richer](/place/205)
- [Weston, St. Marychurch, Torquay](/place/196)

## Topic

- [70th Birthday Presentation to CMY](/topic/225)
- [American piracy](/topic/172)
- [Auckland Bells, The](/topic/103)
- [Books for the Chicago Exhibition](/topic/221)
- [Bullock\'s proposed book of Anglican saints](/topic/213)
- [CMY\'s Collected Works](/topic/264)
- [CMY\'s literary earnings](/topic/160)
- [Charlotte Yonge Scholarship, The](/topic/113)
- [Church restoration](/topic/198)
- [Collection of British Authors](/topic/224)
- [Gosling Society, The](/topic/104)
- [Indian Mutiny, The](/topic/134)
- [Keble\'s funeral](/topic/184)
- [Macmillan\'s Sunday Library](/topic/145)
- [Marriage between first cousins](/topic/101)
- [Philological Society\'s proposed Dictionary, The](/topic/151)
- [Risorgimento, The](/topic/149)
- [Scotch girl\'s novel](/topic/193)
- [Winchester lectures for ladies](/topic/240)
- [\'Bethlehem\'](/topic/177)
- [advertisement for <i>Robert Elsmere</i>](/topic/217)
- [avoiding accusations of Puseyism](/topic/154)
- [higher education of women, The](/topic/105)
- [illustration](/topic/167)
- [proposed guide to charitable institutions](/topic/190)
- [rate of payment of <i>MP</i> contributors](/topic/102)
- [sales of CMY\'s works](/topic/155)
- [story of Indian life](/topic/202)
- [women publishing books with their names](/topic/106)
