---
id: 1000
full-name: Ellen J. Millington
first-name: Ellen J.
last-name: Millington
title: Ellen J. Millington
dates: (b.1818)
---

teacher and contributor to MP(1853-64)

Ellen J.

Millington translated The Aesthetic and Miscellaneous Works of Frederick von Schlegel from the German in 1849 (reprinted a number of times up to 1891), Christian iconography, or, the history of Christian art in the Middle Ages by A.N.

Didron from the French in 1851, and herself wrote Heraldry in History, Poetry, and Romance (1858) and Characteristics of the Gods of Greece. A Manual for Schoolgirls (1867).

As well as the series of articles on heraldry, she contributed seven articles on ‘King Arthur and his Knights’ to the MP between 1861 and 1864.

Daughter of Henry Millington (b. 1790/1), attorney\'s clerk [1851 census, in Bristol], she is described by CMY as an invalid ex-governess; in the 1861 census she was living with her mother (father absent but evidently alive) Emma Millington (b.1794/5), her sister Anna Gerard (b. 1818/9), widowed by 1851 census, keeping a tiny school of three pupils in Westbury on Trym.

In the 1871 census her mother is Anna Millington, now a widow, Anna Gerard also now a widow, and the school bigger and occupying two houses in Clifton.

She was living at Hawarden, Wales, with Anna Gerard, in the 1881 census.

Her father is found in 1861 (not 1871) living with his son, the Rev.

Thomas Street Millington (1821-1906), curate, later vicar of Woodhouse, Leics., and a prolific author of theology and boys’ fiction.
