---
id: 12
full-name: Charles Warren Adams
first-name: Charles Warren
last-name: Adams
title: Charles Warren Adams
dates: (1833-30 July 1903)
---

animal rights campaigner

He married, first (1861), Georgina Alethe Polson (b.1838), daughter of the Rev. Hugh Polson and Georgiana, only child of Charlotte Yonge and her first husband Captain George Crawley, and therefore CMY’s first cousin once removed.  (Mrs Crawley was CMY's aunt and godmother and married secondly the Rev Thomas Jones, Rector of Exeter College Oxford). The Polsons had other children: (Arthur b. 1831/2, George b. 1833/4, Rosalia b.1834/5 and Catharina K. b. 1835/6). Adams married secondly (24 June 1885), in the teeth of her family, the Hon. Mildred Mary Coleridge (1847-14 January 1929). For his involvement in brawling during a church service at St. George in the East, in defence of the innovations introduced by the vicar, see The Times (11, 14 April 1860). [LG 1952 Woollcombe Adams of Anstey Hall; 1841, 1851, 1861 censuses at www.ancestry.co.uk]
