---
id: 1462
full-name: Gertrude Walter
first-name: Gertrude
last-name: Walter
title: Gertrude Walter
dates: (Shotapoor 24 May 1849-20 May 1897)
---

housemate of CMY, sister-in-law of JBY

Daughter of Edward Walter and Mary Emma Coulthard. Her sister Frances married (1858) CMY\'s only brother Julian Bargus Yonge. She moved into Elderfield with CMY in about 1872.  Her illness began 8 years before 1871.
[Bombay Baptisms N/3/24/118; \'she would have been 48 on the 24th\']

CMY described her movingly in ‘Our Tender Ones’ Mothers in Council 9 (January 1899) 20-27, 26:

‘Let me draw the picture of a real invalid not long passed away. She was a bright active girl of fourteen when rheumatic fever set in, followed by arthritis. Gradually, during nearly twenty years, every power was taken from her; first one knee was affected, then the other, then she could no longer sit at the piano, she moved on crutches, and drove in a donkey chaise; but in time, always after severe illness and pain, these pleasures failed her, she could only be carried from one room to another or to church on a couch. She lost her voice, and next the use of her right arm, and for several years was entirely confined to bed.’
