---
id: 1520
full-name: Florence Wilford
first-name: Florence
last-name: Wilford
title: Florence Wilford
dates: (Woolwich 29 Feb 1836-?1897)
---

novelist, contributor to MP (1866-83), member of the Gosling Society

Daughter of Major-General Edmund Neal Wilford (1800-1881), RA, Governor of the Royal Military Academy, Woolwich, until his retirement, she was a Gosling as ‘Turkscap’ from June 1865; her address then was c/o Mrs Chrystall\'s,. St. Cross, Winchester. In the 1851 census, she was 15 and was staying at Bromley Kent, in the company of Maria Cristall, whom CMY describes as her aunt.  In 1881 she and her elder sister Emma, 48, were living with their father in St. Leonards; in 1891 she and Emma were staying in Bournemouth.  Her Royal Literary Fund file indicates that she had suffered from mental illness intermittently since 1883 and was in a private asylum in 1889 when CMY wrote a letter to them on her behalf. (Her application was refused on the grounds ‘authorship insufficient’, which seems rather harsh since she had published sixteen books since 1858.) CMY assured Bullock (16 March 1895) that she was well and at home with her sister. She was probably the Florence Wilford who died at Keynsham, Glos. in 1897. [IGI; RLF application 2311, born at Woolwich]
