---
id: 159
full-name: Jemima Blackburn
first-name: Jemima
last-name: Blackburn
title: Jemima Blackburn
dates: (1823-1909)
---

artist and naturalist

Jemima (Wedderburn) Blackburn (1823-1909), a Scottish naturalist and painter, met CMY through [Frederic Rogers](/person/1252) (1811-1889), later Lord Blachford, a Devon Tractarian who was married to her cousin Georgina Colvile (d.1900).

Blackburn’s memories of CMY are printed in Robert Fairley, [Jemima: Paintings and Memoirs of a Victorian Lady](/periodical/63) (Edinburgh : Canongate, 1988), 128: ‘Charlotte Yonge was a friend of the Rogers and was asked to stay while I was visiting them.

It was a very small house and we were lodged in two little garrets next one another, and used to brush out our hair together before going to bed, and so soon became friends.

She was very good looking with dark hair and fine eyes, spoke pleasantly and was a little above middle height.

We talked of many things. I found her not at all formidable, as one feared she might be, being so well informed; one might almost say learned. . . . I kept up the friendship as long as she lived, and got a good many letters from her while I was illustrating her books.’ She married Hugh Blackburn, Professor of Mathematics at Edinburgh University.

Jemima Blackburn discovered the habits of the cuckoo.
