---
id: 162
full-name: Mary Elizabeth Bromfield
first-name: Mary Elizabeth
last-name: Bromfield
title: Mary Elizabeth Bromfield
dates: 1824/5-1888
---

contributor to MP

The identity of this person is slightly puzzling, though CMY called her one of \'my crack authors\'.

The most likely candidate seems to be Mary Elizabeth (Mills) Bromfield (Harrow 1824/5-1888 Newton Abbot), daughter of the Rev. Dr William Mills, master of Exeter Grammar School, in 1861 living with an engineer brother in Canterbury. She married (Canterbury 23 Sept 1862) the Rev. Henry Bromfield, Vicar of Blockley, and was living with him there 1871. In 1881 she was a widow with an aged spinster sister-in-law at Fladbury House, Pershore, the address with which she corresponds with MP. She was probably the Mary E. Bromfield, author of SPCK tales, Female Christian Names &c., in COPAC.

Another possibility is that she is also the contributor to Biographies of Good Women described as ‘the author of Magdalen Stafford’. That novel, Magdalen Stafford, or, A Gleam of Sunshine on a Rainy Day (1857) and the same author’s The Home Life of English Ladies in the XVII Century (1860), may be Mrs Bromfield’s work.
