---
id: 1865
full-name: \'Bath Brick\'
first-name: \'Bath Brick\'
title: \'Bath Brick\'
dates: —
---

\'Bath Brick\' made her first appearance in MP in May 1876 as a participant in the [Spider](/organisation/116) competitions, when she was commended for a life of the Cid. In June 1876 she appears as ‘A Bath Brick’. Requested to describe ‘A Parish Church’ she chose Clevedon (September 1876): \'on one of the rounded headlands of the Bristol Channel, between Brean Down and Portishead, nestles the old parish church of C____ , dedicated to St. Andrew.\'
In March 1879 she described Wrington in answer to \'Describe the most interesting place in your neighbourhood\'. Therefore it seems reasonable to assume that she resided in north Somerset. As well as being a regular contestant in the Spider competitions, Bath Brick was also a frequent correspondent of the magazine. She is mentioned in the poem written by Mary Anderson Morshead to commemorate the ending of the Spiders in March 1887. Subsequently she took part in the Debateable Ground essay society. Her last appearance was in September 1896.

As to her identity, one possibility is that she was Emma Caroline Scarth (Bath 1850-?1921), younger daughter of the Rev. Harry Scarth, Rector of Wrington.
