---
id: 207
full-name: Catherine Anna Mona Brougham
first-name: Catherine Anna Mona
last-name: Brougham
title: Catherine Anna Mona Brougham
dates: (1804/5-1892)
---

contributor to MP (1888)

MS Girton College, Cambridge, To A.D.

Innes (9 June 1888), identifies the contributor of an article signed \'C.A.W.B.\' as \'Mrs Brougham/ Castlehaven Rectory/ Castletownsend\'.

The article is signed ‘C.A.W.B.’, and refers to ‘my mother, Lady M.’ and to the author as ‘aged’.

The initials were evidently misprinted, and the author Catherine Anna Mona Brougham (1804/5-1892), widow of the Rev.

Henry Brougham (d.1831), Rector of Tallow, and daughter of Sir John Macartney and his second wife Catherine Burgh.

Two other articles appeared in the Monthly Packet in 1889 over the initials \'C.A.M.B.\' Mrs Brougham was probably living with a clerical son, because E. Œ.

Somerville, who lived in Castletownsend, refers (10 September 1888) to \'a hideous tennis function at the Broughams.\' Selected Letters of Somerville and Ross ed. G.

Lewis (London: Faber 1989), 118.

Earlier \'Recollections of Parochial Work in Ireland\' had appeared in MP 1864-5, and the bank account shows payments to Mrs Brougham of £11 (20 April 1863); £10 (12 March 1864); £5 15 s. (29 August 1864); £8 (31 Jan 1865); £3.3s. (23 February 1866).

We are grateful to Mr Peter Wyly for supplying her dates of birth and death. [See also PB Brougham]
