---
id: 2183
full-name: Stephen Duke Yonge
first-name: Stephen Duke
last-name: Yonge
title: Stephen Duke Yonge
dates: (Coblentz 1844/5-1912)
---

third son of CMY\'s cousin Dr. [John Francis Duke Yonge](/person/1622)

Stephen Yonge had emigrated to Melbourne, Australia, by 1864.
The Gentleman\'s Magazine (1866), 399 records the marriage (18 July 1866) \'At the Roman Catholic Cathdral, Plymouth, Stephen Duke Yonge, esq., of Plymstock, to Madeline Bartlet, fourth daughter of the late Lieut.-Col.George Smith, Bombay Native Infantry, of The Lodge, Plymton.\'
However he does not appear in the 1871 or later English censuses, and in 1897 CMY evidently thought he was in California.
According to the Probate Records the will was proved in 1873 of \'Madeline Bartlett Yonge (Wife of Stephen Duke Yonge) formerly of Ladye Park near Liskeard in the County of Cornwall but late of Lower Lake, Lake County California . . who died 19 November 1872 at Lower Lake\'.
According to data assembled by family genealogists at http://www.ilind.net/ancestry/jfdyDesc/p1.htm#i754, Stephen Yonge seems to have had two children.
