---
id: 221
full-name: The Rev. John Frederick Watkinson Bullock
first-name: John Frederick Watkinson
last-name: Bullock
prefix: The Rev.
title: The Rev. John Frederick Watkinson Bullock
dates: (1840-1918)
---



He succeeded his father and grandfather as Rector of Radwinter 1865-1916.

In 1902 he published the first three volumes of a projected six volume work called Daily Lections for every Morning and Evening throughout the Year (London: Rivington 1902).

Volume V of this work, described in his preface, was to have consisted of \'Lections on Anglican Worthies, arranged as additional Readings for Sunday\'.

These \'Biographies of Eminent Anglicans\' exist in MS and are catalogued under that name among the Bullock papers in the Bodleian Library, Oxford, but were never published, since no more of the Daily Lections ever appeared.

The biographies were contributed by various authors, including CMY, Elizabeth Rundle Charles and Florence Wilford. [ Burke LG 1862, Venn, Alumni Cantabrigienses. N.B.

Venn\'s statement that there is an obituary in the Guardian 11 April 1918 seems to be inaccurate.]
