---
id: 237
full-name: Anna Butler
first-name: Anna
last-name: Butler
title: Anna Butler
dates: (b.1825/6)
---

sister of the Very Rev.

William John Butler, contributor to MP (1852)

An obscure figure but an important early contributor to MP, she seems to have shared the family scholarly interests, being a student of German and Danish and author of a book CMY refers to as your 'Scandinavian book'  in early 1856.

The letters in the Fairclough collection are clearly addressed to a sister of William Butler, who had two, Frances, who married in 1843 and died in 1851, and Anna (b.1825/6), who was still alive in 1892, author of Likes and Dislikes: Some Passages in the Life of Emily Marsden (1858) and several other works published as by ‘The author of Likes and Dislikes', viz., Philip Bezant, or, Is Revenge Sweet? (1859), The Brotherhood of St.

John the Evangelist at Berlin (1859), Chilcote Park, or, The Sisters (1860) and The Post Office Window, Being a Tale of the Night School (1862).

The identification is confirmed by payments to Miss A.

Butler in the bank account.
