---
id: 267
full-name: The Rev. Richard Carter Smith
first-name: Richard
last-name: Carter Smith
prefix: The Rev.
title: The Rev. Richard Carter Smith
dates: (1802-1864)
---

perpetual curate of Charlton-next-Woolwich, father of Ann Carter Smith

He was christened Morwenstow, Cornwall, 29 August 1802, son of William and Ann Smith; and married, at Campton, near Bedford, on 24 November 1825, Mary Williamson, daughter of the Rev. Edmund (Boase has Edmond) Williamson (c.1760-1839), Rector of Campton with Shefford, Beds., and his wife Phoebe Riland.  Smith was admitted, late in life, a fellow commoner at Caius College, Cambridge in 1844, proceeded BA and MA in 1849 and 1860, was ordained deacon in 1848 and priest in 1849.  He served as curate of Sutton Coldfield, Warwickshire 1848-50, Pershore 1851-3, Stepney 1854-7, and Charlton-next-Woolwich from 1862, being appointed to the perpetual curacy of St. Pauls Charlton.  He died aged 62 on 1 October 1864. It looks as if Richard Carter Smith was emulating one of his brothers-in-law in retraining for the church in the crisis years of the early 1840s, and that after he was ordained he acted as curate to another brother-in-law for five years. He has  BL or Copac entries but the Harvard library catalogue lists Richard Carter Smith, Reise i Norge 1838 overs av Johnny Johnsen (Oslo, Univertitesforl c.1976). This corroborates the evidence that the Carter Smith family had spent time in Norway. [IGI; Alumni Cantabrigienses, there is a brief death notice in the Gentleman's Magazine.]
