---
id: 28
full-name: Anne Elizabeth Mary Anderson Morshead
first-name: Anne Elizabeth Mary
last-name: Anderson Morshead
title: Anne Elizabeth Mary Anderson Morshead
dates: (1845/6-1928)
---

missionary and schoolmistress

Always called Mary, she was the daughter of Pentire Anderson Morshead and Charlotte Story; her paternal grandmother was a Yonge which made her a cousin of CMY.

She joined the Gosling Society as ‘Bog Oak’ and was one of the liveliest contributors to The Barnacle, she left when she went to South Africa to do missionary and social work in 1868; she later wrote a history of the Universities Mission to Central Africa 1859-1896 (1897) and  A Pioneer and Founder . . .

Robert Gray, first Bishop of Cape Town (1905).

She  also edited Eikon Basilike (1887).

For many years, from at least 1881, she was a matron at Marlborough St Giles Industrial School for Girls, Andover.

Many of her contributions to MP are signed ‘Bog Oak’.

Jackson’s Oxford Journal (30 May 1891) reports her speaking at a GFS conference as a member of the committee for the Winchester Diocese.

She was first cousin to fellow-Goslings Mary Sunderland and Anne Baker.
