---
id: 307
full-name: Eliza Callahan Cleveland
first-name: Eliza Callahan
last-name: Cleveland
title: Eliza Callahan Cleveland
dates: (1839-1914)
---

American correspondent of CMY

She is described as contributing sketches of good works among negroes to Mission Life 1867. She and her mother are mentioned as friends in Elizabeth Sewell\'s autobiography, which was probably how the correspondence with CMY arose.

She was the daughter of Sarah Paine Perkins and Henry Russell Cleveland (1808-1843) and was brought up in the New England political and literary establishment. She was the niece of the art collector Edward Newton Perkins (1820-1899) and was travelling with him and her mother in Italy in 1859 when they were attacked by local revolutionaries, causing a diplomatic incident.

Eugene Hollahan \'Intertextual Bondings Between \"The Wreck of the Hesperus\" and \"The Wreck of the Deutschland\"\' Texas Studies in Literature and Language 33 (1991) discusses her correspondence with Longfellow which she communicated to CMY who published it in MP.

There is a large collection of the Cleveland and Perkins papers in the New York Public Library.
