---
id: 327
full-name: Alice Mary Coleridge
first-name: Alice Mary
last-name: Coleridge
title: Alice Mary Coleridge
dates: (1846-1907)
---

member of the Gosling Society, cousin of CMY

Much the youngest daughter of Francis Coleridge (1794-1854); her mother sank into depression after her birth and she was brought up by her elder sister Harriet Duke (Coleridge) Lowe (b.1829/30), wife of the Rev.

Edward Clarke Lowe (1823-1912) one of the moving spirits in the Woodard Schools movement for the education of the middle classes.

She lived with them at The College, Hurstpierpoint, and was a Gosling as ‘Gurgoyle’ 1863-after 1869.

She became Lady Warden of St.

Anne's Abbot's Bromley, a Woodard girls' school, c. 1874 and spent the rest of her life there.

Her brother Arthur Duke Coleridge was father of Mary E.

Coleridge, the poet.

She was CMY's goddaughter.

It looks from the Barnacle as if she spent some time living with Mildred and/or Mary Coleridge.  [ODNB; Rice, Story of St.

Mary's Abbot's Bromley; Coleridge, Story of a Devonshire House]
