---
id: 329
full-name: Christabel Rose Coleridge
first-name: Christabel Rose
last-name: Coleridge
title: Christabel Rose Coleridge
dates: (1843-14 Nov 1921)
---

biographer of CMY

Daughter of the Rev. Derwent Coleridge (1800-1883), headmaster (1826-41) of Helston Grammar School, Principal (1841-64) of St Mark\'s College, Chelsea, and Rector (1864-80) of Hanwell, Middlesex, and his wife Mary Simpson Pridham;  she was granddaughter of S. T. Coleridge.  The longest-serving member of the Gosling Society, she was called Chelsea Delf to 1863 and Chelsea China thereafter;  she acted as secretary and many members seem to have been recruited by her;  she was first cousin to Cobweb and Hedgerose; Ladybird, Gurgoyle, Pena and Cricket were more distant relations.  The move to Hanwell took place in August 1864. In 1873 she was evidently helping her brother Ernest run a school in his house at Chiddingfold. Contributor to (including Debatable Ground) and later editor of MP. From 1890 she was editor of Friendly Leaves (Jan 1876 to June 1917) a magazine, originally edited by Anne Mercier, produced by the Girls\' Friendly Society (founded 1875). Will proved £4615 [Hainton, Unknown Coleridge;  DNB; will]
