---
id: 351
full-name: Mary Frances Keble Coleridge
first-name: Mary Frances Keble
last-name: Coleridge
title: Mary Frances Keble Coleridge
dates: (1824-25 March 1898)
---

daughter of Sir [John Taylor Coleridge](/person/344), cousin and lifelong friend of CMY, member of the Gosling Society

The intimacy between CMY and Mary Coleridge is not well documented because the letters to her were, Christabel Coleridge states, burnt in an accident, but she is very frequently referred to in letters to others.

Her 1845 engagement to Roundell Palmer, later 1st Earl of Selborne, was broken off, and she never married.

She was devoted to her niece Mildred, daughter of Lord Coleridge, and encouraged CMY to found the Gosling Society partly in order to find an outlet for Mildred\'s intellectual interests.

Her Gosling name was The Old Secretary, but when Mildred lost interest in the society, she did likewise.

She was devastated by the furore over Mildred\'s 1885 marriage to Charles Warren Adams, who had sued Bernard Coleridge for libel.

In the same year her brother Lord Coleridge had married Amy Lawford, who had previously lived as the wife of her first cousin, but had then had their Gretna Green marriage declared invalid.

It appears that Mary Coleridge, like CMY, consequently disapproved of the second Lady Coleridge, and deplored her influence on her husband. [PB: Coleridge, Story of a Devonshire House]

A portrait of her and her sister Alethea as girls sold in 2006 is illustrated at www.artnet.com/Artists/LotDetailPage.aspx?lot_id=5830456F7F89012700A33CFAA5D
