---
id: 50
full-name: Maria Georgina Archer Houblon
first-name: Maria Georgina
last-name: Archer Houblon
title: Maria Georgina Archer Houblon
dates: (b. 1853)
---

member of the Gosling Society

Daughter of the Rev.

Thomas Archer Houblon (1808-1874) and Eleanor Deedes (d.1865).  A Gosling as Polypodium, she lived in December 1876 at Peasmore Rectory, Newbury.

Her father had been one of W.J.

Butler's curates at Wantage;  her only brother, the Rev.  T. H.

Archer Houblon (1849-1933) succeeded him as Vicar of Wantage, 1881-1907, and Maria kept house for him.

She became an Associate of the Wantage sisterhood in 1870.

Of their three sisters Eleanor (d. 1917) became an associate in 1866;  Sophia (1844-1927) became a professed sister of the community in 1878 and Reverend Mother 1912-1920; and Louisa Margaret (d. 1924) became an associate in 1871, professed sister in 1880 and Reverend Mother of the daughter house of the Holy Rood, Worthing.

They were cousins of other Goslings Elisabeth Forbes and Rachel Deedes and were also related to the Bramstons [LG 1952, Lady Anne Archer Houblon, The Houblon Family;  Wantage archives;  WWW;  Journal of Clarissa Trant]
