---
id: 512
full-name: Marion Finlaison
first-name: Marion
last-name: Finlaison
title: Marion Finlaison
dates: (b. London 1834/5-1914)
---

schoolmistress, subeditor of MP

CMY\'s neighbour Marion Finlaison (1834/5-1914) is described in Coleridge, [Life](/organisation/40), 272, 280.

She ran a small boarding-school in Otterbourne and acted as sub-editor of MP.

Although Marion is what she wrote on the census forms, it appears she was actually baptised Catherine Jane.

She was the daughter of William Finlaison (1789-1852), Captain RN (he was brother of the actuary and was on the Beagle, briefly also governor of Ascension I) and Mary Anne Ovenden.

In 1861, calling herself Marion C. C [or J?].

Finlaison, she was living with her mother in the household of her sister Mary Isobell (1819-1900) and brother-in-law, the Rev. [Henry Jenner](/person/758) (1820-1898), Rector of Preston, Kent.

Jenner was later made Bishop of Dunedin New Zealand (though rejected as too High) and Bishop of the Eglise Catholique Gallicane.

Marion Finlaison acted as subeditor of the MP and ran a small boarding school in Otterbourne from late 1870s, probably successor of the school run by Mary Adams.

She was evidently known by her family as Kate.

She lived at Wingham between Preston and Otterbourne. [Not in PO Directory 1875, listed in White\'s Directory 1878; Finlaison letters; geocities.]
