---
id: 846
full-name: Mary Elizabeth Latimer
first-name: Mary Elizabeth
last-name: Latimer
title: Mary Elizabeth Latimer
dates: (1822-1904)
---

American historian, contributor to MP (1879-93)

She lived in Baltimore, Maryland, and published two novels as Elizabeth Wormeley: Amabel: A Family History (1853) and Our Cousin Veronica, or, Scenes and Adventures Over the Blue Ridge (1855). In the 1880s she began writing again, publishing three novels under the name Elizabeth Wormeley Latimer: Salvage (1880), My Wife and My Wife\'s Sister, 1881, and Princess Amélie: A Fragment of Autobiography (1883). In 1888 she published three translations from the French: History of the People of Israel, by Ernest Renan, and For Fifteen Years and Steel Hammer, both by Louis Ulbach and in 1890 George Sand’s Nanon. In the 1890s and early 1900s she published a series of books on the history of various European nations, and on the colonisation of Africa, three more translations and a final novel, Prince Incognito (1902).
