---
id: 988
full-name: Blanche Catherine Medhurst
first-name: Blanche Catherine
last-name: Medhurst
title: Blanche Catherine Medhurst
dates: (London 1848- Barnstaple 1925)
---

social worker and contributor to MP (1873-5)

She was daughter of Francis Hastings Medhurst (d.1852), of Kippax Hall, near Leeds, and Mary Anne Bushnan; a friend of Mrs Mercier and patroness of Emmeline Spratt.

She published a study of workhouses, The Idle Room (1886). [LG 1871, census] The 1861 census shows Mary Anne Medhurst with two other daughters and her mother Anne Bushman (d.1878) living at 29 Dorset Square; in the 1871 census Blanche is there too.

Hers is an odd story, because her father killed another boy while a private pupil at school and got three years for manslaughter in 1839, coming up before Mr Justice Coleridge; his grandfather, a rich stockbroker, had murdered his wife while insane and was at that time in an asylum. [Times].

She wrote an article in MP (1886) about the Associated Workers League, of which she was evidently a member.
