---
id: 116
reference-type: Organisation
name: Spider Society, The
title: Spider Society, The
---

In January 1873 the last page of the Monthly Packet included an announcement:

TO OUR READERS

COBWEBS OR, THE MONTHLY PACKET ESSAY SOCIETY.

Two Questions, to be Answered in Writing, on History, Literature, Art, or Science, will be proposed in each Number. Answers to be directed to ARACHNE, CARE OF THE EDITOR OF THE MONTHLY PACKET. If 200 of our Subscribers will send a Shilling’s worth of Postage Stamps to the above Address, we will print the best one of the Answers to each Question, provided it does not exceed 2000 words, at the end of the NOTICES TO CORRESPONDENTS in the Number for the second month after the Questions come out. We do not offer a prize, as it is impossible to fix any limit as to age; but we hope sometimes to give a few words of help or criticism.
______________

SPIDER QUESTIONS

Give an account of the history and derivation of the words -- Vaunt, Brag, Bombast, and Rhodomontade.

Describe an Oak-leaf -- its growth, structure, and historical and poetical associations.

Essay societies of this kind, whether associated with a magazine or not, were tremendously popular at this period. The background to Yonge’s foundation of the Cobwebs was her experience of running the Gosling Society between 1859 and 1877. The MP Christmas number for 1872 had consisted (as Christmas numbers often did in those days) of a series of stories by divers hands with a link story. In this case, the link story was the story of an essay society called ‘the Spiders’ ‘in graceful allusion to our being a fraternity of spinsters’. The author of this story was perhaps Christabel Coleridge. It gives an account, in fictional form, of a society which is plainly based on the Goslings. The foundation, immediately afterwards, of the new Cobweb Society was undoubtedly moving what had been a private organization into a more public sphere. When the Goslings were finally wound up in 1877 (after some years in which Yonge had been complaining about the quality of the work produced by recent members) the explanation which was given was that:

Having begun with 12 intimate friends & cousins who actually did 4 questions once a month it has come to only two once in two months & of those generally only one answered by a few - while there is little acquaintance between many[.] It seems therefore time to break it up, since there are other essay societies in plenty now and Mother Goose still superintends the Spiders.

The Spider essay society ran in MP until 1887, when it was wound up and CMY published a valedictory poem [\'Arachne\'s Farewell\'](/book/274) in the April issue.
