---
id: 23
reference-type: Organisation
name: Girls’ Friendly Society, The
title: Girls’ Friendly Society, The
---

This organization was founded by Mary Elizabeth Townsend in 1875, as a response to the forlorn condition of young women working away from home, usually as servants and shop assistants. It established a network of diocesan societies, within which Associates (ladies) provided support and facilities for Members (girls). These were of very various kinds, including lodging, education, recreational facilities, convalescent homes, circulating libraries and employment bureaux. CMY was much involved in its work from its earliest years, and published a rare pamphlet, THe Girls\' Friendly Society: A Short Account of its Working in the Diocese of Winchester to the end of the year 1878 (1879), a copy of which is MS Lambeth Palace Library Tait 268 ff224-9. At that date the diocese had 3,057 members and CMY was in charge of the circulating library. The tribulations of those trying to administer the organization were amusingly described by CMY in MP in 1882 \'A Conversation on the Girls\' Friendly Society\'. It ran The Girls\' Friendly Society Associates\' Journal for the Associates and Friendly Leaves for the Members. CMY’s kitchen maid, Rosina Dewsall, took the exams of the Girls’ Friendly Society Reading Union. Its archive is held by the Women’s Library. Brian Harrison, \'For Church, Queen and Family: The Girls\' Friendly Society 1874-1920\' Past and Present 61 (1973) 107-138 is informative. The charity still exists and its website is http://www.gfsplatform.org.uk/
