---
id: 47
reference-type: Organisation
name: Society of Watchers and Workers, The
title: Society of Watchers and Workers, The
---

This was founded in 1879 by [Edith Jacob](/person/749) (1836-1918), who became seriously ill early in 1868; her disease was described as \'congestion of the spine\' and she spent most of the rest of her life in varying degrees of invalidism. During this first attack, according to her brother, she reflected on the contribution which invalids could make to the life of the Church. The result of this was a paper \'Thoughts on invalid life\' published at the suggestion of CMY and reviewed by her in the Church Quarterly Review. This resulted in the foundation of the \'Society of Watchers and Workers\', an organisation to which Edith Jacob devoted her energies for the rest of her life, and of whose privately printed journal, the Watchword, she was editor. The activities of the society, which included support for homebound \'invalids of the cultured classes\', enabling them to direct their energies in prayer and fundraising for charitable objects, are described in more detail in Kathleen Alice Orr, Letters (1907, 1909), a privately printed memoir of a deceased watcher with a memoir by Edith Jacob. The Watchers were especially keen on missions.
