---
id: 50
reference-type: Organisation
name: Winchester College
title: Winchester College
---

A boys’ public school founded in 1382 by William of Wykeham, Bishop of Winchester. In CMY’s youth it consisted of seventy scholars (chosen until 1855 by patronage rather than competition) living with the Second Master in College, and about 100 fee-paying boys living in ‘Commoners’ under the supervision of the Head Master. There were 120 commoners on George Moberly’s arrival as Head Master in 1836, and numbers had declined by the 1850s. Boarding houses did not exist until the 1850s. The Warden of Winchester College, the head of the whole institution, who lived in lodgings on the site, was the Rev. Robert Speckott Barter (1790-1861), a much-loved figure. Moberly resigned and was succeeded in 1867 by his son-in-law George Ridding. On Barter’s death in 1861 he was succeeded by the Rev. Godfrey Bollis Lee (1817-1903).
http://www.winchestercollege.co.uk/history-of-the-college and ‘Winchester College and Commoners; Blackwood’s Magazine 95 (January 1864) 66-92.
