---
id: 79
reference-type: Periodical
name: <i>Magazine for the Young</i>
title: <i>Magazine for the Young</i>
---

This periodical was founded by Mary Anne Dyson and her sister-in-law and published by James Burns, but edited from soon after the start by Anne Mozley (1809–1891), whose publisher brothers took over its publication in 1850; it ran 1842-1875.

It was known in CMY’s circle as ‘the Pink Mag’; it was a tiny duodecimo production with a pink paper cover. CMY published in this periodical ‘Chapters on Flowers’ (February 1850-December 1852), which later appeared as The Herb of the Field (1853); twenty-seven ‘Langley School’ stories (September 1846-December 1848), fifteen of which appeared as Langley School; ‘Mrs Elderney’s School’ which was never reprinted in volume form (January 1850-Jan 1852); ‘Thoughts on Pictures’ (1853), also never republished; Friarswood Post Office (August 1858-August 1859); Countess Kate (October 1861-December 1862); and New Ground (January 1863-November 1866).
