---
id: 1778
title: To Ann Maria Carter Smith
date: '1860-01-06'
display-date: Jany 6th 1860
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1860/1
---

My dear [Miss Smith](/person/263),
I have been a long time in answering you and thanking you for your story, but I wanted to finish reading it that I might tell you at once all I thought about it.

And now I have 1st to enclose you a [cheque](/topic/102) for the amount due to you for ‘[Who will come & do likewise](/organisation/265),’ the praises of which I hear on every side; and next to congratulate you on the prosperity of Aggesden.

The [Christian Remembrancer](/periodical/59) has a capital little notice of it, which I think a great prize, as it so seldom mentions books of that description; and I think the [Saturday Review](/periodical/99)’s article[^2] about it was quite a testimony to its excellence in its own line, tho’ the S R itself is strongly bent on despising the day of Small Things. I could not help thinking the chapter of the Wynnes which I read last night an excellent answer to its one sided view about ‘keeping the conscience up to the quivering pitch.’ I really think that the article was not ill natured to you (more so in spirit to me) and I think it will sell the book rather than hinder its sale.

It is a great shame to call your writing like mine, for you have quite a different line, and more vigour in it - as in [Thorns & Roses](/periodical/253) which is still my favorite.

Now about the Burleighs.[^3] There is much that is pretty in them, especially the opening, and in Lettice’s character.

The best part is Olivia’s illness and her reformation, but I am afraid that it wants a good deal of recasting.

Somehow the people are not alive, as yours generally are, perhaps from its being harder to do a long story of the last century than only a short sketch. I am afraid I must make a great many criticisms.

First, the duel is of no use, and has no consequences though you threaten both youths with punishment, Gerard worse than John, and that he did not get.

Then, there is too much of the tendresses between Dr Blomfield and his wife, I do not think the Doctor has quite come up to what you meant him to be. I am sure such a man would never talk of scolding which he would consider a vulgar feminine performance quite beneath his dignity.

Nor in those stiff old times would his wife call him Gerard.

You must take care too of Gerard himself or he will really deserve for the Saturday to call him a spoon.

With regard to both him and John, I am almost afraid the trials of young men of that date were almost too coarse for womankind to meddle with now.

The best thing about the family is Dr Blomfield and his grandson, but you must take care of useless bits of conversation and fun with Lettice, which gets rather tiresome.

Then Jack Mowbray is rather a conventional sailor than a live man, and his way of answering Olivia’s scorn does not strike me as real. I do not think she should be blamed for his death, for if she had accepted him ever so much, he could not have refused the offer of a ship in time of war.

And his being killed much diminished the punishment of the loss of her beauty, for I don’t see what use it was to her if he never was to see her again.

Nor can I see that her never marrying was a reason that she could do without her fortune, or that anyone would have thought it right to take a girl of 22 at her word that she should never marry and could give away her money.

It is the only young ladyish incident I ever knew you commit.

By the by, I am going on the old Scottish principle of doing as you are done by, to pass on to you a criticism once made on the first draught of [Redclyffe](/book/15), that Laura shewed all her grief for her lover’s illness by mere exclamation of ‘O Philip’ and I thought of this again with John’s ‘O Camilla’. I should like Camilla to have been more drawn out. I suppose little Mary’s epitaph is a real one; but it is too comical for Olivia or her mother to have invented it, and I am afraid it made us laugh all through the farewells. I think dandified is a word of the 19th century, people were macaronis in that time, and John’s tricks would have been those of a Mohawk.
I am shocked at such a letter of holepicking, but I know you sent me the M S that I might candidly tell you how it struck me.

Now I think that it might do if much shortened, and re-studied, but in its present state, I think that to put it forth would be a perilling of your Aggesden reputation, and I am convinced that nothing but great care and labour can keep one up after a lucky hit has once gained attention.

Hoping you will not think me as bad as Dr Blomfield
[signature cut out]


[^1]: Envelope addressed to Miss A C Smith/ Rectory/ Old Charlton/ SE and postmarked Winchester 6 January and London SE 7 January 1860.
[^2]: ‘The Whole Duty of Young Women’ Saturday Review (24 December 1859) 768-9, praises Aggesden Vicarage: ‘in point of literary ability, this seems to us the best of all the imitations of Miss Yonge’, but mocks it for its trivialities and for encouraging young women to keep ‘their consciences up to the quivering point.’
[^8]: We have not been able to find a published version of this story, and Smith may have abandoned it in the light of CMY’s criticism.
