---
id: 1784
title: To Ann Maria Carter Smith
iso-date: '1860-03-12'
display-date: March 12th 1860
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1860/6
---

My dear [Miss Smith](/person/263),
I am delighted to hear that the rest of the Websters[^2] is en route. I find that I never get a book parcel given out on a Monday morning, so I am not at all uneasy at not having received it at the same time as the letter, though I feel rather baulked of my afternoon’s pleasure. My mother and I have most thoroughly enjoyed these first seven chapters, which she thinks the best thing you have done, and I - tho’ still holding to my first love, the [Thorns & Roses](/periodical/253), do admire very much & think likely to be very useful. I am quite in love with the story, & think my sentence above sounds very flat. It is so exactly the line of life one wants stories about. I scarcely found any hitch in the language but that is always less easy to judge of in M S than print and I think that re writing will smooth off everything verbal, and get hold of sentences by their right ends. Those relations with the clergyman are excellently done, and the grand mamma difficulties are a very good notion. I only think that perhaps her vulgarity might be a little felt. Would she ever, especially as you tell us she was humble, leave off sirring her husband and son, and speaking of her son as Mr John, I am sure she never - at her age - could have called her former master George. I do not think either that the world could ever have ceased to speak of the father as Mr Webster, and the son as John Webster. I have been thinking over all the cases I know, and cannot find one to bear out your nomenclature. In excuse for George, could not the old lady never cease from something rather provoking, as for instance calling him Master George Should it not be made clear that the rest of the family went to Church when the father went to Friarswood. By the by, is not 4 miles a huge walk? We are just 4 miles from Winchester and I don’t think there would be time to make it an after tea walk even for a strong man in summer. However no two people agree about possible walks. I do delight in that interview of Grace & Mr Haxted. I think the difficulty so well managed, and the London part is capital. I am so glad the rest is on its way. [The Stepmother](/book/38) will finish two or three numbers after Christmas (I hoped she would have all been stuffed in before, but that proves impossible) and I am so glad to have this to succeed her. About plots - don’t you know how one photographer can so place himself as to make the real objects group themselves into a picture. I think the point is to find the point of view in which events might thus group themselves, however simple

yours sincerely

C M Yonge


[^2]: This story was subsequently published in MP (May 1861 to December 1863) under the title \'On the Banks of the Thorne\'.
