---
id: 1787
title: To Ann Maria Carter Smith
date: '1860-03-21'
display-date: March 21st 1860
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1860/8
---

My dear [Miss Smith](/person/263),
I have been so much taken up that I could not answer your letter sooner, and thank you for the way you have taken it. I am amused at the ordeal you are undergoing. I never met with anything like it, except once, when going with [a cousin](/person/1582) to luncheon with a connection of hers, she was addressed with ‘Anne, why could you have lent us [Abbeychurch](/book/2).[^2] Those games!

And that mother!’ Afterwards we found we had all betrayed ourselves.
I think you are right in not making old Mrs Webster have been a servant - the mutual relations would be so very difficult to get over especially at that time of life, and the daughter of a respectable farmer or tradesman would fit in much better. I am quite relieved to hear how Harold and Grace are to end, though it is very cruel of me.

So many [cousins have little inclinations](/topic/101) that go off safely that it is much safer so to shew it.

Though after all, there is a cousin marriage coming in the story by two authors,[^3] only I don’t think they were first cousins, and I could not help believing in it myself.

On the whole, if you ask me I should prefer Grace’s staying at home, and making more of the Sydneys, but have you got a decided catastrophe point of the story, I mean to finish up.

When once my framework is settled, I never could make such a change as that, nor believe in it - if I leave out anything, I usually believe it really happened all the same only that there is no call to describe it. I want George and his father to get themselves right. I think it is the thing I care specially for.

How good that last scene is about the cricket, & the different ways of treating brothers.
I think there are some reviews that think a book is disposed of when once they have said it is like something else. I remember one novel being said to resemble [Miss Austen](/person/76), [Miss Edgeworth](/person/1819) & [Sir Walter Scott](/person/1672) all at once, and for a long time [Mrs Mozley](/person/1062)’s [Fairy Bower](/topic/240) was a great plague as a comparison both for [Miss Sewell’](/person/1301)s books & mine.

It is cleverer than either certainly, but not in the same line that they aim at, and I think I never saw any books so full of compression if I may say so - so free from the water element.

Perhaps real life writing going over much of the ground of common life has a tendency to be like, from the very likeness of events, & superficial people see the resemblance more than the essential dissimilarity.

However I only told you as a motive for consideration whether every effort should not be made to save yourself from dilution and to condense as much as possible. I do think the characters well worth pains, & am very fond of them all

yours sincerely

C M Yonge


[^1]: Envelope addressed to Miss Ann M Smith Compton Rectory/ Shefford and postmarked Winchester 21 March 1860.
[^2]: CMY’s first novel, published in 1844.
[^3]: Jean Ingelow and Frances Mary Levett, One story by two authors: or, A tale without a moral. (London 1862) Serialised in the Monthly Packet, February 1860 to June 1861.
