---
id: 1791
title: To Anne Sturges Bourne
iso-date: '1860-05-16'
display-date: May 16th 1860
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Anne Sturges Bourne
manuscript-location: 'MS Hampshire Record Office: Sturges Bourne Collection: 9M55
  F55/2p1'
---

My dear [Miss Bourne](/person/1379),
In the first place you will be glad to hear that it was a very nice quiet Sunday & Monday at the Nest.[^2] [Mrs Dyson](/person/462) cheered by the return of “her son,”[^3] and both glad of finding that his family really consider it a boon that they should stay and take care of him while their house is building at Crookham.[^4] I hope that [Mr Keble](/person/798)’s suggestion will take effect, and the form of the testimonial be a school room and prayer room for [M A’](/person/464)s girls.[^5] Nothing seems likely to give them so much pleasure, only [the Judge](/person/344) hesitates lest such a thing should not be permanent. I do want a good sensible large room to belong to the establishment, and I hear the one school room at the almshouses is smaller than the present! Only they will not eat in it. About Hannah, I wish you would come and talk - and see [Harriet](/person/1359) and [Mrs Hicks](/person/690) - and then we could talk over many things.[^6] Our people are away certainly till the end of next week, but we have one of the Crawleys here. Any time would suit us, & if you could come on your way to or from the Nest it would be very nice, for a day or night as the case might be.
Now for the legacy you were so kind as to leave me. I like the Air part very much, and shall put it in as Hints on Reading, being as it is a species of review. The only point where I doubt is whether girls should be told that they should prepare themselves for possibilities by curtailing luxuries, because as we - (including the dogs) agreed, many who marry poor are fairly tired out with luxury, and enjoy the small scale. It is their ignorance, not self indulgence, that is the trouble. [Kate Crawley](/person/899), who is very delicate, & lives in a small house, very poor, went along with every word against stuffiness & for its prevention, so that I am sure it is practical. But is it true that a tradesman’s daughter would not be restrained by convenances from scouring -? I fancy many of them would be more afraid of it than ladies. I think that scouring hardens hands, and hurts knees so much and is so easily done by the very roughest maid or char woman that it is not to be upheld to girls like dusting or bed making. Had not the girl better get a friend to walk with her (who needs it as much) than worrit her poor old mother, who had to mind the shop or the children.
The Cleanliness & the Food both seem to want more consideration and development. Do you think girls want to be advised not to wear old clothes but to buy new ones? And I think you hardly consider enough the capacity that animal fabrics retain of shaking off dirt - brushing & airing really being as good to them as washing to linen - except in the matter of grease - and should good healthy pure mud be put on a level with grease, which cannot be got rid of -
I doubt whether any body under 30 is guilty of an overweening constancy for an old woollen gown or cloth cloak - the latter of which if people are moderately tidy need never get into any dirt at all, and is aired whenever worn, black velvet is a much more dangerous article especially when made into streamers for the hair - or very old jackets. I think an entire detailed article on dress would be very useful, but there is too much of it wanted to be squeezed in at the end of the Air. I should like to distinguish the economy of the real good all-wool thing that will clean and put away, and that which will never properly clean because half wool, half cotton, each needing contrary treatment.
About food, you have I see only jotted down the heads, except maid’s tea and extra meals, where I fully agree. But I doubt whether the labourer doing upon meat once a week is a wise example, because his beer is allowed for, either given or considered in his wages - and as a fact, the underfed grow old and get exhausted sooner than the well fed. Besides, he lives a good deal upon pure air out of doors. Even maid’s tea is to be distinguished between the stimulus when you are obliged to do too much for your strength for a time - & the idleness of having it without need. Would it be too much to ask if you could do these two in a little more detail for other numbers?
Your Rose is capital, her mistress especially so. I think I should have found you out even if I had[^7]

Yours sincerely

C M Yonge
I am so glad you have fallen foul of knick knacks - but possibly it might be said – “if you must have them, dust them yourself.”


[^2]: The Dysons’ nickname for Dogmersfield parsonage.
[^3]: The Dysons were childless. Evidently Charles Dyson’s successor in the parish was being \'mothered\' by his widow Elizabeth.
[^4]: The death of the Rev. Charles Dyson (1788-24 April 1860) meant that his wife Elizabeth and his half- sister Mary Anne had to find another home, which they did at Crookham near the home of Mary Anne’s girlhood friend, Anne Sturges Bourne.
[^5]: The girls in the \'small boarding school for superior village girls\' that Mary Anne Dyson conducted as a work of charity. See Coleridge, [Life](/organisation/40) 147-149. A schoolroom was now needed in Crookham
[^6]: The letters that follow suggest that Hannah was a girl in the village whose future was being settled, with CMY’s lifelong servant, Harriet Spratt, and the wife of the village carpenter being included in the discussions.
[^7]: Presumably a story written by Anne Sturges Bourne, who had since the 1840s been writing short fictional stories incorporating advice to working class girls for the [Magazine for the Young](/periodical/79).
