---
id: 1814
title: To Susanna Warren
date: '1861-02-07'
display-date: Feb 7th 1861
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Susanna Warren
manuscript-location: 'MS Princeton University, Parrish Collection C0171: Box 29'
---

My dear [Miss Warren](/person/1475),
Many, many thanks for the extracts.[^1] I was waiting to write and thank you for them till a few pressing letters were put out of the way - indeed I dont [sic] believe I thanked you intelligently for the first set, I mean not after I had really studied it.

Henerety I believe to be meant for Henrietta here who was generally so called.

Another they have given up in despair and call Mary. [Venetia Stanley](/person/1842) shone out as a matter of interest and curiosity, and the Alethea who was married at nine years old interested me, as hers is a family name of our own.

All the Aletheas seem to have been after 1600, indeed it seems as if the Reformation had set everyone wild after inventions.

Fancy Dame Trot being accounted for! I should think the Trotts must be same as Troth which occurs afterwards.

Ysonde must have been old and hereditary, I have her again in a register from [my uncle](/person/1623)’s parish of Newton Ferrers, where there is a man named Mirth and a woman named Venus in the early years of 1600.

It is funny in the German book to find an explanation of the English custom of christening by surnames, with Betsey Trotwood as an example - it quite agrees with the objections made to registering a child whom a cousin of mine then living in the Prussian dominions wanted to call by our old family name (or surname) Duke, which the registrars insisted was no name at all.[^2] Could you not make a collection of these old Durham customs and let me have them for the [Monthly Packet](/periodical/52). I do not think it would at all interfere with the county history, but would be rather a gathering of materials.

Thanks for Mr Nichol’s letter, I am not sure about writing to him till my plans are a little forwarder, as I do not quite like to trouble a stranger till I can put my direct wants together in a positive form of enquiry.

Just now I am in the midst of the names from the Latin (having done those from the Hebrew and Greek) then must follow Keltic and Teuton, and then the fashionable names of different periods in each European country must be done - and till I get to this I shall hardly see my questions upon the single county
I retract about Trott.

Turning over Laing’s Chronicle of Norway, I fell on Queen Droth, in ante Christian days! I hope the Book hawking meeting will be propitious, and Routledge too -

Yours sincerely & most thankfully

C M Yonge


[^1]: Warren had evidently supplied CMY with material for her [History of Christian Names](/book/48).
[^2]: Betsey Trotwood is a character in Dickens\'s David Copperfield who calls the hero \'Trotwood\' after her surname\'. CMY\'s cousin Dr. [John Francis Duke Yonge](/person/1622) had at least two sons by his first marriage who were born in Coblentz in the 1840s.
