---
id: 1828
title: To Susanna Warren
iso-date: '1861-05-09'
display-date: May 9th 1861
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Susanna Warren
manuscript-location: 'MS Princeton University, Parrish Collection, C0171: Box 29'
---

My dear [Miss Warren](/person/1475),
The Lecture has not yet found its way to me, but I hope it soon will. I know there is no reason for mistrusting the post in such cases as a family party generally takes a good while in all sucking the marrow of anything of the sort, especially if it be in M S, and as I do not think we are likely to be interrupted for a long time there is no need of hastening your friends, except so far as to ensure its not being forgotten.
I shall be delighted to have your Dragon paper, they are monsters for whom I have a special affection, beginning with More of More Hall,[^1] and going on to Kempion the King’s son.[^2] Have you seen [Campbell’s Tales from the Western Islands and Highlands](/organisation/201) - most curious fragments of myths from all manner of places worked up together, a Northern Blue beard but with a little cat who licks off the blood, helps the lady out of the scrape teaches her to disenchant Blue beard (not that he has a blue beard) and becomes a princess. There is a “Draygan” in one who comes out of the Sea.
Does the [London Library](/organisation/29) send its books into the country, if so it would be an immense boon to me, and I should be very glad to see its terms &c. There are things of which a months [sic] use would be of infinite service to me, though I should not like to buy them, and getting at them in a public library would be nothing compared with having them at home.
I have had our own register here lately,[^3] and found nothing very curious except that people were born, not baptized in Commonwealth times. The parish must have been more exclusively Joan, Betty, Mary & Anne than now, and if a wife came in with a new name it never went on to the daughters Science and Philadelphia, by and by turned into Phillis, were our funniest - one of the latter died in my time. She belonged to a family we now call Diddums but which began as Didymous and oddly enough were always having twins, one pair called Adam & Eve. But I was disappointed to find how few of our present surnames went back any good distance. I fancy that there was then a large proportion of Roman Catholics, indeed there is a note of a discovery of many of their children unregistered
Bisley, Gloucestershire has one Em, a girl, many Tybaltas, and an Ysolda - how many specimens of that old name one finds, though I never saw it belong to any historical person. Thanks for the hopes of [Exeter Cathedral](/periodical/244)

Yours sincerely

C M Yonge


[^1]: \'A legendary hero who armed himself with an armour of spikes; and, concealing himself in the cave where the dragon of Wantley dwelt, slew the monster by kicking it on the mouth, where alone it was mortal.\' (Brewer, Dictionary of Phrase and Fable. 1898)
[^2]: ‘Kempion’, in Sir Walter Scott’s Minstrelsy of the Scottish Border, features a “fiery beast” that could only be disenchanted by the kiss of Kempion “the king’s son”.
[^3]: As part of her research for the [History of Christian Names](/book/48).
