---
id: 1836
title: To Frances Sophia Coleridge Patteson
date: '1861-07-07'
display-date: July 7, 1861
from-name: Charlotte Mary Yonge
to-name: To Frances Sophia Coleridge Patteson
manuscript-location: MS location unknown. Printed in Romanes, <i>[[otherbook:241]Appreciation]</i>
  122-4
---

My dear [Fanny](/person/1151),
I thought it might be more comfortable to you not to hear from me till the great stress of letters was over at first, and so that I would wait to write till I could send the precious letters.[^1] We took our turn the last, and so read them upon Friday, the very day one would have chosen above all others for it, the girding to the battle in that calm and self-devoted spirit seemed to chime in so perfectly with the resting from the labours.

One in spirit as they always were, how much closer they may be together now!

And now your Sunday is passing fast away, and that return to daily life is coming that seems hardest of all when the external calm is over, and one seems no longer lifted into that higher and more real region, but beginning to to find what the world is without the arm one has leant on so long.

It is strange how the recurrence of scene or place brings this back as fresh as ever when one thinks one is used to it: the pang of not looking for the [white head](/person/1631) in the stalls of the Cathedral was one of the first, and it was almost as overcoming to see the field-paths where we used to walk between churches on Sunday . . . and the not having him to meet me at the end of a journey; only that brought the thought, Would that face meet me in the real home when the journey is over?

It is the first vexation and worry, the first loss, that is, after all, what comforts one the most - when it is what would have been doubly felt for them, and one knows they are shielded and only gain by it.

After your last note to me, I was sure your first feelings must be of the relief that the hard and long way to the grave was over, and rest had so gently begun, and this must be the abiding sense, even though the sore, sore missing must come, till the grief turns with time to solemn pleasure.

After all, but for those beautiful letters, it is such a separation as that from your brother, and with no anxiety and suspense.

Those letters do go home to one’s heart; as [Mrs.

Keble](/person/795) said, one can hardly part from them; there is something in the depth and simplicity of your brother’s that ought to do one great good, and fills one with more reverence than I can say.

His own feelings seem to me to absorb all the rest, and to be much the most precious part; but there certainly ought to be a description of the outward things put forth, and this could, I should think, be easily compiled from his and [Mrs.

Abraham](/person/3)’s letters. I have done as you told me, and have put the bound [Daisy Chain](/book/24) into [Mrs.

Biss](/person/161)’s case [^2]. . .

You will be feeling the whole sorrow freshly both in thinking of the arrival of the letters in N.

Zealand, and in watching for the answers; but I have hoped from the first that the tidings of the first alarm and then of the end would not be far apart, and that there would be no dreary watching for mails coming in.

And, oh, what a comfort the talk to [Mrs.

Selwyn](/person/1297) will be!

Mrs.

Keble wrote to her, but she could not come then, but hopes to manage it.


[^1]: Fanny Patteson had been receiving letters of condolence on the death of her father [Sir John Patteson](/person/1156) (1790-28 June 1861).

The letters which CMY and her mother had been reading were evidently from Fanny Patteson’s brother, the [Rt.

Rev.

John Coleridge Patteson](/person/1155) in Melanesia.
[^2]: This is probably a misreading by Romanes of ‘Mrs.

Bliss’s care”, see the letter to Sophia?

Bliss (1 July 1861).
