---
id: 1838
title: To Margaret Gatty
date: '1861-09-01'
display-date: '[September 1861]'
from-name: Charlotte Mary Yonge
to-name: To Margaret Gatty
manuscript-location: MS location unknown. This fragment printed in Christabel Maxwell,
  <i>[[otherbook:306]Mrs. Gatty and Mrs. Ewing]</i>, (1949), 133.
---

[My mother](/person/1606) and I are much obliged for [your](/person/549) kind letter.[^1] Our route to Thirsk lies direct from London, and we are due there on Friday, staying there about a fortnight or so--but afterwards we have to get across to Gloucestershire, and Sheffield is so temptingly on the way, that if you are likely to have room for us, we should much like to sleep a night at Ecclesfield, in the last of September, as far as I at present see my way.[^2] My mother is always in dread of strangers, so her consent is to be considered entirely due to [Aunt Judy](/person/494)’s fascinations!

By the by, I am going to say what I always do wherever she goes, that if anyone wishes to see her (Mamma) minus a headache, they must give her coffee instead of tea--the latter being poison to her!

When I do get her out on her travels with me, I feel highly responsible, so I daresay you will excuse my mentioning this.... I have not half said how pleasant it will be to make bodily acquaintance, nor how kind we feel your invitation.

Yours sincerely
C. M.

Yonge.

We bring a maid, so I tell you the worst of us beforehand!!

But we are not so troublesome as to want two rooms, Mamma and I being one in sleeping matters.


[^1]: Gatty’s biographer Maxwell writes: \'In 1861 the two women met.

In September of that year Charlotte Yonge and her mother contemplated a visit to Thirsk in Yorkshire and must have received an invitation to Ecclesfield, for this was Miss Yonge’s reply.\' The visit took place on October 2.
[^2]: CMY and her mother were preparing to stay with the [Rev.

Robert Francis Wilson](/person/1541) (1808/9-1888), Perpetual Curate and later Vicar of Baldersby since 1858, formerly a curate of Keble’s at Hursley and subsequently Vicar of Rownhams.

The vicarage, the church of St.

James, Baldersby, and a model village and school to go with them, were built from 1856 to the designs of William Butterfield in High Church taste at the expense of Viscount Downe.

In fact they were no doubt still being built at the time of this visit.
