---
id: 1843
title: To Ann Maria Carter Smith
iso-date: '1861-11-21'
display-date: Novr 21st 1861
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1861/13
---

My dear [Miss Smith](/person/263),
You must have begun to wonder if the Indian £10 was coming I am sure I did, but here it is at last, in good time I hope. It seems that [Mrs Elphinstone](/person/482) has been very ill, and that has prevented her from sending it sooner. I will write to her to acknowledge it as soon as I have heard from you. I am glad to see your three Ks in the [Churchman](/periodical/62).[^2] I augur well of them, and the Banks of the Thorne are much liked. You will have some sheets of [Mrs Grant](/book/43) very soon, but I had to abridge her a little there was so much more of her than of the others.
Fancy the amazement of some travellers in the train at hearing [Dr Harris](/person/629) of Torquay alluring two ladies thither by saying ‘If you will come to Torr I will give you the worst street there’.[^3] You may fancy they were kindred
[the letter seems to break off here, although the fourth side of the sheet is blank. Possibly CMY forgot she had not signed the letter and posted it like this]


[^2]: The Daughters of the Fair Elms By the Author of The Wynnes, a serial which ran in the Churchman’s Companion from November 1861.
[^3]: Presumably he was trying to “allure” them into being district visitors in his parish.
