---
id: 1846
title: To Henry Hucks Gibbs
iso-date: '1861-11-25'
display-date: Novr 25th 1861
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Henry Hucks Gibbs
manuscript-location: MS Guildhall Library 11, 021 v.19
---

My dear [Henry](/person/558).
To begin with domestic intelligence. You and your kind [wife](/person/1856) will, I am sure be glad to hear that a very fine little [boy](/person/1607) made his appearance here on Saturday evening - one day less than 13 months younger than his [sister](/person/1613); who has not quite decided whether he is a doll or not.[^1]
Next, I shall be very glad of the prospectus &c that you propose to send, for I want details of instructions.[^2] If I find the word explained in the Glossary attached am I to note that it is so - am I to refer to page or chapter - and the like. Of course mere mispronunciations are not worth noting - but would you put such a word as iccles instead of icicles - or hummobee for humble bee - The Glossary puts in all manner of very ordinary words, such as croak, the voice of a raven, and wag to move - by the by not only applied to a dog’s tail, but as it is in Hampshire to any sort of movement. Perhaps you would send me one of your notes by way of specimen or pattern.
Do you know whether your friend [Mr Halliwell](/person/1857) has traced the history of Cock Robin’s dispute with Jenny Wren?[^3] I find that in Scotland it is called Lennox love to Blantyre, and is there considered a satire on Queen Mary and Darnley, there being the additional verse in which Robin enquires after his ring, and hears that she ‘gied it to a lodger, a leal sweet heart o’ mine o’ - whereupon he hopped on a twig, and gave her the well known reprimand which seems to me more to the purpose than any thing Henry Darnley ever did. Besides, I can’t make out that Blantyre has anything to do with Queen Mary - though the name is Stuart. I want to make out the history partly for the sake of the Red breast, and partly because in allusion to it, the estate that Frances Stuart of Lennox and Richmond gave her brother Lord Blantyre was called Lennox love to Blantyre.[^4] Another subject I should like to begin is what the figures were on old Spanish playing cards.[^5] The [Wilsons](/person/1541) have a most curious set, in which the Spades are certainly swords which is all right, but the hearts are like music stools, and their ace [sketch] for which I can only account as the standing pie of the tarts made by the Queen of Hearts. The diamonds were round, I thought they were meant for coins - the clubs real clubs not trefoils. Did you ever light on anything to explain these?
your affectionate cousin

C M Yonge


[^1]: Francis Arthur Yonge (1861-1918) and Helen Emma Yonge (1860-1941).
[^2]: The reference is to the original Proposal for the Publication of a New English Dictionary by the Philological Society (London: Trübner and Co. 1859). At this date the editor of this dictionary, which later became the O.E.D., was Frederick James Furnivall, (1825-1910) – see letter to the Rev. W.G. Henderson, 10 December 1861. As later letters from CMY to Furnivall (e.g. letter dated 11 August 1863) show, she and her mother did a considerable amount of research for him.
[^3]: J. O. Halliwell (1820-1889) had published Nursery Rhymes of England (London: Smith 1842).
[^4]: Frances Stuart, Duchess of Lennox and Richmond (1647–1702), a celebrated beauty at the court of Charles II, bequeathed her estate to her nephew Lord Blantyre.
[^5]: The Gibbs family firm had trading links with Spain and South America, and its principals spoke Spanish; H. H. Gibbs privately printed a study of The Game of Ombre in 1874.
