---
id: 1854
title: To Ann Maria Carter Smith
iso-date: '1862-01-01'
display-date: Jan 22d [1862]
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1862/1
---

My dear [Miss Smith](/person/263),
I enclose your cheque. I am very sorry to have kept you waiting so long, but [Mr Mozley](/person/1065) has not paid me yet, and as I sent him an appeal the other day to see if I could not get our [pay raised](/topic/102), I was waiting for his answer though even if it were to raise our terms it would hardly be for this year that is past. I feel very cross every morning when the post comes with no letter from him, and I think how many expectants are abusing me!
I hope you have a great punishment in store for your three Ks - otherwise I shall be much scandalized, Rosamond is bad enough but I cannot understand Rachel and Marion being shocked and the father not more angry. I recognized Frank, I wish you had given him his own surname. I think you must be as much tormented by time as I am in [continuing the Daisies](/book/53)[^2], perhaps more as you have married two stories. I see your heart is with Frank & Elizabeth much more than at Fair Elms, and I acquiesce, provided you will make that terrible Rosamond repent. I know a girl so like her that I can’t bear to see her so naughty

yours sincerely

C M Yonge


[^2]: The Trial, the sequel to The Daisy Chain, began serial pulication in the MP in January 1862.
