---
id: 1867
title: To Henrietta Elizabeth Fursdon
iso-date: '1862-06-27'
display-date: June 27th 1862
from-name: Charlotte Mary Yonge
from-address: '[Otterbourne, Winchester.]'
to-name: To Henrietta Elizabeth Fursdon
manuscript-location: MS Mrs Katherine Wykes-Sneyd
---

My dear [Irene](/person/538),
Many thanks for the photograph which I am glad to have as a much pleasanter likeness of you. It seems odd that it should have met [Pena](/person/973)’s and as [Humble Bee](/person/81) is staying here, we set her to guess by the old ones which of her fellow [Goslings](/topic/104) it was. The Exhibition has grievously affected the Goslings this time and few have sent in answers.[^2] Humming Bird[^3] alone has answered all. I think your Missions have the prize - they are very interesting.
Many thanks too for the Stamps. You have been very kind about them. I have not many more than 50 [Last Heartsease Leaves](/book/45) left now, and they will be sure to go off in time, but if anyone turns up happening to want one, you will know where to apply. I have been for a longer walk than I intended and cannot write Mother Goose’s letter tonight but unless [Albatross](/person/622)’s should come in to morrow, which I do not expect, I shall send the answers to you tomorrow as Humble Bee has seen them. [Glow Worm](/person/534)’s answer was good, but Humble Bee’s better.
your affectionate
Mother Goose


[^2]: The International Exhibition held in South Kensington 1 May-1 November 1862.
[^3]: Unidentified.
