---
id: 1869
title: To Ann Maria Carter Smith
iso-date: '1862-07-26'
display-date: July 26th [1862]
from-name: Charlotte Mary Yonge
from-address: Baldersby
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1862/4
---

My dear [Miss Smith](/person/263),
Your letter has been following me all over the country and has just reached me here. I am ashamed of the blunder that must have been made somehow, probably by myself, but here I am in Yorkshire out of the way of making out how the error could have happened.
I was terribly hurried while we were preparing to leave home, and did not myself correct the paper of the M P contributions, but the person who did so is generally more exact than I am so I think the blunder must have come in the reckoning afterwards. Certainly [62 pages would amount to £7..15](/topic/102)- so that I ought to have sent you £9 with the slight encrease. I am very sorry there has been this error in the matter, and the more so because I cannot make out how I fell into it.
Would you let me wait to make it up till I get home, though that may not be till the end of October when I shall be able to make out how it was, and clear it up I am ashamed to ask this but I daresay you will kindly allow it, though it is not on Turenne’s principle of paying his debts before he went to the wars. Our programme is to remain a fortnight longer here at Baldersby Parsonage Thirsk, then go to the Scottish border, and then into Devon. I fear you are in the height of moving uncomfortables

yours sincerely

C M Yonge
