---
id: 1875
title: To the Reverend Henry Octavius Coxe
iso-date: '1862-10-29'
display-date: Oct 29th 1862
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To the Reverend Henry Octavius Coxe
manuscript-location: 'MS Bodleian Library, Oxford: MS. Don. d.144 ff 156-7'
---

My dear [Mr Coxe](/person/377)
I am going to venture on sending you my Greek Saints’ names. They are out of a Russian Calendar, and are those that seem to have been productive of names and that cannot have been common to both the Eastern and Western Churches since [Alban Butler](/organisation/27) takes no notice of them. I hope it will not be very troublesome to you to note down for [me] where and when they lived, and just the leading feature that individualizes them. I am almost ashamed to bother you about it when you are so busy, but even if I were in the study of which I have such pleasant recollections, and I hope gained much ground, though if I had been less stupid I should have gained more.	
With many thanks for help, past, present and to come.
Agrippina	 June 23
Anysia		Dec 30
Anchippius	Feb 19
Glycera	May 13
Demetrius 	Oct 26
Emilianus	Aug 8 ?
Irene			May 5
Jebroma	June 2
Charlampadius	Feb 1
Chariton 	Sept 2
Photius		Aug 12
Spiridion
Manna
