---
id: 1878
title: To Ann Maria Carter Smith
iso-date: '1862-11-21'
display-date: Novr 21st 1862
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1862/5
---

My dear [Miss Smith](/person/263),
I think this story is one of the most complete you have yet done. Mr Franklyn’s self debates are excellent, and dear little Mary beautiful, the wicked part very touching By the by you should do something with the /Michaels\ mother. She must be mentioned somehow- on his return, or else have died. I think if she had, she would be a great riddance out of Victoria’s way, and besides how was she provided for, if the insurance was only just enough for Victoria’s provision. Are not you in rather a hurry with the poor things. Would you not tell how Mr Franklin found Michael again - it would be a moment to shew him softened - which he wants. Should it not be shewn that his great blunder was the not saying ‘If you are both in the same mind when Michael comes home we will consider of an engagement.’ I think that Charles’s letter of thanks to Victoria is not quite up to the mark - it looks too like woman’s hand. I fancy it would be better either to rewrite it or to avoid it altogether That is all my criticism, in all the rest you carried our hearts quite along. Then about what to do with it. It seems to me a pity not to publish it all in one by itself it wants to be read all together As to the [M P](/periodical/52) it could not have it simultaneously with the Websters, and it ought not to be kept long waiting. I have been thinking over other periodicals, and I do not think any quite good enough for it. If [Good Words](/periodical/73) were not so Scottish and Presbyterian it might do- but the part about the Christening would not go down there, besides they dont return MSS. I believe you would do best by it and yourself too, by letting [Parker](/person/1144) make a little red book of it, specially just now at Christmas. I think he might be quick about it and get it out. [Mr Bourne](/person/178) the partner is the person to write to now, and I will wait to return the M S till I hear from you whether I shall send it straight to him or back to you. I would say a good word for it to him if you liked, and remind him of Aggesden.
I have only been at home three weeks, and have been very busy, but I was meaning to write to you to say that I have been finishing off the Skell Islanders in the December Packet at one gulp, and having a Xmas story to put in besides, I was obliged to sacrifice the Websters for the month. I hope you will not mind.
As to the corrections if you think of marking them they could easily be done in the proofs of Die Kleine Mutterchen, I think it is quite worthwhile to make a book for Xmas I think you will have to add an English name for the stupid people there are in the world

yours sincerely

C M Yonge
Thank you for letting me read it
