---
id: 1881
title: To Ann Maria Carter Smith
iso-date: '1862-12-02'
display-date: Decr 2nd [1862]
from-name: Charlotte Mary Yonge
from-address: Otterbourne/ Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1862/ 7
---

My dear [Miss Smith](/person/263)
I am sorry my counsels only led to disappointment but I daresay it is wise in poor old [Mr Parker](/person/1144) to undertake as little as possible. I should think you were in good hands with [Bell & Daldy](/organisation/135). I know [Mrs Gatty](/person/549) thinks them very liberal. In one case I knew where a lady wanted to publish a story rather longer than yours, they offered to take it if she would guarantee £30 in case the book failed- she did not like to do this, so it went off, but I think that would be a good course with your story.
I think they are attentive and courteous to their clients, twice they have sent on people to me when they thought a thing better for the [M P](/periodical/52) than for themselves one was the Xmas story in this number the other Little Maggie which I did not like, but they printed
So Rose & are some shades less naughty, I cannot guess in what form her chastisement will come, I begin to hope you won’t kill Rosemary as I dreaded

yours sincerely

C M Yonge
