---
id: 1886
title: To Henrietta Elizabeth Fursdon
date: '1863-03-12'
display-date: March 12th 1863
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Henrietta Elizabeth Fursdon
manuscript-location: MS Mrs Katherine Wykes-Sneyd
---

My dear [Irene](/person/538)
Many thanks for your sister’s pretty little poem. I daresay it took great effect at your tea drinking.

How much more beautiful [Aytoun](/person/1875)’s is than [Tennyson](/person/1874)’s and what a glorious day that was![^1] I could see the bridal train rush by on the LSW, and hear the guns fired at Southampton. [Our squire](/person/282) gave beef and beer to each family at home, and there was a grand bonfire on the hill
Thank you so much about the answers to the Sunday questions
your affectionate
Mother Goose


[^1]: The [Prince of Wales](/person/1876) (later Edward VII) married Princess [Alexandra](/person/1877) of Denmark on 10 March 1863 at St George\'s Chapel, Windsor.

The Poet Laureate, Alfred Tennyson (1809-1892), had composed ‘A Welcome to Alexandra, March 7 1863’ beginning ‘Sea-king’s daughter from over the sea, Alexandra!’ and W.E.Aytoun (1813-1865) a ‘Nuptial Ode on the Marriage of his Royal Highness the Prince of Wales’ to celebrate the marriage.
