---
id: 1896
title: To Anne Yonge
date: '1863-07-27'
display-date: July 27th [1863]
from-name: Charlotte Mary Yonge
from-address: Newsells
to-name: To Anne Yonge
manuscript-location: 'MS WDRO Acc No 308: 27/7/63'
---

My dear [Anne](/person/1582),
A few lines I must write before we go – Your letter this morning told us much more than we had had before but it was so sad yesterday getting both together the letters written in the fluctuations.

We shall be only one day’s post away now, and that really induces [Mamma](/person/1606) to go on to St Dunstans.

Otherwise we should like to have staid [sic] in this kind quiet place.[^1] Those boys will be more than ever dear to you now.[^2] I think it is a thing to be very thankful for that they have been so much with you all that they can look to you and cling to you more than many can to their aunts.

Dear boys, I am glad we are in the way of seeing so much of the elder ones[^3]. I got to know them much better this summer, when they came to us in our own house. I do think her spirit pervades them all and will last with them. O how one looked up to her admired her bright freshness. I never knew any death that so rang in one’s ears ‘in the midst of life we are in death’ she was so full of life and vigour and so untiring that she was one’s marvel & delight and I believe a recollection of undimmed brightness is a precious thing – unmixed with long hours of pain and weary decay. I have been hearing much of a large family belonging to the Mackenzies whose [mother](/person/1882) was cut down in her bloom having brought them to much about the age of these dear boys- and oh! the way her presence and influence seem still to guide her [sailor](/person/450) and her [soldier](/person/453), and influence the choice of the one who is to be a clergyman is full of hope & encouragement for them.[^4] But the putting out of that brightest spot in uncle Yonge’s life- I don’t know why it is but I can’t help grieving for that most of all.

How often I think of the tablet to your brothers and its inscription.[^5] What a year it has been.

You know our direction.

St Dunstan’s Regents Park N W. I suppose it will be the little ones that [uncle Yonge](/person/1623) brings. - How sad that the deferred holidays made such a difference to their being with her.
I hope [John](/person/1619) is better. I do look to the [hope](/person/1365) at Newton being a rainbow, as an old lady who was here last week calls her grandchild who was born the day after her husband’s death.[^6] I cannot write more.
your most affectionate

C M Yonge


[^1]: Newsells Bury, near Barkway, Hertfordshire, was the home of [Caroline Vernon Harcourt](/person/1442) (d.1871), an old friend of FMY\'s and CMY\'s godmother.
[^2]: The \'boys\' were Anne\'s nephews, the six sons of her sister [Alethea](/person/27) who had just died.
[^3]: The elder boys were boarders at [Winchester College](/organisation/50).
[^4]: [Anne Mackenzie](/person/930)’s eldest sister Elizabeth (d. 1858) had married George Dundas (1802-1869), Senator of the College of Justice in Scotland, from 1868 styled Lord Manour.

Their children included Captain [James Dundas](/person/453) (1842–1879) V.C. and [Mary Frances Dundas](/person/455), who was a Gosling as Ladyfern from 1863 to 1868.
[^5]: The tablet in the church of Holy Cross, Newton Ferrars, near Puslinch, reads: To/ the Memory/of/ James Yonge/ Who died Nov 2nd 1834/ Aged 18 years/ Also of Edmund Charles Yonge,/ who died Jany 15 1847: aged 19 years/ sons of the Revd John Yonge,/ of Puslinch, (rector of this parish),/ and Alethea H.

His Wife/ They both died at Otterbourn/ in the County of Hants./ And are interred there.

Jesus said ‘What I do, thou knowest not now But thou shalt know hereafter.’ John 13. 7.
[^6]: Anne\'s brother Duke, Vicar of Newton Ferrars, and his wife Charlotte, were expecting their first child.
