---
id: 1913
title: To Alexander Macmillan
iso-date: '1863-11-05'
display-date: Novr 5th [1863]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: MS British Library Add MSS 54920
---

[Sir](/person/939),
I am sorry you had so much trouble about the [Trial](/book/53). I was only waiting to send it to you till I heard whether you thought it worth while to look at it so long before hand. I now send it by this post. There are six more chapters not yet in type of about the length of these, but I hope that the last of them will appear on the 1st of March or April, and I should imagine that the whole had better appear as soon as possible afterwards.

I have arranged that the [Clever Woman of the Family](/book/58)should first come out in the [Churchman’s Family magazine](/periodical/63), to be completed there by December 1864,[^2] but I retain the copy right, and shall hope to bring out the book together in December, having stipulated with [Messrs Hogg](/organisation/159)[^3] that the choice of a publisher for it shall then be in my hands.
I have not yet had an answer from [Messrs Longman](/organisation/153) with regard to my other works

Your obt servt
C.M. Yonge

A Macmillan Esq


[^2]: It appeared there from Jan 1864 to May 1865. Macmillan published it in 1865.
[^3]: Publishers of the Churchman’s Family Magazine from Jan. 1863 to April 1873.
