---
id: 1919
title: To Alexander Macmillan
iso-date: '1863-11-27'
display-date: Novr 27th 1863
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne Winchester
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 11-12'
---

Dear [Sir](/person/939),
My brother will call on you on Wednesday morning, the 2nd, unless he should hear from you to the contrary. His address is [J.B. Yonge](/person/1624) Esq
					9 Montague Place
					 Bryanston Square.
I have just heard that there are 50 copies of the [Lances of Lynwood](/book/23) ordered, and that there are none in stock.
I think a new edition should be put in hand at once, it is a childs book, with designs by [Mrs Blackburn](/person/159) engraved by [Dalziel](/organisation/163), I will send up a copy of the 1st edition by my brother. I have not one of the more recent, but I know it was smaller and less ornamental though with the illustrations - Perhaps you will judge how the new one should appear.
I shall send by him the account of “[the Young Stepmother](/book/38), which I think should be taken into consideration as a basis for arranging the terms for the [Trial](/book/53).
Yours faithfully
C.M. Yonge
