---
id: 1921
title: To Henrietta Elizabeth Fursdon
iso-date: '1863-12-05'
display-date: Decr 5th [1863]
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne, Winchester.
to-name: To Henrietta Elizabeth Fursdon
manuscript-location: MS Mrs Katherine Wykes-Sneyd
---

My dear [Henrietta](/person/538)
You have indeed had much sorrow during these two years, and you must be feeling it deeply, a kind aunt is such a treasure in ones life.[^1] It has been a strange year of death – the same post brought me tidings of the death of a little [godson](/person/170) of mine who had long been hovering between life and death from the remains of scarlet fever, - his little [sister](/person/169) two years younger previously died. She was about six years old, and was born after her [father](/person/168)’s death. I don’t know whether you knew them, the Bogues of Tenbury.
I wonder what piece you are transcribing of [Marco Visconti](/periodical/77), it is a very interesting but a very melancholy book.[^2] I hear of many promising things for this [Barnacle](/periodical/89).
I am not sure of the Fursdon post town so I must send this to Dawlish.
[signature cut out]


[^1]: The people referred to are the Reverend John Richard Bogue (1808-1857) and his children Edith Elizabeth Bogue (1857-1863) and Francis Reginald Bogue (1855-1863). They were cousins of CMY\'s through the Bargus family. The condolences are therefore probably on the death of Henrietta’s aunt [Elisabeth Fursdon](/person/537) (1805-1863).
[^2]: This was presumably in connection with the [Gosling Society](/topic/104).
