---
id: 1925
title: To Florence Wilford
date: '1864-01-12'
display-date: Jan 12th [1864]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Florence Wilford
manuscript-location: MS Society of Antiquaries 444/17/144
---

My dear [Florence](/person/1520),
Many thanks to you and your friend for your kindness about the pantomime. I am sorry however to say that I do not think it will quite do. I suppose it is the sort of thing to be done not so much by a regular narrative of the scenes as by some clever sketch such as perhaps takes an older hand. I hope it will not be a disappointment, but I think from your letter you have prepared her for it. I am glad you like some of the [Events of the Month](/periodical/69), I think it will improve by practice.

You have not told me the fate of Christina with the [Churchman](/periodical/62), I greatly think that serial is improving under the new [Master](/person/1328) - there is a very good story beginning.[^2] I am so glad your foot is better - I have some friends staying here and not much time so I must finish

yours sincerely
C Yonge


[^1]: Black-edged paper.
[^2]: Felicia Skene had recently taken over as editor of the Churchman\'s Companion. A story called \'Christina\' appears in Wilford\'s A Vantage Ground and Other Stories Reprinted from the Monthly Packet and the Churchman\'s Companion (London: Masters 1879).
