---
id: 19268
title: To Anna Rachel Bramston
iso-date: '1897-11-25'
display-date: 'Novr 25th [1897] '
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Anna Rachel Bramston
manuscript-location: Essex Record Office D/Dlu/95/1/1
---

My dear [Miss Bramston](/person/195),

It is very odd that I should just have been looking over the [Fairy Bower](/topic/240) and coming to the same conclusion about as to the absurdity of all the neighbourhood being agitated about the children.  But after all it is a device to shew the characters upon.

I think the worst sort of book is as you say, what makes naughtiness charming (it always is amusing) but Holiday House is quite harmless, because the children got punished.  Misunderstood is bad as making disobedience pathetic and a new book Gerald and Dolly is a very bad instance.  The children are let in to see the Xmas tree too soon.  Dolly wants [?] a doll for fear anyone else should get it, and gets burnt to death - not as a lesson against unfair selfishness but as a pretty pathetic incident to close the story.

But you are quite right as to the futility of diving into mysterious misdeeds.  I think it is a conclusion that experience teaches.  I have known a grown up brother and sister declare that they really never knew whether they had done the mischief they got bewildered by the confusion of the investigation.  And, on the other hand, I know two people who each dated their truthfulness from the sufferings of her conscience over a thing that never was found out.

I have got a sincerity paper giving that same advice, not to ask point blank Did you?  So I shall hardly be able to put both in at the same time. I must see which fits in best for April

yours sincerely

C M Yonge

&nbsp;

&nbsp;
