---
id: 1930
title: To Alexander Macmillan
iso-date: '1864-01-25'
display-date: Jany 25th 1864
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne Winchester
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 15-16'
---

Dear [Mr Macmillan](/person/939)
Herewith I send enough of the [Trial](/book/53) for the printer to proceed with at once. I have erased all the redundancies I could find, and I hope it may thus become less cumbrous - Unless there is some difficulty I suppose there is no need of sending me proofs. [Mr Parker](/person/1144) wrote to me himself to recommend [Phelps](/organisation/164) who printed the [History of Christian Names](/book/48) and as there were a good many letters from ancient alphabets there used, I suppose it would be best to put any future edition into his hands. For this book I have no choice
I shall be much pleased if [Mrs Macmillan](/person/941)[^2] is inclined to write me her views on the [Golden Deeds](/book/51), I am sure it is a subject on which discussion will be a great assistance.
Perhaps I could procure [Mrs Blackburn](/person/159)’s original designs for the [Little Duke](/book/20). Would you think it worth while for me to do so- ? Many of the faults in the illustrations as they appeared in the first edition were from the badness of the stone - One or two chiefly of animals were spirited and good but unfortunately the blot is the Little Duke’s face, and I am afraid this is past improvement but if you think these designs preferable to new ones, I could try if they are still to be had.
Yours faithfully
C.M. Yonge
