---
id: 1945
title: To Ann Maria Carter Smith
iso-date: '1864-03-28'
display-date: March 28th 1864
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1864/3
---

My dear [Miss Smith](/person/263),
I have been waiting to answer you till I had read far enough on in your storyx to be able to judge, and now being within a quire and a half of the end, I think I can do so.[^1] I think the history of the elder Juliet very original and excellent and I like that about young Josie very much likewise, she is a very winning buoyant creature, but indeed I think in the rest you must not put in such terrible harshness and hatred - you know it made [Wishop Rectory](/organisation/257) painful and this is the same kind of thing. The terms between Horace and his father are a great deal too dreadful to be written of - and indeed though I have known of boys like Horace here and there in real life, I never knew of a father so shockingly devoid of all natural affection to such a son. Then about Hannah’s affairs - I think you have exaggerated the distance between the baronet and the doctor’s family, even for that day. I can imagine the baronet disliking the connection, but not the doctor holding the barrier as so impassable. Nay - my great grandfather was a physician and surgeon in Queen Anne’s time - he married a county heiress - one son was brought up to be a physician at Plymouth. In the next generation there were 3 sons, of whom the two younger were being educated for physicians, when the death of their brother, the heir, made them change and become clergymen that they might finish their education together. The younger of the two, my [grandfather](/person/1600), married a baronet’s [daughter](/person/1905) about 1782 - and of their children three - (of whom [one](/person/1614) is still a Plymouth physician) married their first cousins the baronet’s children, and I am quite sure none of us would ever have felt as if we had any inequality of connection or were at such an awful space from baronet blood. I think if the proud humility be necessary on the Lakes’ part, you should have made Miles’s father a peer. But I think his cruelty to Hannah and her child just what is so like torturing a mouse that it would be much better not to read of it. It gives one an oppressed ground down sense, and there is nothing high or noble to compensate for the pain or carry one through. Indeed I do not think that anyone could like to read of it. I believe you would do much more prudently to confine the story to the two Anastasias. And if I were you, I would keep Kenneth’s history till he returns, for the bits of real journal break in uncomfortably on the narrative.
And now having said all this, I am afraid I must add that I have not standing enough with [Macmillan](/organisation/111) yet to give a helping hand. I have been thinking all through suppose you tried [Bentley](/organisation/168)at once but I am sure softening is needed before it is fit to put forth. I am afraid I am writing more candidly than sounds kind. I had a few minor things to say, such as that I don’t think gigs were invented then but I must stop now and I am afraid I have only said what is disappointing. Had I not better return it by rail? One thing I do think that the action is brisker and better sustained than usual

yours sincerely

C M Yonge


[^1]: Envelope addressed to Miss Smith/ and postmarked Winchester 28 March 1864 and London SE 29 March 1864.
