---
id: 1946
title: To Ann Maria Carter Smith
date: '1864-03-31'
display-date: March 31st 1864
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/
---

My dear [Miss Smith](/person/263)
I did not write yesterday as I had to go to Winchester, and besides my [sister in law](/person/1604) had not quite finished reading the M S.

The part about Horace’s marriage I do like, and the softening, but I am very sorry you adhere to the early part - especially his father’s repeated wishes for his death.

If you could only hear the horror of [my mother](/person/1606) and my sister in law at them! and besides I do not see what moral you teach by giving us anything so disagreeable, the boy is as bad a boy as can be, yet without ever repenting he becomes very respectable and prosperous. I know you are not writing for children, so this matters the less, but even if for grown up people, there is no moral for his father continues to hate him unjustly and I cannot but think it will set people against the story. I see that it is so even with the Websters where the same spirit is found in a minor degree, people turn strongly against the whole description of Mr Webster, and I think you will find it so with this.

As to Miles and Hannah, it is of course likely the parents’ would wish for a better match for their son, but the Lakes talk of their inequality in a way that is quite beneath them, being really as well educated and blood relations, and we can none of us get over Miles’s treatment of poor little Effie. I like the Seringapatam journals far too well to wish them shortened.

Could they not come with the release and news of Kenneth’s safety.

My first thought I own was of old Mrs Baird’s exclamation ‘Heaven help the puir lad that’s chained to our Davie’. I think if one did fear Susie turning into an old maid by his death, it would add to the interest.

The lesser matters we noticed were a puzzle about the bells in the early part, also that in 1767, Charlotte could not many years have been the Dr’s horse.[^2] Parlour maids are very recent matters - even the name I never heard till about 20 years ago. I am now 40, and when first I can recollect, I can only think of two households without a man servant, one a mother and daughter in a cottage, the other two old sisters very poor.

The Lakes would certainly have had a footman also the surgery boy in livery, and the coachman to wait, besides friends’ servants, so I do not think the maid would have appeared at all. I do not think luncheon was a regular meal, and high teas were never heard of.

Indeed I think a ‘nooncheon’ as even my grandmother used to call it was only a refection of bread and fruit or bread and cheese, when dinner was as late as 3 o’clock, and that the chief meal was at 2 or 3 in all but the grandest houses keeping London hours. I don’t think such a familiarity as Grannie would have been dreamt of. I never saw it in any old book, and with neither of my grandmothers should any of us have attempted it, indeed my [grandmother Yonge](/person/1905) was addressed as ‘ma’am’ by all her sons and daughters.

Did you ever read Sir Charles Grandison? I think it would help you to the tone of the people.

Oh! and pray don’t make the India muslin yellow and unfashionable, they would have been in the highest fashion just then, and washing never hurts them.

Did you see in Reade’s last book how he makes the girl who wears one look soft and floating whereas the tarletan [sic] ladies looked like little pigs in crackling [Josephine](/person/2415) and [Marie Antoinette](/person/2417) both wore them and cashmires.

As to the yellowness, my mother had two of the same pattern at her wedding, only one was made up, and when I came out, the two together made one which was quite a good colour, though such is the increase of garments that I suppose it would look now as if I had on a pillow slip. I had another which an [old nurse](/person/1702) of mine who married a drum major brought me home from India and that never discoloured, so I really do not think they do. I like the name of the two Anastasias, and it tells the story well.

You see the Tyrrels were a county family, but Anastasia was on an equality with them so I cannot see the great space between her and the Leighs.

Should not the chesnut tree have come in at the end, for Anastasia’s children? I was half in hopes of hearing that your sisters had protested against your cruelty in making us hear of such people as Horace and Miles. I am half inclined to tell you what I so often hear said of your stories ‘ O I don’t like her disagreeable fathers’, people are so hurt at the partiality and temper. I have mentioned this because I think a way of looking at character grows into a mannerism and that had always better be avoided.

Now Robert Lake would really have not been a ‘disagreeable father’ if he would only have been more touched and grieved, and less savage about Horace.
I have spoken strongly, but the more I think about it, the more I feel that something of alteration is wanted. I know it is possible to dilute a story down to milk and water by over criticism, and that the strong purpose of the author should have its way, but if this is your purpose you should think about it a long time first

yours sincerely

C M Yonge


[^1]: This letter is printed with a few omissions by Battiscombe, [Charlotte Mary Yonge](/organisation/17), 114-115.
[^2]: Battiscombe transcribes this as ‘have been in the Doctor’s house’
