---
id: 1949
title: To Louisa Twining
iso-date: '1864-04-26'
display-date: April 26th [1864]
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Louisa Twining
manuscript-location: 'MS Princeton University, Parrish Collection C0171: Box 29'
---

My dear [Miss Twining](/person/1427),
I am sending off your acknowledgements today, but I am much afraid they will not be in time for the next [packet](/periodical/52), if not they must appear in June, and I hope may by that time be added to as I am sure your paper must excite great interest[^2]

Yours sincerely

C M Yonge


[^2]: The paper referred to here was evidently the unsigned \'Help for Incurables MP (April 1864) 437-449, which can be attributed to Twining on the basis of this letter. A notice to correspondents appeared MP (June 1864) 668: ‘Miss L. Twining begs to acknowledge, with many thanks, the receipt of the following donations from readers of The Monthly Packet, to the [Home for Incurable and Infirm Women](/organisation/26), 23, New Ormond Street, W.C.’ followed by a list of names and amounts. These must be the “acknowledgements” that were too late for the May issue.
‘Hints on Reading’ (March 1864) 335) also includes a notice of ‘Stories of Crowbridge Union,’ edited by Miss Twining,. ‘The book would be useful, not for young readers, but in showing those who can gain access to a Union Workhouse, the sort of use they can be of to the inmates--a subject on which we hope to say more in our next number.’ The book was M.A.B., Tales of Crowbridge Workhouse. Blind Charlie. The Three Friends. Cousin Jane. By M. A. B. With a preface by Louisa Twining. (London: Masters 1863)
