---
id: 1956
title: To Messrs Macmillan
date: '1864-05-31'
display-date: May 31st 1864
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Messrs Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 26-27'
---

Miss Yonge would wish the following presentation copies of [the Trial](/book/53) to be sent - if they have not already been sent, - she is not certain whether [Messrs Macmillan](/organisation/111) had her list and should wish to guard against any being sent twice over - Copies to be sent to
[Miss Coleridge](/person/351)
Heaths Court
Care of [JD Coleridge](/person/343) Esq
6 Southwark Crescent
			also to -
[Sir William Heathcote](/person/669) Bart M P
91 Victoria Street
[Mrs Pode ](/person/1180)
3 Craven Place
Westbourne Terrace
Miss [Anne Yonge](/person/1582)
Puslinch
Yealmton
Devon
[Miss Dyson](/person/464)
Church Crookham
Farnham
Miss [Frances Patteson](/person/1151)
Weston
St Mary Church
Torquay
[Madame de Witt](/person/423)
Val Richer
Lisieux
Calvados
France
Also 12 copies to be sent to my/herself - by the South Western railway, addressed to
Miss Yonge
Elderfield
Otterbourne
Bishopstoke
Letters to be always directed to Winchester as post town, parcels by railway to Bishopstoke.
