---
id: 19634
title: Alexander Macmillan to Charlotte Mary Yonge
date: '1866-10-08'
display-date: Oct 8 1866
from-name: Charlotte Mary Yonge
to-name: Alexander Macmillan to Charlotte Mary Yonge
manuscript-location: Copy outletter book British Library Add MSS.55386 (1) P. 451
---

My dear Miss Yonge                                                              Oct 8 1866

I have a good many things to write to you about, but I am going to confine myself at present to one.

You remember our projected [Sunday Library](/topic/145) and the several difficulties we found among those writers quite adequate for various subjects, a free Church Minister in Glasgow has written a series of papers on Natural History subjects (he is an accomplished naturalist) connected with the Bible.

He has sent me one and I have agreed to publish.

There is a collected form under the title of Bible Readings in Nature or in the Knowledge of Nature.[^1] I have read through a good many of them aloud to my wife & children.

They strike me as realizing so completely the idea I had in seeking to make a Sunday Library that I cannot help sending them to you at once for your opinion of them. I won’t say another word about them, or any thing else at present.

But I shall be glad to hear what you think of them on the whole.

Yours very faithfully

A.

Macmillan

&nbsp;

&nbsp;


[^1]: This is probably a reference to the Rev.

Hugh Macmillan, Bible Teachings in Nature (1867).

In 1861 Macmillan had published another book by the same author (to whom he was related) entitled Footnotes from the Page of Nature.
