---
id: 19653
title: Alexander Macmillan to Charlotte Mary Yonge
iso-date: '1866-11-07'
display-date: Nov. 7 1866
from-name: Charlotte Mary Yonge
to-name: Alexander Macmillan to Charlotte Mary Yonge
manuscript-location: Copy outletter book British Library Add MSS.55386 (2) P. 572
---

Dear Miss Yonge,

Only a line to say that I have had the [illegible]  of [Miss Peard](/person/1160)s [illegible]. I have been thinking that it would hardly do to begin a Series such as we spoke of with. That it should come some way on. Even among church of England people the History of the Prayer Book is not the most attractive subject, though I do think it about the most useful.[^1] Still for a set of books meant for the young & em[illegible]  people. Beyond this and the tale (?) should be the opening. My [illegible]  work would be more on this line. I do want such books as I have no doubt Miss Peards will be, but [illegible]  [illegible]  [illegible]. I am sorry I have been so occupied that I have done little with the series as yet. I hope to buckle to it soon. In the mean time I will read Miss Peard’s MS most carefully and tell you how I feel about it.

Have you ever seen a little volume I published by Mr De Teisser called “The House of Prayer” but meant as a devotional companion to the Prayer Book and seems to me [illegible]  done. I send you a copy by this post. If you think well of it I shall be grateful for any little [illegible]   [illegible]  [illegible]. I don’t think he will be able to write for our Sunday Library. Paul (?) said it to be to our own sales.

I shall be glad to hear what [Miss Sewell](/person/1301) thinks of the specimen page.[^2] Have you fixed on the exact title? You don’t say whether you think one or three volumes would be best.

Yours very f’'lly

[A. Macmillan](/person/939)

&nbsp;

&nbsp;


[^1]: CMY had evidently proposed that the [Sunday Library](/topic/145) should include Frances Mary Peard\'s History of the Prayer Book, a series of papers originally contributed to the [Monthly Paper of Sunday Teaching](/periodical/81), and subsequently published in 1870 by the SPCK.
[^2]: Macmillan refers to CMY and Sewell\'s collaboration on [Historical Selections](/book/71).
