---
id: 1975
title: Alexander Macmillan to Charlotte Mary Yonge
date: '1864-09-13'
display-date: Sept. 13 1864
from-name: Charlotte Mary Yonge
to-name: Alexander Macmillan to Charlotte Mary Yonge
manuscript-location: 'Copy outletter book British Library Add MSS. 55383 (1): P. 327'
---

Dear Miss Yonge	
We shall be very glad indeed to see the [Deeds](/book/51) become words in print.[ I](/person/939) meant to have no [illustrations](/topic/167) except the vignette which I have had in my other Golden Treasury books.

This has been 'exercising' me a good deal of late. I cannot hit on either the sort of subject or the man to do it. I would be most grateful to you for a hint. I am inclined to send the first few sheets to Mr [Holman Hunt](/person/1912) & say 'Do what you can'.

He works slowly and with difficulty & is not always willing to undertake these things, but if he would it would be pleasant to have anything from him.

If he does not do it we might get [Millais](/person/1911) [illegible] things & rapidly enough always with great ability of course but I would not be so clear as to their - what shall I say .

Golden-ness is [illegible]
[The rest of this letter is illegible]
