---
id: 1991
title: To Ann Maria Carter Smith
iso-date: '1864-11-08'
display-date: Novr 8th 1864
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1864/ 7
---

My dear [Miss Smith](/person/263)
I so seldom see the paper that I did not know that this greatest sorrow that can befall one’s unmarried life had come upon you.[^2] It takes me back at once to ten years ago when I was tasting the same cup, and strangely enough there was the same connection between the sorrow and my first real [success](/book/15). How you must feel the change & the sorrow for others as well as yourself. I am glad there is not in your case the shock of an immediate break of home, but that you have time to detach yourself gradually. As to the grief itself, I think it is one that lives more than any other I have known and yet is more precious. And those testimonies from poor neighbours do so live with one like treasures through the rest of ones life.
The Anastasias must I am sure be a success from the tone of all the notices I have seen of them, and [Miss Taylor](/person/1397) is very much pleased with them, you know she is a great admirer of yours (except the Websters) but she has not guessed you here. She likes the 3d volume specially. I am just going to enjoy it
With many thanks

yours sincerely

C M Yonge


[^2]: The Rev. [Richard Carter Smith](/person/297) died on 1 October 1864. CMY\'s father [WCY](/person/1631) had died in 1853.
