---
id: 2003
title: To Christabel Rose Coleridge
date: '1865-01-01'
display-date: Jany 23d 1865
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel,](/person/329)
Here is the first Golden egg that a Gosling has yet laid, though I am afraid it is only a paper one!

Many thanks to you for the Eagle that contributed to it[^1].

You know that I have got a new [Gosling](/topic/104)- [Elizabeth Catharine Yonge](/person/1603), Eton - to the brood the Cobra di Capello- (because she wears spectacles)[^2] She is only 15, but will be a capital one in time.

She is staying here now, so your Sidney questions will be the first she will see. I hope to take her up to be introduced to [Kittiwake](/person/887)- Have you got the [Barnacle](/periodical/89) yet?

your affectionate

C M Yonge


[^1]: ‘The Eagle of one house is the Goose of Another\'.

She had evidently contributed to MP, and the \'golden egg\' enclosed with the letter was a cheque to Coleridge for £5 which was cashed on 17 February.

The story had appeared in December 1864 and was later reprinted in Coleridge\'s The Face of Carlyon and Other Stories (1875).
[^2]: The gosling, Elizabeth Catherine Yonge (1847/8-1905).

In fact she called herself Cricket.

Census returns suggest that she was born in 1847/8 so she may have been older than CMY thought.
