---
id: 2019
title: To Alexander Macmillan
iso-date: '1865-04-25'
display-date: April 25th 1865
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 75-76'
---

My dear [Mr Macmillan](/person/939),
Thanks, I should prefer having the [monthly sum](/topic/160) in cheques here, but the £200 to be paid to [Messrs Hoare](/organisation/169). I hope the proofs are coming though it is rather late if the [Dove](/book/62) is to come out this [month](/periodical/78). I am afraid there are some anachronisms in it, and I did not give it the looking over that I should have done if I had thought of not seeing it again.
Here are these two chapters of [Bethlehem](/topic/177), I would have sent Abraham, but I could not get him finished today. His chapter will be more descriptive.
I think I must do the preparation through the Israelites first before that of the heathen world, because in point of time Israelite history comes before Gentile history. I thought of trying to give a highly drawn out picture of each stage of Jewish prophecy - the next after Abraham to be the death bed of Jacob.

Yours sincerely

C M Yonge
