---
id: 2059
title: From the Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
iso-date: '1865-08-01'
display-date: '[August 1865]'
from-name: Charlotte Mary Yonge
to-name: From the Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. This fragment printed in Yonge, <i>[[cmybook:102]Life
  of John Coleridge Patteson]</i> II, 150-2.
---

It was a great delight to [me](/person/1155) to receive a letter from [Mr. Keble](/person/798), by the February mail from England. How kind of him to write to me; and his words are such a help and encouragement.
I dare say I shall see Merivale’s Lectures soon. Nothing can well be so wonderful, as a proof of God’s hand controlling and arranging all the course of history to those who need it, as a subject for adoration and praise, to those who need not such proof, than the vast preparation made for the coming of Christ and the spreading of the Gospel. To popularise this the right way, and bring it home to the thought of many who have not time nor inclination for much reading, must be a good work. I suppose that all good Church histories deal with that part of the subject; it is natural for the mere philosopher to do so.
And think how the early Alexandrian teachers used the religious yearnings of the East to draw men to the recognition of their wants, supplied and satisfied only in Christianity. Often it is the point d’appui that the Missionary must seek for. There is an element of faith in superstition; we must fasten on that, and not rudely destroy the superstition, lest with it we destroy the principle of faith in things and beings unseen. I often think, that to shake a man’s faith in his old belief, however wrong it may be, before one can substitute something true and right, is, to say the least, a dangerous experiment. But positive truth wins its way without controversy, while error has no positive existence, and there is a craving for truth deep down in the heathen heart.
Do you remember that grand passage of Hooker, where he says that he cannot stand to oppose all the sophisms of Romanism, only that he will place against it a structure of truth, before which, as Dagon before the Ark, error will be dashed in fragments?
In our work (and so I suppose in a Sunday school) one must think out each step, anticipate each probable result, before one states anything. It is of course full of the highest interest. Can’t you fancy a party of twenty or thirty dark naked fellows, when (having learnt to talk freely to them) I question them about their breakfast and cocoa-nut trees, their yams and taro and bananas, &c., ‘Who gave them to you? Can you make them grow? Why, you like me and thank me because I give you a few hatchets, and you have never thought of thanking Him all these long years.’
‘It is true, but we didn’t think.’
‘But will you think if I tell you about Him?'
‘He gave them rain from heaven and fruitful seasons.’
How it takes one back to the old thoughts, the true philosophy of religion. Sometimes I lie awake and think ‘if [Jowett](/person/1951) and others could see these things!’
And yet, if it is not presumptuous in me to say so, I do think that this work needs men who can think out principle and supply any thoughtful scholar or enquirer with some good reason for urging this or that change in the manners and observances of the people. Often as I think of it, I feel how greatly the Church needs schools for missionaries, to be prepared not only in Greek and Latin and manual work, but in the mode of regarding heathenism. It is not a moment’s work to habitually ask oneself, ‘Why feel indignant? How can he or she know better?’ It is not always easy to be patient and to remember the position which the heathen man occupies and the point of view from which he must needs regard everything brought before him.
Thank you for Maclear’s book.[^1] It is a clear statement of the leading facts that one wishes to know, a valuable addition to our library. You know, no doubt, a book which I like much, Neander’s ‘Light in Dark Places.’
I shall remember about [Miss Mackenzie](/person/930)’s memoir of that good [Mrs. Robertson](/person/1952). I wonder that men are not found to help [Mr. Robertson](/person/1953). Here, as you know, the climate (as in Central Africa) is our difficulty. I think sometimes I make too much of it, but really I don’t see how a man is to stand many months of it. But I can’t help thinking and hoping that if that difficulty did not exist I could see my way to saying, ‘Now, a missionary is wanted for these four or five or six islands, one for each, and a younger man as fellow-helper to that missionary,’ and they would be forthcoming.
Yet doubtless I don’t estimate fairly the difficulties and hardships as they appear to the man who has never left England, and is not used to knocking about. I should have felt the same years ago but for the thought of being with the [Primate](/person/1295), at least I suppose so.
Well, I have written a very dull letter, but the place from which it comes will give it some interest. I really think that not [Mota](/place/150) only, but the Banks Islands are in a hopeful state.
Next year (D.V.) [Mr. Palmer](/person/1884) will try the experiment of stopping here for eight or ten months. I almost dare to hope that a few years may make great changes. Yet it seems as if nothing were done in comparison with what remains to be done.[^3] B-- and Mary, I am thankful to say, come (all being well) to New Zealand to stay as long, as many years, as I think fit. I don’t begin with enlarging upon their faults. They must be quite sure of my love to them being undiminished before they will be open and speak freely. But they say, ‘We have been uneasy, and read your letter over and over again. We want to go, if you will let us.’


[^1]: CMY’s footnote: \'Missions of the Middle Ages\'.
[^3]: The rest of the letter from this point on was omitted from the revised edition of CMY\'s biography.
