---
id: 2067
title: To Frances Maria Wilbraham
iso-date: '1865-08-26'
display-date: Aug. 26 [1865]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Frances Maria Wilbraham
manuscript-location: MS Harry Ransom Humanities Research Center, University of Texas.
  C. R. Coleridge Collection
---

My dear [Fanny](/person/1513),
You and [Emily](/person/1514) have exactly the memory that may be called kind – Many thanks to you for the very pretty little snow tip butterflies, which are of a species highly to be commended. I hope shortly to wear them into Devonshire where I believe we are going next month - I think the present visitors at the Vicarage are decidedly wholesome, being the [brother](/person/799) and [sister](/person/797) but I dread the chance of [Queen Emma](/person/485), and I fear it must have been a great grief that [Mrs W B Heathcote](/person/1955) has romanized fancying [her husband](/person/667) would have done the same, but no doubt led away by [Lady Herbert](/person/1956).[^1] I don’t think she ever was a wise person though she was pulled up by her husband while he lived. [Dr.](/person/1015) & [Mrs. Moberly](/person/1019) drank tea with us last night, and read us a delightful description of the travellers moonlight view of the Steinbach. I think she would have quite recovered if the damp days did not throw her back constantly. What dreadful things do happen! Poor [Mr Hudson](/person/1958) was a neighbor of the [Peter Young](/person/1636)s’ and we met him there last year.[^2] I never saw any one so full of life and spirit, and to them he was like a brother. He leaves a [young wife](/person/1959) and two little children. Do you know of any idiot asylum to which parish relief is not a bar, we have a little boy here who cannot go to [Earlswood](/organisation/38) because he has had relief since his fathers death?
Love to Emily
Your most affectionate

C M Yonge


[^1]: CMY was worried about the health of both John and Charlotte Keble. Both Mrs Heathcote and Lady Herbert became Roman Catholics at about this time.
[^2]: The Reverend Charles Hudson, (1828-1865), vicar of Skillington, Lincolnshire, a well-known mountaineer who had died in July 1865 while climbing the Matterhorn. His wife was Emily Antoinette Mylne.
