---
id: 2080
title: To Alexander Macmillan
iso-date: '1865-11-01'
display-date: Nov 1st [1865]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 117-8'
---

Dear [Mr Macmillan](/person/939)
By no means did I mean the graceful little lamp on [Golden Deeds](/book/51) - nor the Dove in the Sunday Book - nor the well in Cawnpore. I meant such a high priest and book as are outside Smith’s Biblical dictionary; or some of the whole pictures of men and women one often sees upon books, - spoiling the whole effect of the real [illustration](/topic/167) within. It was odd that I asked my [mother](/person/1606) if she thought what I said could be supposed to apply to Golden Deeds and she said - no by no means.[^1]
The Montfort arms are a lion. I will get the description soon but it need not be a formal shield like the arms on a peerage, but a sort of trophy, perhaps a helmet, shield and broken sword /& spear\, which would answer to the memory of old Montfort that pervades the [whole](/book/61). If the design formed a vignette on the title page it might have the motto -
But he the chieftain of them all
His sword hangs rusting on the wall
Beside his broken spear.[^2]
I send the bit of preface, and shall be glad to have the proofs - the long concluding chapter wants to be divided and furnished with mottoes. The to be continued was a mistake that I ought to have corrected.

Yours sincerely

C M Yonge


[^1]: They were discussing plans for illustrating The Prince and the Page.
[^2]: Walter Scott, [The Lay of the Last Minstrel](/organisation/141) I, 7.
