---
id: 2106
title: To Elizabeth Missing Sewell
iso-date: '1866-03-15'
display-date: March 15th [1866]
from-name: Charlotte Mary Yonge
to-name: To Elizabeth Missing Sewell
manuscript-location: 'MS Princeton University, Parrish Collection, CO171: Box 29'
---

My dear [Miss Sewell](/person/1301),
I ought to have answered you long ago that I am very glad that you are as Hampshire people say 'tackling' that [beginning](/book/71) of mine
I suppose Carter’s history was the other authority for Hereward that I proposed, I have however a great mind for Thierry, as the place where I fell in love with him first.[^1] Perhaps I had better send you the book, or shall I translate it, I think I could do so quickly, if I left it to take my own time, translating is just what suits me as company or travelling work. I am afraid I cannot do much for your friend in the way of autographs as my [sister in law](/person/1604) seizes all my first choice of them - but here is one of [Sir John Coleridge](/person/344) - When I get another of [Miss Ingelow](/person/741) you shall have it, but the two I have I want one for Frances the other for myself. I am not sure if [Miss Roberts](/person/1244) is considered famous enough

Yours sincerely

C M Yonge
After all the Judge’s letter has hidden itself. When it comes up you shall have the autograph.


[^1]: They were working together on Historical Selections, an anthology of passages from different historians arranged chronologically by subject, beginning with the Norman Conquest.
