---
id: 2115
title: To Jemima Charlotte Mozley
date: '1866-04-05'
display-date: April 5. 1866.
from-name: Charlotte Mary Yonge
to-name: To Jemima Charlotte Mozley
manuscript-location: MS copy in the Newman archives, The Oratory, Edgbaston, Birmingham
---

My dear [Mrs Mozley](/person/1064),
I answer your kind letter at once, without waiting till after to-morrow because I have promised to write to many then.

We did feel stunned indeed all the Good Friday though we had known the day before that there was nothing else to look for, and we were (and are) most thankful that [he](/person/798) is spared the solitude that [she](/person/795) so much dreaded for him, that she had always wished that she might be the survivor.

In very truth the death blow to both was that paralytic seizure on St Andrew’s Day in 1864, for though she did not break down till he was fairly well - not indeed till the middle of the winter, I think there can be no doubt that what she had then gone through quickened the life long evil in heart and spine which produced the terrible spasmodic asthma that haunted her at intervals.

Still she came home from Penzance bright and only looking more fragile, and exulting in his being so well, and she did much as usual till the middle of the summer, August I think - when she failed much.

Then came good [Queen Emma](/person/485) - who good lady gave as little trouble as possible - quartered her attendants in the village, and did not even bring a maid - but she could not help bringing an amount of excitement that did harm, though both enjoyed it thoroughly.

It was the last time I saw either of them - he was then very well and she weak but bright and full of eagerness.

It is curious to have had my last sight of him with the Queen of the South come to hear his wisdom.

We always thought that last year together most peculiarly happy - a fresh sort of honey-moon - he had made a duty of casting aside his cares, and they waited on each others health and took drives together with the greatest enjoyment.

And I believe your [Brother](/person/1085)’s visit to Hursley was a great peace to him. I think it must have been very like the St Marks Hymn in the [C.Y.](/periodical/95)[^2] That however was not till after she had made another great I cannot call it downwards step - but in September (after we were in Devon) she had a dreadful attack of spasms, which caught her on the stairs, and there she sat for two hours - able to be lifted neither up nor down.

It was plain that Hursley air was killing to her, and they went at once to Bournemouth.

She could not bear to take him out of reach to Penzance.

Things went on much the same till Xmas when she grew so much worse that their [brother](/person/801) and [sister](/person/797) came, and have never left them.

About once a fortnight came some terrible access, spasms, fainting, dropsical symptoms or lastly sickness, and for three or four days her death was hourly expected - then came a rally - and cheerful enjoyment of sky and sea seen from her bed - music - reading aloud.

That book of Mrs Robertson’s Memoirs which [Miss Mackenzie ](/person/930)sent them in proofs was one of their greatest pleasures.

He all the time kept well.

Friends at Bournemouth say his step tottered more and more, but his handwriting had quite recovered itself, and he took interest in all as usual.

Almost his last letter to [Sir J.

Coleridge](/person/344) said he wondered at himself for being able to eat drink and sleep, but so it was - he was well.

He wrote several notes and walked on the beach on the 21st but there must have been some bewilderment next morning, for he got up at 6 taking it for 7, and used a cold bath instead of a hot one.

In the course of the morning he fainted, his strength failed fast, erysipelas came on and wandering and though before the next Wednesday the erysipelas was passing off, his state was hopeless, and [Dr Burslem ](/person/230)ascribed it entirely to the long strain of grief, and the resignation perfect in itself, but crushing the broken frame.

All the last night they were each asking if the other was gone, and when he was, her first thought was thanksgiving.

She is now at the end of the week much in the same state, and is able to give all directions for the funeral - with all her consideration for every one - the power of vitality is strong, though on Sunday all thought she would be taken with him to the brick grave that is all ready for her.
yours very sincerely
C. M.

Yonge


[^1]: Jemima Mozley was John Henry Newman’s sister; evidently she lent him CMY’s letter about the death of John Keble from which this copy was made.
[^2]: Newman had visited Hursley and met both Keble and Pusey after many years on 13 September 1865.

Keble’s poem for St.

Mark’s Day in The Christian Year begins:
Oh! who shall dare in this frail scene
On holiest happiest thoughts to to lean,
On Friendship, Kindred, or on Love?

Since not Apostles’ hands can clasp
Each other in so firm a grasp,
But they shall change and variance prove.

Yet deem not, on such parting sad
Shall dawn no welcome dear and glad:
Divided in their earthly race,
Together at the glorious goal,
Each leading many a rescu’d soul,
The faithful champions shall embrace.
