---
id: 2147
title: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
date: '1867-01-29'
display-date: January 29, 1867.
from-name: Charlotte Mary Yonge
to-name: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. Printed in Yonge, <i>[[cmybook:102]Life
  of John Coleridge Patteson]</i>, II, 227-30.
---

My dear Cousin,
[I ](/person/1155)enclose a note to [Miss Mackenzie](/person/930), thanking her for her book about [Mrs.

Robertson](/person/1952).

It does one good to read about such a couple. I almost feel as if I should like to write a line to the good [man](/person/1953).

There was the real genuine love for the people, the secret of course of all missionary success, the consideration for them, the power of sympathy, of seeing with the eyes of others, and putting oneself into their position.

Many a time have I thought: ‘Yes, that’s all right, that’s the true spirit, that’s the real thing.’
Oh! that men could be trained to act in that way.

It seems as if mere common sense would enable societies and men to see that it must be so.

And yet how sadly we mismanage men, and misuse opportunities.

Men should be made to understand that they cannot receive training for this special Mission work except on the spot; at the institution the aim should be to give them a thorough grounding in Greek and Latin, the elements of Divinity, leaving out all talk about experiences, and all that can minister to spiritual pride, and delude men into the idea that the desire (as they suppose) to be missionaries implies that they are one whit better than the baker and shoemaker next door.

The German system is very different.

The Moravians don’t handle their young candidates after this fashion.

Now Mr.

Robertson and his good wife refresh one by the reality and simplicity of their life, the simple-mindedness, the absence of all cant and formalism. I mean the formal observance of a certain set of views about the Sabbath, about going to parties, about reading books, &c., the formal utterance of an accepted phraseology.
‘Would that there were hundreds such!

Would that his and her example might stir the hearts of many young people, women as well as men!

Well, I like all that helps me to know him and her in the book, and am much obliged to Miss Mackenzie for it.

We have had a trying month, unusually damp close weather, and influenza has been prevalent.

Many boys had it, one little fellow died.

He was very delirious at last, and as he lay day and night on my bed we had often to hold him.

But one night he was calm and sensible, and with [Henry Tagalana](/person/1975)’s help I obtained from him such a simple answer or two to our questions that I felt justified in baptizing him.

He was about ten years old, I suppose one of our youngest.

Last Saturday, at 12.45 A.M., he passed away into what light, and peace, and knowledge, and calm rest in his Saviour’s bosom! we humbly trust.

God be praised for all His mercies!

It was touching, indeed, to hear Henry speaking to his little friend.

He spoke so as to make me feel very hopeful about his work as a teacher being blessed, his whole heart on his lips and in his voice and manner and expression of face.

But, my dear Cousin, often I think that I need more than ever your prayers that I may have the blessing for which we pray in our Collect for the First Sunday after Epiphany: grace to use the present opportunities aright.

My time may be short; we are very few in number: now the young English and Melanesian teachers ought to be completely trained, that so, by God’s blessing, the work may not come to nought. [Codrington’](/person/312)s coming ought to be a great gain in this way. A right-minded man of age and experience may well be regarded as invaluable indeed. I so often feel that I am distracted by multitudinous occupations, and can’t think and act out my method of dealing with the elder ones, so as to use them aright.

So many things distract--social, domestic, industrial matters and general superintendence, and my time is of course always given to anyone who wants it.

The change to Norfolk Island, too, brings many anxious thoughts and cares, and the state of the people there will be an additional cause of anxiety. I think that we shall move en masse in April or May, making two or three trips in the schooner. [Palmer](/person/1884) has sixteen now with him there. I shall perhaps leave ten more for the winter school and then go on to the islands, and return (D.V.) in October, not to New Zealand, but to Norfolk Island; though, as it is the year of the meeting of the General Synod, i.e., February 1868, I shall have to be in New Zealand during that summer.

You shall have full information of all my and our movements, as soon as I know myself precisely the plan.

And now good-bye, my dear Cousin; and may God ever bless and keep you. I think much of you, and of how you must miss dear [Mr.

Keble](/person/798).

Your affectionate Cousin,
J. C. P.
