---
id: 2154
title: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
date: '1867-03-23'
display-date: March 23, 1867.
from-name: Charlotte Mary Yonge
from-address: '[[other:139]Kohimarama]'
to-name: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. Printed in Yonge, <i>cmybook:102]Life of
  John Coleridge Patteson]</i>, II, 240-46.
---

My dear Cousin,
Our last New Zealand season, for it may be our last, draws near its close.

On Monday, only two days hence, the ‘Southern Cross’ sails (weather permitting) with our first instalment. [Mr.

Palmer](/person/1884) has got his house up, and they must stow themselves away in it, three whites and forty-five blacks, the best way they can.

The vessel takes besides 14,000 feet of timber, 6,000 shingles for roofing, and boxes of books, &c., &c., without end.
[I](/person/1155) hope she may be here again to take me and the remaining goods, live and inanimate, in about eighteen or twenty days. I can’t tell whether I am more likely to spend my Easter in New Zealand or Norfolk Island.
I see that in many ways the place is good for us.

The first expense is heavy. I have spent about 1,000 l. already, sinking some of my private money in the fencing, building, &c., but very soon the cost of all the commissariat, exclusive of the stores for the voyage, and a little English food for the whites, will be provided.

Palmer has abundance of sweet potatoes which have been planted in ground prepared by our lads since last October.

The yam crop is coming on well: fish are always abundant.
I think that in twelve months’ time we ought to provide ourselves with almost everything in the island.

The ship and the clergymen’s stipends and certain extras will always need subscriptions, but we ought at once to feed ourselves, and soon to export wool, potatoes, corn (maize I mean), &c.
I never forget about the idea of a chapel.

At present the Norfolk Island Chapel will be only a wing of my house: which will consist of two rooms for myself, a spare room for a sick lad or two, and a large dormitory which, if need be, can be turned into a hospital, and the other end a wing in the chapel, 42 x 18 feet, quite large enough for eighty or more people.

The entrance from without, and again a private door from my sitting room.

All is very simple in the plan.

It seem [sic] almost selfish having it thus as a part of my dwelling house; but it will be such a comfort, so convenient for Confirmation and Baptism and Holy Communion classes, and so nice for me.

Some ladies in Melbourne give a velvet altar cloth, Lady S. in Sydney gives all the white linen: our Communion plate, you know, is very handsome.

Some day [Joan](/person/1154) must send me a solid block of Devonshire serpentine for my Font, such a one as there is at Alfington, or [Butterfield](/person/247) might now devise even a better.

But I think, though I have not thought enough yet, that in the diocese of Norfolk Island, and in the islands, the running stream of living water and the Catechumens ‘going down’ into it is the right mode of administering the holy sacrament.

The Lectern and the small Prayer-desk are of sandal-wood from Erromango.

It will be far more like a Church than anything the Pitcairners have ever seen.

Perhaps next Christmas--but much may take place before then--I may ordain Palmer Priest, [Atkin](/person/1979) and [Brooke](/person/1981) Deacons, and there may be a goodly attendance of Melanesia!! communicants and candidates for baptism.

If so, what a day of hope to look forward to!

And then I think I see the day of dear [George Sarawia](/person/1980)’s Ordination drawing nigh, if God grant him health and perseverance.

He is, indeed, and so are others, younger than he, all that I could desire.

So, my dear Cousin, see what blessings I have, how small our trials are.

They may yet come, but it is now just twelve years, exactly twelve years on Monday, since I saw my [Father](/person/1156)’s and Sisters’ faces, and how little have those years been marked with sorrows.

My lot is cast in a good land indeed. I read and hear of others, such as that noble [Central African band](/organisation/42), and I wonder how men can go through it all.

It comes to me as from a distance, not as to one who has experienced such things.

We know nothing of war, or famine, or deadly fever; and we seem now to have a settled plan of work, one of the greatest comforts of all; but while I write thus brightly I don’t forget that a little thing (humanly speaking) may cause great reverses, delays, and failures.
I am very glad you understand my unwillingness to write, and still more to print over much about our proceedings. I do speak pretty freely in New Zealand and Australia, from whence I profess and mean to draw our supplies.

Accurate information is all very well, but to convey an idea of our life and work is quite beyond my powers.

Still, everything that helps the ordinary men and women of England to look out into the world a bit, and see that the Gospel is a power of God, is good.

And now, good-bye, my dear Cousin.

May God bless and keep you.

Your affectionate Cousin,
J. C. PATTESON.
