---
id: 2161
title: To Edith Sophia Jacob
iso-date: '1867-03-01'
display-date: <span class=‘strike’>March</span> April 1st [1867]
from-name: Charlotte Mary Yonge
to-name: To Edith Sophia Jacob
manuscript-location: MS Charlotte Mitchell
---

My dear [Miss Jacob](/person/749)
Excuse the blunder of the date there is one of those revolutions going on caused by whitewash and new carpetting which drive oneself to holes and corners and one’s senses no where. It began suddenly on Saturday, or I would then have sent you Gerontius, thinking he might be a pleasant companion in your Oxford week. I hope it is successful, though [Mr Wither](/person/1544) says the [Dean of Emly](/person/1840)[^1] failed you.
How I wish we were near enough to read [Dante](/periodical/246) together - not that I really understand him but I should like to have to go through him again. When you do read him, after the first two or three cantos, when he is fairly over the Styx, I think you should go on at once to Purgatorio. I think one rather wastes time & patience in working through the political people in all the circles below - and the classical fiends are provoking, while everything in Purgatorio seems in a hopeful dewy sadness.
I suppose in reality, nobody does know the meaning of ‘He was heard in that He feared’.[^2] The Divine and Human Wills were certainly at issue at that dreadful moment there seems no doubt, but the very words offered up Himself almost signify the readiness to be a sacrifice. But in the main, I think it may be safe to call that prayer unanswered in the same sense as so many of our own prayers are - ie - that though the cup - the event itself - may not pass from us yet that the very thing in it, that one has most feared, may have been averted or softened in some wonderful manner. I am not looking at any authorities as this domestic revolution makes books hard to come by
yours very sincerely

C M Yonge


[^1]: The Rev. William Alexander (1824-1911) was known as the Dean of Emly 1864 until his appointment as Bishop of Derry in 1867; he was husband of the hymnwriter Cecil Alexander, and was a candidate for the professorship of poetry at Oxford in 1867.
[^2]: Hebrews 5: 7-8: ‘Who in the days of his flesh, when he had offered up prayers and supplications with strong crying and tears unto him that was able to save him from death, and was heard in that he feared; Though he were a Son, yet learned he obedience by the things that he suffered;’
