---
id: 2163
title: To Edith Sophia Jacob
date: '1867-04-10'
display-date: April 10th [1867]
from-name: Charlotte Mary Yonge
to-name: To Edith Sophia Jacob
manuscript-location: MS Charlotte Mitchell
---

My dear [Miss Jacob](/person/749),
I have the Récit d’une Soeur, and if you like to read it, I could leave it, either at your house in the Close, at [Jacob & Johnsons](/organisation/187) or any other convenient house of call at Winchester.

It is a beautiful book - the family are so good and charming, though not equal in intellect or poetry to the Guérins.[^1] The great matter in reading it is not to judge it by the first half of the first volume. I like the second much the best. I was sure you would come under the spell of Gerontius.

What a wonderful [mind](/person/1084) it is that thought it out. I see it said that it was a real dream of [Cardinal Wiseman](/person/1542), but I believe much more that the [erasure] old man ‘Gerontius’ was himself.

That adjective correction is thoroughly a man’s.[^2] Any day before the 20th, will be quite in time for me to have the Dream.[^3]
yours very sincerely

C M Yonge


[^1]: CMY had reviewed Pauline Craven, Récit d’une soeur: Souvenirs de famille (1866) in ‘[The La Ferronnays Family](/book/64)’, Christian Remembrancer; she had also written an [article](/book/50) there on [Eugénie](/person/1984) and [Maurice de Guérin](/person/1985) in 1864.
[^2]: The sense is perhaps that the erasure is untidy; the erased word looks like ‘old’: ‘Gerontius’ means ‘old man’.
[^3]: This refers to the forthcoming publication of Jacob\'s \'The Gate of Paradise\' in the [MP](/periodical/52).
