---
id: 2165
title: Mary Anne Frances Martin to Alexander Macmillan
date: '1867-04-21'
display-date: April 21st 1867
from-name: Charlotte Mary Yonge
from-address: Mrs Shephard Waterhead Windermere
to-name: Mary Anne Frances Martin to Alexander Macmillan
manuscript-location: MS British Library Add MSS.54974/10-15
---

Dear [Mr Macmillan](/person/939)
[I](/person/971) have been more fortunate than I had expected & have much pleasure in sending you a carte of Harriet Martineau which, as you know, I had not expected to obtain. I have not seen her, nor have I sent my letter of introduction, but her niece - to whom one of our friends had written - called yesterday while we were at Furness Abbey & we propose going to the Knoll tomorrow.

Meanwhile my mind has been greatly 'exercised' with regard to the groups allotted to Miss Yonge in the [Sunday Library](/topic/145).
I do not wonder at her choosing St Louis. [Writes 4 pages giving her views of St Louis and his times.] In fact it was a time of great & manifold activity - political religious & intellectual.

It was the century which was to produce & prepare for Dante and I think that we not only might but ought to get it done in a very different manner to that which it would be possible for Miss Yonge to work at it.

It seems to me that to her & all writers of her class should be given those biographies which do not involve deep study or extensive historical reading & research - the lives of men who while they influenced largely the society in which they lived yet have have[sic] not been so bound up with the political life of an age as to make it impossible to separate them from great historical events.

The early martyrs & fathers - the missionaries both of the middle ages & of modern times are admirably adapted for such writers.

They are all men who cut themselves off from the world - stood apart from it and who may be studied in & by themselves & who require that sympathy with the individual or the concrete which distinguishes the novelists and gives them their peculiar power.

Don’t you think it would be better to let Miss Yonge browse at will over this pasture - it is ample & fertile - and to keep our Miltons and Dantes and St Louiss [sic]?

By the by I saw Mr.

John Seeley before leaving town.

If he does not leave England in the long vacation he will write a life of Milton - putting in the Areopagitica and Tract on Education - two of the most valuable of the prose works - & both short.

It will make a grand volume.

If he travels on the continent as he may do, we must wait longer, but he will do it.

He suggests that [Dean Stanley](/person/1987) might write the life of Philip Henry, which he has lately been reading with great interest.

It would make a capital companion volume to the Milton and I suppose would take wonderfully.

We might expect an almost exhaustive treatment of the period from Dean Stanley & Mr Seeley and the Dean among the Nonconformists would be very attractive.

Mr Seeley also told me that [Mr Church](/person/297) - of whom you have spoken - has for some years past been a great student of Dante and his times - and he would of course be the very person to undertake St Louis.

Please let me know what you think of these suggestions.

We are very pleasantly located here - the lake washes the garden wall and we are not having more rain than is reasonable to expect in this place & at this time of year.

We went to Church on Good Friday & were informed that we could not believe in one God unless we believed in three - which seems to me such an outrageous manner of stating the doctrine of the Trinity that I prefer today to stay at home & hence this long letter which I fear you will find tedious[.] Dr Storrar has lent me the 'Reform Essays' in which I am much interested and so with 'Felix Holt' and a volume of Comte I am trying to keep my mind open in spite of all the ecclesiastical literature with which I am overwhelmed.

Please give my kind regards to Mrs.

Macmillan
and believe me
very truly yours
Frances Martin
