---
id: 2176
title: To Edith Sophia Jacob
iso-date: '1867-06-12'
display-date: June 12th [1867]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Edith Sophia Jacob
manuscript-location: MS Charlotte Mitchell
---

My dear [Edith](/person/749),
You will think there is no end to me but I saw [Mr Moore](/person/1046) yesterday and he says that his magic lantern came from Carpenter & Newman 24 Regent Street, and that they are much better than Negretti having devoted their minds to magic lanterns His lamp is an Argand These were all your questions I could recollect, but if you have any more, he will gladly and clearheadedly answer them. [Mamma](/person/1606) has just seen the new nursery maid trotting after the donkey carriage and ‘Mithter Dandatti’ and the three children & thought she looked very nice.[^2] On Saturday week [Miss Mackenzie](/person/930) will betake herself to the Kings Head at Hursley. The American lady who wrote the Scilly isles wants to do a series of English cathedrals - it is like the Scotch lady flying at Archbishops.
Poor dear Field House we took leave of it and its roses and cows last night, and felt as if a very sunny page in our life was turned down[^3]

yours affectionately

C M Yonge


[^2]: This suggests that Edith Jacob had recommended a nursery maid to JBY’s family, and CMY is giving news of her progress.
[^3]: The farmhouse at Hursley which [Dr. George Moberly](/person/1015) had rented from Sir William Heathcote, which his family were now leaving for ever.
