---
id: 2191
title: Alexander Macmillan to Charlotte Mary Yonge
iso-date: '1867-07-17'
display-date: July 17. 1867
from-name: Charlotte Mary Yonge
to-name: Alexander Macmillan to Charlotte Mary Yonge
manuscript-location: 'Copy outletter book British Library Add MSS.55387 (1): P. 360'
---

My dear Miss Yonge	.
[I](/person/939) have forwarded your letter to [Miss Martin](/person/971) who has gone to Bude. I am sure there will be no difficulty in arranging matters. Her only object as I understood her was as the [Series](/topic/145) is to go over a long space there would be serious danger of one book repeating the work of another, and so there would [be] too much of one part given, and details of another that would be newer & more interesting from novelty would be too little dwelt on.[^1] The part about the Last Supper and the Resurrection for instance, might be given by at least six or seven writers, so the Riot at Ephesus. Indeed more or less central points must be alluded to by a good many, and in the genesis of the events you could not well avoid the latter in some detail and the former must be recognized in the historical reality. But I am sure you will see that our scheme from its very extent involves considerable care that each division should be rather carefully defined. I hope you will not find much difficulty in making some abridgement in this early end[?], and expansion in the later part, so as to accomplish this object. I do not think that the mitre in any degree weighed on Miss Martin’s mind. I [sic] certainly did not on mine. I daresay it is a defect on my part, but I have never been able to feel interested in questions of dress and the like either one way or the other. I would [illegible] wish the phraseology which expressed this side of matters excluded from our book.
I enclose send by this post some short pages which I have had set up as pages in order to make a dummy book to take with me to America, I will hope to have [Mr Armitage](/person/60)s [drawing](/topic/167) in about a week & then can make up my partially imaginary volume. I am making 'careful studies' - as the artists say - of title pages & covers, and such humble departments. It seems I do care for dress after all - in my own line.
Please tell me whether you like the white or toned paper best. I find a reaction in favour of white springing up.
It seems to me that possibly you may have been wasting time otherwise valuable to you on these early chapters, I remember your [benevolent aims](/place/188). Shall I add £20 to the cheque to make up lee way a little. We want as much of Polycarp [and] Ignatius as you can give us. You see by this sheet that we have reached 80 pages out 1[or 4]00 & not got to them. Pray understand that that was Miss Martin’s meaning. She will write to you from Bude.
Believe me, dear Miss Yonge
Yours very truly
A. Macmillan


[^1]: This letter is concerned with the appearance of CMY\'s in Macmillan\'s Sunday Library series edited by Frances Martin.
