---
id: 2192
title: Mary Anne Frances Martin to Alexander Macmillan
date: '1867-07-18'
display-date: July 18th 1867
from-name: Charlotte Mary Yonge
from-address: Canal Cottage, Bude, Cornwall
to-name: Mary Anne Frances Martin to Alexander Macmillan
manuscript-location: MS British Library Add MSS. 54974/24
---

Dear [Mr Macmillan](/person/939)
[I ](/person/971)enclose my letter to Miss Yonge and will you send it on if you think well, but if not will you tell me what had better be done.
I have read her [proofs](/book/72) again & the fact is that she is writing a Sunday Story Book (of which there are thousands) and she will not have the story broken up.

It is very prettily told and no doubt will be very taking.

Miss Yonge believes everything that she wishes to believe and gives you no hint that there are grounds for doubting it. I suppose by the time we get to Ignatius we shall receive his celebrated ‘Be ye subject to the bishop as to Jesus Christ’ and ‘Follow your bishop as Jesus Christ the Father: reverence the deacons’ as the ordinance of God, as undoubted Apostolic utterances.[^1]
Please don’t think I am in a bad temper - because I am not - but it has always seemed to me unfair to children or anyone else to make them out a coherent story of materials which one knows untrustworthy or doubtful.

The information which Papias gives about the four Marys is interesting, but as you see Donaldson says there is 'unfortunately' no testimony as to its genuineness - and it is from him that we get the testimony as to the relationship of John to Christ.[^2]
I have not written at all to Miss Yonge on these points because she would naturally be annoyed at my criticisms. I think it will be much better to get her to abridge as much as possible the earlier & more dangerous part & then to tell her own story.
I do hope it will all go on smoothly, and it really does not trouble me a bit if you think I can manage discreetly and not do or say anything that shall give needless pain or annoyance.
. . . . . . . . .
very truly yours
Frances Martin


[^1]: On his way to his martyrdom in Rome (he was eaten by lions in the Colosseum), Ignatius (died c.67AD), one of the pupils of St John and later Bishop of Antioch, wrote a series of Epistles to his congregation in which these words appear.

Frances Martin, the editor of Macmillan\'s [Sunday Library](/topic/145), with her Broad Church views and interest in recent biblical criticism, was unsympathetic to CMY’s High Church preoccupation with such questions as the apostolic succession.

Objections of this kind had been foreseen by CMY in her letter to Macmillan of 28 June, and she had been reassured by him in his letter of June 29.
[^2]: Papias of Hierapolis was a writer whose fragmentary surviving works record traditions of the early church.
