---
id: 2193
title: To Alexander Macmillan
iso-date: '1867-07-18'
display-date: July 18th 1867
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54920: 186-187'
---

My dear [Mr Macmillan](/person/939)
The sheets came on Tuesday with [Miss Martin](/person/971)’s marks, and I have gone over them and marked with ink all that it seems to me that I could well part with.[^1] Her marks are in pencil and I see what she wishes to part with is the entire [chapters](/book/72) that belong to the Gospels and Acts, which take away all the youth of St John. Now if I might be allowed to keep enough to belong to his personal history, and make a whole man of him, I think I could manage, but I do want him and Ephesus as complete as I can make them; and the touching contrast of his long life and his brother’s early death is lost if I may not have the request that they might together share the Glory. Might not what I have left be again to see how it looks and whether it hangs together properly.
Thank you for your kind and liberal offer but I could not receive payment for what was of no use, and did not suit your purpose. I think I must have taken out about a quarter of what was standing, of course more might have gone only it seems a pity to make a thing bare and bald or to lose the picture of a character.
I always did like white better than tinted paper, and I think people find it easier to read.
As I said, I am working away at the Seven Churches and their Messages. The explanation of Gnosticism is needful to them, and the history of Simon Magus gives it a fact to hang on, so I can hardly do without that.
The Riot of Ephesus Miss Martin did not scratch out, and I think it cannot be dispensed with. In a real life of St Paul it would assume much larger proportions. I hope you can let me have as much of my thread as I have left myself, or indeed I shall scarcely know how to make the book worth having

Yours sincerely

C M Yonge


[^1]: Frances Martin was the editor of Macmillan\'s [Sunday Library](/topic/145) series, to which CMY was writing The Pupils of St. John the Divine.
