---
id: 2199
title: Alexander Macmillan to Charlotte Mary Yonge
iso-date: '1867-07-25'
display-date: July 25. 1867.
from-name: Charlotte Mary Yonge
to-name: Alexander Macmillan to Charlotte Mary Yonge
manuscript-location: 'Copy outletter book British Library Add MSS.55387 (1): P. 389'
---

Dear Miss Yonge	
The parcel for [Miss Lewis](/person/873) reached Tooting safely, and will not in the least inconvenience [me](/person/939).[^1] I will endeavour to deliver it early after my arrival.
I have read the [Story of the Scotch girl](/topic/193). It is very interesting - rather sensational in fact. [Robespierre](/person/2420), [Danton](/person/2421), [Napoleon](/person/2207), the Guillotine 'La Lanterne,' a sprinkling of smugglers with a slight dash of wreckers, highly toned Irish, Scotch, French nationalities, a mad woman, suicide, a murder or two &c &c. make up a dish that certainly cannot be considered savourless. There is no great reach of thought, as [Mrs Lewes](/person/1994), or [Mrs Gaskell](/person/1965) have, nor anything like grace & delicacy of touch of [Miss Thackeray](/person/1240) but it looks to me vigorous firm drawing. I am getting a friend, a critic by profession to look at it. My reading was too much in novel reading vein to enable me to judge. Besides it was done between 11p.m. and 2 a.m. after a [illegible] of day
We shall communicate direct with her.
Yours very sincerely
A. Macmillan


[^1]: CMY had asked him to deliver an illumination to her friend Miss Lewis in Philadelphia.
