---
id: 2207
title: To Christabel Rose Coleridge
iso-date: '1867-09-24'
display-date: Sept 24th [1867]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
Here is the September [Barnacle](/periodical/89) – the binder has really made it so, though it ought to be the Midsummer one. I suppose that great MS ought to go round with it as I suppose no one would have patience to copy it out in the right size[^2] It was very stupid and this thin Barnacle would be much the better for it. Will you put in a note to that effect when you write the orders. I have only the conclusion of Two and Two[^3] towards another and I go to Ottery on Monday and to Puslinch on Wednesday next for a month, so the answers should come to me at Puslinch (Yealmpton) if they are not ready before Monday –
In haste

yours sincerely

C M Yonge
Giftie I shall be glad of whenever you can send her – or wherever.
I have two old Barnacles here waiting


[^2]: The copies of the Barnacle were assembled from material written by contributors on their own paper, and though member of the [Gosling Society](/topic/104) were begged and exhorted to use a standard size, the pages vary a good deal in size and shape.
[^3]: Two and Two, a story by Frances Peard (Fern Seed) features in the last extant volume of the Barnacle (Michaelmas 1867).
