---
id: 2231
title: To Ann Maria Carter Smith
date: '1868-01-01'
display-date: Jany 23d [1868]
from-name: Charlotte Mary Yonge
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1869/1
---

My dear [Miss Smith](/person/263),
Your story is capital and I am very glad that the power of writing no longer seems to be crushed out of you.

The only things I have to say are that I think a little guarding is wanted (which I would do in a note) to shew that part of it is playful since [Church restoration](/topic/198) is not altogether matter of taste, and some of the deformation was really luxury, family pride and irreverence.

Of course some was only bad taste - like the porch of St Mary’s at Oxford, but I do not think people had any right to block windows with monuments especially with heathen monsters in them.

Don’t you think 15 years rather a short space for time to out run Mr Short so! I think 20 or 25 /ago\ was as near as I can remember the era of cottage bonnet and blue ribbons I remember very big shady hats first coming in in 1854 and 5, but young ladies were pretty fast by that time, and if Mr Short was a High Church Oxonian, he would hardly have fallen in love with the gallery and monument, but have been crazy for rubbing brasses - and zealous for getting down ‘pues’ as he would have spelt them.

But I suppose to put it five years back would disturb Edith’s age too much.

By the by Kate and Kitty are fashionable now would not Sally match better?[^2]
I am glad you have been writing a longer story I hope I may soon see it

yours sincerely

C M Yonge
I think we can vote for your idiot.[^3]


[^1]: Black-edged paper.
[^2]: Most of the features CMY criticized remain in the published story, \'Mr.

Short\'s Summer Visit to Bishop Thornton\' MP (July 1868) 42-53, but Sally appears on p.53.
[^3]: CMY and her mother subscribed to the [Earlswood Asylum](/organisation/38), so had a vote to give eligible candidates.

Carter Smith was trying to get a girl in, but the Yonges had been unable to vote for her in 1866, having promised their vote elsewhere.

See letter to A.

Carter Smith of 3 May 1866.
