---
id: 2267
title: To Christabel Rose Coleridge
date: '1868-09-15'
display-date: Sept 15th [1868]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
I think you had better guide the flight of the [Barnacle](/periodical/89) I have nothing special to observe about it, except that it might be worth while to let [Mary Morshead](/person/28) have it at once, as I do not know how soon she sails.[^1] I suppose it is the last at least for the present[.] [Mrs Valentine](/person/1437) is getting up another Christmas annual, especially for children, so I should think it might be worth while to write to her and then you could ask after Giftie.[^2] [Mamma](/person/1606) is very weak and only gets up to take a short drive in her donkey chair every day. I think [Lady Coleridge](/person/347) must be better since [Edith](/person/331) saw her[,] for [Miss Dyson](/person/464) seems satisfied about her, and she is at Ottery now.

your affectionate

C M Yonge

You idle [Gosling](/topic/104) - you don’t give a hint where here  is - so this must go to Hanwell.


[^1]: For Cape Town to work as a missionary.

See letter to Christabel Coleridge, 1 July 1868.
[^2]: Laura Valentine worked as a children’s books editor for Warne, who published Giftie in 1869; the annual was probably Warne’s Home Annual (1869 etc).

Perhaps the Christmas 1868 edition was dated 1869.
