---
id: 2294
title: To Christabel Rose Coleridge
iso-date: '1868-12-01'
display-date: Decr 3d [1868]
from-name: Charlotte Mary Yonge
from-address: Puslinch Yealmpton
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
Thank you and [Edith](/person/331) for taking the Bandits’ Bride[^2], I hope your collections will prosper. We have £163, and want £700 if we build a masters house, £400 if we content ourselves with a school
Have you written to [Miss Arnold](/person/1467), or shall I accepting [Miss Clarke](/person/300) I find [Grace Latham](/person/2024) has not time, so perhaps we had better accept [Miss Budd](/person/219) and [Miss Llewellyn](/person/2025). Scotland has sunk away from us, so I suppose Wales is coming instead The other perhaps we had better reject on the grounds of not being a round dozen. I think twelve is the right number.
Since September December is begun I shall send you Mother Goose’s own questions, to save one writing out of them.[^3]
‘Give a history of the art of letter-writing with an account of the most noted letters and correspondents ancient and modern.
What are the synonyms of Beauty – give their derivation, history and shades of meaning
your affectionate
Mother Goose
This ought to have gone yesterday


[^2]: A reference to the photograph of CMY which she was selling in aid of the proposed school in connection with the [Church of the Resurrection](/place/188), Eastleigh.
[^3]: The letter is concerned with the administration of the [Gosling Society](/topic/104), of which Coleridge was secretary.
