---
id: 2295
title: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
iso-date: '1868-12-21'
display-date: December 21, 1868.
from-name: Charlotte Mary Yonge
from-address: St. Thomas, Norfolk Island
to-name: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. This fragment printed in Yonge, <i>[[cmybook:102]Life
  of John Coleridge Patteson]</i>, II, 341-4 and 346-8.
---

My dear Cousin,
[I](/person/1155) must write you a few lines, not as yet in answer to your very interesting letter about [Mr. Keble](/person/798) and about Ritualism, &c., but about our great event of yesterday.
[George Sarawia](/person/1980) was ordained Deacon in our little chapel, in the presence of fifty-five Melanesians and a few Norfolk Islanders. With him [Charles Bice](/person/2026), a very excellent man from [St. Augustine](/organisation/13)’s, was ordained Deacon also. He has uncommon gifts of making himself thoroughly at home with the Melanesians. It comes natural to him, there is no effort, nothing to overcome apparently, and they of course like him greatly. He speaks the language of Mota, the lingua franca here, you know.
But what am I to say of George that you cannot imagine for yourself? It was in the year 1857 that the [Bishop](/person/1295) and I first saw him at Vanua Lava Island. He has been with us now ten years; I can truly say, that he has never given me any uneasiness. He is not the cleverest of our scholars; but no one possesses the confidence of us all in the same degree. True, he is the oldest of the party, he can hardly be less than twenty-six years old, for he had been married a year when first we saw him; but it is his character rather than his age which gives him his position. For a long time he has been our link with the Melanesians themselves whenever there was something to be done by one of themselves rather than by us strangers. Somehow the other scholars get into a way of recognising him as the A 1 of the place, and so also in Mota and the neighbouring islands his character and reputation are well known. The people expect him to be a teacher among them, they all know that he is a person of weight.
The day was warm and fine.
At 7.20 A.M. we had the Morning Service, chanting the 2nd Psalm. I read Isa. xlii. 5-12 for the First Lesson, and 1 Tim. iii. 8-13 for the Second, and the Collect in the Ordination Service before the Prayer of St. Chrysostom. [Mr. Codrington](/person/312), as usual, read the prayers to the end of the third Collect, after which we sang our Sunday hymn.
‘At 11 A.M. we began the Ordination Service. One Epiphany hymn, my short sermon, then Mr. Codrington presented the candidates, speaking Mota for one and English for the other. The whole service was in Mota, except that I questioned Bice, and he answered in English, and I used the English words of Ordination in his case. George was questioned and answered in Mota, and then Bice in English, question by question. [Mr. Nobbs](/person/1986) was here and a few of the people, [Mr. Atkin](/person/1979), [Mr. Brooke](/person/1981), so we made a goodly little party of seven in our clerical supper.
What our thoughts were you can guess as we ordained the first Melanesian clergyman. How full of thankfulness, of awe, of wonderment, the fulfilment of so much, the pledge of it, if it be God’s will, of so much more! And not a little of anxiety, too - yet the words of comfort are many; and it does not need much faith, with so evident a proof of God’s Love and Power and Faithfulness before our very eyes, to trust George in His Hands.
The closing stanzas of the Ordination Hymn in the ‘Christian Year’ comforted me as I read them at night; but I had peace and comfort, thank God, all through.
Others, too, are pressing on. I could say, with truth, to them in the evening in the Chapel, ‘This is the beginning, only the beginning, the first fruit. Many blossoms there are already. I know that God’s Spirit is working in the hearts of some of you. Follow that holy guidance, I pray always that you may be kept in the right way, and that you may be enabled to point it out to others, and to guide them in it.’
And yet no words can express what the recoil of the wave heathenism is, but ‘when the enemy shall come in like a flood,’ and it has indeed its own glorious word of Promise. It is like one who was once a drunkard and has left off drinking, and then once more tastes the old deadly poison, and becomes mad for drink; or like the wild furious struggles (as I suppose) of poor penitents in penitentiaries, when it seems as if the devil must whirl them back into sin. You know we see things which look like ‘possession,’ a black cloud settling down upon the soul, overwhelming all the hopeful signs for a time. And then, when I have my quiet talk with such an one (and only very few, and they not the best among us), he will say, ‘I can’t tell, I didn’t mean it. It was not I. What was it?’ And I say, ‘It was the devil, seeking to devour you, to drag you back into the old evil dark ways.’ ‘It is awful, fearful.’ ‘Then you must gird your loins and pray the more, and remember that you are Christ’s, that you belong to Him, that you are God’s child, that Satan has no right to claim you now. Resist him in this name, in the strength of the Spirit whom Christ has sent to us from the Father, and he will flee from you.’
It is of course the same more or less with us all, but it comes out in a shape which gives it terrible reality and earnestness. Only think, then, more than ever, of them and of me, and pray that ‘the Spirit of the Lord may lift up a standard against the enemy.’ At times we do seem to realise that it is a downright personal struggle for life or death.
‘January 8th.-A very joyful Christmas, but a sad Epiphany!
[U---](/person/1975), dearer to me than ever, has (I now hear from him) been putting himself in the way of temptation. I had noticed that he was not like himself, and spoke to him and warned him. I told him that if he wished to be married at once, I was quite willing to marry him; but he said they were too young, and yet he was always thinking of the young fiancée,[^1] *but I did not know he was contriving plans for their meeting when the others were at singing class -- in the evenings a voluntary matter, and therefore no strictness in requiring all to be present (the regular singing class being different, at 3 p.m.).
On Saturday last she was not quite well, he went to see her in the evening, and not with any wrong intention, as he tells me (and I think he has told me everything).* Alas! he had too often (as he says) put himself in the way of temptation with his eyes open, and he fell. He was frightened, terrified, bewildered.
Alas! it is our first great sorrow of the kind, for he was a Communicant of nearly three years’ standing. Yet I have much comfort.
I can have no doubt, 1st, that a fall was necessary, I believe fully. His own words (not suggested by me) were, ‘I tempted God often, and He let me fall; I don’t mean He was the cause of it, it is of course only my fault; but I think I see that I might have gone on getting more and more careless and wandering further and further from Him unless I had been startled and frightened.’ And then he burst out, ‘Oh! don’t send me away for ever. I know I have made the young ones stumble, and destroyed the happiness of our settlement here. I know I must not be with you all in Chapel and school and hall. I know I can’t teach any more, I know that, and I am miserable, miserable. But don’t tell me I must go away for ever. I can’t bear it! ‘
I did manage to answer almost coldly, for I felt that if I once let loose my longing desire to let him see my real feeling, I could not restrain myself at all. ‘Who wishes to send you away, U--? It is not me whom you have displeased and injured.’
‘I know. It is terrible! But I think of the Prodigal Son. Oh! I do long to go back! Oh! do tell me that He loves me still.’
Poor dear fellow! I thought I must leave him to bear his burthen for a time. We prayed together, and I left him, or rather sent him away from my room, but he could neither eat nor sleep.
The next day his whole manner, look, everything made one sure (humanly speaking) that he was indeed truly penitent; and then when I began to speak words of comfort, of God’s tender love and compassion, and told him how to think of the Lord’s gentle pity when He appeared first to the Magdalene and Peter, and when I took his hand in the old loving way, poor fellow, he broke down more than ever, and cried like a child.
Ah! it is very sad; but I do think he will be a better, more steadfast man: he has learnt his weakness, and where to find strength, as he never had before. And the effect on the school is remarkable. That there should be so much tenderness of conscience and apprehension of the guilt of impurity among the children of the heathen in among many brought up in familiarity with sin, is a matter for much thankfulness.[^2]
Well, my dear Cousin, I have told you this! It will help to bring us nearer to you, I think, in our mixed joys and sorrows.
I think of you and your great sorrow.[^3] May God strengthen you to bear it patiently, and I know He will do so; and after all, there is no real sorrow but that which comes from sin. These other trials are hard to bear, but there is nothing in them; and yet how easy it is to say this, living in comfort, to one in the deep water!
May God bless and comfort you.
Your affectionate Cousin
J.C.P.


[^1]: The passage between asterisks was omitted from the revised edition.
[^2]: The rest of the letter, from this point on, was omitted from the abridged edition.
[^3]: CMY\'s [mother](/person/1606) had died on 28 September 1868.
