---
id: 2296
title: To Anne Elizabeth Mary Anderson Morshead
iso-date: '1869-01-19'
display-date: January 19, 1869
from-name: Charlotte Mary Yonge
to-name: To Anne Elizabeth Mary Anderson Morshead
manuscript-location: MS location unknown. Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  331-2
---

My dear [Mary](/person/28)
Thank you so much for your long letter and history of all your doings.[^1] I am sure if usefulness makes a happy life this ought to be one, and you must have much of kindness and of the sense of a living Church round you to fill you with energy. I do not know whether you have ever felt a sort of sense of the absence of the whole salt of life in being with people who had not gone on to the energetic influences of the Church. I don’t quite know whether I am writing sense, but I do remember such a weary flat feeling at one place I stayed at, where the people were highly cultivated, but their energy and interest in Church matters seemed to have died out. I told [F. W.](/person/1520) that you had been saying her verses about the Tree to the [Bishop](/person/578), and she only hoped you remembered that some of them were a quotation from [Dr. Neale](/person/1078). I shall be very glad if you can send me a paper on Church work, but in general I had made it a rule to leave missionary papers to the [Net](/periodical/94), because they do get so frittered and dispersed among too many magazines, but I do not think that Church work in Cape Town exactly comes under this category, and there is no harm in making an exception sometimes.[^2] The Illustrated News is so good as to say that but for its sectarian character the [Monthly Packet](/periodical/52) would take a high rank among magazines, and I do not wish to diminish that character, though I do not wish to increase it.[^3] How do you get on with your Dutch? It looks as if it must be like speaking very broad Somersetshire. You will have heard how [Anne](/person/1582) and I went into Devon together; I saw your [mother](/person/41) and all your sisters.[^4] What a very nice face [Beatrice](/person/31)’s is. But they were not at home when I called with [Elizabeth Colborne](/person/320). [Reginald](/person/318) and [Frank Colborne](/person/323) are come to [Winchester](/organisation/50) to be in the same house with [Ernest Morshead](/person/29); it must be a tremendous change for them, coming so suddenly too. I am staying away from home for a few days, and so getting time to write my letters. I fancy I shall make a good many little excursions this year, including one to Normandy, but you had better always write to me at home, as a letter there will be sure to find me. The [Goslings](/topic/104) are come to life again, and I am expecting a flight of answers in a few days, indeed the very day when I hope you will be seeing [Bishop Macrorie](/person/2027) consecrated. [Archbishop Tait](/person/1391)’s appointment pretty thoroughly settled that matter.[^5] I hear that the building of [Keble College](/person/5) is getting on very nicely, and that Mr. [Edwin Palmer](/person/1128) is talked of for the head.[^6] [Fernseed](/person/1160) and I hope to stay at New College together in the first week in June. Will not that be most delightful? I am afraid this is a very stupid letter, but you will write to me again I hope, and tell me how you are going on, and what your work settles into.
Your affectionate cousin
C. M. Yonge


[^1]: Mary Morshead was now working as a missionary in Cape Town.
[^2]: It seems probable that the article \'Account of the Consecration of the Rev. W. K. Macrorie\' which subsequently appeared in MP was by Mary Morshead.
[^3]: It is not quite clear which periodical CMY refers to here; the Illustrated London News seems unlikely to have been making animadversions on the MP; a more likely possibility is the Pictorial Missionary News edited by the Rev. Henry Grattan Guinness.
[^4]: The sisters were [Louisa](/person/36) (b.1846/7), [Julia](/person/34) (b. 1850/1), [Mildred](/person/37) (b. 1855/6) and Beatrice Anderson Morshead.
[^5]: The Rt. Rev. William Kenneth Macrorie (1831-1905) was consecrated Bishop of Maritzburg by Bishop Gray on 25 January 1869, a rival to [Colenso](/person/1872) who was still in Natal maintaining his right to be bishop. The Rt. Rev. Archibald Campbell Tait, Bishop of London, had been appointed Archbishop of Canterbury in October 1868.
[^6]: The Ven. Edwin Palmer (1824-1895), archdeacon of Oxford, was not appointed head of Keble College.
