---
id: 2322
title: To Arthur John Butler
iso-date: '1869-06-18'
display-date: June 18th [1869]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Arthur John Butler
manuscript-location: MS Mrs Caroline Fairclough/18
---

My dear [Arthur](/person/238)
Thank you much These thanks would have come sooner but that just as I was going to study and profit by your notes, a Yankee walked in with a letter of introduction, and I had to perform my civilities to him - alas he came just as the mutton was half cold and the pease all gone

I shall set to work and doctor up the chapter incorporating what you have done to it.[^2] I think Clark’s comparative grammar is pretty good so far as I understand it, and I am pretty well off for Greek, French and English, but I am not satisfied with my Latin lights, and the next is a good deal light of nature I am sorry for the Agnus but no doubt you are right. I am going to rewrite and work your corrections in, and then most probably I shall molest /you\ again.

My photograph looks as if - under certain conditions it might have turned out rather good, for such an unphotographable person as I know myself to be - at any rate ‘smiling at grief’ as I appear to be is better than frowning like a sepoy’s daughter or bandit’s bride as I generally do.[^2] [Emma](/person/822) will think you unusually successful when she has seen the portrait gallery here!

Pray thank your [mother](/person/240) and [aunt](/person/113) for their letters and the latter for her hint about the Dolomites, by which I hope the [Packet](/periodical/52) may profit.

yours sincerely

C M Yonge


[^2]: This correspondence with Arthur Butler relates to a series in MP on which they were collaborating entitled [\'Polyglott Parsing\'](/book/348), which traced the connections between several ancient and modern languages.
