---
id: 2328
title: To Mary Anne Dyson
date: '1869-08-05'
display-date: August 5 [1869]
from-name: Charlotte Mary Yonge
from-address: '[[other:205]Val Richer],'
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown. Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  238- 241
---

My dear [Marianne](/person/464)
Here we are, after having, I think, done very well on our journey.

We met [Miss Martin](/person/971) on board the steamer. I forget whether I told you that she had begged to come at the same time for the benefit of our escort, and though we had rather have been alone, she was very helpful and pleasant.

She is the editor of the [Sunday Library](/topic/145), which is the way we fell in with her.

It was rather a nasty passage, 460 people in the boat, very much in each other’s way under the circumstances, and [Frances](/person/1604) and [Harriet](/person/1359) were both very bad. I never go beyond being rather unhappy and helpless, and the worst of it was it was raining hard all the time, and all the umbrellas but one had imprudently been packed up, so you may suppose how wet people were.

Frances came out terribly wet through, and shivering, but some drops of essence of camphor on a lump of sugar staved off a cold.

Of Calais we only saw outlines enough to make us feel we were in France, and misty rain hindered us from seeing anything till we came near Amiens, and then we had to wait about an hour at the station.

We found the town was too far off to go to see the cathedral, so our chief edification there was the embraces of a priestly seminary breaking up for the holidays as it seemed, for there were twelve or fourteen priests, mostly very young, and thirty or more little boys.

There was a great kissing on both cheeks of the priests as they parted, but most went on with the train, and priests and boys were dropped here and there by the way.

One little fellow had an old peasant father and mother who came to meet him, and kissed and smoothed his hair, and walked off in great pride. [M.

Guizot](/person/597) says the best scholars at the village schools go to these seminaries and become either priests or schoolmasters.

At each station stood a woman in blue, with a high-glazed hat over her white cap, holding up a staff perpendicularly as a signal, It had a very quaint effect.

Moreover, French electric wires don’t make the weird Æolian harp sound that ours do, but go tinkle, tinkle, like little bells.

All the last part of the way was in the dark.

We got to the Hotel d’Angleterre at Rouen at 10 P. M., and climbed up an enormous staircase to our tiny rooms, and oh the noise! carts, carriages, steam-engines, music, laughing, talking, chattering, till 2 A. M., and by 5 a man was shouting about ‘citoyen’ under the window.

None of us had any sleep except from 3 to 5, and by 7 we were all out making our way to the Cathedral.

It was like getting into the middle of a picture of[ Prout](/person/1213).

The west front had the grandeur one knows. but the most remarkable feature within struck me as being that there was a gallery of arches below the triforium, so as to have four steps up to the roof instead of three.

There was Mass going on in three different places - at an altar outside the choir, at the Lady Chapel, and in one of the little altars that there were on the east wall of the recess of every window, but the choir with the high altar was shut up and looked desolate.

The north doorway, called the Portail du Calende, was very curious; it has the whole history of Jacob and Joseph in tiny compartments, an immense number of little scenes.

We peeped into St.

Maclou, a very splendid old church, but its east end sadly disfigured by the great gilded shrine, with a huge golden angel descending amidst big golden beams (in both senses of the word).

St.

Ouen was certainly the loveliest thing I saw, and every fitting there is in excellent taste, most dainty Gothic shrine work rising behind the choir, and the whole with great gracefulness and majesty combined, but I cannot recall the details now, I saw it in so much haste.

We found the Place de la Pucelle, with its curious old houses, and had not much more than time to get back to the Quai.

It really is very grand there, the broad river with its ships, the suspension bridge crossing it, the quaint old houses round, the rows of trees with benches under, and green hills partly wooded to be seen whether you look up or down the river, the spire of Notre Dame de Bon Secours rising up most beautifully. I wish we could have had a day there only, not a night.

Into the train again, with a little boy about nine and his bonne.

He was very loth to leave his mamma, and kissed and clung to her to the last moment, and then was in very high spirits all the rest of the way.

It was very beautiful.

All along were hills of chalk, partly wooded, and here and there broken quite into crags and cliffs, while pinnacles of chalk stood out on the very edge of the stream like the Needles come inland.

They were the Rochers (I think) d’Obteimer, but I must learn the name. I was sorry when we tunnelled through them, but it was still very pretty; the railroad seemed to go through the centre of a valley, with low ridgy hills sloping down into water, [sic] meadows, or harvest-fields.

Sometimes a perfect sea of ruddy corn, and the cottages were beautiful, black-timbered and white-washed between, and their high-pitched roofs make their shapes so pretty. the apple and pear trees often stood out quite in the midst of the corn, and the flax was done up in tiny little fan-shaped shocks, looking like a fairy’s harvest.

On a hill side we saw an old tower, which had been part of the Abbey of Bec, and amazed me, for I had always fancied it by a riverside in a forest.[^2] The river Reel, however, runs through green meadows, and all that part put me in mind of Stroud as we came into Lisieux, and saw the fields below the wooded hills covered with bleaching linen, and those houses standing perched about.

At Lisieux carriage and cart met us, and we drove out here, all getting shyer and shyer every minute, till we came in by the great white gates, and the whole family turned out at the door to welcome us. M.

Guizot looks smaller and much more wiry, active, and alert than in the photo, with his bright eyes and courteous eager manner.

Between English and French I can get on very well with him, and [Mme. de Witt](/person/423) talks English perfectly, and so do her girls.[^3] [Julian](/person/1624)’s French is a more serviceable article than mine, which is lucky, as [M. de Witt](/person/419) speaks no English though he understands it, but he is much given to la mécanique, and so they get on together.

This is a regular French bedroom, like a little drawing-room, the bed in an alcove, and all the washing in two little closets.

We get a roll and cup of tea or coffee at eight, and come into public at eleven to prayers and breakfast.

It is now a little after ten, and I shall finish up my letter before I go down, as I do not know when the post goes.

They are very kind, and it is very pleasant. I really enjoyed yesterday evening very much, and it will be sure to improve with greater familiarity with the ways of the place and the language.

The garden is beautiful, on very broken ground, and a great glow of geraniums and roses.

We are just too late for the distribution of prizes at the village school, for which I am sorry, harvest holidays having set in.

If you can read this letter in its streaky criss-cross, send it on to [Gertrude Walter](/person/1462) at Otterbourne, and she may please send it to [Miss Mackenzie](/person/930), Woodfield, Havant.

We encountered [Mr.](/person/934) and [Mrs.

Mackenzie](/person/935) at the Charing Cross station, to my great pleasure.

Alas! it is raining. I will describe more to-morrow.

Your most affectionate
C. M. Y.


[^1]: Like CMY, Guizot had contributed to the Sunday Library series.
[^2]: The Abbey of Bec is mentioned in [The Little Duke](/book/20).
[^3]: Henriette (Guizot) de Witt (1829-1908), translator and author, elder daughter of Guizot, had married Conrad de Witt in 1850.

Their two surviving children were [Marguérite](/person/425) (1853-1924) and [Jeanne](/person/424) (1855-1944).
