---
id: 2350
title: To the Reverend John Frewen Moor
date: '1869-11-04'
display-date: Novr 4th [1869?]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To the Reverend John Frewen Moor
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e 86.'
---

My dear [Mr Moor](/person/1046)
This is what [Mrs Arnold](/person/2055) says, and I should think the terms as fair as could be expected.

She is not a very charming looking person, but her [husband](/person/62) has been half over the world and will probably be entertaining --- I wish I could send this over to you today, but our man is laid up with a bad cold --- Anything more you like me to do, I will most gladly. I suppose the Arnolds should meet [Frewen](/person/2056) at the Bishopstoke station. I wish your report of [Mrs Moor](/person/1044) were more comfortable[^1]

Yours sincerely

C M Yonge
On second thoughts you may be glad to save a post, so I send this by a messenger --- Tell me if I can be of [help] I wish I were not too beset with children and young maids to take Frewen in myself but I will send him some books -- to Linkhorn’s farm.


[^1]: Black-edged paper.
[^2]: The problem seems to be to find accommodation nearby for Frewen Moor who is coming home from school and cannot come home because his mother is ill.
