---
id: 2355
title: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
date: '1869-11-24'
display-date: November 24, 1869.
from-name: Charlotte Mary Yonge
from-address: Norfolk Island
to-name: The Right Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. Printed in Yonge, <i>[[cmybook:102]Life
  of John Coleridge Patteson</i>], II, 390-6.
---

My dear Cousin,
To-day we married three young couples: the bridegrooms,[Robert Pantatun](/person/2004), [William Pasvorang](/person/2059), and [Marsden Sawa](/person/2060), who have been many years with us, and are all Communicants; the brides, [Emily Milerauwe](/person/2061), [Lydia Lastitia](/person/2062), and [Rhoda Titrakrauwe](/person/2063), who were baptized a year ago.

The Chapel was very prettily dressed up with lilies and many other flowers.

The bridegrooms wore white trousers, shirts, &c., the brides wore pretty simple dresses and flowers in their hair.

We crowded as many persons as possible into our little Chapel. [Mr.

Nobbs](/person/1986) and some ten or twelve of our Pitcairn friends were all the visitors that we could manage to make room for.

Great festivities followed, a large pig was killed yesterday and eaten to-day, and [Mr.

Palmer](/person/1884) had manufactured puddings without end, a new kind of food to many of the present set of scholars, but highly appreciated by most of them.

Then followed in the evening native dances and songs, and a supper to end with, with cheers for the brides and bridegrooms.

There are now six married couples here, three more at Mota, and one or two more weddings will take place soon.

Very fortunately, a vessel came from Auckland only three or four days ago, the first since the ‘Southern Cross’ in June.

It brought not only five mails for us English folk, but endless packages and boxes for the Mission, ordered by us long ago, stores, clothing, &c.

We had all ordered more or less in the way of presents for scholars, and though we keep most of these treasures for Christmas gifts, yet some are distributed now.

These presents are for the most part really good things.

It is quite useless for kind friends to send presents to Melanesians as they would do to an English lad or girl.

To begin with, most of our scholars are grown up, and are more like English young people of twenty or eighteen years old than like boys and girls, and not a few are older still; and secondly, no Melanesian, old or young, cares a rush about a toy.

They, boys and girls, men and women, take a practical view of a present, and are the very reverse of sentimental about it, though they really do like a photograph of a friend.

But a mere Brummagem article that won’t stand wear is quite valueless in their eyes.

Whatever is given them, cheap or dear, is estimated according to its usefulness; and whatever is given, though it may cost but a shilling, must be good of its kind.

For example, a rough-handled, single-bladed knife, bought for a shilling, they fully appreciate; but a knife with half-a-dozen blades, bought for eighteen-pence, they would almost throw away.

And so about everything else. I mention this as a hint to kind friends.

They do like to hear that people think of them and are kind to them, but they don’t understand why useless things should be sent from the other end of the world when they could buy much better things with their own money out of the mission store here.

They are very fond of anything in the way of notebooks, 8vo and 12mo sizes (good paper), writing-cases (which must be good if given at all), patent safety inkstands--these things are useful on board ship, and can be carried to the islands and brought back again safely.

Work-baskets or boxes for the girls, with good serviceable needles, pins, thread, scissors, thimbles, tapes, &c. &c., not a plaything.

Here we can buy for them, or keep in the store for them to buy, many things that are much too bulky to send from a distance, the freight would be ruinous.

The ‘Southern Cross’ brings them usually to us.

Such things I mean as good carpet-bags, from 5s. to 10s., stout tin boxes with locks and keys, axes, tools, straw hats, saucepans, good strong stuff (tweed or moleskin) for trousers and shirts, which they cut out and make up for themselves, quite understanding the inferior character of ‘slop’ work, good flannel for under-shirts, or for making up into Crimean shirts, Nottingham drill, good towelling, huckaback, &c., ought to be worth while to send out, and if bought in large quantities at the manufacturer’s, it would pay us to get it in England, especially if the said manufacturer reduced the price a little in consequence of the use to be made of his goods.

Dull small blue beads are always useful, ditto red.

Bright glittering ones are no use, few Melanesians would take them as a gift.

Some islanders like large beads, as big or bigger than boys’ marbles.

These are some hints to any kind people who may wish to contribute in kind rather than in money.

[Mr.

Codrington](/person/312) has given these fellows a great taste for gardening.

Much of their spare hours (which are not many) are spent in digging up, fencing in and preparing little pieces of land close about the station, two or three lads generally making up a party, and frequently the party consists of lads and young men from different islands.

Then they have presents of seeds, cuttings, bulbs, &c., from Mr.

Codrington chiefly, and [Mrs.

Palmer](/person/2064) and others contribute.

Some of these little gardens are really very nicely laid out in good taste and well looked after.

They have an eye to the practically useful here too, as every garden has its stock of bananas, and here and there we see the sugar-cane too.

From 3.30 P.M. to 6 P.M. is the play time, although they do not all have this time to themselves.

For three lads must milk from 5 to 6, one or two must drive in the cows, seven or eight are in the kitchen, three or four must wash the horses, one must drive the sheep into the fold, all but the milkers have only their one week of these diverse occupations.

There are about twelve head cooks, who choose their helpers (the whole school, minus the milkers and two or three overlookers, being included), and so the cooking work comes only once in twelve weeks.

The cooks of the one week drive up the cows and water the horses the next week, and then there is no extra work, that is, nothing but the regular daily work from 9.30 A.M. after school to 1 P.M.

Wednesday is a half-holiday, Saturday a whole holiday.

There are six milkers, one of whom is responsible for the whole.

One receives 2s. 0d. per week, his chief mate 1s. 6d., and the other four 1s. each.

They take it in turns, three each week.

This is the hardest work in one sense; it brings them in from their play and fishing, or gardening, &c., and so they are paid for it.

We do not approve of the white man being paid for everything, and the Melanesian being expected to work habitually extra hours for nothing.

There are many other little extra occupations for which we take care that those engaged in them shall have some reward, and as a matter of fact a good deal of money finds its way into the hands of the storekeeper, and a very fair amount of 3d., 4d and 6d. pieces may be seen every Sunday in the offertory bason.

Perhaps I should say that we have seldom seen here any indications of these Melanesians expecting money or presents; but we want to destroy the idea in their minds of their being fags by nature, and to help them to have some proper self-respect and independence of character.

We see very little in them to make us apprehensive of their being covetous or stingy, and indisposed to give service freely.

School hours 8-9.20, 2-3.30, singing 7-8 P.M., chapel 6.45 A.M., 6.30 P.M.

Of the 134 Melanesians, besides the baby, ten are teachers, and with their help we get on very fairly.

There are sixteen of us teachers in all, so that the classes are not too large.

Mr.

Codrington takes at present the elder Banks Islanders, Mr.

Palmer the next class, and [Mr.

Bice](/person/2026) the youngest set of boys from the same group.

[Mr.

Atkin](/person/1979) takes the Southern Solomon Islanders, and [Mr.

Brooke](/person/1981) those from the northern parts of the same group. I have been taking some Leper’s Islanders and Maiwo or Aurora Islanders as new comers, and other classes occasionally.

Out of so many we shall weed out a good number no doubt.

At present we don’t condemn any as hopelessly dull, but it will not be worth while to spend much time upon lads who in five months must go home for good, and some such there must be; we cannot attempt to teach all, dull and clever alike.

We must make selections, and in so doing often, I dare say, make mistakes.

But what can we do?

Our new hall is a great success.

We had all the framework sawn out here; it is solid, almost massive work, very unlike the flimsy wooden buildings that are run up in a week or two in most colonial villages.

It is so large that our party of 145, plus 9 English, sit in the aisles without occupying any part of the middle of the room.

This gives us ample accommodation for the present.

Indeed we might increase our numbers to 200 without any more buildings being necessary.

The married people give the most trouble in this respect, as they have their separate rooms, and four or five married couples take up more room than three times the number of single folk.

However we have here room for all, I am thankful to say, though we must build again if more of our young people take it into their heads to be married.

They pass on quickly, however, when married, into the next stage, the life in their own islands, and so they leave their quarters here for some successors.

I hope you can understand this attempt at a description, but I never could write properly about such things, and never shall do so, I suppose. I like the life, I know, a great deal better than I can write about it.

Indeed, it is a quiet restful life here, comparatively.

Some anxieties always, of course, but, as compared with the distractions of New Zealand life, it is pleasant indeed.

We have very few interruptions here to the regular employment of our time, and need not waste any of it in visits or small talk, which seems to be a necessary, though most wearisome part of civilised life.

Your [namesake](/person/2065) goes on well; not a clever girl, but very steady and good; her sister and brother are here; the sisters are much alike in character and ability, the brother is sharper.

You will, I know, specially think of [George Sarawia](/person/1980) and his wife [Sarah](/person/2002) at Mota, with [Charles](/person/2068) and [Ellen](/person/2069), [Benjamin](/person/2066) and [Marion](/person/2067).

They are all Communicants, but the temptations which surround them are very great, and early familiarity with heathen practices and modes of thought may yet deaden the conscience to the quick apprehension of the first approaches of sin.

They do indeed need the earnest prayers of all.

Your affectionate Cousin,
J. C. PATTESON.
