---
id: 2367
title: To Mary Yonge
date: '1870-01-08'
display-date: Jan 8th [or perhaps 6th, 1870]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Mary Yonge
manuscript-location: 'MS Plymouth and West Devon Area Record Office Acc No 308: 8/1/70'
---

My dear [Mary](/person/1626)
I knew this loss would be one to come home to you especially, so often as you and [uncle James](/person/1614) have consulted together over illness and so much as he loved and trusted you.

It grieves on to look back upon the sad anxious disappointed life it has been, with those strong vehement and always kind and generous aims so seldom successful- at least in that part of his life that I can well remember though the earlier life must have had a good deal of prosperity and success to judge by the great influence he had over Plymouth.

And what exceeding affection his patients had for him, and how much his kindness told upon every body. [^2] But after all the sorrow and trial, it is a peaceful thought that rest has come at last, [Kate](/person/899) and I have been thinking and talking much over this the last of the Cornwood family, our own uncles and she is glad she has not put off her journey so that she was not travelling on Friday.

She goes now at the same time as I do – at 12.57 on Monday. I come back on Saturday and then [Gertrude](/person/1462) is coming up to me for a little while to relieve the long winter shutting up, she has not been out since November, and is quite weary of seeing the same tables and chairs, but altogether she is better this winter than last.

What a night of tempests we have had, and today some of the gusts shake the house, I am glad it was not yesterday, and I am hoping there was not room for you to go, for I am sure you ought not to try your self too much. [Julian](/person/1624) was very sorry not to go, but he had been in his bed half the day before, and if he had set off the moment he got the letter he would have been at Plymouth very late at night. I am grieving too for [Mrs Papillon](/person/1136), who has just lost her [eldest girl](/person/2263) from the effects of scarlet fever, not my [goddaughter](/person/1137) but she is now the only girl, and will feel the loss all her growing up, even if there should be more sisters. [^3] There are three boys; Poor dear [Jane Moore](/person/1042), she must have suffered indeed in the longing to know more, and the suddenness.

What a sad year it has been
your most affectionate

C M Yonge


[^1]: Black-edged paper.
[^2]: As well as having a tragic home life, Dr Yonge tried to keep political radicals and religious nonconformists from gaining influence in the city of Plymouth, with limited success.
[^3]: Emily Caroline (Garnier) Papillon (b.1839), granddaughter of the aged dean of Winchester, married (1862) Philip Oxenden Papillon (1826-1899).

The dead girl was Beatrice Emily Papillon (1863/4-1870) and the goddaughter Muriel Caroline Papillon (b. 1866).

Two more daughters were born subsequently.
