---
id: 2372
title: To Mary Yonge
date: '1870-01-31'
display-date: Jan 31st [1870]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Mary Yonge
manuscript-location: 'MS Plymouth and West Devon Area Record Office Acc No 308: 31/1/1870'
---

My dear [Mary](/person/1626)
Very likely the bill will come out tomorrow, I think Mr Hart may hold his hand now, as the school is in existence. I am not quite sure without asking [Mr Layland](/person/850), but I really think those photographs have raised £20. [^2] Yes, dear [Anne](/person/1582) did send 2/2 every half year for the [penny club](/organisation/10).

It shews how long ago it began that the girl she first took is a married woman now I think you must have forgot the 10/6 of stamps you found you had not enough in the house, but they did not come the next day, or else the post lost them as it did an autograph of Joanna Baillie’s and a Christmas card that were sent to [Gertrude](/person/1462) only from Winchester.

They cannot be traced at all and the Post office only says that they ought to have been registered.

The opening of the school went off very well.

The [Bishop](/person/1512) preached on ‘Verily thou art a God that hidest Thyself, O Lord God of Israel,’ which he pronounced with the last syllable very long.[^3] The Sermon was on the mysterious way in which God hides Himself in the midst of revealing Himself.

The revelations in the OT that cannot be understood without the New he gave as an instance saying that the Three at Abraham’s Tent door and then the One in converse with him seemed as if the [illegible] ‘was trembling on the verge of full revelation of the Doctrine of the Trinity’ He spoke also of the one in each patriarchal tent who seemed to miss the Grace, like the dark lines in the ray of light, and then he brought it to the need of religion being the main point of education since it was so easy to miss Grace even in the fullest light and he made a great distinction between Religion being the one great point and education being what is called founded on Religion
There was a prayer and hymns afterwards at the Opening of the school and the collection was £16, which Mr Layland wants for school materials.

He has a master from the Winchester training school and a sister to live with him and teach work. I did not see much of the Bishop to speak to either then or at the dinner at the Park, there were so many grandees, but on Thursday he was so kind as to come with [Sir William](/person/669) and call, and so Gertrude saw him.

It seems to be his way to call on people, and no doubt that has led to the great influence he had over the county squires in Berks & Bucks.

People were so little used to it here that when he called at Cranbury, [Mrs Chamberlayne](/person/278) asked me what he came for [^4] Unluckily I was engaged to dine there that Thursday and so could not go to Hursley again as Sir William asked me to do. I have not yet heard about the Consecration on St Paul’s day except through the Moberlys.

Their Bishop said the [Greek one](/person/2265) was a most gorgeous sight.[^5] He /[Dr Moberly](/person/1015)\ was invited to the dinner in the Jerusalem chamber but could not go.

They all seem well at Salisbury. I had a long letter on Friday from [Bishop Patteson](/person/1155), safe come home /to Norfolk Island\ with 134 scholars, who came in two relays – he staying at [Mota](/place/150) for five weeks while the Southern Cross was going with the first load.

There are 24 girls now under [Mrs Palmer](/person/2064).

Some only 9 or 10 years old.

They go gladly to be trained to marry Christians saying ‘Then we shall not be beaten – we shall not have our head broken’.

Never mind about the books, they may wait till I come. I have found ‘a noble life’ it had come home before.

The life of Lady Russell [^6] is not mine. I am glad you can leave the dear room undisturbed. I had not been up into it for two or three times, for I thought it teased her to be followed up there – but every corner is vivid before my eyes from very old times.

You have room to leave it, as one cannot in a small house, Gertrude is in our former room here, and she was ill yesterday, so I had to sit with her there all the evening, so like former sittings[^7] Indeed I had to sleep there one night before she came, for a horrible smell broke out in my room that put me out of order for a day or two. I believe it was a drain.

Gertrude is pretty well today. I think she will stay through February as the people at the other house have to go to London. [Mary Walter](/person/1558) has some law business to do on being 25, and it is better to have Gertrude here than alone with the children.

She lies on the sofa very content with her books and work.
I am glad Frank Colborne is to go to London about his ears. [^8] The measles will I suppose run through the house.

They have had another bad spell of colds at the other house. I am sure they keep it too warm [Uncle Yonge](/person/1623) must have been glad he was not obliged to meet [your Bishop](/person/1400) [^9] No doubt the activity of a young man must be felt in the diocese, and he will do much, if it be only the right way.
I was told, on very direct authority – ie, second hand from a visitor in his house at Rugby, that [Mr Gladstone](/person/1653) offered him the Deanery of Durham, saying he could not make him a Bishop, and that he utterly repudiated any right on Mr G’s part so to shelve him
I must go out now
Your most affectionate

C M Yonge


[^1]: Black-edged paper.
[^2]: Photographs of CMY by [William Savage](/person/1283) had been sold to raise funds for the school in connection with [the Church of the Resurrection, Eastleigh](/place/188).

Mary Yonge had bought some and was to have paid in stamps.
[^3]: The new Bishop of Winchester, Samuel Wilberforce, opened the schools at Eastleigh on Monday 24 January, in the presence of \'a large, fashionable and attentive assemblage\' (The Hampshire Advertiser, 29 January 1870).
[^4]: Amelia (Onslow) Chamberlayne (c.1807-1898), wife of Thomas Chamberlayne (1805-1876), of Cranbury Park, Otterbourne’s village squire.
[^5]: Among those present in Westminster Abbey at the consecration of the Rt.

Rev.

John Fielder Mackarness as Bishop of Oxford on 25 January (St.

Paul\'s Day) was the Greek Orthodox Archbishop of Syros, who was visiting Britain.
[^6]: Probably The Married Life of Rachel, Lady Russell (London: Bosworth 1855), an English translation of François Guizot, L\'Amour dans le mariage.
[^7]: The sense of this is that Anne Yonge\'s bedroom is unused at Puslinch, but at Elderfield CMY cannot preserve her mother\'s as a memorial.
[^9]: The Rt.

Rev.

Frederick Temple (1821-1902), headmaster of Rugby 1857-69, had refused Gladstone’s offer of the deanery of Durham in July 1869, and accepted the see of Exeter in September.

There was opposition to his appointment, evidently shared by the Yonges, because he had contributed a relatively uncontroversial essay to a controversial book, Essays and Reviews (1860).

He was subsequently (1896) Archbishop of Canterbury.
