---
id: 2379
title: To Christabel Rose Coleridge
date: '1870-05-09'
display-date: May 9th [1870]
from-name: Charlotte Mary Yonge
from-address: Puslinch
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
I have my doubts whether you are not in the right and [Goosedom](/topic/104) has had its day. I do not think that now I have no one to read and discuss the answers with I do my part with the same spirit and effectiveness, and there are not enough Goslings acquainted with each other to keep the thing up with animation.

Gaggles used [to] do something, but there has been no opportunity of them.[^2]
[Frog](/person/822) does not mean to fail but is always doing it and as you say no one perseveres but [Cricket](/person/1603) and [Double Daisy](/person/1161), the rest are no use at all but to lose the paper.

So on the whole, I believe that when the answers to Cricket’s questions come in, I had better give the Coup de Grace, instead of hunting up anyone to ask a fresh set
The fact is that Goslings used to like the questions they did not know now they only answer those they do know I thought at the time that it was dangerous to print all those papers. [^3]
Certainly Goosedom has been a very great pleasure to its mother but it has been languishing so long that I think it will be better to end it, and if I go to Ottery we will there conduct a finale.

On Thursday I go to [Lady Seaton](/person/314)’s Beechwood Plympton for a week-

yours affectionately

C M Yonge


[^1]: Black-edged paper.
[^2]: Gaggles were occasional meetings of members of the Gosling Society.
[^3]: Probably the printed Rules of the Society of Goslings, a copy of which survives among the Fursdon letters.
