---
id: 2381
title: To an Unknown Woman or to Alexander Macmillan?
iso-date: '1870-05-30'
display-date: May 30th [1870]
from-name: Charlotte Mary Yonge
from-address: Wantage
to-name: To an Unknown Woman or to Alexander Macmillan?
manuscript-location: 'MS British Library Add MSS 54920: 240-1'
---

My dear Madam,[^2]
I have been having some talk and consultation about the Godmother’s Readings with people who have so much to do with schools as to be really an influence
First, I am advised strongly to do - what I proposed at first - to have the Scripture part, without the comment, printed separately, as cheap as may be, for the children to use, while the teacher has the one with the comment. I do believe this would be greatly used in Schools if we can make it cheap enough[^1]
Another advice is to keep the Godmother out of the title, as that is thought likely to discourage the sale for Schools. I suppose if my name goes to it, the individuality would be marked enough. I believe it is only the first page that this change would affect
Scripture Readings
by

Charlotte M Yonge
Then people would ask for it as Yonge’s Scripture Readings.
My address here is the [Rev’d Wm Butler](/person/244)’s Wantage - I go home on Thursday

Yours sincerely

C M Yonge


[^1]: Black-edged paper.
[^2]: This letter is among the correspondence with [Alexander Macmillan](/person/939), and the salutation may simply be a mistake. Or the letter may have been addressed to his sister-in-law [Eliza (Orridge) Macmillan](/person/941), who was his partner, but one would expect CMY, who had met her, to address her as Mrs Macmillan. Or it is possible that the letter was addressed to [Frances Martin](/person/971), the editor of [Macmillan\'s Sunday Library](/topic/145), although the Scripture Readings do not appear to have come out in that series.
