---
id: 2432
title: To Mary Ann Moberly
date: '1872-01-01'
display-date: Jan. 1, 1872.
from-name: Charlotte Mary Yonge
to-name: To Mary Ann Moberly
manuscript-location: MS location unknown.  This fragment printed in [[otherbook:122]<i>Dulce
  Domum</i>], 245-6.
---

[[To [Mary Ann Moberly](/person/1019)]There is a full detail of all that is known in a letter from [Mr.

Brooke](/person/1981) in the new number of [Mission Life](/periodical/80) . . . both bring out more of the pain and grief than the first, which rests on one like a vision of the crystal sea and the palm.[^1] But the sweet smile bears one on through it all. I go to Lichfield on Monday; [Mrs.

Selwyn](/person/1297) says that [her Bishop](/person/1295) is overflowing with recollections of the early days of the mission. . . .

Some islands have been quite depopulated by those wretches. I believe Satan always does stir up something dreadful when his kingdom is being taken from him, but when he can only make martyrs it is well. . .


[^1]: CMY refers to the reports of the death of the Rt.

Rev. [John Coleridge Patteson](/person/1155), and to her visit to Lichfield to research the [biography](/book/102) she was writing.

The Bishop of Lichfield, George Augustus Selwyn, had formerly been Bishop of New Zealand and had appointed Patteson Missionary Bishop of Melanesia.
