---
id: 2434
title: To Christabel Rose Coleridge
iso-date: '1872-01-01'
display-date: Jan 1st [1872]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
I did not mean to admit another [Gosling](/topic/104) but an old promise has come up to [Beatrice Morshead](/person/31), [Bog Oak](/person/28)’s sister, who like her abides at Wiverton Plympton. She is a very nice girl but I don’t think will prove as brilliant as Bog Oak was. Will you tell [Cherry](/person/2276) to send her questions – if it be Cherry’s turn. I have had none from her yet, and I can remember nothing about her but that she lives in Kent. She has sent in a stupidish answer about the Ludicrous
[Bluebell](/person/317) has come home, but has not reunited herself to me so perhaps she goes out, - it would be a pity as she lives near Beatrice.
I think [Good Words](/periodical/73) has got into bondage to crack authors with made names, - I would get out of it if I were you.
It is is such a indescribable feeling about that Martyrdom, between glory and pain, it has seemed never to be off ones mind all this month[[footnote:]]

yours affectionately

C M Yonge
Please send Beatrice the list
