---
id: 2444
title: To Sir William Heathcote, Bt.
date: '1872-04-23'
display-date: April 23, 1872.
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester
to-name: To Sir William Heathcote, Bt.
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  302-303.
---

My dear [Sir William](/person/669)-
I am always bothering you about something, and now I want to ask if you would give me a sentence. I want one describing the remarkable and peculiar merits collectively of the Bench of Judges in the [Patteson](/person/1156) and [Coleridge](/person/344) days.[^1] I cannot well take it out of the mouth of a Coleridge and a judge, and I do not think I can do it rightly myself.[^2] I want to make as full a picture as possible of old Judge Patteson, for he ought to be remembered, and he went for very much in the formation of [his son](/person/1155).

If you would put, as you would in a letter, your view of the high stamp of men who were judges from about 1830 to 1855, it would be what I want expressed. I do not know any one else whom I should like to see doing it but Sir [Roundell Palmer](/person/1129), and I do not know him enough to ask.-

Your affectionate
C. M. YONGE.


[^1]: CRC’s note: This opinion is incorporated in the [Life of Bishop Patteson](/book/102).
[^2]: She means she can hardly ask [John Duke Coleridge](/person/343) to praise his father and uncle at the expense of himself and his judicial colleagues.
