---
id: 2451
title: To Christabel Rose Coleridge
date: '1872-07-01'
display-date: July 1st 1872
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
I like this very much and Gruet is a very satisfactory Eagle.[^1] It is much more satisfactory to reform Ruprecht instead of demolishing him- The land of romance too is a satisfactory variety.

There is one fairy land play – also a story from Gibraltar and one from Ascension isle and one from [Mme de Witt](/person/423) about a poor girl left in charge of her sisters children while their parents are shut up in Paris! [^2] Also a Church decking narrative related by a Church Eagle, who certainly does not shew himself at all a goose.

But I have three visits – only one is a boy’s, which makes a little variety.
I suppose it is too late now for the suggestion but should you not call Ferdinand the Constant Prince to make plain whom you mean
your affectionate

C M Yonge


[^1]: CMy refers to the plans for the Christmas number of the MP for 1872, to which Coleridge contributed a story called \'Minne\'s Knight\'.
[^2]: Inserted above, \'young lady\'.
