---
id: 2486
title: To Alexander Macmillan
iso-date: '1874-01-19'
display-date: Jany 19th 1874
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 1-2'
---

Dear [Mr Macmillan](/person/939)
I am trying the abridging process upon [Bishop Patteson](/book/102), but I hope the latter part can wait to be reprinted till I get the corrections from the Mission itself.
I am much afraid that [Lady Martin](/person/970)’s recollections about New Zealand, about which I wrote to you have been lost on the voyage. They were announced, and enquired after, but never appeared
I see the third volume of the [Scripture Readings](/book/87) must stop with Daniel’s last chapter. I think I can make the 4th and last get to the end of the Acts as there is much less collateral matter to lengthen out with, and to harmonise a narrative from the Gospels is more desirable than to give every discourse. But I must begin from the return from captivity

Yours sincerely

C M Yonge
