---
id: 2497
title: To Edward Augustus Freeman
iso-date: '1874-04-21'
display-date: April 21st 1874
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Edward Augustus Freeman
manuscript-location: MS John Rylands Library, Manchester, FA1/7/835
---

My dear [Mr Freeman](/person/523),
Many thanks for King Ine. I hope we are not to wait thirteen years for his second part.[^1] It goes to my heart to lose St Boniface as a Devonshire man. What could have made them choose such a place for him to be born in as Crediton, if it was not true? No wonder Ceadwalla was tempting to the Witch.! I like Miss Macarthur’s Scotland much, it keeps hold of a clear thread.[^2]
I have been catching it from the [Saturday](/periodical/99) more than I have done for years! I confess I thought it rather captious to blame me for not getting Sir John Elliot’s sufferings into [a baby history](/book/101) of 6 pages to each reign, and for saying the early times of Charles I were quiet, when I simply meant that there was not a civil war! Then there was a funny controversy between a correspondent of mine and the [Athenæum](/periodical/170) critic as to whether Wat Tyler was on horseback or not as he appeared in the picture! Mr Kitchin’s history of France seems to me very good as far as I have got, which is only to the Pippin times[^3]

Yours sincerely

C M Yonge


[^1]: Edward Augustus Freeman, King Ine Part I (1872) and Part II (1874) were reprinted from the Proceedings of the Somersetshire Archaeological and Natural History Society.
[^2]: Margaret Macarthur, History of Scotland (London: Macmillan 1873), volume 3 of the Historical Course for Schools series edited by Freeman.
[^3]: The Rev. G. W. Kitchin\'s A History of France was published in three volumes between 1773-7.
