---
id: 2512
title: To George Lillie Craik
date: '1874-09-07'
display-date: Sept 7th 1874
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To George Lillie Craik
manuscript-location: 'MS British Library Add MSS 54921: 5-6'
---

Dear [Mr Craik](/person/379)
‘Enquiring friends’ kept me in such a whirl on Saturday from the moment I came home that I could not acknowledge the very agreeable parcel I found waiting me, which I need not say I was very glad to see.

It is certainly a pleasant [amount](/topic/160) to look forward to and I see that it does not include the sum for the Abridged Edition of [Bishop Patteson](/book/102), any more than for [Lady Hester](/book/110).[^1]
I hope there has been no mistake about the £200 you were so good as to promise me immediately for I find Messrs [Hoare](/organisation/169) have not received it.

Will you kindly let me know whether it has been paid

Yours truly

C M Yonge		
What honors [sic] for the Patteson memoir
G.L.

Craik Esq
Looking again at your letter I see you say on the 18th of August you have ‘today paid the account,’ - was it to Barnett and Hoare instead of Hoares’ Fleet Street or can they have put it to a wrong account?
