---
id: 2525
title: To Mary Anne Dyson
iso-date: '1875-04-06'
display-date: April 6, 1875
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown. Printed in Coleridge, [[otherbook:40]<i>Life</i>]
  261-2
---

My dear [Marianne](/person/464)
I heard this morning that good old [Mr. Gibbs](/person/560) is gone - on Friday night - his flowers fresh in our church. We had a very successful day, and no doubt [Amélie](/person/869) has told you about it[^1], the Confirmation afterwards, thirty-five of our children, the girls led off by [Helen](/person/1613), [Amy](/person/783), and [Gerty](/person/1482) and six of the school-girls with such sweet solemn faces, and a Cranbury man who had been baptized on Easter Sunday.[^2] Afterwards fifty-four mothers had tea in the school, and [Mr. Ashwell](/person/68) made them a capital speech about what depended on them. So many are my own old girls. One woman is one of seven sisters, and there are and have been twenty-five already at school of the second generation of that family. A good number were communicants next day. I had a feast of talk with Mr. Ashwell, but imagine his materials for [the Bishop](/person/1512)'s life - he never destroyed a letter![^3] He spoke highly of your godson, and enthusiastically of his wife. Well, I think you will get on well with your young [Vicar](/person/2184), and I am sure you will like his [mother](/person/2302); I never heard any one find a fault with her.[^4] No time for more.
Your most affectionate
C. M. Yonge


[^1]: At the time of the 1871 census Amélie Leroy (1851-1934), later a novelist as ‘Esmé Stuart’, was living with Mary Anne Dyson in Crookham and working as a teacher in her school.
[^2]: Apart from CMY\'s niece Helen Yonge, the named confirmation candidates were perhaps Amy Jones-Bateman, whose father was a great friend of Julian Yonge\'s, and Gertrude Webber, stepdaughter of the Rev. Walter Elgie, the curate.
[^3]: He was writing the life of Samuel Wilberforce.
[^4]: The new vicar of Crookham cum Ewshott was the Rev. Gordon Wickham, whose father had been second master of Winchester College.
