---
id: 2572
title: To Christabel Rose Coleridge
date: '1877-02-13'
display-date: Feb 13th 1877
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
Fernando is here and we have read his first five chapters with much enjoyment the only observations I have to make is that the little girls would have been Leonor and Catalina, and that surely Portugal was held by the Moors till Henry of Burgundy conquered it.[^1] I know that Arabia has not affected the language, but I think they possessed the country I like all this about the 5 sons and their mother very much indeed I expect the poor old [S P C K](/organisation/40) is more timid than ever after the recent uproar and that Fernando is not of a Protestant tendency[^2] [Miss Dundas](/person/454) wrote those papers on L E from her Edinburgh experiences and you see we gave[ Miss Kennedy](/person/2307)’s reference for finding out about the Cambridge differences.[^1] [Miss Finlaison](/person/512) is going up on the 13th of March for the ‘pass’ Oxford one, the first – they tell her to take up German and French grammar and composition, arithmetic and algebra to simple equations. I should think [Girton](/organisation/201) would be likely to get the examiners into a groove.

One thing, I don’t think these exams have been made known enough We are amazed at the swarms of enquirers I expect that a dead set at accuracy is being made, to cure female inaccuracy, and that therefore direct cramming tells.[^3] I am enraged with my[ Spiders](/organisation/116) for being tame about the Battle of Lepanto it seems to be out of the line of their sympathies[^4] Our pupil teachers have both got 1st class in Scripture examinations, and of our senior girls we have 1 first class and 2 seconds

yours affectionately

C M Yonge
I will write again when I have finished Fernando, but Lent evening services will hinder ones reading aloud You shall hear when we have done


[^1]: This refers to Coleridge\'s novel The Constant Prince, which was set in fifteenth-century Portugal, and which subsequently appeared in MP.
[^2]: In the agitation about ritualism in the Church of England, the SPCK had been accused of being in the control of the Tractarian movement, and of publishing books which encouraged popery.

See for example, the report of its general meeting headed \'Ritualistic Tracts\' in the Birmingham Daily Post (3 February 1876), 5.
[^3]: Oxford initiated Local Examinations for adolescent boys in 1857, and Cambridge in 1858.

In 1863 girls sat informally for the Cambridge Locals, and in 1865 they were officially admitted by the boards of the Cambridge, Durham and Edinburgh Locals.

In 1870 they were admitted by Oxford.

Miss Dundas was evidently the author of \'A letter to the holders of the Local Certificate\' MP ns 24 (November 1877) 459-69, which is signed L.D..

She was probably Louisa Dundas (b. 1834), daughter of William Pitt Dundas (d. 1883), Registrar General of Scotland.

In MP (March 1877), 288, readers of the magazine who were interested in taking a correspondence course to prepare for the Cambridge Local Examinations were recommended to write to Julia Kennedy, who was prominent among Cambridge supporters of women\'s education.
[^4]: The members of the Spider essay society run through MP had been asked in January to write the history of the battle of Lepanto in 1700 words. CMY commented tartly of their answers MP (March 1877), 5: \'it surprises ARACHNE to find all so tame and so little apparently fired with the spirit of one of the great battles of modern Europe, and one that did so much to stem the progress of Turkish aggression.\'
