---
id: 2595
title: To Augusta Boevey Pode
iso-date: '1877-08-19'
display-date: Aug 19th 1877
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Augusta Boevey Pode
manuscript-location: MS Plymouth and West Devon Area Record Office Ac 1092/31
---

My dear [Augusta](/person/1180)
It is a long time since I heard of you and almost as long since I heard of [Kate](/person/899), and I am anxious to know how she got on this summer I hope [Ernest](/person/1183) is quite well after his chicken pox. I went about looking for him at Domum till I met [Mrs Morshead](/person/2084) and she told me he was gone home. The only Saints day that they did not have him at the other house, I was obliged to go to a meeting of the [Girls Friendly Society](/organisation/23)so I have not seen very much of him this half.[^1] [Gertrude](/person/1462) has been off and on poorly this summer, but she is now gone to her friends at Winston and is to come back on Saturday. I am afraid things are closing in at Puslinch.[^2] Every letter of [Mary](/person/1626)’s tells of greater weakness than the last, and I hardly think there can be any rally. It is like watching an old tree come down after it has sheltered one all ones life. [Arty](/person/1607) has just brought me my letters from Winchester, and here is one from Kate herself. Only think of her being out once more. How wonderful it is! I wonder if she will get to you.
your affecte cousin

C M Yonge


[^2]: CMY\'s uncle the Rev. [John Yonge](/person/1623) of Puslinch was in poor health and died on 23 August 1877.
