---
id: 2611
title: To Alexander Macmillan
iso-date: '1877-11-22'
display-date: Novr 22nd 1877
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 40-41'
---

My dear [Mr Macmillan](/person/939)
What I have by me in the way of authorities are the [Universal History](/organisation/139) Lady Calcott’s in English and in Spanish a life of the Cid - Perez de Hyta (whence Washington Irving took his material, but which is only romance) and old Madiema - who is alarming - as he hardly ever has a paragraph, and when he does put a date, does not use figures![^2]
I have picked out a useful list of books mostly French from the [London Library](/organisation/29) and if they will take the trouble to find them for me, I shall do well but I sometimes think they don’t choose to hunt up an insignificant book out of date for a person in the country. If I do not get the important ones, I will write to you about them
Yes, Longfellow does fall later than my period for I must end with Boabdil’s last look at Spain
I must try to work history and romance side by side - and I think I can keep within the bounds

Yours sincerely

C M Yonge


[^2]: The authorities relate to her research on [The Story of the Christians and the Moors in Spain](/book/126). She refers to Washington Irving\'s The Alhambra. The Spanish life of the Cid was possibly Rodrigo Diaz de Bivar, Chronica del famoso cauallero Cid Ruydiez Campeador (Burgos: 1593), but the word which looks like Madiema has not been identified.
