---
id: 2616
title: To Christabel Rose Coleridge
iso-date: '1877-12-29'
display-date: Decr 29th 1877
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)

Thank you for your pretty card of arum lilies, I suppose they are decking the Church with them in the southern hemisphere I am ashamed not to send you one – a card I mean not a lily, but I got fewer than usual this year and have pretty much disposed of them - I suppose your decorations were made agreeable this year by the splendid crop of holly berries We have had a very pleasant evening – or rather night of private theatricals at Hursley Park. They had Goldsmith’s real play of the Goodnatured man, and it went off with great spirit the Heathcotes and Wilsons all act so well[^2] The last thing was a charming little piece bringing out the likeness of the twins – who conspire (as Breton peasant girls) to ?tire down a fisher man who thinks both are one. That little Albrook schoolmistress goes on well, but she goes home to Southampton every Saturday. I don’t know anything about [Mr Sloggett](/person/2314)’s womenkind but I like himself he is [SPG](/organisation/41) secretary and has been an Indian chaplain, Low Church but just like a picture of a clergyman in the good little books of 20 years ago. I don’t know much about Hyde[^3] I hope to fit Fernando all into this volume That book of [Mrs Charles Martin](/person/968)s ‘An Old looking glass’ is perfectly admirable for servants. Seely publishes it.[^4]

with New Year’s wishes to you and Cherry[^5]
your affectionate

C M Yonge


[^2]: The actors were the children of [Sir William Heathcote](/person/669) and the [Rev. R. F. Wilson](/person/1541).
[^3]: The Rev. Charles Sloggett was Vicar of St. Bartholomew, Hyde, Winchester. He had a wife and five children.
[^4]: Maria Louisa Charlesworth, The Old Looking-Glass, or, Mrs Dorothy Cope’s Recollections of Service (London Seeley 1878 [1877]). Perhaps it had been recommended by Dora Frances Moberly (1841-1926) who had married the Rev. Charles Martin (1840-1910) in 1869.
[^5]: \'Cherry\' seems to have been the novel Coleridge was working on, subsequently published as An English Squire
