---
id: 2634
title: To Christabel Rose Coleridge
date: '1878-06-17'
display-date: June 17th 1878
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
Cherry is very satisfactory.

The only thing I was not prepared for was Roland’s death, and Dick’s keeping the property I expect he married Nettie after all, though it is quite right not to say so. I like the contrast between Cherry’s feelings in the two illnesses very much, it is rather those of the rest of the family that I thought in danger of repetition.

Miss Seyton I think good, and Alvar's making up with Virginia I like I hope [Macmillan](/person/939) will take it. I do not see why the pupil teacher story should not do as a Blue Bell.[^2] [Mine](/book/125) is related by a spinster with a spine who was critic to a Society of nine girls (specified) There is to be an inundation in it and I shall marry up three at the end, so I hope it will have incidents enough.

Our poor pupil teachers are in the final tug of preparation.

They go to Salisbury the first Monday in July, and worked all through Whitsunweek enough to addle their brains[^3] The [coming school master](/person/513) is reported to be an excellent Churchman. I hope he won’t be too good a one and scare the parish Remember me to my exGoslings[^4]
your affectionate

C M Yonge
I never said how glad I am of the little daughter[^5] I hope indeed she will thrive


[^1]: Envelope addressed to \'Miss C R Coleridge/ The Old House/ Market Lavington/ Devizes\' and postmarked 18 June 1878.
[^2]: CMY evidently refers to two projected stories by Coleridge, the novel about Alvar, which she hoped Macmillan would publish and which was published as An English Squire (London: Sampson Low 1881); and a novel about a pupil teacher.

Coleridge seems to have suggested that Marcus Ward might be unwilling to include the latter in his Bluebell series because its plot resembled too closely that of CMY\'s The Disturbing Element.
[^3]: The diocesan teacher training school was in Salisbury, and the pupil teachers at Otterbourne School, [Alice Misselbrook](/person/1257) and [Harriet Godwin](/person/2316), in whom CMY took a close interest, were examined there.
[^4]: [Jane Pearson](/person/1161) and her sister, with whom Coleridge was staying at Market Lavington.
[^5]: Margaret Eulalia Coleridge (6 June 1878-1960), daughter of Coleridge\'s brother Ernest Hartley Coleridge.
