---
id: 2637
title: To the Hon. Sophia Matilda Palmer?
date: '1878-08-20'
display-date: Aug 20th 1878
from-name: Charlotte Mary Yonge
from-address: Manor House Ottery S-Mary
to-name: To the Hon. Sophia Matilda Palmer?
manuscript-location: 'MS Bodleian Library, Oxford: Ms. Eng. lett. e.116 ff 180-1.'
---

Dear [Miss Palmer](/person/1133)
I hope [Lady Laura Hampton](/person/619) will not mind waiting a fortnight or so, for I am as you see in Devonshire and I can hardly manage to look at them till I come home, where they are waiting for me. I have however had a series of poems on the Collects in the Monthly Packet, and I hardly know how I could begin another.[^1]
I came here yesterday and found [Mildred](/person/17) pretty well, but [her father](/person/343) very poorly though he seemed to be getting better[^2] The chimes of the clock are sounding pleasantly as I write

Yours sincerely

C M Yonge


[^2]: Lady Laura Elizabeth (Phipps) Hampton, daughter of the 2nd Marquess of Normanby, married (1868) John Vivian Hampton (1835-1890). A series of \'Sonnets from the Collects\' by Horatia Elder had been published in MP in 1865-7.

The letter is evidently to one of the daughters of Roundell Palmer, 1st Earl of Selborne, who was a friend of the Coleridges, but if it is correctly dated, it cannot be addressed to his daughter Laura, who had married George Ridding in October 1876, but is more likely to be to her sister Sophia, who was a friend of Lady Laura Hampton (Laura Ridding, Sophia Matilda Palmer, 66-7).
