---
id: 2647
title: To Christabel Rose Coleridge
date: '1878-11-06'
display-date: Novr 6th [1878?]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels
---

My dear [Christabel](/person/329)
You must take care about the law of the thing for if Alvar has been subpoenad as a witness Cherry’s appearing would not save him from a terrible scrape.[^1] It could be only at the examination before a magistrate at first.

The Spanish indifference to doing good to one’s neighbour might come out well I wonder whether he ever could come to be good for much I should like to give hopes of the place descending to Jack.
I like Miss Bramstons Snowball Society most particularly it is a capital story (What a malicious blot) Decr 1st is the day of examining for our pupil teachers and senior scholars and everybody is vigorous.

yours affectionately

C M Yonge
The 3 brothers is very pretty.[^3]


[^1]: Black-edged paper.
[^2]: These are characters in Coleridge\'s novel An English Squire.
[^3]: CMY may perhaps refer here to The Three brothers and Other Tales collected by the Brothers Grimm with illustrations by E.H.

Wehnert (London: Routledge 1879), though other explanations are possible.
