---
id: 2651
title: To Alexander Macmillan
date: '1878-11-01'
display-date: Novr 22d 1878
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 72-73'
---

My dear [Mr Macmillan](/person/939)
Very hearty thanks for your kind letter, I will thankfully correct my own careless blunders, of which I know three. I have sent to the [London Library](/organisation/29) for one or two of the authorities but ‘Dahn’s great work’ is not there at all, unless it is more recent than my catalogue, and I don’t think I could properly understand it if I had it[^1]
I will keep to the old lines of the ordinary histories and only correct what I am ashamed of now I see it.
I have sent for Dozy who writes in French and I hope I may there find what [Mrs Ward](/person/1467) means by Count Julian being a Byzantine commander, which interests me apart from the history as I have made it.
I hope in a few days to have entirely finished the [Scripture readings](/book/129)
With many thanks

Yours sincerely

C M Yonge
I don’t generally care about criticism when I am quite sure that it is only deserved by what I cannot help.


[^1]: This relates to the unkind review by Mary Augusta Ward of CMY\'s [The Christians and the Moors in Spain](/book/126).
[^2]: Felix Dahn, Die Könige der Germanen : Das Wesen des ältesten Königthums der germanischen Stämme und seine Geschichte bis auf die Feudalzeit 6 vols (Munich, Wurzburg: 1861, 1866, 1871).

The quotation is from Mary Ward’s Academy review of The Christians and the Moors in Spain.
