---
id: 2657
title: To Alexander Macmillan
date: '1879-01-01'
display-date: Jan 1st 1879
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 77-78'
---

Dear [Mr Macmillan](/person/939)
I am today sending [Clay](/organisation/173) the last copy for the [Scripture Readings](/book/129), I suppose we may consider now whether the five volumes can be made more compact and profitable, and I hope Clay will finish off the present one quickly.

Thanks for sending all these notices of the [Primer](/book/353).[^1] It is odd I thought I had written up to MacMahon’s election, but perhaps [Mr Green](/person/582) thought the siege made a better conclusion - and that I could not grasp it.
I hope soon to send the Spanish corrections[^2] As a matter of curiosity is [Mr Freeman](/person/523) still mending up [that other unfortunate history](/book/99), I have kept all the proofs of mine to compare[?].[^3]
With all good new year’s wishes

Yours sincerely

C M Yonge
Thanks for the primers.

English composition is very good.

Though I wonder at the condemnation of pell mell and topsy turvey.


[^1]: CMY\'s History of France (1878), one of the History Primer series edited by the historian John Richard Green (1837-1883).

Marie-Edmé-Patrice-Maurice de MacMahon (1808-1893) was elected President of France in 1873.
[^2]: These were the corrections to her [Story of the Christians and the Moors in Spain](/book/126) pointed out in a harsh review by Mary Augusta Ward.
