---
id: 2679
title: To Alexander Macmillan
iso-date: '1879-07-09'
display-date: July 9th 1879
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Alexander Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 97-98'
---

Dear [Mr Macmillan](/person/939)
Here is the list of materials for [the little Christmas book](/book/135).
The MS, and the clipping come herewith the four others must be sent by rail in the books in which they appeared.[^1] The Autobiography of Patty Applecheeks came out in an American paper, and my copy of it has been lost, but I am sending to Philadelphia to see whether I can recover it. The Wedding cake (a story of a ridiculous mistake) I also sent to America, and was paid for it, but it has never appeared and I am writing to beg that it may. Both these are of the length of the Phantom
If a little more were needed, I could write one more. There are two stories, one called the Banks of the Leamy, which [Warne](/person/1433) bought for a Christmas annual, and [Sea Spleenwort](/book/46), which [Groombridge](/organisation/148) had, which it is a pity not to recover and unite with the rest, but I cannot afford to advance anything to buy back the copy rights.
What an excellent life of Burns Principal Sharp’s is. He has some qualities (Sharp I mean superior to any writer of the day. I am much tempted to write an answer to the Rights of Woman paper, but I don’t know if [Mr Grove](/person/588) would accept my view of the question, and defence of the poor mothers and chaperons[^1]

Yours sincerely

C M Yonge


[^1]: She was assembling previously published stories which appeared as Bye-Words (1880).
