---
id: 2691
title: To the Reverend Canon William Parsons Warburton
iso-date: '1879-07-04'
display-date: July 4th [1879 or later]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To the Reverend Canon William Parsons Warburton
manuscript-location: MS Girton College Cambridge, Yonge VII 2
---

My dear [Canon Warburton](/person/1466)
Thank you for the sight of the papers. The plan is just what I have wished for so long- and those Occasional papers are excellent.
I wonder how young the people are whom the Elementary questions are supposed to reach. As I see in the report that only 9 sets of answers are come in, I am afraid they are not meant for children below Confirmation age, school room and school boys and girls, who might most wholesomely use them for a Sunday study. Do you know how far this is intended or there is any possibility of working for them likewise? I shall be delighted to do anything that I can to assist.
I wonder if it would be well for me to qualify by going in for the Bishops’s Certificate. I have often thought of doing so, but as nobody else here did so, my ‘clergy’ did not seem to think it worth while to promote it.[^1] After your first examination at Hursley, [Mr Keble](/person/798)came in and said to me ‘Do you know I am convinced examinations are a very good thing’ and then in that droll way he had ‘I’ll tell you! I am ashamed to say, I never was examined for Ordination!’

Yours sincerely

C M Yonge


[^1]: The \'Bishop\'s Certificates\' related to the Diocesan inspection of Church schools. They seem to have functioned both as religious knowledge diplomas for schoolchildren and also as qualifications for teachers. This letter must date from after Warburton\'s appointment to an honorary canonry of Winchester in February 1879.
