---
id: 2726
title: To Ann Maria Carter Smith
iso-date: '1881-05-21'
display-date: May 21st [1881]
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1881/ 5
---

My dear [Miss Smith](/person/263)
Thank you for the end of your story which I like very much. Here and there you may have been a little discursive, and possibly abridgement may find out some bits. About the incongruity of wreaths with the feelings of the last generation I quite agree with you. We /elder ones\ felt it so with [my dear old uncle](/person/1623) who we knew held it as a frivolity, and yet one could not disappoint young ones who did those things in all love and piety.[^2] Still I am glad of the custom provided the flowers are real and kept tidy. It soothes at the time, and really does keep up the sense of connection. When the /school\ children go to ‘put a cross on their baby’s grave’ - a baby they may never have seen, I think it must keep up the family sense of oneness- and I can’t despise it as my elders did.
I am afraid I cannot rectify the Dickens but something no doubt will remind one of us before it is printed. Is not your Duke’s title too like Trolloppes Duke of Omnium[^3] If he must have a title expressed, might not Swallowfield answer the purpose? I was quite surprised to find Sally Armigils’s love, and very thankful that you did not kill the father outright

yours sincerely

C M Yonge


[^2]: The word \'all\' deleted.
[^3]: The Duke of Omnium is a character in Trollope\'s Dr. Thorne (1858) and later novels. A character called the Duke of Swallowfield appears in Carter Smith\'s tale \'A Little Less than Kin and More than Kind\', which was being serialized in MP.
