---
id: 2781
title: To James Sutherland Cotton
iso-date: '1883-10-19'
display-date: Oct 19th 1883
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To James Sutherland Cotton
manuscript-location: 'MS UCLA: collection 100: box 95'
---

[Sir](/person/2354),
Allow me to thank you for your notice of my recent [volume](/book/174) of ‘Cameos of English history.’ But let me observe that Freitag derives the word sometimes spelt Lanzknechts as ‘Landsknechts’—free men of the country.
Miss Strickland, in her [Life of Anne of Denmark](/organisation/157), states that, though Oslo as Upslo afterwards had a Cathedral and was known as Christiana, both James’s letters, and the contemporary chroniclers describe the place as a small dreary village. I have no original authority at hand, but Miss Strickland evidently looked into the matter; and as there was another performance of the ceremony at Kronenberg, it is plain that Oslo could not then have been considered to possess the National Cathedral.
The conversations between Ballard and his fellows are not from my imagination but from the evidence laid before Elizabeth, and whether true or not, are certainly historical.
I remain
Yours &c

C M Yonge
