---
id: 2793
title: To George Lillie Craik
date: '1884-07-10'
display-date: July 10th 1884
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To George Lillie Craik
manuscript-location: 'MS British Library Add MSS 54921: 128-9:'
---

Dear [Mr Craik](/person/379)

I shall have a child’s book called ‘[The Two Sides of the Shield](/book/184)' ready to come out about next Easter as it will be finished in the [Monthly Packet](/periodical/52) about that time.

I feel as if I ought to express my great regret that there has been such a story as the Author of Beltraffio in the [Eng Illustrated Magazine](/periodical/68). [^1]

Surely it will only tend to make sceptically inclined people averse from devout faith - of which they will take Mrs Ambient as a representative and even apart from that most serious evil, it is terribly painful.

Please forgive me for speaking out but I am shocked and grieved and am inclined to cut out the story before lending it. I was sorry for the poem about the man dying without prayer but that seemed an accident, and I am more sorry that it is followed up with this[^2]

Yours truly

C M Yonge


[^1]: Henry James’s story ‘The Author of “Beltraffio”’ appeared in Macmillan’s new periodical, the English Illustrated Magazine 1 (June-July 1884), alongside CMY\'s [‘The Armourer’s ‘Prentices’](/book/171).

Its central character is an English novelist, Mark Ambient, at loggerheads with his wife who ‘thinks a work of art ought to have a \"purpose”\' while he takes a more aesthetic view.

She lets their child die so he should not be contaminated by his father’s works.
[^2]: The same issue of the magazine also included George du Maurier, ‘Der Tod als Freund: A Poem. (from the French of Madame Necker)’.
