---
id: 2811
title: To an Unknown Woman
date: '1885-06-25'
display-date: June 25th 1885
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To an Unknown Woman
manuscript-location: 'MS Bodleian Library, Oxford: 30424 . . . . fol 69 Autograph
  d.4.'
---

Dear Madam
Will you send the Altar Cloth addressed to the [Bishop of Melanesia](/person/1296) at the Close, Lichfield.[^1] He thinks he will probably use it in Norfolk island.[^2]
You had better write to him when you send it

Yours truly

C M Yonge


[^1]: John Richardson Selwyn (1844-98), Bishop of Melanesia 1877-1890.

His father, George Augustus Selwyn (1809-78), the first bishop of New Zealand, had been Bishop of Lichfield from 1868 to 1878, and his widowed mother lived at 18 the Close in 1891.
[^2]: The [Melanesian Mission](/organisation/30) had moved its base from New Zealand to Norfolk Island in 1867.

Accounts of the opening of the memorial chapel to Bishop Patteson in 1881 describe another, different, altar cloth embroidered by his cousin [Paulina Martyn](/person/973): \'The cloth of the Holy Table was presented by Miss Martyn, a relative of Bishop Patteson, and is of the richest work; it is of dark crimson velvet and silk.

In the centre is a gold cross surmounted by a crown.

On either side are lilies in the martyr\'s palm.

On the super frontal are worked in large gold letters, the words in Mota--
LOG RANOGA GOD VAVO TUKA (Glory to God in the highest).\' A Week at St.

Barnabas\', Norfolk Island (Sydney: Fuller 1881).
