---
id: 2812
title: To an Unknown Person
iso-date: '1885-09-02'
display-date: '[September 1885?]'
from-name: Charlotte Mary Yonge
to-name: To an Unknown Person
manuscript-location: MS Girton College Cambridge, Yonge IX 4
---

. . . August and very dreary it was to see the beautiful rooms at Heaths Court with no mistress. I still believe that there will be a great awakening from the present blindness, and [Mary](/person/351) . . .
I think Winchester is a rock that binds its limpets fast - not a good simile either for the limpets do go off, only perhaps it is their affections that stay there. I have not near so much to care about there now, as in old times, only perhaps the dear Salisbury people may come back there.[^3] I believe the elders wish it, but the younger feel more present interest where they are.
I am very sorry you are lame - but I dare say you have plenty of work to do from your sofa. I wish you could see our woods the autumn tints are wonderful this year - and the Virginian creepers are gorgeous
Yours very sincerely

C M Yonge


[^3]: The widow and daughters of George Moberly, headmaster of Winchester College 1835-1866, and Bishop of Salisbury from 1869.
