---
id: 2814
title: To Constance Frederica Gordon Cumming
date: '1885-09-19'
display-date: Sept 19th [1885]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Constance Frederica Gordon Cumming
manuscript-location: MS Princeton University, Parrish Collection
---

My dear [Miss Gordon Cumming](/person/571)
Thank you so very much for the photos, I am very glad to have it. I am afraid this is no return, as it was taken from a not very good picture. [Bassano’](/person/2361)s negatives are used up and he has been intreating me to come again- but I have not been in London for two years.[^1] If ever we are there at the same time, I do hope we may get beyond photographs.

Yes, I look at the Mungoose & consider of him, but I am afraid I must finish off other things before Christmas which have got into type by a sort of mistake for the Christmas number.[^2] I had a scolding about it from the publisher and must appease him.

Yours sincerely

C M Yonge


[^1]: Alexander Bassano (1829-1913), a London photographer.
[^2]: C. F.

Gordon Cumming, ‘The Rabbit Plague in Australasia’ MP 3s 12 (July 1886), 58-69, discusses the possibility that the introduction of the mongoose might control the rabbits.
