---
id: 2822
title: To Gertrude Mary Ireland Blackburne
date: '1885-12-01'
display-date: '[December 1885?]'
from-name: Charlotte Mary Yonge
to-name: To Gertrude Mary Ireland Blackburne
manuscript-location: MS location unknown.  Printed in Romanes, [[otherbook:241]<i>Appreciation</i>],
  187-8.
---

[To [Gertrude Mary Ireland Blackburne](/person/160)]I could not get time to answer your last letter immediately, as I have been very busy in various ways, and, as you may suppose, much disappointed in the elections, in proportion no doubt to your satisfaction.[^1] But I see no safety now, humanly speaking, for the Church, or anything else that is worth preserving, unless the moderate Liberals will make a stand, which I see no sign of their intending.

You say Mr. - disapproves of the State assisting in religious education.

We have come to a pass in which no one expects it to do so; all we ask is that it should not try to stifle religious education, and I think no one can deny that the Council of Education do so as much as they dare, and that the strong and avowed desire is to prevent the clergy from giving a Church education even to their own children in the religious hour, and that if free education comes in, it will be at the cost of religious education.

As to the colonies, I think representation of them here would be a very good thing. I suppose the long distances were the original hindrance.
I believe Conservatives would be as glad as anyone to facilitate (but not compel) transfer of land. I can't understand how honest men could be content to owe their election to the deceits put about. I don't know if the stories were true about taking a halter to the poll to bring home a cow, but I do know of a man who expected a slice of the squire's grounds, of belief that the Conservatives would put a penny on the loaf, of free schools being taken to mean being free not to send your children to school, and a list of Mr.

Strachey's promises in the paper to-day is a strange thing.[^2] Nor will [Gladstone](/person/1653) denounce attempts on the Church.

It is only 'not just yet.'[^3] You say not this century!

Poor comfort when there are only fourteen years more to come.

Alas!

Alas! I feel they have given up to destruction all that is precious and holy.

yours sincerely
C. M.

Yonge


[^1]: The Liberal party won a majority at the election in December 1885.
[^2]: Perhaps Edward Strachey (1858-1936), created (1911) 1st Lord Strachie, Liberal politician, who contested North Somerset in 1885 and Plymouth in 1886, both unsuccessfully.
[^3]: Gladstone\'s election manifesto, published in The Times (19 Sept 1885, 8), contained, in a passage admitting the possibility of the disestablishment of the Church of England, the words: \'I cannot forecast the dim and distant courses of the future.\'
