---
id: 2836
title: To George Lillie Craik
iso-date: '1886-06-25'
display-date: June 25 [1886]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To George Lillie Craik
manuscript-location: 'MS British Library Add MSS 54921: 151-2:'
---

Dear [Mr Craik](/person/379)
I should like to find out how much the lady cares who urged me to write before answering. Whether I will go on with this personal history, and whether time is still important, for it was the hurry that oppressed me.[^1]
The copyright of [Householders](/book/357) and [Thoughts on Pictures](/book/301) is mine.
I quite see that all ought not to come too much together, but I do think Householders is worth the having soon, for children by the sea get interested in shells, and I never saw a book meant for them about conchology that was not utter nonsense.
But no doubt this wants touching up.
There are a good many stories by good authors in that Magnet series and it is a pity they should be all lost.
Even as I regret Miss Keary’s Letters on Egypt. Also a story of hers published hitherto only in [Aunt Judy’s Magazine](/periodical/54) about some capital school boys.[^2] I wish you and [her sister](/person/794)would revive that!

Yours truly

C M Yonge


[^1]: This seems to be a reference to some autobiographical writings, perhaps those reprinted by Coleridge, [Life](/organisation/40) 1-119, or those subsequently printed as [\'A Real Childhood\'](/periodical/254) in Mothers in Council (1892-3).
[^2]: Perhaps \'The Cousins and their Friends\' Aunt Judy\'s Magazine (May 1866-December 1867).
