---
id: 2838
title: To George Lillie Craik
iso-date: '1886-07-24'
display-date: July 24th [1886]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To George Lillie Craik
manuscript-location: MS British Library Add MSS 54921:155-6
---

Dear [Mr Craik](/person/379)
I have just heard to my consternation that there is a book called A Quest of Ulysses, a novel published a year or two ago. [^1] Is it too late to change the name to [A Modern Telemachus](/book/185)?
I have I hope got upon the scent of the original French narrative, so I must keep the preface waiting till I find whether I can get it.[^2]
The [National Society](/organisation/32) think the [book about the Queen](/book/189) not in their line!
Since [Mr Comyns Carr](/person/2364)’s application Sir Henry Ponsonby wrote to me hoping I would not put in the current legends of the Queen’s early history.[^3] I replied by explaining the state of things and saying I wished anyone could be authorised to look at the proofs, and say which is true, also asking leave to dedicate it to the Queen. This was a fortnight ago, but I have had no answer and I suppose this is a bad time for expecting one. A days work more will finish the thing. Will you still take it, and make it as cheap as you conveniently can.

Yours truly

C M Yonge


[^1]: Joseph Hatton, A Modern Ulysses: Being the life, loves, adventures, and strange experiences of Horace Durand 3 vols (London: Chapman & Hall 1883).
[^2]: As is explained in the preface to A Modern Telemachus, CMY had based her story on one in Archibald Duncan\'s compilation of shipwreck tales, The Mariner\'s Chronicle (1804). She had subsequently located a copy of his authority, Jean Baptiste de La Faye Voyage pour la redemption des captifs aux royaumes d\'Alger et de Tunis, fait en 1720 (1721).
[^3]: Sir Henry Ponsonby (1825-1895) was private secretary to Queen Victoria 1870-95. Joseph Comyns Carr was editor of the English Illustrated Magazine in which it had been proposed to publish Victorian Half-Century.
