---
id: 2844
title: To Isabella Margaretta Elizabeth Heathcote
date: '1886-11-04'
display-date: Novr 4th [1886]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Isabella Margaretta Elizabeth Heathcote
manuscript-location: MS Winchester City Council, Historic Resources Centre, LH3802
---

My dear [Bella](/person/1690)
[Gertrude](/person/1462) begs me to write and enquire how [Mr Walpole](/person/1432) is. [^1] I am afraid it takes a long time to recover from anything so exhausting as nose bleeding.

Our [Bishop](/person/213) however seems quite to have done so - he has got happily through this time of hard work at the Diocesan Conference We had a very interesting meeting afterwards at the Deanery about Women’s Work in the Diocese - especially what the Deaconesses at Portsea have to do and the strange things they meet with.

Fancy a woman doubting about having her child baptised for fear it should become an Archangel and have to run about doing the messages for all the others. [Lady Heathcote](/person/665) was here today looking very well, at a meeting of this Habitation? of the [Primrose League](/organisation/255).

Gertrude is tolerable today, having visits from [Miss Coulthard](/person/371) who is at the other house. I wonder who the Lady Valeria’s author is. A Moberly seems as if one should know, but then people do so assume names.[^2] It is a pretty book but for one thing
your affectionate

C M Yonge


[^1]: Isabella Heathcote’s father, Spencer Horatio Walpole (1806-1898), M.P. for Cambridge University (1856-1882).
[^2]: A.Moberly, Lady Valeria (1886) was advertised as the work of Major A.

Moberly, and can probably be safely attributed to Major [Alfred Moberly](/person/1860), nephew of Dr George Moberly.
