---
id: 2845
title: To Elizabeth Barnett
date: '1886-11-12'
display-date: November 12. [1886]
from-name: Charlotte Mary Yonge
from-address: Elderfield,
to-name: To Elizabeth Barnett
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  306.
---

My dear [Lizzie](/person/113)-
. . .

Yes, I saw the [Spectator](/periodical/180) on [Chantry House](/book/186), but indeed I did not put in the ghost for the sake of variety or sensation, but to work out my own belief and theory. I could tell you things I quite believe that chime with it.

One I must tell, not that it is a ghost probably, it is so curious.

The poor people in the Torquay outskirts think a thing walks in the few remaining woods of the Abbey which they call a Widdrington.[^1] Now [Miss Roberts](/person/1244) has hunted up that the last Abbot was accused before Henry VIII. of having murdered a monk named Widdrington, whom however he produced safe and sound.

Don't you think the live man must have been seen after he was thought dead and so left his name? -
Your most affectionate
C. M. YONGE.


[^1]: Christabel Coleridge, who lived many years in Torquay, commented ‘I have never come across this belief.’ A similar story is told of a fourteenth-century abbot by J. T.

White, History of Torquay (1878), 26, but the allegedly murdered man\'s name was Hastings.
