---
id: 2863
title: To Frances Awdry
iso-date: '1887-10-01'
display-date: Oct 22d [1887?]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Frances Awdry
manuscript-location: MS Princeton University, Parrish Collection
---

My dear [Frances](/person/82)
All I know about Juliana Coningsby is in the [Cameo](/book/213)of December 1886.[^2] I got it out of Carte’s history also Knights, and they both took it from the King’s own account which Pepys wrote down at the time. The adventures were really more curious than Jane Lane’s and I have always wondered whether there were anything not told which prevented them from being made more of.[^2] But Carte is too old to mince matters, and nobody would know if there were anything amiss about her, so I think she is safe. She took Charles from Trent to Charmouth and she had a pension on his restoration like Jane Lane. I am glad George Harris is all right again.[^3] Six families in Winchester started scarlet fever the same day, it was all traced to one dairy, and nobody else has caught it, and they are all well again
Your affectionate

C M Yonge
Don’t set up a story concerned with the rejoicings for the 7 Bishops, and the flight of Mary Beatrice[^4]


[^2]: At another stage of his escape Charles pretended to be a servant to Jane Lane.
[^3]: Perhaps [George Montagu Harris](/person/2340), the son of CMY\'s cousin George Collyer Harris (1833-1874).
[^4]: No doubt because she was herself planning [A Reputed Changeling](/book/205) (1889).
