---
id: 2870
title: To Elizabeth Barnett
date: '1887-11-19'
display-date: November 19, 1887
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Elizabeth Barnett
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  310-11.
---

My dear [Lizzie](/person/113)

I trust you will neither find London in a riot or in a fog![^1] I came through it yesterday, and could not see sixpences from half-sovereigns till I was over Waterloo Bridge, when it became less dense.

I was coming from Hatfield, where I have had three very pleasant days, but the first was so beset with fog that I could not see nearly as much of the outside as I could have wished, though I paid my respects to the oak Elizabeth was sitting under when the news came that her sister was all but dead.[^2] Relic-hunters have all but killed it, and it has only one spray at the top.

It is bolstered up with concrete, and fenced round to keep them off.

There is another, much older, mentioned in Domesday, quite well though shaggy, because it has been let alone.

Is it not odd, when the Queen and Prince Albert were there just after they were married each planted an oak - his has died, and hers has thriven? I brought home an acorn of the Queen's.

The very old oaks bear acorns, but they won't grow.

The best thing I saw was the Little Gidding book made for King Charles, Dutch engravings cut out, and the chapters they belong to pasted in below, in most beautiful condition. [Mr.

Maxwell Lyte](/person/2375) of the Record Office was there, so that it was a grand opportunity of having MSS. and letters explained.

All Robert Cecil's commonplace book is there, and most curious letters of course.

I wonder if a fog will be good for that mob.

The anxiety seems to be that there are a good many foreign socialists about, who really do know how to do mischief, and will .

One curious person to meet was the Italian ambassador, [Count Corti](/person/2376).[^3] He told me he had tried living on his estate in Lombardy, but could only stand ten days of country life!

Poor Crown Prince!

He could only speak in a whisper at the Jubilee.[^4] I daresay it will be warmer soon, but I wish you were safe at Lincoln.

Your affectionate
C. M.

Yonge


[^1]: \'Bloody Sunday\', the Trafalgar Square riot of 13 November 1887.
[^2]: Coleridge states that CMY was working on Unknown to History, her historical novel about the captivity of Mary, Queen of Scots, and had gone to look at Elizabethan records at Hatfield; however, as it was published in 1882, if such a visit took place it must have been earlier.
[^4]: Queen Victoria\'s Golden Jubilee, 1887.

Kronprinz Wilhelm of Germany (1859-1941), her eldest grandson, succeeded his father as Kaiser on 15 June 1888.
