---
id: 2878
title: To Anne Elizabeth Mary Anderson Morshead
date: '1888-03-17'
display-date: March 17th 1888
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Anne Elizabeth Mary Anderson Morshead
manuscript-location: MS Miss Barbara Dennis/4
---

My dear [Mary](/person/28)
I am very glad you have this respite, it is so much better for you all.

And you must be glad of time to put things in order, and see about [Sister Sarah](/person/466).[^2] I send the answer to the Febry question as no doubt you meant to keep them all together.[^3] I have put in your apology and I cant put in the Jany class list now- as the printers must be early this month they tell me, and they were kept waiting by a mistake last time I am just in from the Inspection, two days of it! [Mr Brock](/person/201)’s [father](/person/2112) is so ill that there is much fear of his being called away in Holy Week or before it.
I have a whole curious account of the skirmish on Clifton Moor, in the ’45 sent me which I would send you if you were likely to have time for it or mind
your affectionate

C M Yonge


[^1]: Endorsed in pencil ‘addressed to her cousin Miss Anderson Morshead\'.
[^2]: Mary Anderson Morshead was assistant matron of an industrial school for girls in Andover, whose matron was Sarah Joan Easton (b.1836/7), who may be referred to here.
[^3]: Mary Anderson Morshead, as ‘Bog Oak’, ran the Church History Society in MP..
