---
id: 2886
title: To Anne Sturges Bourne
date: '1888-06-01'
display-date: June 22d [1888]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Anne Sturges Bourne
manuscript-location: MS Miss Barbara Dennis/5
---

My dear [Miss Bourne](/person/1379)
Thank you, I wish I saw my way, but I have been five weeks in Devonshire, and I cannot go forth again so soon, as there is a great deal on hand, and lee way to make up before another holiday We have to hunt for an Infant School mistress as our very excellent one marries [the master](/person/1256) and retires.[^1] It is good for him, but bad for us.

We must get an ex p t - I believe they are plenty and cheap.[^2] Yes, Miss Marjory’s Ways are very clever.

Have you had the Dragon of the North? - It is Fouqué like and yet true - and very good Bernard and Marcia is good- so is A Double Marriage, but they are both rather lengthy.[^3] I don’t like Amélie’s last ‘Joan Vellacott’ - it is sound, of course, and there is a beautiful character in it, but she is barbarously killed, and her husband is deluded by a very horrid girl.

Married troubles of that sort are not nice to write about.

Dorothy Osborne’s letters are wonderful. I cannot think how she got educated.

If she had had a Mme de Grignan, she would have been a Mme de Sevigné It is funny to find her discussing the characters in the Grand Cyrus &c just as we do modern novels. I wish I could come to tell you about my visit to the [Bishop of Bedford](/person/722), and seeing the People’s Palace - also the reigning story, but I must keep at home for the present
your affectionate

C M Yonge


[^1]: [Alice Misselbrook](/person/1257) the mistress of Otterbourne Girls\' School, married Alfred Rolfe, who taught the boys.
[^2]: An ex-pupil-teacher.
[^3]: CMY probably refers here to Eliza Stephenson, A Double Wedding (1888).
