---
id: 2890
title: To Anne Sturges Bourne
date: '1888-09-05'
display-date: Sept 5th 1888
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Anne Sturges Bourne
manuscript-location: MS Miss Barbara Dennis/6
---

My dear [Miss Bourne](/person/1379)
Indeed I would gladly if I could, but months ago [Professor Freeman ](/person/523)asked me to come and see Hannah Mores villages, and hear his recollections of her, and the time has fixed itself for next week, and after that comes harvest - and dedication feasts - and Mission Guild meeting, and I am afraid I cannot do it though I am very sorry not to see you again this year before you are shut up for the winter.

If you were well enough I might manage a day or two later.

My [National Society ](/organisation/32)story I fancy you will like being the history of a young school mistress and pupil teachers.[^2] We have just had a grand wedding here of [our master ](/person/1256)and [Alice Misselbrook ](/person/1257)after being infant mistress nine years.[^3] She gives up which is better for him than for us and we are expecting her successor.

Of worthy books, you should read the Dragon of the North.

It is like a possible Fouqué
your affectionate

C M Yonge


[^1]: Silurian envelope addressed to \'Miss Sturges Bourne/ Crookham Knole/ Farnham\' and postmarked Winchester 5 September 1888 and Farnham 6 September 1888.
[^2]: This was CMY\'s [Our New Mistress, or, Changes at Brookfield Earl](/book/198) (London, National Society 1888).
[^3]: Alice Misselbrook, the mistress of Otterbourne Girls\' School, married Alfred Rolfe, who taught the boys.
