---
id: 2935
title: William Crawley Yonge to the Rev. John Yonge, including Charlotte Mary Yonge
  to Anne Yonge
date: '1837-01-01'
display-date: '[?January 1837]'
from-name: Charlotte Mary Yonge
to-name: William Crawley Yonge to the Rev. John Yonge, including Charlotte Mary Yonge
  to Anne Yonge
manuscript-location: MS Plymouth and West Devon Record Office 308/82
---

My dear [John](/person/1623),
Since P?? I have thought a little more about [Northcote](/person/1692)’s application for a reduction and really on second consideration it does seem to be most unreasonable.

Considering the situation, Garden &c I do think that at £70 it is one of the cheapest houses to be found. I am sure I know of none in a come at able situation to be compared to it for cheapness I know that that house in this country would let for £160 or 170.

He might perhaps get a house for £10 a year less in the neighbourhood of Kingsbridge or Two Bridges, but I suppose he is hardly fool enough to go into such a country without roads for the sake of ten pounds. I dined at [Sir Thomas Baring](/person/1693)s last night and wrote the first page of my letter this morning before breakfast.[^1] When I came home Charlotte fancied I had finished it and left space for her so she wrote the scribble which appears on the opposite page
yours affectly [WCY](/person/1631)
[Heathcote](/person/669) dined at Stratton with me so I got him to frank which was handy for [Edmund](/person/322)s letter.[^2]
My dear [Anne](/person/1582)
I ca’nt [sic] say I have much to say but the agreeable news that [Mamma](/person/1606) and [Julian](/person/1624) are a great deal better today and [Graham](/person/321)’s cold was better when he went.

Poor Stumpie was found in the village yesterday morning with his leg broken, but he is going on very well as I believe though it coud not be kept because of its being broken so high up. I hope Edmunds keys arrived in safety he also left behind one of the Stiks and his stick
your very affectionate cousin
CMY


[^1]: Sir Thomas Baring (1772-1848) 2nd Bt., of Stratton Park, which is eight miles north of Winchester.
[^2]: Edmund and Graham Colborne were the schoolboy sons of John Yonge\'s sister Elizabeth, whose husband was currently Lieutenant-Governor of Upper Canada.
