---
id: 2938
title: To Anne Yonge
iso-date: '1838-09-25'
display-date: 25 September 1838
from-name: Charlotte Mary Yonge
to-name: To Anne Yonge
manuscript-location: MS location unknown. Printed in Coleridge, <i>[[otherbook:40]Life]</i>,
  137-139.
---

My dear [Anne](/person/1582)

Though I wrote to you so short a time ago, I cannot let an opportunity pass without writing. I wished for you last Friday, for I think you would have liked our party of pleasure. As it was St.Matthew’s Day, we asked leave out for [Johnnie](/person/1619), [Duke](/person/1599), [Archer](/person/51) and [Charles Wither](/person/1543)at seven o’ clock in the morning.[^1] They came here in a fly, the horses of which were afterwards put on to our close carriage. But I had better tell my own story, for I do not know what was going on at Otterbourne at that time. I have not told you that the occasion of all this set out was to see the first stone of [Ampfield](/place/124) Church laid[^2]. At a quarter past ten Duke and I set off in the fly for [Mr. Keble](/person/798)’s, Duke to take back word at what time Mr. and [Mrs. Keble](/person/795) meant to set off for Ampfield, I to go to church, have my lecture and dine, and a delightful morning I had there. Dinner was over, the gig with Whitethorn, the flea-bitten grey horse, was at the door, and Mr. Keble began to say there was no time to lose. We began to think that [mamma](/person/1606) was not coming for me, so they said they had room for me; so behind in the carriage I went with [Caroline Coxwell](/person/1633), where she and [Alethea](/person/27) made that fine telescope with their bonnets on the Netley Abbey day. We were just settled when the carriage came with mamma, but I stayed where I was, and fine fun Caroline and I had, for we went over the park anyhow, over dells which the post-horses behind looked finely amazed at, and we looked back and laughed. Then we came into Ampfield wood and passed the place where Caroline and I left you and mamma sitting near the great ants’ nest, and we talked of that pleasant day. Then we came into the road and there we found a great assembly of people arriving, three carriages from the park, two carriages of our own, and more from all Hursley. The church is in a beautiful place, where the Hampshire paper says ‘An appropriate service was performed by the Rev. J. Keble.’ Little [Gilbert Heathcote](/person/661) laid the stone, spread the mortar about underneath in fine style, and finally gave the stone three taps with a mallet.[^3] Then came some of the 132nd Psalm, which was exceedingly appropriate, especially the sixth verse, when we looked round and saw the plantations of fir-trees round us[^4]. No sooner was the service finished than [Mr. Fowlie](/person/521)[^5] the steward stooped down and kissed Gilbert, saying ‘Little dear.’ You know when [Julian](/person/1624)[^6] laid our first stone everybody said ‘Pretty dear,’ which made him very angry, so we had a fine laugh at him. In the evening Johnnie and I had some fine games at backgammon, in every one of which he beat. The Confirmation is to be next Monday, and I am very sorry papa will not be at home on that day. I went to Hursley yesterday for the last time before it, and Mr. Keble gave me my ticket.[^7] He is so kind as to promise to go on with me after the Confirmation, which I am very glad of. The church bells are to be put up to-day, and the inside is being painted, paved, and plastered, but the work does not make much show. [Papa](/person/1631) says he wishes the men would employ the time of his absence in drinking all they mean to drink until the church is finished, so [Mr. Wither](/person/1544) is going to give them a supper on Michaelmas Day I believe. Tell Alethea that [Mr. Rudd](/person/1267), the tall man we took the hospital paper to, is dead, and as it was said that he was the handsomest coachman that ever drove to St. James’s, [his wife](/person/1266) thought, I suppose, that he would make a fine skeleton, so she had his grave done two feet deeper than usual that he might not be dug up again, and employed two people to watch him every night; but those people being great poachers spent the night at the river, and left the poor man to his fate.[^8] Poor [Mrs. Moore](/person/1051) has been disappointed of her journey to Bognor, for they were actually on the road, when about Guildford [Mr.Moore](/person/1050) was taken so ill that she was obliged to go back again, and she does not wish to leave town again. He is better now I believe. I had a letter from [Alethea](/person/171) at Heidelbourg the other day. [Aunt Duke](/person/1591) had had some bad headaches for the last few days, which was the only new news to you I suppose. Old Mag has just had his wing cut, which affronts him very much.[^9] Mamma held his beak whilst papa cut his wing. I have now three hundred and ninety-seven dried flowers. I hope your work[^10] will be ready to come by papa as well as [Jane](/person/1616)’s night-cap. Tell [Charles](/person/1601) that Julian is learning Greek and has got as far as ο, η, τό, and can read a line of the Greek Testament without help. A gentleman who has been a good deal in Germany told us the other day that Heidelbourg was a bad town, so I am glad that Aunt Duke lives out of it. I enclose the form that was used at the laying the first stone. Give my love to Jane and [Frances](/person/1605), and tell them that I hope to have a letter from each of them by papa. Mamma will be very glad of her worsted if you can get it for her, and pray send a pair of black purse sliders, for one of those of the beautiful purse, both yellow and black, is broken, though the purse is as good as new.

In the meantime I am, dear Anne,
your very affectionate
Charlotte M. Yonge


[^1]: St.Matthew’s Day is 21 September, presumably a holiday at Winchester School, where Anne’s brothers John Bargus Yonge (1821-1863) and Duke Yonge (1823 -1881) were at school. The other schoolboys were probably Fulbert Archer (1825-1904), a cousin of the Yonges, and Charles Wither (1822-1896), the curate’s youngest brother.
[^2]: Ampfield was a village in the parish of Hursley, and Heathcote had paid for the building of a separate church there.
[^3]: Compare [[cmybook:]The Daisy Chain] (1856), Part 2, Chapter 22, where a child lays the first stone of a church: ‘Gertrude scooped up the mass of mortar, and spread it about with increasing satisfaction . . slowly down creaked the ponderous corner-stone into the bed that she had prepared for it, and, with a good will, she gave three taps on it with her trowel.’
[^4]: Psalm 132, ‘Lord, remember David, and all his afflictions’, was perhaps chosen for the church dedication ceremony because of verse 7: ‘We will go into his tabernacles: we will worship at his footstool’. The sixth verse is: ‘Lo, we heard of it at Ephratah: we found it in the fields of the wood.’
[^5]: Coleridge prints ‘Fowler’ but Heathcote’s steward was William Fowlie (b.1791/2).
[^6]: JBY (1830-1891) had laid the foundation stone of Otterbourne Church in 1838.
[^7]: Keble had prepared her for Confirmation, and the ticket signified that she was worthy to receive the sacrament from the Bishop.
[^8]: Despite the Anatomy Act (1832), permitting physicians and scientists to dissect the bodies of unclaimed paupers, there was evidently still a market in disinterred bodies, especially unusually large ones.
[^9]: A pet magpie.
[^10]: i.e. needlework.
