---
id: 2948
title: To Anne Yonge
iso-date: '1844-11-06'
display-date: Novr 6th 1844
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Anne Yonge
manuscript-location: 'MS West Devon Record Office Acc No 308: 6/11/44'
---

My dear [Anne](/person/1582),
I scarcely expected you would be so kind as to write to me so soon, and I hope it was no great exertion of spirits to you. Such a morning as this is just what one would figure to oneself as the right day for you, and I think I can see both [Puslinch](/place/123) and Newton[^1] this morning. At the moment I am writing I suppose you are just beginning to return home. Surely in a case like this death has lost its sting not only to her but to her mourners, sorrow there must be but no bitterness, I quite see and feel with you that no one can long for themselves or others whom they best love to shake off such a sorrow, it will be the repose rather than the burthen of your life, though I suppose that until more years have passed over our heads, we shall not feel the full consciousness of the blessing of having such treasures in Heaven, and so many as are already especially your own. I do not think you have the [Lyra Apostolica](/periodical/92), therefore I have written out the verses in it which [Mr Keble](/person/798) wrote for [Sir William](/person/669) when [Lady Heathcote](/person/657)[^2] was buried, there are so many lines that seem as if they were meant to express what you all must be feeling [Mamma](/person/1606)’s health does not seem to be suffering as I was very much afraid it would, but she could not eat any breakfast this morning. She is now painting the Commandments which is the best thing she can do, and was a great comfort to her before. Do you know one among the [Plain Sermons](/place/181),[^3] in the 5th volume I think on the Sacredness of Suffering, it is by [Dr Pusey](/person/1215) and I think you will like to read it, we read it last Sunday evening. You must not write to me till you feel quite inclined to do so, and then pray tell me how you are going on, and what you are doing. I hope we can feel ourselves autumn friends as well as spring and summer, though I who never yet have felt the real heart breaking kind of sorrow which makes it hard to say ‘Thy will be done,’ cannot really pretend to try to comfort you, or if I did could say anything which could do you half as much good as one look at [Uncle Yonge](/person/1623), I can still tell you again and again how very much I love you. This is very far from such a letter as should be written but you will know how to understand me. [Miss Garstin](/person/546) wrote today and [Lady Tucker](/person/1421),[^4] they say they will not write to you now, but wish to have everything kind said for them.
my own dear Anne
your most affectionate cousin
CMY


[^1]: Puslinch is in the parish of Newton Ferrers, of which the Rev. John Yonge was Rector.
[^2]: Lyra Apostolica (Derby: Mozley, Rivington 1836), a collection of anonymous poems by Keble, Newman and others. Caroline (Perceval) Heathcote (d. 1835), first wife of Sir William Heathcote.
[^3]: Plain Sermons by Contributors to the ‘Tracts for the Times’ 10 vols (London: Rivington 1839-48).
[^4]: Urania (Leeke) Tucker, wife of Rear-Admiral Sir Edward Tucker of Park Place, Wickham, Hampshire. Her mother was a Bargus and so she was a first cousin of both[Anne\'s mother](/person/1580) (who had just died) and CMY\'s mother. Delia Garstin was a cousin of Anne\'s mother.
