---
id: 2961
title: William Crawley Yonge to the Reverend John Yonge
date: '1849-03-14'
display-date: March 14. 1849
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: William Crawley Yonge to the Reverend John Yonge
manuscript-location: MS Plymouth and West Devon Record Office 308/258
---

My dear[ John](/person/1623)
I hope the untoward task you had to perform on Monday may turn out better than there seems reason to expect, for really one has no right to look for happiness from such a marriage.[^1] As the little man was going to Gibraltar, she had better have left him to take a wife from among the Monkeys of the Rock.

He might have matched himself from among so many. [Delia](/person/1591) in a letter to [Fanny](/person/1606) just whispered the sad intelligence of her son [John](/person/1622)’s rambling inclinations, saying it was quite a secret, & that you were to only person informed of his state of Mind.

How long do you understand that he has been unsettled?

It is lamentable indeed to have a case of the sort come home in our own Family and as in all others that I have known or heard of the accompanying circumstances have been just such as to do the greatest injury and cause the greatest pain to the Friends of the Party.

If he persists in the Change, what a horrid thing his coming to live in Plymouth will be.

How much better that he should have remained where he was.

Poor fellow, it is not so much a matter of Surprise as of regret, seeing how very little opportunity he has had of seeing and being engaged in the practice of the Church of England.

Looking back to his coming home on Saturdays from Macaulay’s, when Sunday was more in the way of relaxation from School, than a Holy Day, then with Williams the Surgeon where I suppose no great good was to be learnt, then at Edinburgh and since in a Roman Catholic country. I very much wish we could get him to come here. I think the best chance for him would be to let him open his Mind to [Mr Keble](/person/798).

Do you understand what it is that he goes off upon?

You did not return the letter from Mr Fewes which I sent you respecting the Sisters of Mercy. I thought it excellent and wanted to send it to [Catharina](/person/1712), so if you still have it will you send it back.

With regard to what you say of the Title given by [Miss Sellon](/person/1294) to her Institution, I think you must agree that the same actions are often the rsults of quite opposite Motives in different Minds, and that therefore although it may be here enough that a person thinking as you do could not adopt such a distinctive title except from a motive of self aggrandizement, it by no means follows that Miss Sellon may not have been influenced by far other feelings.

May it not be the case that she thinks she rather avoids personal exaltation for herself and her fellow Laborers by getting rid of their individuality of Character, by forcing themselves into a Society as members of which they can act with greater Freedom and Propriety, having as it were a recognised Station under the Sanction of the Parochial Minister.

Is it not when one looks to the rest of her Actions, really more probable that Modesty & Humility have actuated her rather than Vanity.

If this Title and some other ?pocuts that have been canvassed seem to you to savor of enthusiasm and Sentimentality, I think it is to be borne in mind that is only Persons of earnest exalted Minds who do in fact devote themselves as she does, and that in order to judge them fairly we should endeavor to throw ourselves into their feelings.

As to reproaches coming from the Romish Church, they are as you say little worth our attention, but I suppose it is not be denied that the absence of any such establishments attached to our Church is a real and great evil.

There are I have no doubt many pious women whose hearts yearn after the opportunity of devoting themselves to the Service of God in works of Charity, who are hindered by various causes from so employing themselves at their own homes, who would gladly indeed under the title of Sister of mercy take refuge in such if they might. I could point to an instance of one whom I have seen at Kebles, whose home was rendered very uncomfortable to her by the persecutions she endured at home, her family pressing her to marry a man of wealth whom she did not prefer, while her wish was not to marry at all being of very retiring habits and only desiring to occupy herself in works of Charity.

Some years ago we got a Copy of a letter of [Dr Pusey](/person/1215)’s to a Lady, whose Friend was inclined to Romanism. I enclose an extract from it, in which you will see how he points to such means of employment & Consolation, and we hear from the Kebles that this has been a subject which has much dwelt on his Mind and that he has of late expressed his firm persuasion that the time would come when such institutions would be vouchsafed to the Church since there were so many who made it the subject of their earnest prayers. I thank you may see from this that other Motives than a vain wish for personal notoriety may very well have prompted Miss Sellons Course and that to obtain pecuniary aid for her Schools is quite a Minor Consideration.
I am rather anxious to suggest a different view because I think that when a Woman acting so noble a part, is met by such a Storm of Obloquy and vulgar abuse, occasion sought against her by tampering with runaway Servant-Maids the objects of her Bounty and she a young gentlewoman dragged before the public obliged to vindicate herself in person in the presence of those unfeeling Scoffers, exposed almost like a Criminal on trial, but without experiencing the fairness that is always in our Courts extended to a Criminal, it is ten thousand pities that right minded men who have no community of feeling with those Railers, should yet withold their support or expression of sympathy for her, because they feel an objection to the name she has given to her Association. I do not know what were the other points or practices which you felt to be objectionable before this uproar was made and have since been discontinued.

In the report of the Meeting it seemed that the names for the hours of prayer had been changed to the corresponding English words, that the Cross had been taken from the Table in the Oratory and that Miss Sellon had since these attacks given away the small Cross which she wore and had been given to her as the Memorial of a Friend, several years ago.

But these things were not before the public and could only have been known by the means which were taken, enquiry of the Servants, or prying into her own house.

Nothing of the objected matters was before the public except the Titles Sisters of Mercy and Orphans Home, and it was only the latter of these to which Hatchard objected because it interfered or he was afraid it would interfere with the [Plymouth Orphans home](/organisation/33). I though the being driven to part with her Cross was a painful result of the persecution.

Do you remember what Burke says in [his work on the French Revolution](/organisation/236) speaking of the poor Queen of France, how he had seen her several years before the idol of the People in the bloom of youth & beauty, and then of her fall ‘Little did I dream’ says he ‘that I should have lived to see such disasters fallen upon her in a nation of Gallant men in a nation of Men of Honor. I thought ten thousand Swords would have leaped from their Scabbards to avenge even a look that threatened her with insult.’ And so it seemed to me, that when such a woman engaged in such a cause is subjected to such treatment, laboring as she says, amid all that is most bitter to a womans heart, calumny, ingratitude & Suspicion, causing pain & anxiety to a degree that has seriously affected her health, it is a sort of duty to come forward and at least let her have the Comfort of assurance that all Church people are on her Side and ready to stand by her, so I could not refrain from writing to her and have sent my subscription to the Agent. [James](/person/1614) too found fault with some Sentimentality in her Address; I cannot understand it. I felt rather with the Author of the letter in the Times in which he spoke of its incomparable grandeur and touchingness. I am sure it seemed to me to shew a wonderful Mind.

James also speaks of Dr Pusey’s visit as a bad hit.

He does not know what is at work.

From the little extract from his letter which I enclose, you will I dare say draw the same conclusion that I do, that as he is a Friend of Miss Sellons, this Institution has not been set up without consulting him, and that he and she look to the spread of such an Example as already in consequence of the publicity given by the attack on her, another has been set up on Liverpool. I believe that Dr Pusey is the most valuable man in England, the man who does the most extensive good and does the most to counteract evil whether in the shape of inclination to Romanism, or to Infidelity.

He seems to be a sort of Bishop to the disquieted & troubled minds and very many there are who look to him for consideration & support. I heard a few days ago what fearful progress the Germanizing Spirit is making in Oxford, turning many of the cleverest young men to Infidelity like [A Froude](/person/528), and that the great Stay and support on the other side is Dr Pusey.

As to the [Church Union](/organisation/22), I understand the purpose of it to be to work for the same objects as you would support, to be an association to watch over the affairs of the Church and to instruct those Members of Parliament who are well disposed but are not always able to inform themselves fully on the Measures brought forward. I dont think you need have apprehended illegality in the Constitution of it, as though there might be delegates, there were no oaths to bind the members and I believe both [Coleridge](/person/344) & [Patteson](/person/1156) belong to it. I met at Coleridges last dinner Keble, [Sir George Prevost](/person/1713), Mr [Beresford Hope](/person/1714) (the founder of [St Augustine’s](/organisation/13)) & [Ed Bastard](/person/119) who had all been at the first meeting of it.

Indeed I went to Town with Keble who shewed me the Rules that were to be proposed and we discussed them in the Train. I reckon they would all fight against the Jew Bill as heartily as could be wished as well as against the other infamous Schemes coming forward.

In all the addresses and Petitions that have been got up during the last 15 or 16 years, and in all the Elections I have always thought it best to go along with that which seemed to me in a right direction though I might not if I had had my choice have approved of every word in such address or Petition or liked every point of Character in the Member.

Cooperation is every thing and to obtain it many must sacrifice some points of detail.

Poor Jane Blacklie seems to have gone off happily for herself very rapidly, much more so than is usually the case in Cancerous affections was it not.

You say you dont see how Californian Gold is to relieve our Markets.

Dont you suppose that depression of Trade generally, want of Money & want of Confidence are the causes of the present low prices. I do, and that an influx of gold may so raise them that rents may rise very considerably
ever affectly yours
W. C.

Yonge
Fanny will send [Mary](/person/1626) a Copy of a letter addressed by one of the Ladies to a friend in Hampshire near Fareham.

Just read the account of the mode of their Life and of Miss Sellons power of influencing the Boys.


[^1]: This seems to be an uncharitable reference to the marriage at Plymouth on 12 March 1849 of WCY\'s niece [Cordelia Anne Duke Yonge](/person/1099) to [Colonel Oldfield](/person/1100).
