---
id: 2964
title: To Mary Anne Dyson
date: '1849-10-29'
display-date: October 29 [1849]
from-name: Charlotte Mary Yonge
from-address: Otterbourne
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  154-156
---

My dear [Driver](/person/464)[^1]
I rather doubted about sending you Cyrus[^2], because, as you will see, he does not stand alone, but is a chapter of general history and therefore is not very minute, nor has he been written more than once, so that you must excuse numerous deficiencies and please to let me have him again.

To my shame be it spoken I have not read [Clarendon](/organisation/35); we ought to have read him aloud when we were diligent Dicks[^3], instead of which I was set to read him to myself when I was too young and could not get on. I think you get a great deal of him well adapted in [Lodge](/topic/106), but you see I am not competent to give an opinion.

Prince Rupert and the Cavaliers cannot help being interesting in spite of [the man](/person/1720) that writes it.[^4] I think you would find it a useful string to your bow.

He certainly makes out a very good case for Rupert, who, always having been rather a pet of mine, I am glad to see exculpated.

It seems that he fought Marston Moor against his own opinion, under positive orders from Charles, which he never showed to any one under all the accusations he suffered, but carried about him to his dying day. I wish I could do more to help you where you are.

Don’t be afraid for the [Confirmation story](/book/18)[^5], it will be written all the quicker when it once begins for being well cogitated at first, and I do cogitate it.

Lucy and Juliet are the names of the sisters still, I could not make the first do with any other. I have been settling how Lord Herbert begins the Confirmation with them - something in this way; they are staying at his parsonage, you now, just after he and Constance are come back from Madeira.

He says, ‘Don’t you think, Lucy, that you could be spared to stay with us till after the Confirmation?’ He was little prepared for the manner in which his invitation was received.

Lucy rose up and sat down, then said with an effort, while the tears began to flow, ‘ Oh, Herbert, you don’t know how bad I am!

When Aubrey died, and I was ill, then I thought how I was really going to be good, and we set to work and made rules, and went to Mr.

Fellowes to be prepared for Confirmation.

Then I was out of spirits and weak after all that had happened, and mamma thought it was the Confirmation, and took us to London, and Juliet and I came out!

And I could not help liking the parties very much, only what with them and with the masters too, all my time was taken up, and I could not mind my rules, and so whenever I got time to think I only found myself growing worse and more unhappy.’
So this is to be the state of mind in which he takes her up.

And I have made out why Constance was so superior. I think the three sisters were sent home when Constance was seven, Lucy five, Juliet four, and all put under the protection of an uncle, Mr.

Berners, who always lives abroad, and concerns himself no more about them than to send them to a very good clergyman’s widow who takes young Indians, and there they stay until Constance is thirteen or fourteen, when on their father’s death or mother’s second marriage they are suddenly recollected and all moved to the fashionable school where they have been ever since, Constance having brought away with her too much good to be spoilt in the atmosphere there, perhaps confirmed before she goes.

At seventeen she goes to stay about with relations preparatory to going to India, stays with some school-fellow for the consecration of a church where Lord Herbert, just ordained, is to be curate.

She is a delicate, graceful, winning, white-lily sort of person, not striking, but very lovely, and he forthwith falls over head and ears in love and only waits to get all the different people’s consents.

Lucy and Juliet spend one happy little week of summer holidays with them at his curacy, and are promised Christmas, then he grows ill and is ordered abroad, and they have one little meeting with him and Constance in London.

All this before the beginning of the story.

If [Henrietta](/book/11) does not tarry on the road again your mind will be relieved about Fred on Thursday, and I hope the Old Slave’s aunt[^6] will recover it. I am just sending off two chapters more.

My idle work now is writing [a play ](/book/35)for the Moberly’s Christmas sport, about that time when Edward III. and Philippa found their children left all by themselves in the Tower.[^7] As they say great novelists cannot succeed in the drama, I suppose I shall make a fine mess of it, but it will do for them at any rate to make fun of.

Do you want to know where to get red cloak stuff two yards wide at four shillings per yard [?].

Mamma saw some at the Consecration in Sussex, and has a famous bale of it which is just going to be made up. I read a piece of the Allegro at [school](/organisation/107) last week, and I never saw a child in a state of greater delight than [Marianne Small](/person/1332), [Elizabeth](/person/1721)’s younger sister.[^8] I have just given [Jane Martin](/person/969) a real old [Christian Year](/periodical/95).[^9] Thanks for the news of [Allens](/person/923); the economical fire amuses us much. [Abbey Church](/book/2) No. 3 would begin after the laughing.

Your most dutiful
C. M. Y.


[^1]: CRC comments that these letters to Dyson ‘show how habitual was the discussion of botany and history in her circle.’ Another CRC note to this letter reads: ‘The story here dwelt on developed into the Castle Builders.

The letter is given as a specimen of the way Charlotte discussed all her tales with her friend, and also as showing the way in which they gradually grew up in her mind.’
[^2]: The account of Cyrus in her [Landmarks of History](/book/14) (1852).
[^3]: Hannah More, The History of Diligent Dick (1829) was one of the Cheap Repository Tracts.
[^4]: The author, Eliot Warburton (1810-1852), was presumably disapproved of by Mary Anne Dyson because of the flippancy and condemnation of monasticism in his most successful book, The Crescent and the Cross, or, Romance and Realities of Eastern Travel 2 vols (London: Colburn 1845).
[^5]: The story described here was published as The Castle-Builders, or, The Deferred Confirmation, in serial form in the [Monthly Packet](/periodical/52) April 1851-May 1853, and in volume form in 1854.
[^6]: CRC identifies CMY\'s fellow slave to Dyson as [Anne Mozley](/person/1061), editor of the Magazine for the Young.

The aunt could be a mistake for Anne Mozley’s sister-in-law, [Harriett Mozley](/person/1062) who was certainly known to the Dysons.

But there is evidence that \'Old Slave\' was Elizabeth Barnett, sister-in-law of the Rev.

William John Butler of Wantage (CMY wrote to her in 1854 as \'Old Slave\'), so she may be the person referred to here.
[^7]: ‘At midnight, December 2, 1340, the queen [and] king found that three nurses and the rest of the royal children were the sole occupants of the royal fortress of the Tower; the careless Constable, Nicholas de la Beche, had decamped that evening to visit a lady-love in the city, and his warden and soldiers, following so good an example, had actually left the Tower to take care of itself.’ Elizabeth Strickland, ‘Philippa of Hainault’ in Agnes Strickland, [Lives of the Queens of England](/organisation/157), 7 vols (London: Colburn 1840-3) II, 353.
[^8]: Marianne Small (b. 1839/40) and Elizabeth Small (b. 1837/8), daughters of John Small (b. 1797/8), of Allbrook, agricultural labourer.

The poem was John Milton, ‘L’Allegro’ (1645).
[^9]: Keble’s bestselling volume of poetry, that is, and not The Child’s Christian Year (1841), an anthology of poems by various hands compiled for Sunday Schools by CMY’s mother.

Jane Martin (b.1836/7) was daughter of James Martin, agricultural labourer, of Otterbourne; by the time of the 1861 census she was kitchenmaid to Countess Nelson at Landford House.
