---
id: 2970
title: To Mary Anne Dyson
date: '1850-06-24'
display-date: Midsummer Day [24 June 1850[[footnote:1]]]
from-name: Charlotte Mary Yonge
from-address: Otterbourne
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown.  Printed in Coleridge, <i>Life</i> 160
---

My Dear [M. A.](/person/464)
O that the sky of the Church was as clear as the sky above our heads, and how, as they always do, yesterday's [Christian Year](/periodical/95)[^2] seemed to chime in with the thoughts that must sadden one even in this most glorious weather, as we thought last night when the full moon was shining so gloriously in the midst of the sky, and the elm-tree making such a beautiful shadow on the field.

What can I say but that I am very sorry for you, and for [her](/person/889), it is like seeing tower after tower in a fortress taken by some enemy, and every time the blow seems nearer home. I do think such things as these make one know the comfort of people's being dead and safe, so that one can give them one's whole heart without the fear of having to wrench it away again. ‘Death only binds us fast.’[^3] When I say one's whole heart I mean one's heart of admiration, and that kind of half-historical love for living saints that we were talking of one evening, for I am thankful to say that no personal friend of my own, no one indeed whom I knew well, has gone, none indeed whom I knew so well as Miss Lockhart.[^4] There was [a cousin](/person/1622) indeed, but I had not seen him since he was a youth and I a child, and we feel most about him for the sake of his [mother](/person/1591) and of his [wife](/person/1723), who holds firm, and as to his mother, nothing could ever shake her I am sure.[^5] After hearing of such a thing as this, it does seem indeed a warning to any woman not to put herself in the way of being shaken by personal influence, and yet what could one do if one's [Mr.

Keble](/person/798) went, meaning him as an example of one's Pope. I remember Mr. [H. W](/person/1510). saying he could fancy making a Pope of [Archdeacon M](/person/951).[^6] ; is this what he is doing ?

And then why is Rome better because England is worse? that is the great wonder.[^7]


[^1]: CRC dates the letter \'about 1850\'.
[^2]: Keble, ‘First Sunday after Trinity’ in The Christian Year. 23 June 1850 was the first Sunday after Trinity.

The whole poem is relevant to the anxieties of the period, especially ll. 13-16 ‘We in the midst of ruins live,/ Which every hour dread warning give,/ Nor may our household vine or fig-tree hide/ The broken arches of old Canaan’s pride.’
[^3]: Keble, ‘Eighth Sunday after Trinity’ 44-8: ‘The grey-hair’d saint may fail at last,/ The surest guide a wanderer prove;/ Death only binds us fast/ To the bright shore of love.’
[^4]: Elizabeth Crawford Lockhart (b.1811/12) was the superior of the Sisterhood of St.

Mary\'s Wantage, which had been founded by the [Rev.

William Butler](/person/244).

She was under Manning\'s influence.

Her conversion to Rome in 1850, which followed that in 1843 of her brother William Lockhart (1819-1892), caused great consternation among the Butlers and their connections.
[^5]: Dr.

John Francis Duke Yonge (1814-1879), a physician, the son of WCY\'s eldest brother the Rev.

Duke Yonge.

See the letter above from William Yonge to John Yonge (14 March 1849).
[^6]: The Rev.

Henry Wilberforce (1807-1873), youngest son of William Wilberforce (1759-1833), the campaigner against the slave trade.

He and his wife Mary (Sargent) Wilberforce (1811-1878) were received into the Roman Catholic Church on 15 September 1850.

In the 1851 census Elizabeth Lockhart was staying with them.

The Rev.

Henry Edward Manning (1808-1892), archdeacon of Chichester and later Cardinal Archbishop of Westminster, was the widower of Mary Wilberforce\'s sister.

He became a Roman Catholic on 6 April 1851.

See David Newsome, [The Parting of Friends: A Study of the Wilberforces and Henry Manning](/place/128) (1966).
[^7]: CRC’s note: ‘This extract shows the feeling caused by the numerous secessions to the Church of Rome about this time.’
