---
id: 2971
title: To Mary Anne Dyson
iso-date: '1850-08-22'
display-date: August 22, 1850
from-name: Charlotte Mary Yonge
from-address: Otterbourne
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown. Printed in Coleridge, <i>Life</i> 177-8
---

[No salutation]
Do you really mean that you are thinking of a [rival magazine](/periodical/52)? I have a great notion it would be a very good thing, and you would make [Mary Coleridge](/person/351) write, and keep her from being sentimental. Also [mamma](/person/1606) goes into it so vehemently that she desires it to be observed that it might be printed very well and cheaply by the man at Winchester who did [Shiverydown](/book/10), a communication which I consider as premature.[^1] Did you ever see such a dreadful little note as she has perpetrated to go in this letter? Pray tell the [fellow-slave](/person/1061) that I am going to Plymouth, and ask if she would like to have a chapter on flowers from thence.[^2] I send Edith a promised ear of mummy wheat, enough to sow the whole garden I should think.[^3] I am glad the curate has got his holiday, I hope it will cheer him up. Our new school-master comes just as we go, which is I think a pity. Amabel is at this moment in the midst of [comforting Guy](/book/15) about his doom; he has just begun to establish an influence over Charles and to develop a soul in her, both very unconsciously. I don't think I have thanked you for the reflections on [Emmeline](/book/18); thanks to both drivers, she wants an infinity of smoothings down.[^4] We are reading the [Seven Lamps of Architecture](/organisation/138), some part very pretty, other by writing fine very nonsensical, other very powerful, and the beginnings of chapters only fit to be in German.

Your most affectionate
C. M. Y.


[^1]: Shiverydown was the family name for the story published as Kenneth, or, The Rearguard of the Grand Army. The 1850 edition by John Parker was printed in Winchester.
[^2]: Anne Mozley (1809-1891), the editor of the Magazine for the Young, was the sister of the Tractarians J. B. Mozley (1813-1878) and Thomas Mozley (1806 - 1893). CMY had been contributing a series of \'Chapters on Flowers\' , subsequently published as [The Herb of the Field](/book/17) (Derby: Mozley 1853). The article, ‘Compound Flowers’ (September 1850) 305-15, looks forward to [The Daisy Chain](/book/24): ‘When you make a daisy chain you thrust the needle and thread through the receptacle or disk, and the center florets. . . Daisy chains are country children’s strings of pearls, the pearls of the meadow, as we may call them, for the very same word, Margarita, signifies at once a daisy and a pearl.\' [308-9]
[^3]: Perhaps one of Dyson’s pupils, though the name does not appear among those listed on the 1851 census.
[^4]: By \'both drivers\' CMY means Dyson herself and Anne Mozley.
