---
id: 2972
title: To Mary Anne Dyson
iso-date: '1850-10-20'
display-date: 20 October [1850]
from-name: Charlotte Mary Yonge
to-name: To Mary Anne Dyson
manuscript-location: MS location unknown, printed in Coleridge, <i>Life</i>, 178 -
  181.
---

My dear [Marianne](/person/464)
Your letter has so made me overflow that in spite of Sunday evening I cannot help beginning to write after finishing my task of the 7th Command[ment][^1]. You see one part is founded on a saying come down to me, I don't know how, 'that nice men are men of nasty ideas.' I don't know how far all this ought to be administered, or whether innocence should be let alone, innocence of thought I mean. I like a bit very much in the [C. R](/periodical/59). review of the Prelude about harm not being done by the things children read in books. [^2] If I had thought of it I would have sent the [Listeners](/organisation/16) in the parcel for [Mrs. Dyson](/person/462)'s Sunday evening selections; at present I believe I return to my old recommendation of the dear old [Pilgrim's Progress](/topic/224), where I am sure they could learn nothing but good. I have nothing better at this moment to suggest than [Marco Visconte](/periodical/77), unless you were to give them some good book of travels, such as Franklin' [Voyages](/periodical/54), which I used to read for ever. Or perhaps Palgrave's [Merchant and Friar](/organisation/131)would do; there is a great deal I do like exceedingly in it, and only one thing I don't, and that is not important, namely some unpleasant philosophising over a dissected eye, which I think has a bad tendency, but I do not perceive that wiser people think so. As to [Mr. B](/person/119)[^3] , there were reports of the worse danger, and he did not act wisely certainly in having [Mr. Maskell](/person/975)[^4] staying with him just as all knew he was going to secede, but he seemed quite steady as far as could be guessed by his ways when we saw him, and his whole soul seemed in the Church restoration, not like a man who meant to abandon it; he took such pleasure in showing all that was doing and telling of the further schemes, and with the belief of early death about him which he has expressed I cannot think that he would remain in our Church if he doubted her really. He has been very unwell, and does not take care of himself, so [my uncle](/person/1614) has ordered him abroad, and [the Warden](/person/118) has just been to see about him; we heard to-day that it is to the Nile that he is to go, and choosing that instead of Italy seems like a very good sign. He is certainly more like a man in a book than like the rest of the world. What you say about [Archdeacon M.](/person/951). seems almost too terrible to be possible, but I must tell you a curious thing. Five or six years ago [Mr](/person/1443). and [Mrs. Harcourt](/person/1442)[^5] took us to a great Agricultural meeting at Goodwood, and papa sat next the Archdeacon and had a great deal of talk; but what struck papa was this, that Archdeacon M. first said to him that he hoped not to be called on to speak, and then put himself forward and showed that he wanted to do so. Papa said of it at the time that it showed a want of simplicity, it was so unlike what [Mr. Keble](/person/798) would have done; and he never had full confidence in him after that. How strange it is that the goodness and holiness of life that one would have thought would secure people only seems to lay them open to assaults of the faith, like Eustace in the [Combatants](/place/123), which you really ought to read. [^6] I suppose [Miss Martineau](/person/1724) is the Socinian specimen of pretty writing that you mean; I read a beauty that I am sure was hers the other day, about a heroic lady in a parish with a deadly fever; there was such a pretty piece about the clergyman and his wife going about fearlessly for themselves, only now and then a terror striking them for each other.[^7] And there is [Mary Barton](/periodical/69).[^8]

I think what you say about hero-worship exemplifies the difference between looking at a man as a saint or hero and as a Pope, in which latter case I think it is really making him infallible, and putting trust into something visible, giving our eyes up to him, so that if the light in him becomes darkness, he leads us into the ditch. Alas, how well I recollect Mr. [H. Wilberforce](/person/1510) on your lawn saying he could fancy making a Pope of Archdeacon M. I dare say you have read those letters of [Dr. Pusey](/person/1215)'s[^9] which the [Coleridges](/person/344) have about the danger of the craving to be guided. It must be the difference between looking up to a tree and clinging to it; in the case of saint-worship, the tree's fall seems to carry away half of you and leave you scarcely knowing where you are, in the other case you go with it.

I like the notion of the [Mag](/periodical/52). exceedingly, and when the [landmarks](/book/14) are done would devote the best part of my energies to it, and put in the [Cameos](/book/73), and work up the [Catechism](/book/33) papers into Conversations, but I have my fears, for I believe a new Mag. is an immense risk, and I think it is very doubtful whether [the Mozleys](/organisation/108) would choose to start one in opposition to [Masters](/organisation/112).[^10] Besides, who will guard us from the universal fate of good Mags. of growing stupid as soon as they get into circulation. However, it is my will, but not my poverty,[^11] and it would be a very pleasant thing if it can but be done. I don't think though that I shall venture on a letter to [the fellow-slave](/person/1061) just yet, till I know a little better how far she is in earnest; tell her to write to me, or better still if she would but come and stay. Do send her when she comes to you. Is her history of France going on? I wish any one could tell us what the cost of starting a Mag. would be. I advise you to set up a blackboard in your infant school; my eyes were opened to its uses by [Duke](/person/1599). I don't think I would make our Mag. much of a poor people's concern, more for young ladies and calves; perhaps started in that way it would not seem so like an opposition. I have got a book about the Reign of Terror which mamma hates the sight of, but which has some beautiful stories in it.[^12] Do you know [Tales of the Peerage and Peasantry](/organisation/159)? One of the stories in it about Lady Nithsdale would be excellent for Calfdom. I am going to give [Laura and Amy](/book/15) a sensible friend, a Mary Ross, about 25, daughter to the clergyman in the next parish, very clever, reading and school-keeping, without a mother, taking long walks rather independently and caring little for dress, quite feminine, however, and very nice. Charles delights in her, but Philip cannot abide her, because of her superiority in reality; he fancies it is for want of feminine grace. Amy is intensely fond of her, and she watches the two girls as they come to be on an equality with her with a motherly sort of interest. It is at her house that Guy made the outburst that led to the explanation with Amy. [Penny Club](/organisation/10) awaits me. Good-bye.

Your devoted slave,
C. M. Y.


[^1]: The seventh commandment is: \'Thou shalt not commit adultery.\' The sense of this is, although CMY does not usually write letters on Sunday evenings, but performs some sort of religious exercise (\'my task), she is doing so because she is so interested in the question Dyson has raised, which seems to be whether the girls in her school should be permitted to read books which refer to adultery. Dyson has evidently also asked for recommendations for books suitable to be read aloud on Sundays.
[^2]: [Review of William Wordsworth, The Prelude](/organisation/7) (1850) in The Christian Remembrancer XX (October 1850) 332-73, 347: \'And children left to themselves may in their innocence get no harm from what may taint an older imagination. But as a rule, it must be the duty of parents to guard their minds from contamination as much as their manners.\'
[^3]: Probably Edmund Rodney Pollexfen Bastard (1825-1856) of Kitley, near Yealmpton, a neighbour of the Puslinch Yonges, mentioned in George Moberly\'s diary as having converted to Rome by January 1851 ([Dulce Domum](/place/122), 94),who married a Roman Catholic in 1853. The context makes clear that Mr B is a patient of CMY’s uncle Dr. James Yonge, a Plymouth physician.
[^4]: The Rev. William Maskell (1814?-1890), ecclesiastical historian, was deeply involved in the Gorham controversy over baptismal regeneration, and converted to Rome in about 1850.
[^5]: The Rev. Leveson Vernon Harcourt (1788-1860), chancellor of York, and his wife, née the Hon. Caroline Peachey (d.1871), CMY\'s godmother. They lived at West Dean, in Sussex, and were neighbours of Manning, who was Rector of Lavington.
[^6]: The Rev. Edward Monro, The Combatants: An Allegory (London 1848). In this story about withstanding the temptations of worldliness Eustace is the noblest but suffers most.
[^7]: Harriet Martineau (1802-1876), Deerbrook (1839). Martineau had been brought up as a Unitarian. Socinians deny the divinity of Christ.
[^8]: Elizabeth Gaskell (1810-1865), Mary Barton (1848), another novel by a Unitarian.
[^9]: The Rev. Edward Bouverie Pusey (1800-1882), one of the founders of the Tractarian movement. Its followers were often called Puseyites. CMY met him only once, at Keble\'s funeral. He wrote a large number of letters of spiritual advice, some of which were published (but not at this date), and the Coleridges’ letters were presumably in MS.
[^10]: Anne Mozley was the editor of the [Magazine for the Young](/periodical/79), which was aimed at a readership among working-class children. CMY had contributed her novel The Two Guardians to another organ of the Tractarian movement, [The Churchman\'s Companion](/periodical/62), published by Masters. The Dysons and the Yonges felt, however, that the latter was too controversial in its theology to be good for the young, and wished to start a magazine aimed at children and young people of the middle and upper classes. The magazine was eventually begun on 1 January 1851 as the [Monthly Packet of Evening Readings for Younger Members of the English Church](/periodical/52). By \'calves\' CMY usually means the pupils at Mary Anne Dyson\'s school, but here she seems to be referring to a larger group of young people.
[^11]: Romeo and Juliet V, 1, 75:\'My poverty, but not my will, consents.\'
[^12]: Perhaps [The Reign of Terror: A Collection of Authentic Narratives . . written by Eyewitnesses](/organisation/9) 2 vols (London, Simpkin and Marshall 1826).
