---
id: 2982
title: To Alice Arbuthnot Moberly
date: '1851-11-01'
display-date: '[November or December 1851[[footnote:1]]]'
from-name: Charlotte Mary Yonge
to-name: To Alice Arbuthnot Moberly
manuscript-location: MS location unknown.  Printed in [[otherbook:122]<i>Dulce Domum</i>],
  98.
---

My dear [Alice](/person/1025),
Herewith is the '[Bridge of Cramond](/book/41)' finished. I hope [George](/person/1014) will not think too much sentiment falls to his share; and that we shall soon fall in with that important actor, the hawk.

You and your two gipsies ([Emily](/person/81) and [Annie](/person/1024)) will make courtiers, and Zedekias will help; indeed six, besides the other actors, is nearly as much as the stage will hold.

Pray be grateful to me for bringing in a rat and the old lark.

As to the Scotch, I believe it is shocking; but if you can get it corrected it will be a good thing.

My boast of no scratches was futile; I had to make them afterwards.

We were glad to hear of [Kate Barter](/person/116).


[^1]: Dated on the assumption that \'The Bridge of Cramond\' succeeded \'The Pigeon Pie\' as the Moberlys\' Christmas play and was acted in 1851.

The play, based on a legend of James V of Scotland, appeared in print as The Strayed Falcon (1862).

Annie Moberly wrote in [Dulce Domum](/place/122), 96:

For several years Miss Charlotte Yonge wrote plays for us to act at Christmas.

The learning the parts and rehearsing took weeks beforehand, and Miss Yonge liked to act herself sometimes.

She was Queen Philippa in \'St.

Barthelemy\'s Fair.\' Mary made a lovely Cinderella, and was small enough to he pushed into one of the cupboards of the carved oak sideboard when the prince came to try on the shoe.

She was dressed in my mother\'s dark green silk, and under it a dress of white net with all her most glittering ornaments sewn on to it, which was displayed when the fairy (Dora) touched her with her wand tipped with a silver star.
