---
id: 3014
title: To Elizabeth Roberts
date: '1853-11-29'
display-date: Novr 29th [1853]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Elizabeth Roberts
manuscript-location: 'MS Huntington Library: Yonge Letters'
---

My dear [Madam](/person/1243),
I enclose your P O order for 11/6 for the last quarter of the [Lesser holidays](/organisation/234). [Mr Mozley](/person/1065) promises this next year 1854 to raise his pay to[ 1/6 per page](/topic/102), so that I hope the Cathedrals will be a little less unworthily paid when you have time and inclination to make them out.

Your present of the Garland must be indeed a most precious one, I wish we were not so entirely on the opposite ends of England that there seems no conveyance but the post, for I should much like to see it. I have been asked several times if there was any hope of its being published separately, and I should think it would meet with many purchasers, who would be very glad of it.

As to the question of publisher, I think if I was you I should fix my own price for permission to print such or such a number and give a certain time to sell them in, and then if Mozley did not accept your terms you would be free to look elsewhere.

His family is very clever, but I never quite think they appreciate botany, so that I am not quite sure what he would say in this case.

When he brought out my little [Herb of the Field](/book/17) which had been published in the [Magazine for the Young](/periodical/79) he was afraid of illustrations, though I thought them much wanted.

However, having them ready drawn would make a difference and I am sure the book might be a very pretty one, especially if you added the emblems of the Saints perhaps as tail pieces, there is a tolerable list of them in Lord Lindsay’s [Christian Art](/topic/104),[^1] and another in a little paper of the [Ecclesiological Society](/organisation/131), and really it is most useful to have some key to such figures as one sees in Henry VII’s Chapel or in Worcester Cathedral.

Yours sincerely

C M Yonge


[^1]: Lord Lindsay (later the Earl of Crawford) Sketches of the History of Christian Art (1847).
