---
id: 3021
title: To Elizabeth Roberts
iso-date: '1854-01-16'
display-date: Jany 16th [1854]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Elizabeth Roberts
manuscript-location: 'MS Huntington Library: Yonge Letters'
---

Dear [Miss Roberts](/person/1243),
I hope your correspondence with [Mr Neale](/person/1078) has been satisfactory, and also with [Mr Mozley](/person/1065). If you have not heard from him yet, I should think you had better write again and ask his decision. Certainly I think it would not do to dwell on the other name of the Arbor Vitae, the Legend of the Blessed Thistle I do not know. I had not heard that the Wren was our Lady’s bird, though I have all my life known a rhyme said to be the cause that deters boys from robbing the red breast and the wren saying that
	Robin and Jenny Wren
	Are God almighty’s cock and hen
It would not do to quote, but it seems as in the case of the Lotus Corniculatus they must have been transferred at the Reformation. Are not St Cuthbert’s beads fossil ammonites, I fancied they were and that tradition declared them to be snakes turned to stone, do not the notes to Marmion say so. But I have no right to talk about them from my South country.
Thanks for the promise of Carlisle Cathedral, I shall much like to see the paper, my recollections are vivid of the poor Cathedral. By your account the Puritans must have left behind them the temper that battered down its nave, but the decking it for the first time may I hope be the beginning of a revival of better things. Winchester is at present much interested in a new organ for the Cathedral, which [Dr Wesley](/person/1488)[^1] has persuaded them to have, and hopes to have finished by Easter. There have been great debates whether the place for it should continue on the north side of the choir, or be removed to the west screen, the usual situation, but expense has decided in favour of the present locality, and though I believe it is bad taste I am one of those who rejoice in it, I like the full unbroken line, from the west door to the beautiful east window above the Lady Chapel. Not that this is our longest Cathedral view, from one of the side west doors there is a view up to the end of Langton’s chapel at the east end, the longest I believe of any Cathedral in England. Glastonbury must have been nearly the same length, but alas! that is only to be traced by its broken walls. The view of Winchester is just now much hurt by the repairs [Lord Guildford](/person/591) has been inflicting on [St Cross](/organisation/130), filling up places in the tower with cement, which has whitened it so much that I would hardly have recognised it as the little square grey tower that I have known all my life as an attendant on the Cathedral.[^2] I hope it will soon tone down, and any further damage has happily been stopped for the present

Yours sincerely

C M Yonge


[^1]: The composer Samuel Sebastian Wesley (1810–1876) had been appointed organist of Winchester Cathedral in 1849.
[^2]: The Rev. the 6th Earl of Guilford (1772-1861), son of the Rt. Rev. Brownlow North (1741–1820), bishop of Winchester from 1781-1820, was a notorious pluralist. His occupation of the lucrative post of Master of St. Cross Hospital had caused a scandal which is supposed to have inspired Anthony Trollope’s novel [The Warden](/periodical/170) (1855).
