---
id: 3039
title: Anne Yonge to Mary Yonge
iso-date: '1854-04-17'
display-date: Monday 17th April [1854]
from-name: Charlotte Mary Yonge
from-address: Otterborn
to-name: Anne Yonge to Mary Yonge
manuscript-location: MS Plymouth and West Devon Record Office 308/123/9
---

My dear [Mary](/person/1626)
[I](/person/1582) could hardly help writing a note last night before I went to bed, it seemed so long to have known about[Harvey](/person/1751) without saying a word.[^2] I do not know whether I mentioned that we were to spend Saturday in a shopping expedition to Southampton & so no chance of writing then, but so it was. You will quite understand how little I mean the words to apply to herself when I say how very sorry I am at the tidings. I do not know anything out of our own immediate family, I mean those we actually live with that I should have felt as I do this. Other people we mix with now & then & lost sight of again for weeks or months as the case may be, but she has never ceased to seem a part of our own home, & a sort of link there with times that are for ever gone by, wh nothing else can ever supply. Think of the memories of our childhood & the intimate knowledge of each one of us, that die with her, & how very much more of it I believe I was going to rescue before the opportunity was passed. While for her very deep & consistent feeling on religious subjects & the truly pious cast of her mind (for she really cared for nothing in this world in comparison to the things of another) one felt the sort of respect as of an example wh years & years cd not bring oneself near. I felt no hope at all of a better account after [Jane](/person/1616)’s note on Saturday morning, but still it came very suddenly on me, for after reading it we set off straight from Church to Southampton, & by the time we got back[Mr Wither](/person/1544)had brought your letter from Winchester & was ???ing that he had not been disappointed of bringing me what he calls ‘something for supper’. To you all it must have been quite as quick a surprise, perhaps a greater one, after seeing her so lately taking that ride & tending her school & she herself perhaps was the only one really prepared for it seems to me we know that long ago she would have been ready & even longing to have done with her weary life, if it had been so ordered & I do not think she had the unpleasant sort of self reliance & confidence some have who lend an ear to the doctrines of the dissenters. I have so often thought how much it would be incumbent on us to do for her in a last illness whenever it came, seeing how large a share of her confidence she bestowed on our family & home lonely her situation &c & little contemplated that it would end in 2 or 3 hasty runs & hurried visits in the dark very often of a winter’s evening but all this as you say of little consequence to her now & when not thinking of ones own feelings & the loss of the sort of true friend she was, in the interest for everything concerning us, we can most truly rejoice that she has arrived safely at her journey’s end, & probably with less anxiety & suffering to herself than if her illness had been lengthened after she was too weak to get up. I do not think she wd have liked people to be much abt her house when too ill to overlook what they did. Full enough it is of treasures. I hope [Mary Davis](/person/1752) has learnt the histories of Mercy & that some of her children will care for them. Some I wd fain she wd give to us all [Duke](/person/1599)’s little pigtails for instance, but we cd not ask. Poor Mary D. herself is truly to be pitied. The only peaceful spot she has for years has been by Harvey’s fireside & the soothing conversations she had with her seemed the only thing that enabled her to get through her rough life at home. I shall hear abt the Funeral no doubt, & I suppose you all will go, & I shall be sorry I am not there too. I am very glad you were with her on Tuesday. I remember we were so once before on a like occasion.
My 1st Saturday away from home was rather a strange one and somewhat saddened by contemporary events & reflections. [At Fanny](/person/1606) had looked forward to it, for so long a time, as a kind of boundary line wh was to cheer up & restore her failing spirits that when it came & she found herself less able to enter into the proper feelings of the day than she expected, she seemed quite knocked down by it, having got up with a beginning of a headache, & been tired the day before with long business with [Sir Wm Heathcote](/person/669), & waiting too long for dinner; besides a sort of stye in her Eye, wh has been fidgetty & troublesome, all contributed to make it very bad, & then came a note from [Jane C.](/person/1042) in reply to Aunt F’s enquiry for the Baby saying how very little hope they entertain of its recovery they fear there is already a deposit of water on the Brain, in wh case At Fanny says it is earnestly to be hoped it wont survive. Altogether I think this contributed to upset her. She laid down on the sofa & despatched Charlotte with a composed face to school & soon after I found her having what she called ‘a good comfortable cry’ but it appeared so far hysterical that tho obliged to obey her & go on to school I cd not be easy not to run back at 10 o’clock & see what had happened next. I found her on her way up to bed, her head was so much worse & she was inclined to be sick & so there she spent the rest of the day till 6 o’clock only 1/2 undressed however. Then to our surprise while Charlotte & I were sitting down at our solitary tea, in she walks at the window, saying the departure of the brilliant sunshine had so far revived her that she had got up. We strolled abt the garden for 1/2 an hour & she staid up to prayers, & is today very well & cheerful. Charlotte is gone to fetch Mary C. so I shall come presently to an abrupt conclusion.
It was not a worse headache than she has had before, & the crying & all are parts of the nervous derangement but I really think it was on the whole better than if she had tried to go to Church. The service wd have affected her in many ways & it was very long indeed - so very many communicants I never saw in a country parish, & in the afternoon Mr Wither’s remarks on the War & the certainty that all the lighthearted young soldiers that were gone cd not return, wd not have been consoling, besides his notice of the Baptism & Funeral in the (I am talking to At Fanny so excuse mistakes) same day. wh however he did very well indeed. But we had been the grave digging yesterday, & as they came out of church the funeral had arrived too early, & they had to pass through it at the Church yard gate. It was a [Mrs Barfoot](/person/105), whose illness has reminded me of Harvey all along (mother of that[Mary White](/person/1753).) for when 1st I came Mr Wither said she had something the matter with her throat & was greatly afraid it was a Cancer. She had heart complaint & tho this seemed to come to nothing more than a swelling she rapidly drooped & died on Tuesday or Wednesday. Poor old Shepherd died last night, he has soon followed his master. I need not ?sh out the history of my day however. I pitied Charlotte very much for all she had to do, & not to do, for Aunt Fanny is so afraid of her getting into a worry when her head is bad & making better worse that she made her go to [school](/organisation/107) & church again in the afternoon & kept me apologising & explaining to Char: as well as she could, but I thought even in the eyes of the world she would not like it to appear that she was not the one to stay with her sick Mother, but she submitted, & then came the Prize giving & she had to make a public speech to the 20 children or more, all ranged in a circle outside the drawing room window, Mrs Payne & [Harriet](/person/1359) listening, noticing the difference in this Easter, & why they had their books without the usual Tea drinking, & Feast. When we got up again we found Aunt Fanny had been dozing & as usual dreaming one of her ridiculous dreams. ‘She was watching Charlotte give round all the prizes & at last one little particularly clean boy was left, dressed in white & with well brushed hair & held out his hand very eagerly as if expecting a prize, whereas Char enquired his name, to wh he replied ‘Sarcophagus Slaughter’. You may imagine how she & Charlotte laughed. [At Seaton](/person/314) & Jane went to London & return to Dittisham today. At Seaton feeling very much the parting with [Francis](/person/324).[^3] I am sorry I have written such a scrabble as this. & said nothing I most wanted I believe. Frank’s letter I have certainly never seen. Tell me what was in it & I will answer. I quite forgot that Harvey wd be buried at Holberton not Newton I suppose, when I said abt yr going. It ought to be [Papa](/person/1623) or Duke to perform the service sd it not? I trust the long effects of her teaching will yet be seen on her scholars & [John Winter](/person/1754) too must have realised some benefit from his sojourn with her. She has been of far more use in her generation than many in her state of health cd have been. Thank Jane for her letter. I do hope Papa’s cold will go. It as parched as ever here, but in Southampton we paddled abt miserably in a straight down hard shower wh soon made the streets & flags a map of mud. Poor Christopher, this is the end of all made plans. I hope he is better. I wont write any more because of At Fanny. What a pity Harvey had not made her will, how often it happens
love to all yrs affect
Anne Yonge
There was a tremendous ‘row’ in Winchester yesterday between the Militia & the Soldiers of the 88th who are almost all rough Irishmen. They were fighting & rioting all day I believe. I have been thinking that after all Harvey had everything she cd most have desired, a sufficient degree of illness for a very express warning of what was coming. The communion just then instead of waiting for Easter, as she might have been inclined, and Duke to read prayers at the last. It is as happy we must assume she has [illegible] I am sorry for the poor drowned man


[^2]: Harriet Harvey (Holbeton 1800/1-1854) is recorded in the 1841 census as a female servant at Puslinch, and in the 1851 census as a schoolmistress, living alone in the village of Torre in Newton Ferrars parish.
[^3]: Lady Seaton’s second son the Hon. Francis Colborne (1817-1895) was an army officer no doubt also on his way to the Crimea.
