---
id: 3045
title: To Jemima Blackburn
date: '1854-05-26'
display-date: May 26th [1854]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Jemima Blackburn
manuscript-location: 'MS University of Illinois, Urbana Champaign: Letter 3.'
---

My dear [Mrs Blackburn](/person/159)
Many thanks for your photograph which I am very glad to possess, as it is pleasant to have more than a visionary notion what one is writing to. [^1]
I cannot find any authority for [Tom Thumb](/book/21)’s father being a miller, in one of your books he is a ploughman in the other a woodman, and in [Grimm](/organisation/243) a peasant, so as he seemed to be quite well to do, with a cow and team of horses, I concluded he was a forest farmer.

The last chapter is terribly destitute of authority, but it struck me that you could make such a funny [sketch](/topic/167) of the little face looking out of the longtailed tit’s nest.

Mab’s state chariot shall be the snail shell, her everyday one the hazel nut.

By the by, Tom’s proportions vary shockingly, if he was really as big as a /man’s\ thumb he could never have got into a snail shell, and not very well have ridden on a butterfly, at least not an English one, and even on an Atlas moth I am puzzled to know what he did with his legs.

However the butterfly is indispensable, and I hope you will make it a peacock.

For my pleasure I will put him for once on a dragon fly.

Those bats’ wings were a piece of stupidity of mine a mixture of the bats’ downy bodies and the coats Titania ordered for her small elves, which somehow I had imagined fur coats. I suppose it will be better to keep these fairies quite apart from that unsatisfactory race of ‘Good people’ that live in hollow shew and pay the teind[^2] - their legends have an awfulness about them that exemplifies [Mr Ruskin’](/person/1268)s theory of the terrific shadowy grotesque play of Northern nations.
I am going from home for a week this afternoon, after which I must give the final touches to my new tale ‘[Heartsease or the Brother’s Wife](/book/19)’, and then will set on at Tom and do him, or at least his rough copy, I hope by the time you are ready for him. I think the German scenery best suits the storks, though I always think of them on the top of a column in some book of travels in Palmyra I fancy. I wonder why they do not come here, I wish they would.

Indeed I must defend my Babel lion as the wild beasts of the desert certainly do meet the wild beasts of the island in the prophecy, and we know it was a hunting ground of the Sassanid Kings, so that there is full authority for the likelihood of lions being there, besides Sir R Porter having seen them.[^3] I believe it is true that [the Xtian Year](/periodical/95) has grown into my mind. I only wish it had into the rest of me, so I do not deny the having thought out of it, but I uphold there being full foundation for the Lion, apart from that.[^4] Thank you too for the paraphrases, I think I like one from Job the best.

If you are ever in want of small verses for small children, I never met any so pretty as ‘[Moral Songs](/organisation/12)’ by [Mrs Alexander](/person/21),[^5] published I think by [Masters](/person/981).

It is quite a little book about 1/6 I think not at all in the hymn line nor doctrinal, but about being afraid in the dark, about little birds, field mice, sunbeams, village wells &c, very simple and poetical like a better tone of some of the ‘[Original poems](/topic/160)’[^6] I grew up upon. I cannot lay my hand on [Lady Bertha’s Honey Broth](/periodical/57), but I think the publisher is Cundall.

The story is, wonderful to say, by Dumas, and very funny and good.

There are other translations, but this is the one for delightful illustrations

Yours sincerely

C M Yonge
The Honey broth is published By Chapman and Hall price 1/6, the illustration by Berthall


[^1]: Perhaps one of those illustrated in Fairley, [Jemima](/periodical/63) 35.
[^2]: The Scots ballad \'Tam Lin\', about a minstrel stolen by the fairies, includes the lines: ‘Then would I never tire, Janet,/ In elfish land to dwell;/ But aye at every seven years,/ They pay the teind to hell.’ The \'teind\' is a tenth.
[^3]: Isaiah 13:21-2; Sir Robert Ker Porter, [Travels in Georgia, Persia, Armenia, ancient Babylonia, &c. &c. during the years 1817, 1818, 1819, and 1820](/place/133) (1821).
[^4]: ‘Monday in Whitsun Week’, 31-6: ‘With half-closed eye a lion there/ Is basking in his noontide lair,/Or prowls in twilight gloom. /The golden city\'s king he seems, /Such as in old prophetic dreams/Sprang from rough ocean\'s womb.’
[^5]: Cecil Frances Humphreys (1818-1895) married (1850) the Rev.

William Alexander.

This was her third book, published by Masters in 1849, following Verses for Holy Seasons (1846) and Hymns for Little Children (1848) to which Keble wrote a preface.

As a girl she had lived in Winchester and known CMY.
[^6]: Original Poems for Infant Minds by Ann and Jane Taylor, first published in 1804-5.

The more famous Rhymes for the Nursery, containing ‘Twinkle, twinkle little star’, was published in 1806.
