---
id: 3054
title: To Elizabeth Roberts
date: '1854-11-04'
display-date: Novr 4th [1854]
from-name: Charlotte Mary Yonge
to-name: To Elizabeth Roberts
manuscript-location: 'MS Huntington Library: Yonge Letters'
---

My dear [Miss Roberts](/person/1243),
Many thanks for the [paper on Gloucester](/periodical/244).

It came in a good time for a cousin was staying with us whose home is close to Gloucester, and her brother a minor canon who has all its antiquities at his fingers ends.[^2] She set down the yew tree to ask him about, but as she went home in haste to prepare to set off in a week to spend the winter in the South of France, I think it has a fair chance of being forgotten and shall set another of the sisters to ask the question when the confusion is over.

She agreed with you in almost everything except in admiring the modern monuments.

It was curious that we had just been reading an account of that great day at Lichfield in a letter from a lady who was staying in the house with the [Bishop](/person/1295) and [Mrs Selwyn](/person/1297). I do not know whether I mentioned to you my enjoyment at meeting them at Winchester and at Hursley.

They spent two days at [Winchester college ](/organisation/50)and gave one of them to Hursley, and I believe it was the universal wish that the time had been longer.

However we carry away some of his words and the remembrance of that noble, keen, apostolic face, which will haunt us long after he has left us. I think of his undertaking himself to navigate his missionary ship ‘the Southern Cross’ out to New Zealand with a crew of six men, it will be ready on St Stephen’s day, when Mrs Selwyn will have to take leave of her boys, and for seven years look to no home but this floating one.

It is joy to think there are such people.
I was amused at the offence given to the descendant of the Danes, but I am at a loss to think where I have introduced the name of Thompson, and certain little friends of mine who have made themselves a sort of concordance to the [Heir of Redclyffe](/book/15) cannot recollect it either. I am afraid he must often suffer the same indignity for it is a name one writes down as one would ----- to fill up a gap. I think the general judgment of ‘[Heartsease](/book/19)’ has been pretty fair, that she is inferior in some ways and superior in others to her predecessor, the details of course vary and very amusingly.

There is a time in one’s life when printed critiques seem very dread and infallible, and it is curious to find oneself judging of them at last.
I should like to know some of your articles in [Chambers](/periodical/56), I have been trying to guess, but I cannot detect from style.

If you should be inclined to continue from ‘[Rambles among the heather](/organisation/245)’ I think I shall be able to keep a space for them after the next half year, for we have had so much botany of late that I think I must keep one volume clear before beginning afresh.

It seems presumptuous to make arrangements so long beforehand, but I find I am obliged to do so, to avoid crowding.
I hope you are benefitting in health by your excursion and that you have no cause to be under personal anxieties for friends in this time of suspense.

We have been in great measure spared the terrible anxiety for [my brother,](/person/1624) who was prevented by illness from going to the Crimea, and is now I believe on the way home to recover, but there are many connexions and friends still with the army and these are days of trembling of heart, I hope we shall all be the better for them

Yours sincerely

C M Yonge
How beautiful your Cathedral on your note paper.

The sight of it conjures up [Mr Gresley](/person/1756)’s pretty book[^3]


[^1]: Black-edged paper, with black-edged envelope addressed to Miss Roberts/ Kings Bromley/ Kingsley.
[^2]: Perhaps a member of the Crawley family.
[^3]: [Gresley](/person/1756) was a Tractarian controversialist who also wrote fiction, and on the whole it seems more likely that CMY would apply this adjective to one of the latter than to one of his theological works.
