---
id: 3055
title: To Anne Yonge
iso-date: '1854-12-01'
display-date: December 1 [1854]
from-name: Charlotte Mary Yonge
from-address: Otterbourne
to-name: To Anne Yonge
manuscript-location: MS location unknown. Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  218 - 220
---

My dear [Anne](/person/1582)

Of course you know that the imaginary wheels we had so often heard turned to real at half-past eight that evening.[^1] We had a visit from [Lady Heathcote](/person/665) with her paper to show the British Queen had got in at Falmouth, and then she was so kind as to drive on to Winchester, where she got the letter, which made us very comfortable though rather upsetting [mamma](/person/1606), and obliging her to have recourse to strong coffee, more especially as she was rather over-tired by walking to Hursley Church, as we generally do on a Saint's day.[^2] However, [he](/person/1624) has set her to rights, and she is very bright to-day, though we neither of us got our proper sleep last night. He looks thin and is languid, but his face is not in the least altered, and he has by no means realised Laura's dream that he had come home in big red whiskers. I am sure if he had stayed in that climate it would have been the death of him. We can hardly believe that the suspense is over at last, or what makes us so much brighter. And here we are, all three writing letters as hard as we can, except when we are talking. Rover very happy, though, as he took a day's sport with the Hursley keeper, he is still so tired and stiff that he can only indicate his joy with his tail, and such of his eye as is not scratched out by briars. [Mr. Wither](/person/1544) came in for a few minutes last night, and put in Julian's name before the thanksgiving this morning. He had thought of coming to see you, but found ‘he must come home first’, and indeed, though it seemed joy enough to know him in England, it is better to have him here. Anent the nurses, I find the Kebles are not at this moment looking out for them for the East, but we do wish to know of some such persons, though the time is not yet come for speaking to them.

You know there is a hamlet of Hursley, towards Winchester, named [Pitt](/place/133), too far from church and school, so that [Mr. Keble](/person/798) has in Lent been reading prayers there in a room, and I knew they (the Kebles) wished much to do something for it. So it has ended in my offering that money of [Guy](/book/15)'s,[^3] etc., which has been so much on my mind, for the purpose, and it turns out to have been a dream of Mr. Keble's to build a school with a room to be licensed for a chapel, and there to place some good lady with a girl to teach the school, and also to have two or more nurses living there, trained, and fit to go out among the poor, also to make it a home for girls out of place, but this is more doubtful; the lady and the two nurses are to form the nucleus, and we want to know of them before the step is taken on which all must depend, namely, the asking the [Bishop](/person/1383)'s consent. The lady is, we hope, found, provided she does not wish to go to the East[^4], so that negotiation has been opened, and if things go on well I will write about your staid people. I told Mr. Keble of them, and he said, ‘I should like to have some one of Miss Anne Yonge's recommending.'’ It would not be worth while to say anything to them till the plans are more complete. Mr. Keble's notion is to have the people trained while the house is building, as the land is luckily [Sir William](/person/669)'s, and he (Sir William) quite enters into it (I don't know what is the matter with my pronouns). It is quite a long time since I wrote, and I hardly know what I have told you, and what not; these last three weeks have been a terrible strain on all one's sense, to keep up talk and occupation, and to try to be patient. I do think it has been the worst time of all. But it has ended very happily, and here we write letters and talk, and Julian is reading up his newspapers. He is more weak than I thought he was earlier in the day; he has that chilliness of weakness about him, and is tired beyond even walking down to Mr. Wither's, though he has done nothing but going to church. He and the stiff Rover are very good company for each other. His goods went on to London by mistake, but he promises us a fine unpacking of curiosities. Such a funny account of [little Duke](/person/1596) in charge of a boat where some grand officer demanded a passage, and this little fellow adhering to his orders to take in nobody.[^5] [Sir E. Lyon](/person/1757) was so delighted when he heard it that he had the little fellow to breakfast the next morning to hear all the story.


[^1]: CMY\'s brother Julian had returned from the Crimea.
[^2]: St. Andrew\'s Day, 30 November. Coffee was a remedy against headache, to which FMY was prone.
[^3]: Profits from The Heir of Redclyffe. The provision of a school in such an outlying hamlet is one of the leading events in CMY\'s novel [The Daisy Chain](/book/24). According to J. Frewen Moor, [A Guide to the Village of Hursley (1869), 6, the chapel was built at CMY’s expense, for £800, to a design by William Butterfield. It is now [2009](/place/124) a private house.
[^4]: To nurse in the Crimea.
[^5]: Duke Dowton Yonge was a very young naval officer, of the Antony family.
