---
id: 3063
title: To Anne Yonge
date: '1855-03-29'
display-date: March 29th [1855]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Anne Yonge
manuscript-location: MS West Devon Record Office Acc 1092/13
---

My dear [Anne](/person/1582),
We know what the news must be that came this morning and yet it is a strange sense of blank that comes in feeling that all is really over, but more so at the times for prayer than at those for praise.[^2] When one can recollect that the weak suffering body is not pressing down the power of praise any more, but that it has grown to what we only have such little gleams of here that we can hardly guess at it at all It is strange to have the two still prayed for that were so before you came when others have gone so much more quickly. I wish we had not taken you from the last Easter and the last months of her, and yet those have been times of our feeling together.

If it were not that I cannot leave [Mamma](/person/1606) at such a time, I should have wished so much to be with you in the laying her in the resting place. I wish I were coming with [Julian](/person/1624), but you have each other, and it would not be much satisfaction to you.

Little we thought in our parting at Chobham that the same party would never meet again, but only may that sweet unselfish unfailing cheerful kindness stay with me as a lesson, and charm of remembrance.

She was a bright thread in all the brightest hours of my life, and I do not know how to turn to the thoughts of not seeing the little figure and engaging face again coming in with her little table in the morning.

But this is the wrong sort of thought, and there is the better remembrance of the meeting she has had with the others who are gone from us before.

I wish I could have sent this little picture before or on your birthday, but I only got it yesterday.

It seems to fit the time, and I hope you will like it.

Do you remember our Easter Eve talk leaning over the gate at[ Cranbury](/place/119) that sunny evening last year?

Easter Eve is a day which brings a blessing on these waiting times of sorrow.

Julian is gone to [Mrs Heathcote](/person/658)’s funeral, not invited, for they asked only relations and tenants. [Mr Wither](/person/1544) goes home with [his brother](/person/1763) after it, so I grieve to say we have no Church till Saturday at 6.[^3] The little school girl was buried this morning- it was a day’s illness, and suspected of being scarlet fever so the school could not attend it.

Poor [Lovedy Kelland](/person/1764), how she has suffered![^4] It does indeed seem weeks ago that [Mrs Moberly](/person/1019) was here. I wonder when and how we shall meet – differently outwardly from what we now fancy no doubt.

Do you remember our having read those Burial Psalms so often under such different feelings – one of them once going up the hill from Ambleside[^5] – when all was bright – and how they fit ones tone.

If you come back to your own room, hang this little picture there. I cannot think of its being your solitary room without tears, but ‘think what if she be there’

your most affectionate
CMY

Julian is just come back. [Mrs Keble](/person/795) is better but the East wind keeps her back.


[^1]: Black-edged paper endorsed \'1855\'.
[^2]: The news of the death of Anne\'s sister [ Jane Duke Yonge](/person/1616) (1820/1-27 March 1855).
[^3]: Mrs Heathcote was aunt to the curate William Bigg Wither, and his eldest brother Lovelace Bigg Wither of Manydown Park, the head of the family, had no doubt attended the funeral.
[^4]: The name was later used for a character in [The Clever Woman of the Family](/book/58) (1865).

Lovedy (Saunder) Kelland (Chittlehampton 1824/5-1858 Lapford), wife of John Kelland of Kelland Barton, Lapford, farmer, may be the person referred to.
[^5]: The word \'Keswick\' deleted here.
