---
id: 3067
title: To Alice Arbuthnot Moberly
iso-date: '1855-06-01'
display-date: June 1855.
from-name: Charlotte Mary Yonge
from-address: Otterbourne,
to-name: To Alice Arbuthnot Moberly
manuscript-location: MS location unknown. This fragment printed in <i>[[otherbook:122]Dulce
  Domum]</i> 121-2.
---

My dear [Alice](/person/1025),
I hope [George](/person/1014) is feeling the freshness of these nice cool days[^1], and [Mrs. Moberly](/person/1019) is contented and happy without the babies, who by [Mary](/person/1020) and [Edith](/person/1012)'s account must be very funny, especially [Edward](/person/1013). What a pleasure it will be to see George at Winchester again, and to hear of all your doings, by which I hope ‘[The Daisy Chain](/book/24)’ will profit, as it has a Commemoration in it. ‘[Cleve Hall](/periodical/146)’ I like very much, I think the best of [Miss Sewell](/person/1301)'s stories. . . .We had a nice visit from [Dora](/person/968), [Kitty](/person/114), [Annie](/person/1024), and [Johnnie](/person/1017) last week, and we all joined [Mr. Bigg-Wither](/person/1544) and the Miss Yards[^2] and walked to Brambridge Gardens; there was a very hot sun and a thunderstorm - not quite enough to satisfy you, but enough to flatter the children with the hope of being rained up at Otterbourne, in which case I think [Miss Cowing](/person/374) would have been in a tolerable state of alarm. I should have liked to have heard that Sea-King lecture.


[^1]: Alice Moberly was in Oxford, nursing her brother George through a serious illness.
[^2]: [Eliza](/person/1578) and [Adelaide Yard](/person/1577)
