---
id: 3074
title: To Ann Maria Carter Smith
date: '1855-11-01'
display-date: Novr 3d [1855]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1855/1
---

[Madam](/person/263)[^1]
I shall be very happy to avail myself of your pretty and pathetic tale of [Lucy and Christian Wainwright](/organisation/31) for the [Monthly Packet](/periodical/52) as soon as I can find space for its appearance, but I fear this may not be immediately as I should be sorry to break up the story into several numbers as the effect would be injured.

My [rate of payment ](/topic/102)is 1/6 per printed page, and on putting this into type I will communicate with you.

Allow me to make one remark.

Should not Christian have spoken of a pang long ago on hearing of Col Prescott’s marriage rather than his death?

yours truly

C M Yonge


[^1]: Ann Maria Carter Smith (1835-1909), daughter of the Rev.

Richard Carter Smith (1802-1864), curate of St.

Paul’s, Charlton, and Mary Williamson.

Ann Carter Smith lived at Stepney, but the family had previously lived in Norway; she contributed to MP (1856-90), and published fiction.
[^2]: In envelope addressed to Miss A Carter Smith, Stepney Rectory, London very indistinctly postmarked on reverse.
