---
id: 3092
title: To Ann Maria Carter Smith
date: '1856-12-01'
display-date: Decr 22d [1856]
from-name: Charlotte Mary Yonge
from-address: Otterbourn
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1856/5
---

My dear [Madam](/person/263)
Many thanks for [Wishop](/organisation/257), which looks much improved by the omissions.

The M P was [Sir William Heathcote](/person/669) MP for Oxford, perhaps you will even better like to hear that [Mr Keble](/person/798) could not help listening to the [Thorns and Roses](/periodical/253) with great interest in the middle of his work. I have put out the beginning of Wishop for March, but I cannot make sure of it, as there is a short story which must come in in Lent, and I cannot tell what room there may be.

Will you be kind enough to convey my thanks to [your sister](/person/71) for the note and proof received this morning.

It is hardly worth while to trouble her with a note merely to express my thanks.

yours truly

C M Yonge
I forgot to add my thanks for the return of the postage stamps.

If ever Mrs Atkinson finds time for Tradition 6th it will be welcome, but I never reckon on contributors after marriage - like the inspectors of schools who complain that so many school-mistresses 'yearly are lost to the profession' by marriage[^2]


[^1]: Envelope addressed to Miss Anne C Smith/ Stepney Rectory/ London and postmarked Winchester 23 Dec and on reverse 1856
[^2]: Ann Carter Smith\'s recently-married sister Frances Atkinson, paid for contributions to MP, was evidently the author of the five articles on ‘Traditions of Norway’ MP (July1855-February 1857), signed \'S. R. L.\' The Carter Smiths had lived in Norway.
