---
id: 3102
title: To Anna Butler
date: '1857-06-15'
display-date: June 15th 1857
from-name: Charlotte Mary Yonge
to-name: To Anna Butler
manuscript-location: MS Mrs Caroline Fairclough/13
---

My dear [Miss Butler](/person/237),
I certainly do like the [Likes and Dislikes](/organisation/248) so much that I consider my self selfdenying in what I am going to say, and you will consider me servile, but I really believe that the [Packet](/periodical/52) must [steer clear](/topic/154) of Puseyite name and discussion, and do what it does silently.

So I suspect, with all thanks, that it will be wiser for Emily to stand alone, and yet I am sorry to part with her, and admire what does not suit me to put in.[^1] But somehow Lucy & Charlotte are rather too much the same type as my Lucy and Sophy[^2], and the [Object in Life](/organisation/5)[^3] which is just begun gets on the same ground and I think it better to have things more entirely in different lines in at the same time.

The last form of the Stamp myth is a gentlemen who is to give a nomination to Christ’s hospital to a widow’s son.

Also I hear that one of the generous collectors was found erasing the postmarks!

The novel criticisms are great fun, and very true.

After all perhaps I am more afraid of what may come than of what there is, but on the whole I think you will go on more freely without the packet to trammel you, and I am very anxious to know what cure you devise for the prejudiced old uncle. I should doubt his ever being cured.

Would you or could you send me an outline of the future course of the story, that is if you had rather it did appear in the Monthly Packet, and then I might be better able to judge

yours sincerely

C M Yonge


[^1]: The first part of Butler’s novel Likes and Dislikes had appeared in MP ( July 1855-November 1856). CMY is evidently refusing to publish the second part.
[^2]: Lucy and Sophy are characters in CMY’s [The Young Step-mother](/book/38), which was serialized in MP (April 1856-December 1860) and published in an abbreviated version in 1861.
[^3]: An Object in Life ran in MP (July 1857-December 1858) and was published as An Object in Life.

By the Author of Sunlight in the Clouds (London 1860).

The author was perhaps [Harriet Lucy Cox](/person/375)
