---
id: 3107
title: Anne Yonge to the Rev. John Yonge
iso-date: '1857-09-26'
display-date: 26 Septr 1857
from-name: Charlotte Mary Yonge
from-address: The Royal Hospital
to-name: Anne Yonge to the Rev. John Yonge
manuscript-location: MS Plymouth and West Devon Record Office 308/123/25
---

My dear [Papa](/person/1623),
[I](/person/1582)am much obliged for your notes this morning; and I do not much expect now that [John](/person/1619) will join our festivities. It wd have been very nice and pleasant if we could all three have come together, [Jane](/person/1042) expresses great disappointment that there has been no time to arrange things in any orderly manner. She wd have had no thought but of John & [Cordelia](/person/1590) being here, if it had not been for the haste & hurry that ensued on the chance of going to India; & when I was coming they thought Cordelia’s illness was so serious, he wd not think of leaving her. [^1] I dont think he wd find himself in the way, for people seem to go on very independently of each other. It is only [Capt. Moore](/person/1041) who dislikes the rout & fuss, & might wish fewer to be in the house, but really by the time John came it wd not much matter. They do not object at all to [Mr Drummond](/person/1340) so John may make himself quite easy & comfortable on their account in that matter.[^2] With two or three others in the house, & generally a stray gentleman or two at dinner, he is a great help & amusement & so pleasant & kind in all the little Expeditions we have made. He is always in time & in his right place even when every one else fails, & he and [Graham](/person/321) at other times entertain each other. This I hope will reconcile John to the fact of his being here. [Zachary](/person/1777) I suppose is ignorant of the Wedding day (Wednesday 30th Septr) for he writes to [Aunt Seaton](/person/314) to ask if they will be quite alone on Tuesday eveng for having no fitting suit for company, he can only pay them a flying visit in his way back to England & will dine & sleep that night. I do not know what reply she will make. We have had beautiful weather since we have been here & I hope you have not found it too hot at home but work has by no means failed you & I am very sorry [the Bishop](/person/1778) cost you two unpleasant expeditions in addition to other things wh cant be avoided. I hope you do not read or write more in consequence of my longer absence but the evenings are already lengthening & I fear your readers as usual grow sleepy. I do not think there will be any further changes now in the wedding day, as all the invitations are sent & Capt Moore’s visit to London will be deferred to a future opportunity, His Regiment embarks at Gravesend I believe on the 2d Octr. I believe he is very sorry indeed to exchange it for another, but [Uncle Seaton](/person/313) & all but Jane were provoked at his making any difficulty about it. I have proposed to [Uncle Edd](/person/1602) to go to Killarney on Friday & Saturday, return here for the Sunday, and cross over to England on Monday (5th I believe)[^3] Charlotte cannot stay a moment later than that, but is anxious about Killarney & for its sake wd not make a point of flying back to [Aunt Fanny](/person/1606), as instantly as she otherwise would after the wedding. They have exact guides & explanations of the route here, with minute directions for the different points to be observed in a two days or three days visit. If we find the former not quite enough, we might go on Thursday afternoon instead. Jane wishes [Cordelia](/person/319) could go with us, to cheer her up a little & perhaps she will.[^4] You must tell me if this plan is what you like & wish, or if you wd rather we came home at once, after being here already so long. Has [Duke](/person/1599) given up all thoughts of meeting us at Manchester? for Monday or Tuesday wd be a convenient day to him & he need not be absent from his Parish long. I will let him know whether we are likely to cross in the morning or afternoon of Monday. Uncle Edd of course wd take me, but he has no interest in the pictures himself. He says he is not tired of his life here & continues to amuse himself in various ways, but I have no doubt he will be glad to return to the more natural habits of his own home. Last night he was made to play at Whist & very often he is entrapped in a game of proverbs or such like, wh always go on when any one is here, or spelling words, I mean like Francis. He thoroughly enjoyed the Review I think as indeed every one must have done, the day was so fine & the brilliant green of the grass & low bushes & shrubs through which the soldiers came ?flowing for after one of the repulses was a beautiful contrast to the scarlet of the Coats. They say Uncle Seaton had the review on purpose to amuse [Miss de Salis](/person/415) & us, at this time of year he does not often have them, & it was rather a melancholy sight for all these troops will soon be going to India & the Militia are to be called out instead. One charge of the four regiments of cavalry all in a body far exceeded any of the sights I saw at Chobham. It was on an immense open space of green grass soft & short as a mown lawn & a very gentle ascent. On the top a line of trees, within which were our carriage & one or two others. Under no circumstances cd we have had a better view of the thing, for they came at their fullest speed in a straight line towards us. You cannot imagine the tremendous effect, far beyond the rush of the express train under our feet on that little Bridge. On they came, with a thundering noise & clatter of hoofs sounding hollow on the turf, & at a pace wh made them grow on our sight at each second. I wish I knew how many paces they galloped but it looked to me almost as much as the whole length of the meadow, or at least from the higher to the lower corner of it, & it did not contribute to our ease of mind to see Graham & Uncle Edmund in the very centre of the space, only slowly crossing it when the charge began. Graham set spurs to his horse in a moment, & went off at a slope, & I saw he wd be away in time, but Uncle Edd on a great white steed of Uncle Seaton’s was more deliberate & [Elizth](/person/320) gave him up for lost & covered her eyes He did escape & I believe thinks there was no danger, but I cd not watch him once my eye had been attracted by the advancing troop They came up quite close to us the horses were much exhausted for a few minutes snorting & panting for breath. Then they wheeled off to the right & to the left. The men must be very sorry to leave their fine horses, but such are their orders, & to get fresh ones in India. We had the Scots grey 1st Dragoon Guards & the Lancers, the 94th foot & I believe the 16th but I keep on forgetting. [Capt Prendergast](/person/1779) dined here last night, a man whom At Seaton says is dying to be aide de camp in [Capt Middleton](/person/1780)’s place, rather slow & quiet. I was wishing all day you dc have seen the review so near home it wd not have tired you & the park itself is so very pretty and of ?ing extent.
It was said yesterday (by the maids) that the Irish were going to rise [like the Sepoys](/topic/134) & that the streets were all placarded to that effect, but Uncle Seaton only laughed heartily at the report & at Elizth for giving any heed to it.
I suppose the leaves on the Trees are turning with you, here they are still quite green & the grass so very fresh & bright, not a bit scorched. I hope you have settled your business satisfactorily with [Mr Cornthwaite](/person/1781) I suppose [Croad](/person/1782) will think it too late to go to Guernsey now. The 27th last year was the day of that frightful storm of wind & sea at Sidmouth. We shall be fortunate if we cross as pleasantly the second time as the other day. Uncle Edd thanks for yr note. I do not know if he will write to you today or not. Jane ought to have thanked you for yr gift, but she does not do half she wishes & fully intended that the first thing last Monday.
Goodbye This bad writing is not likely to benefit your eyes but believe me your affect daughter
Anne Yonge


[^1]: CMY and Anne Yonge were both staying with Lord and Lady Seaton in Dublin, to attend the wedding of their cousin the Hon. Jane Colborne to Captain Alexander Montgomery Moore (1833-1919). Lord Seaton was commanding the army in Ireland.
[^2]: George Stirling-Horne-Drummond (1813-1876) of Blair Castle, was the widower of Mary Hay (d. 1855), sister of Cordelia (Hay) Yonge, wife of Anne’s brother John Bargus Yonge. John and Cordelia were not present. The Hays were relations, daughters of William Hay (1788-1876) and Mary Garstin (d. 1863), first cousin of Lord Seaton, Aunt Duke and Aunt Yonge.
[^3]: ‘Uncle Edd’ was presumably Vice-Admiral Edmund Yonge (1795-1868), brother of Lady Seaton and John Yonge, who lived near Plymouth and was perhaps escorting Anne.
[^4]: Cordelia Colborne, who was about to lose her sister Jane.
