---
id: 3109
title: To Frances Mary Yonge
date: '1857-10-01'
display-date: October 1, 1857
from-name: Charlotte Mary Yonge
from-address: Royal Hospital [Dublin]
to-name: To Frances Mary Yonge
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i> 210-215
---

My dear [Mamma](/person/1606)
The day is over, and a most satisfactory and prosperous day it was; if people are to have a grand wedding it should be just such a one.

You heard of us till just after the real breakfast, from which time [Miss de Salis](/person/415), [Anne](/person/1582) and I worked at the flowers and wedding presents till twelve, when we dressed, and Jane came to Miss de Salis’ room to have her veil on.

She had been rather knocked up upstairs and had a dose of our sal volatile, but she was quite composed and like herself, and looked as nice as could be.

Then little [Constantia Wood](/person/1786) arrived driven up in a perambulator, looking like a little queen, with her [father](/person/1784) and [mother](/person/1785) walking behind.

Everybody was in full uniform, [Lord S](/person/313). with three stars and three crosses.

When Jane was ready we went down into the end room.

All the doors being open the length is grand, and it is like the Speaker coming up to the Queen to go from the end room up to the chapel.

Jane and all the bridesmaids were shut into the end room, and paired off, [Elizth](/person/320). and [Delia](/person/319), [Anne](/person/1582) and me, Miss de Salis and Lady Barbara, the two Miss Gascoignes, and [Alethea](/person/317) and Constantia[^1]; after them two pretty little girls, [Lady Anne](/person/1288) and [Lady Rachel Scott](/person/1289), whom [Lord Clonmel](/person/1787) would not allow to be bridesmaids, but were in muslin and blue, looking very nice.[^2] Lord S[eaton]. came for Jane, and marched off so fast that our procession became a race almost.

After us came Aunt Seaton with [Lord Carlisle](/person/255), and how the others came I cannot say.

All the indifferent ones had been sent into chapel first, so it was only the family.[^3] [Captain Moore](/person/1014) was gone on with [Graham](/person/321), and his best man, [Major Learmonth](/person/1788).

The grand thing was that in the hall were ranged all the old pensioners, making a long line on each side of the space, all in their red coats and cocked hats, which they wear broadsided like a beadle.

It was a magnificent spectacle, and so suited to the military wedding.

There are three high steps up to the altar, so Graham stood beautifully above us, Captain Moore and Jane on the top step, then Lord Seaton next below, and we all spread out in a semi-circle.

Graham read better than I ever heard that service, and except that Captain Moore was in too great a hurry with the ring, nothing could have been more perfect than their action; Jane's bending, shrinking towards him was the prettiest bride-like thing I ever saw.

The picture was perfect, the bright-painted window above the dark, almost black oak carvings - Corinthian columns with festoons, in the Grinling Gibbon [sic] style - the wide chancel, Graham looking so tall and well in his surplice and scarf; Jane's slim bending figure, Captain Moore upright and soldierly in his scarlet staff uniform, and his best man in dark cavalry blue; Lord S[eaton]. of course most beautiful, white-haired and upright, and then the half-circle of bridesmaids, all white picked out with blue, as pretty a dress as could be.

Of course I could not judge of more than what was before me, but that was very pretty - nay, a great deal more. A deep recess under a window in the hall is used for a vestry, and there all the signing was done, and it was the most perfect picture of all - Jane leaning down and signing, Graham in his surplice in the chair, and Lord Seaton's scarlet just giving a sort of cameo setting to the two figures, and his grey head towering above.

The Lord Lieutenant came into the said recess, and kissed her hand.

He and [Lord Cardigan](/person/1789), [Major Freke](/person/1790), Colonel Wood, and [Mr.

Drummond](/person/1370) signed, so, as Graham says, all nations were represented.[^4] Then we paraded into the drawing-room, and stood while the place was filling with everybody in the world, or in the army, Jane and Captain Moore sitting in the ante-room to receive the select.

After all, her courage was up to go into the breakfast with the Lord Lieutenant, Aunt Seaton with Captain Moore, Lord S[eaton]., [Lady Howth](/person/727), Lord Cardigan, Lady Cheedlemont, then the herd, male and female after their kind, as Mr.

Drummond said. [^5] I fell to Mr. [Currie Connellan](/person/365), and had [Sir Richard Dacres](/person/399) on the other side - a fine hearty weather-beaten old soldier, whom I had got rather acquainted with at the dinner-party and the Curragh, and so I was very happy and comfortable, except that the band was too near for us to hear ourselves speak.

I forgot the giving of favours which was in the hall, after the signing.

We ran about with them and the pins, and I luckily fell upon people I rather knew than otherwise.

The most remarkable event was Miss de Salis catching [Mr.

Hare](/person/1791) with a bridesmaid's favour on.

Little Alethea looked very pretty and exceedingly solemn all the morning. [Reginald](/person/318) and [Lionel](/person/323) were greatly at their ease, and Lionel chose to trot about on his own feet in the midst of the throng in the most independent way.

The two little bridesmaids were the prettiest little fairy things that could be. [Lady Maria Scott](/person/1287), whom we remember so pretty and little at [James](/person/315)'s wedding, has grown very pretty and graceful.

She was at the table; her two sisters and little brother dined separately, ran about and looked on, the little blue visions peeping out of the drawing-room every now and then.

It was a great horse-shoe table, holding 116 people, without the least crowding or discomfort, and the scene was as pretty as anything of the kind could be.

The Lord Lieutenant made what might well be called a great speech, quite short, and saying how well the scene suited the occasion, the temple of Mars transformed into the bower of Hymen; then came all sorts of good wishes of happiness, prosperity, and peace to the young couple, and though peace might not be the most appropriate wish for a military man, he hoped that if peace should not continue, the bride would prove to be the wife, as well as the daughter, of a hero.

Wherewith he stopped, and Lord S[eaton]. and Captain Moore each thanked without attempting speechifying.

Lord Cardigan was to have proposed the bridesmaids' health, and the best man was in the agonies of composition of a reply, but Jane made the merciful blunder of getting up too soon, and carrying us back into the drawing-room, by which I hope 'our health may not be indamnified.' The cake, a magnificent structure, over which [H.](/person/1359) had heard four Frenchmen chattering, followed us, and I unluckily was caught near it, and made to make the first incision with the help of Major Learmouth.

And then soon after came the Lord Lieutenant and spoke to me (Aunt Seaton had introduced me before, and I had made a curtsey as well as nature or art would permit, and thought of Miss Brontë.[^6] I was all the better that none of our own party were near to mark my flounderings, so he talked politely of how long I had been here, etc., and said I came from a very pretty county, so I found he meant Devon, and had to explain it was Hants, whereupon he asked if [Barchester Towers](/organisation/169) was taken from Winchester, and I said some of the circumstances but not the people, and he supposed I should think it flippant.[^7] Then he hoped I should not be idle, and asked if a plot was not the hardest part, to which I said, ‘all ladies found it so except [Miss Austen](/person/76),’ and he answered, ‘I am glad to hear you speak with respect of Miss Austen,’ and then after a little more as to how long I was going to stay, it came to an end, and I made my escape to Uncle Edward, and got into the recess by the garden door, where we could not get out again, and reviewed all the company as they took their departure.[^8] Then the bride and bridegroom came downstairs, Jane looking so nice and natural that I did not recollect what had happened at the first moment.

They had their dinner with us, all looking on and talking and laughing over the humours of the day, and looking at a beautiful perfectly-fitted travelling bag given by Captain Middleton, which we think the most perfect of the wedding presents, not excepting Lord Cardigan's diamond ring.

It was especially comfortable to have them so quietly after all the fuss, and to have the talking over so pleasantly.

One wonderful adventure was the finding a scared half-witted seeming man, respectably dressed, curled up in one of the recesses of the hall. A policeman was sent for, and James sent down to the address he gave to see if the account he gave of himself was true, though nobody could make much of it.

We all peeped at the man as a curiosity through the curtains between the hall and drawing-room, and Miss de Salis mercifully stepped out and took him a bit of cake and glass of wine, which unloosed his tongue, and he told them that he had wandered home from a party, half drunk, without knowing what he was about, got in there, and fell asleep, when he was waked by the band and all this pageant.

The best of it was that all the people round took him for a detective and were on their good behaviour!

If you could but have seen how very pretty Anne looked with her bright colour, wreath and veil, and how well she got on with everybody, you would have been delighted.

Afterwards, we all sat in the drawing-room, and Delia, Mr.

Drummond and I plunged into that favourite element of ours, Italian history, and the genealogy of the Borgias. I am sorry to say it was the last of it, for Mr.

Drummond went early this morning to the Giant's Causeway.

He has been a very agreeable ingredient in the visit, and his Italian history is wonderful. I think [Julian](/person/1624) would like him very much, and if ever he goes to Dunse I hope he will meet him.

Meantime if you do not hear to-morrow, conclude that we are at Glendalough.

On Saturday or Sunday I will write about home-coming.

It is just possible that if Miss de Salis knows for certain that she shall cross on Tuesday I shall wait for her, but she depends upon her eldest brother, and if it is doubtful I will not wait.

The other brother sails on the 5th for India.

Will you be so kind as to send an abstract of this to [Susan Nelson](/person/164)?[^9] I promised Delia that I would give her an account, and I much afraid I shall hardly manage even one for [Mary Coleridge](/person/351). [Mr.

Matcham](/person/1792) was there, and always went by the name of Captain Moore's uncle, so that if I had not known who he was no one would have got at his name at all. I have just been writing out the marriage for the Times, funny work.

Jane's direction is Birt, Athy, and you must mind that her surname is Montgomery Moore. I promised her that you should write. I do think it is a most perfect marriage, quite satisfying me as to the matchableness of the two people, and that is much to say where Jane is concerned.

We are going to Dublin after luncheon.

Meantime this long letter has made me miss the post, but if you don't send to Winton that will not matter.

Miss de S[alis]. made Jane put the cake through her ring nine times, and we all sleep on it. I did not dream at all, being much too sleepy, and nothing else has transpired but from Miss de S[alis]., that her brother asked Mr.

Currie Conellan to dinner, and he could not come because [Taylor](/person/1793) the poet[^10] was staying with him.

Miss de S[alis]. and Anne were the beauties of the bridesmaids.

Your most affectionate
C. M. Y.


[^1]: Jane Colborne\'s bridesmaids were her elder sisters the Hon.

Elizabeth Colborne (1818/9-1882) and the Hon.

Cordelia Anne L\'Estrange Colborne (1824/5-1862), CMY, Anne Yonge, Miss de Salis (perhaps Anne Sophia Elizabeth de Salis, 1832-1916), Lady Barbara (perhaps Lady Barbara Leeson, 1831/2-1919), the Miss Gascoignes (perhaps Evelyn Henrietta, d.1922, and Helen Gascoigne, 1836-1919), and two little girls, her niece Alethea Elizabeth Catherine Colborne (1852/3-1927) and Constantia Wood (b.1851).
[^2]: Jane Colborne\'s eldest brother, James Colborne, later 2nd Baron Seaton, and John Henry Scott, 3rd Earl of Clonmell (1817-1866), had married sisters: the little girls were Lady Rachel Mary Scott (d. 1911) and Lady Annette Louisa Scott.
[^3]: George William Frederick Howard, 7th Earl of Carlisle, Lord-Lieutenant of Ireland (1855-8 and 1859-64).
[^4]: England, Scotland, Ireland and Wales, that is.

Colonel Wood was a member of the old Welsh family of Wood of Gwernyfed.

The Scotsman was George Drummond.
[^5]: Lady Cheedlemont is transcribed thus by Coleridge, but perhaps Anne (Bermingham), Countess of Charlemont (d. 1876).
[^6]: The Lord-Lieutenant, as the Queen\'s representative in Ireland, was treated like royalty.

Elizabeth Gaskell, [Life of Charlotte Brontë](/periodical/70) (March 1857) had quoted the letter (2 June 1851) in which Brontë describes Lord Carlisle coming up to her and saying ‘”Permit me, as a Yorkshireman, to introduce myself.”’ The Rev. [J. E.

Austen Leigh](/person/78), in his A Memoir of Jane Austen (London: Bentley 1870) quotes part of a poem by Lord Carlisle (then Lord Morpeth) praising Austen\'s novels which had been published in The Keepsake (1835).
[^7]: The Hiram\'s Hospital plot in Trollope\'s [The Warden](/periodical/170) and [Barchester Towers](/organisation/169) was partly inspired by the scandal over the funding of St.

Cross Hospital outside Winchester.
[^8]: Perhaps a mistranscription by Coleridge of \'Uncle Edmund\': Lady Seaton\'s brother, Vice-Admiral Edmund Yonge.
[^9]: The Hon.

Susannah Nelson (d. 1900), youngest daughter of Thomas Bolton (1786-1835), who took the surname Nelson on succeeding (1835) as 2nd Earl Nelson; she married in 1865 the Rev.

Alexander Blunt.

Horatio Nelson (1758-1805), the naval hero, was created in 1801 Baron Nelson of the Nile, with special remainder to the heirs male of his brother and his two sisters.

Upon his death the barony was consequently inherited by his brother, the Rev.

William Nelson (1757-1835), created 1st Earl Nelson with the same remainder to the heirs male of his two sisters Susannah Bolton (d. 1813) and Catherine Matcham (d. 1842).

The latter was the mother of Captain Montgomery Moore\'s mother Susanna Matcham (d. 1885).

The uncle referred to here is probably George Matcham (1789-1877).
[^10]: Henry Taylor (1800-1886). CMY admired his historical verse drama Philip van Artevelde (1834), quoted in The Daisy Chain.
