---
id: 3126
title: To Ann Maria Carter Smith
date: '1858-03-28'
display-date: March 28th 1858 [for 1859?]
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ 1858/2
---

My dear [Miss Smith](/person/263),
I meant to have written to you on Saturday, but was hindered.

On the whole I think I should say that your case was more disappointing and vexatious than anything else, and that [Mr Mozley](/person/1065) though his conduct is decidedly provoking did not exactly deserve such strong censure.

You see his view of the case is that if a book do not answer it is no particular pleasure to anyone, and that it is no real injury to retract such a bargain, he having found on enquiry that the chances are against success in his judgement.

You know it is a hazard on his part of not less than £100, so that he surely ought to be allowed to use his judgement in the matter. I do not mean that he ought not very decidedly to have weighed the question more fully, and have made his enquiries before his acceptance, and that it would have been pleasanter dealing had he done so, and I am also quite sure that your stories are of a superior order, and that publishers cannot always judge wisely of chances of success, but I now think it would be wiser to hold the tales back a little, till something else may have made your name, than to force on the publication, with the publisher averse to it, & only held by an appeal to his honor.

It is very vexatious, and I am very sorry it has so happened, for I think the stories would have been very nice to give or lend, and you know how fond of them I am.

But I think [Bell and Daldy](/organisation/135) being of Mozleys’ opinion shews that there must be some foundation for it, and that it had better be regarded. I shall be delighted to read from your new story, and if you can send it at once, this is a favorable week for the reading, as my [mother ](/person/1606)and I chance to be alone together. I should be able better to write to [Mr Parker](/person/1143) after having done so. [East London ](/organisation/265)is very popular, and we are all delighted with the Wynnes, who make us quite eager after the [Churchman’s Companion](/periodical/62), as we have not been for a long time.

Henrietta’s bright idleness telling more than poor Barbara’s strong efficiency is excellent - so too is the mother, but I can’t make out whether Gordon is to punish her for spoiling him, or be brought right by the atmosphere of good, as naughty youngests so often are. I have great hopes too of Elizabeth.
I don’t think your 400 pages would be an objection to the [Packet ](/periodical/52)- but the long stories it is engaged to would be one to you, as they would keep you waiting till 1861.

But at any rate I shall have the present pleasure of it!

yours sincerely

C M Yonge
