---
id: 3128
title: To Ann Maria Carter Smith
iso-date: '1859-04-09'
display-date: April 9th 1859
from-name: Charlotte Mary Yonge
from-address: Otterbourne, Winchester.
to-name: To Ann Maria Carter Smith
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1859/2
---

My dear [Miss Smith](/person/263)
The end of Aggesden does not at all disappoint me, I think Frank's gradual self conquest beautifully done, and John not at all less charming than at first. Mary is a very good lesson altogether, and very nicely done. And now for the subject of those two troublesome verbs to lie and to lay. I observe you say 'he lay down his head' and 'I must lay down all my life.[']
Now surely they stand thus-
Verb active				Verb passive
present					present
I lay my head				I lie down
past					past
I laid my head				I lay down
participle				future
My head was laid			I will lie down
	or lain				I must lie down
future
I shall lay my head
I beg your pardon, but really I think you will find that this is right. I rather hope too that you will not let 'to leave' stand as a neuter verb. I do not think the good English of old Lady Merivale's schoolroom should have allowed it. So much for impertinence. Next after having heard so much of Robert Merivale, one is disappointed at his taking no notice of Johnnie's accident, nor feeling the thwarting of his project. Could not Mr Arnold be really refreshed by having to console him when they met in London, and could not he rejoice in the improvement. Surely too he should be accounted for when the family went abroad. Why could not he go with them, and be wheeled to the sights, or have the German baths recommended. It would keep them away, and make it more probable and less selfish, for when Sir Hector was so devoted to that boy, his long absence seems the more strange, as the poor fellow was not even with Netta.
Lord Duthoyle is just like a good young lord, but I think the reviews will be down upon you if you say quite so much of the rank, and the effect it produced. I think you would find [Mr Parker](/person/1143) the pleasanter person to deal with, at least I like his ways the best of all my publishers, and I would gladly tell him what I think of your story, if you like me to do so. I think some such title as 'a tale for the young' might obviate the novellette air. It has been a great pleasure to [my mother](/person/1606) and me, the last chapters we read quite sorry that each page made them fewer. I do wish the [M P](/periodical/52) had space for it at once, the tale is so exactly the thing for it, but it certainly ought not to resemble 'our Margaret' in long lying by. That reading is delightful. But surely you meant St Paul parting with the Ephesians at Miletus.
One thing more, did the Artillery go to India till this last war? John Hughes and his sisters in law are great fun
With many thanks

yours sincerely

C M Yonge
