---
id: 3144
title: From the Reverend John Coleridge Patteson to Charlotte Mary Yonge
iso-date: '1859-03-21'
display-date: 'Kohimarama: Dec. 21, 1859.'
from-name: Charlotte Mary Yonge
to-name: From the Reverend John Coleridge Patteson to Charlotte Mary Yonge
manuscript-location: MS location unknown. Printed in Yonge, <i>[[cmybook:102]Life
  of John Coleridge Patteson]</i> I, 434-8.
---

My dear Cousin,
[I](/person/1155)have received at length from [my father](/person/1156) a distinct statement of what you have given to the [Melanesian Mission](/organisation/30). I had heard rumours before, and the [Bishop of Wellington](/person/4) had spoken to me of your intentions, but the fact had not been regularly notified to us.
I think I know you too well to say more than this. May God bless you for what you have lent to Him, and give us, who are specially connected with the Mission, grace to use your gift as you intend it to be used, to His glory in the salvation of souls.
But you will like to hear how your gift will be appropriated. For three summers the Melanesian scholars lived at [St. John's College](/organisation/138), which is situated on a low hill, from which the ground falls away on every side, leaving it exposed to every wind that blows across and around the narrow isthmus.[^1]
Thank God, we had no death traceable to the effect of the climate, but we had constant anxiety and a considerable amount of illness. When arrangements were completed for the arrival of a new principal to succeed the Bishop of Wellington, the college was no longer likely to be available for the Mission school. Consequently, we determined to build on the site long ago agreed upon; to put up some substantial buildings, and to remove some of the wooden buildings at the College which would not be required there, and set them up again at Kohimarama.
Just opposite the entrance into the Auckland harbour, between the island of Rangitot with its double peak and the easternmost point of the northern shore of the harbour, lies a very sheltered bay, with its sea-frontage of rather more than a quarter of a mile, bounded to the east, south and west by low hills, which where they meet the sea become sandy cliffs, fronted with the red-flower-bearing pohutakawa.[^2] The whole of this bay, the seventy acres of flat rich soil included within the rising ground mentioned, and some seventy acres more as yet lying uncleared, adjoining the same block of seventy acres, and likely to be very valuable, as the land is capitable - the whole of this was bought by the Bishop many years ago as the property of the Mission, and is the only piece of Church land over which he retains the control, every other bequest or gift to the amount of 14,000 acres, having been handed over by him to the General Synod. This he retains till the state of the Melanesian Mission is more definitely settled.
On the west corner of this bay we determined to build. A small tide creek runs for a short way about S. S. E. from the extreme end of the western part of the beach, then turns early eastward, and meets a small stream coming down from the southern hill at its western extremity. This creek encloses a space extending along the whole width of the bay of about eighteen or twenty acres.
At the east end stand three wooden cottages, occupied by the master, mate, and a married seaman of the 'Southern Cross.' At the west end stands the Melanesian school. Fences divide the whole space into three portions, whereof the western one forms our garden and orchard; and the others pasture for cows and working bullocks; small gardens being also fenced off for the three cottages. The fifty acres of flat land south of the creek we are now clearing and ploughing.
The situation here is admirably adapted for our school. Now that we have a solid wall of the scoriæ from the volcanic island opposite, we have a complete shelter from the cold south wind. The cliff and hill to the west entirely shut off the wind from that quarter, and the north and east winds are always warm. The soil is very dry, and the beach composed exclusively of small 'pipi' shells - small bivalves. So that by putting many cart-loads of these under our wooden floors, and around our buildings, we have so perfect a drainage that after heavy rain the soil is quite dry again in a few hours. It causes me no anxiety now, when I am for an hour away from my flock, to be thinking whether they are lying on the ground, forgetting that the hot sun overhead does not destroy the bad effect of a damp clay soil such as that at St. John's College.
[The buildings](/organisation/139)at present form three sides of a quadrangle, but the south side is only partly filled up. The large schoolroom, eighty feet long, with three sets of transepts, has been removed from the College, and put up again so as to form the east side of the quadrangle. This is of wood; so is the small wooden quadrangle which serves now for dormitories, and a part of which I occupy; my house consisting of three little rooms, together measuring seventeen feet by seven. These dormitories are the southern side of the quadrangle, but do not reach more than half way from the east to the west side, room being left for another set of dormitories of equal size, when we want them and can afford them. The west side consists of a very nice set of stone buildings, including a large kitchen, store room, and room for putting things in daily and immediate use; and the hall, which is the northern part of the side of the quadrangle, is a really handsome room, with simple open roof and windows of a familiar collegiate appearance. These buildings are of the dark grey scoria, almost imperishable I suppose, and look very well. The hall is just long enough to take seven of us at the high table (so to speak), and thirty-four at the long table, stretching from the high table to the end of the room.[^3]
At present this is used for school also, as the carpenters who are making all our fittings, shelves, &c are still in the large schoolroom. We take off the north end of the schoolroom, including one set of transepts for our temporary chapel. This part will be lined, i.e. boarded, neatly inside. The rest of the building is very rough, but it answers its purpose.
In all the stone buildings, the rough stone is left inside just as it is outside. It does not look bad at all to my eye, and I doubt if I would have it lined if we had funds to pay for it.
I hope eventually that stone buildings will take the place of the present wooden schoolroom and dormitories; but this ought to last for many years. Here we live most happily and comfortably The climate almost tropical in summer. The beautiful scenery of the harbour before our eyes, the smooth sea and clean dry beach within a stone's throw of my window. The lads and young men have their fishing, bathing, boating, and basking in the sun, which all day from sunrise to sunset beats right upon us; for the west cliff does not project more than a few yards to the north of us, and the eastern boundary is low and some way off. I see the little schooner at her moorings whenever I look off my book or my paper, and with an opera-glass can see the captain caulking the decks. All is under my eye; and the lads daily say, 'College too cold; Kohimarama very good; all the same Bauro, Mota,' &c., as the speaker belongs to one or other of our fourteen islands represented. . . . The moment we heard of your gift, we said simultaneously, 'Let it be given to this or to some specific and definite object.' I think you will like to feel not only that the money came most opportunely, but that within the walls built with that money, many many hundreds, I trust, of these Melanesian islanders will be fed and taught, and trained up in the knowledge and fear of God . . .
Your affectionate Cousin,
J. C. Patteson


[^1]: Charles Abraham.
[^2]: The place is now a suburb of Auckland called Mission Bay.
[^3]: This building is currently (2007) occupied by the Mecca Stonehouse cafe, 44 Tamaki Drive, Mission Bay, Auckland.
