---
id: 3162
title: To George Lillie Craik
iso-date: '1890-08-04'
display-date: Aug 4th 1890
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To George Lillie Craik
manuscript-location: 'MS British Library Add MSS 54921: 180-83'
---

Dear [Mr Craik](/person/379)
I much fear that you may be, like all the world, taking holiday for there is a scheme on which I much wish to consult you and Mr Macmillan, and which needs to be matured before the Church Congress in October.
I must explain that a good while ago, a society [was started] for raising the tone, religious and moral of the cottage women in a Hampshire town-village. This has spread till now it is a very considerable society, called the [Mother’s Union](/organisation/31), and comprising a great number of women of all ranks, ladies as well as poor women, ladies for their own sakes as well as merely as an example. You will judge of the numbers from the fact that the [little paper](/periodical/93), which is the ‘organ’ has a circulation of 20 000. This is intended for poor women, but it has been found that the educated class of mothers are quite as much in need of practical instruction as the poor.
[Mrs Sumner](/person/1381), the wife of the [Bishop of Guildford](/person/1382) who is the originator and president of the Society is therefore very desirous of setting on foot a [paper](/periodical/82) for the purpose, of which (faute de mieux) I would be the Editor.
Our present view is that it should be quarterly, but not so large as to cost, at the outside, more than 4 pence a number - That the papers should not be serials - so that each number should stand alone, and could be given singly - That each should contain three varieties of counsels - or essays - one on the nursery period one on that of education one on questions concerning youth. Besides these such miscellaneous papers as there might be room for, notices of useful books &c we could get papers from experienced persons and good writers and through the society there would be little or no doubt of securing some circulation from the first. This diocese has 1000 lady members, and there are many more elsewhere, and though of course they could not be compelled to take it in, they would almost certainly do so. As it ought to be got up not expensively it would be almost certain to answer.
The Society, the Mothers Union by its Working Council, ought to remain the proprietors as they must have the control of the articles and management and appointment of the Editor.
Now would you undertake the publication and pushing at a percentage. Or if not advise us to whom to apply. It is a bad time of year for consultation and we should not actually start till the New Year, but there is an opportunity of bringing the subject forward at the Church Congress which is not to be missed.
I hope to send [‘Two Penniless Princesses’](/book/216) in a day or two, I have been waiting to get the four last chapters put into type but [Clowes](/person/309) who prints the [Monthly Packet](/periodical/52) will not be hurried
Yours very truly

C M Yonge		
There is a [Parent’s Union](/organisation/34) under [Miss Mason](/person/2100) chiefly in the Northern Counties.[^1] And a [Parents Union Monthly Journal](/periodical/218) published by Allen but it is not what we wish.


[^1]: The Parents\' Educational Union (later the Parents\' National Education Union) was established in Bradford in 1887 by Charlotte Mason (1842-1923).
