---
id: 3182
title: To an Unknown Person
date: '1891-01-01'
display-date: '[1891]'
from-name: Charlotte Mary Yonge
to-name: To an Unknown Person
manuscript-location: MS location unknown.  Printed in Romanes, [[otherbook:241]<i>Appreciation</i>],
  192
---

What seems to me to be the fact . . . is that, having been brought up in the Protestant school of thought, and worked out Catholicity for himself, when everybody thundered at the Tracts, etc., he [[John Henry Newman](/person/1084)] thought the fault lay in the Church of England, not only in the blundering of individuals, and he did not wait to see her clear herself.[^1] And then I think that he had, apparently, never thoroughly followed the times between the separation from the Greek Church and the Reformation. [Hurrell Froude](/person/529) was doing it, but there has [sic] been so much less research that H. F. takes for granted that Roman Ritual is necessarily Apostolical, without (apparently) having found out about equally Apostolical rites that Rome had crushed - e.g., Gallican, Spanish, not to say our own Uses.[^2] And now we have all that was like a day-dream to them.


[^1]: John Henry Newman. CMY refers here to Letters and Correspondence of J. H.

Newman during his Life in the English Church ed.

Anne Mozley 2 volumes (1891) [1890].
[^2]: Richard Hurrell Froude (1803-1836), friend of Newman and Keble, died young of tuberculosis.

His [Remains](/periodical/98) 4 vols (1837, 1839) influenced the development of the Oxford Movement.
