---
id: 3199
title: To Alice May Gordon
iso-date: '1892-07-10'
display-date: July 10th 1892
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne Winchester
to-name: To Alice May Gordon
manuscript-location: MS Girton College Cambridge, Yonge XIV 2
---

Dear [Mrs Gordon](/person/572)
What a work you have been doing at York! Here in our county division, we had no opposition to an old [Conservative member](/person/2115), so we were saved all the battle and heartburning; Winchester elected its Conservative, and Southampton our [native squire](/person/2114) - It is a most agitating election, and oh! How dreadful it would be to have a triennial parliament.
I have finished Eunice and she gives one a great deal to think about. The children and their mother are delightful, and the hint about putting out one’s finger to help Providence is a very valuable one, So is the shewing poor Eunice’s want of foundation, and want of power to repel the stings - while Polly’s selfish sense of safety without repentance repels her more. How curiously it is the extremes meeting the Indulgence sparing the trouble of repenting in the same way.
[Miss Coleridge](/person/329)’s permanent address is Cheyne Torquay, but she is at Malvern just now. If she spends any time in London on her return I hope she may have a talk with you
Yours very truly
C. M. Yonge
