---
id: 3223
title: Isabella Lucy Bishop to Charlotte Mary Yonge
date: '1893-07-01'
display-date: Edinburgh, 1st.July 1893
from-name: Charlotte Mary Yonge
from-address: MUSEUM OF SCIENCE AND ART,
to-name: Isabella Lucy Bishop to Charlotte Mary Yonge
manuscript-location: MS UCLA collection 100 box 119/2
---

Nestorian Tablet in China
The Museum possesses a rubbing of the inscription on this tablet, presented in 1886 by the [Rev.

James Stevenson](/person/2126), of the China Inland Mission.

In the Museum Library may also be seen:—
‘The Middle Kingdom,’ by Dr S.

Wells Williams: London, 1883. A translation of the tablet is given in Vol. II., pp. 277-285, with other information.
‘The Nestorian Monument … in Shen-hsî, China ... with the Chinese Text of the Inscription, a Translation, and Notes, and a Lecture on the Monument.’ By Prof.

Legge, Oxford.

London, 1888
There is a paragraph on the present condition of the tablet in the Times of 30th May, 1893.

The Elms Houghton Huntingdon
July 8
Dear Miss Yonge,
[Sir Murdoch Smith ](/person/2125)has kindly sent me the enclosed. I saw the translation of the inscription.

It is very long, high flown and mystical, but very interesting.
I am so glad that your friend was pleased with the stamps.

In gt haste
Yours very Sincerely,
[Isabella L.

Bishop](/person/1817)
