---
id: 3245
title: To the Reverend John Frederick Watkinson Bullock
iso-date: '1894-01-31'
display-date: Jan 31 [1894]
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne
to-name: To the Reverend John Frederick Watkinson Bullock
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e.174 ff 165'
---

Dear [Mr Bullock](/person/221),
I think [Gordon](/person/2090) must have been confirmed, as he was chiefly brought up in England. I see you have marked Bishop Andrews.[^2] Can you tell me of any short biography of him, I have to recommend books for our [Higher Religious Education Society](/organisation/48) - books for that era of James I

I doubt [Miss C Coleridge](/person/329) having time to write for you. But [Miss Anderson Morshead](/person/28) - Industrial School Andover - knew [Bishop Gray](/person/578) well, and could write of him Could write of Abp Sancroft[^3] or [Bp Mackenzie](/person/929) - whose sister [Anne](/person/930) was one of truest saints I ever knew -

I think you should have [Frances Havergal](/person/2091) - She was most devout and good, though not High Church, but most attached to the church. Also [Agnes](/person/2011) - the devoted workhouse nurse, and I do think [Mrs Trimmer](/person/2092) and [Hannah More](/person/1836) ought not to be omitted. Also Lady Falkland[^4]

I have a few doubts whether [Miss Sellon](/person/1294) realised this saintly ideal. However she fought a great battle

Yours truly

C M Yonge

Would [Miss M Trench](/person/1418), the writer of Charles Lowder’s life write him for you?


[^2]: This letter, and others to Bullock, relate to his project for a book called Daily Lections which was only published in part. Lancelot Andrewes (1555-1626), bishop of Winchester was one of the proposed subjects of a section, which survives in MS in the Bodleian library and is there catalogued as [\'Biographies of Eminent Anglicans\'](/book/358).
[^3]: William Sancroft (1617–1693), archbishop of Canterbury .
[^4]: Later letters make it clear that CMY refers to Lettice Cary, Viscountess Falkland (c.1612-1647), rather than her mother-in-law, Elizabeth Cary, Viscountess Falkland (1585-1639), Catholic convert and controversialist.
