---
id: 3251
title: To the Reverend John Frederick Watkinson Bullock
date: '1894-02-19'
display-date: Feb 19 [1894]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To the Reverend John Frederick Watkinson Bullock
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e.174 ff 167-8'
---

Dear [Mr Bullock](/person/221),
I send you Bishop Frampton with your list, and many thanks for it, I hope you have the life of [Fletcher](/person/1677) of Madeley that shews how much braver he was than two soldier brothers.[^1] Your [Mother](/person/2134) may be interested to hear that [Heartsease](/book/19) was the last book [Lord Raglan](/person/1276) read.
[Sir Eustace Stewart](/person/1277) who lent it to him told me

Yours truly

C M Yonge


[^1]: The Rev.

John William Fletcher (1729-1785), vicar of Madeley, Shropshire and friend of John Wesley; he came from a Swiss military family.

The book was probably [Wesley’s Designated Successor: The Life, Letters and Literary Labours of the Rev.

John William Fletcher, Vicar of Madeley](/topic/213) (London: Hodder 1882). CMY had written the life of Robert Frampton (1622-1708), Bishop of Gloucester for the [\'Biographies of Eminent Anglicans\'](/book/358) series which was part of Bullock\'s Daily Lections project.
