---
id: 3258
title: To Alice May Gordon
date: '1894-04-06'
display-date: April 6th 1894
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne
to-name: To Alice May Gordon
manuscript-location: MS Princeton University, Parrish Collection
---

Dear [Mrs Gordon](/person/572)
My books may very well follow the rest of the [collection](/topic/221) to Newnham, I never expected their return and they will be very well there.[^1] I wonder if you will succeed in getting them for the future exhibition!
I am glad you have found such suitable work.

What a profusion of periodicals of all sizes there are, though it shocked me a little that no woman’s paper can succeed without the fashions

Yours truly

C M Yonge


[^1]: Alice Gordon had written to the Editor of The Times (5 January 1893): \'A library has been built in the Women\'s Building of the Chicago Exhibition, in which the best books written by women of all nations are to be exhibited.

We are anxious that English women\'s writings should be well represented. A committee has been formed consisting of Miss Agnes Clerke, Mrs. W. K.

Clifford, Mrs.

Green, Miss Kingsley, Mrs.

Humphry Ward, Miss Charlotte Yonge, and Mrs. J.E. H.

Gordon, to collect a representative library.\' She asked for the gift or loan of books or MSS.
