---
id: 3320
title: To Mary Yonge
date: '1896-03-24'
display-date: March 24th [1896?][[footnote:1]]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Mary Yonge
manuscript-location: MS West Devon Area Record Office Ac 1092/25
---

My dear [Mary](/person/1626)
I hope your headache did not forbode influenza. I have been hoping to hear that you were well, for so much seems to be about, and my dear [Mary Coleridge](/person/351) is entirely prostrated from it, so that the doctor only says she may recover, and she was so weak and helpless before, not able to get up from her chair, or walk without help, that I scarcely dare to have much hope though she is only 72.

She has [Alethea Mackarness](/person/923) and her daughter [Katie](/person/2151) living close by to be with her whenever she is able to have them with her Her maid [Susan](/person/2152) is everything to her and has been for years, but they have a night nurse
And last week there was a great alarm about [Mr Wither](/person/1544) who is 86, he had preached, and taken a funeral, both in his Bath chair, on Sunday week and had sciatica after, which I supposed pulled down his strength for he had faintings and wandered at times in talk.

His doctor says he has long had a certain amount of bronchial disease, and a cold, or faintness might be the end, but he has rallied a good deal now.

Nieces and nephews take time to be with him, but they have families and it is difficult, and his poor old [sister ](/person/1546)is not in health to go to him.

He was much disappointed in the autumn that they could not meet.

She was obliged to put it on her state, but those who knew told her that he was not fit to take the journey.

He is very large and unwieldy and has to be helped out of his chair.

Unluckily he and his Curate have not taken to each other – the Curate having been sent him by the Bishop, and having no old attachments. I fear this day of gusts of snow is bad for them. [ Helen](/person/1613) has seen a great branch of a tree broken off. [Henry](/person/184) has a cold and loss of voice, which is apt to happen when he goes to preach for other people. [Mr Hoets](/person/705) of Twyford gives us very interesting services on Fridays on the Prodigal son – a regular course, which I like much better than chance varieties of neighbours We are going through what you had to do with Mrs Hancy, for [Mrs Bishop](/person/156) is 66, but there is little fear but that she will have a pension
your most affectionate

C M Yonge


[^1]: The dating of the letter depends on its statements that Mary Coleridge (1824-25 March 1898) is 72 and William Bigg Wither (1809-1899) 86.
