---
id: 3328
title: To Clifford Wyndham Holgate
date: '1896-06-02'
display-date: June 2nd 1896
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne Winchester
to-name: To Clifford Wyndham Holgate
manuscript-location: MS Princeton University, Parrish Collection
---

Dear[ Mr Holgate](/person/1643)
This is really only an abridgement of the [article](/book/66) in the Christian Remembrancer, except that I added the going to Winchester College chapel in 1854. I signed the paper because once or twice I found myself writing I to a personal reminiscence, but it can be altered if you wish it.[^1] I think [Lord Seaton](/person/313)’s personal appearance is fully described in the paper.

He was the most striking old man I ever saw.

The best likeness of him is one of [Richmond](/person/1731)’s Crayons. I have an engraving of it, I think the original is at [Beechwood](/place/126), but I am not sure.

There is another print that I do not like so much, and a full length picture which I believe was done for the United Services Club.

There is a print from that but I do not like it - it is in Life Guards uniform and that being cavalry - is apt to look awkward on an infantry man.

There is another small portrait of him at [Puslinch](/place/123), a much younger man - but I never realized it, never having known him till his return from Canada.

My [mother](/person/1606) was [his step father](/person/106)’s youngest daughter, my [father](/person/1631) was in his regiment, and was first cousin to his [wife](/person/314).

Anything about the pictures might best be learnt from [the present Lord Seaton](/person/318), Beechwood Plympton

Yours sincerely

C M Yonge


[^1]: This letter, and the preceding one to Holgate, evidently relate to an untraced article by CMY on Lord Seaton.
