---
id: 3333
title: To Mary Elizabeth Christie
date: '1896-12-08'
display-date: December 8, 1896.
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester
to-name: To Mary Elizabeth Christie
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  338
---

Dear [M. E. C.](/person/294)
I feel strongly impelled to write to you both to thank you for your letter and for St.

Christopher's legend. A German lady once sent me a set of photographs of frescoes of his history, where he was going through all sorts of temptations, including one by evil women.
I think I must tell you that the [Daisy Chain](/book/24) was written just when I was fresh from the influence and guiding of [my father](/person/1631).

Not that he was in the least like Dr.

May, being a soldier with the highest chivalrous sense of nobleness and justice, and moreover with a strong desire to see, and do everything in the best way possible.
I remember his exclaiming, when Norman's health began to fail, ‘You don't mean to kill him?’ and that seems to me to mark how far I had gone on in that story.

The [Heir of Redclyffe](/book/15) he had looked over and criticised with all his might.

Another advantage the Daisy Chain had was, that coming out in monthly parts there was a good deal of friendly, often merry discussion of the characters, with such friends as [Mr.](/person/798) and [Mrs.

Keble](/person/795), [Miss Dyson](/person/464), and [Dr.

Moberly](/person/1015) (later Bishop of Salisbury).

So that external influence had much to do with the developments.

It has always had the best sale of all my books, yet when I read both it and the [Pillars of the House](/book/109) over, for the sake of taking up the broken threads, as well as to see them with older eyes, I found myself preferring the latter, as brighter, and on the whole less pedantic than is the effect of Ethel in parts, and with more of hope throughout.
I think I must mention that [Guizot](/person/597)'s public recommendation of the Heir of Redclyffe led to the only thoroughly spiteful review that ever befell me, in Household Words, written, I imagine, by some blindly jealous admirer of Dickens.
[Heartsease](/book/19) was the last book [Lord Raglan](/person/1276) read, I was told by [Admiral Sir Stewart](/person/1277) who lent it to him.

And [Mr.

Butterfield ](/person/247)was said to be in search of Ethel for a wife.

But [Mrs. T.

Mozley](/person/1062) had set the fashion of reading books on child life.

By the bye, I wish you would write a notice of the [Fairy Bower](/topic/240) and [Lost Brooch](/periodical/78), also of Louisa, with their wonderful cleverness and irony.

Grace and Mary Anne always remind me of [Dr.

Newman](/person/1084)'s controversy with [Kingsley ](/person/816)about truth, the same which resulted in the Apologia.
I have inflicted a long letter on you, but when I once began I could not help going on.

Yours sincerely
C. M.

Yonge


[^1]: There is a biographical account of Mary Elizabeth Christie (1847-1906) in her A Tardiness in Nature and Other Papers (Manchester: Manchester University Press 1907).
