---
id: 3363
title: To Frederick Orridge Macmillan
iso-date: '1897-12-14'
display-date: Decr 14th 1897
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne Winchester
to-name: To Frederick Orridge Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 229-30'
---

Dear [Mr Macmillan](/person/942)
One of my very first ventures in publishing was [‘Kenneth: or the Rear Guard of the Grand Army’](/book/10). [J.H. Parker](/person/1142) of Oxford published it, on the half profits system, I retaining the copyright. There were two or three editions but it has gone out of print, though I am sometimes asked how to get it.
Also, about 1850 and 52, [Masters](/person/981) published[Henrietta’s Wish](/book/11), and [the Two Guardians](/book/13), republished from the [Churchman’s Companion](/periodical/62). Both had fair success, and he gave me £20 and £25 for each successive edition I think three. I have heard no more of them for many years and now I learn that his successor has given up the publishing business and I believe the stock is handed to Mowbray. The Copyright is mine.
I hear of enquiries for the books at times. Would it be worth while for you to try to recover them?
The [Bishop of Quebec](/person/456) has just asked me to let him have a former tale of mine for a Church paper. I have recommended him Kenneth, as there is much adventure but I have come to perceive that there are many mistakes, so that I do not so much care to have it revived as the other two, which I really think worth renewing

Yours truly

C M Yonge
