---
id: 3379
title: To Frederick Orridge Macmillan
iso-date: '1898-07-12'
display-date: July 12th 1898
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne
to-name: To Frederick Orridge Macmillan
manuscript-location: 'MS British Library Add MSS 54921: 245-6'
---

Dear [Mr Macmillan](/person/942)
I am asking [Mr Medley](/person/916) (The Rev John Medley Tyntesfield, Bristol) to write to you direct about his Grandfather’s drawing.[^1] It is rather a question what he may feel able to do, as it does not belong to him but to his cousin. It is in a book, but whether only fastened in, or bound up I cannot tell
I have told him that in either case, book or drawing would be quite safe with you. It is a very beautiful and characteristic sketch and should have [Mr Bacon](/person/2196)’s name.
Here is an addition to be sent to the printer. [Lady Heathcote](/person/665) (being past 80) could not find it at first and her daughters did not like to press the matter, I do not like notes encumbering pages but if the alteration to the text is too much this might go as a note at the end of the first chapter
I send the proofs through [Miss Heathcote](/person/663) so as to be secure from mistakes, as she is much more accurate than myself, besides having local knowledge on the Hursley side

Yours truly

C M Yonge


[^1]: The Rev. John Medley was presumably the son of Christina Bacon and the Rt. Rev. John Medley (1804-1892), bishop of Fredericton.
