---
id: 3412
title: To Christabel Rose Coleridge
date: '1899-07-01'
display-date: July 23d [1899]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels/76
---

My dear [C C ](/person/329)
If I were to be dissected while I am alive, I think you would do it tenderly, but indeed I have always shrunk from seeing the lives of living people and my whole old fashioned nature revolts at the idea partly personally, and partly because I know how those who are gone would feel about it, so indeed I do not think it is possible to my feelings and I hope you will not be vexed.

We are overwhelmed with applications for the Infant school at Allbrook, having advertised in the [School mistress](/periodical/212).

One offers herself from Stirling!

She would be odd here I think.

We have [Mrs Sumner](/person/1381)’s presentation next week, all the mothers in the diocese to drink tea at Wolvesey, and the week after our bazaar for the schools- after which from the 3d to the 6th, I go down to the Heathcotes at Beechwood and on the 10th [Annie Moberly](/person/1024) comes to me for ten days, and I shall get a dip in Oxford news.

Mr [Cosmo Lang](/person/2089) made a splendid speech at the [Higher Religious Education](/organisation/48) meeting.
[A D I](/person/744)’s promises dont seem to come to anything only he says his company won’t let him get at the money to pay his debts till all is paid in.
I wonder if it would do any good to send a lawyer to call on him or if it would be only sending good money after bad.

He has given no account for my own books, as well as /contributions to\ the [M P](/periodical/52).

If you are not paid for all this past year, I wonder you do not strike but he keeps on pacifying you.

You never mentioned Alice.
your affectionate

C M Yonge
