---
id: 3418
title: To Christabel Rose Coleridge
iso-date: '1899-08-15'
display-date: '[15 August 1899]'
from-name: Charlotte Mary Yonge
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels/79
---

My dear [C C](/person/329)
I am sure unless we could get an amount of subscribers enough to start a new Church [Packet](/periodical/52) with security, it would be vain. Could we find out? Otherwise [Sir W Besant](/person/1652) is right, and we must acquiesce. I would make [Duck’s Eggs](/book/251) a fresh start for it is needed, but I think it is not hopeful, sorry as I am, especially that Church should be a decided drawback.[^2] If it eschewed Controversy Churchbuilding charity and saints I should think it might get on But men such as [Canon Ashwell](/person/68) are hard to catch in these days [FMP](/person/1160) has changed her mind and says she won’t come, but is going to India . I have written to beg her to meet me at Waterloo and come home with me on Friday but I don’t know if she will.
I have excogitated a new end for Ducks Eggs working in the old friends. All were going out to Carrigaboola, via San Frisco- Magdalen- Paula and all, with Angela and the Bishop – also Bernard who – on holiday in England was suddenly wanted for a Travis & Underwood emergency, involving California Ship either wrecked or on fire not far beyond Liverpool ([Annie Moberly](/person/1024) wanted a woman to hide for the sake of saving a more valuable life of Man) Angela dies – putting her Sisters bonnet on someone else. All the women are saved, but Bernard is struck down by a spar left unseen, insensible He comes to himself to find Angela hanging over him, the golden curls looking like her childhood. They think they are going together, but a Ewemouth collier picks them up in time- Bernard lifted into unconscious but Angela falls in lifting him into the sea
Phyllis had had to be left at home- So you have the account in Bernard’s words to Clement
your affte

C M Yonge


[^2]: The working title for the novel which became Modern Broods (1900).
