---
id: 3420
title: To Christabel Rose Coleridge
iso-date: '1899-08-25'
display-date: Aug 25 [1899]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels/82
---

My dear [C C](/person/329)
Here is a behind the times letter that concerns you. I have heard from [Mr Thring](/person/1281), who says I can remove my books with proper notice, but as I don’t know how long proper notice is, I have written to ask, also he thinks there may be trouble about those of which [A D I](/person/744) gives Royalty and on the older ones there is no agreement.[^1] I asked if I ought to wait to write to [Macmillan](/organisation/111) till there is some decision about A D I
I don’t think, on considering it, that [FMP](/person/1160)’s opinion goes for much, she has gone too much out of the range of English life. I doubt [Skeffington](/organisation/110) since the father died, he has been very ritualistic and also silly and sensational and I should question if he had extensive connection enough. [Darton](/organisation/109), if he has a soul for it would be better, and I am sure it is safer to be a mere publisher of principle and good taste and not an aspirant author which was one mistake.
Yes from 18 to 30 is the age to write for, but with a certain view to what might be good or bad for the younger ones who would read also. [FMP](/person/1160) has been staying in Scotland and with [Lady Macclesfield](/person/1655), also [Miss Acland](/person/8) /Oxford\, so she has been seeing varieties. I shall have [Annie Moberly](/person/1024) for a week in September and she is of much use to talk to, though too busy to be any good when her term begins. I did not like to ask FMP point blank, but I doubt her having read [the Long Vacation](/book/237) where I think Emilia, Gillian and Dolores are all essentially modern young ladies. [^2]
The glass is really going down but there is hardly a blade of grass left except under the trees and in the water meadows. Yarrow and plantain, also thistles do what they can
your affectionate

C M Yonge


[^1]: George Herbert Thring (1859-1941), solicitor, Secretary of the [Society of Authors](/organisation/44), 1891-1906. He was the son of Edward Thring, the headmaster of Uppingham whose book on teaching CMY so admired.
