---
id: 3454
title: To Mary Yonge
date: '1900-03-27'
display-date: March 27 [1900]
from-name: Charlotte Mary Yonge
from-address: Elderfield Otterbourne
to-name: To Mary Yonge
manuscript-location: MS West Devon Area Record Office Acc No 308
---

My dear [Mary](/person/1626)
I hope [ Sydney](/person/2178) is as much better as I am, I believe I should be well if the East wind would mitigate itself, but we had showers of snow yesterday, and more looks possible today. [Helen ](/person/1613)has been so good as to come down and look after me as her [mother](/person/1604) has [Mrs Mansfield](/person/952) (Georgina Halliday) staying with her Her husband is an army doctor, and ordered out – and she is a niece they are fond of.

She has been at Aldershot where the [Moores](/person/1041) are in a temporary lodging, as [Lady Audrey Buller](/person/2223) does not turn out of Govt House -–[^1] She – G Mansfield says it is very troublesome, having militia and volunteers who know nothing of real army discipline and don’t like being pulled up –
Helen had a nice courteous letter from [Princess Christian](/person/2222) in her own hand to thank for the things she sent.

Fancy a lady sending for the soldiers a lot of old envelopes to be turned out and used to draw upon! I hope the useful things do get out and not delayed by government arrangements
What flowers [Charlotte](/person/1587) must be seeing
your most affectionate

C M Yonge


[^1]: General Montgomery Moore had succeeded to the Aldershot command on the departure for South Africa of General Sir Redvers Buller.
