---
id: 3463
title: To Christabel Rose Coleridge
iso-date: '1900-07-09'
display-date: July 9th [1900]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels/99
---

My dear C C
There is much to rejoice in in that SW line, poppies meandering streams and all, and Oliver was capable of a welcome. Tory[^1] disposed of three young mice yesterday (What would the Puritan have done to him?) I thought of sending them to the Eastleigh bazaar tomorrow, but they are still too young - [Alethea](/person/182) is come home and had a hayfield party yes on Saturday Her cousin, [Mrs Mansfield](/person/952) is coming to stay with her while the [Vicar](/person/184) is away She was one of the Hallidays her husband is an Army doctor in Africa, his elder sister poor woman has two sons in Pekin.[^2] We had a soldier in his red coat returning thanks yesterday for his safe return and recovery from illness. It looks like coming out at the other end. The Hants paper says [Lord Airlie](/person/1094) was shot through his field glass-
I have got from [Mudie](/organisation/137) Rawnsley’s Life and nature at the English lakes, with a good deal rather impertinently familiar about Greta Hall and all your people and the Southeys. Also the singing competition at Kendal and another competition of the Collies, one by one of course, in driving to the pen, over three miles of hill, three sheep, the shepherd standing still and giving no help but occasionally shouting
[Miss Fin](/person/512) comes back today. She will be in a frightful scramble with only two days to the festival That Salisbury and Exeter train is horrid as to luggage They lost [Emily Blunt](/person/163)’s[^3] bicycle and kept it in a shed till the holidays were over, but had to compensate. What a state Torquay must be in of uncertainty, ecclesiastically and politically.[^4] School time!
your affte

C M Yonge


[^1]: Coleridge, [Life](/organisation/40), 244 states that Vic and Tory were two kittens born on the Queen’s birthday. She herself had a cat named Oliver Cromwell.
[[footnote:2]The Boxer Rising began in Peking on 20 June 1900. Georgina Mansfield was a daughter of Frances Yonge\'s sister [Louisa Halliday](/person/616).
[^3]: Emily Blunt was a teacher at Miss Finlaison’s little school in Otterbourne.
[^4]: The question of who was to be the next vicar of Tormohun was soon solved by the appointment of the Rev. [John Jacob](/person/747).
