---
id: 3594
title: To Christabel Rose Coleridge
date: '1893-06-02'
display-date: June 2 [1893?]
from-name: Charlotte Mary Yonge
from-address: Elderfield
to-name: To Christabel Rose Coleridge
manuscript-location: MS Mrs Clare Roels/112
---

My dear [C C](/person/329)
We cannot find your porcupine, I think he must be shut up in a MS.

Susan, the cook informed me yesterday that she is going to marry in July, rather frantic for she can only get through easy work here with [Bessie](/person/359)’s help however I am glad to be spared the break down that there will be- and Bessie has a sister who will probably come so all will most likely do well, those Collins grandchildren being all of the ‘old retainer’ kind.[^1]
I found the [Higher Religious Education](/organisation/48) wanting to know about giving lectures to the [Reading Unions](/organisation/211), which they were asked to do- so I wrote to [Mrs Chester](/person/1682). I was attacked at once for not coming to luncheon!

The young ladies were away so they forgot to ask me. I settled the [M in C](/periodical/82) business with [Mrs Sumner](/person/1381) You must be glad to leave the real summer heat in London
your affte

C M Yonge
I wish I could find the Porcupine.

How remarkably your correspondent spells.


[^1]: The cook at Elderfield during the 1891 census was Elizabeth Savage (b.

Eling 1836/7), but she does not seem to have been one of the Collins grandchildren, so this letter probably dates from some years later.
