---
id: 9097
title: To Sarah Harriet Selwyn
date: '1885-06-25'
display-date: June 25th 1885
from-name: Charlotte Mary Yonge
from-address: Elderfield, Otterbourne, Winchester.
to-name: To Sarah Harriet Selwyn
manuscript-location: MS Charlotte Mitchell
---

My dear [Mrs Selwyn](/person/1297)
It is quite too good to be true that [your son](/person/1296) should come to take care of us, and that we should have you all here.[^2] There are so few left of your old set of special friends that perhaps you will accept a kind of shadow of them in me. I shall be at home all August and the treat would be exceeding. I should make the acquaintance of your new [daughter in law](/person/1685), and all the children.

And this is a wonderful place for walks in woods and heaths and downs, so that I think they would be very happy.

Then we are in reasonable reach of [Fanny Patteson](/person/1151), and I dothink it would be very pleasant in many ways.

Old [Bishop MacDougal](/person/1948) says he well remembers your [father](/person/1950), and I think he will be still in residence[^3] It was a grand sight to have the old and the young Missionary Bishops together yesterday evening.

Very delightful and memorable it was.

Do pray come, I really think you will be very comfortable and in reach of all manner of pleasant expeditions for the young folk.

yours affectionately

C M Yonge


[^1]: With envelope addressed to \'Mrs Selwyn/ The Close/ Lichfield\' and postmarked Winchester 25 June 1885.
[^2]: The Rt.

Rev.

John Richardson Selwyn, on leave as Bishop of Melanesia, was acting as locum tenens for the Vicar of Otterbourne.
[^3]: The former Bishop of Sarawak was now a canon of Winchester.
