---
date: '1859-06-01'
display-date: June 1, 1859.
from-address: 'Otterbourn, Winchester. '
manuscript-location: 'Text from [[otherbook:781]<i>Report of the Commissioners appointed
  to Inquire into the State of Popular Education in England</i>] 6 vols (London: Eyre
  and Spottiswoode 1862), V, 5-8, 451-55.'
original-date: '2010-11-05 11:26:50'
title: To the Duke of Newcastle and other members of the Royal Commission on Popular
  Education
wordpress-id: 14430
---
Hello!

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[This is the text of CMY’s answers to a printed circular issued by the members of the Royal Commission to Inquire into the Present State of Popular Education in England, led by the Duke of Newcastle, which reported in 1861.

For clarity, the questions on the circular, not all of which she answered, have been added in italics.]

Miss Yonge of Otterbourn.

PRELIMINARY.

1.

What opportunities have you had of gaining experience as to the state of popular education?

To what localities and to what descriptions of persons does your experience apply ?

1.

My opportunities of gaining experience in popular education consist in having had for the last 18 years an intimate knowledge of and share in the management of a [school for girls](../others.html#107) and infants, from fifty to sixty in number, and in being generally aware of what passed in the boys' school.

I have taken great interest in the subject of education, but my answers will not apply to any but the school before mentioned, since no other has come directly under my personal knowledge.

The locality is the parish of Otterbourn, Hampshire, which is entirely agricultural.

The children are those of labourers, with a small proportion of those of village tradesmen and railway officials.

I.—STANDARD OF EDUCATION.

2.

Up to what age do you consider it practicable and desirable for children of either sex to continue their attendance at school during the whole or part of the year, season, or day, regard being had to their parents means of supporting them, and to the necessity of their thorough instruction in their future occupation, agricultural, commercial, mechanical, or domestic?

2.

It would be desirable for children of both sexes to attend school from four to fourteen years old; but this is only practicable for the children of servants, gamekeepers, small tradesmen, and railway officials, or, among labourers, for an only child, or the youngest of a family when all the elder ones are maintaining themselves.

A girl in an ordinary cottager's family, if not the eldest at home, can usually attend school till twelve years old.

If the eldest at home, her mother can often spare her to attend school during the winter months, but more cannot be expected after seven years old, where there are younger children in the family.

A girl may continue to give partial attendance for a longer time than would otherwise be the case if she have leave of absence on occasion of her mother's employment for a day or a portion of a day in baking, washing, charing, or going to market, and these will usually recur weekly with regularity.

In a parish of this description, where nearly all the girls go out to service between the ages of eleven and fourteen, I believe that constant attendance at school and employment there in study and needlework is the best preparation for their future life, by giving habits of regularity and discipline.

An orderly mother does much in training her daughter for service by making her useful at home; but the removing the girl to assist in out-of-doors' work, excepting at harvest, is productive of the worst consequences.

Boys seldom attend school after ten or eleven years old, being set to field work of various kinds, but they are less liable to be irregular than girls, both from being less valuable at home, and from not being deterred by bad weather.

Sometimes a boy may be removed for a few weeks to keep birds or tend pigs, and attend school regularly for the rest of the year, and some come in the winter though not in the summer.

3.

What amount of education, religious and secular, could children of either sex be reasonably expected to obtain in the period which you have specified, and of what should it consist ?

How far do you consider it desirable to include music, drawing, and other matters of taste, in the course of popular instruction which you would wish to see adopted?

3. I should wish a girl to be well acquainted with Holy Scripture, so as to have a clear idea of the narrative and the chief prophecies, with the proofs of the doctrines of the Church; to understand the Catechism thoroughly, and to be able to illustrate it from Scripture, and to be well instructed in the meaning of all the services of the Church.

She should be able to read fluently, write well, and spell correctly; have a general understanding of the principles of arithmetic, extending to proportion and fractions; to work neatly; to know the general course of English history, and enough of ancient history to explain that of the Bible; and to have some knowledge of grammar and geography.

A boy, from the absence of needlework, may be expected to be several degrees more perfect in the other branches of instruction, and chiefly in arithmetic and writing.

Singing is desirable in either case, and for boys perhaps it would be well to teach it thoroughly; but the time that cottage children can afford for any sort of instruction is too limited for anything else verging towards accomplishment, though an intelligent teacher or visitor can do much towards giving habits of cultivation, observation, and interest in natural objects.

This last is the point to be most aimed at, as the chief means of awakening the mind, and obviating both stolid indifference, and the cruelties caused by ignorant terror.

4.

Will you state your opinion as to the respective advantages and disadvantages of the following methods of prolonging the period of instruction, and insuring the permanence of its results with respect to each sex?

(a) Sunday schools ?

4. (a) Sunday schools have been always most useful in this place, both as giving an object for which the weekly religious instruction prepares the children, and as keeping up the education of those who are forced to absent themselves either entirely or for a time from the daily school.

(b) Half-time systems?
(c) Industrial and domestic training?

(c) Needlework is the only industrial training I consider desirable for a girl in such a locality as this.

She leaves school too young to profit greatly by any attempt at domestic training, and in fact actual service at any tolerable place affords the most practical training in household work.

(d) Evening schools?

(d) An evening school, open three times in the week in the winter months, has proved very useful to the young lads who had left school early, but with a spirit of improvement.

(e) Lectures and mechanics' institutes ?
(f) Free and lending libraries ?

(f) A lending library has been much valued for many years, both by parents and children, and has proved very useful.

The books are most sought after which have been read aloud to the upper classes at the Sunday school.

(g) Prize schemes or prize endowments ?
(h) Distribution of minor State appointments on educational grounds.

5.

Should education be supplied to the poor gratuitously, or should it be paid for by them partially or entirely?

II—ACTUAL STATE OF EDUCATION.

6.

How far does the present state of the education of children of either sex, in the districts and classes with which you are acquainted, come up to the standard defined by your answers to the preceding questions ?

What is the nature and extent of any deficiencies which may exist under any of the heads specified in them?

6.

In the parish of which I have spoken, and the time in which I have known the school, about seven girls have attained anything like the degree of knowledge above described.

Of the boys I cannot speak with the same certainty.

The girls I have mentioned were more than usually intelligent, and under favourable circumstances.

The religious knowledge of all came fully up to the standard I have mentioned; they read and wrote well, and could work out sums in simple proportion. I do not imagine, however, that beyond the school-house their arithmetic would be remembered more than enough to serve in their ordinary accounts.

Their grammar, though an assistance to understanding and to spelling, does not improve either their spoken or written language.

Their geography is very vague; and only one, by the help of reading at home, has kept up any correct knowledge of history.

In ordinary cases of those who leave school early after fair but not constant attendance, the religious knowledge is generally good; reading, writing, and work respectable; but spelling deficient, and of the other subjects little more than the most vague ideas remain.

III.—CAUSES OF DEFICIENCY (IF ANY).

7.

What are the causes of these deficiencies, and in particular how far may they be attributed to—

(a) Want of schools, whether arising from deficiency of the funds necessary to establish and support them, or from other causes.

(b) Deficient or unskilful teaching, or bad choice of the subjects taught.

7.
(a)
(b) In former years the deficiency was in some degree occasioned by the mistress's inability to carry on instruction in history and geography, which were only taught through a visitor.

The present mistress can teach them.

(c) Want of interest on the part of parents in their children's education.

(c) The chief causes of the children's deficiencies[^1] are, however, the irregularity of attendance, which makes it difficult to teach history in class, and still more the want of connexion between school studies and home habits.

The parents and relations cannot appreciate the children's progress except in reading, writing copies, and needlework and there is nothing to call their knowledge of geography or history into requisition, while correctness of speech would be treated as affectation. A girl who can spell admirably at her dictation lesson in school will forget all her orthography in a letter out of school, and in most cases the school cultivation and memory are not carried beyond the school door.

Still, however, such an amount of the intelligent spirit of cultivation may be imparted as will enable the young person to improve herself in after life, and often to recall what may have apparently been forgotten or have passed unheeded.

(d) Value of the labour of children, inability of parents to pay school fees, or other economical causes.

(d) It is the value of the mother's work that removes girls from school before eleven years old, and afterwards of their own.

It is only in unusually large, and therefore poor families, that there is any inability to pay the school fee of one penny each per week.

(e) Bad management or bad organization of the schools.

(e) The parent's willingness to enforce constant attendance depends much on the popularity of the teacher.

In the long run, this is of course secured by efficiency, but by no means invariably so at first. A very youthful master or mistress is strongly objected to by many parents; punishments are resented, and justice misinterpreted.

More reasonably, likewise, the mothers are slack in sending their daughters if they do not find needlework well attended to, and especially if work, and above all mending sent from home, be not well taken care of.

To have their own making, and, still more, mending, well done at school, would be more of an inducement to cottage women to send their daughters than any other branch of education; but, unfortunately, mistresses frequently dislike such work, and imagine it not good practice for the children.

It may here be taken into account, that by attracting to our schools the children of very low and rough characters we drive away those of the classes just above them.

As far as my experience goes, the paucity of the children, especially daughters of farmers and tradesmen, in our village schools, even where the education is good, is a well-founded dislike to the rude habits of some of the labourer's children with whom they would associate.

When only the well-disposed careful cottager sent his children to the dame's school, and their very attendance was a token of respectability, the same objection was not made, and the farmer's children willingly sat on the same bench.

Now when by every inducement, the children of the roughest families are brought to school, though they are often in course of improvement, the parents of a better class shrink from promoting intercourse between them and their own children. I have known at least three instances of little children being removed from the village school on account of the language and habits caught from others whom they there met.

(f) Laws or social arrangements affecting the condition of
the poor.

IV.—CHARACTER OF THE EXISTING SYSTEM OF GOVERNMENT AID AND INSPECTION.

8.

The Government at present makes grants in aid of various elementary schools and training colleges out of the general taxation of the country, requiring, on the part of those who receive them, the fulfilment of certain conditions (especially the combination of religious with secular instruction, and proportionate local subscriptions), and reserving to itself the right of inspecting all schools so assisted.

What is your opinion of this system ?

How does it affect districts of different degrees of wealth and inhabited by populations of different characters, and districts which do and those which do not receive assistance ?

9.

What is your opinion of the system pursued at present in relation to—

(a) Pauper schools ?
(b) Reformatory schools ?

How would you provide for the education of the children of paupers and criminals, or of deserted and destitute children ?

10.

Does the existing Government system stimulate or diminish voluntary liberality ?

Are you aware whether any considerable number of persons entertain conscientious objections to its existence?

8.
9.
10.

The Government system has much increased the amount of voluntary subscription to schools, both in places where it is adopted and where it is not, by raising the standard of education. I am convinced that a large number of the managers of village schools have scruples which deter them from applying for Government assistance; some from the dread that it might lead to future interference with religious instruction; some from inability to fulfil the conditions; many more from thinking the standard of education higher than is beneficial, and others from being satisfied with masters or mistresses who are not able to fulfil the requirements, or who have some bodily infirmity, which does not interfere with their efficiency as teachers, but renders them ineligible for certificates.

V.—ENDOWED SCHOOLS.

11.

What is the result of your observations as to the efficiency of endowed schools, intended or available for Popular Education, and as to their adaptation to the existing condition of society?

VI.—SUGGESTIONS.

12.

Would you propose—

(a) The maintenance of the existing system of Government aid and inspection?
(b) Its further development?
(c) Any and what modification of it?
(d) The substitution or addition of any district, or other system of public aid and inspection?
(e) The voluntary principle?
(f) A system of rating; and if so, how should the rate be
assessed?

Should it be obligatory on the ratepayers to make the rate?

If so, how should the obligation be enforced if they were unwilling to make it?

Upon what objects should it be lawful to expend the amount levied?

How should the schools supported by rates be managed?
(g) Any and what mode of dealing with existing charitable
endowments either already applicable by law, or which might be made available, for purposes of education?
(h) Will you make such suggestions as occur to you for
the establishment, improvement, and extension of any of the methods of prolonging education, or preserving its results, mentioned in question 4, with particular reference to the requirements of the districts to which your experience applies?

11.
12. I have had no experience to enable me to speak on these points.

Inspection is, I think, extremely useful, as a stimulus to both teacher and school children. I should be glad if it could be so far extended that a school without pupil-teachers or assistance of any kind could benefit by it.

The advantage was felt here of the inspections about eight and ten years ago, but they have not been repeated, owing to the schools not being in connexion with Government.

13.

Would you make school attendance compulsory?

If so, on whom would you impose, and how would you enforce the obligation of ensuring the attendance of the children ?

Would you wish for the establishment of schools under the direct control of the State ?

Should the education given in such schools be gratuitous or not?

What subjects should be taught in them?

You are requested to give your plans upon the subjects referred to in questions 12 and 13 with as much detail as possible, and with particular reference to the manner in which you would deal with the difficulties arising from differences of religious belief.

13. I cannot enter into these questions farther than to express a strong opinion against compulsory attendance.

The parents, while the present rate of wages continues, cannot afford to lose the labour or the assistance of the children, and would resent any interference with their liberty of action.

VII.—TEACHERS AND TRAINING COLLEGES.

14.

What is your opinion as to the qualifications of the masters or mistresses of public, private, or dames' schools for their duties, both generally and with special reference to the circumstances of the districts and classes to which your experience applies ?

14.

My experience of other schools has not been sufficient to enable me to judge.

In this place we have found that a person of mature age, with enough of experience of schools to learn something of management, has had far more success, both with parents and children, than young men regularly trained in the colleges, of whom we have tried several.

15.

Is the training given to masters and mistresses in normal schools and training colleges well adapted to its object?

Can you suggest any points in which it requires improvement?

Is the state of these institutions generally satisfactory?

Are trained teachers usually satisfied with their profession and with their social position ?

16.

What is your experience as to the working and as to the results of the system of apprenticing pupil-teachers?

17.

Should schoolmasters and mistresses be paid by—
(a) Stipends ?
(b) Fees?
(c) A combination of the two ?

15.
16.
17. (c) School masters and mistresses are best paid by a regular salary, and the children's pence in addition, as they then are interested in keeping them at school, and are paid in proportion to the numbers.

VIII.—RESULTS.
18.

What is your experience of (a) the intellectual, (b) the moral effects of education on the poor ?— Will you state as many specific facts as possible in support of your opinion, allowing for the influence which other causes than education may have had in improving the condition of the poor.

18.

The education of the poor in this place has been gradually improving for the last thirty years, and decidedly with beneficial effect.

In dealing with this inquiry the difficulty consists in the fact that hitherto I have not seen the labourers elevated by education as a class.

Many individuals are raised above the mass, but not the mass itself.

Lads who have received a fair education leave the parish as policemen, railway officials, or the like; girls go into good services, and marry in a degree above that of their parents.

Few but those of dull intellect, deficient instruction, and idle or bad habits, are left to supply the new generation of mere agricultural labourers, and these are thus becoming, in the mass, inferior to their predecessors, who included the better sort as well as the worse.

Yet though there may be fewer persons of uncultivated power and great worth among the labourers under thirty than among those above that age, the condition of the poor is in many respects improved.

This I believe to be chiefly brought about by the greater habits of exertion consequent on the change in the poor law, also by abundance of work, and cheapness of the necessaries of life, as well as by the numerous openings for the employment of the more promising young men.

Of luxuries and comforts the poor possess many more, owing to these causes; but, as before said, education has led to the rise of numbers above the lowest station.

Those who continue in it are not, I am afraid, superior in the moralities or proprieties of life to the less educated generation before them, but this is chiefly owing to that over which they have no control—the state of their cottages.

C. M. YONGE.

[^1]: The printed text has \'deficiences\', which is probably a printer\'s error, though the word is found in the OED.

