---
date: '1860-01-01'
display-date: Jany 10th1860
from-address: 'Otterbourne, Winchester. '
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1860/2
original-date: '2010-05-04 12:15:39'
title: To Ann Maria Carter Smith
wordpress-id: 1779
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263),
It is a pleasure to have such a letter so answered, after feeling quite uncomfortable to have sent it off.

Now I think I must copy off what a very able friend of mine says of the reading of Aggesden, apropos to the [Saturday](../others.html#99) ‘I think that they (the SR) admire Aggesden & in fact it seems to me as little to design a moral as a plot.I should say there was none of either, but a slice of very real life, presenting most life like characters, who work out their own moral. I think its fault is, as you say, in careless diction, and one would like a little rounding off and uniting threads towards the end.

However I think it very good & a wonderful contrast to most of the books which attempt that style of story.

One most distinctly knows Mr & Mrs Arnold, Mary, Sir Hector & more, like real acquaintance & all the interlacing of different classes is very well done with Mrs Arnold’s lady like treatment of the governess.’
I think that worth having and so would you, if you knew the person.

Thank you for telling me of [Professor Whewell](../persons.html#1818),[^2] I think it a feather in my cap.

Do you know I am very sorry to hear you do not feel as if rewriting answered with you, for I believe it is the only way to do more than ephemeral work, for it is nearly impossible to get language, characters and keeping all right at first - and rewriting is the only way to be free of useless words & excrescences, which make a thing lengthy.

Here, they tell me that reading aloud a first & second copy of mine is like going over a stony or smooth road.

Remember [Miss Edgeworth](../persons.html#1819) polishing ad unguem[^3], [Miss Bronté](../persons.html#1810) [sic], now [Miss Mulock](../persons.html#378), - I believe that what reads the most easily is generally produced by the greatest amounts of work. I generally go back and do over my yesterday’s work, much like the snail of the arithmetical question who climbed 4 ft each day & slipped back 3 each night, besides sometimes going back to write whole masses over again, & get them into keeping or abridge them, but then I am happier rewriting than blocking out

yours sincerely

C M Yonge

[^1]: Printed in part by [Battiscombe](../others.html#17) 113.

Envelope addressed to Miss A M C Smith/ Rectory/ Old Charlton/ SE and postmarked Winchester 10 January and London SE 11 January 1860.

[^2]: William Whewell (1794-1866), son of a carpenter, professor of moral philosophy at Cambridge, 1838-1855, and Master of Trinity College 1841-1866.

In September 1854 CMY described his A Plurality of Worlds to Parker as “that remarkable book”.

Carter Smith had perhaps met him with her brother-in-law Edward Atkinson.

It sounds as if he was a CMY fan.

[^3]: “To a nicety”. (Unguis is Latin for a finger nail.

The expression is borrowed from the practice in sculptors, who, in modeling, give the finishing touch with the nail; or from joiners, who test the accuracy of joints in wood by the nail.)

