---
date: '1860-01-13'
display-date: Jany 13th 1860
from-address: Otterbourne, Winchester.
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1860/3
original-date: '2010-05-04 12:23:53'
title: To Ann Maria Carter Smith
wordpress-id: 1780
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263),
It is as pretty and as touching as possible, and we felt it very much, both the waiting, and the old dog coming home to us, in a very way you cannot know.

But the very feelings it excited (though we are strangers to all who sailed in that expedition) made us doubt whether the facts be not too recent for treatment in anything like fiction.

The numbers were too few for the individuals not to be all known, and if one of those two in the boat have left a mother, a Rose or a wife, would she not feel it almost an injury to have her feelings guessed at and put forth for the public.

It gives me somewhat the same sensation as did that picture 2 summers ago at the [Royal Academy](../others.html#141)[^2] of the ladies in the vault awaiting [the sepoys](../others.html#134), a picture which caused people who had lost relatives in the massacres to be kept away from the Exhibition.

Myself I do admire and delight in the sketch very much, I think it most sweetly touched, and if it were about anything less real or less recent, I should be delighted to have it, but unless one was sure that there are no survivors belonging to the two in the boat who could ever read it, I think it would be kinder to keep it unpublished at least till the freshness shall be entirely gone from the grief. I suppose you could not make it some other expedition - no impossible, it would lose its vividness, and the Arctic associations. I do like your sailors so much you are more up in this subject than I, but I thought there was coffee &c in the boat, so as to seem as if they died not of hunger, but of freezing, which surely is a far less painful death, and leaves one to hope both slept away unconsciously. I am going to keep the M S a little while if you will let me - it is so very pretty that I should like it to be read by those who it could not pain, and who will take care of it.

Dear old Poll, I feared she was going to die.

yours sincerely

C M Yonge

[^1]: The letter belongs with MS Westcountry Studies Library, Exeter/ 1860/4, and envelope addressed to Miss Ann C Smith/ Rectory/ Old Charlton SE and postmarked Winchester 23 January1860 and London SE 24 January 1860.

[^2]: Joseph Noel Paton, ‘In Memoriam’, exhibited 1858. ‘A group of English ladies and children is assembled in one of the houses at Cawnpore, some in agonies of terror, others bearing themselves with the most courageous resignation, but all about to be barbarously massacred by the advancing Sepoys, who are seen passing the window, and bursting in at the door, with blood-thirsty exultation.’ The Royal Academy Review (1858) 26.

For an image see http://commons.wikimedia.org/wiki/File:Paton_Sir_Joseph_Noel_In_Memoriam.jpg

