---
date: '1860-11-01'
display-date: Nov 3d 1860
from-address: 'Otterbourne, Winchester. '
manuscript-location: 'MS Girton College Cambridge, Yonge XI 2 '
original-date: '2010-05-05 12:29:45'
title: To Susanna Warren
wordpress-id: 1804
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Warren](../persons.html#1475),
Many thanks for your three letters and their enclosures.[^2] I am very glad the [Society](../others.html#40) has taken it up, for not only will it now be cheaper and better got up, but it is a relief from responsibility - [Miss Goodrich](../persons.html#567) is personally known to [Mr Evans](../persons.html#491), and has written a good many little books and tracts for the SPCK -'The cross bearer' - Faith Ashwin, the Chamois Hunters &c- [Fanny Wilbraham](../persons.html#1513) has also written a nice little history of Russia which is on the society’s list, and I think she too knows Mr Evans, as she certainly does [Mr Lonsdale](../persons.html#898), so there is no difficulty there.
[Miss Millington](../persons.html#1000) is really, it seems to me, the best qualified of all our authors, her knowledge of old medieval literature is so deep and accurate. I do not know her personally but she is a sort of mediaeval dictionary to me, and I am sure all she did would be well done. I almost wish while you are at Bristol you could see her, but I do not know the localities and Durdham Down has an out of the way sound nor do I like to ask her to call on you, as she has a tender throat, in fact she has been a governess and is just now disabled, whether permanently or not I do not know. I hope the SPCK will not throw her over.

Her book on [Heraldry](../others.html#121), which is published with her name, shews her research
Since I wrote, I have heard from my Sussex [Miss Roberts](../persons.html#1244), who seems willing to undertake her county, but she will not be at home till the summer.

She is the author of Mlle Mori, and is step daughter to the [Revd H Latham](../persons.html#843) of Fittleworth, and her knowledge of history, natural history, geology &c is wonderful.

The other [Miss Roberts](../persons.html#1243) (no relation) is as you may see by her [Cathedral sketches](../others.html#244), well qualified for her work but I do not think she has begun. I have met [Mr Heygate](../persons.html#685) once at [Mr Keble](../persons.html#798)’s and could write to him, but I had rather wait to do so till the SPCK has had its meeting, & defined its plan, & appointed its editor, since it is possible it might be afraid of him. I could also get at [Mr George Mackarness](../persons.html#925) (brother of the [Rector of Honiton](../persons.html#926)) who would be able to do Derbyshire, but I think it will be best now to wait for the decision of the SPCK.

As to the worthies, I suspect they had best only be interwoven into the county history when they affect it, because it is nearly impossible to tell whether birth, life or death gives a right to them - Ridley[^3] for instance, a Borderer by birth, London by diocese, Oxford by martyrdom!

William of Wykeham[^4] is exclusive Hampshire property, as the great sailors are Devon, but birth alone is not enough to fix the locality, & besides hurried biographies are so stupid, that I think working the people in is the best chance, but of course I will try to follow the lead, and work in the line that will best match the others -
I had written to [Mrs Gatty](../persons.html#549) to ask if [Mr G](../persons.html#1823) would take the Editorship in case of need, & I hear from her that he is going to write himself about it if he should say he would, do you think the SPCK would have him as an editor of its own - Let me know this as soon as you can that I may know how to answer him.

They tell me that Thomasine is a great Yorkshire name as it is in Devon - we never have it here -
About folk-lore - do you think the poor advanced enough to have it put before them in a book -?

As far as I see, the superstitious would be confirmed in superstition, the more advanced would not look on it as preserving a curiosity but as a folly to print “old wives’ fables,” which they despise.

Much as I grieve at missing such a charming collection, I do not think it would answer for poor people’s reading - I mean such a superstition as that linen washed on Good Friday becomes bloody - or the like -
Thank you for sending me [Mrs Kingsley](../persons.html#817)’s letter - I own it is a relief to my mind, for beautiful as his descriptions are, & safe as the subject might seem, sometimes one expression implies a whole tone of thought.[^5] But the Society is now in charge and that is all well. I see nothing to doubt of in your prospectus except as I said the worthies & the folk lore

Yours sincerely

C M Yonge

[^1]: Envelope addressed to Miss S Warren/The Revd G Hawksley’s/ 12 Polygon/ Clifton/ Bristol and postmarked Winchester and Bristol 3 and 4 November 1860.

The Rev.

John Hawksley of this address in 1861 census was a clergyman without cure of souls with several teenage children, and possibly Warren was their governess.

[^2]: This letter is concerned with a plan for \'a series of county histories and descriptions fit for popular use and such as would teach an intelligent poor man what to be proud of in his county\'.

See letter below to Elizabeth Roberts, 5 November 1860.

Their publication by the SPCK is under discussion.

[^3]: Nicholas Ridley (1500?-1555), Bishop of London.

[^4]: William of Wykeham (1324-1404), Bishop of Winchester and Chancellor of England, founder of Winchester College and of New College, Oxford.

[^5]: Frances Eliza Grenfell (1814-1891) married (1844) the Rev.

Charles Kingsley (1819-1875). CMY was to be a great admirer of The Water Babies (1863) but she had grave doubts about some of his writings.

In the recently published Hopes and Fears (1860) the schoolmistress is criticised for teaching his poem \'The Three Fishers\' because it contains the line \'The sooner ’tis over, the sooner to sleep\'.

Evidently Kingsley, through his wife, had declined to contribute.

