---
date: '1861-03-18'
display-date: March 18th 1861
from-address: Otterbourne, Winchester.
manuscript-location: 'MS Westcountry Studies Library, Exeter/ Yonge 1861/6 '
original-date: '2010-05-09 09:45:10'
title: To Ann Maria Carter Smith
wordpress-id: 1824
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263),
I think your answer is a very wise one, and quite what I can understand. I am sure with all the poor I have known unusual help unless on some very pressing occasion would be anything but really beneficial, but the three old couples might be most happily provided, and I hope [Mrs Elphinstone](../persons.html#482) may choose that way of spending the sum. I will put what you say before her, thank you much for so answering.

Thanks too for the Mothers’ Meeting particulars. I put one or two points as notes to the longer letter, which I think they help out greatly - though the object is different. I really think it might be a good time to stir [Mr Mozley](../persons.html#1065) up about reprinting those stories of yours. [Frances](../others.html#265) would come in well upon the sensation caused by My Life and What Shall I do with it I send the first proof of the Websters, who look well in print, but must wait a month. I thought I should have had a great deal of room when [the stepmother](../books.html#38) and [the pilgrim](../others.html#180) were both done, but there always seems to be less than ever.

About [the ladies](../books.html#43), whom I rather propose to call ‘More precious than rubies’ I shall be very glad of [Mrs Grant](../persons.html#1825), and perhaps if you will do the other that you were thinking of first, we might then see about [Mrs Carter](../persons.html#1830).

The fact is that [my mother](../persons.html#1606) knows her nearly by heart, and is much inclined to her, but a little in doubt whether she shall have time to undertake her, having something else just now about which she is busy, and if you were otherwise employed, I should rather like this to decide itself.

Lady Russell, [Mrs Hutchinson](../persons.html#1834) and [Caroline Perthes](../persons.html#1827) have been beautifully done by the author of Magdalen Stafford[^2], [Olimpia Moratea](../persons.html#1849) by [Miss Taylor](../persons.html#1397), and likewise a wonderful [Mum Bet](../persons.html#1846), an American slave whom she extracted from [Miss Martineau](../persons.html#1724)’s American book. I have a Russian lady too who has delighted me much [Mme Svetchine](../persons.html#1848), whom I translated from the French. I fear I shall still be long in finishing my own part.

yours sincerely

C M Yonge

[^1]: Envelope addressed to Miss Ann Smith/ Rectory/ Old Charlton/ SE and postmarked Winchester 18 March 1861 and London SE 19 March 1861.

[^2]: The identity of the person who published the novel Magdalen Stafford and other works as \'the author of Magdalen Stafford\' is puzzling, but she may perhaps be the [Mrs Bromfield](../persons.html#162) whom CMY called \'one of my crack authors\'.

