---
date: '1861-06-10'
display-date: June 10th 1861
from-address: Otterbourne,Winchester.
manuscript-location: 'MS Princeton University, Parrish Collection, C0171: Box 29'
original-date: '2010-05-09 11:59:47'
title: To William Butler Bourn
wordpress-id: 1832
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#178)[^1],
I am much obliged by the little book that I received on Saturday, which seems to me very interesting.

My tale of the [Young Stepmother](../books.html#38) is ready to be begun upon whenever you like to have it sent up - unless you think it better to wait till later in the year.

So much has been said in the [Saturday Review](../others.html#99) lately about the want of a history of Christian names that I think it may be as well to advertise [mine](../books.html#48) - as preparing. I think it will be ready by the beginning of next year unless any unforeseen delay should arise, and it may be wise to show that it is in the field.

But I should be glad to know whether this would be thought advisable or whether it would be an expense that it would be best not to incur
I intend the title of the book to be “Christian Names” their History and Derivations
Yours faithfully
C.M.Yonge

[^1]: Partner in the firm of John Parker, publishers.

It is assumed this letter is to him, as CMY addresses other letters on publishing matters to \'Mr Parker\'.

