---
date: '1861-11-01'
display-date: Novr 23d 1861
from-address: Otterbourne, Winchester
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1861/14
original-date: '2010-05-11 08:25:50'
title: "To Ann Maria Carter Smith\t\t "
wordpress-id: 1845
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
I have not the letter, at least I do not believe I have but I am almost certain that it was to be the 4 couples at 2lb; and I think you may safely so apply it. I will wait a week to write to [Mrs Elphinstone](../persons.html#482) in case you should be able to tell me anything specially about any of the people.[^1]
I do not know whether I forgot to finish my story or only put it stupidly, the point of it was the staring of the strangers at hearing such a grave polished man as [Dr Harris](../persons.html#629) proposing the worst street in Torr as an allurement to a lady.

That Torr Churchyard is indeed a strangely mournful place, with all its records of early deaths among strangers and its graves so close together I wish we had more time to spend with the kind cousins there, but I was hurried away by having to meet [Mrs Selwyn](../persons.html#1297) before her return to New Zealand, and I could not go to Cockington though I have a whole houseful of cousins and a godson there.[^2] I did once walk there from Livermead many years ago.
[Masters](../persons.html#981)’s corrections and criticisms amuse me very much - it was great fun to see how he presided over the Maiden of our own day. I wish you would have a good fight with him it would do him good

yours sincerely

C M Yonge

[^1]: Letters to Carter Smith dated 18 March, 3 July, 21 November 1861 and 3 April 1862 refer to a donation by a Mrs Elphinstone of money to be given to poor people in Ann Carter Smith\'s parish.

[^2]: The Mallock family of Cockington Court were connected to the Yonges and the Froudes; Livermead was a house at Torquay belonging to them

