---
date: '1861-12-31'
display-date: Decr 31st [1861]
from-address: Otterbourne, Winchester
manuscript-location: MS Mrs Katherine Wykes-Sneyd
original-date: '2010-05-11 17:53:03'
title: "To Henrietta Elizabeth Fursdon\t\t\t\t"
wordpress-id: 1851
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Irene](../persons.html#538)
I send back the translation with many thanks for the sight of it. I was very sorry to see by the paper that the sorrow you feared has come,[^1] and that the year is closing on you in sorrow and mourning, perhaps of a kind that one feels doubly, through one’s parents as well as oneself. I do not know whether you are feeling able to care for these Gosling matters now but I think I told [Pena](../persons.html#973) all about them.

The [Firefly](../persons.html#1168) and [Cobweb](../persons.html#675) had each three votes so they will each have an equal prize.

Many thanks to you and [Glow Worm](../persons.html#534) for your photographs, hers is one of the best, and I am glad to have seen her brown eyes, and know the likeness
your affectionate
Mother Goose

[^1]: The death of her aunt [Grace (Fursdon) Rogers](../persons.html#1255) on 24 December 1861.

