---
date: '1862-04-01'
display-date: April 3d 1862
from-address: Otterbourne, Winchester.
manuscript-location: MS Westcountry Studies Library, Exeter/ 1862 /2
original-date: '2010-05-12 09:41:19'
title: To Ann Maria Carter Smith
wordpress-id: 1859
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263),
Thank you much for sending me this letter, I will certainly write to [Mrs Elphinstone](../persons.html#482) about it - the last time I heard from her she had been excited by the account of the [Needlewomen](../others.html#27) to get up a subscription on their behalf- with a vision of opening a branch in London. I referred this to [Miss Batty](../persons.html#126) and [Miss Barlee](../persons.html#108).[^3] I am so glad the application of her money turned out so well. I am afraid you have not had your copy of the [Biographies of Good Women](../books.html#43), I ordered one to go to you, but it was so long before the book came out that I feared it had been forgotten only that I knew of others having been received which had been sent out at the same time, so pray let me know and I will cause one to be sent to you. I send the Temple paper, I wish I had been able to use it at once for the [Prince Consort](../persons.html#1736)’s Death made all the difference to the expediency of putting it in, and I was thinking of asking you what you thought about it.

As to the Maiden of our own day I have heard nothing of [Miss Wilford](../persons.html#1520) for a long time, she told me it was to be published separately[^3] but I have not heard of its coming out.
I have not congratulated you all through this letter on your sister’s marriage partly because I think the last sister generally feels far too solitary to be thankful for congratulations and is rather glad to be excused it.[^4] I begin to see Rosamond’s punishment coming, but I think you are looking for Ethel to keep Elizabeth company in a change of mind.[^5] Do you know I once knew an offer of marriage made between the hero & heroine of two stories by different authors - the hero was [Miss Jackson](../persons.html#1861)’s Fred, but I am sorry to say the overture came from the lady’s side

yours sincerely

C M Yonge

[^1]: Envelope addressed to Miss Smith/ Rectory/ Old Charlton/ SE and postmarked Winchester 3 April 1862 and London SE 4 April 1862.

[^2]: Johanna Batty contributed on philanthropic topics to the MP under the name Ivanovna.

Miss Barlee was probably Ellen Barlee, the author of Our Homeless Poor and What We Can Do to Help Them (1860), Sketches of Working Women (1871), Locked Out: A Tale of the Strike (1874) and other works, and Lady Superintendent of the Institution for the Employment of Needlewomen in London, which attempted to improve the conditions of women workers by eliminating the middleman.

[^3]: i.e. after its first appearance as a serial in the Churchman’s Companion.

[^4]: [Mary Carter Smith](../persons.html#266) married (4 February 1862) Thomas Henry Plowman.

[^5]: A character in Carter Smith\'s \'The Daughters of the Fair Elms\'.

