---
date: '1862-05-12'
display-date: May 12th [1862]
from-address: 'Otterbourne, Winchester. '
manuscript-location: MS West Devon Area Record Office Ac 1092/32
original-date: '2010-05-13 10:54:13'
title: To Charlotte Cordelia Pode
wordpress-id: 1864
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Charlotte](../persons.html#1587)
I cannot tell you how much pleasure [Duke](../persons.html#1599)’s letter gave me yesterday morning[^2] and the whole Sunday that has passed since has only encreased [sic] the enjoyment of thinking of your future.

It is so very pleasant to me that my own first god child, who has always seemed my god child above all my subsequent ones, should be committed to him whom I have known the best of all my cousins – and honored for his exceeding goodness and kindness from the time we were little children together.

How comfortable and happy a thing it is to think of you as belonging to the dear Puslinch family, and working with them at Newton - it seems one of the happiest lots that can be, and as if no home could be more peaceful and promising in all that can lead to goodness and help one in doing right.

What a gain it will be for [Frances](../persons.html#692) and your brothers[^3] to have another such brother – and how much help and comfort it will be to [Mary](../persons.html#1626) and [Anne](../persons.html#1582) to have you always at Newton to be ready for some of the tasks that have pressed heavily of late.
I am writing in a hurry, for the Moors[^4] have been here and interrupted, so that I cannot say as much as might be said upon our great gladness, and all the others have run off their several ways, so that I have no collection of messages for you, but we all do most heartily rejoice and wish you joy.
your affectionate cousin

C M Yonge

[^1]: Endorsed upside down ‘mothers engagement’.

[^2]: Charlotte Cordelia Pode (d.1929), CMY’s first cousin on her father’s side and her own goddaughter, had become engaged to the Rev.

Duke Yonge, CMY’s cousin on her mother’s side.

They were married on 26 August 1862.

After Battiscombe\'s biography of CMY was published one of her daughters wrote to another relative that CMY had wished to marry their father, but there is no other evidence for this story.

[^3]: Charlotte Pode was an orphan, her mother Anne Duke (Yonge) Pode having died in 1845 and her father Thomas Julian Pode in 1857.

She had a stepmother.

Her elder sister Anne was married but her younger sister Frances Alethea Pode (who seems later to have been called Alethea rather than Frances) was not.

[^4]: Probably the [Rev.

John Frewen Moor](../persons.html#1046), jr. (b.1823/4), perpetual curate of Ampfield from 1853, and subsequently vicar of Ampfield, and his family.

