---
date: '1862-06-27'
display-date: June 27th 1862
from-address: '[Otterbourne, Winchester.]'
manuscript-location: MS Mrs Katherine Wykes-Sneyd
original-date: '2010-05-13 11:11:25'
title: To Henrietta Elizabeth Fursdon
wordpress-id: 1867
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Irene](../persons.html#538),
Many thanks for the photograph which I am glad to have as a much pleasanter likeness of you.

It seems odd that it should have met [Pena](../persons.html#973)’s and as [Humble Bee](../persons.html#81) is staying here, we set her to guess by the old ones which of her fellow [Goslings](../others.html#104) it was.

The Exhibition has grievously affected the Goslings this time and few have sent in answers.[^2] Humming Bird[^3] alone has answered all. I think your Missions have the prize - they are very interesting.

Many thanks too for the Stamps.

You have been very kind about them. I have not many more than 50 [Last Heartsease Leaves](../books.html#45) left now, and they will be sure to go off in time, but if anyone turns up happening to want one, you will know where to apply. I have been for a longer walk than I intended and cannot write Mother Goose’s letter tonight but unless [Albatross](../persons.html#622)’s should come in to morrow, which I do not expect, I shall send the answers to you tomorrow as Humble Bee has seen them. [Glow Worm](../persons.html#534)’s answer was good, but Humble Bee’s better.
your affectionate
Mother Goose

[^1]: Address cut out.

[^2]: The International Exhibition held in South Kensington 1 May-1 November 1862.

[^3]: Unidentified.

