---
date: '1862-12-02'
display-date: Decr 2nd [1862]
from-address: 'Otterbourne/ Winchester. '
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1862/ 7
original-date: '2010-05-14 08:53:00'
title: To Ann Maria Carter Smith
wordpress-id: 1881
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
I am sorry my counsels only led to disappointment but I daresay it is wise in poor old [Mr Parker](../persons.html#1144) to undertake as little as possible. I should think you were in good hands with [Bell & Daldy](../others.html#135). I know [Mrs Gatty](../persons.html#549) thinks them very liberal.

In one case I knew where a lady wanted to publish a story rather longer than yours, they offered to take it if she would guarantee £30 in case the book failed- she did not like to do this, so it went off, but I think that would be a good course with your story.
I think they are attentive and courteous to their clients, twice they have sent on people to me when they thought a thing better for the [M P](../others.html#52) than for themselves one was the Xmas story in this number the other Little Maggie which I did not like, but they printed
So Rose & are some shades less naughty, I cannot guess in what form her chastisement will come, I begin to hope you won’t kill Rosemary as I dreaded

yours sincerely

C M Yonge

[^1]: Envelope addressed to Miss Smith/ 8 Wellington Road/ Old Charlton/ SE and postmarked Winchester 2 December 1862 and London SE 3 December 1862.

The envelope also enclosing a letter from John William Parker, Sr., dated 19 November 1862.

