---
date: '1863-03-19'
display-date: March 19th 1863
from-address: Otterbourne, Winchester.
manuscript-location: 'MS Princeton University, Princeton University, Parrish Collection,
  CO171: Box 29'
original-date: '2010-05-14 09:32:21'
title: To Frances Mary Peard
wordpress-id: 1888
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Peard](../persons.html#1160)
It is very kind of you and exceedingly inviting - the Sphinxes especially, but just at this moment [my mother](../persons.html#1606) and I are moving into a cottage - as my [brother](../persons.html#1624)’s family is outgrowing this house, where I have lived the 39 years of my life - and we are in such difficulties how to stow away our belongings, especially in the way of pictures that we are really afraid to increase the number of them, otherwise I think we should be greatly tempted by your very kind offer.

How you will enjoy the choice. I wish I was to be in town in time to see them, but I daresay I shall meet with a sight of some when we come up for a week in the end of April.

All the more enterprising part of our household kept the great day at Winchester and considered themselves to have had a good view of the [princess](../persons.html#1877)[^2] in her train. I only saw the carriage on the line half a mile off, and heard the guns at Southampton.

The bonfires were a magnificent sight in which the country people really had the advantage. I hope the happy pair had not their heads too stiff with bowing to look out at Osborne for all the I of Wight was blazing, and the Portsmouth shore.

What a fairy land it must all be to her in her fresh simplicity I think I like [Aytoun](../persons.html#1875)’s poem[^3] the best of those the event has produced.

Our direction after Monday will be at Elderfield Otterbourn [sic] &c

Yours sincerely

CMYonge

[^1]: The note is folded, sealed, stamped and addressed on the reverse to ‘Miss Peard 16 South Audley Street/Grosvenor Square/London/W’.

[^2]: Alexandra Princess of Wales, travelling with her husband (later Edward VII) to Osborne House, on the Isle of Wight, for their honeymoon.

