---
date: '1863-06-01'
display-date: June 3d [1863]
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: 'MS Princeton University, Parrish Collection, CO171: Box 29'
original-date: '2010-05-14 09:54:56'
title: To Jane Margaret Hooper
wordpress-id: 1891
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Hooper](../persons.html#711)
I do not think [Miss Gilbert’](../persons.html#1878)s [Instution](../others.html#1) [sic] quite calculates on such work as this good lady proposes - it does not seem as if it would take much teaching to tear up paper!, however here is her letter and here are her stamps at your disposal, I think Maggie would have wider ideas! I hope your little people are quite well again. I must tell you a story rather in their line. A little girl had been taking some medicine, and was going to bed. “Nurse, shall you say your prayers tonight?”
“Yes my dear-”
“Then please say for me, that it is Lady ---’s little girl, and she has such a bad taste in her mouth that she cannot say her prayers”
Yours very truly
C.M.

Yonge

[^1]: Black-edged paper.

The word Elderfield is inserted by hand; ‘Otterbourne, Winchester.’ is printed; a date of 1863 is therefore suggested.

