---
date: '1863-06-11'
display-date: June 11th [1863]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1863/4
original-date: '2010-05-14 10:07:27'
title: To Ann Maria Carter Smith
wordpress-id: 1892
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263),
I am half afraid of plunging into a tour because I have got so many on hand, that Eastern journal is indeed printed to the end, but I cannot get it in, and the Journal in Holland lingers on, and I have some Italian letters that I grieve not to have got in, so on the whole I think I had better decline yours, though if I had not been so ‘furred up’ as Hants people say I should have liked it very much.
I must confess to having betrayed you to [Florence Wilford ](../persons.html#1520) She so very nearly knew that I was obliged to tell, but I think she is very discreet.

She has been staying a long time with [her aunt](../persons.html#384) nursing a sprained foot, but is now gone home.
I heard of nothing amiss about the postage of your last proofs.

yours sincerely

C M Yonge

[^1]: Black edged paper, black engraved address Otterbourne, / Winchester, the word Elderfield added above Otterbourne.

Envelope addressed to Miss Smith / 8 Wellington Buildings/ Charlton/ SE and postmarked Winchester 11 June 1863 and London SE (date illegible).

