---
date: '1863-10-09'
display-date: Oct. 9. 1863
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55381 (2) P. 536
original-date: '2010-05-14 12:51:45'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 1906
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Madam,		
[I](../persons.html#939) shall have much pleasure in undertaking the publication of your new tale '[The Clever Woman of the Family](../books.html#58)' either on commission or otherwise.

The terms for publishing on commission are I believe uniform among publishers.

The whole of the publication expenses, such as printing, paper, binding, and advertsing are charged to the author; and a commission of 10 per cent on the sale is charged by the publisher when he renders his accounts.

This at least is our practice.

Another mode which we frequently adopt is to pay a fixed sum for each edition of so many copies selling at such a price.

Many authors prefer this system as it not open to the uncertainty of the half profit mode, and the clear interest the publisher has in getting back his outlay quickly is supposed to give an impetus to his efforts for the sale of the tale.

To the publisher it is so far pleasant as it leaves him freer with regard to the advertising and other modes of quickening the sale of the book.

If you thought of adopting the latter mode it would be needful for us to see the MS. in order to make our calculation for print and the like.

With regard to books which are your own property and which we are in [Messrs Parkers](../others.html#152) hands we will very gladly take charge and do our very best for them, on the commission terms which I have above [illegible].

There will be I fear a little difficulty in dealing with the other two so long as the present editions last, as [illegible] that [Mr Parker](../persons.html#1144) has now sold his entire business to [Longmans](../others.html#153). I dont think he has [the] right to sell his interest in your books without your leave. I think you might well take the opportunity of recovering the copyright of these two books entirely by asking Mr Parker to fix a price at which you might purchase the stock & interest in these two books, and then they could be transferred to your new publisher. I think it might be well for you to have all your works in your own hands; I cannot help thinking that by & by a cheap uniform edition of your works would sell well.
I shall be glad to enter into any further explanations you may wish, if you see your way to [illegible] [might be crossed out] entrusting us with your publishing we shall consider it an honour and do our best to promote your interests.
I am, Madam,
Yours very respectfully
A.

Macmillan
Miss Yonge Elderfield Otterbourne Winchester
