---
date: '1863-12-18'
display-date: Dec 18th [1863]
from-address: Elderfield
manuscript-location: MS Mrs Katherine Wykes-Sneyd
original-date: '2010-05-20 10:37:23'
title: To Henrietta Elizabeth Fursdon
wordpress-id: 1923
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Henrietta](../persons.html#538)
You have a very nice set of [questions](../others.html#104) this time and I think the best to choose among them will be the distinguished Christian characters of Milan, and the monuments, but I think you should call them sepulchral monuments, as I suppose you mean only those that mark the actual place of the remains - as I imagine you don’t wish to include the Monument par excellence. I think you may allot four sheets to Milan and six to the Monuments.

Did I send you this advertisement before.[^2] I hope you will take the thing in - it is in good hands, and I think will have a good deal that is pleasant and useful in it.
I am glad you have your aunts; though yours will be a sad subdued Christmas, it is such a comfort to be all together.[^3]
your affectionate
Mother Goose

[^1]: Black-edged paper.

[^2]: This was probably the flyer for [Events of the Month](../others.html#69) which CMY also sent to Ann Carter Smith on 29 October 1863.

[^3]: Henrietta\'s aunt [Elizabeth Fursdon](../persons.html#537) had recently died.

