---
date: '1898-11-06'
display-date: Novr 6th[?1898-1900] [[footnote:1]]
from-address: Elderfield
manuscript-location: Surrey History Centre, Dodgson Family Collection D/1/57
original-date: '2014-02-27 14:08:15'
title: 'To Frances Jane Dodgson '
wordpress-id: 19258
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Dodgson](../persons.html#2423),

I will keep your card to consider in case a certain poor Alfred Shany is disposed of, he is 43, and every five years has to be freshly voted for as he will be turned out on his family's hands.[^2]

I well remember that day of [your Brother](../persons.html#261)'s photography. [^3] It was the only time except once that [my mother](../persons.html#1606) was photographed so we should be very glad to have the negatives   If the parcel were sent to Miss Bowles at Ranmure [?] there would be sure to be a safe opportunity before long

yours very sincerely

C M Yonge

[^1]: The letter is assumed to have been written after \'Lewis Carroll\'\'s death in January 1898.

This is consistent with the implication that it dates from the period in which CMY\'s nephew-in-law, the [Rev.

Henry Bowles](../persons.html#184), was vicar of Otterbourne and easily able to receive parcels from his family, who lived in Surrey like the Dodgsons.

It has also been assumed that it was addressed to Dodgson\'s eldest unmarried sister, though he had several.

[^2]: Alfred Shany is unidentified, but was evidently an inmate in an institution whose subscribers voted for candidates.

[^3]: CMY and FMY had been photographed by the Rev.

Charles Lutwidge Dodgson in Oxford on 4 May 1866.

