---
date: '1864-01-18'
display-date: Jany 18th 1864
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS British Library Add MSS 54920: 13-14'
original-date: '2010-05-20 11:12:48'
title: To Alexander Macmillan
wordpress-id: 1926
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#939),
I found the other day that Messrs [Longman](../others.html#153)’s delay in transferring my books to you was rendering it difficult for the retail booksellers to procure them - I therefore wrote to them a day or two ago to urge on the completion of the arrangements and I hope you may soon be able to let me know that this has been done.

How soon do you think it would be advisable to begin printing the [Trial](../books.html#53)?

It will finish in the [Monthly Packet](../others.html#52) in April or May. I would make a push for its doing so in April if this were best, and in that case I suppose you would begin printing at once and I would send you the other chapters- I have an alteration or two to make in what I sent you, but this can be done in the proofs.

My [brother](../persons.html#1624) mentioned to me the project of which you spoke to him of a little book of [Golden Deeds](../books.html#51),[^2] it is one that I should have much pleasure in carrying out
Yours faithfully
C.M.

Yonge

[^1]: Black-edged paper.

