---
date: '1860-12-29'
display-date: Decr 29th [1860s]
from-address: Elderfield
manuscript-location: MS Mrs Katherine Wykes-Sneyd
original-date: '2014-05-01 10:14:16'
title: To Henrietta Elizabeth Fursdon
wordpress-id: 19298
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Henrietta](../persons.html#538)

Many thanks to you both for your answers to the Scripture questions, - you see they are beginning to come into the [Monthly Paper](../others.html#81) if you take it in

I hope [Glow Worm](../persons.html#534)'s cold is mending.

Her Gay Geese were quite new to the collections.  I have sent all the Goose answers, though I think [Gurgoyle](../persons.html#327)'s must stand as the best.  I think you will be delighted with the [Barnacle](../others.html#89) it is a very grand one this time.[^1]

I am glad you have answered the Palm Sunday question.  I was afraid no one would.

Some unknown person sent me two nice answers for the two Christmas

&nbsp;

[passage missing where signature has been cut out]

&nbsp;

I shall help out one of your Palm Sunday answers with the other for the [M Paper](../others.html#81).

[^1]: CMY refers to the essay contributions to the [Gosling Society](../others.html#104) by Henrietta (\'Irene\'), her sister Charlotte (\'Glow Worm\') and Alice Coleridge (\'Gurgoyle\').

