---
date: '1864-01-25'
display-date: Jany 25th 1864
from-address: Elderfield Otterbourne Winchester
manuscript-location: 'MS British Library Add MSS 54920: 15-16'
original-date: '2010-05-20 14:06:52'
title: To Alexander Macmillan
wordpress-id: 1930
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
Herewith I send enough of the [Trial](../books.html#53) for the printer to proceed with at once. I have erased all the redundancies I could find, and I hope it may thus become less cumbrous - Unless there is some difficulty I suppose there is no need of sending me proofs. [Mr Parker](../persons.html#1144) wrote to me himself to recommend [Phelps](../others.html#164) who printed the [History of Christian Names](../books.html#48) and as there were a good many letters from ancient alphabets there used, I suppose it would be best to put any future edition into his hands.

For this book I have no choice
I shall be much pleased if [Mrs Macmillan](../persons.html#941)[^2] is inclined to write me her views on the [Golden Deeds](../books.html#51), I am sure it is a subject on which discussion will be a great assistance.

Perhaps I could procure [Mrs Blackburn](../persons.html#159)’s original designs for the [Little Duke](../books.html#20).

Would you think it worth while for me to do so- ?

Many of the faults in the illustrations as they appeared in the first edition were from the badness of the stone - One or two chiefly of animals were spirited and good but unfortunately the blot is the Little Duke’s face, and I am afraid this is past improvement but if you think these designs preferable to new ones, I could try if they are still to be had.

Yours faithfully
C.M.

Yonge

[^1]: Black-edged paper.

