---
date: '1864-02-17'
display-date: Febry 17th [1864]
from-address: Elderfield Otterbourne, Winchester.
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1864/1
original-date: '2010-05-20 14:47:27'
title: To Ann Maria Carter Smith
wordpress-id: 1937
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
I have certainly made a mess!

The fact was this, that two or three years ago, I made a great appeal to get [more pay](../others.html#102) than the 2/6, and the result was a sum sufficient to give at the rate of about /6 per page more to some one article in the number, but not to all. I have no doubt that I then told you I could give you 3/ per page. I ought to have kept a record of my engagement, and I wish I had done so, then I should not have forgotten that I had fixed to give you that amount.

Then you see when there were long pieces of your story, I having really forgotten, thought that I was doing by you like other people, in making up money, and so adding something, though not the regular rate. I have been in puzzles ever since that sixpence was added, and shall be so for ever, unless it comes to be for everyone.

Meantime I feel much concerned at the sight of your post office order, and am inclined to ask if you will let me send the sum to an [asylum for the blind at Dublin](../others.html#166), which seems to be in great need of help. I had a most earnest letter about it and I send you the paper that accompanied it. I am very sorry for the mistakes I have made

yours sincerely

C M Yonge
I would send the order back to you, but that I am afraid I must cash it now, and besides I think you would rather not.

[^1]: Black-edged paper.

This letter properly belongs in the envelope addressed to Miss Smith/ 8 Wellington Road/ Old Charlton/ EE and postmarked Winchester 17 February 1864 which currently contains the letter dated March 31st 1864

