---
date: '1864-02-25'
display-date: Feb 25:1864
from-address: ''
manuscript-location: MS British Library Add MSS.55382 P. 218-9
original-date: '2010-05-20 14:59:43'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 1939
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge	
[I](../persons.html#939) suppose you would like to have the '[Trial'](../books.html#53) stereotyped.

This can be done now at nearly the same cost as the Composition would be hereafter.

For readjusting the page and having stereotype plate cast the expense would be £68. I do not know how you have arranged the matter on former occasions.

But I suppose that you would probably prefer to purchase the plates and have them as your own property.

The new edition of the [Lances of Lynwood](../books.html#23) is very nearly ready. I have seen a proof of the cuts and they come out very well - albeit they are sombre in tone throughout.
I am sorry I did not feel well what answer to make to [Mrs Blackburn](../persons.html#159), in a small book of that kind one cannot afford much for illustration, unless a very large sale can be calculated on.

Now the [Little Duke](../books.html#20) has been out for several years & has been sold in a very cheap form.

We are now going to publish it at an advanced price, and there is no doubt that we will take some time to sell a remunerative edition, I am in hopes that nicely printed and bound we shall sell as many at 2/6 as at 1/6 in its present form.

That the [net profits](../others.html#160) of an edition of 3000 copies would not be more - to you - than £70 allowing publishers of 10 per cent.

There is really no room here for illustrations, and I am inclined to risk its publication without anything.

The present little design on the cheap edition is really hardly ornamental.

My present feeling is that we will do as well without as with illustrations & also that we cannot afford it.

So I would advise answering Mrs Blackburn in that sense.
I hope [my sister](../persons.html#941) will write to you one these days. A young [gentleman](../persons.html#1903) from the Unicorn [?] who arrived three weeks ago has been occupying engrossingly [my wife](../persons.html#940)’s attention, so that all the care of a large household have devolved on her, and hindered her from more than absolutely necessary writing. I think we agreed generally with your idea.

The more utter selflessness entered into the more it would seemed [sic] to us worthy of a place in The [Book of Noble Deeds](../books.html#51), which is the last form the title has assumed to me - and a [illegible] will be the final one.

Tell me how you like it
I am dear Madam
Yours very faithfully
A.

Macmillan
