---
date: '1864-02-26'
display-date: Feb 26th [1864]
from-address: Elderfield Otterbourne, Winchester.[[footnote:2]]
manuscript-location: 'MS Princeton University, Parrish Collection, CO171: Box 29'
original-date: '2010-05-20 17:21:50'
title: To Louisa Catherine Palmer or Mary Anne Palmer
wordpress-id: 1941
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Palmer](../persons.html#1131)[^3]
I am ashamed of not having thanked you sooner for the statement [C M S](../others.html#19) which is a great help to me, being very clear though of course very sad. I think Mr Gorst’s book must be soon coming, and then I shall dash into my subject - I was going to say like Captain Dodd at the pirate, for I have just been reading that wonderful chapter of Hard Cash.

Have you heard of [Miss Bennett](../persons.html#138) lately. I am afraid her eyes are very much affected.

She spent a day with us and was obliged to shade them constantly with a screen and I am afraid they have been worse since that

Yours sincerely

C M Yonge

[^1]: Black-edged paper.

[^2]: Elderfield added by hand to the printed address.

[^3]: Louisa Catherine Palmer (d. 1868) and [Mary Anne Palmer](../persons.html#1132) (d. 1884) were sisters -in-law of the Rev.

Charles Abraham, first bishop of Wellington, New Zealand.

They may have supplied CMY with tales of missionary heroism for use in [A Book of Golden Deeds](../books.html#51).

