---
date: '1864-03-09'
display-date: March 9.1864
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55382 P. 267
original-date: '2010-05-21 08:35:31'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 1943
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge	.

What you received is an original drawing - not a proof. [I](../persons.html#939) am glad you like it so far. I want to reproduce it by the photolithographic process which is at once cheap and accurate.

The [artist](../persons.html#500) is a very promising young man who is almost self taught & who has done some charming oil[sic].[^1] He wanted to try his hand on book[ illustrations](../others.html#167), and this seemed a good chance for him, if it did not please you, no matter, and if it did then we could have something to make this new [edition](../books.html#20) look lively.

Will you kindly send me back the drawing, I shall send him your criticism.
I am dear Miss Yonge	
Yours very faithfully
A.

Macmillan

[^1]: Robert B.

Farren (b. 1832), later an artist and illustrator but at that date working as curator of a geological museum in Cambridge.

There are many letters to him in this volume of Macmillan’s correspondence, and, as later letters reveal, Macmillan pressed CMY to allow him to illustrate a number of her books.

