---
date: '1864-03-11'
display-date: March 11th 1864
from-address: Elderfield Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: '
original-date: '2010-05-21 08:44:04'
title: "To Alexander Macmillan\t\t\t\t"
wordpress-id: 1944
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
I sent the [drawing](../others.html#167) by the train yesterday.

It was very dull of me not to have seen that it was a drawing.

Our only other criticism is that a touch or two might make the [little Duke](../books.html#20)’s limbs more child like.

As a matter of fact I believe the Normans did not wear beards, but I only found this out long after the book was out, so book and beard must both stand as they are much to the advantage of the picturesque.
I add the list of people to whom I should like copies of the [Trial](../books.html#53) to be sent.

If it comes out during the Easter recess however that first copy in the list should come with mine instead of going to Victoria Street
Yours faithfully
C. M.

Yonge		
[Sir William Heathcote](../persons.html#669) Bart M P
91 Victoria Street
[Mrs Pode ](../persons.html#1180)
3 Craven Place
Westbourne Terrace
The[ London Library](../others.html#29)
12 St James’s Street
[Miss Coleridge](../persons.html#351)
Heaths Court
Ottery St Mary
Miss [Frances Patteson](../persons.html#1151)
Weston
St Mary Church
Torquay
Miss [Anne Yonge](../persons.html#1582)
Puslinch
Yealmton
[Mrs Wilson](../persons.html#1540)
Broomfield
Davidson’s Mains
Edinburgh
6 copies to myself[^2]

[^1]: Black-edged paper.

[^2]: Another hand has written ‘6 by rail’ across the top left corner.
<br/

