---
date: '1864-04-27'
display-date: April 27 1864
from-address: House of Commons
manuscript-location: MS Girton College, Cambridge, Yonge II
original-date: '2010-05-21 13:52:40'
title: Sir William Heathcote to Charlotte Mary Yonge
wordpress-id: 1950
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Charlotte,
1.

The charge of Forgery may be received, & the person accused committed by any Magistrate before whom he is brought, without reference to the place where it is said to have been committed[^1]
2.

The Handwriting may be disproved by any person acquainted with the genuine handwriting.
3 The trial may take place in any county in which the Person shall be apprehended, or shall be in custody.

Therefore Mr Grey may receive the information on the evidence of Mr Beauchamp, who will produce the forged document, & of Alison & Maria, & will commit for trial at the Exeter Assizes.

At the trial itself you will be able to produce Edward also.

How he will get torn to pieces in cross examination! & serve him right too!

But the others are legally competent to prove the case.

These are all the questions that you have asked.

Thanks for letting me see the very good Chapter, which I return
Ever yrs very afftly
[William Heathcote](../persons.html#669)

[Notes, on writing paper stamped 91 Victoria Street, accompanying the preceding letter][^2]
She will be convicted of an assault, occasioning actual bodily harm.

The punishment for this is 3 years penal servitude or imprisonment - not exactly 2 years. I do not exactly remember the description of the assault - but I should think 1 years imprisonment with hard labour about the right amount. I forgot to ask [Coleridge](../persons.html#343) about this.

On the whole we came to two conclusions 1st that it will be much the safest way for you to do as you originally intended, [illegible] not to give the details of the trial but only a general outline - with the result 2ndly that no ending for the trial would be so effective for the snubbing of Rachel as that as soon as her cross examination was concluded the Judge should stop the case & tell the jury that though the evidence showed that the man was dishonest enough, yet that the almost incredible folly of a young Lady who was self sufficient enough to fancy herself capable of managing matters of business, had got the whole of these transactions into such a mess that it was not possible to sustain a criminal charge.

Then for the difficulty of keeping her in Prison, John Coleridge suggests that you should make Maddox for some reason desirous of not being tried at Quarter Sessions, but at the Assizes, & make application to that effect.

Perhaps because he thought the Country Magistrates were getting to know too much about him or on the other hand make the committing magistrate either inadvertently or for some reason, commit for trial at the Assizes.

Then, if you make the arrest take place in August just after the summer Assizes & commit him for trial at the next Spring Assizes in March you will have 7 months for the Russian journey.
I am however afraid that there are Winter Assizes at Exeter, & your story is quite within recent times.

But perhaps, between August & December you may get the Russian journey over.

The Judge in setting down Rachel might do it with gentleness, & have a natural tenderness for her childish ignorance of the world more afflicting to her than any amount of scolding.

Maddox’s alias has no bearing on the case. I think he should be indicted there as Maddox in the first place - because he was not known by any other name there - though it might be procedure to add the alias of Mauleverer in account of the discovery
In stating how the case went, it might be said, not only that, for Rachel’s unbusinesslike way of going through her account there was no proof of embezzlement supposing Maddox to have been his servant, but that there was insufficient proof of his having been her servant without which there could have been no embezzlement at all.

Her arrangements were so loose in themselves and so confusedly expressed that it was doubtful whether he was not to be regarded as acting on a footing of equality with her & more as a partner.

Good night - I shall be very glad to know more

Ever yours very afftly
William Heathcote

[^1]: CMY had apparently sent Sir William a draft of the chapter in [The Clever Woman of the Family](../books.html#58) (Chapter XXI) concerning the exposure of the forger and embezzler, Maddox/Mauleverer.

Mr Grey is the local magistrate who commits him to trial, Mr Beauchamp the man defrauded, and Edward the one whose signature was forged.

Alison is Edward’s sister, who is called to identify the documents as forged, and Maria is Maddox/Mauleverer’s mistress who is called on to give evidence of his alias.

[^2]: The main purpose of these notes seems to be to help CMY devise a way of allowing Edward, now living in Russia, to testify at the trial of Maddox/Mauleverer.

The \'she\' of these notes is Maria, Maddox’s mistress, who was accused of ill-treating girls placed in her care, ostensibly to learn wood-engraving.

