---
date: '1866-06-14'
display-date: ' June 14 1866'
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55386 (1) P.160
original-date: '2014-05-22 12:12:35'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 19563
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge,

Except for a possible visit to [illegible] Lodge on Saturday, whence I shall return on Monday, I will be at home all the 10 days from the 20th and it will be a great pleasure to me to see you. I have several matters which I should wish to talk over with you. I am sorry I can say little about  Mr J[illegible]  in [illegible] my dear [Sister-in-law](../persons.html#941).

We are not losing [illegible]  gaining ground.[^1]

The [dove](../books.html#62) is continuing a success with even the most captious critics, and is selling well in spite of a dull distressing season, caused by all these distressing bank failures.

The year has revealed very un[golden deeds](../books.html#51).

How does the [chaplet of Pearls](../books.html#69) stand?

You will tell me about it when I see you.

Could you do a second series of Golden Deeds, or rather a companion volume, of the doers?[^2] Mr Craik has suggested a volume Heroes of History, and in talking it over it looks as if it might assume that form. I mention it now that you may think over it.

[Next 7 lines indecipherable]

Yours very faithfully,

Alex.

Macmillan

[^1]: Frances Macmillan appears to have been very ill, but was recovering by September 6.

[^2]: Macmillan proposes here the collection that eventually became [A Book of Worthies](../books.html#80).

