---
date: '1864-05-31'
display-date: May 31st 1864
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 26-27'
original-date: '2010-05-21 14:49:04'
title: "To Messrs Macmillan\t\t\t"
wordpress-id: 1956
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Miss Yonge would wish the following presentation copies of [the Trial](../books.html#53) to be sent - if they have not already been sent, - she is not certain whether [Messrs Macmillan](../others.html#111) had her list and should wish to guard against any being sent twice over - Copies to be sent to
[Miss Coleridge](../persons.html#351)
Heaths Court
Care of [JD Coleridge](../persons.html#343) Esq
6 Southwark Crescent
			also to -
[Sir William Heathcote](../persons.html#669) Bart M P
91 Victoria Street
[Mrs Pode ](../persons.html#1180)
3 Craven Place
Westbourne Terrace
Miss [Anne Yonge](../persons.html#1582)
Puslinch
Yealmton
Devon
[Miss Dyson](../persons.html#464)
Church Crookham
Farnham
Miss [Frances Patteson](../persons.html#1151)
Weston
St Mary Church
Torquay
[Madame de Witt](../persons.html#423)
Val Richer
Lisieux
Calvados
France
Also 12 copies to be sent to my/herself - by the South Western railway, addressed to
Miss Yonge
Elderfield
Otterbourne
Bishopstoke
Letters to be always directed to Winchester as post town, parcels by railway to Bishopstoke.
