---
date: '1866-07-06'
display-date: July 6 1866
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55386 (1) p. 228
original-date: '2014-05-22 12:49:00'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 19572
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge

[Mr Craik](../persons.html#379)’s title was Heroes of History, which was less objectionable than A Book of Heroes as regards the chance of confusion with [Mr Kingsley](../persons.html#816)'s.[^1] Still there is some objection to it.

It had not struck either of us before, but we both feel it now when you point it out.

How would [“A Book of Worthies”](../books.html#80) do?

There is the old “Scotch Worthies” and “Worthies of France” and Fuller’s “worthies”.

The first objection that strikes me is that the word has a semi-derisive(?) application in some modern day regions.

But it is a capital old word nevertheless, and there is no harm but much good in restoring a noble word from lower use. I rather feel that ‘true chivalry’ lacks sim[illegible]  And the epithet “true” has a sort of antagonistic tone, [illegible] for books that I do not like. “A Book of Chivalry” would be better I think. I will have little hope of you  [next two paragraphs indecipherable]

Very faithfully yours

[A.

Macmillan](../persons.html#939)

I went to the Delegates meeting last Monday [rest of the paragraph indecipherable][^2]

[^1]: In 1856 Macmillan had published Charles Kingsley\'s, The Heroes, or, Greek fairy tales for my children.

[^2]: Macmillan had attended a meeting of the Delegates, or governing committee, of the [Cambridge University Press](../others.html#263).

