---
date: '1866-11-22'
display-date: Nov. 22 1866
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55386 (2) P.654
original-date: '2014-05-22 14:48:51'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 19659
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge,                                                                  

How do you like this? I think a [illegible] ly cheap book [illegible] [illegible]  made a profit.

Yours very f’lly

[A.

Macmillan](../persons.html#939)

Alexander Macmillan to Charlotte Mary Yonge

Copy outletter book British Library Add MSS.55386 (2) P.701

&nbsp;

Dear Miss Yonge,                                           Dec. 3. 1866

&nbsp;

I have received some copies of Dynevor Terrace.

Shall I send them to you or to some place inBrighton? I can probably add a book or two of my own if you say the cause is worthy.

&nbsp;

I will anyway see about the Cameos very soon and also about Miss Peard.

The pre-Christmas weeks are rather pressing.

&nbsp;

I liked Miss Sewell’s title very well.

It might be slightly modified.

Have you got the leave [illegible]  from all the authors?

&nbsp;

I will write very soon,

&nbsp;

Yours faithfully,

	Macmillan

So the Chaplet finished?

&nbsp;

&nbsp;
