---
date: '1867-01-19'
display-date: Jan. 19. 1867
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55386 (2) P. 814
original-date: '2014-05-22 16:13:57'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 19672
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge,                                                                         

The [illegible] Palgrave’s [Unknown Reference 479]Normandy], but volume 1 is nearly out of print.

We have only very few copies and they are at present imperfect.

If you want merely to use it for the future you can return the copy I send you by rail today, which is my own private copy if you want to possess it, let me know and I will charge it to you at trade price.[^1]

[Mrs Craik](../persons.html#378) is very much gratified of course to know [M.

Guizot](../persons.html#597)’s opinion of her book.

She had heard it direct from himself, but will I am sure thank you for sending her good news.[^2] People often have bad ones delivered with no little gusto.

This cold weather is freezing all business as well as many people’s blood. I hope it will do them good after.

The parcel has gone to [Miss Sewell](../persons.html#1301).

Yours very faithfully

[A.

Macmillan](../persons.html#939)

[Roscoe](../persons.html#1260)’s books are out of copyright.

So use him freely.[^3]

[^1]: CMY had asked him in her letter of 17 January to find her a copy of Palgrave\'s History of Normandy to use as background for [Cameos from English History: From Rollo to Edward](../books.html#73).

[^2]: CMY had reported that Henriette de Witt had told her of Guizot\'s admiration for Dinah Craik\'s novel Two Marriages.

[^3]: [3] CMY had written (14 January 1867), with reference to obtaining permissions for republication of extracts from historians in [Historical Selections](../books.html#71): \'Do you know who Roscoe’s representatives are, for there is all the Battle of Hastings from him.

Miss Sewell says she wants all the MS to look over and arrange again – would you send it to her.\'

