---
date: '1864-09-12'
display-date: Sept 12th 1864
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54920: 36-7'
original-date: '2010-05-22 09:30:37'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 1973
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
We are at home at last and in three days more I hope to send up the copy for the printer of all the ancient history [Golden Deeds](../books.html#51).[^2] Of course he will let me have the proofs. I hope the delay will not prove to have been of consequence.

Are there to be any vignettes to the chapters, if there are, there is a story of the Coliseum which quite asks for one of the Dying Gladiator or of the Coliseum itself. I think there should be a chronological index, the ground of which I will make before sending up these sheets of the M S.

Thanks for sending me Karamsin, which arrived on Saturday, it looks so full of interest that we should like to make it our pièce de resistance for our winter’s reading if you can let us keep it long enough.
[My brother](../persons.html#1624) desires me to ask whether you would like to have him translate Todleben’s Sebastopol which was reviewed in the Times the other day.[^3]
I suppose your Isle of Wight holiday is over.

Ours has ended by an arrival in a house with only two habitable rooms
Yours very truly
C. M.

Yonge

[^1]: Black-edged paper.

[^2]: Each of the deeds is dated and \'ancient history\' probably means the first fourteen chapters, the last of which was dated 404 A.D.

[^3]: The review was by [William Howard Russell](../persons.html#1270). JBY was presumably offering to translate from the French rather than the Russian edition.

