---
date: '1864-09-13'
display-date: Sept. 13 1864
from-address: ''
manuscript-location: "Copy outletter book British Library Add MSS. 55383 (1): P. 327\t\
  \t"
original-date: '2010-05-22 09:42:14'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 1975
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge	
We shall be very glad indeed to see the [Deeds](../books.html#51) become words in print.[ I](../persons.html#939) meant to have no [illustrations](../others.html#167) except the vignette which I have had in my other Golden Treasury books.

This has been 'exercising' me a good deal of late. I cannot hit on either the sort of subject or the man to do it. I would be most grateful to you for a hint. I am inclined to send the first few sheets to Mr [Holman Hunt](../persons.html#1912) & say 'Do what you can'.

He works slowly and with difficulty & is not always willing to undertake these things, but if he would it would be pleasant to have anything from him.

If he does not do it we might get [Millais](../persons.html#1911) [illegible] things & rapidly enough always with great ability of course but I would not be so clear as to their - what shall I say .

Golden-ness is [illegible]
[The rest of this letter is illegible]
