---
date: '1859-11-01'
display-date: Novr 1st 1859
from-address: Otterbourne. Winchester.
manuscript-location: 'MS Charlotte Mitchell. '
original-date: '2015-03-09 14:15:02'
title: To John William Parker, Jr.
wordpress-id: 19905
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Sir](../persons.html#1143),

I am much obliged by your letter received this morning, and either by today's or tomorrow's post, you will receive [Miss Roberts](../persons.html#1244)' MS[^1]  If you decide on accepting it, I suppose it should be begun as quickly as possible, since Christmas is so near.

The proofs should be sent to me, and I should also have the copy returned with them, as there are so many Italian names for which it would be safer to refer to the MS.  I really would not have troubled you about it if I had thought it at all after the common run of ladies' manuscripts.  I believe she thinks it should make two volumes foolscap octavo.

I am very glad to hear that the present edition of the [Daisy Chain](../books.html#24) is so nearly gone.  I should wish it to be made as cheap as will bring in some degree of profit. I think it is stereotyped, and this with cheaper paper and perhaps a cheaper style of binding may reduce the price, though it is too large to be ever completely a "cheap book".  I suppose the volumes are too thick to bear a paper binding like [Miss Sewell](../persons.html#1301)'s.[^2]  It must certainly continue to be in two volumes

yours faithfully

C M Yonge

J W Parker Esq

[^1]: Margaret Roberts\'s novel Mademoiselle Mori: A Tale of Modern Rome was published by Parker in 1860.

[^2]: Elizabeth Sewell\'s novels had appeared in a uniform greyish-brown paper binding.

