---
date: '1864-11-21'
display-date: Novr 21st 1864
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 54-55 '
original-date: '2010-05-22 18:12:05'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 1994
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
This is an excellent [title page](../books.html#51), much better arranged than what I had thought of. I suppose I need not return it. I am going to send you a formidable list of presentation copies, which must be set down to my account as I have rather a large stock of young friends for whom I think this will be a better gift than a story book would.

Thanks for the Sunday Book, I see many favorite [sic] old friends in it.

And the dove outside is beautiful in spite of its loss of colour.

The [Little Duke](../books.html#20) looks well, and the faces younger, it is a very pretty book, and I shall be glad to have it published on commission like the rest

My historical story '[the Dove in the Eagle’s Nest](../books.html#62)' is just begun, and if it is fit for the purpose, would be much honored [sic] by going into your [Magazine](../others.html#78); I think it will take about twelve chapters - the subject is the burgher civilisation of the 15th century brought in contact with the savage robber nobility, but I wish I had more authorities. I hunted at the Bodleian, but only found how little there was to be had. I will send the first chapter as soon as it is finished, and if the [Editor](../persons.html#980) would wish it, an outline of the story.

It is not a child’s story, but its dénouement is not a marriage. I began by dreaming a chapter of it, a couple of years ago, and have thought it out at intervals ever since.

What would be your terms for such a story as this - ?

Shall I set to work in earnest upon the Historical verses, and if so would it suit your plan if I set them in framework of conversation which I think would be the most palatable form of notes and criticisms.[^1]

I send a photograph in case the ladies at the Elms[^2] may like to have it. I’m afraid it is not very like though there are a good many opinions about it

Yours very truly
C. M.

Yonge

[^1]: ]No book that fits this description appeared until the 1880s when CMY published Aunt Charlotte\'s Evenings at Home with the Poets: A collection of poems for the Young, with conversations (1881) and Historical Ballads: Arranged to meet the New Code of 1882, Schedule II, English (in three parts) (1882).

[^2]: Macmillan’s[ wife](../persons.html#940) and[ sister-in-law](../persons.html#941).

