---
date: '1864-11-01'
display-date: Novr 22d 1864
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: '
original-date: '2010-05-22 18:24:38'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 1995
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
I send both title page and the proof of the statuette, which is indeed most beautiful and suggestive. I wrote yesterday about the title page. I could not do so before as I only came home late on Saturday and the Sunday post goes early. I enclose the list of presentation copies[^1]

Yours sincerely

C M Yonge
Will you be kind enough to send the sheets of the [Golden Deeds](../books.html#51) to Messrs [Williams & Norgate](../others.html#165) for [Tauchnitz](../persons.html#1396) - as he may like to have it for his juvenile library, and I am writing to him today to ask the names of books likely to help 'my [Dove in the Eagle’s Nest](../books.html#62) -'
[Mrs Pode](../persons.html#1180)/ 3 Craven Place/ Westbourne Terrace W
[Miss Taylor](../persons.html#1397)/ 21 Taviton Street/ Gordon Square W C
[Miss M M Coleridge](../persons.html#17)/ 6 Southwick Crescent W
[Miss Margaret Lonsdale](../persons.html#896)/ Care of Miss Coleridge/ 6 Southwick Crescent
[Miss Coleridge](../persons.html#351)/ Heaths Court/ Ottery St Mary
[Miss Alice Coleridge](../persons.html#327)/ St John’s College/ Hurstpierpoint
[Miss C R Coleridge](../persons.html#329)/ Rectory / Hanwell
[Miss Helmore](../persons.html#675) / Cheyne Walk/ Chelsea
[Miss Mary Dundas](../persons.html#455)/ 9 Charlotte Square /Edinburgh
[Miss Johns](../persons.html#887)/ Winton House/ Winchester
[Miss Charlotte Fursdon](../persons.html#534)/ Fursdon / Exeter
[Madame de Witt](../persons.html#423)/ Val Richer/ Lisieux/ Calvados/ France
[Miss Anne Yonge](../persons.html#1582),/ Puslinch/ Yealmton
12 to myself
To the Editors of the [Literary Churchman](../others.html#76) - & [Events of the Month](../others.html#69)

[^1]: The letter is endorsed ‘sent Nov 24’.

