---
date: '1881-07-10'
display-date: July 10th [1881]
from-address: 'Elderfield '
manuscript-location: 'MS Charlotte Mitchell. '
original-date: '2015-07-11 03:03:22'
title: To Edith Sophia Jacob
wordpress-id: 19998
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Edith](../persons.html#749)

Would this be the kind of thing?[^1]  I suspect it is too long.

It is a beginning I once made and you may as well look at it.  I also send a paper on the study of the Bible, which an American Sunday School Society once made me write and which might serve you some day perhaps.

You see this is a mere beginning, hardly getting beyond the Acts.  [Canon Bright](../persons.html#199) wanted me to do a Church history, and I got so far and then quailed - wanting the lash of a serial to keep me up to it.

We seem to be getting on well under the new dynasty, but it has been a strange thing that in one spring the school should lose Vicar, master and pupil teacher[^2]

your affectionate

CMYonge

I was going to cut out the article but on second thoughts I send the whole paper as there are curious things in it

&nbsp;

[^1]: CMY has evidently been asked for a contribution to [The Watchword](../others.html#100), the periodical edited by Edith Jacob which circulated among the [Society of Watchers and Workers](../others.html#47).

She certainly contributed a series [\'Militant Here on Earth\'](../books.html#149) about the early history of the church which deals with the travels of St.

Paul and might be the article referred to.

[^2]: [The Rev.

Walter Elgie](../persons.html#478), Vicar of Otterbourne, died in February 1881 and was succeeded by the [Rev.

Walter Brock](../persons.html#201). A week after his arrival the schoolmaster, [Walter Fisher](../persons.html#513), also died.

