---
date: '1865-02-01'
display-date: Febry 3d [1865]
from-address: Elderfield
manuscript-location: 'Princeton University, Parrish Collection C0171: Box 29'
original-date: '2010-05-24 09:54:55'
title: To Ellen Julia Johns
wordpress-id: 2005
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Johns](../persons.html#772),
We are much obliged for your kindness, and if things - weather included turn out well - I hope to bring the [Cricket](../persons.html#1603) and her sister in time for a four o’clock tea with you on Monday.[^1] I am afraid we cannot do more, as after that it gets so late and cold for an open carriage.

Our basket only holds three so that my [mother ](../persons.html#1606)- though thanking you for your kind message will remain at home

Yours sincerely

C M Yonge
I have sent this to shew my good intentions but just as I had written it, it turned out that my cousins must go on Monday to the Isle of Wight, and they do not come back till Wednesday.

Then Thursday is [Miss Chamberlayne](../persons.html#1744)’s wedding, and they may have to leave us on Friday, but if possible, I will try to bring them that day.

[^1]: Cricket was CMY\'s cousin Elizabeth Yonge, who was to be introduced to the Johns daughter Katie who was also a member of the [Gosling Society](../others.html#104).

The accompanying sister was probably either [Mary](../persons.html#1628) or [Charlotte Yonge](../persons.html#1588).

