---
date: '1865-02-07'
display-date: Febry 7th 1865
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 63-64 '
original-date: '2010-05-24 10:04:24'
title: To Alexander Macmillan
wordpress-id: 2006
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
I have to thank you for sending me the parcel of German books, which I hope will much add to the correctness of my [story](../books.html#62). I am not sure however that one has not come for me to which I have no right -Alt-Nordisches Leben Von Dr Karl Weinhold -
[Miss Keary](../persons.html#793) told me that you had promised to get for her some Old Northern books, so perhaps it was meant for her.

In that case shall I send it?

Did you also put in Duncan’s Shipwrecks which do indeed look like a store of Golden Deeds -?

Any way I am very glad of the freight, and much obliged to you for putting me in the way of getting these books.

Will you be kind enough to have a copy of [Golden Deeds](../books.html#51) sent to
	Mlle [Marianne von Nathusius](../persons.html#1077),
Meyendorf
Leckhausen
Magdeburg.

She wants to get the start in translating it, before [Tauchnitz](../persons.html#1396)’s English edition comes out. [Mme de Witt ](../persons.html#423)is translating it into French

Yours sincerely

C M Yonge
Please to let sheets of the [Clever Woman](../books.html#58) go to M.

Tauchnitz, unless this has been already done. I have heard from him today about it
