---
date: '1865-03-06'
display-date: March 6 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (1):  P.
  220'
original-date: '2010-05-24 14:40:15'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2010
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge	
That extremely excellent and instructive person '[The Clever Woman of the Family](../books.html#58)' will be duly introduced to all your friends as per list.[ I](../persons.html#939) trust we shall have her 'out' in a very few days, when your wishes will be attended to in this and also in regard to the other books you give me a list of instructions about. I am in occasional correspondence with Mr [Henry Wilberforce](../persons.html#1510), at least he writes us every now and then with regard to books for review.

So I can no doubt get the copy provided to him.

His last letter was from Malvern I think he said he would be there some time.

He used to write for, and at one time edit '[The Weekly Register](../others.html#174).' I daresay he has some hand in '[The Month](../others.html#91).'
I have never answered you last letter about the [Sunday Library](../others.html#145), as I wanted to do it at some length, and it is hard to write quietly in the middle of business.

But I will only say now that in one respect, the theological, I do not think there would be the slightest chance of any difficulty.

In the specific end we have in view I think the more [we] keep to the broad current the more effective we will be.

The certain, and, within the pale of the Church, the uncontroverted, offers a field wide enough for our purpose.

Indeed it often strikes me that if a really earnest attempt were made to insist on and illustrate those things that are undoubted, vital, in our Faith a great deal might be done towards the true unity. I have no idea that anything will be gained by any one 'giving up' things he perceives to be valuable even in a minor degree, and controversy must, and indeed ought to go on.

But in the aim we had before us it would be neither desirable nor appropriate.
I have been having the 131st Psalm running through my head for the last month or more (might it run through my heart!) And thinking if we could all get in to that mind & mood how greatly clouds would clear and the blessing from Bethlehem would come on us 'and refining our souls & keeping them low, like a weaned child' we would rise to heights undreamt of among the Highest Churchmen, and scope of vision the Broad Churchman never saw in his wildest dream.[^1] If we could keep that before us we might do much.

But the Sunday Library we can think over a little more before deciding anything. I would gladly secure you and if I could, and on my own part anticipate no difficulty. I must set [Mrs Daniel](../persons.html#941) into correspondence with you.
I think I have got a young Cambridge [Artist](../persons.html#500) who would do the[ illustrations](../others.html#167) admirably.

My idea is a book about the size of Kingsleys[sic] Water Babies, a copy of which I send you along with the copy of the [Heir of Redclyffe](../books.html#15).[^3] I thought of some ten or twelve woodcuts very beautifully done.

Have you any 'views on art' that you would like to enunciate for this gentleman?

Yours ever faithfully
A.

Macmillan

[^1]: This is Macmillan’s initial proposal for a book to be called \'Bethlehem\' to be written by CMY, that apparently never came to fruition, though their letters give a detailed account of its progress.

The quotation is a paraphrase of Psalm 131:2: \'Surely I have behaved and quieted myself, as a child that is weaned of his mother: my soul is even as a weaned child.\'

