---
date: '1865-03-24'
display-date: March 24. 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (1): P. 291'
original-date: '2010-05-24 15:17:36'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2013
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge	
[I](../persons.html#939) am writing to [Mrs Vaughan](../persons.html#1929) & will tell her with how much pleasure I consent to her using the story from [Golden Deeds](../books.html#51). I will remind you when we reprint, that you may give us the additional story.
I don’t think I ever congratulated you on the marvellous good scotch you give us in the [Clever Woman](../books.html#58).[^1] I, a western man, from the Land of Burns, claim a classical purity in my own Scotch taste and could detect no flaw.

When you have any ['Bethlehem'](../others.html#177) done I would rather like to have, say a chapter to make experiments in type to.

The [Sunday Library](../others.html#145) scheme, could I have no doubt, be arranged in the way you indicate.

My feeling that substantially no one whom I would wish to help in it, would disagree with your feeling. I am sure by dwelling in all cases on the life, there will be so much the less chance of straying from the light.

But the organisation will want a little help. I shall be so grateful for guidance even if you do not feel free to assume the responsibility. I am anxious however, that [Mrs Gatty](../persons.html#549) should not be asked, at least as from me, and for this reason.

She has published with my excellent friend [George Bell](../persons.html#1930) for many years. I would like exceedingly to keep up the old loyal policy between author & publisher so far as I could, and this would be like poaching on a friends preserves. I think I can safely say I have never done so yet.

In a scheme which I want to do good I would like to avoid it.

Otherwise I admire her & shall much [illegible]. [Miss Keary](../persons.html#793) tells me about your ['Goslings'](../others.html#104).

Any very good one I would certainly not object [to]. I rather fancy new brain.

But we will have time to talk over all this.

Have you quite decided on the title of your story for the [Mag](../others.html#78). '[The Dove in the Eagle’s Nest](../books.html#62)' is slightly sentimental. I dont know that it is any worse for that.

But perhaps a somewhat simpler one would do better.

Yours very faithfully
A.

Macmillan

[^1]: In The Clever Woman of the Family there is a housekeeper who speaks broad Scottish.

