---
date: '1865-03-25'
display-date: March 25th 1865
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 71-72 '
original-date: '2010-05-25 09:06:16'
title: To Alexander Macmillan
wordpress-id: 2014
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939),
This is a quick fire upon a busy man, but there are two or three things to say, and first that [Mme de Witt](../persons.html#423) has written to say that the [Christian Names](../books.html#48) have not reached her, and asking whether you have sent them through any Paris bibliothèque where they could be enquired for. I also enclose a direction to which I should like to send a copy of the [Golden Deeds](../books.html#51).

It is in fact to the little Princess [Marguérite](../persons.html#956) of Savoy, a child of 13, the niece of Victor Emmanuel - but it is etiquette to give it to the [Governess](../persons.html#1931) instead of herself.

She has been writing a poem on the Gascon Squire in the [Lances of Lynwood](../books.html#23)!

If I did not know about her and the governess through [Miss Sewell](../persons.html#1301) and some friends of hers I should think it a hoax, as I really did the first proposal to translate a book of mine which came on April 1st
Here is the 1st chapter of [Bethlehem](../others.html#177). I have had a young friend here, and so have been hindered from going further. I think there is scope for a very beautiful illustration here.

In the latter part I could take no words but the Bible and Milton.
'The Debatable Ford' would be as suitable a title as the [Dove](../books.html#62) &c and perhaps might be the first. I believe my [brother](../persons.html#1624) would say the Dove &c was 'flummery' - but most I have told of it have liked the sound of it, and it tells the story.

The length seems to me its chief fault. I had better leave the decision between the Dove and the Debatable Ford to you and [Professor Masson](../persons.html#980).

Do you know if there is a publisher named [Ratcliffe](../persons.html#1933) at Calcutta -?

About three years ago the [Calcutta University](../others.html#175) [bought](../others.html#160) of me an edition of 5000 of my [Landmarks /of Ancient History](../books.html#14)\ for their schools &c and two days ago, I got a letter dated Kyd Street, Calcutta, signed Ratcliffe, and saying the University had published another edition and that he was going to pay me 3d per vol.

Whether it is a banking or a publishing firm or a government office, I cannot make out - there is not even the initial of a Christian name.
I’m afraid my Scotch was not rightly original for I wrote the sense in pencil, and sent it to a friend in Edinburgh to translate into good Scotch, or it never would have had such genuine turns.[^2]
I know how great a friend [Mrs Gatty](../persons.html#549) considers [Mr Bell](../persons.html#1930), and I should hardly have mentioned her, but for her having translated that 'Bit of Bread' by special request, I believe, for [Messrs Saunders and Otley](../others.html#144), so that I concluded there was some understanding about her taking individual bits of work for individual purposes.

But of course I would say nothing to her. I should like to see a very choice volume on Creation, and the book of nature, if one could only find a person with the head and the heart and the perseverance all united as in [Dr George Wilson](../persons.html#1932) or [Hugh Millar](../persons.html#1813).[^2]

Yours sincerely

C M Yonge

[^1]: In fact the letter was from James Sutcliffe, principal of the Hindu College, Calcutta.

[^2]: Macmillan\'s Magazine I (1860) 199-203 had carried an obituary by John Cairns of the chemist, museum director and popular science writer George Wilson (1818-1859).

