---
date: '1865-05-05'
display-date: May 5. 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (1): P.440'
original-date: '2010-05-25 12:23:51'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2027
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge	
The photograph is from a picture by [Mr Farren](../persons.html#500) the young artist whom [I](../persons.html#939) wanted to [illustrate](../others.html#167) your [Bethlehem](../others.html#177). I was anxious to know that you thought him up to the mark.

The picture was from Kingsleys Saints Tragedy, Saint Elizabeth of Hungary carrying her child to the altar in the early morning. I think it indicates a power considerably above average of entering into a spiritual conception.

But I should be glad of your opinion.
I am having all you sent of the Bethlehem set up. I would like to go over it altogether, and when I do I want to write you about it. I think there are two or three points which might [be] worth considering again.

But I will try to write at some length when I have the three chapters in type.
I am glad you find the Shipwreck Volms interesting.
I enclose a [cheque](../others.html#160) for the month. I think as far as I can guess that the story is liked.

Yours ever very truly
A.

Macmillan
