---
date: '1865-05-06'
display-date: May 6th 1865
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: MS British Library
original-date: '2010-05-25 12:33:00'
title: To Alexander Macmillan
wordpress-id: 2028
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939),
Many thanks for the [cheque](../others.html#160) for £25 for this month’s [Dove](../books.html#62). I am not sure whether a letter is still a sufficient receipt, if not please let me know, and I will send a stamped one, but receipt stamps are not easy to come by when one is out of the article, unless we are sending to Winchester, therefore I think it better to acknowledge the cheque at once.

And at the same time I send [Jacob](../others.html#177). I want to give the full scene and circumstances of each stage in foreshadowing and prophecy where it is possible. I am at Moses now and after Balaam I suppose Rahab and Ruth must be touched, and then the promise to David made out fully.

Then Isaiah meeting Ahaz at the high way to the Fuller’s field, /Micah\ - Jeremiah’s 31st chapter, Daniel’s fixing the time, the reoccupation of Bethlehem after the captivity. I have no doubt there is much that needs consideration in what I have done. I dwelt much on the doom on the physical world because I wanted to shew what was remedied and what was not, and besides I think the true connection of decay and pain in the animal creation with human sin is rather a relief than otherwise to a young mind, which is other wise grieved by the problem of innocent things suffering.

But I have no doubt that there is much that I have not done well, or made out as I meant to do it.

The photograph is very full of expression. I must confess to not having read the Saints’ Tragedy - and but for the candles, the picture made me think it was an eastern scene.

The figures all have an eastern look.
I have the [magazine](../others.html#78) now, and I see no slip to care about too much, except that Maximilian was not then king - which no one will know - and that the contraction of Ermentrude’s name should have begun with an T instead of an F.

It is a fatality common to all magazines I suppose - for it is always befalling the [Monthly Packet](../others.html#52) - that similar subjects come together - and thus the twin sons exactly alike in the Tale of the New Forest are an odd coincidence with the chief heroes of the Dove

Yours sincerely

C M Yonge
