---
date: '1865-05-08'
display-date: May 8. 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (1): P. 450'
original-date: '2010-05-25 12:48:35'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2029
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge	
Your note will do very well in the mean time.

If [I](../persons.html#939) can remember, tomorrow, I will get you and send you a small formal receipt book which you will be able to sign with little trouble.
I have only got the first [chapter](../others.html#177) in type, the one I sent and you returned. I read it through once to myself and then aloud yesterday.

The impression I had at first was somewhat confirmed on this reading. I think you will find yourself rightly[?] that it is rather meagre for an opening, slight and unimpressive compared with what I am sure the rest will be.

The quotations dont please me quite.

You should tell your story yourself, not through scraps of this & that.

Of course I dont mean the quotation from the Gospel which is admirably brought in, and just as it ought to be. I am asking [Clay](../others.html#173) to set all you have sent up in type.

Then I mean to go over it again carefully, and I will tell you all I feel. I think it possible as I see the subsequent parts I may feel the meagreness of the first chapter less.

Have you Kittos Cyclopaedia, or Pictorial History of Palestine, or Bible Dictionary?
