---
date: '1865-05-10'
display-date: May 10. 1865.
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (1): P. 463'
original-date: '2010-05-25 15:14:28'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2032
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge, 	
It is most kind of you to take my crude criticism in so good part. [I](../persons.html#939) did think of the parts, and your possible motive in dwelling on the opening [chapter](../others.html#177) in the slight way you have done.

Still with an eye to what is coming I cannot but think that the opening should be fuller, more sonorous and in a higher key.

But I have asked [Mr Clay](../others.html#173) to let me have all you have sent put up in type and then I will be in a position to write you at greater length and with more complete knowledge of what the whole idea is.
I think the whole book should be in a somewhat lofty rapt mood.

The 'piece of the ear & the leg,' and the broad tail of the sheep jarred on me. I dont know that I am right, but the mystery and awe, though they clearly demand quietness yet seem to demand that it should be rhythmic, as if one could chant it.

If I might prescribe I should say one should read the 34th chapter of Ezekiel and the 23rd Psalm aloud to get the [illegible]
But I am trying your patience enough in generalities. I have every confidence that the book will be a noble one. I have been reading the second part of the '[Dove](../books.html#62)' with great delight. I hope you are getting the proofs all right.

Would you like me to send you Stanleys sermons.

Pray say if you would also if you fail to get Thomson Land and Book &c.

The [London Library](../others.html#29) will get it for you. I have of my own Kittos Pictorial History of Palestine if you would like to see it.
I will send the sheets to [Appletons](../others.html#142) and [Tauchnitz](../persons.html#1396) regularly.

The Yankees are very sharp and it appears to me that they are acting systematically on [getting](../others.html#172) as much as they can on all hands.

But I fancy you will get your money in the long run. I got a little for Mr [Henry Kingsley](../persons.html#1940)s two last novels £20 a piece - from [Ticknor & F](../others.html#179).

He paid me about a month ago.

They had waited a while before sending it
Yours very faithfully
Alex Macmillan		
</p

[^1]: Arthur Penrhyn Stanley (1815-1881), Dean of Westminster, published many volumes of sermons.

His Sermons preached before the Prince of Wales during his tour in the East in 1862, with notices of some of the localities visited (London : Murray 1863) is probably the one referred to here.

[^2]: Publishers of CMY’s works in America.

[^3]: Ravenshoe (1862) and Austin Elliot (1863).

