---
date: '1865-05-30'
display-date: May 30. 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (2): P. 526'
original-date: '2010-05-26 11:06:47'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2037
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge	
[I](../persons.html#939) was only able last night to read over carefully and coherently the whole of what is now in proof. I like it very much in many respects.

But in what was my main idea in the [work](../others.html#177), and which I thought you agreed with me in, it really is seriously lacking, and the lack of this idea seems to me to deprive it of the unity which would so greatly increase its interest and value. I am afraid I must have been indistinct in what I said, but what I meant was that a Cradle song should be felt throughout.

The point and head of each chapter should be a truth, or an expectation of a birth.

The feel that made the Jewess so long to be a mother in Israel was the feeling I wanted to see dominate.

In the first Chapter, besides the shepherds a little more about Mary, the Promise given in the Annunciation, the child in the manger cradle might have been given, but in the second chapter instead of the Fall being the prominent object, this and all its results. I would have in subordination, and the first new child that ever was in the world.

Then the second, then the promise of the triumph of the dead, the awful and disastrous failure in the case of the first example of the seed.

This is what was in my mind. A dim far off vision of the coming of the seed might be seen in Abel, and yet what a contrast.

Again the third chapter I think should open with Isaac’s birth and the rest be reflective.

The promise of blessing through seed, the long delay, impatient attempt at fulfilment.
I dont like to go into too much detail.

But please tell me if you understand what I mean.

The subject, or theme as they say in music should be the cradle song.

Will you tell me if you think I am wrong or right, or if you think I should go into the explanation more fully.

Ever dear Miss Yonge
Yours most truly
A.

Macmillan	
[Cawnpore](../books.html#59) has gone to the printer.
