---
date: '1865-06-26'
display-date: June 26. 1865
from-address: ''
manuscript-location: 'Copy outletter British Library Add MSS. 55384 (2): P. 604'
original-date: '2010-05-26 13:13:49'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2049
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge
The M S. has come all right.

Sending as early as - [I](../persons.html#939) am thankful indeed you do, to address him here is the simplest way.[^1] His private address is 2 Newton Villas Finchley New Road. N.W.
I shall be very glad to hear about the result of your conference with [Miss Sewell](../persons.html#1301).

My only feeling in the suggestion I made re - Montfort was that each [volume](../books.html#71) - supposing it is found that we have so emphatically met a public want that go beyond the first, which I dont in the least doubt [-] should be complete as to an idea, not merely to a year.

What you suggest clearly fulfils this better than my crude list.
I shall be very delighted to have your [Prince & the Page](../books.html#61) for a Christmas book.

For the illustrations, photolithography which was use in the case of Kingsleys Water Babies will be better than zincography[.] But both are inclined to be rough.

But I will go into it carefully, if you will kindly send me one of the drawings. I will also go over the story itself [to] see what quantity it will make, like the [Little Duke](../books.html#20).

This months number of the Dove is admirable, so clear and firm in [illegible] tone, reminding me constantly of these qualities in [Scott](../persons.html#1672). I was thinking why should not the Christmas book be written in this honest style.

Pardon me.

Yours very faithfully
A.

Macmillan

[^1]: This refers to the chapters of [The Dove in the Eagle\'s Nest](../books.html#62) which she was sending to [David Masson](../persons.html#980), editor of [Macmillan’s Magazine](../others.html#78), where it was being serialized.

