---
date: '1865-07-03'
display-date: July 3. 1865
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS. 55384 (2): P. 625'
original-date: '2010-05-26 13:50:40'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2051
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge	
Your scheme as decided by [Miss Sewell](../persons.html#1301) and yourself seems to me very admirable.[^1] The one question is the compactness and vivid unity, which will be hard rather in an [illegible] such as you propose.

But with artists like yourself [and] Miss Sewell there should be no difficulty[.] the thing ought to be very interesting indeed.
[I ](../persons.html#939)have read all the [Prince and the Page](../books.html#61) down to the present month. I think it delightful, and hope it will make a very nice Christmas book.

But I confess I do not feel quite clear about the [illustration](../others.html#167).[^2] At a first glance it does not quite please me.

The Architecture in any case should be more subordinated, but my first impression of the figures is rather that they are weak. I will write more about it tomorrow.
ever most truly yours
A.

Macmillan
The enclosed cheque is for both your [story](../books.html#62) & [paper](../books.html#59) - which [illegible] capital.

[^1]: The scheme was for the book which became [Historical Selections](../books.html#71).

[^2]: CMY was trying to persuade him to use a drawing by [Katie Johns](../persons.html#887).

