---
date: '1865-08-05'
display-date: 5th August 1865
from-address: ''
manuscript-location: MS BL Add. 57,504 f.128
original-date: '2010-05-19 09:16:30'
title: 'Frances Mary Yonge to Daniel Sedgwick '
wordpress-id: 2063
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Mrs Yonge informs Mr Sedgwick[^2] that the Hymn ‘Think of the Mercy’ - was written by a young lady who died at fourteen, many years ago, she was the youngest daughter of the [Dean of Winchester](../persons.html#542).[^3] The other hymn ‘And is the day of mercy set’ was taken from a book ‘by a Layman’.

The book having been a borrowed book the publisher’s name cannot be referred to

[^1]: Miscatalogued as from ‘Miss Yonge’.

Black-edged paper.

[^2]: Daniel Sedgwick (1814-1879), a hymnologist, was seeking information about hymns in the collection produced much earlier by FMY: [The Child\'s Christian Year: hymns for every Sunday and Holy-day.

Compiled for the use of parochial schools](../others.html#186) (Oxford : J. H.

Parker 1841).

The two hymns appeared there for Christmas Day and for the Second Sunday in Advent respectively.

[^3]: Inserted in pencil in another hand, ‘Miss Jacob’.

This however is an error for \'Miss Garnier\'.

John Julian’s Dictionary of Hymnology (1898), which drew on Sedgwick\'s collections, notes that it was written in 1835 by Emily Garnier, daughter of the Dean of Winchester (II, 1164).

