---
date: '1865-08-13'
display-date: Aug 13th [1865]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 107-8 '
original-date: '2010-05-27 13:44:47'
title: To Alexander Macmillan
wordpress-id: 2065
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
Thanks, here are the receipts. I think I once got 5/ in like manner before from the Cape.[^1] I am not able yet to speak with any certainty of our plans.

We have just offered ourselves to my [uncle](../persons.html#1623) for the 8th of September, and there is such a vista of relations to stay with when once we get into Devonshire, that I do not think we shall come to London till the middle or end of October, and that is dependent on whether [Mr](../persons.html#558) and [Mrs Gibbs](../persons.html#1856) have finished some alterations they are making to their house at St Dunstans - so it is not at all worth while to try to make times fit, though if our London visit does come to pass I should be very sorry to miss you.

Could we not accomplish a meeting at the British Museum and looking together at some of the wonderful wood cuts of Maximilian’s time.

In the Nuremberg Chronicle, there is a wood cut of Ulm which would make a delicious frontispiece, and I know I could borrow that, or I suppose it could be copied in the Museum.[^2]
I fancy a few facsimiles (reduced) of those curious wood cuts such as this and one or two from Theurdanck and the Weise Konig would be very attractive.

Yours sincerely

C M Yonge
I hope in a few days to send the rest of the [Prince and the Page](../books.html#61).

[^1]: Money received in respect of the sale of [pirated](../others.html#172) American editions in the British Empire.

[^2]: These [illustrations](../others.html#167) were intended for the volume edition of [The Dove in the Eagle\'s Nest](../books.html#62).

