---
date: '1865-10-04'
display-date: Oct 4th 1865
from-address: '[[other:181]Sorel] Torquay'
manuscript-location: 'MS British Library Add MSS 54920: 111-2 '
original-date: '2010-06-03 11:56:54'
title: "To Alexander Macmillan\t\t\t\t"
wordpress-id: 2073
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939)
I enclose the [receipt](../others.html#160) with many thanks.

Your letter followed me hither this morning. I think we shall be in these parts about a fortnight longer - and shall then come to a place about a couple of hours of London - whence I hope to run up for a few hours to town, and I shall then be able to talk over matters with you. I fancy it will be somewhere about the 25th, but our doings are some what uncertain
I hope you had weather as fine as ours. I have scarcely seen a drop of rain since we left home this day four weeks.

Pray do not decide on the [Dove](../books.html#62)’s illustration without looking at the queer old contemporary books.

Ulm from the Nuremberg Chronicle which I could easily get etched exactly in pen and ink would be explanatory, being that I constructed the topography in the story from it.

How intensely interesting the history of [Eyre](../persons.html#1960) the explorer is.[^1]

Yours sincerely

C M Yonge

[^1]: Edward John Eyre, Journals of Expeditions of discovery into Central Australia, and overland from Adelaide to King George’s Sound, in 1840-1, including an account of the manners and customs of the Aborigines, and the state of their relations with Europeans 2 vols (1845). CMY’s deep enthusiasm for missionary work explains her interest in the book; this very month, however, Eyre, as Governor of Jamaica, repressed an uprising with a violence which led to a public controversy and the ruin of his career.

