---
date: '1865-12-06'
display-date: Decr 6th 1865
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54920: 119-20 '
original-date: '2010-06-04 21:18:53'
title: "To Alexander Macmillan\t\t"
wordpress-id: 2083
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
Will you direct this on if you know the address - if not perhaps [Mr Williams](../persons.html#1964) would kindly do so. [M.

Pichot](../persons.html#1172)[^1] wrote to ask my sanction for translation of the Dove, and I answered that I had already given permission to [Mlle Souvestre](../persons.html#1354).

But the next thing I heard was that Mlle Souvestre had given it up for want of time so that I must write to him again, and I had made away with his letter.

Messrs [Spottiswood](../others.html#183) have sent to me for the preface to [the Prince & Page](../books.html#61). I think I enclosed it to you about a month ago, but if you do not find it ready to hand, I can easily write another.

The book is smaller than I thought it would have turned out, and must I suppose be less costly than the [Little Duke](../books.html#20).

Yours sincerely

C M Yonge

[^1]: Amédée Pichot (1795-1877) was a prolific translator; his work included La Colombe dans le nid de l’aigle (Paris: 1867).

It seems CMY proposed to get in touch with him through [Williams and Norgate](../others.html#165).

