---
date: '1865-12-01'
display-date: "Decr 22d [1865]\t"
from-address: ''
manuscript-location: MS University of Delaware
original-date: '2010-06-05 11:37:18'
title: "To Ellen Julia Johns\t\t\t\t"
wordpress-id: 2088
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Johns](../persons.html#772),
I suppose you are enjoying a Christmas rest, indeed I almost expect to hear that [Mr Johns](../persons.html#769) is spending his holiday on a visit to [Katie](../persons.html#887).

The business of my note is however to tell Katie or ask you to be so kind as to tell her, that we are having a great revolution in the state of [goosedom](../others.html#104).

Some goslings having grown lazy and some outgrown it, there is to be a break up, but I think we shall form a fresh society on the nucleus remaining, consisting of [Christabel](../persons.html#329) and probably my cousin the [Cricket](../persons.html#1603).

And I thought that probably likewise Kittiwake would wish to adhere, but as I have hardly time to write to her tonight will you kindly tell her about it. I hope she will find time to send us some drawings for the [Barnacle](../others.html#89) which is any way to be kept up.

We have had a sad week while the poor little [baby](../persons.html#1592) at the other house was struggling with whooping cough and with convulsions, and now it is a relief that her rest is come.

With all good Christmas wishes

Yours sincerely

C M Yonge
