---
date: '1866-01-22'
display-date: Jan 22nd [1866]
from-address: ''
manuscript-location: 'MS British Library Add MSS 54920: 134-5 '
original-date: '2010-06-05 16:49:16'
title: "To Alexander Macmillan\t"
wordpress-id: 2100
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
Thanks for your kind letter and for the [payment](../others.html#160). I quite agree to the [Sunday Library](../others.html#145) being brought out in parts, as a good plan. I think if it were made pretty and attractive children would take it in for themselves.

The difficulty to me at present seems to be, how to embrace the various subjects without being desultory. I suppose you mean that each part would be complete in itself, though three or six might form a volume - not that each part should be like a magazine with a fragment of many subjects.

In the latter case I should propose as a model a child’s Magazine called '[The Charm](../others.html#57),' which was so contrived that each subject occupied a sheet in each monthly part, and so when bound up all the history could be put together - all the science - all the story.

But such a procrustean bed must have been misery to editor and contributors and I fancy was much aided by unlimited woodcut power. I think however that there is quite 'scrappiness' enough abroad in the world, and that many mothers who say Magazines make their children desultory would gladly hail entire parts on one subject. I have written down most irregularly my ideas of a few subjects, but I have not time this morning to think all out specially not the biographies which should be more modern, and of younger people.

It seems to me as if the best way might be to draw up a very full prospectus, and bind it in with each part, announcing the subject of the ensuing Then I fancy No 1 might be Biblical, No 2 Biographical, No 3 Natural History - then perhaps a Biblical one again so as to have four volumes by the years end - though not a vol every quarter.

It seems to me that this would gain more readers.

It was the way that Parker’s (Oxford) Church history [sic] Stories were managed - they made up into volumes of their different subjects - without being consecutive. I think I know of some excellent contributors - and some I should like doing myself.

About the Editorship, I think I could manage it, if (I hate what I am going to say) I had full power of selection.[^2] I am not sure whether in religious matters - literary not practical - it is quite easy for two to work together unless their shades of opinion are very similar because it becomes a matter of conscience. I would gladly be on the staff of contributors, give all the help in my power, or else edit having full authority, but I am afraid of divided responsibilities. I know this has an unpleasant conceited sound, but it is brought to my knowledge again and again that my name is taken as a guarantee of an Anglican tone that is High and not Ultra high, and not at all Broad, that I do not feel as if it would be fair towards that class of readers to give that sort of sanction if I did not with my whole heart approve.

If I did become in any way responsible, it must be with full authority. I hope you will forgive me for saying so much - when it might be - that the colleague is altogether of my way of thinking.
I should avoid saying anything in the Sunday Library likely to be offensive to any sober minded person, because I think such expressions most undesirable to put before children but in collecting works by different writers to form a whole for the young, I think there ought to be some discretion in choice or in correction in the editor.
[Mr H.

Wilberforce](../persons.html#1510) has found a great blunder in the [Prince & Page](../books.html#61). I did not know that the Knights Hospitalers were not priests.

And I fear it is too much interwoven with the story for alteration

Yours sincerely

C M Yonge
Tell me if I should try to secure some contributors

[^1]: It appears that Macmillan was proposing a joint editorship with someone as yet unnamed. CMY’s reservations largely restate views she had expressed a year earlier when the Sunday Library was first suggested, in her letter to Macmillan of 10 February 1865.

