---
date: '1866-03-31'
display-date: Easter Eve [31 March], 1866.
from-address: Otterbourne
manuscript-location: MS location unknown. Printed in <i>[[otherbook:122]Dulce Domum]</i>,
  177-8.
original-date: '2010-06-07 12:47:34'
title: Frances Mary Yonge to Mary Ann Moberly
wordpress-id: 2112
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

It is quite a comfort, my dear [Mrs.

Moberly](../persons.html#1019), to have your letter, and to answer it immediately.

And it is better to write than to see you; our hearts would be too full for speech.

Charlotte and [I](../persons.html#1606) can only trust ourselves to talk at times.

It comes at the best possible time for us all; these services are so especially full of [Mr.

Keble](../persons.html#798).[^1] At the same time we are quite alive to the special mercy of his not having been left to linger a few sad, feeble years without [her](../persons.html#795) to comfort him, and I suspect that she feels that strongly herself.

She has surprised us so often, she may yet rally; and she has learnt her lesson of submission and patient waiting so thoroughly that any way it must be well for her.

The person I pity is [Sir William Heathcote](../persons.html#669); fancy having to appoint a successor! [Lady Heathcote](../persons.html#665) says he was quite knocked down by it.

Of [Dr.

Moberly](../persons.html#1015)’s two invitations, to the house of mourning and the house of feasting, it is not difficult to guess which he will accept.

Bitter as the sorrow is, I think it would have been worse but for the warning of last year; he had written so cheerfully of late, we had almost forgotten his precarious condition.

It will always be a pleasure to Charlotte to think how welcome her Saturday’s letters have always been to them. I do not know how to leave off writing; it seems the only thing I have spirits to do. . .

[^1]: John Keble had died on Thursday 29 March 1866, the day before Good Friday.

His wife Charlotte, who had long been an invalid, survived him for only a few weeks.

