---
date: '1866-04-06'
display-date: April 6, 1866
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: "MS location unknown. Printed in Coleridge, <i>[[otherbook:40]Life]</i>\_\
  224"
original-date: '2010-06-07 15:47:36'
title: To Anne Yonge
wordpress-id: 2117
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Anne](../persons.html#1582)
Most peaceful, most gentle has the day been.[^1] The Psalms suited perfectly, and while we said ‘In His pleasure is Life,’ a butterfly flew about in the sunshine in church. I had a short talk with the [Bishop of Brechin](../persons.html#516) and told him your abode, and he hopes to come and see you about the end of the week.

You had not sent me the Hursley letter about our dear [Louisa](../persons.html#616).

When you can I shall indeed like to see it. [Mrs.

Wilson](../persons.html#1539) of Rownhams and I have been clinging together all day.
I did go to the early service, and stayed the time between at the park.

Is not [Sir William](../persons.html#669) to be pitied to have to supply such a place?

Such a [gathering of the good](../others.html#184).

Some said it was like Paradise, but oh! there tears and mourning will have fled away.

Your most affectionate
C. M.

Yonge

[^1]: Keble\'s funeral took place at All Saints, Hursley on Friday 6 April 1866.

