---
date: '1867-03-06'
display-date: Ash Wednesday [6 March 1867?]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2010-06-09 15:16:36'
title: To Christabel Rose Coleridge
wordpress-id: 2150
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329),
I should not have been so ungrateful if I had not been laid up, first by being deluded into eating some Scallop fish that everybody else flourished upon, and then by a wicked chair, which cast its hind leg as I was sitting down on it, and strained my back - Not till lately have I had the energy to pack up the Answers and write to you. I shall be very thankful if you will steer the [Barnacle](../others.html#89) boat for me and become its headquarters.

If you would put in the list of rotation into the fly leaf of each number, perhaps you would digest it better than I do - for mine seems utterly unattended to.

Have you ever heard of the new number, I sent a confirmation to [Ladyfern](../persons.html#455) about it of which she has taken no notice to me, and I further have set her [Aunt](../persons.html#930) at her. I think we must devise some other binder.

The first eight are at Torquay, and I have desired [Fern Seed](../persons.html#1160) to send them to you.

It really will be a very great help if you will take the Barnacle branches off my hands. I suppose the MSS had better still come to me, and then I will send them to you, and you to that bad Ladyfern unless we turn her off. I am glad you & [Mrs Coleridge](../persons.html#1976) thought as I did that the National Goosedom idea is wild and impracticable, and likely to come to nothing.[^1] I was not quite sure whether it was not my own old fashionedness, and so wanted to get some fresh opinion on it.

They have had a little Gaggle at Torquay[^2] in imitation of yours
your affectionate

C M Yonge

[^1]: No doubt a scheme to expand the [Gosling Society](../others.html#104), as was eventually done with the [Spider Society](../others.html#116).

[^2]: Three Goslings, [Emily Maconchy](../persons.html#945), [Paulina Martyn](../persons.html#973) and Frances Peard, lived in Torquay.

