---
date: '1867-03-25'
display-date: March 25th [1867]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 174-175'
original-date: '2010-06-10 08:47:48'
title: "To Alexander Macmillan\t\t\t "
wordpress-id: 2156
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
The [Chaplet of Pearls](../books.html#69) is done, and I shall send it by train tomorrow, being glad to get it out of the house, as it entices me into touching it up when I ought to be doing other things. I am afraid you will think that though it is not a story without an end, yet the end is very far away - but it would not be shorter, and judging by the number of chapters I do not think it is as long as [Redclyffe](../books.html#15). I do not think it would shorten without taking away the sense of time and proportion - which is wanted in a finished tale, though not so much in a magazine. I have had editorship enough to know what an unfinished story is. I made a resolution at first about accepting any tale without its end, and never broke it without being sorry for it - even with people I could trust.
I saw [Miss Wilbraham](../persons.html#1513) on Saturday and I think she seems likely to be able to write for the [Sunday Library](../others.html#145) - but her [mother](../persons.html#1982) is such an invalid that she is always rather uncertain.
I must write about the Penny Readings when I have thought more about them.
I must put a note to the Chaplet begging people not to think it a controversial tale - is it any use to do this to the 1st chapter in the [Magazine](../others.html#78), or had it better wait to be a preface to the whole?

Yours sincerely

C M Yonge
