---
date: '1867-07-01'
display-date: July 1st [1867]
from-address: Elderfield Otterbourn
manuscript-location: 'MS British Library Add MSS 54920: 181-182'
original-date: '2010-06-10 14:50:05'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 2183
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
I believe the childish form does not last,[^1] it is always cramping and a scratch of the pen will alter it where it prevails.
I was sorry afterwards I had not mentioned St John being recognised by his former pupil, the captain of the robbers, when he went out to be taken by him.

It would be a fine subject for expression, and I wonder it has never been taken before. I believe I meant Archippus - the (supposed) angel of Laodicea as the third pupil of St John, but there is not enough of him to stand alone, without a wonderful amount of sermonizing - so I have worked him in with the other less little distinguished and half made out people.
I hope you will put an Eagle on the [cover](../others.html#167).

Have you seen the Eagle in New College Chapel, it is a magnificent creature, and I should most particularly like to have it either there or in the title page, or both, for many reasons. I would send you a photograph but the one I have is not in the best position - and you are so much at Oxford that it would be sending coals to Newcastle.

What a fair and sensible article Mr Ll.

Davies’s is.

We are in a world of hayfields delicious to all senses

Yours sincerely

C M Yonge
It is just possible that on Wednesday or Thursday [Miss Sewell](../persons.html#1301) may call on you.[^2] If you will be from home on either of those days - would you let her know at the [Revd W.

Sewell](../persons.html#1306)’s
Huntley
Gloucester

[^1]: He had objected to the childish tone of her draft chapters of [The Pupils of St.

John the Divine](../books.html#72).

[^2]: This would be in connection with the book of [Historical Selections](../books.html#71) being compiled by CMY and Sewell.

