---
date: '1867-07-09'
display-date: July 9th [1867]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 183-184'
original-date: '2010-06-10 15:34:12'
title: "To Alexander Macmillan\t\t"
wordpress-id: 2186
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
I send up the two next chapters of [St John](../books.html#72), in case it should be convenient to show [Mr Armitage](../persons.html#60) the description of the scene with the Robber.

Do you mean to have [vignettes](../others.html#167)?

If you do the cup with the serpent should come at the end of the last chapter I send you, and the one I am writing now should have the golden candlestick, I should try for Diana for the first if the Ephesian Diana were not so frightful.
I suppose [Miss Sewell](../persons.html#1301)’s call on you was not accomplished.

It was to depend on whether she decided on going to the Paris exhibition
I am sorry she did not manage it, as it would have saved time

Yours sincerely

C M Yonge
Thanks for the [Pall Mall Gazette](../others.html#192), I thought it the most dangerous so I hope the others will be as polite[^1]

[^1]: The Pall Mall Gazette (2 July 1867), 11, reviewed [The Danvers Papers](../books.html#63) in appreciative if slightly patronizing terms.

