---
date: '1867-07-12'
display-date: July 12 1867
from-address: ''
manuscript-location: Copy outletter book British Library Add MSS.55387 (1) P. 348
original-date: '2010-06-10 15:53:36'
title: Alexander Macmillan to Charlotte Mary Yonge
wordpress-id: 2189
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge
[I](../persons.html#939) have sent the description to [Mr Armitage](../persons.html#60), who I am sure will be very glad to have it.

About [vignettes](../others.html#167) I am rather uncertain.

They are very dangerous.

Anything short of high excellence is apt to be commonplace and conventional.

The cup with the serpent dos not commend itself to me quite. I am afraid I have not much taste for arbitrary symbolism - meanings in fact I do like and in words.

However I think the three pictures will do excellently well, and Mr Armitage will treat them reverently and carefully. I hope to have one to show you before long.
I was so fortunate as to be in when [Miss Sewell](../persons.html#1301) called on Wednesday.

We had a nice long talk, I hope she will tell you the result!

On my return from America she hopes to be ready to begin to print. I start early in August.

The time between seems too short for all my preparations. I have been such a stick-at-home all my life that the prospect of a long voyage quite frightens me.
I am dear Miss Yonge
Yours very truly
A.

Macmillan
