---
date: '1868-02-18'
display-date: Febry 18th [1868]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2010-06-15 10:59:22'
title: To Christabel Rose Coleridge
wordpress-id: 2234
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
I am sorry not to have written to you before, but I could not get time before.

It does seem to me good time for a story again, but do you not think the Proverb foundation has been rather much worked and could not the subject be proposed in some other way.

For instance suppose [they](../others.html#104) were set to Write a story shewing the difference between Romance and Sentiment Only that cuts up your other question which I like very much I think the Genius and Imagination was once asked by one of the fireflies in her short life.[^1] I cannot lay my hand on your letter, and I do not feel sure what your other was.

Was it not something on national character[.] [Shamrock](../persons.html#1389) has never had a [Barnacle](../others.html#89) since June which I cannot make out at all, have I missed her in the list? I put her high up in the list for sending round the answers because I put London and suburbs as much together as I can.

What became of the answers I cannot think, the same great ones have stopped short somewhere and never got to [Bog Oak](../persons.html#28) nor home
your affectionate

C M Yonge
If you do want a proverb story what think you of ‘Dwarfs on giants shoulders see further than Giants’ but do not let me lose Romance & Sentiment

[^1]: It sounds as if there had been two members of the [Gosling Society](../others.html#104) with the sobriquet Firefly.

However, the only one traced is [Jessie Peters](../persons.html#1168).

