---
date: '1868-05-05'
display-date: May 5th 1868
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 195-6'
original-date: '2010-06-15 14:07:57'
title: To Alexander Macmillan
wordpress-id: 2243
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
Thank you much for your kind answer.

The second set of [cameos](../books.html#93) is nearly all written, but the [Monthly Packet](../others.html#52) must have the first turn of them and that will take a good while - about a year at shortest.
I am afraid you think me very idle about the [Worthies](../books.html#80).

The truth is that my [Mother](../persons.html#1606) has grown so infirm of late that I have less time than usual, and that time I thought it wise to spend in completing Monthly Packet Material, Cameos and a [story](../books.html#81) (of James I of Scotland in Captivity) that in case of being able to do no work, there might not be a stand still. I hope however to return ere long to Alexander the Great - whom I have left a full year on the Banks of the Granicus

Yours sincerely

C M Yonge

[^1]: The first volume of Cameos from English History was published in 1868, the second in 1871.

