---
date: '1868-05-29'
display-date: May 29 1868
from-address: ''
manuscript-location: 'Copy outletter book British Library Add MSS.55387 (1) P. 400 '
original-date: '2010-06-15 14:38:54'
title: 'Alexander Macmillan to Charlotte Mary Yonge   '
wordpress-id: 2247
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Miss Yonge,
[I](../persons.html#939) send you the first copy of the [Cameos](../books.html#73) which has been bound.

It has been delayed about that title page, in which I wanted to produce a [cameo effect](../others.html#167), [illegible] that may be.

The book I am sure is a charming book and we tried to give it an adequate dress.
I think [Clay](../others.html#173) is making better progress with the [Selections](../books.html#71). [Miss Sewell](../persons.html#1301) seems satisfied. I have never I think spoken of terms to you or her.

We would I think be disposed to buy this as we did the Cameos.

Do you think this would please both?

One cannot [4 lines too pale to read.]
I dont forget that we owe you for the Cameos & the [Pupils](../books.html#72). I am afraid that we shall find the number published of the [Library](../others.html#145) [illegible] of the volumes.

Yours very faithfully
Alex Macmillan
