---
date: '1868-07-01'
display-date: July 1st [1868]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2010-06-16 09:27:54'
title: "To Christabel Rose Coleridge\t\t\t\t\t"
wordpress-id: 2255
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
Here are the answers but I really have no time to do their Cackle.

The two months holidays come now, and would you kindly tell the brood that I think they had better not send me any questions after the holidays till I tell them. I hope by no means to give up [Goosedom](../others.html#104) in the end, but [Mamma](../persons.html#1606) is so sadly failing that I must for the present drop all unnecessary claims on my time. I can still do things but those that tie me to certain days are necessarily many, and as things can only get worse, I am sure it is better not to do what can be dispensed with.

Please make the others understand this, and likewise that I hope to return to my Goose work some time or other Tell them also that [Bog Oak](../persons.html#28) resigns, as she is going out to work at Cape Town under the [Bishop of Capetown](../persons.html#578).[^1] N B dont write this about her to her two cousins [Sparrow Hawk](../persons.html#97) and [Iceberg](../persons.html#1384), as her uncles & aunts are only to be told too late to make a remonstrance.[^2] In fact I think the Torquay ones had better simply be told she resigns.
I saw [Katie Johns](../persons.html#887) yesterday but not to speak to
your affectionate

C M Yonge

[^1]: The boat sailed from Southampton, picking up Bishop Robert Gray and his wife at Plymouth on 10 October 1868.

[^2]: The mother of Sparrowhawk (Anne Baker b.1840/1) was sister to Bog Oak (Mary Anderson Morshead)’s father; her mother and the mother of Iceberg (Mary Sunderland 1853/4-1877), were sisters.

