---
date: '1868-07-22'
display-date: July 22nd [1868]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 203-4'
original-date: '2010-06-16 10:10:36'
title: "To Alexander Macmillan\t\t\t\t"
wordpress-id: 2258
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939),
I am afraid I have been guilty of a misunderstanding, and of leading [Miss Sewell](../persons.html#1301) into one, but I thought we were to have [£200](../others.html#160) for the copyright of the [Historical Selections](../books.html#71), and I must say I think it is hardly compensation for all the trouble it has given.

Miss Sewell has connection enough to secure it a good sale as a school book and we should be quite willing to take a percentage on the sale, only that the permanent long account to be divided would be troublesome.
I am afraid it is all my fault.

You offered us the same as I was to have for the [Cameos](../books.html#73), and I am afraid I did think this was £200 for want of referring back to your letter about them and thus I misled both Miss Sewell and myself so that we had agreed that she should have £125 and I £75. I am sorry I made the blunder, but I think that now, unless you would give us the £200 (which I really think that the copyright is worth) that a percentage on the price of each 100 would be the most satisfactory way

Yours sincerely

C M Yonge
