---
date: '1868-07-22'
display-date: July 22nd 1868
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: "MS Girton College Cambridge, GCRF 9/1/22. Partly quoted in M.C.Bradbrook,\
  \ <i>\u2018That infidel place\u2019: a short history of Girton College, 1859-1969</i>\
  \ (London: Chatto & Windus 1969)."
original-date: '2010-06-16 10:17:16'
title: "To Sarah Emily Davies\t\t\t"
wordpress-id: 2259
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[Madam](../persons.html#2014),
I am obliged to you for your letter respecting the proposed college for Ladies,[^1] but as I have decided objections to bringing large masses of girls together, and think that home education under the inspection or encouragement of sensible fathers, or voluntarily continued by the girls themselves is far more valuable both intellectually and morally than any external education I am afraid I cannot assist you.

I feel with much regret that female education is deficient but I think the way to meet the evil is by rousing parents to lead their daughters to read, think and converse.

All the most superior women I have known have been thus formed by home influence and I think that girls in large numbers always hurt one another in manner and tone if in nothing else.

Superior women will teach themselves, and inferior women will never learn more than enough for home life.

I say this much to shew that I do not hold back from the plan without having endeavoured to think it over

yours truly

C M Yonge

[^1]: Emily Davies was trying to gain support for a residential college for women where they could undertake standard undergraduate degree courses.

The college was established at Hitchin, halfway between London and Cambridge on 16 October 1869.

In October 1873 it was moved to Cambridge and renamed [Girton College](../others.html#201).

