---
date: '1868-09-15'
display-date: Sept 15th [1868]
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: MS Mrs Clare Roels
original-date: '2010-06-16 12:21:09'
title: "To Christabel Rose Coleridge\t"
wordpress-id: 2267
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
I think you had better guide the flight of the [Barnacle](../others.html#89) I have nothing special to observe about it, except that it might be worth while to let [Mary Morshead](../persons.html#28) have it at once, as I do not know how soon she sails.[^1] I suppose it is the last at least for the present[.] [Mrs Valentine](../persons.html#1437) is getting up another Christmas annual, especially for children, so I should think it might be worth while to write to her and then you could ask after Giftie.[^2] [Mamma](../persons.html#1606) is very weak and only gets up to take a short drive in her donkey chair every day. I think [Lady Coleridge](../persons.html#347) must be better since [Edith](../persons.html#331) saw her[,] for [Miss Dyson](../persons.html#464) seems satisfied about her, and she is at Ottery now.

your affectionate

C M Yonge

You idle [Gosling](../others.html#104) - you don’t give a hint where here  is - so this must go to Hanwell.

[^1]: For Cape Town to work as a missionary.

See letter to Christabel Coleridge, 1 July 1868.

[^2]: Laura Valentine worked as a children’s books editor for Warne, who published Giftie in 1869; the annual was probably Warne’s Home Annual (1869 etc).

Perhaps the Christmas 1868 edition was dated 1869.

