---
date: '1868-09-30'
display-date: Sept. 30, 1868
from-address: Otterbourne
manuscript-location: MS location unknown. This fragment printed in <i>[[otherbook:122]Dulce
  Domum]</i> 206-7
original-date: '2010-06-16 13:17:47'
title: "To Mary Ann Moberly\t\t"
wordpress-id: 2270
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs.

Moberly](../persons.html#1019),
Thank you for your kind, sweet, cheering note.

It does seem to me truly that it is the burden of the flesh [she](../persons.html#1606) is freed from, so entirely labour and weariness had the mere act of living been to her for months past; but with what sweet smiles![^1] I am glad your dear [Alice](../persons.html#1025) so thoroughly shared the peacefulness of the earlier watch, as well as that last trying day, which I trust will have done her no harm. I hope she and the [Goddaughter](../persons.html#81) may be with us on Friday.

She, with [George Yonge](../persons.html#1611) and (perhaps) [Duke](../persons.html#1599) and [Anne](../persons.html#1582), are the only ones to be with us here now who were with us before.[^2] The others have ‘all passed into the world of light,’[^2] - the dear [Kebles](../persons.html#798), [Lord Seaton](../persons.html#313), [Warden Barter](../persons.html#118), my cousins [James](../persons.html#1615) and [John](../persons.html#1618).

All Alice’s life I think she was the most loved and cheering young thing, out of the family, to both my [father](../persons.html#1631) and mother; and how she helped us in 1854! . . . I have been really alone for some time, so the loneliness does not press so much as no doubt it will.

[^1]: CMY’s mother Frances Mary Yonge had died on 28 September 1868.

[^2]: i. e. at WCY\'s funeral.

[^3]: Henry Vaughan (1621-1695): ‘They are all gone into the world of light!/ And I alone sit lingring here’.

