---
date: '1868-10-07'
display-date: Oct 7th 1868
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 216-7'
original-date: '2010-06-16 14:31:06'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 2278
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939),
Thank you for your kind note and expressions of sympathy.

It is the beginning of a lonely life to me, but I have my [brother](../persons.html#1624)’s house very near, and full of kindness.
I write now about that unfortunate [Cameo](../books.html#73) which was missed out.

The proof of it came to me first numbered XXXVI, which is its proper place, but the revise is XLII, so as to make it seem as if it belonged at the end of the reign of Edward II.

Would it not be better to indicate on it its right place than to number it wrong? I will keep the revise till I hear from you.

May I also ask if you absolutely reject the story '[Wooed and Won](../others.html#202)'-?[^2] If so let me know, but please do not return it till I write again

Yours sincerely

CMYonge
They are really using the Cameos in School at Winchester College

[^1]: Black-edged paper.

[^2]: A story for which CMY was trying to find a publisher, possibly the \'story of Indian life\' mentioned in the letters to Macmillan dated 23 September and 10 October 1868.

