---
date: '1868-10-10'
display-date: Oct 10th 1868
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 218-9'
original-date: '2010-06-17 20:56:09'
title: "To Alexander Macmillan\t\t"
wordpress-id: 2282
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
The lack of a tiger is serious. I mourned it as I read, and yet I thought it shewed some strength of mind to have avoided any ordinary ingredients of excitement.

And when we were reading many books aloud, I certainly found [this](../others.html#202) answer better than many with a more direct selling element did, and the freshness of descriptions to me compensated for want of incident.

Will you kindly direct it to [Mrs Valentine](../persons.html#1437), care of [Mr Warne](../persons.html#1433), and send it in. I think that they are beginning a system of one volume tales into which it might fit.[^2]
The other matter was a mistake of mine. I imagined that the lady wrote to me on behalf of a branch institution just set up at Grimsby instead of which it turned out that she was only staying there on a visit.

It was one of the confusions I made during the last months of illness.

The right direction is
The [Sister in Charge](../persons.html#2020) for the Grimsby connection.

Kings College Hospital
Portugal Street
Strand
and if you will so send the unfortunate parcel, I should be much obliged.
I find it is a library for the lady nurses’ own reading that they want - not as I fancied only books for the patients’ use.

So I think I had better send a copy of each of my tales, instead of only the three I mentioned before if you will kindly give orders accordingly.[^3]
Having lost the first letter I will not lay the blame on it, but I certainly did not understand it. A much more practical one has now come

Yours sincerely

C M Yonge

[^1]: Black-edged paper.

[^2]: CMY subsequently lent her name as editor to Warne\'s \'[Star of Hope](../books.html#212)\' and \'[Victoria Tales and Stories](../books.html#211)\' series.

Possibly the projected series may be connected with either or both of these.

[^3]: A list is appended in a different hand: ‘Heartsease, Dynevor Terrace, Heir of Redclyffe, Daisy Chain, Hopes & Fears, Young Stepmother, Dove in Eagle’s Nest, Clever Woman of A Family.’

