---
date: '1868-11-01'
display-date: '[November 1868]'
from-address: Puslinch
manuscript-location: MS location unknown. This fragment printed in <i>[[otherbook:122]Dulce
  Domum]</i>, 207-8.
original-date: '2010-06-18 08:59:27'
title: "To Mary Ann Moberly\t"
wordpress-id: 2293
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Many many thanks for [your](../persons.html#1019) most kind letter, and for telling me of the happy prospect before [Dora](../persons.html#968)[^1] . . . I have asked [Mrs.

Wilson](../persons.html#1539) to send on to you a letter of [Bishop Patteson](../persons.html#1155)’s, which I think you will feel refreshed by reading; please send it on to [Miss Anne Mackenzie](../persons.html#930).

You are so very kind, and it would be very delightful to make one in the migration; but I have only seen [Miss Dyson](../persons.html#464) for a day since her sorrow, and not at all since mine,[^2] and the meeting at Testwood has become such an institution that I could not fail in it, so I must wait until you are at Brighstone again, and I have always had a wish to see that in spring. I have just returned from [Lady Seaton](../persons.html#314)’s It is a [house](../others.html#126) of shadows and memories to me.

[^1]: Dora Frances Moberly’s had become engaged to the Rev.

Charles Martin, whom she married 14 September 1869.

[^2]: Mary Anne Dyson\'s sister-in-law [Elizabeth Dyson](../persons.html#462) (with whom she had lived at Crookham since her brother’s death) had died in the first quarter of 1868, and CMY\'s [mother](../persons.html#1606) had died on 28 September 1868.

