---
date: '1869-02-02'
display-date: Febry 2nd [1869]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 225-6'
original-date: '2010-06-18 14:19:37'
title: "To Alexander Macmillan\t\t"
wordpress-id: 2298
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
I enclose a [receipt](../others.html#160) with many thanks, and rejoicings that the books still continue to prosper. I should be finishing another [Worthy](../books.html#80) today if I had not five young cousins spending the day with me, but at any rate old Curius Dentatus will come before the end of the week, I chose him as the representative of the old hardy uneducated peasant king that the first Romans were.

Then comes Scipio for the Gentleman Roman before he was spoilt. I hope to be in London for a few days about the 1st of March, and will then bring you a specimen of the Double Skeleton.

Those papers were both very striking in the last no of the [Magazine](../others.html#78). I believe the fault is the father’s for paying no heed to the daughters interests.

Almost all the most superior girls I have known have owed much to their father’s influence. I am sure it made me.

The author of Estelle Russell has got the names of places at the Yealm so nearly right that one wonders that she made the charitable young lady walk across the estuary three miles broad at least, between Wembury and Revelstoke.
I think minute geography of real places is dangerous

Yours sincerely

C M Yonge

[^1]: Black-edged paper.

