---
date: '1869-03-29'
display-date: March 29th [1869]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54920: 230-31'
original-date: '2010-06-22 11:23:22'
title: "To Alexander Macmillan\t\t\t"
wordpress-id: 2313
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939)
I think I should enjoy editing a Globe edition of children’s books,[^2] and am much obliged to you for the proposal. I suppose the question is how many really good ones have exhausted their copy right.

Perhaps Philip Quarl could begin the series, it is really Defoe’s but I doubt if anyone has read it.
I send 9 chapters of the [Lion](../books.html#81).

One object is to make people think of that St Katharine’s charity, and its unhappy state of slumber. I make my heroine end there the heroine [sic] is much too poor a creature for her to marry.

Alas! under the impression they were in type, I made away with those sheets of the [parallel history](../books.html#89)! I am now waiting to go to Winchester to get some large paper ruled for me.
I must try to get matters forward by August, as then the [Chaplet](../books.html#69) is to treat me to a trip to Paris and [Val Richer](../others.html#205)
I am delighted with Miss Winkworth’s number of the [Sunday Library](../others.html#145).

Yours sincerely

C M Yonge

[^1]: Black-edged paper.

[^2]: This project became A Storehouse of Stories, [first series](../books.html#83) (1870) and [second series](../books.html#96) (1872).

