---
date: '1869-06-04'
display-date: June 4th [1869]
from-address: New College
manuscript-location: MS Keble College, Oxford, Liddon Correspondence 1869 (2:4).
original-date: '2011-10-12 13:57:41'
title: To the Reverend Henry Parry Liddon
wordpress-id: 2316
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Liddon](../persons.html#877)
Thank you for your very kind answer. A letter will be an excellent way of conveying your recollections.[^2] I think considering what Hursley Vicarage was, it would have been perfect treason to have made notes of the daily life and conversation - What seems to me most wanted is something to give an idea of [Mr.

Keble](../persons.html#798)’s greatness and his championship - and this [Sir J Coleridge](../persons.html#344) writing from an equality and without perfect sympathy, has in some degree missed.[^3]
A fortnight or a month’s time will be quite soon enough for me. I shall be at home I hope on the 12th
With many thanks
Yours very truly

C M Yonge

[^1]: Blue paper with the printed centred address ‘Elderfield, Otterbourne, Winchester.’ crossed out.

Transcribed by the librarian, Margaret Sarosi.

[^2]: This was published in MP and collected in [Musings over the Christian Year](../books.html#88).

[^3]: CMY refers to Coleridge\'s [A Memoir of the Rev.

John Keble](../others.html#226).

