---
date: '1869-09-06'
display-date: Sept 6th [1869]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS West Devon Area Record Office Ac 1092/35
original-date: '2010-06-23 11:44:54'
title: "To Charlotte Cordelia Yonge\t\t"
wordpress-id: 2340
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Charlotte](../persons.html#1587)
I have never thanked you for that kind note that told me so much and made me able to understand more of how the grievous scene went on, and how that [dearest one](../persons.html#1582) was taken and now I am wishing to know whether you think [uncle James](../persons.html#1614) or [Mr Rogers](../persons.html#2049) had at all apprehended that all the distressing symptoms of some years past were tending that way, as I now suppose they did. I was very anxious about her last year, and only said nothing (except to [Elizabeth Colborne](../persons.html#320)) because I thought [Mary](../persons.html#1626) could not bear to talk it over, and she certainly said things that shewed her to think that life was in a way over for her.

How Mary is to bear up against all that must fall on her now I cannot think. I long to be of some help to her, and yet I fear no one can help her, [Duke](../persons.html#1599) does more than anyone else. I remember last year dear Anne saying that when once Duke was in the house things seemed off one’s mind. I am glad [Katharine](../persons.html#1365) is old enough to have a distinct remembrance of her aunt. I hope [Helen](../persons.html#1613) will have the same – you cannot think how good and gentle she is to me now.[^3] how did you get through Sunday, I hope [John Morshead](../persons.html#43) came to help Duke. - I am imagining that the Organ must have been silent.

It will be very hard to you to begin to play it.

Whenever you can write to me I shall be very thankful, I feel as if I hardly knew myself without Anne to turn to and think of

your affectionate cousin

C M Yonge

Thank Duke for his letter I wrote to Mary yesterday when I found I could not come. I am better today, but I know he is right & that it is better not.

[^1]: Black-edged paper.

[^2]: CMY had asked Charlotte Cordelia Yonge for an account of the death of Anne Yonge.

[^3]: Katherine (b. 1863) was the eldest of Duke and Cordelia Yonge\'s children, and Helen (b.1860) was the eldest of CMY\'s brother\'s children.

