---
date: '1869-12-01'
display-date: Decr 1st [1869]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: Guildhall Library MS ii,012 v. 25 f. 233
original-date: '2011-10-10 16:36:52'
title: To Louisa Anne Gibbs
wordpress-id: 2356
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Louisa](../persons.html#1856),
I am so much obliged to you for that letter, I think the giving a set of necessary tables to be learnt by heart is an excellent idea which I had not thought of.[^2] I had come to your conclusion about questions. I had been always used to them with school children, but [Helen](../persons.html#1613) and [Arthur](../persons.html#1607) have minds and memories awake enough not to want to be badgered with questions.

The plan I have now drifted into is this - taking from 10 to 20 verses of the the Bible - putting first beside them a very easy kind of summary, professedly for ‘little ones’ but really to secure that stupid ones do not quite miss the drift of the narrative.

Then I do a comment, trying to take in geography, history customs, and the bearing of the chapter, anything in fact that wants pointing out I will see about maps, but I have never been in trouble to find them - between [Mant](../others.html#112) and Arrowsmith, and Crutchley[^3] which I generally use with Helen. I should like maps with the names and divisions for each period but it might make the book so much more expensive that it may serve as well to mention in the preface some good map book - such as I am sure the [N S](../others.html#32) have. I shall not go to the [SPCK](../others.html#40) they allow one so little liberty. I have also thought of giving references to good sermons or other comments or illustrations (not pictures).

If you have any notes of them, it would be a great help to let me see them, and your ‘old copy book’ of things to learn by heart.

In truth I passed over the Genealogy from Shem to Abraham, as I think that is the questionable time as to Usher’s Chronology, and that some generations are passed over.[^4] I have only gone as far as the 18th of Genesis, and that does not quite shew my plan, for I want to work in Psalms and bits of prophecies in their chronology when the time comes, and I shall put a few specimens of Job between Genesis and Exodus. I think it must be published in quarterly volumes - for one would be immense, and would take as many years as the [dictionary](../others.html#151). I wonder whether if I sent you a page or two you would have time or like to see whether it is the sort of thing. I do take the bits of comment I did for the [Monthly Paper](../others.html#81) where I can, but as they only belong to the Sunday lessons there is a great deal more to supply in between. I think you are quite right that the age from 10 to 15 should be the most considered, but if I possibly can, I want the book to serve for Schoolroom reading for children of varying ages, or to be read twice by the same child, once with the short summary and once with the long one.
I suppose the rule about short and long lessons varies with different natures.

Helen was horribly inattentive when I took her a year ago, now without scolding, but from sheer interest in the work she fills her whole mind, but she flags after a quarter an hour of the same thing, even when it is lengthened at her own wish.

Very likely this is different with boys.

Arthur a year younger, & with really a better head for arithmetic does one sum while she does two and writes one out, from mere dawdling, for many of the operations of the sum come more readily to him.

Yet he has much more force and power of combination.

But I did not mean to run on about them though they are my great delight. I hope [Kate](../persons.html#899) is coming to me in another fortnight.

yours affectionately

C M Yonge

[^1]: Black-edged paper.

[^2]: This letter seems to be a response to Louisa Gibbs’s comments on CMY’s [Keynotes of the First Lessons for Every Day of the Year . . .Published under the direction of the Tract Committee](../books.html#79) which was issued by the SPCK in 1869.

But the plan for a larger book may relate to [Scripture Readings for Schools and Families](../books.html#87) (1871-1879.

[^3]: The Rev.

Richard Mant, Bishop of Down, was one of the editors of a family Bible (1814), with notes including maps, published by the S.P.C.K, which CMY mentions her father using in her childhood: ‘Daily, before breakfast, he read the Bible with us, from Mant’s edition’ ‘A Real Childhood’ Mothers in Council II, No 5 (January 1892) 15-19.

[^5]: James Usher or Ussher, Archbishop of Armagh (1581-1656) had established in the 1650s that the date of the foundation of the world was 24 October 4004 BC; this reference reflects CMY’s sense that modern geology and ancient history have disputed the date, and also her unwillingness to deal with controversial matters.

[^6]: Kate (Crawley) Low was a first cousin of Louisa\'s husband Henry Hucks Gibbs.

