---
date: '1870-03-02'
display-date: March 2 [1870]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Mrs Clare Roels '
original-date: '2011-02-03 11:15:19'
title: To Christabel Rose Coleridge
wordpress-id: 2374
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
Yes, the Coral islands and King René will do very well, but really the [Goslings](../others.html#104) are so long that I do not think they are worth keeping up. [Cricket](../persons.html#1603) and [Double daisy](../persons.html#1161) are the only ones who have sent answers and that only to Henry VIII [^2], I thought Ulysses might have been so entertaining but I believe nobody that does not live with a public library ever has books enough.

Your modern story is a good notion, it is one I once tried, but I did not get on with it, partly for want of experience of suburban people.

Can’t you give your refined young lady a sense of humour to enliven her, and let her see the absurdities that the unrestrained run into?
your affectionate

C M Yonge

[^1]: Black-edged paper.

[^2]: ‘Write the history of Henry VIII’s expedition to France.’ Sent to Mary Fursdon 29 January 1870.

