---
date: '1870-03-14'
display-date: March 14th 1870
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS John Rylands Library, Manchester, FA1/7/832
original-date: '2011-02-03 11:31:46'
title: To Edward Augustus Freeman
wordpress-id: 2376
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Freeman](../persons.html#523) [^1],
I waited to thank you for your kind note to see if there was any chance of so getting rid of the old edition of [History of Christian Names](../books.html#48), as to make it reasonable to put an abridgment much corrected in hand - But unluckily the book was printed in the anarchy of the [J W Parker](../others.html#152) establishment and the edition was too large, so that I do not know how to get through the dregs of it, and [Mr Macmillan](../persons.html#939) does not give much encouragement to selling it off en masse.

It is a pity for I would like to improve it myself, but on the other hand, though some part - i.e. the Teutonic, I could mend, all I know about the Keltic is that it is all wrong! I long to sweep away the letters of the alphabet which I blundered out without having ever heard of Grimm’s law.
I have always wished to tell you that it was on the authority of [Professor Münch](../persons.html#1071) of Christiania that I made those Frank names like Hadweh &c come from wehe - consecration, instead of wig - man. [^2] He died just as the book came out, and I have never been able to find out if this was a crotchet of his own or not.

Two or three people busy in education want the old Stream of Time renewed, corrected and modernized.[^3] I believe it would be very desirable if only one could indicate the doubtfully a haze of some kind.[^4]
Yours very truly

C M Yonge

[^1]: The name has been written over the word \'Sir\'.

[^2]: Peter Andreas Münch (1810-1863), mediaeval historian and uncle of the painter Edvard Münch.

[^3]: A translation and continuation, by William Bell, of Friedrich Strass\'s general chronology, originally published in England as Descriptive Guide to the Stream of Time, or, General Outline of Universal History, Chronology and Biography, At One View (London: Vernor, Hood & Sharpe 1810).

[^4]: The sentence is indecipherable.

