---
date: '1870-03-30'
display-date: March 30th [1870]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Mrs Caroline Fairclough/24 '
original-date: '2011-02-08 16:37:26'
title: 'To Arthur John Butler '
wordpress-id: 2377
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Arthur](../persons.html#238)
Authorities for the wars of the Roses are very scarce and bad. I believe [Sharon Turner](../others.html#172) [^2] is the modern who has done them up best, and his notes guide to the places where he gets his authorities. I believe the best, next to the Paston letters are Polydore Vergil, and a certain Abbot /(I think)\ Welthamstead of St Albans who was a great Lancastrian till Queen Margaret let her wild Borderers plunder his Abbey.[^2] I believe that there are lots of documents scattered about, original letters &c.

Shakespeare went by Hall and Hollingshed and Fabyan’s Chronicle which are none of them precisely history, but Lingard and Turner tell one what is borne out.

Did you ever meet with Philippe de Commines he is deliciously quaint and his mediaeval French would delight you.
[Polly](../books.html#348) has been regularly squeezed out of two or three numbers of the [M Packet](../others.html#52) - when there are rampant contributors wanting to get in, I have to sacrifice her.

She was actually in this month, and then came a London school that had to beg now or never.

Your bit of Gothic is not beyond my powers when I have not - as at this moment [Helen](../persons.html#1613) painting and asking me questions every minute but I will not keep the letter waiting for greater discretion
I hope Polly will continue in another month, it is written, but it is waiting for room. I hope to be at Wantage for a day or two at the end of May.

yours sincerely

C M Yonge

[^1]: Black-edged paper.

[^2]: CMY presumably refers to John Whethamstede (c.1392–1465), Abbot of St.

Albans.

