---
date: '1870-05-30'
display-date: 'May 30th [1870] '
from-address: 'Wantage '
manuscript-location: 'MS British Library Add MSS 54920: 240-1  '
original-date: '2011-03-02 10:38:32'
title: 'To an Unknown Woman or to Alexander Macmillan? '
wordpress-id: 2381
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear Madam,[^2]
I have been having some talk and consultation about the Godmother’s Readings with people who have so much to do with schools as to be really an influence
First, I am advised strongly to do - what I proposed at first - to have the Scripture part, without the comment, printed separately, as cheap as may be, for the children to use, while the teacher has the one with the comment. I do believe this would be greatly used in Schools if we can make it cheap enough[^1]
Another advice is to keep the Godmother out of the title, as that is thought likely to discourage the sale for Schools. I suppose if my name goes to it, the individuality would be marked enough. I believe it is only the first page that this change would affect
Scripture Readings
by

Charlotte M Yonge
Then people would ask for it as Yonge’s Scripture Readings.

My address here is the [Rev’d Wm Butler](../persons.html#244)’s Wantage - I go home on Thursday

Yours sincerely

C M Yonge

[^1]: Black-edged paper.

[^2]: This letter is among the correspondence with [Alexander Macmillan](../persons.html#939), and the salutation may simply be a mistake.

Or the letter may have been addressed to his sister-in-law [Eliza (Orridge) Macmillan](../persons.html#941), who was his partner, but one would expect CMY, who had met her, to address her as Mrs Macmillan.

Or it is possible that the letter was addressed to [Frances Martin](../persons.html#971), the editor of [Macmillan\'s Sunday Library](../others.html#145), although the Scripture Readings do not appear to have come out in that series.

[^3]: The first of the [Scripture Readings for schools, with comments, Genesis to Deuteronomy](../books.html#87), was published by Macmillan in May 1871; it cost 3s. 6d. and the version without comments was 1s. 6d..

Eventually there were 5 volumes, 1871-1879.

