---
date: '1870-05-31'
display-date: 'May 31 st [1870] '
from-address: 'Wantage '
manuscript-location: 'MS Mrs Clare Roels  '
original-date: '2011-03-02 10:44:10'
title: 'To Christabel Rose Coleridge '
wordpress-id: 2382
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
The [Goslings](../others.html#104) will not die. I find we had better kill the useless members, and get some quite young ones in keeping the questions easier- We have now left only [Cricket](../persons.html#1603), [Frog](../persons.html#822), [Double Daisy](../persons.html#1161) and[ Pixie](../persons.html#539) to whom is to be added
The Honble
[Alethea Colborne](../persons.html#317),
Beechwood
Plympton
I am not sure what she is to be called [^2]- Can you still be Secretary even if you have no time for the Questions?

It would be a great help to me.

Frog [^3] proposes a new one but I have not the particulars of her yet. I am going home on Thursday I have had a very pleasant expedition all round Devon ending with Torquay and Ottery.

Frog suggests the Goslings writing their criticisms below Cackle, which would be amusing, I think
your affectionate
Mother Goose

[^1]: Black-edged paper.

[^2]: Mary Fursdon was told Alethea Colborne was to be Bluebell on 10 July 1870.

[^3]: CMY was staying with Frog\'s parents the Butlers at Wantage Vicarage.

