---
date: '1870-12-31'
display-date: Decr 31st [1870]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library. Add MSS 54920: 244-5  '
original-date: '2011-06-02 12:24:57'
title: To Alexander Macmillan
wordpress-id: 2396
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
Do you not think that the [parallel history](../books.html#89)[^1] should come out in time for Schools to set themselves up with this winter.

The one I wrote it for is crying out for it, and it seems in vain to wait for a neater finish to France than the fall of the Empire.
I am glad you give hopes of clearing off the old [History of Christian Names](../books.html#48) I have them bristling with corrections, and I should begin by cutting out large pieces of the book - but alas, I have acquired no further knowledge of the Keltic names - always the weakest point in the book.

Only I do know that some part is more desperately wrong than the rest.
I have been writing to [Miss Martin](../persons.html#971) about the [Founders and Pioneers](../books.html#90). I believe they are ready now.

Yours sincerely

C M Yonge

[^1]: Her A Parallel History of France and England, consisting of Outlines and Dates (London: Macmillan 1871) was on the verge of publication.

