---
date: '1871-03-16'
display-date: March 16th 1871
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Caroline Fairclough/25
original-date: '2011-06-02 14:50:54'
title: To Arthur John Butler
wordpress-id: 2402
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Arthur](../persons.html#238)
Arianwen means silver lady.

She was a Welsh saint and the name has never quite died out in Wales, so I suppose the girl has Welsh belongings of some sort.

Arian rhod a silver bow is the rain bow, who scares away spirits of wrath there is a charming bit about her in old Davis’s [Celtic researches](../others.html#49) which nobody believes now.

Alas! [Macmillan](../persons.html#939) took advice about the [School room magazine](../others.html#69) till his heart failed him and he would not try it. I think it is a pity, but those grand people must embark on a large scale if they do it at all.

And war literature has so filled the [Monthly Packet](../others.html#52) that I have never had room for that chapter of [Polly](../books.html#348) all this time.[^1]

yours sincerely

C M Yonge

[^1]: Butler, who was the son of CMY\'s friend the Rev. W. J.

Butler, Vicar of Wantage, shared her enthusiasm for etymology (expressed in her ground-breaking [History of Christian Names](../books.html#48), and collaborated with her on a series of articles in MP on comparative linguistics under the title \'Polyglot Parsing\'.

