---
date: '1871-05-20'
display-date: May 20th [1871?[[footnote:1]]]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Charlotte Mitchell
original-date: '2011-06-06 15:18:45'
title: To Edith Sophia Jacob
wordpress-id: 2410
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Edith](../persons.html#749)
I should not think [Miss Adams](../persons.html#15) could have any objection to your girl. [^2] She has one now whose [father](../persons.html#2270) is [Miss Sturges Bourne](../persons.html#1379)'s bailiff, and her [mother](../persons.html#1820) a ladys maid, the [girl](../persons.html#2269) is refined and more naturally ladylike looking than any of the others, but the sound is not much superior to yours. I am going from home on Monday for a month but it can all be settled with Miss Adams, and I know she has room. I will prepare her before I go.

French comes naturally with her and is not an extra.[^3]
I was thinking of trying to drive over to see you when [Miss Seymour](../persons.html#1308) told me you were at Malvern.[^4] I suppose there is no chance of your being back in July, when [Margaret Roberts](../persons.html#1244) has promised me a visit, and I would try to bring her if she is pretty well. A long drive always seems to me the most perfect way of enjoying a friend, one can talk without the sense of idleness, and with just distraction enough to offer variety if one wants it Indeed I wish, as lookers on and sympathizers can not fail to wish that this serving by standing and waiting were not so very long and weary.[^5] I still very much hope that force of time will bring more power, as it certainly does with many. [Emily Awdry](../persons.html#81) who is the only one of the Moberlys I have seen, says her [father](../persons.html#1015) has felt this like the closing of cares and anxieties for his children, the thing he had cared to live for was the seeing [Selwyn](../persons.html#1026) launched.[^6]
If there be anything to write to me about this negotiation you had better direct here, as I shall be changing about a good deal
your affectionate

C M Yonge

[^1]: The year 1869 added in pencil in another hand, but it seems likely that the letter refers to Selwyn Moberly\'s death on 8 April 1871.

[^2]: Mary Adams (b.1831/2) ran a small boarding school in Otterbourne with her aunt from 1862.

[^3]: As far as this the text has been crossed through in pencil, as if part publication had been contemplated.

[^4]: Miss Seymour was probably Edith Jacob’s first cousin, daughter of Rev.

George Augustus Seymour (1828/9-1909), Rector of Holy Trinity, Winchester, whose wife Elizabeth Noel (d. 1868), was her aunt.

[^5]: John Milton, \'On His Blindness\' 14: \'They also serve who only stand and wait.\' Edith Jacob was a confirmed invalid.

[^6]: The Moberlys\' youngest son Selwyn died in 1871.

