---
date: '1872-01-17'
display-date: Jany 17th 1872
from-address: 'Bray, '
manuscript-location: MS Girton College,  Cambridge Yonge I 2
original-date: '2011-06-14 10:33:25'
title: The Rev. James Edward Austen Leigh to Sir William Heathcote
wordpress-id: 2436
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [William](../persons.html#669)
[I](../persons.html#78) have to thank you for some game which gives me an opportunity of writing to you. I have thought much of your concern for [Lord Carnarvon](../persons.html#2277)’s illness, which must have been great; I felt no little interest in it myself, as he is too good a man to be spared. I was the more alarmed from recollecting how few of his family have lived to be old : now however I trust that he is doing well.

What is your son [Arthur](../persons.html#653) doing? I heard a report that he was abandoning the law, & taking to tuition work..
I have just been just been reading Miss Yonge’s ‘[Daisy Chain](../books.html#24)’, I am not sure whether for the 2d or the 3d time. I wonder where it is ranked in her own estimation. I place it very high amongst her works, & consider it a model specimen of her peculiar powers.

No one else could have written anything like it.

The variety of the characters, the nice discrimination of their shades; the force with which they are drawn, the whole process of their development, strike me as admirable; & in spite of one or two little mistakes (such as making the boys catch crayfish in what must have been a tributary of the Severn, or the Wye, where they do not exist) & make me place it very high, not only amongst her works, but in the general region of fiction.

Like [Walter Scott](../persons.html#1672)’s works & [my own Aunt](../persons.html#76)’s, I am never weary of reading it.

We have had a large family party for some weeks.

All our Sons have been more or less here except [Charles](../persons.html#77), whose residence will begin when Parliament meets: but all are now breaking up. [^2] [Mary](../persons.html#2278) is this morning crossing from Devon for another four month’s residence at Mentone.

She is not ill, but [Dr Quain](../persons.html#1219) urged it as a measure of precaution.

With our affectionate regards to all your party I am very affly yours
J E Austen Leigh

[^1]: The Rev.

James Edward Austen Leigh (1794-1874), nephew and biographer of Jane Austen, had been friends from childhood with Sir William Heathcote, whose mother was a friend of his aunt\'s.

[^2]: He had seven sons.

