---
date: '1872-04-08'
display-date: April 8, 1872
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  301-2
original-date: '2011-06-15 11:57:22'
title: To Sir William Heathcote, Bt.
wordpress-id: 2442
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Sir William](../persons.html#669)
Would you be so kind as to look at page 9 of the 'Gleanings' at the beginning of the [Musings on the Christian Year](../books.html#88), and tell me whether you have any recollection of telling [Mr.

Keble](../persons.html#798) anything about your opinion of [King Charles](../persons.html#1768)'s truth?[^1]
There is a new edition called for, and [Miss Dyson](../persons.html#464) wants me to take it out.

Her letter coming while I was at Salisbury, I asked whether it was there thought that I ought, as it was not according to my impression lightly thrown out, and I put it in because I thought it disproved blind admiration, while showing the real tenderness.
[The Bishop](../persons.html#1015) advised me to ask whether you remembered having said anything of the kind to him - if you did, to leave it; if not, to take it out.

So I am acting by order in troubling you about it.

Your affectionate
C. M.

Yonge

[^1]: The cult of Charles I was very significant to the Tractarians.

In the case of the Hursley group their intense historical consciousness was stimulated by the fact that Richard Cromwell had inhabited the village.

