---
date: '1872-04-23'
display-date: April 23, 1872.
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  302-303.
original-date: '2011-06-15 12:08:03'
title: To Sir William Heathcote, Bt.
wordpress-id: 2444
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Sir William](../persons.html#669)-
I am always bothering you about something, and now I want to ask if you would give me a sentence. I want one describing the remarkable and peculiar merits collectively of the Bench of Judges in the [Patteson](../persons.html#1156) and [Coleridge](../persons.html#344) days.[^1] I cannot well take it out of the mouth of a Coleridge and a judge, and I do not think I can do it rightly myself.[^2] I want to make as full a picture as possible of old Judge Patteson, for he ought to be remembered, and he went for very much in the formation of [his son](../persons.html#1155).

If you would put, as you would in a letter, your view of the high stamp of men who were judges from about 1830 to 1855, it would be what I want expressed. I do not know any one else whom I should like to see doing it but Sir [Roundell Palmer](../persons.html#1129), and I do not know him enough to ask.-

Your affectionate
C. M. YONGE.

[^1]: CRC’s note: This opinion is incorporated in the [Life of Bishop Patteson](../books.html#102).

[^2]: She means she can hardly ask [John Duke Coleridge](../persons.html#343) to praise his father and uncle at the expense of himself and his judicial colleagues.

