---
date: '1872-04-25'
display-date: April 25th 1872
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Royal College of Surgeons, London, Hunter-Baillie collection
  0014/7/244 '
original-date: '2011-06-15 12:15:05'
title: To the Reverend Edward Coleridge
wordpress-id: 2445
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Cousin](../persons.html#332)
Thank you for your note.

The character you give dear [Coley](../persons.html#1155) is I think almost exactly what [Bishop Abraham](../persons.html#4), [in] the papers in [St Luke’s Magazine](../others.html#87), and his own letters, have been helping me to trace, but I am very glad of your confirmation of it.[^2] Can you remember anything about his giving a seal to [Bishop Selwyn](../persons.html#1295) when he came to take leave at Eton before his first going out.

It is spoken of in a letter but neither the Selwyns nor Pattesons can recollect anything about it. I am glad you mentioned the copying.

It is sometimes referred to in his letters but I had not spoken of it.

Any time that it is convenient to you to send the letters I shall be grateful for them, but they will not come into immediate use for a month or six weeks as I have only reached the Oxford period, and I am just now a good deal interrupted.

Perhaps I had better write when I am close upon the need for them, and ask for them. I am very anxious to shew how extensive his mind and interests were.

Your affectionate cousin

C M Yonge

[^1]: Other letters in this collection are addressed to the Rev.

Edward Coleridge; letter 242 is from Max Müller enclosing letters from Bishop Patteson for CMY’s biography; 239 from Sir John Taylor Coleridge, about his own illness; 246 last page of letter from Bishop Patteson, when Selwyn’s chaplain, giving his views on New Zealand politics, especially his disagreement with the Governor.

[^2]: CMY was researching her [biography](../books.html#102) of Bishop Patteson.

Coleridge was Bishop Patteson\'s uncle, and had taught him at Eton, but was also an important British supporter of the Melanesian mission.

