---
date: '1872-11-13'
display-date: Novr 13 th [1872]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2011-06-17 13:52:03'
title: To Christabel Rose Coleridge
wordpress-id: 2461
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
York and Lancaster Rose has gone- one half to school- and the other has grown too busy, so it resigns, and I have accepted a
[Miss Alice Poole](../persons.html#1188)[^1]
Uffington
Farrington
She is sister to [a governess](../persons.html#1187) I like very much –
Hanbury Mills was an immense pleasure to [Gertrude](../persons.html#1462).

She and [Frances](../persons.html#1604) have both bought one. I think Linda is true, but as you say, it was not possible to bring her out more. I confess I had rather not have married Frank I think he got restless and picked his moustaches, and frightened her. I doubt too whether Patty would have come off with such flying colours with old Mr Weatherby
your affectionate
Mother Goose
The lady with a long nose will end in the summer.

Then we will have your Face if it is not too ghastly for a serial

[^1]: \'York and Lancaster Rose\' was the sobriquet of two sisters, members of the [Gosling Society](../others.html#104).

Their replacement, Alice F. S.

Poole (b.

Newland, Gloucestershire 1849/50), was living at Uffington with her mother Catherine Poole (b. 1807/8); she later became a governess and at the time of the 1881 census was living in Camberwell with her sister Harriet Poole (b.

Mansfield, Nottingham 1843/4), also a governess.

The latter is probably the Miss Poole to whom there are several other references.

