---
date: '1872-12-01'
display-date: Decr 23d [1872]
from-address: ''
manuscript-location: MS Mrs Clare Roels
original-date: '2011-06-17 14:25:40'
title: To Christabel Rose Coleridge
wordpress-id: 2465
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
Here is the pay for Minne’s Knight, with many thanks.[^2] I conclude you are at home.

You will see proposals for a monstrous Goose affair in the next packet, but I shall get help in the selection of the essays.[^3] I hope you will do the Snow and Sun next year
Who asks our question next? I should think Hanbury Mills must be a great success, every body seems to like it who has read it I am much afraid the Awdry’s departure will be the ruin of our [lectures](../others.html#240), there seems to be no one to take the same pains about them[^4]
your affectionate

C M Yonge

[^1]: The paper has a decorated motif ‘New Year’s Day With the Season’s Cheer and a Friend’s Regards.\'

[^2]: ‘Minne’s Knight’ was Coleridge\'s contribution to the MP Christmas number of 1872..

[^3]: MP (January 1873) carries on the back an advertisement for [\'COBWEBS OR, THE MONTHLY PACKET ESSAY SOCIETY](../others.html#116).

Two Questions, to be Answered in Writing, on History, Literature, Art or Science, will be proposed in each Number.

Answers to be directed to ARACHNE, CARE OF THE EDITOR OF THE MONTHLY PACKET.\'

[^4]: The Rev.[William Awdry](../persons.html#85) (1842-1910) and his wife since 1868, former Gosling Frances [Emily Moberly](../persons.html#81) (1844-1921) had been the moving spirits in bringing lecturers to Winchester in connection with the movement for the higher education of women.

