---
date: '1872-12-31'
display-date: Decr 31st [1872]
from-address: ''
manuscript-location: 'MS Princeton University, Parrish Collection C0171: Box 29'
original-date: '2011-07-09 07:52:24'
title: To Blanche Catherine Medhurst
wordpress-id: 2467
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Miss Medhurst](../persons.html#988)
Thank you for your kindness to [Emmeline](../persons.html#1358), she is an affectionate girl and has a refinement about her that makes her pleasant to have to do with.

Her [brother](../persons.html#2287) with whom she lives was one of the College choristers at [Winchester](../others.html#50) and had a good education there, so I hope she is in good hands, but a little notice and sympathy will be a great help in the great plunge it must be from daily services to the business of life. I wanted her to have been a school mistress, but though she was a good teacher she did not like it, and it is too much a profession to be taken up experimentally now.

The inspector too advised me not, thinking her too delicate, so Sunday school teaching might be too great a strain, otherwise she would be valuable for it.

She will like to tell you about Hursley which she knows well.

The family are so consumptive that I am always prepared to have her break down
With many thanks

Yours truly

C M Yonge

[^1]: The paper has an ornamental decoration: \'With a Christmas greeting on my tongue/ with a friendship old whose faith keeps young/ I venture friend thy friends among\'.

