---
date: '1872-01-01'
display-date: '[check 1872]'
from-address: '[Tyntesfield]'
manuscript-location: MS location unknown.  This fragment printed in Romanes, [[otherbook:241]<i>Appreciation</i>],
  158 - 9
original-date: '2011-07-11 10:29:50'
title: To Elizabeth Barnett?
wordpress-id: 2468
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[To [Elizabeth Barnett?](../persons.html#113)][J.F.O.](../persons.html#926)[^1] slept here last night to assist at the opening of [Mr.

Randall](../persons.html#1222)'s church at Clifton,[^2] to which we have been this morning.

The Bishop of Salisbury, [Dr.

Moberly](../persons.html#1015), preached most beautifully about the Shadow and the Image. [Mr.

Skinner](../persons.html#1329)[^3] is also here for it. . .

Those who stayed for the luncheon are full of enthusiasm, and say it was most successful, and that the two Bishops spoke in perfection in their several ways; but [Archdeacon Denison](../persons.html#2137)[^4] seems to have almost demolished poor Dr.

Moberly by with the noise he made.

This is a holy and beautiful house to be in, with [Blanche](../persons.html#557)'s almost unearthly goodness and humility, and [her husband](../persons.html#560)'s princely nobleness. . . .

He still reads the lessons in chapel, and with beautiful expression.

Just fancy what it was to hear him read the last chapter of Ecclesiastes, the spirit so rising above the infirmities!

He wants to build a chapel here for the district, also a private chapel, licensed for H[oly]. C[ommunion].

But the [Rector](../persons.html#2289)[^5], a very low and slovenly Churchman, will not consent; though the [Bishop](../persons.html#2288) has been talked to by [our Bishop](../persons.html#1512) and [him of Ely](../persons.html#213)[^6], he will not or cannot abide it.

As to the chapel, there came a letter two days ago, saying ' he would do everything in his power,' but it is much feared that this means only a licence for the Holy Communion, not permitting anyone not in the house to receive.

It is celebrated now in the Oratory, but with a sense that it is irregular and might be stopped when nobody is really ill.

How Mr. [Vaughan] and the Bishop can take advantage of the scrupulous forbearance they meet with, I cannot think.

[^1]: The Rev.

John Fielder Mackarness (1820-1889), bishop of Oxford, who signed his letters J. F. O., was married to CMY\'s cousin Alethea Coleridge. CMY was staying at Tyntesfield, the home of William and Blanche Gibbs, rich and enthusiastic members of the Church Movement.

Both the Gibbses were related to CMY through the Crawley-Boevey family.

[^2]: The Rev.

Richard William Randall (1824-1906), a notorious ritualist, became first vicar of All Saints, Clifton in 1868.

It was designed by G. E.

Street and rebuilt after bombing in the Second World War.

[^3]: The Rev.

James Skinner (1818-1881), founder of the English Church Union and vicar of Newland, Worcs., was author of \'A Plea for the Threatened Ritual of the Church of England\' (1865).

[^4]: The Venerable George Anthony Denison (1805-1896), archdeacon of Taunton, vicar of East Brent, Somerset, and protagonist in a protracted battle in the ecclesiastical courts during 1854- 8 over the doctrine of the Real Presence.

[^5]: The Rector of Wraxall since 1857, the Rev.

Edward Protheroe Vaughan, who owned the presentation of the living.

[^6]: The Bishop of Bath and Wells, in whose diocese Wraxall lay, was an Evangelical, the Hon. and Rt.

Rev.

Lord Arthur Charles Hervey (1808-1894); the Bishop of Ely was the Rt.

Rev.

Edward Harold Browne (1811-1891); and \'our Bishop\' was Samuel Wilberforce (1805-1873), Bishop of Winchester.

