---
date: '1873-07-17'
display-date: July 17th [1873]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e 86. '
original-date: '2011-10-13 10:32:11'
title: To the Reverend John Frewen Moor
wordpress-id: 2476
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Moor](../persons.html#1046)
[Mr Wither](../persons.html#1544) gives £7 a year and finds everything.

What he wants is a girl who has been out before so as to have had her first teaching, and is well to be depended on not to be saucy or lazy with his old housekeeper, who is good natured, and will get up and do things herself instead of making the girl do them.

The place is kitchen maid, as Sophy is housemaid & parlour maid, and she should be a steady girl companionable with Sophy, and if a girl who would find her amusement in reading & working at home it would be better.
I think this is all that signified. I thought I had a girl but turned out too much pledged to another place. I hope yours will do.

It was very pleasant to see how much our old friend is thought of there, and what an improvement he has made

Yours sincerely

C M Yonge

[^1]: Envelope addressed to \'The Revd/ J F Moor/Ampfield Vicarage/ Romsey\' and postmarked Winchester Jy 17/73.

[^2]: The Rev.

William Bigg Wither, formerly curate of Otterbourne, had moved to Hardwick, Buckinghamshire.

