---
date: '1874-03-15'
display-date: March 15th [1874]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54920: 246-7   '
original-date: '2011-07-12 09:18:01'
title: To Alexander Macmillan
wordpress-id: 2494
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939),
This is all very satisfactory, thank you much.

One thing more.

Should not there be a facsimile of the autograph[^1] - I should like a page of that exquisitely neat distinct writing which never altered from the time it formed itself at Eton - and which spreads into sheets upon sheets of mine and yet I never stumble at a word.
I must put in a page with a list of the islands arranged in their groups for reference. I can make one from the Reports.

Most of the islands have two names native and discoverer’s, and a good many three native, English and Spanish - and as everybody is always varying the spelling of the native names one gets distracted
But I will make a list and get the [Bishop of Lichfield](../persons.html#1295) to correct it

Yours sincerely

C M Yonge

[^1]: The letter is about the publication of the [Life of John Coleridge Patteson](../books.html#102).

