---
date: '1874-10-30'
display-date: Oct 30th 1874
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Lady Margaret Hall, Oxford.
original-date: '2011-07-12 14:00:08'
title: To Elizabeth Wordsworth
wordpress-id: 2515
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Elizabeth](../persons.html#1566)
I have been waiting till the wedding was over to write to you and should have done it before post time today but that [Mrs Newland](../persons.html#1083) brought her children to a dancing lesson and came in here. I am afraid you did not get the fine day on SS Simon & Jude though I don’t think it was quite so bad as some. [Gertrude](../persons.html#1462) was very bad the day you mentioned and the one after, and was long in getting back to her usual state again, but I think she is quite well now, she is so sorry to have lost such a piece of your visit Thank you for looking up the Golden Rose, it seems a very odd fancy of Luther to put it in[^1] I think his Hebrew must rather have broken down there.

One would not have thought such a Pascal article would be so much in favour with him that he should go out of his way to bring it in.

You just missed [Miss Roberts](../persons.html#1244), the president of your sister [Dora](../persons.html#862)’s essay society who dropped in a few days after you had gone, after some travels in Switzerland, and brought Gertrude a wonderful assortment of wild flowers dried I wish you could see as I can now, the horse chesnuts [sic] at the bottom of the hill are all brilliant apricot colour and when the green grass is ?searching, and a big purple black cloud behind has a low sun shining on it, it is splendid.

We did much enjoy your visit and should have done so more if that unlucky rheumatiz would have kept off!

Your affectionate

C M Yonge

[^1]: Luther used a rose as his personal seal. A golden rose was offered by the Pope in 1518 to his protector the the Elector Frederick the Wise of Saxony. CMY presumably refers to one or other of these tales.

