---
date: '1874-11-26'
display-date: Novr 26th 1874
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Lady Margaret Hall, Oxford.
original-date: '2011-07-13 09:52:22'
title: To Elizabeth Wordsworth
wordpress-id: 2517
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Elizabeth](../persons.html#1566)
I ought long ago to have written to you though you told me not, I fully meant to have done so, I was so delighted with the book, but we have had a sad time of illness with poor [Gertrude](../persons.html#1462) She got better for a fortnight, and then came all the old troubles, and now she has another abscess under her knee and I do not think will be up for a long time to come.

But I do like your little book greatly, and I think your Lincolnshire people must be very intelligent to have called it out[^1] Have you seen [Miss Bramston](../persons.html#198)’s book, the Carbridges it is very pretty, and puts me in mind of many things.

The eldest daughter has come out so like [Alice Moberly](../persons.html#1025) and the father and mother are so excellently done. I have known people so like them.

We are all snow today and I fear it bodes a hard winter.

Poor [Warden of New College](../persons.html#1404), it seems like a break up, and what a grief to [Mr Coxe](../persons.html#377) it must be.[^2]
Your affectionate

C M Yonge

[^1]: Probably Wordsworth\'s Thoughts for the Chimney Corner (1873).

[^2]: The warden of New College was Edwards Sewell.

Probably CMY is referring to the death of his brother the Rev. [William Sewell](../persons.html#1306) (1804-14 November 1874).

Bodley’s Librarian, the Rev.

Henry Octavius Coxe (1811-1881), was father-in-law to Elizabeth Wordsworth’s brother John.

