---
date: '1875-04-27'
display-date: April 27th 1875
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Girton College Cambridge, Yonge VIII 5
original-date: '2011-07-13 13:06:36'
title: To Isabel Mary Warburton
wordpress-id: 2530
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Warburton](../persons.html#1465)
The Botleigh butter is engaged to Southsea, but at Cranbury whence I have it, they make a great deal on Mondays and Thursdays, and send it to Hailes.[^1] If you like, and will let me know how much a week you want, I will see whether the bailiffs wife can send it direct to you; but it is always liable to fail if there is a large party in the house.
I have read Edward III, and think it excellently told, especially the battle of Poitiers.

But is there not a little slip in making the name of that baby King, son of Louis Hutin Louis.

Surely it was John, for some histories number King John as John II, because of him and I think if he had been Louis, Louis XI would have been Louis XII.

And why is Du Guesclin said to be a peasant I know his delicious memoirs are no great authority, but they would hardly make him of a knightly family if he was not, and there his father has a castle and fights in a tournament
Yours very sincerely

C M Yonge
