---
date: '1875-11-08'
display-date: Novr 8th 1875
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Plymouth and West Devon Area Record Office Ac 1092/29
original-date: '2011-07-14 09:26:22'
title: To Augusta Boevey Pode
wordpress-id: 2538
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Augusta](../persons.html#1180)
I don’t know how it is but there never seems to be room in the [Packet](../others.html#52). I cannot get in my own [Cameos](../books.html#134), nor finish up [the Three Brides](../books.html#120) as I meant to have done by two chapters at a time.

When I began the York & L Rose I thought both it and Dt Cecil would end at Midsummer, and now I find that they will last on into next year.

Then [the new printer](../others.html#173) will not let me put things in type and keep them till I can find a good niche, but only prints just when will make one number so that I do not get my way. I hope as the Winter Story will finish I shall have a little more room after December, but to get in your paper has really been impossible hitherto.

The [Beginnings of Church history](../books.html#119) are the short chapters that I have had in the now collapsed [Monthly Paper](../others.html#81) finished up on to the present time, for there are so many Church histories stopping with the three first centuries.

The [Stories](../books.html#117) are only the old ones like the Xmas Mummers &c reprinted in one volume. [My Young Alcides](../books.html#112) is a sort of Modern story built on the lines of the Labours of Hercules. I have had to finish it up to be a Christmas story and have been so hurried as to have no time for anything else in the way of writing for the last fortnight but I sent off his preface and title page today and must bring up arrears
Ones heart aches to think of Puslinch but I think those times of worry and unhappiness are not constant, and that this probably was the effect of [Duke](../persons.html#1599) being obliged to go instead of choosing a good time as he did in the summer I think the brain always was an excitable one and that anxiety has grown on him with the inability to control it, but one certainly does dread extreme old age. I do not know what day [Miss Finlaison](../persons.html#512)’s break up is to be.

They are all in a state of excitement about a concert which is to come off this week in the girls’ school room, two days of it, between the choir,[ Frances](../persons.html#1604), [Mrs Bateman](../persons.html#784) and the governesses. I wonder whether even to the musical the pleasure or the worry predominates, though to be sure the Managers and performers have all the worry to themselves. [Gertrude](../persons.html#1462) is beginning the winter astonishingly well, and is taking quite a start of strength though I do not suppose she will go out again
I hope [John](../persons.html#1184)’s cold is better and that it will not be the beginning of such a series as you had last winter
your most affectionate

C M Yonge
