---
date: '1876-03-01'
display-date: March 3d 1876
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Bodleian Library, Oxford: MSS. Autogr. MSS. Autogr.  d. 33
  ff 245-6'
original-date: '2011-07-14 11:18:30'
title: To Elizabeth Missing Sewell
wordpress-id: 2546
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Sewell](../persons.html#1301),
There is only one chapter of [Heartsease a conversation](../books.html#45).

It was privately printed twice, and now people are always asking for it, so I am going to put it into the June [Monthly Packet](../others.html#52) though I do not think it is at all worth all the curiosity about it[^1]
The publisher sent me [Miss Owen](../persons.html#1110)’s book just in time for me to answer a person who wrote to enquire whether the chapters were separately published. I will certainly mention it
I am afraid I have no autograph of [bishop Patteson](../persons.html#1155)s that I could cut off, his letters all being closely written there is no cutting one off, and as our correspondence did not begin till he was in New Zealand I have no notes, so that I am unable to find one for you
With my kind regards to [Miss Janetta](../persons.html#1305)

Yours sincerely

C M Yonge

[^1]: This was the additional chapter of [Heartsease](../books.html#19) which explained what happened to the characters.

[^2]: A. C.

Owen, who had contributed articles on \'Christian Art\' to MP in 1874-5, had just published The Arts Schools of Mediæval Christendom edited by John Ruskin (London: Mozley & Smith 1876).

He had commended the volume of MP containing these articles in a lecture later published in his The Pleasures of England (1884). CMY does not seem to have recommended it in MP, however.

