---
date: '1876-05-01'
display-date: May 1st 1876
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Plymouth and West Devon Area Record Office Acc No 308: 1-5-76'
original-date: '2011-07-15 10:40:27'
title: To Mary Yonge
wordpress-id: 2550
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
A great deal seems to have happened since I wrote to you last, but before I tell you about Oxford, I must come to what is uppermost in my mind, about [Julian](../persons.html#1624)’s affairs.

He fully expected a compromise to have been made which would not have brought such difficulty, but that has failed, and there is the whole debt of the company, about £12,000 come upon the 5 directors – of whom some have little or nothing.

Julian was obliged to declare himself a bankrupt.

Every body knows it is only from having become security, and there is every expression of kindness and sympathy from everyone, servants and all, and there is not a debt here, so I do not think he loses in people’s respect but it is a terrible business, and it is lucky that I have something to help him through with, which will save the things in the house from seizure.

Certainly we never dreamt of anything like this coming to any of us, and it seems like a bad dream, so that one wonders to find things going on at all.

There is to be a great meeting of all the creditors in a month’s time, and then I believe it will all be wound up.

His friend, [Mr Jones Bateman](../persons.html#785)[^1] who is a most good man and a lawyer, has comforted us much as to what is likely to happen - The furniture will probably be valued all together, and have to be bought back, and then – if they capture his life income, and make him an allowance, Mr Bateman says the usual way is to dispose of it, according to the table of prices of annuities, and that it will probably be possible to raise money to buy it back for him so I hope it may not turn out so very badly but it certainly is a terrible business, and it will be a great relief when it is over one way or the other.

Things seemed all right a week ago, and I left home without fears, but when I came home on Saturday evening [Gertrude](../persons.html#1462) told me how bad it was.

However we are rather surprised to find ourselves so cheerful in the midst of it.

Julian to going to act as secretary to poor [Sir Thomas Fairbairn](../persons.html#496) who is nearly blind and I hope he will be paid £100 a year for that.

Perhaps some other employment may turn up.

It would be a great relief for him if he could feel himself doing something.

This has made a whole letter, and I had meant to tell you of the beautiful services at Oxford. I was at New College, and the first thing in the early morning, when I went to the 7.30 service I met dear [Mrs Gibbs](../persons.html#557)[^2] at the gate of [Keble college](../others.html#5) with her sweet calm face, and thoughtful eyes – I was to glad to have seen her- The disappointing thing was that nobody could hear either sermon well. I was a great way off and only caught the first words of each sentence but it was a noble thing to see what a work had sprung up in these ten years- The [Warden of Keble](../persons.html#1691) did his part in all the Church services but did not go to the public luncheon, and [Lord Beauchamp](../persons.html#129)’s party was given up.[^3] The warden stood about and talked to people when they came out of church and I shook hands with him.

Oh! what a dreadful thing that was happening to so good a man /as [Lord Lyttelton](../persons.html#913)\!

The day the stone of the Chapel was laid 3 years ago, I had a good deal of talk with him, chiefly on the charity voting matter The speeches were very good at the platform after laying the stone [Mr Gathorne Hardy](../persons.html#620)’s especially so – and [Lord Salisbury](../persons.html#547)’s.[^4] He is so good a man that it is well that the Indian Bishoprics are in his hands.

People were saying that 10 more are to be formed. [Dr Mylne](../persons.html#1076)[^5], the elect of Bombay, looked full of energy.
[Canon Liddon](../persons.html#877)’s sermon lasted two hours and a half, during which I was wedged in tight between two ladies unable to hear anything distinctly![^6] When we came back to New College there were a whole army of guests arrived for dinner.

However some had been at Church so there was time to dress, and I sat between Mr Hardy and the [Rector of Exeter](../persons.html#879).

Then there was a huge soirée, 4000 people in New College Hall, the whole of the grandees of the university to meet Lord Salisbury, but happily that did not last very late, and the next day I went to Wantage, and staid there till Saturday, when I came home to find this strange contrast to my holiday week.
your most affectionate

C M Yonge

[^1]: Rowland Jones Bateman (d.1896), a barrister, was a close friend of Julian Yonge\'s who lived at the Grange, Allbrook and was much involved in parish work in Otterbourne.

[^2]: Matilda Blanche (Crawley) Gibbs (d. 1887), of Tyntesfield, CMY’s second cousin, had financed the building of Keble College Chapel, whose opening on 25 April 1876 CMY had attended.

[^3]: The Warden of Keble College was the Rev.

Edward Stuart Talbot (1844-1934), whose father-in-law, the 4th Lord Lyttelton (1817-1876) had committed suicide in a fit of depression on 19 April.

The 6th Earl Beauchamp (1830-1891) was a prominent Tractarian layman.

[^4]: The other attendees included Gathorne Hardy (1814-1906), conservative politician, later 1st Earl of Cranbrook; and the 3rd Marquess of Salisbury (1830-1903), then Secretary of State for India and subsequently Prime Minister.

[^5]: The Rt.

Rev.

Louis George Mylne (1843-1921), consecrated Bishop of Bombay 1 May 1876.

[^6]: The Rev.

Canon Henry Parry Liddon (1829-1890), a disciple of Pusey famous for his eloquence and the length of his sermons.

