---
date: '1876-06-01'
display-date: June 1st 1876
from-address: Elderfield
manuscript-location: 'MS Plymouth and West Devon Area Record Office Acc No 308:  1-6-76'
original-date: '2011-07-15 11:08:33'
title: To Mary Yonge
wordpress-id: 2554
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I know you will be wishing to know about us, but I am afraid there is nothing very cheering to tell except that I think the worse must have come to the worst.

The five banks that were creditors would not take any compromise though they were offered more than [Julian](../persons.html#1624)’s proper share of the deficit but it seems that by the law each single director can be made responsible for the whole, and though two more are men who can pay, they will have their utmost from him before they go on to the next.

As they cannot touch the property which is in the marriage settlements they capture his income for his life £300 a year.

This the actuary’s calculation makes worth £4000 but everyone says that it will not sell for anything like that, so I hope it will come within my power to purchase it for him and the furniture &c which is valued at £1000.

That would come to about what was offered for the compromise, ie, something between £2000 & 3000.

Happily I can go so far as that, and it is hoped it will be enough.

But they will have only £600 a year to live on instead of £900 then, and they have £200 a year to pay to an insurance office.

Julian is most heartbroken, partly because it makes him lose his commission of the peace unless he is reappointed, and though everyone here is as kind as possible some of these Bank people have tried a worrying and bullying line; we think to work on his friends - whereas there is no one to work on but me, and I cannot go further.

It was hard to have it cast in his teeth that he had ten servants, whereas one was poor old underwitted [John Shepherd](../persons.html#2304), who has had 8 shillings a week for the last 40 years working hard in the garden, and another old[ Harry Mason](../persons.html#1750), who had a small allowance and till a fortnight ago tottered into the garden and sat in a chair to peck up the daisies on the lawn.

Then he had an attack of internal haemorrhage and they say that the large vessels of his heart are affected, and he may die suddenly any moment!

But the kindness & goodness of the people round is great, they all seem to try to shew the same respect. A tradesman at Winchester where they had cashed a cheque, not knowing it would not be honored sent it back, and wished them not to think of it. [Edmund](../persons.html#42) was here on Tuesday but I was out, and did not see him.[^1] There are worse troubles.

Some poor neighbours of ours have lost absolutely all in Turkish bonds.

And the meeting of the choirs on Sunday at beautiful Romsey Abbey missed the clergyman there, [Mr Berthon](../persons.html#144) and then it proved that his youngest daughter had run away to Paris with a man who, they say is married.[^2] The poor girls were motherless, and he is a very clever odd man who I suppose has not attended to them much [Sir Wm Heathcote](../persons.html#669) comes home tomorrow, I have had a very kind letter from him
**[^3] I believe depression of iron trade broke up this mine.

But the times are bad.

They say there are 500 coachmen out of place in London, and 100 fewer carriages in the Parks-
But how lovely the summer is, [Gertrude](../persons.html#1462) had a drive today.

She goes to [her step mother](../persons.html#130)’s for a visit on the 19th, and then [Mary Coleridge](../persons.html#351) comes to me. [Mary](../persons.html#927) and [Eleanor Mackarness](../persons.html#2305) are to be married on the 9th of August[^4] **
I have not liked to write till I knew what course things would take
your very affectionate

C M Yonge

[^1]: Mary’s nephew, the Rev.

Edmund Doidge Anderson Morshead (1849-1912), still a schoolboy at Winchester College.

[^2]: The Rev.

Edward Lyon Berthon (1813-1899) was Vicar of Romsey and inventor of the screw propeller; his wife had died in 1865.

His memoirs do not refer to this episode.

[^3]: The passage between asterisks ** is on a separate sheet and is inserted conjecturally.

[^4]: On 3 August 1876 the daughters of the Bishop of Oxford and his wife Alethea (Coleridge) Mackarness were married at Cuddesdon.

Mary Alethea Mackarness (1851-1940) married her cousin the Hon.

Bernard Coleridge and her sister Eleanor Victoria Mackarness (1855-1936) married the Hon. and Rev.

Randal Parsons (1848-1936). (The MSS certainly says 9 not 3 but the wedding definitely took place on the 3rd (Jackson\'s Oxford Journal, 12 August 1876).

