---
date: '1876-07-27'
display-date: July 27th 1876
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Plymouth and West Devon Area Record Office Acc No 308: 28-7-76'
original-date: '2011-07-15 12:15:03'
title: To Mary Yonge
wordpress-id: 2559
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I hoped to be able to tell you by this time that [Julian](../persons.html#1624) was quite free and had had his discharge but though the money is paid, the forms take a long time owing to the wearisomeness of lawyers however all the real trouble is over now. I do not think it has every been in any but the Hampshire papers which had a kind little paragraph about a Gentleman much respected
Fancy poor [Mr Chamberlayne](../persons.html#282) suddenly becoming unable to speak distinctly.[^2] It is found to be paralysis of the tongue and [Gull](../persons.html#598) who came down yesterday to see him gives little hopes of its not encreasing, so as to prevent him from swallowing. he is about 70, a fair Church goer, and always liberal and kind to the parish in money matters
[Gertrude](../persons.html#1462) comes to Southsea on Saturday, and I am going down to see her on Monday and take her little dog to her as she did not have him at Storrington. [Arthur](../persons.html#1607) came home today, and I hear him playing at cricket in the field. [Frances](../persons.html#1605) will be amused to hear that the [Prevention of Cruelty to Animals Society](../others.html#243) got up a donkey shew.

It was in the park at Broadlands at Romsey, and I went to it with [Caroline Cooke Trench](../persons.html#367).

There were 42 donkeys, all ranged in an oval space, chained round with their heads outwards, and a clear space in the middle, where the gentlefolks might walk about, a stand at one end where [Mrs Cowper Temple](../persons.html#1058) dispensed prizes.

About half were poor people’s donkeys, of whom 4 got the prizes, the first prize being 30/- Mrs Cowper Temple adorned the prize ones with ribbons, and they gave some thing to all the poor people who did not get a prize.

The creatures were beautifully got up, and looked well groomed and handsome.

When the first went up for his prize all the rest brayed a chorus, to the general amusement!

The 2nd prize to a gentleman’s donkey was to a beautiful snowy white one, a lady’s at Hursley. [Sir Wm Heathcote](../persons.html#669) is wonderfully well, and able to do all his usual work, but he is going to Mentone again this winter. I am going to Tyntesfield on the 8th till the 18th.

We have had no rain for more than a fortnight and the harvest looks most beautiful all amber fields. I was at Domum but I never saw [Edmund](../persons.html#42) Where will [Cordelia](../persons.html#1590)’s home be now?[^3]
your most affectionate

C M Yonge
How is Philip Leonard and Honor Weeks?[^4]

[^1]: With envelope addressed to Miss Yonge/ Puslinch/ Yealmpton, postmarked Winchester 28 July 1876 and endorsed ‘Julians Aug 7th-17th CMY if her life is written’.

[^2]: Thomas Chamberlayne (1805-21 October 1876) of Cranbury Park, near Otterbourne, principal landowner in the parish.

[^3]: This is probably a reference to Mary\'s widowed sister-in-law Cordelia Yonge.

[^4]: Unidentified, perhaps poor neighbours of Mary Yonge\'s?

