---
date: '1876-09-12'
display-date: Sept 12th 1876
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS Auckland Central City Library: Special Coll manuscripts RBR
  MS 135.'
original-date: '2011-08-01 15:12:27'
title: To Anna Rachel Bramston
wordpress-id: 2563
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Bramston](../persons.html#195),
I have an urgent appeal sent through the [Freemans](../persons.html#523) of Somerleaze for warm garments for the poor refugee Servians
[Miss Johnstone](../persons.html#775), 10 Ovington Gardens SW is going out again to Herzegovina on that day, and begs for money, serge blankets or any thing warm for the poor creatures
Perhaps you saw the account in the [Cornhill](../others.html#156), 3 months ago[^1] They will not be able to go on coming to that sort of school unless some clothing is sent them.

If you can interest anyone in Manchester will you send the parcel there? I write to you as I think [your sister](../persons.html#198) is away
Have you found a [GFS](../others.html#23) secretary?

Yours sincerely

C M Yonge

[^1]: This article was Mrs Kennard. ‘A lady’s visit to the Herzegovinian insurgents’ Cornhill Magazine, vol 34 (July 1876), 60-73.

Nationalist risings against the Ottoman government in the Balkans led to the Russo-Turkish war of 1877-8. CMY\'s friend Edward Augustus Freeman had been raising money for Balkan refugees since the previous year, and his son-in-law Arthur Evans had publicized in the Manchester Guardian the work of Paulina Irby (1831-1911) and Priscilla Johnston, who had formerly run a school for Christian girls in Sarajevo, and were now working with refugees on the border with Austrian Slavonia: see Dorothy Anderson, \'Paulina Irby (1831-1911)\' ODNB, and Edward Augustus Freeman, \'The Sufferers in Eastern Europe\' The Times (11 October 1876) 7.

