---
date: '1877-08-04'
display-date: 'Aug 4th 1877 '
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS British Library Add MSS 54921: 28-29  '
original-date: '2011-08-04 15:40:52'
title: 'To Alexander Macmillan '
wordpress-id: 2591
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Macmillan](../persons.html#939)
There is something in [Mr Freeman](../persons.html#523)’s essays that he wants me to look at.

Would you be so kind as to let me have them - it is the volume with Charles the Bold in it
I hope the two French histories will come out right at last![^1]
I always suppose some one is making holiday in August so I shall direct this so as to be opened by either you or [Mr Craik](../persons.html#379)

Yours truly

C M Yonge

[^1]: E. A.

Freeman, who was the editor of the \'Historical Course for Schools\' series, was critical of CMY\'s contribution, the volume on the [History of France](../books.html#99).

His essay on \'Charles the Bold\' was published in the second volume of his Historical Essays (1873).

She was also writing another [History of France](../books.html#353) for Macmillan, in the \'Historical Primers\' series edited by J. R.

Green.

