---
date: '1877-05-22'
display-date: 'May 22nd 1877 '
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS Girton College Cambridge, Yonge XV 2 '
original-date: '2011-08-04 15:54:27'
title: 'To Frederick James Furnivall '
wordpress-id: 2593
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Furnivall](../persons.html#531)
You must have my Ns somewhere, for I put them all into their sack and sent them back to you I should think four or five years ago, I know it was just as [a friend](../persons.html#1462) came to live with me, and I had to make room for her possessions[^1]

Yours truly
C.M.

Yonge

[^1]: CMY and her mother had been among the workers recruited by Furnivall to work on the vast [project](../others.html#151) which eventually became the New English Dictionary.

Gertrude Walter came to live with CMY in September 1873.

This letter relates toFurnivall\'s attempts to gather up the material accumulated by the Philological Society when James Murray took over the project for the Oxford University Press.

For the confusion which Furnivall\'s energetic but haphazard methods had produced, see Lynda Mugglestone, Lost for Words: The Hidden History of the Oxford English Dictionary (New Haven, Yale: 2005).

