---
date: '1877-09-29'
display-date: 'Michaelmas Day [29 September] 1877 '
from-address: ''
manuscript-location: 'MS Mrs Katherine Wykes-Sneyd  '
original-date: '2011-08-05 09:27:48'
title: 'From Charlotte Mary Yonge and Christabel Rose Coleridge to Mary Penelope Fursdon
  and the other members of the Gosling Society '
wordpress-id: 2600
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Mother Goose & [the last Gosling of the original brood](../persons.html#329), faithful where few were faithful found having eaten goose together on Michaelmas day solemnly dissolve the ancient [Brood](../others.html#104).

Having begun with 12 intimate friends & cousins who actually did 4 questions once a month it has come to only two once in two months & of those generally only one answered by a few - while there is little acquaintance between many[.] It seems therefore time to break it up, since there are other essay societies in plenty now and Mother Goose still superintends the [Spiders](../others.html#116).

Much that has been amusing & useful has been elicited in these 17 or 18 years & Mother Goose looks back with much pleasure on the intercourse it has produced.

If Goslings will send questions to the Spiders Mother Goose will be very happy to insert them if suitable.

[^1]: Black-edged paper.

In another hand, probably Coleridge\'s.

