---
date: '1877-11-21'
display-date: 'Nov 21st 1877 '
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS Princeton University, Parrish Collection C0171: Box 29 '
original-date: '2011-08-05 11:40:37'
title: To Catherine Barter?
wordpress-id: 2610
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Barter](../persons.html#116),
I should think such a school as [Mr Holland](../persons.html#707) proposes would be a very good and useful thing.[^2] I do not see how I can help about it though I know so few people in London and I do not think there is anything for me to write about Mr Holland further than to wish him success, so I will ask you to do so for me.
I saw [Alice Moberly](../persons.html#1025) last week, when [Mrs Ridding](../persons.html#1238) drove her over.

It is a long time since I have seen Salisbury not since the opening of your nave[^3]
With my love to [your sister](../persons.html#114)

Yours sincerely

C M Yonge

[^1]: The word \'choir\' has been substituted for \'nave\' in pencil.

This would be the choir of Salisbury Cathedral, which reopened after restoration on 6 November 1876 (Bury and Norwich Post 7 November 1876, 2).

It seems probable that the letter is addressed to Catherine Barter, whose brother Henry was married to the sister of Alice Moberly.

The Moberlys father was Bishop of Salisbury.

[^2]: The Rev.

Francis James Holland (1828–1907) opened in 1878 and 1880 the two Anglican day-schools for middle-class girls in London now (2011) known respectively as Francis Holland School, Clarence Gate and Francis Holland School, Graham Terrace.

The ethos of the schools was in contradistinction to those founded by the Girls’ Public Day School Trust, which were non-denominational.

