---
date: '1877-11-24'
display-date: '24 November 1877 '
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS Lady Margaret Hall, Oxford. '
original-date: '2011-08-05 13:58:33'
title: 'To Elizabeth Wordsworth  '
wordpress-id: 2612
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Elizabeth](../persons.html#1566)
I believe (reluctantly) that you are right and that Ebb & Flow is too apposite to the present fashion to bear postponement, I think [Macmillan](../persons.html#939) would take such a story as that, and do well by it, I hope to send it off on Monday.[^1]
[Gertrude](../persons.html#1462) thanks much for the paper about the works She has sent off a parcel today Yes, [M.Guizot](../persons.html#597) gave me that history of France as it came out and having lately achieved binding it, it becomes a most agreeable possession, and Gertrude is diligently reading it through.

The pictures are delightful.[^1] Have you read Uarda – It is very like being in Egypt allowing for a slight tincture of the German scholar.

About the sling – if Frank once began with a solid one, I don’t think he would have taken to the awkwardness of a handkerchief – which is rather a thing extemporized for a day or two’s hurt.

What is that fresh zest of life made of - does it come from inside or outside or both. I fancy the outside ingredient must be something to surmount, and in the inward the spirit to try.

Yours affectionately

C M Yonge

[^1]: CMY wished to publish Wordsworth\'s novel in MP, but could not do so immediately.

[^2]: Perhaps his L’histoire de France depuis les temps les plus reculés jusqu’en 1789, racontée à mes petits-enfants . . . illustré . . d’après les dessins d’A de Neuville, 5 vols (Paris 1870-6).

