---
date: '1877-12-22'
display-date: 'Decr 22nd 1877 '
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: 'MS British Library Add MSS 54921: 42-43  '
original-date: '2011-08-05 14:12:07'
title: 'To George Lillie Craik '
wordpress-id: 2614
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
I have got into a puzzle how to manage with the further [Scripture readings](../books.html#129).

Clay has printed them so slowly that I have only gone on with them when the arrival of proofs has warned me that copy would be wanted.

And now I find that the volume has come to its regular size - about 250 pp in the middle of the Acts - i e when St Paul is at Ephesus on his 3d journey, and the 1st Epistle to the Corinthians has just been worked in, in parts of course
What shall I do. I should think it would take about 100pp to finish up in due proportion to the rest, and I suppose we must make the volume take them in.

In truth the 3d volume ought to have gone to the end of the Old Testament.

Will [‘Story and History of the Moors and Christians’](../books.html#126) in Spain do for the new book -?

Is there any objection to making large extracts from Lockhart’s Spanish ballads, or would it be safer to /ask\ consult [Mr Murray](../persons.html#2312)’s consent.
I translate for myself when I have the original, but I have not in many cases.

Yours truly

C M Yonge

[^1]: Black-edged paper.

