---
date: '1878-04-02'
display-date: April 2nd 1878
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54921 '
original-date: '2011-08-08 12:25:35'
title: To George Lillie Craik
wordpress-id: 2625
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
I am exceedingly puzzled. I am sure I wrote on to the end of the [history of France](../books.html#353), and that [Mr Greene](../persons.html#582) had it and wrote to me that it only came to 86 pp, and that I must make it longer.

What can have become of the latter part?

What did he go upon if he had it not in type to the end?

Besides, I believe I had it in type but the printers must know best. I should have said I was certain I have had and corrected on the other end, but that if the printers have it not, that becomes impossible
I should like to know whether Mr Greene saw the whole of the pages, or only calculated[.] I must supply them of course if they are no where, but I can hardly do so till after Easter[.] I am working hard to finish up [the Story of the Moors](../books.html#126), and then be in London for a few days in the second week after Easter
I suspect that the 2nd part of my Copy must have been lost - or it may have gone to [Clay](../others.html#173) as I did not at first know that [Clowes](../others.html#245) was doing the primer - and Mr Greene must have written from calculation[^2]

Yours truly

C M Yonge

[^1]: Black-edged paper.

[^2]: This relates to the History of France CMY was contributing to Macmillan\'s \'Historical Primers\' series edited by John Richard Green.

