---
date: '1878-10-01'
display-date: October 1, 1878
from-address: Elderfield, Otterbourne, Winchester
manuscript-location: MS Miss Barbara Dennis.  Part facsimile in Dennis, [[otherbook:55]<i>Charlotte
  Yonge</i>] following 45.   Printed in Coleridge, <i>Life</i> 319
original-date: '2011-09-08 11:35:48'
title: To Florence Wilford
wordpress-id: 2644
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Florence](../persons.html#1520)
I am glad you finished your journey prosperously, and I hope you have brought home a store of strength for the winter and for the trials.

How one sometimes wishes that one's people may never have another worry, and yet I suppose it is all right! I have just lost my most good and wise friend [Marianne Dyson](../persons.html#464).

For more than a year she had been in so utterly feeble and broken a state that one could only dread further loss of faculties, and there was a good deal of wearing though not acute suffering, so that it was really thankworthy to know that rest had come on St.

Michael's morning. I have known her 35 years, and she has been a great help and blessing throughout my life.

Scarcely a story of mine but has been read and discussed with her, and I don't know any one I owe so much to after my [Father](../persons.html#1631) and [Mother](../persons.html#1606) and [Mr.

Keble](../persons.html#798). [Anna Bramston](../persons.html#195) was there, being a friend of her companion [Miss Leroy](../persons.html#869). [Mary Bramston](../persons.html#198) spent last evening here, her farewell before going to Truro.[^1] [Gertrude](../persons.html#1462) is better, but cannot walk at all now. I am so glad you are able to 'take up your pen,' as poor people's letters say. I hope the ideas will flow if you do not call them too hard.

Your affectionate
C. M.

Yonge

[^1]: Mary Bramston went to Truro as governess to the daughters of the new Bishop, the Rt.

Rev. [Edward White Benson](../persons.html#140).

