---
date: '1878-10-01'
display-date: Oct 3d [1878]
from-address: Elderfield
manuscript-location: 'MS Princeton University, Parrish Collection C0171: Box 29'
original-date: '2011-09-08 11:49:23'
title: To Mrs Curteis
wordpress-id: 2645
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Curteis](../persons.html#2034)
First I must tell you of what perhaps you have seen in the [Guardian](../others.html#75), my dear [Miss Dyson](../persons.html#464)’s death.

She had been growing feebler and feebler for the last two years and had for months been wholly confined to bed, and unable to read even a letter, though she was constantly read to for the last fortnight she was almost unconscious, and slept herself away.

She leaves a great blank behind her!
I am afraid it is too late to protest against Helen’s babies, except by word of mouth as I have done, for I can’t bear them[^1] But I think they have had their day - and the bad imitation will do more to disgust with them than my protest.

Armine does not by any means die so you need not be afraid for him.[^2] I have him now in the midst of a naughty fit, quite sufficient to save his life.

Thank you so much for your kind thoughts about the game

Yours sincerely

C M Yonge

[^1]: John Habberton Helen\'s Babies (1876), a best-selling work for young people. CMY may perhaps have considered that it treated religion irreverently.

[^2]: Armine is a character in CMY\'s [Magnum Bonum](../books.html#131) (1879), serialized in MP January 1877-December 1879..

