---
date: '1878-10-07'
display-date: Oct 7th 1878
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS University of Kansas P357:1
original-date: '2011-09-08 12:02:27'
title: To Frances Emily Awdry
wordpress-id: 2646
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Emily](../persons.html#81)

Thank you for thinking of [Alice Perrin](../persons.html#1115). I do not quite understand from your letter whether [Mrs Mitchell](../persons.html#2317) is now at Ryde or at Dublin .

If she is near, I should like her to see Alice Perrin.

She is 13, a good steady child, but not equal to [Fanny](../persons.html#1116) in any way, and so very small that I should not like to send her such a distance unseen by her mistress.

Would it be possible to arrange a meeting? I have said nothing about it for fear of disappointment so I am not sure whether her parents would allow her to go to Ireland, though there is more chance in her case, as they have consented to Fanny’s being far off, and the mother is a step

With many thanks

yours truly

C M Yonge
