---
date: '1879-01-29'
display-date: Jany 29th 1879
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54921: 80- 81 '
original-date: '2011-09-08 14:25:48'
title: To Alexander Macmillan
wordpress-id: 2660
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
It is rather difficult to arrange the order of these books.[^2] [Heartsease ](../books.html#19)was out before [the Daisy Chain](../books.html#24) indeed those four that I numbered first were meant to answer to the four Seasons, and ought to go together[^3]
In point of date, the Daisy Chain and [the Young Stepmother ](../books.html#38)are the next, but the Daisy Chain [Trial](../books.html#53) and [Pillars](../books.html#109) ought to come together
What is to be done about the lesser historical ones, [the Prince & Page](../books.html#61), and [Little Duke](../books.html#20) are children’s books but [the Danvers’ Papers](../books.html#63) are not, Would it not be well to pair some lesser ones together?

What is the size and price to be
I have classed historical ones according to date except [Lady Hester](../books.html#110) which would bind with Danvers Papers
Please have a copy of the Daisy Chain & Trial sent to [Mrs Beresford Earle](../persons.html#2319) the Soke, Winchester Also one of [the Three Brides](../books.html#120) sent to [Miss Lewis](../persons.html#873) - 710 Pine St Philadelphia US.

Yours truly

C M Yonge

[^1]: There is a box drawn round the final paragraph and Post Jan 23/79 MC 660/16 written after first and per New York 23/1/79 MC after second.

[^2]: This letter refers to the uniform edition of CMY\'s novels.

[^3]: When the uniform edition was published the first four books were numbered 1.

The Heir of Redclyffe (1853), 2.

Heartsease (1854), 3.

Hopes and Fears (1860) and 4.

Dynevor Terrace (1857).

The model for this intriguing arrangement was undoubtedly La Motte Fouqué, [Die Jahreszeiten](../others.html#102) (1811-14), consisting of Frühlings-Heft: Undine; Sommer-Heft: Die beiden Hauptleute; Herbst-Heft: Aslauga’s Ritter and Alpin und Jucunde; and Winter-Heft: Sintram und seine Gefährten.

