---
date: '1879-02-28'
display-date: Feb 28 th 1879
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2011-09-08 14:53:08'
title: To Christabel Rose Coleridge
wordpress-id: 2663
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
I am sorry to say the 11th is the only day [Mr Wilson](../persons.html#1541) is available that week and that (unless she alters[)], is [MFCK](../persons.html#351)’s day.[^1] How would it be if you came here on Monday 9th I sent you to Rownhams on the 11th, and you then returned to Winchester the same day – either having something to come for you here or being set down at Chandlers ford or Bishopstoke?

Or would you put it off entirely till after May’s visit, which – but for the Humberts, might be the more comfortable way.[^2]
I wish I could see how to manage it better, and it looks inhospitable but I hardly know how else to manage
your affectionate

C M Yonge
Diocesan religious examination
1st class –1
2nd ---	3
3rd		5
no failure

[^1]: On CMY\'s advice, Coleridge was seeking spiritual counsel from the Rev.

Robert Wilson, Vicar of Rownhams, near Southampton.

However, since CMY cannot entertain two visitors simultaneously in addition to Gertrude Walter, Coleridge must wait until Mary Frances Keble Coleridge has finished her visit.

Chandlers Ford and Bishopstoke were both railway stations on the line to Southampton.

[^2]: The family of the Rev. [Lewis Humbert](../persons.html#730) were friends of Coleridges, and perhaps she was visiting them next.

