---
date: '1879-06-05'
display-date: June 5th 1879
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS UCLA: collection 100: box 95'
original-date: '2011-09-09 13:05:20'
title: 'To ?Mary Eliza Bramston '
wordpress-id: 2672
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Bramston](../persons.html#198)
[Mrs Elgie](../persons.html#475) has asked me to answer your note as it is not quite easy to do so. [Miss Finlaison](../persons.html#512) is a very good and excellent person, and very anxious to make the girls good.

She can give them a thorough good foundation in English, French and German, music and some drawing and makes them take interest in what they do. I think a good girl inclined to learn is very happy with her, and I am quite sure she has done much good to some of the girls she has had, and that they were very happy.

She has three now, and very nice girls they are.

She always has a foreign governess—and has sometimes had out a music master, or taken them to Winchester for dancing or drawing.

She feeds them well.

The terms are £80 for one oldish girl, less for a younger one or sisters.

The reasons of difficulty in answering are that when her old mother was alive, and would do the housekeeping, things were apt to be uncomfortable, and though since her death this has been mended, the reputation lasts, and perhaps she is under-servanted, but more scholars would mend that.
[Ethel Luke](../persons.html#2321), a much petted rich girl who was there from 15 to 17 kept on begging to stay fresh quarters so I am sure they must be comfortable.

The other point is that people some times think that the helping at school, and some editing for me takes off time from the girls.[^1] But she takes the younger ones & makes them look over while she teaches the Scripture & catechism at school 3 days in the week—and the time she gives me is while the governess walks with the girls & they have lessons in the afternoon so I don’t think it reasonable.

Some also do not like her appearance & manner, but I know she is a thorough lady in mind—I think I should send a girl there with confidence in all essentials.

Yours sincerely

C M Yonge

[^1]: As well as acting as sub-editor of the MP, Finlaison taught at [Otterbourne School](../others.html#107).

