---
date: '1879-06-13'
display-date: June 13th 1879
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54921: 92 '
original-date: '2011-09-09 13:13:42'
title: To George Lillie Craik
wordpress-id: 2673
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
I hope my sending the corrections on this [pirated](../others.html#172) American copy of the [‘Christians and Moors’](../books.html#126) is not inconvenient; they sent me a dozen, and I preferred sacrificing one to doing so from /with\ my own last copy
The lists at the end must not however be used to print from as the Americans have massed them together with a fine disregard of chronology
I have I hope corrected the careless blunders, It is not possible to alter in accordance with all the new German lights on Spanish history without rewriting the book, and it professes to be half romance.
I see the [Spectator](../others.html#180) is critical as to Arabic names. I do not think the Emir ought to be made Ameer.

In fact though I know no Arabic, I suspect the Spectator cannot be altogether right in all its criticisms Forms of names are so sure to vary that I think it safer to follow the books I take them from when I am ignorant.
[Magnum Bonum](../books.html#131) is quite finished now 43 chapters.

Is it to be two vols at first

Yours truly

C M Yonge
