---
date: '1879-07-04'
display-date: July 4th/1879
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54921: 95-96 '
original-date: '2011-09-09 14:33:28'
title: To Alexander Macmillan
wordpress-id: 2678
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)

Thanks for the copy of the [Heir of Redclyffe](../books.html#15) which is very prettily got up and attractive[^1] I never yet saw an illustrator who would avoid the height of the present fashion

I wonder whether you would think it worth while to publish a little book of stories of mine[^2] chiefly from Christmas numbers of the [Monthly Packet](../others.html#52) four being historical (one not hitherto published) - one modern life, as are also two others which have only been in American papers

Yours sincerely

C M Yonge

Would it be too late to suggest to the illustrator of [Heartsease ](../books.html#19)that in those days the Guards wore no moustaches?[^3]

I should have thanked you for Spenser and Burns, I was sorry not

[^1]: This is a disparaging reference to the illustrations by [Kate Greenaway](../persons.html#2323) in the new collected edition.

[^2]: CMY is proposing the collection of stories republished as [Bye-Words](../books.html#135) (1880).

[^3]: Heartsease was also illustrated by Greenaway.

