---
date: '1870-01-01'
display-date: '[late 1870s]'
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Charlotte Mary Yonge Society/6
original-date: '2011-09-12 10:29:54'
title: To Cyril Hammond Elgie
wordpress-id: 2689
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Cyril](../persons.html#472)
Thank you for your story.[^2] Here is one for you in return.

The Boy who rode on a Saddle of Mutton
There was a little boy who always got whatever he cried for.

One day he was at dinner with his father and mother, there was a large piece of meat in a dish.

He heard them call it a Saddle of mutton. ‘O’ said he ‘I must ride on the saddle’ So he cried and roared till his mother who spoilt him, said ‘Do take him up and let him stand over it’ and his father took him up, with his legs on each side the dish, but he would go plunge down on the mutton.

He broke the dish and all the gravy ran about and there was a dreadful mess.
I am your affectionate

C M Yonge

[^1]: Cyril Hammond Elgie (1871-1917) was the eldest son of the Rev.

Walter Elgie, curate and then Vicar of Otterbourne.

His mother wrote in Coleridge, [Life](../others.html#40), 264: \'Children were not afraid of her, as many grown-up people were; my own children were perfectly at their ease with her, and one adventurous spirit used to write stories (very ill-spelt) and send them to Miss Yonge, when an unfailing reply came, generally the same evening, telling some other story in return.\'

