---
date: '1870-06-08'
display-date: June 8th [1870]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Princeton University, Parrish Collection, CO171: Box 29 '
original-date: '2011-09-12 11:18:45'
title: To Sarah Anne Mercier
wordpress-id: 2694
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Mercier](../persons.html#990)
Here is that charming little story at last.

One thing might I ask?

Could not poor Maria’s one note of admiration be changed from Lor! I have rather the feeling that it is an abridgement of a more sacred word.[^1]
Did you mean Marian to blunder about feeding cows and milking chickens - ?

Also did you send me a capital paper about fashion?

Yours sincerely

C M Yonge

[^1]: ‘Hints on Reading’ MP (April 1871), 418, recommends ‘Mr.

Warne’s last Victoria Packet, where . . .

Mrs.Filby’s Maria rises far above the general order of such little books’.

However, since this letter evidently encloses a proof for correction, it presumably dates from the previous year.

Several series of [‘Warne’s Victoria Toy Books: A Packet of Twelve Nursery Stories’ ](../books.html#211)were published.

Since they appeared under CMY\'s editorship and several were anonymous, they are sometimes incorrectly catalogued as her work.

