---
date: '1880-10-15'
display-date: Oct 15 1880
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Girton College Cambridge, Yonge VIII  '
original-date: '2011-09-14 10:43:01'
title: To the Reverend William Parsons Warburton
wordpress-id: 2713
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Warburton](../persons.html#1466)
I am afraid that when I think of myself as teaching Standards V and VI I feel your first sections somewhat alarming - though perhaps they are not harder than some of the extracts in the advanced Readers and my country children may be no fair criterion
I do not think that the narrative part is so difficult, but in the generalising.

What makes it delightful reading to us - the allusions, and allusive forms of expression would be great stumbling blocks - e.g.

What would they make of Sitting Bull and Flying cloud - who by the by would surely burn wigwams rather than kraals This is very impertinent but you see you have set me on, and I am figuring to my self working at it with the best scholars I ever had!

After the first section I do not see than it is beyond a wholesome stretch to the mind except for a few ideas that belong to a degree of cultivation one can not expect. I really think it is chiefly in the first section that the difficulty lies, and that alarms the reader - it would be a great pity to recast the ensuing chapters, and spoil their flow, - and I hope the Sanctuary will not insist on such a change[^1] - would not it look easier if the paragraphs were more divided. I think in the end of Sect II, the allusion to Upper and Lower Canada and Egypt would confuse a 12 year old intellect more than elucidate matters
I am afraid this is what be called a candid opinion, but I wish the history was not hampered with the consideration of the children, and that I could be free to enjoy it as it is
Do you happen to have by you Andrew Marvell’s few lines on Charles I’s death I can only remember the first and last.[^2]
The poetry in this 4th standard vol is a great difficulty everything spirited is naturally so strong one way or the other as not to suit the needful neutrality

Yours sincerely

C M Yonge

[^1]: The offices of the publisher, the [National Society for the Education of Children in the Principles of the Established Church](../others.html#32), were in the Sanctuary, Westminster.

The history textbook which Warburton was working on has not been identified.

[^2]: Andrew Marvell, ‘An Horatian Ode upon Cromwell’s return from Ireland’, ll. 57-60. \'He nothing common did or mean/ Upon that memorable scene:/ But with his keener eye/ The axe\'s edge did try:/ Nor called the gods with vulgar spite/ To vindicate his helpless right,/ But bowed his comely head,/ Down as upon a bed.\' It was included in CMY\'s [English History Reading Books](../books.html#150) IV, 117.

