---
date: '1881-03-12'
display-date: March 12  [1881]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Westcountry Studies Library, Exeter/  Yonge 1881/1
original-date: '2011-09-14 15:24:15'
title: To Ann Maria Carter Smith
wordpress-id: 2720
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
It is very pleasant to hear from you again. I think I shall read your paper to [our mothers](../others.html#31) next Friday as part of it.

We only began last winter- [our clergyman’s wife](../persons.html#475) to do the executive and I to read to them Alas! this spring we have had the terrible and unexpected loss of [our good Vicar](../persons.html#478).[^1] He was only 42, and in full work, when struck down by a chill ending in typhoid fever- and from the first, he was never sensible.

So I am keeping the thing together as best I can, and I expect a young bride will have to begin
It strikes me that your opening is written to a more ignorant set than I am used to, and I think I shall leave that out and go on to the part about the Queen.

Our most regular members are three sisters who have borrowed books the last 30 years and have the perplexing faculty of never forgetting a story they have once read! I wish you could feel moved to write anything again like ‘Georgie’s Christmas holidays'.

But I feel sure stories are given to one, in a measure as [Frances Havergal](../persons.html#2091) felt that her poetry was[^2]

yours sincerely

C M Yonge

[^1]: The Rev.

Walter Francis Elgie (1837- February 1881), Vicar of Otterbourne.

[^2]: Frances Ridley Havergal (1836-1879), prolific hymn writer. CMY had no doubt recently read M. V. G.

Havergal, Memorials of Frances Ridley Havergal (1880).

