---
date: '1881-01-01'
display-date: '[spring 1881]'
from-address: ''
manuscript-location: MS Charlotte Mary Yonge Society/8
original-date: '2011-09-14 15:44:20'
title: To Catharine Elgie
wordpress-id: 2721
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Elgie](../persons.html#475)

Thank you for this precious little bit.[^1] If you are parting with the books or any of them, I should very much like if you would let me buy the Wordsworth and the Lightfoot’s comments on the New Testament.[^2]

I think I remember the sermon that was founded on these notes.

I have done the deed with Davis. I hope he has places

yours affectionately

C M Yonge

[^1]: The Rev.

Walter Elgie, Vicar of Otterbourne, had died on 25 February 1881 and CMY here thanks for an autograph given to her in his memory.

[^2]: The Lightfoot referred to here might be the Rt.

Rev.

Joseph Barber Lightfoot, Bishop of Durham, who published commentaries on the Epistles, or CMY may refer to John Lightfoot, The Harmony of the Foure Evangelists, among themselves, and with the Old Testament (London: White 1644).

