---
date: '1881-04-01'
display-date: April 2d 1881
from-address: 'Elderfield, Otterbourne, Winchester. '
manuscript-location: MS Princeton University, Parrish Collection.
original-date: '2011-09-14 15:48:11'
title: To Eliza Callahan Cleveland
wordpress-id: 2722
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Cleveland](../persons.html#307)

Thank you much for sending me the answer to that question.

Do you remember sending me the two volumes of the Harvard biographies, James Lowells’ was the one I liked above all others, there seemed to be such depth and originality in his whole character.

I have lent the book to several persons chiefly on his account

I remember that pleasant visit well.

Pray assure friend that our little Scamp is in full health and beauty, and I hope a little better behaved.

I have not seen [  Miss Sewell](../persons.html#1301) for a good while, but I hear from her often and she seems as busy as ever upon her plans for education being made as wide as it is universal.

Have you seen the life of sister Augustine?

Kegan Paul publishes it[^1] She was too true a Catholic to accept the dogma of Infallibility, and therefore had to die excommunicate

Yours sincerely

C M Yonge

[^1]: Sister Augustine, Superior of the Sisters of Charity at the St.

Johannis Hospital at Bonn (London: Kegan Paul 1880) was an authorized translation, by Emily Augusta, Lady Durand, of Henri Lecoultre’s German biography of Amalie von Lasaulx (1815-1872).

The doctrine of papal infallibility had been affirmed by the Vatican Council of 1869-70.

