---
date: '1882-03-27'
display-date: March 27th 1882
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Bodleian Library, Oxford: Ms. Eng. lett. e.100 ff161-2'
original-date: '2011-09-16 12:46:25'
title: To Percy Harris
wordpress-id: 2745
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Percy](../persons.html#631)
The houses I should prefer for a boy are
the Revd [J H DuBoulay](../persons.html#446)’s
Southgate Hill	or
the Revd[ J T Bramston](../persons.html#196)’s
Culvers’ Close[^2]
I have a weakness for a clergyman’s house, and besides, I think so highly of both the men and their wives - [Mrs DuBoulay](../persons.html#2343) as I daresay you know was Alice Cornish sister to the [Bishop of Madagascar](../persons.html#2344).

Both she and [Mrs Bramston](../persons.html#2303) are very nice about the boys.

Mrs Bramston’s father is [Archdeacon Adey](../persons.html#2342) he /Mr B\ is [the Dean](../persons.html#197)’s son. I should certainly try to get [George](../persons.html#2340) into one of their houses, though of course it must be a chance.

Preference has really so little to do with it that I do not suppose it would be of any use for me to say anything.

They had not, when I last heard, discovered anything in [Mr Fearon](../persons.html#502)s house to account for the illness, but I think there must have been, as three boys were ill, the butler died, and the doctor who attended them like wise.[^3] I suppose it will be thoroughly investigated when Mr Fearon leaves it. I hope George may get in to College, and that we may be able to meet when you come with him at Election . I think you are quite right in deciding against Harrow

Yours affectionately

C M Yonge

[^1]: Percy (Primrose) Harris (b. !839/40), the widow of CMY\'s cousin the Rev.

George Collyer Harris (1833-1874), Vicar of St.

Luke\'s Torquay, was evidently proposing to send her son George Newton Harris (b. 1868/9) to [Winchester College](../others.html#50).

[^2]: If he does not get an academic scholarship (‘into College’) he must board with one of the housemasters.

[^3]: The Rev.

William Andrewes Fearon, subsequently (1884-1901), headmaster of Winchester College.

