---
date: '1882-05-04'
display-date: May 4th [1882?][[footnote:2]]
from-address: "Elderfield Otterbourne\tWinchester"
manuscript-location: 'UCLA: collection 100: box 95'
original-date: '2011-09-16 13:05:54'
title: To Horatia Katharine Frances Gatty
wordpress-id: 2747
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Gatty](../persons.html#469),
The Signora [Linda Villari](../persons.html#1444) wife to [Professor Villari](../persons.html#2345) at Florence sent me this pretty little sketch of a real favourite bird.

It is too youthful for the [Packet](../others.html#52), but I think you will like to open a connection with her, as she writes prettily and freshly. I enclose a card she sent with her address.

She wrote a very pretty story once for the Packet called the Angel of Viareggio.
I hope you can give a tolerable account of [Mrs Ewing](../persons.html#494).

We were greatly charmed with Laetus Sorte Meâ[^3]

Yours sincerely

C M Yonge
On second thought I will keep the card as if rejected you had better return Dinderino to me

[^1]: Endorsed in another hand \' Signora Linda Villari/ 93r Via Tinti/ Florence/ “Dinderino”\'

[^2]: ‘The Angel of Viareggio’ appeared in MP (January-June 1880) and ‘Laetus Sorte Mea’ in Aunt Judy’s Magazine in 1882.

It was published as The Story of a Short Life (1882).

The letter must antedate the death of Juliana Ewing in May 1885.

