---
date: '1882-06-07'
display-date: June 7th 1882
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2011-09-16 15:42:28'
title: To Margaret Wilcox
wordpress-id: 2751
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Margaret](../persons.html#1517)
So many thanks for sending me [Miss Smedley](../persons.html#2346).[^1] I had a good deal of her in the [Readers](../books.html#150), but I shall borrow more now.[^2] I wish her verses had been more known but I think they will grow into part of the common stock of knowledge of poetry in our youth. I sincerely rejoice at [your brother](../persons.html#2348)’s appointment not only is it good for him, but what a load it takes from your shoulders which are used indeed to bearing family burthens.[^3] I filled in the address of your letter and I hope Canon Bright’s poems arrived all right
[Mrs Langton Clarke](../persons.html#301)’s death is a terrible blow[^4] There was something so bright and charming about her, which left a long impression though I have seen so little of her. I should think it must greatly dim the brightness of Whitburn for years to come though there will be every help that kindness can give, but poor [Mr Clarke](../persons.html#2347) with his weak health has so depended upon her that I cant [sic] think how he will every hold up his head

Yours affectionately
C.M.

Yonge

[^1]: Menella Bute Smedley, Lays and Ballads from English History (1850).

[^2]: Between 1881 and 1888 CMY edited a series of history readers, [English History Reading Books](../books.html#150) (1881-1883).

At the time of this letter she was also working on another textbook for the National Society, [Historical Ballads](../books.html#156) (1882).

[^3]: Of her several brothers the one most likely to be referred to here was the much younger Ernest Shepley Wilcox, who was a widowed civil engineer living with her and his children in the 1881 census, but had remarried by 1891.

[^4]: Frances Mary Clarke (1835/6-1882), the wife of the Rev.

James Langton Clarke (b.1833/4), curate of Whitburn, was born at Whitburn, and was perhaps related to CMY’s friends Thomas and Sophia (Collinson) Harrison, friends and neighbours of Margaret Wilcox.

