---
date: '1882-12-09'
display-date: Decr 9th 1882
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS  Pembroke College Oxford 60/14/97
original-date: '2011-09-19 13:02:23'
title: To the Reverend Bartholomew Price
wordpress-id: 2762
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Price](../persons.html#1208)
Mr [Walter Smith](../persons.html#1344) took the [Mozleys](../others.html#108)’ business when [John Mozley](../persons.html#1065) died and [Charles](../persons.html#1063) retired.

He was trained at [Macmillans](../others.html#111) and I think he knows his profession (or what ever it is to be called) thoroughly.[^1] He is a gentleman and pleasant to deal with in all ways. I do not know [the present Parker](../persons.html#2349), as my dealings were with [his father](../persons.html#1142), but I prefer Mr Smith greatly to J H P.

He is very straightforward and lets one understand what he is about, and I should call him rather cautious than enterprising.

He has had to feel his way a good deal, for old John Mozley had attended to nothing for years, and a foreman they took into partnership immediately went mad, and upset the arrangements- and they had to go on paying him as partner after he was in an asylum, till the firm could be dissolved.

So poor Mr Smith has had a great deal against him but I think he has done well, and I am quite sure you may have full confidence in his honourable dealing.

He is a very good Churchman, and would think the work a great honor I think it would be the making of him so that I hope you will see your way to giving the publication to him.
[Julian](../persons.html#1624) is getting through the winter well among his birds and his china painting.

With kindest regards to Mrs Price

yours sincerely

C M Yonge

[^1]: As well as being Sedleian Professor of Natural Philosophy Price was secretary to the delegates of the Oxford University Press 1873-84, and his enquiry about Smith seems to have been about employing him in this capacity.

