---
date: '1883-01-01'
display-date: Jany 23d 1883
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS British Library Add MSS 54921: 121-2: '
original-date: '2011-09-19 15:56:44'
title: To George Lillie Craik
wordpress-id: 2768
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
Many thanks for the [payment](../others.html#160).

The knowledge that the amount for [Unknown to History](../books.html#157) is coming is quite sufficient for me at present. I have been kept waiting about the [Christian Names](../books.html#48) by [Mr H Jenner](../persons.html#760) of the British Museum who promised to set me right about the Keltic mythology but I suspect has forgotten all about it.[^1] I am desiring him to let me have it again, and let me do my best with it. I think it is compressible into a volume. I took out an immense quantity of the First.
[Clark](../others.html#251) made no sign though no doubt there was a stamp with his name. I was surprised at the uniform obliteration of my capitals which I thought I had taught [Clay](../others.html#173) to observe. I observe printers have an inveterate hatred to capitals, even when they have only to copy type. I suppose it gives them more trouble - or they lay snares for corrections[^2]

Yours truly

C M Yonge

[^1]: The Cornish scholar Henry Jenner (1848-1934), was an assistant in the MS department of the British Museum, the son of Bishop Jenner and the nephew of Marion Finlaison.

[^2]: CMY waged constant war with printers. R & R.

Clark of Edinburgh, and not Richard Clay and Sons, were the printers of the first edition of Stray Pearls; evidently CMY had not observed this in correcting the proofs.

