---
date: '1883-12-01'
display-date: Decr 1st [or 14?] [1883]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: MS Mrs Clare Roels
original-date: '2011-09-21 14:49:00'
title: To Christabel Rose Coleridge
wordpress-id: 2782
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
Things change a good deal.- Before [John](../persons.html#343) went to America, he altered his will so as to make [her](../persons.html#17) tolerably dependent on [Bernard](../persons.html#2143), hoping thus to put a stop to it all and thinking it would keep the man on his good behaviour.[^1] Since that he offered £300 for her life if before June, [Mr Adams](../persons.html#12) found employment so as to secure a reasonable even if small income, £400 if she would live with one of her own friends but this was rejected.

On Sunday poor [May](../persons.html#351) wrote to me in despair saying she was gone to stay with [Miss Blatchford](../persons.html#2355), it is said to be for a fortnight, but they don’t know what is meant to be the result.

It is a strange matter altogether-! I got, about a fortnight ago- a sheet of [the Miz Maze](../books.html#165) that had not had Press written upon it, with ‘Please Pass’ which I did, so I suppose they are finishing off. I have had one other list of names sent in, but I don’t think there has been time enough to know whether [Carlyle](../persons.html#1972) is world famous.[^2] Do pray read Thring’s 'Theory and Practice of teaching.’ It is the nicest book I have read for a long time.

He says Genius is ‘infinite capacity for work, and infinite capacity for love’ the love giving power to reach the Spirit of what it observes
We had a fund evening at the Guildhall of Tableaux from Winchester history & legend- Queen Emma & the ploughshares.

Such ploughshares with lamps inside. I am sorry for the man’s companion[^3] I expect something will rise in its stead I feel [Florence](../persons.html#1520) is very bad[^4] I don’t know what to advise about dog homes
your affte

C M Yonge

[^1]: John Duke, 1st Lord Coleridge (1820-1894), was trying unsuccessfully to stop his daughter Mildred (1847-1929) from marrying Charles Warren Adams (1833-1903).

Bernard was his eldest son (1851-1927).

This affair, which was played out in a blaze of publicity, including a libel action, is discussed by Julia Courtney, in ‘Charlotte M.

Yonge: A Novelist and her Readers’, unpublished PhD thesis, University of London, 1990.

Adams accused Bernard Coleridge of libelling him by saying that he ‘ran away with a girl under age and that he led her an unhappy life after their marriage’; the case was reported in The Times (24 November 1884) 3e and commented on in a leader in the same issue, page 9e.

The first Mrs Adams, whom he had married in 1861, had been [Georgina Alethe Polson](../persons.html#13) (b.1838), daughter of CMY’s first cousin [Georgiana (Crawley) Polson](../persons.html#1194) and granddaughter of her godmother and aunt [Charlotte (Yonge) Crawley](../persons.html#777), later Jones.

[^2]: \'Name thirty world-famous authors (not living).\' was one of the Spider Questions in MP (December 1883); the best answer was printed in MP (February 1884), 193.

[^3]: This sounds like a periodical, but has not been identified.

[^4]: Florence Wilford was mentally ill with depression.

