---
date: '1885-09-02'
display-date: '[September 1885?][[footnote:2]]'
from-address: ''
manuscript-location: MS Girton College Cambridge, Yonge IX 4
original-date: '2011-09-27 14:03:55'
title: To an Unknown Person
wordpress-id: 2812
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

. . .

August and very dreary it was to see the beautiful rooms at Heaths Court with no mistress. I still believe that there will be a great awakening from the present blindness, and [Mary](../persons.html#351) . . .
I think Winchester is a rock that binds its limpets fast - not a good simile either for the limpets do go off, only perhaps it is their affections that stay there. I have not near so much to care about there now, as in old times, only perhaps the dear Salisbury people may come back there.[^3] I believe the elders wish it, but the younger feel more present interest where they are.
I am very sorry you are lame - but I dare say you have plenty of work to do from your sofa. I wish you could see our woods the autumn tints are wonderful this year - and the Virginian creepers are gorgeous
Yours very sincerely

C M Yonge

[^1]: The top of the first page is cut away, probably because of some reference to the Coleridge scandal, and what is left of he first side crossed out.

[^2]: The letter seems to be connected to [Mildred Coleridge](../persons.html#17)\'s marriage on 24 June 1885 and [George Moberly](../persons.html#1015)\'s death on 6 July 1885.

[^3]: The widow and daughters of George Moberly, headmaster of Winchester College 1835-1866, and Bishop of Salisbury from 1869.

