---
date: '1885-10-15'
display-date: Oct 15th [1885?]
from-address: Elderfield Otterbourne Winchester
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2011-09-28 11:26:17'
title: To Elizabeth Rundle Charles
wordpress-id: 2817
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mrs Charles](../persons.html#287)
Thank you most heartily for the book you have been so kind as to send me.

Such lives as those always remind me of that saying of Sir [Walter Scott](../persons.html#1672) that [Mrs Hemans](../persons.html#1936) preserved - ‘Do not say that noble blood is wasted, it sends down a roaring voice through all time’[^1]
May it lead to fresh worthy deeds -

Yours sincerely

C M Yonge

[^1]: Elizabeth Rundle (1828-1896) married Andrew Charles in 1851 and published historical fiction as Mrs Rundle Charles.

The book referred to in this letter was probably herThree Martyrs of the Nineteenth Century: Studies from the Lives of Livingstone, Gordon, and Patteson (London: SPCK 1885). CMY was fond of quoting [Walter Scott](../persons.html#1672)\'s statement, recorded by Felicia Hemans: \'Do not say that noble blood is wasted, it sends down a roaring voice through all time’.

The quotation occurs The Daisy Chain II, Ch.5, the source being, Harriet Browne, Memoir of the Life and Writings of Mrs.

Hemans, 200.

