---
date: '1886-02-26'
display-date: February 26 [1886]
from-address: 85, Lexham Gardens, Kensington, W
manuscript-location: MS NLS 9752
original-date: '2011-09-28 14:52:06'
title: Mary Louisa Molesworth to Charlotte Mary Yonge
wordpress-id: 2826
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Miss Yonge
I had the proofs of ‘One Sunday Morning’ some time ago & corrected them carefully.

There were several small errors - in themselves small but rather important as affecting the sense, but I daresay the printers will have made all right. I want to know if I may send you another short article I have by me just now.

It is not original, being a free translation from the French of Madame de Pressensé; the original appeared recently in a French serial not known in England.

It was beautifully written in French & I don't think it reads like a translation in English.

It is the history of a sort of French ‘city arab’, and I think it cd. be rather new to English readers.

Madame de Pressensé gave me leave to do what I liked with my translation, but I should like it to appear before very long, for her sake.

The French title is ‘Le Parigot’, I have called it ‘Felix, an outcast’.

Shall I send it to you? I think it cd. easily divide into two parts if too long for one.

My friend [Mr.

Craik](../persons.html#379) told me the other day that you had asked him if I was the Mrs.

Molesworth who had written ‘Carrots’ &c.

Perhaps I shd. have mentioned this to you when I wrote first, but there is no other woman of the name who writes, so I did not think of it.

And in one sense it makes me all the more pleased that you like my sketch, without knowing me.

Believe me
yours very truly
[Louisa Molesworth](../persons.html#1028)
I have stupidly mislaid your address.

Will you kindly let me have a word in reply as soon as you can.
