---
date: '1886-05-16'
display-date: May 16th [1886]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 140-1'
original-date: '2011-09-28 17:27:01'
title: To George Lillie Craik
wordpress-id: 2828
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear[ Mr Craik](../persons.html#379)
I have been asked so urgently that I hardly know how to refuse, by a person who knows a good deal of the popular mind at Liverpool (being on the Committee of those Recreation classes, and doing much besides) to write [a popular account of the fifty years of the reign](../books.html#189), to be dispersed in preparation for the Jubilee Year.

She says it ought to cost only sixpence, to be like a succession of stories and profusely illustrated.

What do you think about it? I rather doubt its being enough in your line for you to like to make it as cheap as it must necessarily be to fulfil its purpose? I should try to make it entertaining rather than connected, and keep out of party politics and personalities.

If you did not wish to take it up, I would try what [Cassell ](../others.html#216)would say to it, but I would much rather work for you.

Yours truly

C M Yonge
