---
date: '1886-05-21'
display-date: May 21st [1886]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 142-4: '
original-date: '2011-09-28 17:40:01'
title: To George Lillie Craik
wordpress-id: 2829
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
Thank you for your kind letter, I do see great advantages in the plan - but I confess I think it not possible to have [such a book](../books.html#189) well and originally illustrated at such a price in any other way.

The doubt in my mind is whether the book would not - (to fulfil its purpose) have to be too common place in its facts to be on a level with the [E. I. M.](../others.html#68) They would mostly have to come out of Sir T Martin and the Greville memoirs. I should be glad to be free from trying at Jubilee events especially Egyptian ones, which I don’t understand, and only mentioning any thing I wished, such as the Irish famine, the Crimean war, or Indian Mutiny, which could be touched on more or less as they affected the Queen.
I want to make the language as simple as I can without absolutely writing down which affronts people especially of the class I wish to reach.

Please let me know whether this would suit [Mr Carr](../persons.html#2364)’s views.[^1] I think I will send the accession chapter all I have yet attempted as what will best give an idea of the style I had thought of
The genealogy story is in Caroline Fox’s memoirs rather differently from this, but I have seen the pedigree on which the discovery was made. [Dr Davys](../persons.html#411)' [daughter](../persons.html#57) has it.[^2]
As for the amount for the number, perhaps we had better settle that when we see how much there is of it, and how it answers

Yours truly

C M Yonge

[^1]: Joseph Comyns Carr (1849-1916), the editor of the English Illustrated Magazine 1883-6, in which Craik had proposed serializing the book which was to become CMY\'s Victorian Half-Century.

[^2]: This pedigree story is also referred to in a letter to Christabel Coleridge (6 June 1882).

