---
date: '1886-05-28'
display-date: May 28th [1886]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 145-6: '
original-date: '2011-09-28 17:46:40'
title: To George Lillie Craik
wordpress-id: 2830
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
You will think there is no end to me, but it may save more letters if you get this before seeing [Mr Carr](../persons.html#2364).
1st - Could some copies be put in boards for prizes for the Board Schools at Liverpool. I suppose they could tell how many, and others might like them[^1]
2d - .

If I could have a list of convenient illustrations I could make them salient points
3d - As to length, I will go on so as to unfold the history naturally, and if there is too much cut down afterwards.
4th I believe the Liverpool people would like it before February; but even if I finish my part quickly, I suppose the illustrations must take time.

Now another subject
I have finished writing a story about the length of [the Little Duke](../books.html#20), 14 chapters of which about half have come out in the [Monthly Packet](../others.html#52).

It is to finish at Christmas [The Modern Quest of Ulysses](../books.html#185) is the title, and it is about a Moorish capture of an Irish and Scotch Jacobite family (naturalised in France) in 1718 A good deal of it is true and there is material for pretty illustrations
Would it be well to set it going, though I do not want it to come out till December, so as not to precede the end in the Packet?

Lastly - may I ask for [Mrs Craik’](../persons.html#378)s edition of Old Fairy Tales? I have been recommending the right old ones in the [library guide](../books.html#196) I spoke of and I want to see which these are.

Yours truly

C M Yonge

[^1]: This relates to the publication of CMY\'s [Victorian Half-Century](../books.html#189) (1886), which Craik was considering serializing in the English Illustrated Magazine, edited by Joseph Comyns Carr.

