---
date: '1886-06-09'
display-date: June 9th [1886]
from-address: 'Elderfield '
manuscript-location: 'MS British Library Add MSS 54921: 147-8'
original-date: '2011-09-29 09:45:08'
title: To George Lillie Craik
wordpress-id: 2833
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
The printer can judge better than I but I do not think there is enough of [the Quest of Ulysses](../books.html#185) to make more than such a volume as [the Little Duke](../books.html#20), so I think it had better belong to that Series.

Thank you for Lord Albemarles’ memoirs. I was waiting to do so till I saw what [Mudie](../others.html#137) sent me, and his box is either delayed or lost, as I have just discovered.
I will not close this letter till I hear the result of the enquiry I have sent to make at the Parcels’ Office.

If I do not get the books today, I think I must ask you to let me have the Queens Journals the Greville Memoirs Princess Alice, and Lady Blomfield, in all of which I know there are characteristic bits.[^1] I have just down the year of revolutions, but I cannot finish off the beginning without more authorities.

The Annals are very useful.

Unluckily this copy has Sheet M twice over, and no sheet N but I do not think there is anything very important in the missing one[^2]

Yours truly

C M Yonge		
Perhaps I ought to see Madame Bunsen’s memoirs
No books come - so if you would kindly get them for me

[^1]: These books were all wanted for CMY\'s work on [Victorian Half-Century](../books.html#189).

[^2]: Craik had presumably provided her with the most recent (1880) edition of Joseph Irving, The Annals of our Time.

