---
date: '1886-06-14'
display-date: June 14th [1886]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 149-50: '
original-date: '2011-09-29 09:54:51'
title: To George Lillie Craik
wordpress-id: 2834
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
[Mudie](../others.html#137)’s books have come at last, after spending ten days on the road.

Greville is there.

And the Queen’s Journals.[^1]
Shall I return you the latter from the [London Library](../others.html#29).
I ought to have the Proofs of [the Quest of Ulysses](../books.html#185). I know I put Lord Balmerino into the wrong rebellion which is as bad as putting Dunfermline on the wrong side of Scotland as I did in [Unknown to History](../books.html#157).

So much for not verifying!

There is a horrible misprint in the [Armourers’ prentices](../books.html#171).

Alderman Ityllio.

It is in the two complete editions, but not in in [sic] the [Magazine](../others.html#68). I believe it arose from my trying to change his name in the proof, and not having a revise. I meant it for Hillyard, but I have never yet discovered how to make an H that the printers do not take for It or a z that they do not make into a y[^2]

Yours truly

C M Yonge		
After all Mudie has only sent the second Highland Journal so I must keep the first

[^1]: These were books she required for work on [Victorian Half-Century](../books.html#189).

[^2]: CMY’s way of writing a Z is often confusing.

