---
date: '1886-06-25'
display-date: June 25 [1886]
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 151-2: '
original-date: '2011-09-29 11:22:05'
title: To George Lillie Craik
wordpress-id: 2836
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
I should like to find out how much the lady cares who urged me to write before answering.

Whether I will go on with this personal history, and whether time is still important, for it was the hurry that oppressed me.[^1]
The copyright of [Householders](../books.html#357) and [Thoughts on Pictures](../books.html#301) is mine.
I quite see that all ought not to come too much together, but I do think Householders is worth the having soon, for children by the sea get interested in shells, and I never saw a book meant for them about conchology that was not utter nonsense.

But no doubt this wants touching up.

There are a good many stories by good authors in that Magnet series and it is a pity they should be all lost.

Even as I regret Miss Keary’s Letters on Egypt.

Also a story of hers published hitherto only in [Aunt Judy’s Magazine](../others.html#54) about some capital school boys.[^2] I wish you and [her sister ](../persons.html#794)would revive that!

Yours truly

C M Yonge

[^1]: This seems to be a reference to some autobiographical writings, perhaps those reprinted by Coleridge, [Life](../others.html#40) 1-119, or those subsequently printed as [\'A Real Childhood\'](../others.html#254) in Mothers in Council (1892-3).

[^2]: Perhaps \'The Cousins and their Friends\' Aunt Judy\'s Magazine (May 1866-December 1867).

