---
date: '1886-09-11'
display-date: Sept 11th [1886]
from-address: Elderfield
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2011-09-29 12:57:14'
title: To Emily Dampier
wordpress-id: 2840
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Dampier](../persons.html#404)
So many thanks from [Gertrude](../persons.html#1462) doubly!

You will like to hear that [Philip](../persons.html#235) and [Margaret Buston](../persons.html#234) walked over here yesterday with some Grapes for Gertrude.[^1] They gave a very good account of their [mother](../persons.html#236).

There is no house to be had at Twyford, so they are looking for one at Winchester which is wiser, I do not think settling in one’s former parish is ever advisable
Poor [Mrs Monroe](../persons.html#1033) does not find it so.

What a beautiful garden she has made.

There will be no college meeting till October so nothing can be done about the living before that
With Gertrude’s love

Yours sincerely

C M Yonge

[^1]: Philip and Margaret Buston were two of the numerous children of the Rev. [Roger Buston](../persons.html#233) (1807-September 1886), Vicar of Twyford.

Evidently this letter is written shortly after his death, when his widow and children were looking for a new home.

