---
date: '1886-11-30'
display-date: Novr 30th [1886?]
from-address: Elderfield, Otterbourne, Winchester.
manuscript-location: 'MS Special Collections, The Shakespeare Centre, Stratford-upon-Avon. '
original-date: '2011-09-30 10:56:18'
title: To Anna Meredith Barrett Lennard?
wordpress-id: 2846
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Barrett Lennard](../persons.html#121)
I am afraid I do not know any one at Cambridge well enough to write about one whom I do not personally know. I do not think second hand recommendations have much effect people have so many first hand.

In fact I only slightly know two people there. I was there some twelve or fourteen years ago and like you, was edified by the admiration of ‘Our Backs’- I never could care for Cambridge as for Oxford.
I am sure I sent you our [Magazine](../others.html#85) for November.[^1] There was an account of the Colonial Exhibition in it, written by [Miss Finlaison](../persons.html#512) I hope it did not fail of coming.

yours sincerely

C M Yonge

[^1]: Perhaps the Otterbourne Parish Magazine.

The India and Colonial Exhibition took place in South Kensington in 1886.

