---
date: '1887-04-07'
display-date: April 7th [1887?]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/70
original-date: '2011-09-30 13:29:05'
title: To Christabel Rose Coleridge
wordpress-id: 2855
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Christabel](../persons.html#329)
Many thanks.

It will be the printers own fault if we are late for they are to keep holiday till Tuesday. I think you are right as to [GFS ](../others.html#23)chiefly because there is a continual conjugating of the verb to worry, active & passive I wish the Central would learn not Men’s Societies dont They have made all clergymen hate the concern! I wish I could draw up a warning about it that would not go abroad, to the many, an ‘Ad GFS’ – like Ad Clercum’. I like your next generation it is a puzzler – and very invidious, the real hitch being the absence of instructive code of honour and propriety where there is not gentle blood, which leads to untrustworthiness If you happen to read that queer Jewish novel Victims you will see it well shewn in poor Vera only the Jew girl had it which is not natural[^1]
I confess I care for Jane more than the rest!

Could you in marble works country help me to a catastrophe. I want Alexis- mooning – to let Fergus occasion a catastrophe that nearly kills Lord Rotherwood & other spectators seeing the quarries.[^2] I fancy Alexis managing the telephone & Fergus sending a wrong order to blow up the dynamite when he was not attending.

Is it possible.
I have got a he changeling in my head-[^3] not too like yours, for he is to be a Gentleman- and have to do with Mary Beatrice’s escape He was not changed as Elfrida was (really) but his beauty was spoilt by troubles at his birth & his old nurse imbued the children & himself with the notion that he was an imp
your affte

C M Yonge

[^1]: ‘Theo Gift’, Victims (1887).

[^2]: This refers to CMY\'s novel [Beechcroft at Rockstone](../books.html#201), published in MP January 1887-December 1888.

[^3]: C.M.Yonge, [A Reputed Changeling](../books.html#205) (1889).

Coleridge\'s changeling was in her novel \'A Lot with a Crook in it\'.

