---
date: '1887-04-15'
display-date: April 15 [1887]
from-address: Elderfield
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e 86. '
original-date: '2011-09-30 13:36:14'
title: To the Reverend John Frewen Moor
wordpress-id: 2857
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Moor](../persons.html#1046)
Thank you very much.

There is one thing more that I want, when you come to the Confirmation, & that is the last [SPG](../others.html#41) report.

Subscribing through [my friend](../persons.html#1462) here, I don’t get it direct

I have made a beginning but I go from home for nearly a week after the Confirmation I do not know what to do about the Chandlers Ford children.

There really are not many - & when a child has everything right it would be hard to refuse it a trumpery little reward because it was not of the parish.

Indeed I suspect coming to Otterbourne is sometimes made an excuse for not coming at all, it is much the way with borderers.

One or two families came before there was a school and have kept on

Yours sincerely

C M Yonge

[^1]: Cream card with rounded corners.

Cream envelope addressed to ‘The Revd/ J F Moor/ Ampfield/ Romsey\' and postmarked Winchester 15 April 1887.

