---
date: '1888-02-01'
display-date: Feb 1st [1888]
from-address: Elderfield Otterbourne
manuscript-location: 'MS British Library: Mary Gladstone Papers. Add MSS 46252: 4-5.'
original-date: '2011-10-03 15:40:56'
title: To Mary Drew
wordpress-id: 2874
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Drew](../persons.html#443)
No book ever was quite equal to the [Conversations with Cousin Rachel](../others.html#60), which I believe Masters still publishes.

It may here and there seem rather antiquated, but the solid part is of all times.

Then there is a little book called ‘Girls’ - published by Skeffington, and one by Lady Barker, published by Hatchard in connection with [G F S](../others.html#23)fr. I cannot recollect its name, but Hatchard’s list gives it.[^1]
As to fiction, girls in their teens seem ready for anything, and the less it is about servants the better they like it - I hardly know what specially to recommend.

Esmé Stewart’s For Half a Crown- National Society is a great favourite and ‘A Promise Kept’ of the same set is very good.

The [NS](../others.html#32) has published my [‘What to lend - &c’ ](../books.html#196)- and you will find a list there
Have you seen the [Mother’s Union Journal](../others.html#93)?

It is to be quarterly, and costs a penny.[^2] I wish the size could be larger for the money, but it must make its way first.

Its first start is very good, I think.

It is to be had of 	[Mr Warren](../persons.html#2377) - Printer
High Street
Winchester
Thank you for your kind promise of the address

Yours sincerely

C M Yonge

[^1]: Drew had evidently asked for advice books for servant girls.

Conversations with Cousin Rachel (London: Burns 1844) was an anonymous conduct book by Mary Anne Dyson.

Girls: Their Work and Influence.

Skeffington, 1877 was praised by CMY in What Books to Lend (9d.) ‘Practical advice in short compass; excellent for Confirmation gifts.’ The third book was perhaps Amy Susan (Marryat), Lady Baker, Half-Hours with my Girls, or, ‘Talks about anything’ (London : Hatchards, 1879).

[^2]: The first issue of the Mothers\' Union Journal is dated 1888.

