---
date: '1888-05-01'
display-date: May 3d 1888
from-address: Arlington
manuscript-location: 'MS Bodleian Library, Oxford: Ms. Eng. lett. e.141 ff6-9'
original-date: '2011-10-04 11:54:23'
title: To Jean Ingelow
wordpress-id: 2881
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Ingelow](../persons.html#741)
Your letter has just come to me here in the midst of the steep hills and narrow valleys of North Devon.[^2] I think I must have been 2 years old when I saw the baby in the blue shawl, as my birthday is in August, and we generally went into Devon in the autumn. I do not think I taught myself to read, as I was then an only child much looked after, but before I accomplished really reading to myself, I said off pages of a story book ‘Miss Jane Bond had a new doll’ and of ‘the Daisy’ and was thought to be reading. I remember the look of the book and its pictures.

Another early recollection comes to me. I should think at 4.

Crossing Torpoint ferry in an open boat being caught in the rain, and being picked up in the close carriage in which [my lame Grand mother](../persons.html#1585) had crossed in the horse boat. I believe it was then that someone being frightened in the boat and [too pale to read] we should be upset. I exclaimed ‘And then we shall catch a fish’ which I know was founded on Mrs Trimmers picture of the Red Sea where an Egyptian is convulsively clasping an eel.[^3] It is the unusual events that make the mark in the memory. I have just asked [my niece](../persons.html#182) for her first recollection.

She gave it as the wedding of [an aunt](../persons.html#616) when she was 3.

When I asked if she remembered a baby sister who died of whooping cough caught before that time - while she and her [brother](../persons.html#1607) were sent away to a friend - she did remember the last sight of [Maggie](../persons.html#1592) and the strange house.

By the bye, the elder boy who was then 5 could not be made to take in his sister’s death from his [father](../persons.html#1624)’s words, but when his 6 year old [sister](../persons.html#1613) who had staid at home told of the stillness &c. he cried bitterly, and when it snowed a month or two after, he told the other children that ‘Maggie was sending it down’
That first book I read to myself was a quarto Robinson Crusoe I being drawn on by the sight of a print where he is clinging to a rock to avoid being washed away by the breakers.

It was /lying\ on a chair, and [my grandmother](../persons.html#103) was reading the newspaper aloud, an operation during which I was hushed and had to amuse myself quietly without interrupting.

My [coeval cousin](../persons.html#1599) (now dead) remembered trying to run alone, but as he was [word too pale to read], that might have been late.

The most precocious child I ever knew of was [Mr Jenner](../persons.html#760), now in the British Museum, who used any amount of fine words before he was three, and before he was five, cried for joy at sight of a beautifully irregular Latin verb - and yet he neither died nor grew stupid.
I think I did learn voluntarily but the being an only child till 6½ with youngish parents immensely interested in me had a great deal to do with early growth I knew all the English Kings and the counties of England before I can remember from dissected maps but my frantic happiness was going among my cousins in Devonshire of whom only two are left, and those not my own special comrades - but I am on my way to them now.
I am quite sure that children develop in a curiously irregular way, and that one side outgrows another, so that one can never say anything is impossible or unnatural in any child.

My first written stories grew out of having to write French letters for my [master](../persons.html#1088), and were done in French - a sort of seed-leaves of all the [Beechcroft](../books.html#3) characters.

But I learnt handwriting later than most people, as my [father](../persons.html#1631) had a theory that to begin with very large capitals in chalk without resting the hand would be good for drawing, so he taught me himself when I was about 6½ or 7, and writing was not easy enough to be an amusement for some years after that. [My cousin](../persons.html#1582) and I wrote big round hand letters to one another when their brothers came and went to [Winchester College](../others.html#50) for postage was Elevenpence
Well this is what some girls I know would call a very I letter
I should be very glad to answer anything else you like. I go tomorrow to Clovelly, Torquay- to another [friend of all my life](../persons.html#351), first known at 10 years old[^4] pray excuse the blots I have just discovered.

It was a great pleasure to meet you after these many years of semi knowledge
Yours very sincerely

C M Yonge
One more early recollection - I think 5 years old - of a housemaid inciting my nurse to repeat ‘the Last Dying Speech and Confession of poor Puss’ from Jane Taylor,[^5] because I could not bear the melancholy & used to fly into a passion and roll on the floor - to her great amusement.

Which shows how little even anxious parents guess.

[^1]: Envelope addressed to ‘Miss Ingelow/ 6 Holland Villas Road/ Kensington’ postmarked ‘Winchester/MY 3/88.

One letter appears to have been miscatalogued as two.

[^2]: She was staying with her niece Alethea (Yonge) Bowles (1863-1941), who had married (1884) the Rev.

Henry Albany Bowles, Rector of Arlington 1884-1892.

[^3]: The \'Miss Jane Bond\' story occurs in William Mavor, The English Spelling Book (1801), though CMY may have encountered it in a different format.

Elizabeth Turner, The Daisy, or, Cautionary Stories in Verse adapted to the Ideas of Children from Four to Eight Years Old (1807) was another bestselling children\'s book.

So was Sarah Trimmer, Sacred History, Although most editions of the latter were unillustrated, CMY was perhaps familiar with the Series of Prints designed to Illustrate the Scripture History by Mrs.

Trimmer (London: Baldwin, Cradock and Joy, 1817).

[^4]: Mary Coleridge.

Kelly’s Directory of Devon and Cornwall (1893) lists ‘Miss Coleridge, Clovelly, Belgrave Crescent, Torquay’.

[^5]: Jane Taylor\'s poem was first printed in [Original Poems, for Infant Minds](../others.html#160) (1804).

