---
date: '1888-10-11'
display-date: Oct 11th 1888
from-address: Elderfield Otterbourne Winchester
manuscript-location: 'MS British Library Add MSS 54921: 165-6'
original-date: '2011-10-06 08:57:36'
title: To Alexander Macmillan
wordpress-id: 2893
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#939)
I have a story all but finished which I think might be printed before this season is over.

It is in 30 chapters and is finished to within 6 of the end.

The difficulty is what to call it.[^2] The period is from 1681 to 1696 the chief interest a youth who has been thought a changeling and who disappears for 7 years during which he is supposed to be murdered - but is really consorting with Jacobite high way men & smugglers. I have thought of Porchester Castle Underground[,] Peregrine the Changeling A Crooked Ship A Changeling Elf, Three Seventh Years, A Seven Years’ Secret
I believe this last is best.

The Mystery of the Vault, which really is most applicable sounds like a penny dreadful - and the objections to the other names relating to the hero are that they sound too like a fairy tale and that for half the book, he is out of sight - the narrative being with the heroine ‘Anne Woodford' - maiden? woman? who had kept silence her tongue is another alternative

Yours truly

C M Yonge		
Three Seventh Years is really the most suitable as the story is in 3 parts each beginning at the 7th year, connected with the belief about fairy children - when he is 14 - 21 and 28

[^1]: This is the only letter in the Macmillan file dated between 1887 and 1889.

[^2]: The book was eventually called [A Reputed Changeling, or, Three Seventh Years Two Centuries Ago](../books.html#205) (1889).

