---
date: '1889-01-29'
display-date: Jan 29th 1889
from-address: Elderfield
manuscript-location: 'MS British Library Add MSS 54921: 168-70'
original-date: '2011-10-06 09:58:08'
title: To George Lillie Craik
wordpress-id: 2899
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
Many thanks for your letter and cheque. I am glad to see your writing again, and that the first dreariness of return has been faced.[^1]
I am glad the cheap edition is doing so well, it is capitally got up and bound, and I regret nothing but [the Daisy Chain](../books.html#24) [illustrations](../others.html#167) and those to [the Trial](../books.html#53).

Those to the intermediate edition were much better.
I have had some correspondence about a story of the historical kind which I finished in the autumn, but it was thought better to let it wait till [Beechcroft at Rockstone](../books.html#201) had had its start.

Its name is a great difficulty A Seven Years Secret has been thought of but does not really suit and I now think that [‘A Reputed Changeling’](../books.html#205) or ‘Peregrine the Changeling’ would be best as though it is by no means a child’s story, the whole turns on the hero’s life being influenced by a sort of half belief in his being a changeling imp
It is in the time of the English Revolution

Yours truly

C M Yonge

[^1]: His wife Dinah (Mulock) Craik had died on 12 October 1887.

