---
date: '1889-04-30'
display-date: April 30th 1889
from-address: Elderfield  Otterbourne Winchester
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2011-10-06 10:45:24'
title: To an Unknown Man
wordpress-id: 2906
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Sir
I am obliged for your letter, which confirms the view I have had for many years that it is not possible for a person of a different nationality to draw a thorough portrait of one described from within, as it were.

You remember that in dealing with foreign scenes, [Scott ](../persons.html#1672)always took a Scotch or English hero - in whose person he saw all the surroundings
In fact I have never had any intimate knowledge of Americans such as could enable me to write otherwise than in the external manner that occasionally was necessary to my story. I think however that the family in [Magnum Bonum](../books.html#131) where Jock was nursed after the yellow fever, and into which Bobus married were thoroughly nice good people, though there is not much of them.

And Edgar’s adventures were written long enough ago for a change in the far west. I had just been reading in a book of travels, an account of such attacks.

But I should certainly not venture on describing American home life from within, as I could only do it from the books, of which I read a good many, but there are shades that no one could follow who is not ‘to the manner born’
I think since the general depression there has been much less fear of losing caste among Gentlemen than even when the ‘[Pillars](../books.html#109)’ were written.

One of my friends, a [General’s daughter](../persons.html#1520), could not be reconciled to Felix going into trade.

On the other hand, an invalid American lady with whom I corresponded for many years could not understand the different positions of Dr May and Henry Ward and I have not the least doubt that to try to describe American life would lead to great errors, so that I never venture on more than a few such touches as are wanted in the course of the story.

Missisauga was chiefly taken from a book about some Western settlers, given me by my Pennsylvanian friend.[^1] I have a [nephew](../persons.html#1607) in Cumberland Valley Kentucky, who has been in America five years, and on his visit last year, found England very small so that I am gaining some experiences

Yours truly

C M Yonge

[^1]: The account in [The Trial](../books.html#53) of the Ward family’s sufferings in Missisauga also appears to be much indebted to Dickens’s in Martin Chuzzlewit.

The Trial was also the novel, referred to here, in which the difference in social status between a physician like Dr May and a surgeon like Henry Ward is depicted.

