---
date: '1889-06-10'
display-date: June 10th 1889
from-address: Elderfield
manuscript-location: MS John Rylands Library, Manchester, FA1/7/839a-839c
original-date: '2011-10-06 15:37:31'
title: To Edward Augustus Freeman
wordpress-id: 2908
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Freeman](../persons.html#523),

This is delightful and will make [the Cunning Woman](../books.html#203) really worth having. I am afraid I must not keep her to pick up more witchcraft but I should like to know what a witches’ ladder is.

The Coleman was a strange chance coincidence. I have changed them all into Coles!

The Tayles was a misprint from a mistake of mine undetected - I believe Watts is really

‘Their nature, too-’

I have an old copy that I can’t lay my hand upon, but I know that ‘their nature to’ to was a family joke said to be a misreading, and I think Mrs Patty was sure to say it correctly[^1] I have put in the dear delight.[^2]

The Monmouth myth is out of Macaulay, who probably got it in his Barley wood days.

We in Hants talk of ‘poor old ladies’ - but of course she would not say it to the real lady so it was a misprint.[^3] That regeneration danger is delightful! I have put in Taunton beer, as Will Chip lands it - The excuse for the odd draught of liquor was a sop to the Temperance folk. I am afraid I can’t lengthen out Black Giles, a very old friend of mine- You see I put in Hester Wilmot also out of a tract. I remember [my father](../persons.html#1631) much admiring Dick’s debût in school.[^4]

I have altered the tumps(?) ‘The Severn Sea’ I could not remember, and was what I wanted.[^5]

I thought there might be gipsy blood in the old woman

I did not know that ‘cared’ was a living word - I have added ‘as the natives would say ‘cared with a sull’.

I have turned chapel into class meeting as safer.

It is one of the little anachronisms which it is so hard to avoid.

But in the ‘cuts’ to the Village School, published between 1780 and 1800 Mr Right walks about among the children at play on a weekday in his Gown and cassock- My [mother](../persons.html#1606) born in /95\ recollects her [father](../persons.html#106) who died in 1809 so arrayed but that was on Sunday.

Still I think Mr Right is sufficient authority - I have carried the Gun to Sedgemoor.

About the pease my theory is that when they are all mashed up together they become an adjective in a pease pudding or when they are treated collectively but when they are individual, their plural should be peas.

If I could, I would have said a barrel of pease, and pea rolling about the floor - but the printers would never have suffered it and of course pisum and pois shew that S is an integral part of the pea - like a of the peacock, so I will make them pease

I must look out ‘had up to Bath’ as uncertain ‘Up to Exeter’ means had up to the assizes at Devon, so that even St Peter was said to have been taken ‘up to Exeter’ and even in the far parts of Hants ‘at Winchester’ used to mean in prison - and I thought Bath the assize town - but if Wells is a quarter sessions one, of course it will not do.

Bedhampton for Bedminster is an [sic] mistake of memory- the banns had been put up, but I will make it ‘St Mary’s’.

It was just what I wanted to know.

There is a St Leonard’s - but I fancied St Mary’s too far from the docks to be for the sailors’ weddings.

All the unsatisfactory weddings here used to be at Portsmouth I dont like employed but it was the only way to avoid a reduplication of who and whom and engaged is worse ‘taken in his place’ is ambiguous

Actually there is no Parson in the clergy list!

So the scholar is unique, and I have made them parsons.

‘Against the Stream’ has some clever bits about the Clapham sect.

It is by the

[author](../persons.html#287) of ‘Schonberg Cotta’ of whom the lady complained ‘that she never could get the books she ordered by the Author of Terra Cotta .

To do Fox or Sheridan it would be needful to be as witty as he who did Falstaff!

And Hannah despised the first representation of ‘the Rivals’ but I believe that was bad acting.[^6] How many times I have been interrupted in this letter, I cannot say!

But I can only add a thousand thanks to you and [Mrs Freeman](../persons.html#2383)

Yours very sincerely

C M Yonge

[^1]: CMY had stayed with the Freemans, who lived near the former home of Hannah More and her sister Patty, in order to gather material for The Cunning Woman\'s Grandson.The quotation is from Isaac Watts\'s Divine Songs for Children, from the well-known hymn beginning:
\'Let dogs delight to bark and bite,
For God hath made them so;
Let bears and lions growl and fight,
For \'tis their nature too.\'

[^2]: Isaac Watts\'s hymn, \'Father of Mercies\', includes the lines: \'O may these heav\'nly pages be/ My ever dear delight\'

[^3]: Inserted above, \'the dame\'.

[^4]: The History of Diligent Dick, Black Giles, the Poacher and The History of Hester Wilmot were three of Hannah More\'s Cheap Repository Tracts.

[^5]: The local name for the Bristol Channel; it gives its name to one of the prophecies of Merlin.

[^6]: CMY quotes in [Hannah More](../books.html#199) (1888), 27, her comment on seeing Sheridan\'s The Rivals that \'much is to be forgiven in an author of three-and-twenty\'.

