---
date: '1889-12-27'
display-date: Decr 27th 1889
from-address: Elderfield
manuscript-location: 'MS UCLA: collection 100: box 95'
original-date: '2011-10-07 14:50:36'
title: To Frances Mary Peard
wordpress-id: 2921
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Frances](../persons.html#1160)
Thank you for your letter.

We don’t deal in squills, but I have just brought in various primroses and violets, though there was hardly a berry for the Church.

However the holly leaves are much finer than when the berries have starved them.
[Gertrude](../persons.html#1462) was tolerable and could enjoy her cards and presents, and shells go on as her great delight at present, that wonderful [step-step father](../persons.html#132) of hers has an endless variety of collections, and sends her shells and fossils the finding and naming of which are a grand occupation, and she likes her maid.[^1]
Your Blue Dragon is a great success, and I like Paul’s sister better than any of your stories for a long time, but as Dover was all Castle to me, it was funny to find no mention of such a feature in the landscape![^2]
[Miss Bramston](../persons.html#198) is coming out here tomorrow, and goes to Torquay on Monday—[Mr Innes](../persons.html#744) much admires her Apples, and there is much that is fine in it, but one wants somebody to love.[^3] I am glad to hear so good an account of [Mrs Peard](../persons.html#2390).

Are we all going to have influenza? I remember a bout of 40 years ago or nearer 50.

Your affectionate

C M Yonge

[^1]: The \'step-step father\' was the Rev.

James Beck, Rector of Bildeston, who had married Gertrude Walter’s stepmother Caroline Walter.

Her maid was probably not [Ellen Foster](../persons.html#2353), who seems to have died this year.

Her successor was perhaps [ Jessie Palmer](../persons.html#2169), who was at Elderfield in the 1891 census.

[^2]: These were books by Peard; CMY had visited her cousin Jane Moore at Dover Castle.

[^3]: Mary Bramston, The Apples of Sodom 2 vols (London: Walter Smith, 1889).

