---
date: '1844-09-30'
display-date: Sept 30th 1844
from-address: Otterbourn
manuscript-location: 'MS West Devon Record Office Acc No 308: 30/9/1844'
original-date: '2010-03-12 14:09:29'
title: To Alethea Yonge
wordpress-id: 2944
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Alethea](../persons.html#27)
I have begun on this great piece of paper because I really have a great deal to say both to you and [Anne](../persons.html#1582), but I believe you wrote first, so I make the letter to you. I am very much & sincerely obliged to you for sending me the opinions so frankly, & I really believe the best way of proving it, is to try to defend myself as well as I can & with a better pen than I have begun with.

You are quite aware that [you are] welcome not to read what I say, or what I send & I am quite aware that I am running the chance of boring you and making you wish you had no such foolish conceited cousin in existence, but as your good opinion is a thing of value more than most people’s, I shall say what I can for myself & in the first place send the advice of [Miss Ashington](../persons.html#67)’s wh next to the [Kebles](../persons.html#798) induced me to publish [it](../books.html#2). I do not say that all she says is true, but at any rate it is unprejudiced by any acquaintance with the author, & shews that there are two ways of viewing these things, & pray do not fancy I send it to praise myself. I can scarcely think that [Miss Robertson](../persons.html#1250) can have read the book throughly [sic], but that I suppose is what every criticized author thinks and of course is nothing to the purpose, so I will try to divide what she says into two parts, first where I think she & I completely differ in idea & principle; next where I have really failed in carrying out my own idea.

Now first I think her, and Anne’s notion of a story or moral tale, seems to be that it must in its whole tendency elucidate some one principle, as its one ground of action, & that any thing beyond a little mere decoration is irrelavant, [sic] but it seems to me that things in real life hardly ever happen all with that pointed tendency to one thing; those who seek for a salutary lesson, in all that passes around them may find the honey in their flowers infinitely varied, though at the same time each according to their own character, experience, or wants, will make these lessons tend in one certain way; therefore since nature & real life are allowed to be the most instructive things to be found, I thought a story taking in the mixture of events & characters differently acted upon by the same circumstances would be more useful, than one written on the other plan.

Thus I have never intended or attempted making any one person a pattern of perfection in all its branches, unless it might be Dora, who is nobody; & Lucy, whose shyness half hides her.

Now as to their being sketches of characters thrown together for my amusement, I do not think that Anne is quite fair there; I should certainly have never written the book, if it had not amused me, & the characters have come out without my intending it, likenesses of sundry people; but with the exception of Elizabeth, whom I always intended to be like myself, only worse trained & more useful; I had no thought of copying anyone, except that one or two little ways of speaking, or tricks wh form no part of character, were put down by chance to make them more like life. A plan or rather two or three plans wh I thought might give hints of the dangers of the present race of young ladies I certainly had, & I suppose the two or three make it seem confused. I wished to shew that the over use of good things is an abuse of them, I mean that self controul [sic] is wanted in love of almost all that is excellent or harmless, as schools, poor people, learning, sense, value for the good, merriment, good nature, gentleness, quiet, that self conceit may exist in a thousand different unsuspected forms; as in love of our own plans for the good of others, in admiration of what is peculiarly our own, in contempt for the abilities of others, even when we are modest in our estimate of our own abilities or goodness, in building our estimate of ourselves on the opinion of others, whether judges or not, rather than on our own consciousness of having done our best, or that wh was our duty [sic] to do, that strict and scrupulous obedience is the only guide wh will not lead us astray in some way or other, that people may do right from not the best motive, or spoil their best deeds by their manner of doing them, that those who have the clearest knowledge or right & wrong will without a humble spirit do worse than the meek spirited who have the least knowledge, that a fault is not an equal fault in all, and that a girl may shew the fullest confidence in her mother without being a tell-tale, & becomes a far more useful person to her companions if she loves them, by discussing their characters with her mother, than if she keeps their faults to herself, on the principle of the party spirit of governors & teachers against those under them.

Looking at the last page will shew the reason of the name, it is principally a lesson on the mischiefs produced by self conceit & the want of self controul together, & it is a lesson not quite on the surface.

Now, I hope you Puslinch people at least will allow I had some reason beyond recommending the game of conglomeration, or making sketches of my friends, the harshness of the book, wh she mentions is not quite, I think what Anne supposes, Elizabeth’s unkindness, for I am sure I never mentioned that without strong reprobation especially after what Miss Ashington said, besides no one fights but Elizabeth, she loves Helen all the time, & only laughs at her more than is kind, & Helen once so retorted, when as Elizabeth said she was as much out of her senses as if she had been absent.

Elizabeth was in a way, out of her mind with self will about the Institute, but she bitterly repented of her unkindness then.

No, I think what gives that effect is Lady Merton’s coldness wh I said was a part of her disposition when I found I could not make her otherwise, I always thought her a failure, but Papa rather liked her, so I did not alter her, and also the absence of words of endearment, and laughing at Helen for loving them.

Now you know we never use them, yet I believe there is a good deal of affection without them. I am sure I should be very unhappy if I did not trust so, & how much more valuable is one short quiet expression to us than any exaggerated expression of the kind to those who live in the constant use of them on trivial occasions without attaching any special meaning to them, & I think we are a good deal in the habit of thinking such constant caresses open to ridicule, though if we lived on them, we s[houl]d feel starved without them.

Whether the principles of the story are harsh & cold in themselves, I cannot say, one’s notion of that must depend on one’s own character; but I can hardly believe that I can be cold hearted, I do hope that Anne would not say so at least, or Julian indeed. I am sure of him, so I can scarcely think the tone of the book can be; but of this I suppose I am no judge.

Now does any-one really believe that those girls laughed at people in bitterness of spirit? that they would not have been just as ready to do them a kindness the next moment, or that Elizabeth’s talking of a natural antipathy to Mrs Hazleby was more true than when she said she would have gone up the chimney rather than to the Mechanic’s institute.

And as to their fun about Mrs Turner, if that was bitterness of spirit, what must ours have been the night we heard of the infant bazaar and the new doll in the wheel barrow?

Anne will think of what she said the next day, but I think I am right in saying that it is possible to laugh at certain things in certain people without malice, without ceasing to love and esteem them,
I should think you would agree with me that the affections are in a healthier state, wh exhibit themselves more by deeds than words, & with this view, is not Elizabeth’s a life of love, thoughtless of se lf, always helping others, doing what she dislikes & called away from pleasure to help her mother and sisters, labouring ceaselessly for them, & the school and thinking it no toil, unwilling to be helped but in a c heerful spirit, gentle towards the little ones, and her only failure in love being her tongue.

Why did the uncontrouled girl do all this but from love, & is not hers a truer kind of love than Helen’s selfish languor, and wish for exchange of tender feeling, ‘Let us not love in word or in tongue, but in deed, & in truth’[^1] seems to me to apply to our love of our own families as well as to higher things.

Elizabeth’s false ideas I consider to be the difference in principle between my critic & me, her exaggerated expressions were intended to be half a defect at times half a joke, & a copy of many young ladies style of language.

The ground work of her character is the noblest principles & feelings almost always acted on, but her mind is very ill regulated & the excess of good feeling runs into evil, & the early freedom from restraint in small matters, and known judgement being really very excellent in general has fostered her self will and conceit, & her temper is truly ungoverned in some respects.

Lady Merton explains her contempt for others to Anne.

Mr Woodbourne is not always a pattern as may be seen from his having married twice, his stern[n]ess and coolness were intended to make Elizth’s character such as it was- the glances were useful to her who felt them severely, and people do generally, especially fathers, behave to their children rather according to the impulse of their own characters than in their conduct to suit each particular child’s disposition. I meant to make him a reality father than a perfect nodding Jupiter of a book father who always says exactly all and no more than he ought to each.

It was his way to be silent & stern, & so he was in the midst of his affection & kindness, & his daughters learnt to value his demonstrations of love accordingly.

Perhaps his ‘basilisk glance’ at Anne was one too many, but I think he would have given it. I am not sure whether that was worth putting into it.

The last thing mentioned is Elizabeth’s love of the Church, & here is the great difference.

Miss Robertson seems to think her affection for it was independent of its holiness, what might have been bestowed on the Puddington chimney if her father had built it, but could she have loved it as she did, if not as regarding it as an offering?

Was not her joy that her father had been permitted to make that offering, that the Holy One would abide in the work of his hands, could she have loved it at all without also loving the Holy Catholic Church, & did she not love still better the old Church, where pride in her father’s good deeds would not influence her? & was she losing thought of its use when she said ‘it was glorious now, & what would it be tomorrow?

When she rebukes Helen for unwillingness to exert herself in helping it forward, was it not that she felt that labourers gifts not freely offered in such a case are like Cain’s offering unacceptable & void.

Was it her own choice to be troubled about many things on the Consecration day, & did she not employ it in a better way, by toiling for her Mamma than by trying to keep herself quiet, for serious thought and contemplation, and leaving unfulfilled so great a duty as succouring her father and mother.

Those who know what a consecration day is to those who have to arrange & settle can say that it is no day of quiet calm thought; the uproar & confusions were Elizabeth’s misfortunes, not her choice, & no wonder that when wearied with running about talking to people whom she did not like, bothered by Mrs Hazleby; and having, I allow, egregiously failed in temper towards Helen, she could not put her mind into a peaceful happy frame.

For an explanation of my line of thought upon that matter, see a sermon in Mr [Newman](../persons.html#1084)’s 4th volume, called ‘Christ manifested in remembrance’.

Her thought of its holiness was not merged, but she was silent in general, & so was I in the book because I depended on people following what I meant, & feeling that much mention of such holy things is irreverent in a mere story.

Now do not think that I suppose you wanted all this defence on my part, you know people are apt to say too much, rather than too little in defence of themselves, & I could not help wishing to justify myself towards you. I hope it will not seem foolish to you, & that you will see I had some principle, whether carried out or not, in writing Abbeychurch, & it is for this reason I have written all this rigmarole, I have just read it to [Mamma](../persons.html#1606) & she says I had better ask you to send it back to me, as it may be entertaining to me to see what my own reasons were at some other time, & the correspondence may as well be kept together.

You are welcome to send all, any, or none of my defence to Miss Robertson, as coming from you or the author, &, I really believe I should like her to be asked those questions, & given those reasons about the Church.

You will be afraid to send me any more opinions if they entail such a volume upon you, but if I can trust to any one’s understanding my feelings about it, it is to you, & I hope you will no see that it is not conceit or vexation at the criticism, but a young girl’s natural interest in her performance. I cannot think it very nonsensical when Mr Keble and [Judge Coleridge](../persons.html#344) both have said they liked it.

Tell me if one of the other opinions is not [Miss Mudge](../persons.html#1067) & which, I cannot say either of them concern me much beyond making me laugh, it was what I always expected. I will write in more satirical style in a day or two.
yr. affect:
C.M.Yonge

[^1]: 1 John 3: 18.

