---
date: '1846-10-30'
display-date: Friday 30th Oct? [sic] [1846]
from-address: '[Otterbourne]'
manuscript-location: MS Plymouth and West Devon Record Office 308/70/17
original-date: '2010-03-17 09:42:29'
title: Anne Yonge to Mary Yonge
wordpress-id: 2957
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626),
My letters must seem to be very few & far between but sudden revolutions happen now & then, wh disorder my private arrangements, such as yesterday, when I was just seated to write to [Alethea](../persons.html#27) & [Uncl Wm](../persons.html#1631) proposed driving Char: & me to Southampton, & before we came back the visitors were arrived.

You will see how much I enjoyed your very long letter presently when I tell you how pleasant it was reading it with [Charles](../persons.html#1601), but I am sorry to hear of [Jane](../persons.html#1616)’s troublesome finger, it must have been very painful, & I hope in addition there will not be the inconvenience of the nail coming off, wh is such a tiresome affair.

You must have enough to do with such a sick house. I do think [Miss Barker](../persons.html#107) is very fidgetty about herself she must often have heard us laughing at [Aunt M. A](../persons.html#1627).’s dislike of physic.

It is a valuable discovery to find even one Physic FY[?initials unclear] is not averse to she says she sipped her senna tea for pleasure. I suppose [Papa](../persons.html#1623) is gone to Torquay to talk to [Dr Harris](../persons.html#629) about [Graham](../persons.html#321).[^1] It is a great shame of him to throw the difficulty on Papa’s shoulders.

There is a great laugh against him here, because he invited [Julian](../persons.html#1624) to breakfast at 8, & was not down himself till 10. I believe I wrote last on Tuesday, so now I will begin at once with our proceedings on Wednesday.

The first thing was a note from Chas leaving me to announce to my friends that he wd not be here to breakfast but go to morning chapel at [Winchester](../others.html#50) before he set out (because he liked chanting better than no changing, & lo behold the organ was repairing & he did not have it after all.) He arrived soon after we came from church, pretty warm with his long walk, though it was such a cold day.

We sat in the Schoolroom & I had an entertaining letter from [Duke](../persons.html#1599) for him to read & then Uncle Wm came up and desired him to give an opinion on his Yealmpton case, & gave him the papers abt it to read, wh Chas liked.

Then we had some luncheon & set off, & I was more sorry when we got to the end of our drive than the beginning.

We were shewn up into a room of strangers, [Mrs Moberly](../persons.html#1019) came forward & spoke to each of us & then begain to talk to [Aunt Fanny](../persons.html#1606) & [Mrs Keble](../persons.html#795). [Mr Keble](../persons.html#798) just shook hands & entered into a conversation with Charlotte about her history of England, part of which he had been reading over for her.

It was delightful having Charles there, for we could fall back on each other, & amused ourselves with examining a large oil painting of the four eldest children which [Dr M](../persons.html#1015) had done whilst Mrs M was ill for a surprise, but it is a horrible painting more vulgar looking & harsh than [Uncle Seaton](../persons.html#313)’s even.

The painter is a cousin of [Mr Huntingford](../persons.html#1705) for whose sake he was employed.

He, Mr H., dined afterwards, & was very anxious to know Uncle Wm’s opinion of the performance; he ventured to ask just as we were going away.

Uncle Wm sd ‘Oh I must take more time to tell it you than I have now.’ & he means when he sees him again to tell him if he has any regard for his cousin he will ask Dr M to take it down & paint it over for no one ever seeing it wd think of having any thing to do with an artist that cd do such a picture.

It is very large the children almost larger than life the youngest [Dora](../persons.html#968) is seated on the ground [sketch] her bonnet thrown off by the side [Alice](../persons.html#1025) standing over her dressing her up with flowers, white convolvulus wh the other two are bringing to her in a basket, but all harsh bright colours no softness even in the faces, so that even the likeness is not agreeable.

Well we stood & talked abt this, & then Charles showed me on another table a most beautiful [sic] of Mrs Moberly by [Mr Richmond](../persons.html#1731), such a very pretty picture (abt the size of Charlotte’s) in water colours, independently of the likeness wh is exact it is not at all stiff or formal although she is merely seated down with her hands before her (has made sidelong remarks & hoped I was enjoying myself.

It is a very large room & in an alcove at the end were all the children, seated round a table at play.

In a widow seat some school boys scrambling together, & some commoners [Dr M](../persons.html#1015)’s nephews & a young Bennett. I asked Chas if he knew much of them, he sd in his funny way why I made one of them black me a pair of shoes this morning this morning.

Now they were all spic & span full dressed.

Soon after Mrs M & the Children went to get ready & Dr M came & spoke & then tried to persuade them to come in, but they were shy, he sd my little regiment is not in good order you see, at last they came in with their bonnets on & books in their hands & we set out.

Uncle Wm took Mrs Moberly, & the Dr Aunt Fanny.

We journeyed down the stairs out into College street, up wh we walked a little way & turned into the Court, some boys who were walking there, must have been amused, for in front of all was sailing the fattest of old nurses with the baby covered up with a white Handkerchief.

Then At Fanny went & took possession of [Emily](../persons.html#81) because she is her goddaughter a poor little girl of two or three years old.

She submitted to being carried & staying by Aunt Fanny all the time without crying.

We were all together a pretty large party with servants too & each of the young children but no one went near the font except the nurse on the side & on the other.

Mrs Keble Charlotte (proxy for [Lady Palgrave](../persons.html#1125)) & Mr. [Chas Moberly](../persons.html#1707), Godfather, nephew of Dr Mr Keble read very slowly & made long pauses & knelt down before he went to take the Baby, stood with his hands crossed on his breast all the time, except when he came to the middle of the prayer of consecration for the water then he stopped moved his book to the further side of the Font, & stretched out his arms crossed over the water till the end of the prayer.

Then as I said knelt down; the nurse stepped forward, and Mrs Keble took the Baby & handed it to him: he put water three times on its face, & then rubbed it on with his hand.

It cried a little, Mrs Keble took it again & held it till the exhortation to the Sponsors when she returned it to the nurse, who had more than once before manifested a desire to take it.

This is not a usual custom Chas never saw it before.

The Godfather gave the name ‘Charlotte and Elizabeth’ & Mr Keble also said the and in christening it.

Many people would say there was mummery but woe to the man that sd dare do so in this house.

After it was over Dr & Mrs M. & At Fanny & the sponsors kissed it & then we journeyed back again.

Chas Charlotte & I however escaped to the Cathedral, but the bell stopped before we reached it, & the service had arrived at the Lords prayer, & we had to walk so far before we reached the right seat.

Chas was shewn to a seat by the Verger, who he heard saying something as he shut the door & turned to ask what he sd. & then found it was the Lords prayer he was repeating to himself as he walked up & down.

There were only 8 choristers instead of 16 & the organ was having something done to it & was not played. I am glad I have heard this for once, but I cannot agree with Aunt Fanny in wishing it was always so; it loses all the grandeur the Organ gives, but is worth having in this respect, that it shews you how wonderfully perfect & complete the sound is in itself.

Every part full & entire not like the Newton men, when each note without the fiddle was short & quick & died away between, making it interrupted & imperfect.

We next went to the Post and got your famous long letter habit shirt & all wh I put into my pocket the first opportunity, & also one from Alethea.

Then we went to Aunt Fanny who was sitting with Mrs M to tell her we were going to walk in the Warden’s garden, & Miss [Cath: Barter](../persons.html#116) who was going home, conducted us through his kitchen passage to it.

Then Charlotte suddenly turned & sd now if I stay here I shall see nothing of the Children, so you can walk as long as you like & then come to us again, so she departed leaving us very happy indeed. [Boger](../persons.html#116), & a nice looking Holdsworth, & [Baldwin Bastard](../persons.html#120) were playing at football in the grass in the middle, so we walked up & down under the trees by the stream of water reading our letters, it was the pleasantest time that cd be, for you told so much that Chas liked to hear & talk about, wh would not have been worth while to write on to him, when he needed explanation. I think it must have taken nearly ¾ of an hour.

Chas said it was better to speak to Boger & called him over once, informed him I was his sister, but he sd to Chas afterwards he had no idea who he was speaking to, he did not stay a minute.

Afterwards they passed us again in their way into the house, Chas said ‘What time is your dinner Boger’ Six, what’s yours’ ‘Six too, says Chas.

It was very funny. W. B. said he was going home to dress then to be ready by the time [the Warden](../persons.html#118) came home. [Johnny Pode](../persons.html#1184) is laid up from a kick on his knee.

Soon after we found a door at the end of the Garden wh opened into College street so after a little hesitation we stept forth, & shut ourselves out, divers boys were passing backwards forwards but it is not the fashion to take any more notice than if they were strangers.

We walked towards the meadows a little way & then saw at some distance Dr Moberly & Uncle William so as it was growing cold & the clock had struck 5 we turned to go in, the College gates were just shutting.

Chas asked the man (oh I forget his name, don’t you know it) not Crow, if any letters came for him, to give them to Mr La Marchant, then he saw 3 commoners coming, & ran back to stop him from shutting the gate before they came up, but it was too late & he sd they wd be obliged to go back & get in another way.

He conducted me up to the Drawing room & then went to dress.

He cd get into the Court by a door at the bottom of the staircase, & the 19 studies we look down on from the staircase window, they are exactly like a row of pigsties.

We took our muslin Gowns with us, & now went upstairs to dress.

We were the first of the ladies ready & found in the drawing room Dr M. & his nephew old [Mr Crocket](../persons.html#1710) (her father) & the far famed [Mr Church](../persons.html#297).

He is exactly such another little man as [Mr Steward](../persons.html#1680) but rather taller & very shy.

He talked to At Fanny about the [new Pope](../persons.html#1709) & railroads routes to India.

Dr M. said he had some puzzles for Charlotte. A ship sailing round the world it is well known, loses a day.

Well the Electric Telegraph passing round the Earth must do the same but then since it takes but a few minutes to accomplish the journey, the news will arrive 24 hours before it starts.

News of a Prince born on a Saturday will arrive on Friday. I do not recollect enough of the reasons to understand it, but he sd no one could disprove the fact, however ridiculous it may appear.

He sd further that there is to be a coinage of 3d. pieces & with them everything can be paid without pence.

Chas proposed 11, & ? divers sums, wh they proved cd be accomplished provided the other person has plenty of change. A puzzle for Frances.

It is like the Men & their Marvels.

Well, now for the dinner party. 18 altogether /besides a side table of the young schoolboys\. I was greatly relieved when [Mr Wither](../persons.html#1544) stepped forward to take me down to dinner.

Each time Chas had hoped he ‘wd not take Anne because then she wd hear no conversation worthy of the name, I had privately quietly hoped he would & so it proved Then better still, Chas who took down Miss Crocket or somebody was shut out of his place on the opposite side & after a movement or two of difft people, a vacant chair presented itself on my other side, & there we sat, & both our neighbours were so busy talking that except some interruptions from Mr Wither now & then we had all the conversation to ourselves without any one listening Chas enquired for puppies & dogs & farm and Mr Burrel & sd he had written home to ask what Papa was going to do with all his money, & many other jokes.

My Uncle & Aunt were certainly the greatest people there that day.

He sat by Mrs & she by Dr & took precedence of all others. I did think we left that dining room that it was the last I sd see of Chas.

He said Dr M always made them a sign when it was ½ past 8 because they could not be looking at their watch in public, but as the little boys came up with us & were still in the drawing room I thought it cd not be so late, but the gentlemen came &[ Dr W](../persons.html#1564) said Charles was gone & Dr M soon despatched the others.

Dr M spoke to & of Charles several times & Mrs Moberly went & sat down near him once & talked a little while but this she did to everyone. I sd think her manners were the best ever seen, for she is quite as quiet as [Mrs Robertson](../persons.html#1250) without any stiffness, more like Lady G Bulteel without her die away ness.

She showed me Aunt Fanny’s Prayer, & [Mr Palmer](../persons.html#1129)’s poem wh they have had mounted on large sheets of paper & bound most beautifully.

It really is beautiful now.

Mr R Palmer was there a day or two ago, & she ‘ventured to shew him this book suppressing the fact that it was intended for [Mary Coleridge](../persons.html#351)’, & he was much surprised his verses sd have been deemed worthy of such an honour.

Mr Huntingford sat by Charlotte, & they talked abt Cicero & his change of name to Tully, & learned subjects of all kinds, she likes him & afterwards she was talking to Dr M. about Greek & Latin composition, the difference between them &c.

Mr & Mrs [Gunner](../persons.html#1708) were there too, they despise him & call him blacklooking, & say she is a silly little thing.

She is a little person, something like young Mrs Dolling only more sprightly.

Miss Crocket is a busy bustling goodtempered little thing, short & fat her cheeks so fat & her eyes so screwed up, that when she laughs, just like [Elizabeth Morshead](../persons.html#1716) & the same kind of expression, quite natural in manner & everyone liking to speak to her & she ready to laugh & talk with all or any she may chance to fall in with, or to play with the children, or as her father sd, to trip to the town to buy her household goods, or to the Cathedral, never out of temper, o yes I’ll do this, I’ll do that however busy she may be.

Miss Cath: Barter is difft more talkative but yet more difficult to get on with than Miss [Helen Bennett](../persons.html#296), who is plain & straightforward, not ashamed of herself or her dress, a Cordelia, or Mary Crawley rather, kind of person in looks but simple & goodnatured, one who wd find out governesses or any ?such despised person to talk to, but more lady like looking than M Crawley.

She talked to me for some time, & I liked her very much.
A younger Miss Barter was just arrived with the Warden, from the wedding, with a favour stuck into her shoulder. I did not like her, I sd think she thought herself pretty.

Mrs Moberly of her own head offered At F. to see the baby in bed, & Mrs Gunner, Chas and me, more than we sd have done in the same case, & she pulled open the curtain of its little pink Bassinette, & put the Candle close in front of it, it was a pretty little child very small but fresh & healthy, & its hand laid up on the pillow, with a little double frill coming round its wrist.

Mrs M pointed to one door, close outside the room the baby was in, & sd that opens into Cloister gallery. I cd not help smiling, when I remembered its other side wh I had seen last with Duke & Charles, rather a noisy place for the Baby Before diner we heard bells, & found they were the College Chapel in honour of the wedding It is a great rarity, for they always are in fear of the tower falling.

Dr M took us into Mrs Moberly’s little sitting room to listen, it was most beautiful, for they were ringing changes, & not at the rate we usually hear, but a little faster than the Cathedral chimes in Exeter. I never heard any thing so pretty in the way of bells.

Then Dr M. jumped up on a sofa & pointed out the windows of the Commoners sleeping rooms, & sd, ‘That’s where your Brother rules, he’s a great man with us.

Of course he says this in great measure for something to say, but he spoke & referred to him more than once in the course of the evening, & called him Charles.

We cd not help laughing at dinner because we heard him at the top of the table saying ‘Now if I say Chas two people will look up, but I must offer some Beef, so then he called Charles & of course it was necessary to look up altho he meant his nephew instead.

They are pretty little children & well mannered, but kept pretty much to themselves, playing at draughts & chess at the end of the room. [Miss Saunders](../persons.html#1282) when first I saw her did not look very stern & as if rather discontented, in fact as if she soon be put out, but in the evening, she looked better & more happy, her best aspect I suppose when smiling & talking.

She looks about the age of Miss Lockyer, & yet no cap.

She did not get much notice.

The two little Deveral girls were very nice little things, the 2 exactly like [Sophia Baker](../persons.html#1717) in face & manner & shyness. I cd have mistaken the two easily. I expect Mrs Dev. has rather agreeably surprised them, for they called her low church, & not a person of much interest, but she begged to be called in time & got up to breakfast at 8 to go to Church with us, tho at home she does not get up till 9 & examined the Church.

She is a fine looking woman, most splendidly dressed, & has projecting teeth like Lady G.

Bulteel & yet homely in some things & takes an interest in dabblying across to see the Turkeys, & says that what she likes to do.

My feet are cold, I’ll warm them here please, & seats herself with her feet on the fender, & was sending a bit or two from some tract on the corn laws, or state of parties or something of that kind, & then sd if you like hearing it, I’ll read it aloud, & did so to the end.

This has made me puzzled in my writing . . . first time I have had ridicule heaped on me for it.

This page is since we came in, Char & I took Mrs Dev: a walk in the Cranbury woods Does it seem old & dismal & winterish at home? I have my first Chilblain today.

It is no weather for curing coughs.

Many thanks for the habit shirt, you will see it was acceptable, the paper was rather crumpled but I do not think I shall be able to write it here. I hardly expect James will go [very small and illegible] pleased at John’s good news . . . .[illegible lines omitted]
Yr affect sister
Anne Yonge

[^1]: The Rev.

Dr.

Joseph Hemington Harris (1799/1800-1881) D. D., incumbent of Torre, near Torquay had married (1837) Jane Yonge (b.1796 ), sister of Rev.

John Yonge of Puslinch and of Elizabeth (Yonge), Lady Seaton.

They were no doubt in charge of the latter’s son Graham Colborne while his parents were in the Ionian Islands.

