---
date: '1849-11-01'
display-date: '[November or December 1849?]'
from-address: Otterbourne
manuscript-location: 'MS location unknown.  This fragment printed in C.A.E. Moberly,
  <i>[[otherbook:122]Dulce Domum: George Moberly, his Family and Friends]</i> (London:
  Murray 1911),  97.'
original-date: '2010-03-19 11:03:18'
title: To Alice Arbuthnot Moberly
wordpress-id: 2965
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Alice](../persons.html#1025)
I am glad you think ‘[St Barthelemy’s Fair](../books.html#35)’[^1] practicable. I shall very much enjoy doing what I can in the preparations, and I will try and grow as fat and dignified as I can in honour of her Majesty, Queen Philippa. I was almost afraid that there were too many characters, though I could not see how to manage with less.

We can furnish a real sword and spinning-wheel.

My notion of the King is in a long blue cloak, which we have here, and a fur tippet.

The object of this letter is to ask you and [Miss Cowing](../persons.html#374), and as many of the schoolroom party as the carriage will carry, to come in the afternoon and look at the illuminated illustrations in [Froissart](../others.html#219) and talk it over and see what can be done.

You cannot think how I shall enjoy the fun of the rehearsals, and it will give me such a good opportunity for correcting any part of the play that may not have the right effect.

[^1]: This play, written by CMY for the Moberly children to act at Christmas, was published as [The Mice at Play](../books.html#35) (1860).

