---
date: '1850-05-18'
display-date: 'Saturday [18 May 1850[[footnote:1]]] '
from-address: ''
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>,
  172-3]
original-date: '2010-03-19 11:14:22'
title: To Mary Anne Dyson
wordpress-id: 2966
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Driver](../persons.html#464)
The first thing I did when I opened your letter this morning was to laugh, it was so exactly what I had been thinking about before I was up, as far as regards [Guy's character](../books.html#15), for what I had been planning was to make the encounter with Martyn happen at Oxford, whither Martyn has volunteered to go to hunt up the supposed debts of Guy's. I mean Guy to have hazel eyes which when he is angry grow dark in the middle and flash (a traditional feature in the wicked ancestor), and when Martyn comes to his rooms with all these unjust suspicions and kind exhortations to confess and moralisings, it is almost beyond bearing, and he speaks in his tremendous tone of suppressed passion, and flashes with these eyes, and they part quite in a quarrel, Guy proudly refusing all explanation.

Then he repents, comes to Martyn's inn next morning, tries to make it up, but, as you say, Martyn fancies it is for fear of his making further discoveries, and is very ungracious, perhaps rather disappointed at the excellent character all the dons give of his cousin.

Guy is comforted by his humility though it is not accepted - I think his contrition should have the 'princely heart of innocence'[^2] following it.

But whether this would be more effective if Martyn interfered with the estate I don't know, perhaps it might considering what is to happen afterwards, and Martyn's remorse; but then, on the other hand, would it not hurt Guy more to think his cousin had been giving that grudging sort of character of him to the people at Oxford, and so be more of a trial? I had been devising his lonely vacation already, when he goes to Morville alone missing his grandfather a good deal, and fancying all sorts of things about the ghost and his destiny whenever he passes the ghost's portrait, and writing verses and thoughts, making in short a grand communing with his own mind which is a steadying of him.

He contemplates the living there alone,without Amabel, without much of the pleasures he has taken to, and sets his face to think it the safest way, and to give up happiness if he may but escape sin, and then his chief wish is that the Edmonstones should understand him, and Martyn, whom all this time he more than half admires, should be cordially his friend.

Then he takes heart and soul to his people, finds cottages wanting repair, etc., and writes to Mr.

Edmonstone about it.

Luckily Mr.

Edmonstone has just, though Guy did not know it, taken model cottages for a hobby, so he goes into an ecstasy, sends Guy a dozen plans once a week, and asks him to come to them the next vacation.

And then it is all right.

Oh further, Mr.

Edmonstone has the unlucky custom of showing his letters to whoever is by, and so, as he had shown Guy's letters to Martyn, he shows Guy a letter written by Martyn on hearing of his engagement to Amabel, one of Martyn's grand letters of good advice to his uncle, against being hasty about it, calling on him to observe that the question about the money has never been explained, and saying that he considers it as a great risk to give her to a man with Guy's temper, etc. etc.

At this, what Guy does is to give one of his eye flashes, which he cannot help, and say with a sort of smile, 'You should not show one such letters, Mr.

Edmonstone.' Then in that meeting which he sought in Switzerland, his eyes do not even flash, showing that the temper is conquered as well as the outward demonstration. I think Mr.

Edmonstone must be so inconsistent a man that the cottages really reconcile him to Guy, and he takes it all for granted and returns of himself to his former opinion of him when Martyn is not there to poison his ear, and Charles is saying all in favour of Guy; it would be quite as probable and more entertaining. I like your idea particularly of Martyn's softening being the one thing wanting to Guy's happiness, which is found at last, and I think it should be poetical justice on Martyn that his illness should leave his head so weak and incapable of thought that he feels himself quite unable to be of the least use to Amabel in her husband's illness, not even able to write a note or give an order for her, instead of making arrangements better than any one else.

Yes, Laura's faith in him never fails, nor has it any reason to do so, she only admired Guy as a novelty just at first, but never thought him really equal to Martyn, whose judicious arrangements seem to her unparalleled, and Charles is always laughing at her for this.
I have found out what the offence was that made Guy bang the door.

Martyn had been advising him to read with a tutor, the curate I suppose, to prepare for Oxford, which would have been all very well if Martyn had not proceeded to disparage Guy's former education, which nettled him.

He tells Mrs.

Edmonstone that 'Martyn had been giving him some good advice which he had been unreasonable enough not to take in good part,' and Charles tells him 'he knows what Martyn's good advice is.' But Martyn is surprised, and something between pleased and disappointed, when Guy acts upon this same advice forthwith, and speaks to Mr.

Edmonstone about the curate.

Also I think the suspecting him of gaming is a particularly cruel suspicion, because it is notorious among the Edmonstones that old Sir Guy had made him take a vow against it, and he will never even play at billiards even in their house, though not by any means thinking them wrong for other people. I fancy Guy a man who would cry over a story, and have all sorts of expressions he was not conscious of flitting over his face. I shall not send this till Monday, not because I think you will be like Mr.

Edmonstone and show it to [John Coleridge](../persons.html#343), but because I think you must want to rest from Guy on Whit Sunday at least, and so do I.

[^1]: Whit Sunday was 19 May 1850.

[^2]: Keble, ‘Sixth Sunday after Trinity’ in [The Christian Year](../others.html#95).

