---
date: '1850-05-24'
display-date: May 24, 1850
from-address: Otterbourne
manuscript-location: MS location unknown. This fragment printed in Coleridge, <i>Life</i>,
  175-6
original-date: '2010-03-19 11:20:57'
title: To Mary Anne Dyson
wordpress-id: 2967
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[no salutation]
I have taken a sheet of paper and turned [my dramatis personæ](../books.html#15) loose upon it to see how they will behave; at present the part of Hamlet is left out, that is to say, they have only got a letter from Guy announcing his grandfather's death. I find that Philip is greatly inclined to be sententious and that Charles likes to tease him by laughing at him, and mimicking his way of saying 'It is the correct thing,' Charles doing so like an idle boy, taking Philip all as goodness, but not liking that sort, and Amabel not able to help laughing at his ways of teasing Philip, though thinking it wrong all the time, which will suit her present merriment, and capacity of being moulded by Guy.

To be bright and buoyant with depth within should be her nature; a gay temper would be best for Guy in his lady. I like the cheating steward very much. I don't think Charles was in earnest enough before Guy came to take Philip as his Bild[^1]; it was Guy who made him in earnest, and by respecting Philip himself almost taught him to do so. I meant it to be a device of Amabel's to put Philip in good-humour to write to him to take their rooms, at which she laughs and makes her husband do so too.

On reading my first chapter I doubt whether Philip will not strike those who do not know him as intended for the perfect hero; I rather hope he will, and as one of those perfect heroes whom nobody likes. I have been reading Mr. [Hurrell Froude](../persons.html#529) over again; I am sure he is wrong when in that essay on fiction he says the author has no pleasure in it, and feels the events and people are under his own control.[^2] I am sure I don't, and what Guy and Philip may choose to turn out I cannot tell, and they seem just like real acquaintances. I think Guy wrote to Charles about the cottages, Charles never having given up his correspondence.

An idea has struck me about the flare-up with Amabel.

You hold that there is such a thing as innocent and proper flirtation; now I think, without understanding their own feelings, Guy and Amabel had very simply got into a very exclusive way with each other, which Mrs. E., afraid of the accusation of manœvring the young baronet, thinks best to check, and so just before some great out-of-doors party - a school-children's feast perhaps- she gives Amy a hint that it is more than is quite proper, which so frightens the poor girl that she shuns Guy as much as possible, will not walk with him, and by sticking fast to Laura somehow gets bestowed by Philip on his friend whom he has brought here, and thereupon Guy flashes at her.

She goes on for two or three days thinking it a duty not to walk in the garden with him or stay alone in the room with him, till the last day he is at home he catches her, tells her she is unlike herself, and demands an explanation; it ends in rather a confused way, but Amy has no doubt of his love for her, though don't you think he might almost tell her so?

He wants to feel himself a more settled self-depending character before engaging her or asking her of her father, and this confession had broken from him unawares.

She says she shall tell her mother after he is gone the next morning, and so she does, and Mrs.

Edmonstone thinks it best to leave it alone, as Guy is still not twenty, and not do anything either to lead to or break it off.

Do you think she would be justified in this?

Then come all the troubles which certainly prevent true love from running too smooth!

[^1]: The word is often used in CMY’s letters to Dyson to refer to the object of hero-worship.

[^2]: \'Composing a story is like reading one for the second time.

No one can feel much interest in the termination of events over which he himself has an absolute control.\' From the essay \'Is a rude or refined age more favourable to the production of works of fiction?\' in R. H.

Froude, [Remains](../others.html#98), I, 145-63.

