---
date: '1850-01-01'
display-date: '[1850]'
from-address: ''
manuscript-location: "MS location unknown.  Extract printed in Coleridge, [[otherbook:40]<i>Life]</i>\_\
  176-7"
original-date: '2010-03-19 11:42:03'
title: To Mary Anne Dyson
wordpress-id: 2969
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[To [Mary Anne Dyson](../persons.html#464)[Sir Guy Morville](../books.html#15) has just arrived at Hollywell, and Charles does not know whether to like him or not. I have got hard into the beginning now, but I believe some work at the [Landmarks](../books.html#14)  will be very wholesome for him.

You know his first confession of love was made at a time when all was going smoothly, and I should think the consciousness of the doom was not at all strong upon him then, though it revived in the days of his troubles and solitude. I am really getting fond of Philip, and mamma says people will think he is the good one to be rewarded, and Guy the bad one punished. I say if stupid people really think so, it will be just what I should like, for it would be very like the different morals caught by different people from real life.

Have you had the third volume of Southey yet?[^1] there is a most curious thing in it at the end about [Thalaba](../others.html#151), by which it appears that some one actually published a sketch tracing out the whole allegory of faith all through it.

Southey is pleased, but in a strange manner shows that he did not mean it, or even understand it when it was shown him! I am sure this seems as if poets themselves were not the composers of their works, and how strikingly it joins with the grand right parts of the old Greeks.[^2] And then in one of his letters about [Roderick](../others.html#222), he says he means to make Florinda kill Sisabert!

Good-bye to the calves for the present, and tell them they have my good wishes for happy holidays.[^3]
Your most affectionate
C. M.

Yonge

[^1]: [The Life and Correspondence of Robert Southey](../others.html#153) ed.

Cuthbert Southey 6 vols (London: Longman 1849-50). CMY refers to the last letter in the third volume (1850), p. 351, addressed to the Rev.

John Martyn Longmire (4 November 1812): \'My aim has been to diffuse through my poems a sense of the beautiful and good . . . rather than to aim at the exemplification of any particular moral precept.\' CMY is surprised by Southey\'s indifference to the allegorical interpretation of his poems because the Tractarians, especially Keble, laid emphasis on the power of poetry to teach by indirection and mystery.

As this part of the correspondence makes clear, her own fiction was written to be moralized by attentive readers.

[^2]: CMY seems to refer here to the idea that classical literature, despite being pre-Christian, might be interpreted as shadowing Christian truths. [Jay, ‘Tractarian Aesthetics’](../others.html#88), 51, cites [Keble’s Lectures on Poetry 1832-1841](../others.html#223) tr. E. K.

Francis (2 vols (Oxford: Clarendon Press 1912), 2, 314 , on this point.

[^3]: By \'calves\' CMY means the pupils at Dyson\'s school.

