---
date: '1850-11-01'
display-date: '[November or December 1850?]'
from-address: ''
manuscript-location: MS location unknown.  This fragment printed in <i>[[otherbook:122]Dulce
  Domum]</i>, 97.
original-date: '2010-03-19 13:04:52'
title: To Alice Arbuthnot Moberly
wordpress-id: 2974
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Alice](../persons.html#1025),
Would [George](../persons.html#1014) mind being the Colonel?

He is never on the stage with Edmund, and a cloak and blue scarf would turn him into a Roundhead. I do not see what else is to be done, for altering the part now would spoil the dinner scene. I am glad you are not more perfect in your parts. I say mine every evening when I am going to bed, but I cannot leave off laughing in the wrong places, especially when I have to congratulate Edmund on his alteration since I saw him six years ago.

Mr.

Dunderhead[^1] lives in the little dressing-room, to the amazement of all beholders who come suddenly upon him in the twilight.

[^1]: Dated on the assumption that \'[The Pigeon Pie](../books.html#34)\' succeeded \'[The Mice at Play\'](../books.html#35) as the Moberlys\' Christmas play. \'When \'The Pigeon Pie\' was acted, [Mrs.

Yonge](../persons.html#1606) made a lay figure to represent a soldier, which went by the name of Zedekias Dunderhead, and George gave much trouble by resolutely refusing to act the part of the Roundhead colonel, so Mrs.

Yonge had to take it herself.\' [Dulce Domum](../others.html#122) 96.

