---
date: '1851-10-18'
display-date: Oct 18th 1851
from-address: ''
manuscript-location: 'MS Huntington Library, Yonge Letters. '
original-date: '2010-03-19 13:22:21'
title: To Elizabeth Roberts
wordpress-id: 2978
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

[Madam](../persons.html#1243),
I am much obliged by your contribution to the [Monthly Packet](../others.html#52), and should be glad to see the other numbers. I must observe however that there are some expressions that had a childish tone that I would gladly see altered such as that the loss of Lucien’s parents was very sad for him, that Hilary wrote clever books, that his Psalms are the same as ours, that a priest is a clergyman &c. [Alban Butler](../others.html#27) also says that Prisca was a virgin martyr at Rome in the 3d century and that her name is connected with that of Aquila’s wife only because there is a tradition that the Church dedicated to her at Rome is built on the site of the House of Aquila.

Sts Aquila & Priscilla are commemorated together by the Greek church on the 14th of July.
I like your plan very much and if you are kind enough to let me have the rest of the papers before the end of next month, I should like to commence them with the New Year, but I find it a good rule not to commence a series without seeing the whole of it
I remain Yours &c
The Editor of the Monthly Packet

[^1]: The MS is accompanied by a small envelope with stamped circle enclosing daisy-like flowering plant on the flap, addressed to Miss Roberts/ Diamond Cottage/ Wetheral/ Carlisle.

