---
date: '1852-06-10'
display-date: June 10th [1852]
from-address: Otterbourn
manuscript-location: 'MS Huntington Library: Yonge Letters '
original-date: '2010-03-22 08:43:48'
title: To Elizabeth Roberts
wordpress-id: 2992
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Madam](../persons.html#1243),
I think there would be time for the two flowers if you have them ready, and like to send them at once to Derby. I will write and tell [Mr Mozley](../persons.html#1065) about them, in case you should like to do this. I was much delighted with the account of the Peacemaker, St Elizabeth of Portugal, in Miss Kavanagh’s [Women of Christianity](../others.html#91), and I am glad that she has so pretty a flower as the Evening Primrose.

As to the bright little Centaury, everyone must be glad to hear of it.[^1] One of my cousins asked the other day if I knew anything of the Anthericum Liliago, St Bruno’s flower, which she said was pretty, and had a bulbous root, but I cannot find anything about it from my books.

Thank you for the translation, it is certainly a very beautiful passage.

Should you object to my introducing it in one of my [Conversations on the Catechism](../books.html#33).

Miss Ormesden might give it to the girls to read, and I think it would come in very suitably with my next subject ‘Death and Burial,’ which I suppose will come out on the 1st August. I meant to make ‘Death and Sleep’ follow the conversation, as the ‘Olive Garden’ does the former one, for your papers have a curious way of coming in à propos to mine. I sometimes wish I had called those conversations in Illustration of the Catechism, which I think would express their object better. I hope to be able to get a Post Office order on Saturday, but we are four miles from Winchester and I cannot always send. I am afraid what you say of [your Bishop](../persons.html#1726) is to be said of too many, it is a very difficult thing to know how to feel about those who are over us.[^2] Here, though all is [not exactly as we could wish](../persons.html#1383) in that respect, we are so happy in our neighbouring clergymen as to have little occasion for any thing but thankfulness.[^3] You would have been interested by the sight of the Whitsuntide adornings of a Church near us, all white flowers, except here and there a red peony.

Lilies of the valley at the east, and more towards the west, white broom with laurel leaves, which had a beautiful effect, even when I saw it on Whit Tuesday when it was much faded.

With many thanks

Yours sincerely

C M Yonge

[^1]: Erythraea centaurium (Pers.).

[^2]: The Hon. and Right Rev.

Hugh Percy (1784–1856), bishop of Carlisle from 1827 to his death, was unpopular and eccentric.

[^3]: The Rt.

Rev.

Charles Sumner (1790-1874), bishop of Winchester, was evangelical.

