---
date: '1852-10-04'
display-date: Oct 4th [1852]
from-address: Malvern
manuscript-location: 'MS Huntington Library: Yonge Letters'
original-date: '2010-03-22 09:59:28'
title: To Elizabeth Roberts
wordpress-id: 3000
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Madam](../persons.html#1243)
I cannot deprive myself of the pleasure of telling you if you have not seen it yet, to look at the Notice of the [Garland](../others.html#225) for the year in the [Christian Remembrancer](../others.html#59), I received it yesterday, and was very much pleased with it.
I have, like you had a fortnight’s illness & idleness, ending in a holiday to visit some merry cousins here.[^1] This morning I have had the great pleasure of a good look over Worcester Cathedral, I cannot think it equal to Winchester or Salisbury, but there are some most interesting monuments, the good Bishop Wulstan especially delighted me, and the Saints and heraldic devices on Prince Arthur’s occupied us a long time. I am sorry it is too late to botanize here, I hear such an account of the flowers.

We leave this place on Thursday, and if in the course of the week after you are kind enough to send any additional flowers, please to direct to me at the
Revd [Charles Dyson](../persons.html#461)’s
Dogmersfield Rectory
Winchfield
The letters are called for

Yours sincerely

C M Yonge

[^1]: A reference (14 Dec 1853) to the good [Edmund Colborne](../persons.html#322) had gained at Malvern suggests the possibility that all the Colbornes had gathered there.

