---
date: '1853-01-15'
display-date: January 15, 1853.
from-address: 'Otterbourne, '
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  188
original-date: '2010-03-22 10:30:51'
title: To Mary Anne Dyson
wordpress-id: 3006
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Marianne](../persons.html#464)
If the maids had not an evil habit of keeping the arrival of a parcel a secret for some hours, I should not have let the dear [Guy](../books.html#15) go without note or comment, but we never heard of him till just as we were starting for Winchester, when I wrote his mother's name in the first that came out, and carried him off. I hope she has had him by this time, and that she is satisfied with the son she gave me to educate, who has been one of my greatest pleasures for two and a half years.

On that same day I took the first step to sending you my daughter for the same purpose. I spoke to [Mrs.

Collins](../persons.html#360), who was much pleased, but her heart is so full of [George](../persons.html#1730) that I was edified by the comparative value of a son and daughter.[^1] She was very nice about it, when I said Miss Dyson chiefly cared for their being well brought up at home, and that I was sure of that with [Bessie](../persons.html#358). ‘Yes, to be sure, we do try to teach them our best, as far as we know, and I don't think they have ever heard anything bad, and that was what [Mr.

Fielder](../persons.html#510) said about George, he wouldn't mind having him with his own children.’ I thought you would be glad of that voluntary testimony, coming out of the fulness of the heart, and quite forgetting it was to recommend Bessie.

She will be going on the 24th of July, and her mother says, ‘she will be happy, for she does not mind being away from home.’ However, as her visits have been made with her grandmother, I would not answer for the felicity at first, but I like to think it is in train. I send ‘St.

Margaret’ on approval; you see she is quite to the level of the[ Pink](../others.html#79).[^2] I will make an exhortation to [Miss Mozley](../persons.html#1061) to put it in as soon as she can; I told her it was coming when she sent me some pay the other day. I suppose you are parting with [Miss Lefroy](../persons.html#864)--[^3] wasn't she to go on Saturday?

Is the Old Man come home? I hope he was not too much tired. [Slave's mother](../persons.html#1606) says she enjoyed insulting you with the Morning Herald, which she had done up before Guy came in propriâ personâ.

Your most affectionate
C. M. Y.

[^1]: The Collins family seem to have consisted of Martha (Andrews) Collins (b. 1805/6), postmistress, wife of George Collins, (b. 1818/9) of the Post Office, Otterbourne, groom and gardener, and their children George (b. 1839/40), Charles (b.1840/1), Elizabeth (b. 1844/5), and Anne (b. 1846/7). CMY probably subsidised Bessie’s attendance at Mary Anne Dyson’s school, for her bank account shows regular payments at this period.

In the 1861 census Bessie Collins was housemaid to the Rev.

Cyril Wood, Vicar of Atwick and in the 1871 census housemaid to the Rev.

John Le Mesurier, Vicar of Bembridge.

[^2]: The “Pink Mag” was her nickname for the Magazine for the Young, edited by Anne Mozley.

[^3]: Probably Fanny Caroline Lefroy (1820-1885), great-niece of Jane Austen, who contributed to MP between 1855 and 1884.

