---
date: '1853-07-01'
display-date: '[July 1853]'
from-address: ''
manuscript-location: MS location unknown.  Printed in <i>[[otherbook:122]Dulce Domum]</i>
  106-7.
original-date: '2010-03-23 11:45:10'
title: To Alice Arbuthnot Moberly
wordpress-id: 3013
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Alice](../persons.html#1025),
The Times was quite right, [Lucien](../persons.html#1733) was at the camp,[^1] though I cannot remember him. [Montebello](../persons.html#1735) told [Lord Seaton](../persons.html#313) that he is very sorry to see our troops in such excellent order. [The Queen](../persons.html#1694) looked in great good-humour, and was determined to see the men have their dinner.

She came to Virginia Water with [Prince Albert](../persons.html#1736), who was sneezing and looking as if he had the measles.

Lord and [Lady Seaton](../persons.html#314) are at the Palace again to-night.[^2] They have a great luncheon in marquees to-morrow.

So much for camp news. . . .We have had a famous party from Fieldhouse; you should have seen [Robert](../persons.html#1021), [Johnnie](../persons.html#1017), [Emily](../persons.html#81)[^3], and Rover all at tea at the little round table. I wish you could have been at Hursley yesterday.

We had a nice sight of the [Bishop](../persons.html#578) and [Mrs.

Gray](../persons.html#579)[^4] in the Vicarage after service, and Mrs.

Gray brought down some beautiful drawings of the Table Mountain . . .

[^1]: In May 1853 an armed camp on Chobham Common, commanded by Field-Marshal Lord Seaton, was set up. CMY herself visited it with several of her cousins.

The Times (4 July 1853) reported manoevres witnessed by the Queen, Prince Albert, the visiting Prince Lucien Bonaparte (1813-1891) and officers in his suite, who probably included Napoléon, second Duc de Montebello (1801-1874).

[^2]: There had been a State Ball on 1 July 1853.

[^3]: Robert Campbell Moberly (1845-1903), John Cornelius Moberly (b.1848 ) and Frances Emily Moberly (1844-1921).

[^4]: The Bishop of Cape Town, the Rt.

Rev.

Robert Gray (1809-1874), and his wife Sophia (Myddleton) Gray were visiting the Kebles.

