---
date: '1853-01-01'
display-date: '[late 1853?]'
from-address: ''
manuscript-location: 'MS fragment West Devon Record Office Acc No 308: 1853/3'
original-date: '2010-03-23 13:35:45'
title: To Anne Yonge
wordpress-id: 3015
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

enjoyed his two visits very much, though after all he missed Johnny Colborne.

Have you had to talk to your princes, it is very funny to think how little we should have believed it if seven years ago we had been told they would be coursing at Puslinch.[^1] [John Coleridge](../persons.html#343) spent half Sunday here, and brought the American magazine with the account of the clergyman who is said to be Louis XVII, it is very curious and really when you read it, vraisemblable, it is franked by his Bishop who says he is a most hard working excellent clergyman.

He had quite lost his memory and had not the least notion who he was till the Prince de Joinville told him.

We were at Winchester yesterday, and[ Jane Wither](../persons.html#1743) shewed us a nugget of gold that had been sent her by some emigrants she helped out to Australia.

It weighed ½ oz, was worth 30/- and looked like the inside of a walnut gilded.

Poor Catherine’s history sounds like a story on the consequences of seeking fine places.

Her mistress fills one with such indignation that I am ready to write a Packet article against selfishness. [Mary Moberly](../persons.html#1020) told me her birthday was the same as[ Guy](../books.html#15)’s so there is another like yours.[^2] I have no time for more
your affectionate cousin
CMY

[^1]: 404 The Times (25 May 1853) reported that the Orleans family had been residing at Kitley, near Plymouth.

The Kitley estate, which neighbours Puslinch, was the home of the Bastard family.

After the revolution of 1848 Louis Philippe and his family sought refuge in England, where he died in 1850.

He and his wife [Marie Amelie](../persons.html#1737) (1782-1866) were accompanied in exile by their son Louis, Duc de Nemours (1814-1896) and his wife, Princess Victoire of Saxe-Coburg (1822-1857), their daughter-in-law, the Duchesse d’Orleans (1814-1858), widow of their eldest son, and her two children the [Comte de Paris](../persons.html#1741) (1838-1894) and the [Duc de Chartres](../persons.html#1742) (1840-1910).

[^2]: Mary Louisa Moberly (28 March 1838-1859)

