---
date: '1854-02-01'
display-date: Febry 23d [1854]
from-address: Otterbourn
manuscript-location: MS Plymouth and West Devon Record Office 308/257
original-date: '2010-03-25 12:26:33'
title: To Anne Yonge
wordpress-id: 3027
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Anne](../persons.html#1582)
[Mamma](../persons.html#1606) is writing to [Uncle James](../persons.html#1614) so I think [Puslinch](../others.html#123) must hear at the same time otherwise I should like to save [Uncle Yonge](../persons.html#1623) the anxiety.
[Papa](../persons.html#1631) has been over working himself with spending whole long days without dinner upon [Julian](../persons.html#1624)’s preparations, and yesterday after going to Portsmouth to take leave of him, and coming home very late, a sort of seizure came on like an exaggerated headache.

We sent for [Mr Lyford](../persons.html#911) who cupped him and that much relieved him, and we hope he is better today, able to speak and recollect but with a very bad headache. poor Julian he was able to come home today by 1 o’clock but he must go at five to sail tomorrow. I hope he will take a better account away with him for he cannot hear again till he gets to Malta.

It came on about ten at night and was better so that Mr Lyford went by half past two.

Mamma did very well all night, and was not so very much frightened.

Mr Lyford seems to make sure of his being better tomorrow. I will tell you if there is any more to say before post time.
your most affectionate
CMY
It is better. I began my letter while there was a flushed face that made us uneasy, but that is gone off now, and he has been mending all day, but we have not ventured to let him see Julian, who only looked at him asleep.

The attack is certainly passing off and they promise us he shall be much better tomorrow
