---
date: '1854-03-09'
display-date: 9th March 1854
from-address: Otterbourn
manuscript-location: MS Plymouth and West Devon Record Office 308/256
original-date: '2010-04-12 10:04:22'
title: Frances Mary Yonge to Mary Yonge
wordpress-id: 3034
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I hope this mild day is doing every thing for [your father](../persons.html#1623)’s cure, I wish more for his own sake than [mine](../persons.html#1606) that he could have been here, but the necessity of allowing half the county to shew their respect made it much more trying to the family.
I seem to be out on a visit, and I do not know how I shall get on when we resume our old habits. [Anne](../persons.html#1582) is a very very great comfort and I am employing her this morning in writing for me which saves both me & Charlotte and at walking time she is invaluable. [Duke](../persons.html#1599) has done us a great deal of good and we thank him for giving up so much time to us. I have desired Duke to get a full explanation from [Harry Mason](../persons.html#1750) of his views about the Wheat, and your Father will advise us accordingly.

It does seem so strange to me to give orders. I have hardly got to think myself mistress of the house in the place of my [Mother](../persons.html#103), and now I have not only to try & do my best, but to avoid the danger of being too much engrossed in my wish to keep things from going to ruin, and I try to keep Charlotte from what I most dread for her, the forlorn feel on those evenings the pleasures of which you know so well, and how she enjoyed them.

Poor [Julian](../persons.html#1624) I cannot write about him till his letters come.
your affect
F M Yonge

[^1]: Black-edged paper.

