---
date: '1854-03-21'
display-date: March 21st [1854]
from-address: Otterbourn Winchester
manuscript-location: MS Princeton University, Parrish Collection, C0171 Box 29
original-date: '2010-04-14 11:04:29'
title: To John William Parker, Jr.
wordpress-id: 3037
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear[ Sir](../persons.html#1143),
There are a few slight corrections of the [‘Heir of Redclyffe](../books.html#15)’ which I will send in a day or two. I am glad to learn that this edition has sold off so well, but I think we should take it into consideration whether it might not be better still further to lessen the price. I have been much urged by influential persons to publish a large and really cheap edition, such as would fall into the hands of a more extensive class of purchasers, and this would certainly well accord with my own views. I see that Lady Catherine Long’s ‘[Sir Roland Ashton](../others.html#107)’[^2] originally a three volume novel is now published at 2/ and the great sale that books thus cheaply printed obtain would seem to point this out as a desirable measure now that the work has become known
I remain
Yours faithfully
C.M.

Yonge

[^1]: Black-edged paper.

[^2]: Sir Roland Ashton: A Tale of the Times (1844), an anti-tractarian novel by Lady Catherine (Walpole) Long (d. 1867).

The edition referred to was advertised in The Times (10 March 1854), 13.

