---
date: '1854-06-05'
display-date: June 5th [1854]
from-address: ''
manuscript-location: 'MS Huntington Library: Yonge Letters'
original-date: '2010-04-19 12:15:05'
title: To Elizabeth Roberts
wordpress-id: 3046
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Roberts](../persons.html#1243),
I have nothing to say in excuse for myself, but that somehow I had the impression of having written to thank you for the two last [Cathedrals](../others.html#244), so that between putting off at first and forgetting after wards, it has been neglected, and I am very sorry for it.

We read them at the time with much interest and I shall be glad to use them when the time for them comes.

Your [Ramble in the Heather](../others.html#245) is very pretty and fresh, and there is always a new interest in botanical sketches where each observer speaks for herself. I have some papers on botany for present use however and fear that I must defer these likewise until next year, so as not to give too much on the same subject.

Welsh names are so poetical when translated that I should think them a great addition to [the Garland](../others.html#225), which I hope still may some time or other find its way to the world I forget whether I answered your question about the Glastonbury thorn, it is like an ordinary hawthorn in all but its budding at Christmas, a fashion followed by all its grafts. I hope better days may some day rise before Wales.

Earnestness would I suppose do great things there as else where, and these are above all things, days in which not to ‘shrink and say t’is [sic] vain’[^2], and I hope in a day or two to see one of those sons of the Church who best shews forth the living and working power. [Bishop Selwyn](../persons.html#1295) is to be at Winchester on Wednesday, and hearing as we have done of all his labours among the isles of the sea, it is almost like seeing one of the mighty men of old, there is a practical hard working spirit in his doings that is good to set before the world.

To contrast Church matters with what they were twenty years ago shews us how much has been done, and how true and living is the grace within our Church working unto the end.

But as four little girls have just walked in to drink tea, I must finish

Yours sincerely

C M Yonge
What will you think of me, I have mislaid your address and must direct to Carlisle

[^1]: Black-edged paper.

[^2]: John Keble, ‘The Gathering of the Church’, l.1.

