---
date: '1854-06-01'
display-date: June 1854.
from-address: 'Otterbourne, '
manuscript-location: MS location unknown.  Printed in <i>[[otherbook:122]Dulce Domum]</i>
  112-3.
original-date: '2010-04-19 13:03:58'
title: Frances Mary Yonge to Alice Arbuthnot Moberly
wordpress-id: 3047
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Alice](../persons.html#1025),
The [Warden](../persons.html#118) has asked Charlotte and [Anne](../persons.html#1582) to dine there to be ready for the evening meeting; but at all events they will come to you first, about 10 o'clock, to go with you to the Cathedral.

You would have enjoyed a walk with us last evening in a part of [Cranbury](../others.html#119) quite unknown to us, where we found some beautiful lady-fern and a dragon-fly surpassing in beauty.

And so the dear people did come to us, [Mary](../persons.html#1020), [Dora](../persons.html#968), [Emily](../persons.html#81), and [Annie](../persons.html#1024), and we are only just come from walking to meet [Miss Cowing](../persons.html#374)[^1] and the rest.

Charlotte sends all that is finished of '[Heartsease](../books.html#19),' and has no doubt there will be more by the time you are ready for it; she is numbering the pages with red, in case they get wrong. I do think [Mrs.

Moberly](../persons.html#1019) will enjoy little John Martindale, even more this time than before. [Miss Keble](../persons.html#796) is very fond of him.

[^1]: Jane Cowing (b.1807/8), the Moberlys\' governess.

