---
date: '1854-07-14'
display-date: July 14th [1854]
from-address: Otterbourne
manuscript-location: 'MS Historical Society of Pennsylvania: Gratz Collection: Case
  10, Box 36. British Authors.  Printed by Green, [[otherbook:75]\''Two Popular Novelists\''].'
original-date: '2010-04-19 14:25:21'
title: To John William Parker, Jr.
wordpress-id: 3050
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#1143),
I hope you will receive "[Heartsease](../books.html#19)” tomorrow, as I shall send it by the South Western early in the day. I shall be glad for it to appear in the same style as the first edition of the [Heir of Redclyffe](../books.html#15) but I do not think the volumes will be quite so large.

You do not say what number you propose to print, I suppose not fewer than 1500 or 2000. I shall be quite ready to correct the proofs.

One of the mottoes of the chapters was supplied from [Mr F Tennyson's poems](../others.html#167) which you kindly sent me, and which arrived just as the lines were needed.

I am glad to hear that the 4th edition of the Heir of Redclyffe has sold off,[^1] I hope the cheap one may meet with equal success.

Yours faithfully
C. M.

Yonge

[^1]: Presumably dated 1854.

The 5th edition is dated 1854.

