---
date: '1854-07-19'
display-date: July 19th [1854]
from-address: Otterbourne
manuscript-location: 'MS Historical Society of Pennsylvania: Gratz Collection: Case
  10, Box 36. British Authors. Printed by Green, [[otherbook:75]\''Two Popular Novelists\'']. '
original-date: '2010-04-20 09:16:39'
title: 'To John William Parker, Jr. '
wordpress-id: 3051
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#1143)
I am much obliged by your sending me the account of ‘[The Little Duke](../books.html#20)’ and the accompanying [£100](../others.html#160). I should be glad if, in sufficient time beforehand, you would be kind enough to tell me your opinion with regard to a second edition, and whether it would be advisable to renew it in the present form, or to have one much smaller and cheaper.

I have also to thank you for ‘[The Plurality of Worlds](../others.html#179)’, I had seen the first edition of that remarkable book but I am very glad to possess this with the additional matter at the commencement.

I suppose 400 pages will not make the volumes too large. I do not know whether the printer has taken into account that most of the latter part of the M S is written less closely than the earlier portions

Yours faithfully

C M Yonge
