---
date: '1855-12-01'
display-date: '[December 1855]'
from-address: ''
manuscript-location: MS location unknown.  This fragment printed in <i>[[otherbook:122]Dulce
  Domum]</i> 123
original-date: '2010-04-22 11:23:38'
title: To Alice Arbuthnot Moberly
wordpress-id: 3076
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Here are the last three [chapters](../books.html#24); I think the others had better come by post.[^1] When it comes back, it is to be added that Margaret gave her pearl ring to be worked into the chalice. I have gone into correspondence with College Street about Miss Bracy. I realised that it was necessary to be careful what was said, but did not suspect danger in that quarter.[^2] I know two good women together can argue each other nearly to death if they will not stop themselves. [Tom Thumb](../books.html#21)'s last proof goes by to-day's post, and in the '[Landmarks](../books.html#28)' I killed Louis XIV this morning. A great weight off my mind the old gentleman seems.

[^1]: The MS in progress of The Daisy Chain (1856).

[^2]: The Moberlys lived in College Street, Winchester.

Miss Bracy is a character in The Daisy Chain, a tiresome young governess who is always imagining slights from her employers.

Evidently CMY feared the Moberlys\' governess [Jane Cowing](../persons.html#374) might take offence. CMY had probably written to [Alice](../persons.html#1025)\'s mother [Mary Ann Moberly](../persons.html#1019).

