---
date: '1856-03-17'
display-date: March 17th [1856]
from-address: Otterbourn
manuscript-location: 'MS University of Illinois, Urbana Champaign: Letter 8.'
original-date: '2010-04-22 12:10:10'
title: To Jemima Blackburn
wordpress-id: 3080
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Blackburn](../persons.html#159),
I condole with you on the loss of your chicken and hope the other will not follow it at the critical moment of putting out the wing feathers. I am afraid the [ Empress](../persons.html#1771) has no such good amusement, and probably the [Imperial prince](../persons.html#1772) is much too grand a personage for her to be allowed to touch him.[^1] I never read anything more absurd than the account of his 144 garments of every description. I wonder whether he will really be kept in white and blue till seven years old.
I hope you have your [Daisy Chain](../books.html#24) which I desired to be sent to you, but [young Mr Parker](../persons.html#1143) being abroad, and [his father](../persons.html#1144) having the gout, I don’t feel as sure as usual of such things being attended to.

If you have not received it, I will send you one, it is a great big book, and I think you will like Harry and the Doctor, but you will find more sick folk than you approve.

Don’t you think there are two sorts of girls by nature as well as by art - boy-girls, and girl-girls - the boy-girls shouting, tearing frocks, hating needles, and being ultra boys till such time as the feminine instinct begins, the girl-girls always being thorough women in gentle tastes. I don’t think education makes the two natures transferable, though it comes to much the same in the end; As it does with boys - whom I have generally seen more timid than girls though more blustering, when small.

Indeed I have only met with one boy under 9 who was not an arrant coward at heart, which has persuaded me that courage is chiefly strength in boys, while in girls, I believe much is a latent consciousness that womanhood is a protection at least from anger.
I never told you how much I like [Dorothy](../others.html#43), there is something very live about her, and Lance is very good as much as there is of him.[^2] I don’t think the Colonel could have married her at his own gate; but it is a pretty bright book.
I hope you are out in the world again - how lucky you are to have been laid up now rather than in an available time of year.

How does the Palissy pottery get on?

Yours sincerely

C M Yonge

[^1]: Eugénie Marie de Montijo (1826-1920) married Napoleon III in 1853, the year after the Second Empire was declared.

Their son, Eugène Louis John Joseph Bonaparte, was born on 16 March 1856. the day before this letter was written.

[^2]: Dorothy: A Tale (1856) was the first novel of [Margaret Agnes Colvile](../persons.html#1157) (1829-1905), first cousin of Jemima (Wedderburn) Blackburn.

Their fathers, Andrew Colvile né Wedderburn (1779-1856) and James Wedderburn (1782-1822) were brothers.

