---
date: '1856-05-19'
display-date: May 19th [1856]
from-address: Otterbourn
manuscript-location: MS Mrs Caroline Fairclough/7
original-date: '2010-04-22 12:16:41'
title: To Anna Butler
wordpress-id: 3082
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Butler](../persons.html#237)
Many thanks for the chapter of [Likes and Dislikes](../others.html#248), which brings out Emilys moral very satisfactorily. I should not like it to be the absolute last, and should quite wish to continue her history after an interval.

How would it be - if we were to continue the story next July year - if we may venture to look so far forward, and if it do not suit you better to publish it all together sooner, in which case I should by no means wish to stand in its way. I should like to see the 15th chapter very much, in fact we are all greatly interested in Helen and Emily and I think they have had great success in the Packet.

We are hoping for [Elizth Barnett](../persons.html#113) on Wednesday, and trust to be in full nightingale form for her. I am sorry [Miss Dyson](../persons.html#464) is laid up with such an attack of tooth ache

yours sincerely

C M Yonge
By the by it has never been explained how the Baroness became lame
