---
date: '1856-11-04'
display-date: Nov 4th [1856?]
from-address: '[[other:121]Dogmersfield]'
manuscript-location: MS Hampshire Record Office 9M55F55/4/1
original-date: '2010-04-22 13:27:10'
title: To Anne Sturges Bourne
wordpress-id: 3087
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Bourne](../persons.html#1379)
To answer while the observations are fresh. 1.

Lord Ormersfield was meant to be courteous & respectful with his aunt, but undemonstrative, and I cannot fancy him saying ‘Aunt’ - though he would talk of my aunt.
2.

Mrs Frost was a woman who went by feeling, and only disposed to work for her son, & bask in his presence.
3.

Louisa’s health was so broken that no one expected her to survive her confinement. I wanted to make all this past sketchy, and thought specifying would run to lengthiness.
4.

Jem knew as little as Louis of minutiae of the speculations, and all Louis says was gently said, and misplaced partly because a man who talks so much must often talk amiss.

Things were a real pain and grief to him, & his father’s coldness made him not know that what he said was felt.

Of course it was meant to be wrong, but the meek quiet manner was not brow beating. 5.

Lord O was married two years - his father and mother were then alive.

Mary first saw Louisa in London, M then with Mr P, afterwards she was at Ormersfield, he gone on some mission, when she nursed Louisa. I meant the old people to live in the country, the young ones to come down to them, but of course as she hated it, and he was in office that would not come to much.

As to the spelling, I must have been under a delusion.
6. I don’t think women like Mrs Frost whose heart has always been in boys do enter much into girls’ habits, I don’t think she quite knew when Clara was not to be treated like a boy, and Jem’s restlessness about it made her petting propensity protect Clara from his restrictions. I think delicacy & unsuspicion hindered her from fears of Clara being attached to Louis, I always meant her forte to be heart, & not judgement. I will look at all the ambiguities. I daresay shortening has left plenty.
5th.

Your further note is come. I think the Clara part is all settled by that former observation that Mrs Frost was not as wise as kind, and Clara would not take to Mary.

It was the one unworthy spot in Lord O, warned by his own misfortunes, to wish his son to marry for happiness, and Mary had connections and fortune enough to make it not too heroic - in fact that was the heart’s core of the story.

Tom was to blame, for he broke off doing the steps out of affront with Jem’s fault finding - and Charlotte received no message to deliver only a confidence.
I send the end. I believe the law is all wrong, and Isabel is not enough made out at her first appearance. [M A](../persons.html#464) is writing, so I need say no more but thank you. I think what has no real magnanimity made a great impression on Tom

Yours sincerely

C M Yonge

[^1]: With envelope (MS 9M55F55/3/3) addressed to Miss Sturges Bourne/ Testwood/Southampton, postmarked Winchester 5 November [year indistinct] and labelled ‘Dynevor Terrace’ and ‘1860’.

However, the year date on the postmark looks more like 1856, which is more consistent with the letter, which seems to have been written before the publication of [Dynevor Terrace](../books.html#27).

