---
date: '1856-12-01'
display-date: Decr 3d [1856]
from-address: Otterbourn
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1856/2.
original-date: '2010-04-22 13:45:43'
title: To Ann Maria Carter Smith
wordpress-id: 3088
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Madam](../persons.html#263),
I cannot deny myself the pleasure of writing to tell you how much your [Thorns and Roses](../others.html#253) have already elicited of admiration. [^1] [One of my best contributors](../persons.html#1397) ([the School Sketches](../others.html#256)) has written this morning ‘you must let me say how much charmed I & all here are with the beautiful tale, Thorns &c Is it a secret absolutely whose authorship it is, or is it permissible to ask whether it is by a young writer untried before.

If so, we may hope for much more.’
I did not give up your secret, but I am sure you will not dislike reading the enquiry.
I heard too this morning that [our neighbour](../persons.html#669), a distinguished M. P. sat up to finish it, and was greatly pleased with it. I am hoping soon to begin [Wishop Rectory](../others.html#257).

Meantime I shall have the pleasure of sending you £6 for your three papers inserted this year - and [Miss Frances Smith](../persons.html#71) £2.. 2.. 6.[^2] Perhaps it would save trouble if I were to include both in one cheque, but I will wait to hear from you or from her.

With my best thanks to both - and hopes for future hope of the same valuable kind

yours truly

C M Yonge

[^1]: Thorns and Roses in a Homely Life, by A.C. D. , had appeared in [MP](../others.html#52) (December1856).

[^2]: Carter Smith\'s sister Frances Hester (Carter Smith) Atkinson contributed a series of papers on \'[Traditions of Norway](../others.html#258)\' to MP.

