---
date: '1857-06-13'
display-date: June 13th 1857
from-address: ''
manuscript-location: 'MS Princeton University: Parrish Collection, C0171: Box 29'
original-date: '2010-04-26 10:40:20'
title: To Miss Moorsom
wordpress-id: 3100
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Moorsom](../persons.html#1053)
I wrote to the [author](../persons.html#1243) of the [Garland of the Year](../others.html#225) in case she should be able to help you to any authorities for the Oxalis, but I have an answer from her this morning saying that it was one of the very few flowers which she described at second hand, but she has written to the person who helped her to try if she can recollect what book she found it in, in the library of the British Museum, rather a wide field it must be confessed! I have been looking in [Mrs Loudon’s perennials](../others.html#108), but I cannot find it there, and I should think the index to some gardening magazines was your best chance.
I can send you a very good account of all our neighbours here. [Mrs Keble](../persons.html#795) is nearly at her best, and the [Moberly](../persons.html#1015)s are all brilliant, the school room party have just migrated to the farm, where we join them on Monday while the house is being painted.

Perhaps you have not heard that the [Peter Young](../persons.html#1636)s are gone to a curacy near Totness a district of Dartington parish, a great loss to us all, excepting in Church music, for [Mr le Geyt](../persons.html#856) his successor has a very fine voice, and has made a great improvement in the Choir.

If any thing satisfactory comes to light on the Oxalis subject I will write again

Yours sincerely

C M Yonge
