---
date: '1857-07-10'
display-date: July 10th 1857
from-address: ''
manuscript-location: MS Winchester City Council, Historic Resources Centre LH3800
original-date: '2010-04-26 11:19:36'
title: To Emma Butler
wordpress-id: 3104
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Butler](../persons.html#240)
Please to consider this note as coming from [Mr](../persons.html#798) and [Mrs Keble](../persons.html#795), as they are very anxious to get this woman’s petition[^1] signed as universally and numerously as possible before the end of next week, when it should be returned (with a tail of names on the ruled lines, and on further sheets gummed on beyond if necessary) to Mrs Keble.

The name of the place to be written at the top of each district, and people’s husband’s or father’s professions after their names.

It is supposed it may have an effect as the Woman’s petition about the Wife’s Sister certainly did.

If you think of any other quarters to which to send them, please apply to Mrs Keble for them, as she keeps the store

yours sincerely

C M Yonge

[^1]: A bill to allow marriage to a deceased wife’s sister was first presented to the House of Commons in 1850 and finally passed in 1907.

The present petition probably related to the Matrimonial Causes Act 1857, which simplified the divorce process, and to which Keble was strongly opposed.

