---
date: '1857-10-01'
display-date: Thursday 1st Oct [1857]
from-address: R. Hospital
manuscript-location: MS Plymouth and West Devon Record Office  308/78/12
original-date: '2010-04-27 09:54:09'
title: Anne Yonge to Mary Yonge
wordpress-id: 3110
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626),
It is a great undertaking to describe accurately so great a wedding, a great deal of the details [I](../persons.html#1582) must reserve until I get home, but I was surprised to find that anything so ponderous cd be passed thro so quietly & easily. [Aunt Seaton](../persons.html#314) even seemed in not the least bustle & everything was arranged like magic; I suppose from the number of workmen & the abundance of payment.

The suite of rooms we occupied form one side of the Quadrangle, & I will show you how they come. [sketch] People enter thro the passage drawing room, but I have not left space enough for the snug pretty little drawing room on the other side of it, the one [Capt M.](../persons.html#1041) & [Jane](../persons.html#1042) have had for their sitting room, & where we all assembled to wait.

Aunt Seaton had charged [Uncle Seaton](../persons.html#313) not to walk too fast, as he usually will do, but he had no mercy on any of us & it was with the utmost difficulty we cd keep up with them & I heard murmurs of ‘Quick, quick’ go on &c on each side as we strode on tripping in our long gowns, and finding the distance widening between us.

All the indifferent guests about 20 were ordered to take their places in the Chapel first, where [Graham](../persons.html#321) was already seated in his surplice & Capt Moore secreted in some recess or corner I don’t know where.

The family & more familiar or honorable guests, followed behind us, [Lord Carlisle](../persons.html#255) leading Aunt Seaton, [Lord Cardigan](../persons.html#1789) [Lady Clonmel](../persons.html#1794) I believe, & the rest as best they cd.

The whole line of the hall on one side runs an open gallery (by wh we can reach [Larkie](../persons.html#1795)’s rooms at times) wh now was filled with spectators to whom the procession was [sic] have looked very pretty indeed passing up between the double line of pensioners all in scarlet.

Uncle Seaton spite of all Aunt Seaton’s warnings, placed himself the wrong side of Jane, in Capt Moore’s place, & had to be told by [Miss De Salis](../persons.html#415) to change.

We eight just occupied the width of the chapel in a straight line behind Jane and [Alethea](../persons.html#317) & [Constantia Wood](../persons.html#1786) like 2 little Guardian Fairies behind us (not a very sublime simile) We all knelt of course, so did Uncle & At Seaton [Uncle Ed](../persons.html#1602). & a few others, but the general mass I am sorry to say did not.

Jane had a white moiré silk with quite a plain shirt, a wreath of orange blossom and jessamine on her head & over all a Honiton lace veil, thickly covered with sprigs & the corner hanging over her face, so that really it looked more modest & she was better concealed than in a Bonnet.

Capt Moore wd not let her wear anything at all on her arms, in the way of Bracelets etc on acct of that verse abt the ‘adorning’ being not of gold or outward apparel.[^2] The service over they were conducted to the vestry, wh is in fact one of the deep embrasures formed by the window of the hall. I mean all the windows are in so deep a recess, with a kind of entrance arch, that each is a complete little room, almost as large as one of [Mrs Penprase](../persons.html#1796)s & the one nearest the Chapel is fitted up as a Vestry, with red velvet seats & a table & chairs, & the Registers spread open upon it.

Here was a shaking of hands & congratulations of wh I accepted [?] The Lord Lieutenant kissed Jane & was most kind.

He is a singular looking old man, very ugly indeed but every one seems fond of him & his kindness feeling & consideration for every one is most remarkable.

He had arrayed himself in white trousers & waistcoat for the occasion.

Here the baskets of favours were brought to us, & while the signatures were going on inside, we began giving them with all our might. I made [Cordelia](../persons.html#319) pin & I carried the Basket & pins.

This accomplished, Jane was let back thro the rooms, now crowded with fresh arrivals (people invited to the breakfast only) & retired; we remained in the room talking to any one we came across as best we might but it was as crowded as it cd be - just standing room for all & I really thought with my veil hitching in other people’s shoulders my head wd have been twitched off. [Reginald](../persons.html#318) & [Lionel](../persons.html#323) came in composedly walking up & down & staring & people declared Lionel wd be trampled on, if not deposited with a guardian on the window seat.

Cordelia introduced me to the Miss Whateley’s, daughters of [the Archbp.](../persons.html#1797)[^3] I cd not ask about ?mappe of them.

We must have stood in this way, until the great dinner in the hall was ready, & at the last moment Capt M. consented to relinquish his earnest desire of not appearing at it, & Jane was led in by Lord Carlisle, followed by At Seaton & Capt Moore Lord Cardigan &c & the grandees who sat at the top of the Horseshoe table this shape [sketch] I have put double spots at the top to shew where Jane, Capt M & Uncle & At Seaton, Lord Carlisle, Lord Cardigan, Lady Clonmel sat, a space was left at the top on the inside just opposite them, so that all by turning their heads cd just see them if they wished it. I was very far down indeed, & only saw a distant vision of Jane’s face, but was the more surprised at her giving a funny little mischievous nod at me.

Lord Carlisle made a very short & most considerate speech, nothing at all wh it was the least unpleasant for Jane to hear, alluding to the warlike trophies by wh we were surrounded (flags &c) & though peace wd be a more appropriate wish for the occasion he cd not help expressing his opinion that if circumstances sd demand his assistance, it wd be proved that the fair Bride now by his side, was the wife as well as the Daughter of a Hero.

Tremendous applause followed this conclusion & the health was drunk in Champagne with Hurrahs.

Capt Moore simply said he thanked them all, but I did not hear in what words, it was but a few, & then he & Jane rose to retire.

They intended us all to have sat on and if people pleased other healths, the Bridesmaids &c to have been drunk but I am not sorry that the movement once given everyone got up & we returned in a greater crowd than ever to the drawing room where on a little table was the enormous cake, placed on a great wide bottom & with white ornaments & flowers on the top making a pile higher than our heads - not big enough- [referring to the sketch, erased] and a great knife as long as my arm.

This was cut & tasted & we handed it about. I slipped away for a minute with Cordelia’s permission in course of time, & we went up to see Jane who was merrily dressing herself, having wonderfully recovered since the morning, & was declaring she sd come down & dine with us, as soon as ever the people were gone. I only staid a minute & by the time I got down Aunt Seaton was standing at the entrance to the passage room shaking hands & dismissing her guests.

It took a long time to do this, & then we found a little dinner laid in the small sitting room for Jane & Capt M and Jane came popping down looking so natural that Charlotte said for the first minute she forgot anything had happened.

They had us all in about the room while they dined & Alethea & Reginald were jumping & racing abt the room, Lady Clonmel & her children & Larkie &c the only remaining guests.

At 6 the carriage came & with very short work of good byes they set off.

The drive to Birt wd take them three or 3 1/2 hours.

We returned to the deserted drawing room & sat round the cake, nibbling the crumbs & talking over the wedding, till Charlotte & [Mr Drummond](../persons.html#1370) branched off into their favourite discussion of the pedigrees of divers unknown Italian duchies till at 7 1/2 came our own dinner, bringing Lady Clonmel again & Larkie & we finished the evening as quietly as if nothing had happened, Miss de Salis singing a few songs, & me at work. [Zachary](../persons.html#1777) had dropped in the evening before, grey trousers & all to our great surprise.

He dined but did not sleep here, & went off very soon after the wedding.

He is going direct to England - Sydney I suppose.

He seemed aggrieved either in fun or in earnest that he had had no thanks for his grouse. I was glad to be able to say you had mentioned having some. I think [Papa](../persons.html#1623) told me of it.
I have not heard from you today, & yr note yesterday I read in great haste. I hope I have not overlooked anything I ought to answer, or that you do not think I am staying away too long.

Charlotte implores to cross over on Monday alone.

She has all the directions for it from [Julian](../persons.html#1624) & [At.

Fanny](../persons.html#1606) quite consents.

She wont hear of staying in Killarney, & Uncle Ed wont hear of my not doing that.

The 7 Churches expedition is to be tomorrow & it will remain to be seen if we go to Kill: on Saturday & come back here on Tuesday, keep the Fast day (if there is one) & cross over to either Holyhead or Manchester, or wherever we might next meet [Duke](../persons.html#1599) if he likes to come.

If he does not come we may take our choice of days, but I do not want to run into another week, but I hope to be with you all on the Saturday if possible, not that I sd mind, if you were all well, & happier without me.

You see what I mean, that I am not pining but I feel as if I had been long enough taking my pleasure. I sd be more decided abt Kill: if it was only dependant on me, but perhaps Cordelia will go, & Elizth is very anxious she sd.

Manchester too, she was so disappointed she did not the other day. I must finish now in haste, as we are going out. I have not written to [Alethea](../persons.html#27) today as I hoped.

You can send this if you like.

Love to [Cor.](../persons.html#1590) ask her if this account is enough, I fear not.

Mr Drummond left this morning at 8.

They are all regretting it, miss him so much &c An old [Uncle](../persons.html#1792) of Capt M. turned up at the last moment the only relative of his
your affect A. Y.

No time to read over.

Bad writing

[^1]: With envelope addressed to Miss Yonge/Rockdale/Yealmpton/S.Devon, postmarked Bow 27 April 1898 and Plymouth 28 April 1898, and labelled ‘Jane Moore’s wedding AY to JDY 1858’.

[^2]: 1 Peter 3:3.

[^3]: The Rt.

Rev.

Richard Whately (1787–1863), archbishop of Dublin from 1831, had four daughters, of whom [Jane](../persons.html#1798) (1822–1893) and [Mary](../persons.html#1799) (1824–1889), were much involved with missionary work at home and abroad.

