---
date: '1857-10-03'
display-date: October 3. [1857]
from-address: 'Royal Hospital, '
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  215-217
original-date: '2010-04-27 10:01:37'
title: To Frances Mary Yonge
wordpress-id: 3111
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mamma](../persons.html#1606)-
Yesterday made my news run into arrears, so I will only note that you must ask me about the College, and the three black Graces perched round the bell, with Science to make a fourth, and how we took them for Faith, Hope, and Charity, and [Graham](../persons.html#321) said Irish divinity had not much to do with faith, and the beautiful embodiment of Ruskinism in the new museum with green Galway marble columns, and foliage carved from the living plants.

And the MSS. in the library with the book of Kells, dug out of a bog, and another book with a wooden cover, in which is set a huge crystal, believed by the devout to be one of the stones of Jacob's pillar, also the one I most longed to turn over. A missal of St.

Agnes' Convent of 1459 where there was a border with the regular gold leaves and black stems, and all our old friends, the turnedover leaves with white patterns upon them, but with little beautiful portraits of saints springing out of them; also an Apocalypse with such a Beast, but they were all in glass cases where only two pages could be seen, and the Irish are so dreadfully afraid of being overworked that they shut everything up at three, and the Library at four, so my time was short.

Then Graham trained us off to see a wonderful chapel of [Mr.

Newman](../persons.html#1084)'s, with frescoes done by [Mr.

Pollen](../persons.html#1800) from the cartoons-- melancholy work.[^1]
Yesterday morning we had to be off at eight, the five ladies namely and Graham, when [Julian](../persons.html#1624) will laugh at hearing that the funds provided to take six people fifty-four miles on the railway, and thirty-six by cars, were a single one-pound note which [Elizabeth](../persons.html#320) had lost, so I had to give Graham my purse, or we should never have gone at all.

The railway took us to K---, whence we took two cars, and drove first to the Devil's Glen, one of those beautiful wooden ravines, with a wild river foaming over rocks, and fine crags rising perpendicularly overhead.

Afterwards a waterfall, of the flight of steps order, at which we were ordered to look through a hole which framed it beautifully, but was not easy of access, and beyond was a breakneck place called King O'Toole's chain, where those who liked hung over the rock.

Then we drove on to Glendalough, a wondrous place, very like the pictures of it, where we were guided by an exaggerated Irishman evidently acting a part, who told me when I found a frog that I might put it into my bosom, but that there were neither toads (stones there were in plenty) nor snakes, for we live in a civilised country.

The glen is a great gorge between the mountains, with a mountain stream swelling in the valley into two grey lakes, less gloomy than I had expected, but then it was a very fine day.

The flat part of the valley and the lower slopes towards the outermost lake are beautifully green and wooded, and on the shoulder of the mountain, among the wood, lay one of the most beautiful patches of verdure I ever saw, all the brighter from the contrast with the rough mountain side, brown and yellow in colouring, the material being black and white sparry stones grown over with heather and dwarf furze.

The torrent comes rushing down from the hills, and makes a grey sparkling line in the middle of the amphitheatre that shuts in the inner lake, which, like its fellow, and the stream, has a broad trimming of white or grey sand, the débris of the spar above.

One of the tributaries forms a pretty waterfall with black rock to set it off, projecting in curious shapes.

It was tolerably full, for we were told there had been so much rain that the rock was so slippery that a widow's cow had tumbled off a crag, and either killed or kicked four hares.

The seven Churches are disposed about the glen, two are nothing but heaps of stones; the two best, the ‘Cathedral’ and St.

Kevin's kitchen, stand in a crowded graveyard of the Byrnes and O'Tooles full of hideous headstones.

There are some interesting old broken crosses on coffin lids, dealing much in circles by way of embellishment, and the Church of St.

Kevin's kitchen has a round belfry like a little round tower. A straight, blunt, tall round tower stood close by, like the other ruins, perfectly yellow with lichen.

All this must have been a four-mile walk; [Miss de S.](../persons.html#415) says that between it and the Devil's Glen we had walked six miles, and as I had started with a cold in my head, and the sandwiches had been forgotten, I was rather done for by the time we came back to a most Irish little inn, where these people, who can eat wedding cake all the morning, or eat nothing at all with equal impunity, ordered eggs and tea, which last was evidently made of the peat of the bogs, and gave me some cold mutton, as I had prejudices in favour of animal food--
		By that lake whose gloomy tea
		China's shores did never see.[^2]
Then on our cars we mounted for about twenty miles to Bray, where we were to take train again, and a strange wild drive it was, with the moon shining on the waste heath, and a great purple hill rising up against the sky as if it would never come any nearer, but at last we did turn round it, and went along a magnified and magnificent valley of rocks, great perpendicular crags rising up like castles, and ending in rocks of odd shapes.

It seemed to me the grandest thing of all, but it was not under favourable circumstances, for the car was such a jolter that we are all as stiff as if we had been riding all day. I was dreadfully tired, and [Cordelia](../persons.html#319) was talking to me all the way about presentiments.

We had meant to catch the 7.25 train from Bray, but were not in time for it, and had three-quarters of an hour in a luxurious refreshment room, where being past eating anything, I thought it a most knowing dodge to remember Julian and take a dose of brandy and water, which put me grandly to sleep all the way to Dublin, and there our final adventure was that the sentry would not open the gate to us, and there we sat till the guard was changed, and fetched the sergeant to our rescue, when the sentry's face of satisfaction in having sold us, grinning out under his bearskin, was a picture.

Once when little [Lionel](../persons.html#323). was ill, the doctor was kept waiting a quarter of an hour in that way.

Your most affectionate
C. M. Y.

[^1]: John Hungerford Pollen (1820–1902) converted to Roman Catholicism in 1852 and was appointed by Newman in 1854 professor of fine arts at the Catholic university, where he designed the university church, St.

Stephen’s Green, consecrated in 1856.

See Suzanne Fagence Cooper, ‘Pollen, John Hungerford (1820–1902)’, Oxford Dictionary of National Biography, Oxford University Press, 2004. CMY presumably found melancholy the contemplation of the work of two apostates.

[^2]: Thomas Moore’s poem on Glendalough opens ‘ By that Lake, whose gloomy shore/ Sky-lark never warbles o\'er,/ Where the cliff hangs high and steep,/ Young Saint Kevin stole to sleep.’ CMY is evidently quoting from a parody.

