---
date: '1857-11-01'
display-date: Novr 23d 1857
from-address: Otterbourne, Winchester
manuscript-location: MS Westcountry Studies Library, Exeter/  Yonge 1857/4
original-date: '2010-04-27 11:40:16'
title: To Ann Maria Carter Smith
wordpress-id: 3113
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
Thank you for all your replies, I had been waiting to answer you till I had read aloud to the end, for you must know I began it the day it came when a girl was here whose London experiences are very West End, and as she went away in the midst, much interested, I only glanced on to the end, and kept the rest till she came again.

She was decided as to no one having any shame at being seen with her father in a cab, and likewise on the pickled salmon subject.

Not very important points certainly, but in such a story as this, I think the keeping and reality great point. I don’t question that Lucy deserves to be called cold blooded, only whether her father would do it.

Your tractarian story is very funny. I should have thought people of that calibre fancied that disseminating tracts was the great duty of life, but I suppose she took a narrower range. I am not sure whether the end is not a shade too abrupt - perhaps before unluckily space will come.

You may think of something to make the end come off more
[the rest missing?]
