---
date: '1858-11-24'
display-date: Novr 24th 1858
from-address: 'Otterbourne, Winchester. '
manuscript-location: 'MS Princeton University, Parrish Collection, C0171: Box 29.'
original-date: '2010-04-27 15:52:40'
title: To the Reverend Edward Coleridge
wordpress-id: 3122
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mr Coleridge](../persons.html#332)
I send you a Post Office order for £2 which is all I can very well do for this most melancholy case, as just before Christmas is not the time for my galleons to come in.

If you will send me another paper, I will forward it to some of the Gibbses who might perhaps be able to do something for the poor family.[^1] I do not know of any one else to ask.

Thank you for your information about the [Melanesian fund](../others.html#30), which I thought most satisfactory, for it would be very absurd to detain the money from securities equally good and more profitable.
I was very sorry to miss the [Abrahams](../persons.html#4) when they were in this neighbourhood lately but the [Kebles](../persons.html#798) saw them. [Julian](../persons.html#1624) and [his bride](../persons.html#1604) are with some of her relations at present and [my mother](../persons.html#1606) has just set off to Winchester to the confirmation of [her Godchild](../persons.html#968), one of the Moberlys.

Pray give my kind regards to [your daughter](../persons.html#1808) and believe me
Yours very sincerely

C M Yonge

[^1]: [William Gibbs](../persons.html#560) (1790-1875), of Tyntesfield and his nephew [Henry Hucks Gibbs](../persons.html#558) (1819-1907) were both connected to CMY through the Crawley family.

