---
date: '1859-04-12'
display-date: April 12th [1859]
from-address: Otterbourn
manuscript-location: MS Westcountry Studies Library, Exeter/ Yonge 1859/3
original-date: '2010-04-28 13:49:29'
title: To Ann Maria Carter Smith
wordpress-id: 3129
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Smith](../persons.html#263)
I hope and trust the tale is safe, I sent it off with the letter on Saturday, in a brown paper cover and a shilling stamp which our post office told me was the sufficient sum.

If it be not come, we must write to the General Post Office but I hope to hear it is all right, as I know the book post will sometimes detain a heavy parcel for a day or two.

It has been haunting me ever since my letter went that I made lain the participle of the active to lay, instead of of the neuter to lie. I believe one always knows less of English grammar than of any other.

By the by, I hope you will not think I wished anything to be said to diminish the inexpediency of [cousins marrying](../others.html#101). I think old Sir John was very right Thank you about Robert.

Those people are very real to me. I enclose a note for [Mr Parker](../persons.html#1143) which I hope may induce him to consider it favorably, unless he thinks it out of his line. I hope you will let me know if it has safely arrived. I am so glad poor Robert and Sophy will be allowed to be together.

In a day or two I hope to send the next division of [East London](../others.html#265), please to direct it on straight to [Messrs Mozley](../others.html#108) at Derby instead of sending it back to me

yours sincerely

C M Yonge

[^1]: This letter evidently belongs in the empty envelope catalogued as MS Westcountry Studies Library, Exeter/ Yonge 1859/4: an empty envelope addressed to Miss Ann Smith/ Rectory/ Old Charlton/ London/ SE and postmarked Winchester 12 April 1859 and London SE 13 April (year illegible).

