---
date: '1890-02-01'
display-date: '[February 1890]'
from-address: ''
manuscript-location: MS location unknown.  These two fragments, which may belong to
  two different letters, were published in <i>[[otherbook:122]Dulce Domum]</i> 304
  and 308.
original-date: '2010-07-05 13:22:32'
title: To a member of the Moberly family
wordpress-id: 3152
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

One can only thank God for the beautiful, holy vision that your ‘sweet [mamma’](../persons.html#1019)[^1] has been to me all these fifty years or so – the looking-up friendship which was so precious.

There has been no presence for a long time more sweet and blessed to me; and that last summer I specially enjoyed, when it had come to be almost the bien-être of relationship, and all redolent of old times. . . .

Well, I don’t think there can be much to alter in her on the other side of the door of Paradise.

How blessed to have two such lives to dwell upon!

Truly, from the first time I saw her, nearly fifty years ago, with her baby on her knee, to my last look, there was no blemish of any kind; and now, the fine Gold has received its final purification, and reflects perfectly the image of the Refiner.

[^1]: Mary Ann Moberly (1812-6 Feb 1890).

