---
date: '1890-03-06'
display-date: March 6th 1890
from-address: Elderfield
manuscript-location: MS Girton College Cambridge, Yonge IV 18
original-date: '2010-07-05 13:34:07'
title: To Arthur Donald Innes
wordpress-id: 3155
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Innes](../persons.html#744),
I hope there are still some [Castle builders](../books.html#18) left for a lady in Portugal wrote a few days ago to ask me if it was still to be had, and I answered that it was.[^1] I suppose the Modern Landmarks are put out by later books.[^2]
I am concerned about a long series of scientific papers on the physical structure of the Earth. I accepted them some time ago from [Miss Gaye](../persons.html#552) and spoke of beginning in July 1890.[^3] Then came this great effort to make the [Packet ](../others.html#52)more popular, and I do not know what to do about it.

At that time people were crying out that there ought to be more improving papers and fewer stories! I do not know if it would be best to put in the papers not as a series but individually.

Yours truly

C M Yonge

[^1]: The Castle Builders (London: Mozley 1854) had been reprinted in 1885.

[^2]: CMY had published [Landmarks of History: Modern History from the Reformation to the Fall of Napoleon](../books.html#28) (1857; 6th edition, London: Smith 1882) and [Landmarks of Recent History, 1770-1883](../books.html#172) (London: Smith 1883), either or perhaps even both of which may be referred to here.

[^3]: Selina Gaye does not seem to have published any such articles in MP.

