---
date: '1890-10-10'
display-date: October 10, 1890.
from-address: Elderfield
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  321
original-date: '2010-07-07 08:33:06'
title: To Florence Wilford
wordpress-id: 3164
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear[ Florence](../persons.html#1520)
I am very glad to hear of you again, and I hope the touch of frost will not be felt at Bournemouth; it has spared all our flowers as yet. I waited to write because [Christabel](../persons.html#329) was coming to make up our plans for the new [volume](../others.html#52).

We will try to put in 'Purification' poem for February, but I am afraid poems do not get much payment. I wish I could put more work in [her](../persons.html#1519) way. [^1] I forget whether you know [Miss Hill](../persons.html#2102), who stays with the [Jones Bateman](../persons.html#785)s sometimes; she is lame from old hip complaint, but gets about on her crutches.

She is sister to Mr.

Rowland Hill. I am afraid the [Newbery Magazine](../others.html#83) is a tardy affair, as all magazines are, unless they begin by being hard-hearted and summary. I don't much like what I have seen of it.

Christabel asks to be remembered to you.

She is my original old [Gosling](../others.html#104), and she and I have been going over our old brood, and what a remarkable set they have been, for good, and alas! sometimes for the reverse, but there are a good many that I am proud of.[^2]
I am hurried and must finish.

Your affectionate
C. M.

Yonge

[^1]: Her correspondent’s sister Emma Wilford (b. 1832/3), as appears from the next letter to Florence Wilford (18 October 1890).

They lived together in Bournemouth. A poem ‘The Treasures of the Snow: Feast of the Purification’, signed ‘W.’ appeared in MP (February 1891).

The feast of the Purification is 2 February, and this may well be Emma Wilford’s poem.

[^2]: The Goslings who had been remarkable for the reverse were probably [Mary Arnold](../persons.html#1467) and [Mildred Coleridge](../persons.html#17).

The former had, as Mrs Humphry Ward, become the author of the notorious novel Robert Elsmere (1888), about an Anglican clergyman\'s loss of faith; the latter, who was a cousin of CMY\'s, fell in love with the unsuitable Charles Warren Adams, and after a series of acrimonious libel suits brought by him against her father and brother, married him in 1885 in a blaze of publicity, causing a family quarrel which was never made up.

Another backslider was probably [Katie Johns](../persons.html#887), who seems to have parted from her husband and become a theosophist.

