---
date: '1891-12-14'
display-date: Decr 14th 1891
from-address: Elderfield
manuscript-location: MS Hampshire Record Office 9M55F56/1
original-date: '2010-07-07 10:55:38'
title: To Penelope Anne Laura Packe
wordpress-id: 3181
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mrs Packe](../persons.html#1112)
I hope the weather will remain fine to the end of this sad day. I shall think of you in the lower end of the Church yard beside the grave of that life long [friend](../persons.html#1379).

The loss to you must be unspeakable.

You and your [Sister](../persons.html#700) were with with [sic] her as very little girls, younger than your children are now the first time I ever was at Testwood.

How glad you will always be that they are old enough to have a distinct memory of her, and happy recollections of the Knoll. I hope it will remain as it is with all the heather.

She was always full of them and talked about them last time like Grandchildren.

Some time, when you or [Miss Martin](../persons.html#2105) have time to write, I should like very much to know what becomes of the Knoll, and what the three old servants do. I have no doubt that she has secured their welfare.
I doubt whether any way [my notice](../books.html#349) have been put in this week, but if sent no later than Wednesday I think it will get in, only as it is rather long already, I think it will hardly be safe to add very much to the length, without omitting something.

With kind regards to Miss Martin

Yours sincerely

C M Yonge

[^1]: Penelope Packe and her sister Laura had been brought up by Anne Sturges Bourne (1809-9 December 1891) who had just died. CMY had evidently written an obituary for a weekly newpaper, possibly the [Guardian](../others.html#75).

[^2]: Black-edged paper.

