---
date: '1892-01-01'
display-date: Jan 1st 1892
from-address: Elderfield Otterbourne Winchester
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2010-07-07 13:38:35'
title: To the Archdeacon of ?
wordpress-id: 3184
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Mr Archdeacon[^1]
I am venturing to ask a favour of you.
I do not know whether you have heard of the [Mother’s Union](../others.html#31), started by [Mrs G Sumner](../persons.html#1381) (the wife of the [Bishop of Guildford](../persons.html#1382)) at first for poor women, to rouse them to some heed to the training of their children but it gradually spread to ladies &c. and indeed quite as much counsel seems to be needed by them as by cottage women.

The need of an ‘organ’ was soon felt, and faute de mieux, I have had to edit the quarterly [‘Mothers in Council’](../others.html#82) of which I send a specimen.

We want particularly good advice upon boys’ training.

Some excellent papers we have had, and we should be very grateful if you would give us a short paper on some point in their home training.

What is foremost in my mind is the fore-arming against the many temptations to gambling - but for any other subject that you might prefer, we should be grateful. I am afraid at present that it must be gratitude alone, as [Wells Gardiner](../others.html#114) who publishes at the risk of the President does not yet pay beyond the expenses, though the sale encreases [sic]
I remain
Yours very truly

C M Yonge

[^1]: CMY is evidently writing to someone who is not a stranger to her from outside the diocese of Winchester. A possible candidate is the Rev. [William Emery](../persons.html#2107) (1825-1910), Archdeacon of Ely, who was interested in schools, and whom CMY knew because he was involved in the Church Congresses.

