---
date: '1892-09-10'
display-date: Sept 10th 1892
from-address: Elderfield
manuscript-location: "MS Mrs Caroline Fairclough/28\t\t"
original-date: '2010-07-18 13:41:27'
title: To Arthur John Butler
wordpress-id: 3201
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Arthur](../persons.html#238)
[Aimée Leroy](../persons.html#869) is at Ilfracombe at this moment. I don’t know how soon she comes home, but a letter would find her in a few days.

The person who could do the thing best of all is [Miss Roberts](../persons.html#1244), author of Mademoiselle Mori but she is abroad and last time I heard of her, she was in Corsica. I think I could do the thing for you, a good deal by a book of hers on the general scenery, but as I did a history under [Mr Freeman](../persons.html#523)’s guidance, I think I could manage that, and these last six weeks without Church or School have brought me so much on with my regular work that I could give three weeks to it.[^1]
There is plenty of Gentiana Pneumonanthe in the New Forest, in bogs not very far from Lyndhurst.

It is very handsome, though smaller than the garden gentian, and when I saw it there it was later in the year than this.

If the days were longer and a good deal besides we might meet at the Lyndhurst station or rather the Eastleigh one, and go down to the place where I have seen it.

yours sincerely

C M Yonge
It used to grow about Farnham but probably the soldiers have been too much for it

[^1]: Arthur Butler, having spent seventeen years in the Education Department (1870-1887), left to join the publishers Rivingtons in 1887, and, after it was sold, became (November 1891- June 1894) Chief Editor at Cassell’s, which published books and periodicals including The Quiver, Cassell’s Saturday Journal, Cassell’s Magazine, Chums and others.

It sounds from this and the following letter as if CMY had written a [historical article](../books.html#350) or book (three weeks, even for her, sounds not much for a whole book) published by Cassells.

