---
date: '1893-01-10'
display-date: Jan 10th 1893
from-address: Elderfield Otterbourne Winchester
manuscript-location: 'MS Bodleian Library, Oxford: MS Acland d.175.ff 178-9 '
original-date: '2011-10-14 19:53:26'
title: To Sarah Angelina Acland
wordpress-id: 3210
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Acland](../persons.html#8)
I am sending Pompei (it does not look natural) to [Christabel Coleridge](../persons.html#329) at Cheyne, Torquay, and it will be more convenient for her to let you know about it, as I am not the sole dictator of [Packet](../others.html#52) now, but one of a triumvirate - being really, I suppose, rather dropped behind the present world.[^1]
I fear that any how the diagrams cannot be brought in, but that [the publisher](../persons.html#744) must decide, and they may think it long and minute
A ridiculous fabulous history of me declared that I never permitted a Roman Catholic to write in the packet, which was very untrue[.] I once had [Kathleen O’Meara](../persons.html#1096) and dropped her, not for her opinions, but for making the cannon fire a salute when William the Conqueror started for England, which destroyed my confidence in her ‘Old Castles’.
I saw [Mrs Cooke Trench](../persons.html#367) last week.

The party have not started yet as [Beatrice](../persons.html#655) feels bound to wait for young [Mr Compton](../persons.html#2118)’s coming of age ball. [Lady Heathcote](../persons.html#665) was then very unwell but was much better when last I heard [Helena](../persons.html#663) was not well but not seriously, and I expect to meet her at some of the [GFS](../others.html#23) affairs next week
Yours very sincerely

C M Yonge

[^1]: The article does not seem to have been published.

