---
date: '1893-01-15'
display-date: Jan 15th 1893
from-address: Elderfield Otterbourne Winchester
manuscript-location: 'MS British Library  Add MSS 54921: 190'
original-date: '2010-07-20 10:10:01'
title: To George Lillie Craik
wordpress-id: 3211
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Craik](../persons.html#379)
I send herewith the story of [‘The Strolling Players’](../books.html#229) - from the [Monthly Packet](../others.html#52).

The joint production of [Miss C R Coleridge](../persons.html#329) and me.

It joins to the [Beechcroft](../books.html#3) series.

If you could tell us what the royalty would be the division would be easier

Yours truly

C M Yonge		
I suppose [Mrs Gordon](../persons.html#572) has called about the [Chicago books](../others.html#221)[^1]

[^1]: See the letter to Alice May Gordon (6 May 1894) about CMY’s loan of her books for the exhibition in Chicago.

Alice Gordon had written to the Editor of The Times (5 January 1893): \'A library has been built in the Women\'s Building of the Chicago Exhibition, in which the best books written by women of all nations are to be exhibited.

We are anxious that English women\'s writings should be well represented. A committee has been formed consisting of Miss Agnes Clerke, Mrs. W. K.

Clifford, Mrs.

Green, Miss Kingsley, Mrs.

Humphry Ward, Miss Charlotte Yonge, and Mrs. J.E. H.

Gordon, to collect a representative library.\' She asked for the gift or loan of books or MSS.

