---
date: '1893-07-28'
display-date: July 28th [1893?]
from-address: Elderfield
manuscript-location: MS West Devon Area Record Office Acc No 308
original-date: '2010-07-27 14:48:38'
title: To Mary Yonge
wordpress-id: 3224
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I was obliged to let the [Guardian](../others.html#75) go that week before I had really read it, but it must be a mistake for our dear [Charles](../persons.html#1601) cannot be referred to in Bp Wordsworths Christian Boyhood, as it was published before his death.[^1] I know he had a copy full of marks of his own.

There is a note in the book about the poet Bowles and the habits at [Winchester](../others.html#50), and I think the letter writer must have confused this with the great influence that Charles certainly had for I do not believe there is any tablet.

We must have known of it if one had been put up. I was at Domum this week and had a glimpse of [Edmund](../persons.html#42) but not of [Geoffrey](../persons.html#1609).[^2] I think I never came across so few people that I knew partly because it was crowded, and partly because it was dark.

But two of the married Moberly daughters were there and I walked about with them, and felt like old times, though one of them ([Kitty Barter](../persons.html#114)) had a tall handsome daughter of eighteen with her. I am glad [Frances](../persons.html#1605) is so much better I hope all her troubles will be over while the warm weather lasts, but she will have to take care in the winter - I think Doctors always dislike one going to Church. [Gertrude](../persons.html#1462) is on the whole better, she has been spending a week in my room instead of her own while there was a chimney sweeping and cleaning – her first change for ten months!

Today she is gone back again.

That unfortunate [Mrs F Yonge](../persons.html#2127) has been applying to [Colonel Oldfield ](../persons.html#2128)who wrote to [John Eyre Yonge ](../persons.html#1620)about her. [^3] She seems to be in a hopeless state of illness by his account (John’s) but he fancies it is a first application.

One son is in the post office, getting 10s a week.

Fancy Morgan [?] having a brother with such young children! [Mr Coward ](../persons.html#2129)(our locum tenens) is very young 27 & looking younger.

He has a splendid voice - On St James’s day, at evening service when we don’t have the choir or any singing, he gave out a hymn, and while we were gazing in amazement sang it all right through by himself!
your most affectionate cousin

C M Yonge

[^1]: Mary\'s brother Edmund Charles Yonge (1827-1847).

Charles Wordsworth (1806-1892), a master at Winchester before he became Bishop of St Andrews, had published Christian Boyhood at a Public School: A Collection of Sermons and Lectures Delivered at Winchester College 2 vols (London: Francis 1846).

[^2]: Mary’s nephews.

Geoffrey Yonge (1867-1893) had perhaps come down to Domum as an old boy of Winchester College; Edmund Anderson Morshead (1849-1912) was a master there.

[^3]: The most likely Mrs F.

Yonge seems to be Mary (Jones) Yonge, the indigent widow of Dr John Francis Duke Yonge (1814-1879), son of CMY’s uncle the Rev.

Duke Yonge, Vicar of Antony.

Colonel Oldfield was the stepson of his sister Delia (Yonge) Oldfield (1807-1864).

However, the reference to \'Morgan\' is obscure.

