---
date: '1894-02-15'
display-date: Feb 15th 1894
from-address: Elderfield
manuscript-location: 'MS Bodleian Library, Oxford: MS English Letters: e.174 ff 135-6'
original-date: '2011-12-16 13:11:07'
title: To the Reverend John Frederick Watkinson Bullock
wordpress-id: 3249
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Bullock](../persons.html#221),
I send [Bp Mackenzie](../persons.html#929) whom I had to do in haste because my book was wanted -
I think I had better take Carnarvon for the leading Cavalier for I can more easily get at his history at present than any other The Memoir of the Verneys I had once from [Mudie](../others.html#137) but I should have long to wait for it again and it is an expensive book, so I will only mention him in the course of what will be an article on the Cavaliers.
I again must hope you will leave out [Miss Sellon](../persons.html#1294). I know of [Dr Pusey](../persons.html#1215)s’[sic] friendship for her, but his friends thought he did not know all details.

And I think from the time she refused to let [Bp Philpotts](../persons.html#1778) be Visitor she grew masterful[^1]
I have little doubt that submission even in what she did not approve would have been wholesome in the end.
I will write Bp Frampton and send it to you[^3]

Yours truly

C M Yonge

[^1]: Henry Phillpotts (1778-1869), bishop of Exeter, long one of the few bishops sympathetic to the Tractarian movement, supported Lydia Sellon\'s sisterhood, which was highly controversial.The proposed biographical articles were for the [\'Biographies of Eminent Anglicans\'](../books.html#358) which formed part of Bullock\'s Daily Lections project but were never in fact published.

[^3]: Robert Frampton (1622-1708), bishop of Gloucester.

