---
date: '1894-04-12'
display-date: April 12, 1894.
from-address: Elderfield, Otterbourne
manuscript-location: MS location unknown.  Printed in Coleridge, [[otherbook:40]<i>Life</i>],
  324-5
original-date: '2010-08-11 15:11:36'
title: To Charlotte Anne Elizabeth Moberly
wordpress-id: 3259
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Annie](../persons.html#1024)
I am very glad you have had such a peaceful soothing time, and that [Mrs.

Cazenove](../persons.html#275) and her daughters have had so much comfort.

It is very good for you to be with your good friends. [Tottie](../persons.html#1588) sent you a book yesterday, which I hope may be sent on.

Thank you for so kindly receiving what I ventured to say. I have written sharply to the editor of the [Church Illustrated](../others.html#229) for putting in commendation of the book.[^1] When one recollects that every word in the Gospel is sacred, and that the history is the direct Inspiration of God the Holy Ghost, it seems to me too terrible to twist them into suiting a person's own ideas of a tragedy.

I do not think you quite understood what I said about the effects on oneself. I did not mean that I thought you believed it.

But I will give you an instance.

It does not signify what I think about the death of Julius Caesar, but whenever I read the history of it there occurs the question, did he really say 'Et tu, Brute,' and was it to Marcus Brutus or to Decimus Brutus? and all the Shakespeare scene.

This is no harm of course, but would not something like it occur when one wanted to concentrate mind and soul on the great crisis of our Redemption, when one wants heart and soul to be full of the reality and the infinite spiritual meanings of every word and deed?

I know people differ about the reading of 'doubtful books.' I did consider it once, as you say, for the sake of other people, for you know questions are asked me, and I have to write letters. [Dean Butler](../persons.html#244) decidedly told me I need not, and I will tell you why I think it is a questionable thing for women to do. I do not mean if one was asked distinctly to read and give an opinion on any one book seriously; then I suppose one must do so, but to read popular undesirable books for the chance of discussion seems to me not good for one's own mind, and very doubtful for other's sake.

Clergymen may and must do it.

They have greater safety than a woman can have, being trained in theology, the history of opinions, and in logic.

Now we women hardly ever get such training, and for want of logic do not see the danger of proving a truth by an insufficient proof, which can be overthrown.

We cannot take in all the bearings, and it is apt to come simply to likes and dislikes in the main.

Then too, without upsetting one's faith, I do believe that the tone of one's mind is hurt by reading such things.

And I do think that a woman produces more effect by what she is than by a thousand talks and arguments.

You may show what I say to [Canon Jelf](../persons.html#757).[^2]

The lame child goes to the [Orthopedic hospital](../others.html#9) on Saturday.

Your affectionate
C. M.

Yonge

[^1]: Marie Corelli, Barabbas 3 vols (London, Methuen 1893), a novel about Christ\'s three last days on earth.

[^2]: Probably the Rev.

Canon George Jelf (1834–1908).

