---
date: '1895-12-14'
display-date: December 14 1895
from-address: Elderfield
manuscript-location: 'MS location unknown, owned in 1947 by Alethea Yonge; part facsimile
  in Mare and Percival, [[otherbook:598]<i>Victorian Best-seller</i>], facing page
  208. '
original-date: '2010-09-07 14:22:10'
title: To Augusta Boevey Pode
wordpress-id: 3305
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Augusta](../persons.html#1180)
It is rather funny that the same post as brought your letter about [Lady Blachford’](../persons.html#1253)s indignation brought one from an American Correspondent of [Gertrude](../persons.html#1462)’s saying that she had observed that strict older sisters did generally turn out indulgent Mothers.[^1] But I understand it this way.

Wilmet had seen that strict laws had not fully answered with Fulbert, Angela or Bernard and the Harewoods were easygoing by nature and also there was a spirit of teasing in the family.

Bill’s goodness came from his friendship with Lance and I do not think indeed I said that outsides in the Navy or Army would have reported ill of the sons, they would do their work there properly, but they did love teasing – up to tyranny pitch as with Gerald when a small child
[the rest not reproduced]

[^1]: Wilmet Underwood, who in the early part of [The Pillars of the House](../books.html#109) is a strict but fair mother to her younger brothers and sisters, turns in the second part and in sequels into an indulgent parent whose unruly sons bully their cousins.

