---
date: '1897-08-22'
display-date: Aug 22 [1897]
from-address: Elderfield
manuscript-location: 'MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/61'
original-date: '2010-10-07 09:51:18'
title: To Beatrice Henrietta Heathcote
wordpress-id: 3356
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Bea](../persons.html#655),
I think I might add these two bits from[ ‘Old Times at Otterbourne’](../books.html#218) as the thing turns out so short[^1]
I heard a very odd thing from [Anna Bramston](../persons.html#195).

She says she has seen a sword said to be old Oliver Cromwell’s in the possession of old [Mr Comely](../persons.html#2176).

He said that at the sale in ‘the old home’ a blacksmith had obtained it, and it had descended to him.

Could the old house be the Cromwell house?

It was a curious sword,, sharpened on both sides towards the point, but all the Comelys are dead, and Anna does not know what became of it I think they must have been blacksmiths for the smithy as I first recollect it was in charge of a certain [‘Betsey Comely’](../persons.html#363) who used to preface her speeches with ‘I am but a fay-male, sir’
Is the water found yet?

Your affectionate

C M Yonge

[^1]: This letter refers to gathering material for [John Keble\'s Parishes](../books.html#247).

