---
date: '1898-02-16'
display-date: Feb 16th [1898]
from-address: Elderfield
manuscript-location: MS Devon Record Office, Exeter 53/10/9/1
original-date: '2010-10-07 15:11:13'
title: To Edmund Doidge Anderson Morshead
wordpress-id: 3369
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Edmund](../persons.html#42)
Thank you for the result of your audacious bit of sacrilege, and also Mr Hardy.

Mr Bowland’s epitaph, I am glad he was a keeper of the parks and not of the swine!

Duthy read the name Bockland and Marsh Bowland[^1] He must have been a man in good odour with employers and tenants I wonder whether his eulogy is the work of a Bishop’s Chaplain or a college fellow I should think it unusual to give his name in plain English, and the age and date were elaborated pieces of work
So many curious things have turned up since I began about the history of Hursley and Otterbourne that I think it will be very entertaining
Thanking you much
your affectionate cousin

C M Yonge

[^1]: The research was connected with her book [John Keble’s Parishes](../books.html#247), in which she quotes, 19-20, the Latin epitaph of John Bowland (d.1474).

Morshead, who taught classics at Winchester College, may have provided the translation.

