---
date: '1898-05-05'
display-date: May 5 1898
from-address: Elderfield
manuscript-location: 'MS Hampshire Record Office: Heathcote Family Scrapbooks: 63M84/234/65'
original-date: '2010-10-07 15:32:05'
title: To Helena Mary Heathcote
wordpress-id: 3370
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Ellie](../persons.html#663)
I am delighted to hear of the Medallion![^1]
Have you seen Sir Herbert Maxwell’s book of the months-?

He disbelieved the rod and someone ought to write to him.

He watched [Mullins](../persons.html#2189) - and fancied he had discovered the places before.

But [Lady Crawley](../persons.html#2188), the mother of [Mrs William Gibbs](../persons.html#557), who had the power only in that generation of the family laughed at it as imagination, and I believe Mrs Gibbs inherited it, but never spoke of it. [Mrs Monroe](../persons.html#1033) had Mullins to find water at Colden Common and he did.

All the servants tried under his tuition but only one maid succeeded.
I am doing our Birds with anecdotes if possible to add to the book.
[Helen](../persons.html#1613) has a copy of [illegible] marked by her [father](../persons.html#1624) and can complete the set.

There really is much to say of them.

Your affectionate

C M Yonge

[^1]: A medallion is mentioned in [John Keble\'s Parishes](../books.html#247), 3, which is the book under discussion here.

