---
date: '1898-06-23'
display-date: June 23rd 1898
from-address: 'Elderfield Otterbourne '
manuscript-location: 'MS British Library  Add MSS 54921: 234-5'
original-date: '2010-10-07 16:17:57'
title: To Frederick Orridge Macmillan
wordpress-id: 3375
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Mr Macmillan](../persons.html#942)
Herewith I send the MS of ‘[John Keble’s Parishes](../books.html#247)’ I shall be glad to know what you think the best way of dealing with it and what you think about illustrations.

There should be a map of the parishes which are locked together but I wait to get it drawn out till I hear about the size of the page
What would be advisable as to illustrations.

We had thought of
Ruins of Merdon Castle
Old house at Hursley
Cup and other relics found in a deep well
Great Seal of Richard Cromwell
Old Church of Hursley
Otterbourne Church
Ampfield Church
Hursley Church
Portrait of [Sir William Heathcote](../persons.html#669)
& [Mr Keble](../persons.html#798)
Would these be too expensive?

What would be the terms
If possible the book should be out by the middle of October, as a Jubilee of the Church’s Consecration is to be kept on that day/24th

Yours sincerely

C M Yonge
