---
date: '1898-10-07'
display-date: Oct 7th 1898
from-address: Elderfield
manuscript-location: 'MS Bodleian Library, Oxford: Autogr. d. 22 ff62-64 '
original-date: '2011-02-02 12:08:33'
title: To Anna Meredith Barrett Lennard?
wordpress-id: 3383
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Lennard](../persons.html#121)
I must send your name on a separate piece of paper, as the book must go from [Macmillan](../others.html#111) as I do not keep a stock of copies by me, and besides I think booksellers packing is safer than home, if I had a copy I was sure was new all through[^2].

What a sad loss of all your precious books, that can never be repaired!

We are looking forward to the 50th Consecration of Hursley church when there will be a great gathering and an octave[?] of services
We had a Te Deum for the victory[^3] in church the Sunday after we heard of it. [Mr Bowles](../persons.html#184) had three cousins there so it came very near.

Today I have been reading of the grand reception in London
What a state the world is in - and is France ever to retrieve its general character, each generation falls lower than the last

Yours sincerely

C M Yonge

[^1]: Envelope addressed to ‘Mrs Barrett Lennard/Hechthausen/ Cui Stade/ Germany’

[^2]: Accompanied by a piece of paper with \'M.

Barrett Lennard from CM Yonge\' on it.

[^3]: The Battle of Omdurman, September 1898, when an Anglo-Egyptian army led by Kitchener gained control of the Sudan.

