---
date: '1898-12-21'
display-date: Decr 21st 1898
from-address: Elderfield
manuscript-location: 'MS Bodleian Library, Oxford: Autogr. d. 22 ff65-67 '
original-date: '2011-02-02 12:06:32'
title: To Anna Meredith Barrett Lennard
wordpress-id: 3389
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Lennard](../persons.html#121)
I suppose your friends are only prepared to make remuneration by entertaining the English folks in return Otherwise I might be able to tell you of someone but everybody is so poor in these days that I am afraid it could hardly be done gratis.
I sent off a magazine by yesterday’s post Luckily there was one over as we had had one too many of an extra number and it gives a tolerable notion of the Christmas work.

The little bits about the Litany are for helps in the catechising.

Lincolns is turned into a villa and let. I suppose you hear of [Mr Jones Bateman](../persons.html#785)’s death, a great loss to the parish, and old [Mr Chamberlayne](../persons.html#282) died this spring at 91.

His son has not yet come to reside at [Cranbury](../others.html#119), where much has to be done to get the place into order.
I am afraid I do not know much about the House of Hohenstaufen before Frederick the Great.
[Lord Blachford](../persons.html#1252)’s letters are as delightful as he was himself, I knew him well and his most beautiful home in Devonshire.

You should read [Lord Selborne](../persons.html#1129)’s life and letters which are most striking[.] I think his old father’s letters are some of the wisest things I ever read
Yours very sincerely

C M Yonge

[^1]: Envelope addressed to ‘Mrs Barrett Lennard/Dom Vehlow/ In Wultike Priegnitz/ North Brandenburg/ Germany’.

