---
date: '1899-02-07'
display-date: Febry 7th [1899?][[footnote:1]]
from-address: Elderfield Otterbourne Winchester
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2010-06-15 13:44:49'
title: To Sir Walter Besant
wordpress-id: 3394
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#1652)
I have been so much interested by the book you have kindly sent me, in common with rest of the [Author’s Society](../others.html#44) and, having had a little correspondence with you many years ago, when you were editing the English Plutarch, I venture to write, thinking you may care to hear some experiences of a long life of writing, not from necessity but because I had something to say.

The passion for telling a story developed itself early, but began to take shape after reading Alisons [history of the Retreat](../others.html#214) from Moscow. [My father](../persons.html#1631) was an exact and fastidious man and he criticised and condemned every awkward expression in my MS till I could not get on, and it was laid aside for some years.

Then the desire to make the beauty of Manzoni’s [I Promessi Sposi](../others.html#113) known to him led to my translating it - but as another translation came out, the only benefit was the training in language, and when I next attempted original composition, it passed muster though much corrected.

That was my training in style, except the knowing his great admiration for the scene of [Bertram’s return to Ellangowan](../others.html#143), and [Morton’s ](../others.html#192)to his home.

When people ask me how to form a style, I always tell them ‘Take care of your grammar and your style will take care of itself’ - Though I do not know whether this is right, and of course there is an arrangement of syllables necessary -
Nothing taught me so much as to the keeping to a story and the subordination of details as Sir Joshua Reynold’s old [Letters on Art](../others.html#135).

Conversations benefitted by the habit of early youth, in gaieté du coeur of writing down in dramatic fashion the actual talks of a large merry party and I should recommend the habit as giving life to dialogue.

Being a strong and practical man, my Father looked into publishing accounts, and came to most of your conclusions. ‘[The Little Duke](../books.html#20)’ was actually printed at Winchester and published on commission but my Father died suddenly while I was still very young, and being no accountant I was glad to leave things in the hands of [J.W.

Parker](../persons.html#1143) to whom [Sir John Taylor Coleridge](../persons.html#344) had recommended me for the [Heir of Redclyffe](../books.html#15), 1750 first Edition half profits, on his giving up I passed to [Macmillan](../others.html#111) and I do not think I have had any cause to complain.

Curiously however the [Daisy Chain](../books.html#24), though brought out in awkward form, and never advantageously received has in the long run been more successful than any book, though [Heartsease](../books.html#19) reached 2000 the first year.

My books for poor children remained with [Mozley](../others.html#108) for whom I edited the [Monthly Packet](../others.html#52), and for his successors, for more than 30 years, with fair success in its own field, juvenile (not children’s) and religious.

Thus I have had experience in editorship enough to go along with what you say as to the hopelessness of the poor people who begin to write for a purpose - Also in general of recommendations.

Only one of mine succeeded that of [the author of Mademoiselle Mori](../persons.html#1244), who would have done as well without it.

One other curious fact I may mention. ‘John Inglesant’ was sent me from the [Guardian](../others.html#75) with a large parcel of other books.

The small type, the awkward form and generally local or provincial appearance made me suppose it was a strictly private or provincial sort - and left it to the last
Then of course I saw what a remarkable book it was. I [reviewed](../books.html#346) it there, and told others of it, especially [Mr St John Tyrwhitt](../persons.html#1428).

After a time [Mr Gladstone](../persons.html#1653) took it up, and it was the book of the day, though [Mr Shorthouse](../persons.html#1654) had tried in vain to publish it and did so at his own expense.
I sometimes wonder if it lives.

He has done nothing to equal it.

And - if you are not tired of this long letter, I should like to add that often in first efforts there is a charm of freshness and spontaneity not to be found in later work, though that may be really superior and better in workmanship. [Peter Simple](../others.html#193), [Harry Lorrequer](../others.html#194), [Waverley](../others.html#195), perhaps [Pickwick](../others.html#196), [Alice in Wonderland](../others.html#197), [Reata](../others.html#198) are all specimens of what I mean.

One feels the enjoyment of the story-teller before he has to work up to his former performance.

Begging you to excuse me for this long egotistical letter

Yours sincerely

C M Yonge
The Society has twice successfully interfered on my behalf[^2]

[^1]: Tentatively dated on the assumption that \'the book you have sent me\' refers to Besant\'s The Pen and the Book (London: Burleigh 1899).

[^2]: One of these occasions may have been the episode described in \'The Art of Authorship\' The Author I (16 June 1890), 44-46, in which CMY is mentioned among those bamboozled by George Bainton into supplying them with descriptions of their writing practices which he subsequently had published as The Art of Authorship (London: Clarke 1890).

