---
date: '1899-02-10'
display-date: Feb 10th 1899
from-address: Elderfield
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2010-06-30 11:59:25'
title: To Mary Elizabeth Sumner
wordpress-id: 3396
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Sumner](../persons.html#1381)
I hope you had the bundle of materials for the April [Mothers in Council](../others.html#82) that I sent to Claremont, Rudleston, Manchester on the 31st January, for it is time [Wells Gardiner](../others.html#114) had them.

If there is nothing to alter, perhaps you would leave them at his office, writing Mothers in Council on them. I only want to add a most excellent book of The Sunday School Institute
‘Christ in the Catechism’ but that can be done in the proofs.

Here is [Mrs Bartram](../persons.html#1668), Ramsgate Vicarage writing to ask leave for their Organist to set to music ‘God Knows’ out of our October number - I suppose there is no objection, but I do not now remember where it came from.
I shall wait to answer till I hear from you.
I have not had [Mrs Guslett](../persons.html#1669)’s paper

Yours affectionately

C M Yonge
