---
date: '1899-02-27'
display-date: Febry 27 1899
from-address: Elderfield Otterbourne Winchester
manuscript-location: The Rev. Canon Geoffrey Curtis
original-date: '2010-03-09 14:46:24'
title: To Matthew R. Bigge
wordpress-id: 3397
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Sir](../persons.html#2083)
I am much obliged for your letter, with the curious particulars about the Bartons.

The cow is delightful!

But Manydown is not a mistake, it is near Basingstoke, and (I believe) held on the tenure of receiving the Winchester scholars if the plague was in the city. I have known many of the family of Bigg, who two generations ago, took the surname of Wither, on inheriting Tangier Park from the family of [George Wither](../persons.html#1686), the Poet.

The crest is a demi hare, with an ear of Big (barley) in its mouth. I cannot recollect the shield, but I rather think that it had the big or barley in it. I wonder whether yours is the same.

yours sincerely

C M Yonge
That was a bad pen so I will take a better one for an autograph
Charlotte Mary Yonge

[^1]: Pasted into a copy of [John Keble\'s Parishes](../books.html#247) (1899) with the ownership stamp of Matthew R.

Bigge and the bookplate and monogrammed binding of John Tricks Spalding.

