---
date: '1899-04-14'
display-date: April 14th [?1899]
from-address: Elderfield
manuscript-location: 'MS West Devon Area Record Office Ac 1092/22 '
original-date: '2010-03-04 15:31:08'
title: To Mary Yonge
wordpress-id: 3404
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
We had two plants of purple periwinkle once in the old shrubbery part of the garden.

It disappeared, and I tried to introduce it here from [Dogmersfield](../others.html#121), where there was plenty, but it did not live.

Tell Jenny the bar is a line or stripe going horizontally all across the shield [diagram] The wreath is supposed to be the folds or fastening on the top of the helmet on which the crest is fixed and often it is made to bend a little to follow the shape of the head [diagram] [^1]
I never heard that the livery was bound to follow it and I don’t think old George Smith had any red in his.

Perhaps Miss Duke brought it in with the blue, but then it would have been blue and white[^2]
[George](../persons.html#1610) was in the Matabele war, I believe his fort was beyond Bulawayo, but he found that the police are disbanded, rode to Salisbury to see [Sir Richard Martin](../persons.html#1670) who promised to find him employment if he came out again. [^3] That was on Christmas Eve, when he swam a river and had to lie in bed till his clothes were dried.

After that he had a fever in a Portuguese hospital very dirty and where nothing could be done for you without pay, not even anything to eat.
[part of letter removed with signature]
next morning
Fraulein [Marie Heller](../persons.html#1671)
Schäpers Strasse
Berlin
[Miss Finlaison](../persons.html#512) knows that this is a very good person, a friend of [Fanny Patteson](../persons.html#1151)s who wants several English to teach for an hour a day, to pay £25 as premium but to be at no further expense.

You don’t say where [Charlotte](../persons.html#1587) is going I suppose
[rest of letter missing with signature]

[^1]: The discussion relates to the Yonge of Puslinch coat of arms which is ‘Or six ogresses in fesse between three lions saliant gules’.

[^2]: Elizabeth Duke (b.1720) married (1746) John Yonge (d. 1767) of Puslinch, and their heirs quartered the attractive blue and silver Duke arms (‘Per fesse argent and azure three chaplets counterchanged’).

[^3]: Endorsed in another hand ‘he is come home for a time, he joined the Mounted Police’, which suggests that the writer thought he was still alive.

