---
date: '1899-08-12'
display-date: Aug 12 [1899]
from-address: The Old House Dorking
manuscript-location: MS Mrs Clare Roels/78
original-date: '2010-06-29 14:35:39'
title: To Christabel Rose Coleridge
wordpress-id: 3416
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
I am glad there are some signs of life or of decay more properly of poor [A D I](../persons.html#744)- ! I do think there are more and more signs that a 6d phoenix would be welcomed.[^1]
I find the booksellers make all sorts of excuses for not having got it – The [Authors Soc](../others.html#44) want to see my agreement before advising me. I could not find it easily before I left home and was too hot for a hunt. [FMP](../persons.html#1160) has written to offer a visit on the 17th or 18th so I have written to her to meet me and come with me on the 18th I have got the MS of [Ducks Eggs](../books.html#251), I think I can make them much more interesting and longer.

We are nice and cool here now, but I think people must suppose that I dispose of all the [scholarship](../others.html#113) money for the begging letters are endless. [Anna Bramston](../persons.html#195) has photographed all the tableaux before the break up!

Poor [George](../persons.html#1610) at Kimberley is tormented as nephew to a lion, and was invited to go to a book dance as ‘[The Daisy Chain](../books.html#24)’- pretty well for a great black police officer.

So you may tell [Walter](../persons.html#353) to prepare to be invited out as Jack a Lantern. [Helen](../persons.html#1613) returns remembrances. I have had a charming letter from the old [Mignonette](../persons.html#1637) about Maximilian and the Martinswand- and an Italian palace – quite good enough for an article. [^2] The local demon [Mr ffinch](../persons.html#1688) & co are a great success, he reads the lessons so beautifully that I am quite sorry to miss a fortnight of him.

He is warden of a college for ‘decayed gentlewomen’ I should think you would have heard of it.
[Maurice](../persons.html#1630) and [Maude](../persons.html#1629) have the funniest little cottage at Fleet, in the middle of purple heath
your affectionate

C M Yonge
Poor Lanty!

[^1]: They were hoping that the [MP](../others.html#52) would be revived in a cheaper form.

[^2]: The legend that the emperor Maximilian I (1459-1519) climbed the Martinswand near Innsbruck is referred to in CMY’s novel [The Dove in the Eagle’s Nest](../books.html#62) (1866) and is also the subject of one of Schubert’s songs.

