---
date: '1899-08-15'
display-date: ' [15 August 1899]   '
from-address: ''
manuscript-location: MS Mrs Clare Roels/79
original-date: '2010-06-30 07:25:00'
title: To Christabel Rose Coleridge
wordpress-id: 3418
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C ](../persons.html#329)
I am sure unless we could get an amount of subscribers enough to start a new Church [Packet](../others.html#52) with security, it would be vain.

Could we find out?

Otherwise [Sir W Besant](../persons.html#1652) is right, and we must acquiesce. I would make [Duck’s Eggs](../books.html#251) a fresh start for it is needed, but I think it is not hopeful, sorry as I am, especially that Church should be a decided drawback.[^2] If it eschewed Controversy Churchbuilding charity and saints I should think it might get on But men such as [Canon Ashwell](../persons.html#68) are hard to catch in these days [FMP](../persons.html#1160) has changed her mind and says she won’t come, but is going to India . I have written to beg her to meet me at Waterloo and come home with me on Friday but I don’t know if she will.
I have excogitated a new end for Ducks Eggs working in the old friends.

All were going out to Carrigaboola, via San Frisco- Magdalen- Paula and all, with Angela and the Bishop – also Bernard who – on holiday in England was suddenly wanted for a Travis & Underwood emergency, involving California Ship either wrecked or on fire not far beyond Liverpool ([Annie Moberly](../persons.html#1024) wanted a woman to hide for the sake of saving a more valuable life of Man) Angela dies – putting her Sisters bonnet on someone else.

All the women are saved, but Bernard is struck down by a spar left unseen, insensible He comes to himself to find Angela hanging over him, the golden curls looking like her childhood.

They think they are going together, but a Ewemouth collier picks them up in time- Bernard lifted into unconscious but Angela falls in lifting him into the sea
Phyllis had had to be left at home- So you have the account in Bernard’s words to Clement
your affte

C M Yonge

[^1]: With envelope addressed to Miss C R Coleridge/ Cheyne/ Torquay and postmarked Dorking 15 August 1899.

[^2]: The working title for the novel which became Modern Broods (1900).

