---
date: '1899-09-01'
display-date: Sept 1 [1899?]
from-address: Elderfield Otterbourne
manuscript-location: MS Mrs Clare Roels/84
original-date: '2010-10-08 11:16:56'
title: To Christabel Rose Coleridge
wordpress-id: 3422
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C ](../persons.html#329)
I am doing my best to write to [Macmillan](../others.html#111) I think it is our only hope and rather a forlorn one- and explaining some of its history and scope hoping not to say too much or too little, nor to shew personal feeling[^1]
But I am sure it is a thing to be considered how to have a high class magazine for young persons, as I have been telling him and of the general wail for it!

So we launch the life boat or rather the rocket-
I think it is better for you to be out of sight of poor Lanty-
[Margaret Roberts](../persons.html#1244) and [Di](../persons.html#841) go to Min y don today if that is the name of it
We had a splendid school feast yesterday, neither too hot nor too cold nor too damp nor too anything.
I have had a famine of books and read up all the old ones of my own, and the result is that Arthurine /(Come to her Kingdom)\ appears at Rockquay and utters an advanced woman’s address to the High School and other auditors, which fires Agatha not unwholesomely Arthurine goes rather in the [Lady Warwick](../persons.html#2198) /and emancipation\ style Bessie Merrifield follows up with the duty of emancipated woman to Church &c[^2]
The byplay is that her naughty brother Hal – of [Stokesley](../books.html#40), had been Magdalen’s lover /very ?haginlory- He had been sent out to Canada to his brothers had got into speculations with a swindling man fled with him, carrying off his brother’s savings, and had never been heard of more except that after years, the sum was returned to them without a clue.

It turns out finally that he – name changed- had been Fulbert Underwood’s partner in a sheep farm- and had nearly married Angela, only Fulbert was sure there was an old ?sclutrose.

Then all as I said before. I suppose you would not like to do a new woman bit for Agatha with Dolores.

Or think of some ?parharshy
your affte

C M Yonge

[^1]: This was an attempt to enlist the help of Macmillan in reviving the [Monthly Packet](../others.html#52).

[^2]: Arthurine was the heroine of the story \'Come to her Kingdom\' which had appeared in the Christmas Number of the [Monthly Packet](../others.html#52) (1889) and was reprinted in [More Bywords](../books.html#209).

It is set in the same village as the earlier story The Stokesley Secret and includes some of its characters.

As the letter indicates, these reappear in the novel under discussion, [Modern Broods](../books.html#251), which also includes old friends, like Fulbert and Angela, from [The Pillars of the House](../books.html#109).

