---
date: '1899-09-12'
display-date: Sept 12  [1899?]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/86
original-date: '2010-10-08 12:01:01'
title: 'To Christabel Rose Coleridge '
wordpress-id: 3425
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
Did you ever hear that the treaty between Fairfax and the Cornish army was signed at Heaths Court. I never heard of it but Sir Mount Stuart Grand Duff staid with [John](../persons.html#343) and says it was signed in the old part of the house[^1] Perhaps dear old [May](../persons.html#351) was ashamed of such doings, and I should not have thought the house so old, as I remember it, and I am sure I never heard of it. I should have thought the Manor house more likely.

John’s reading seems to have delighted him very much.

Marion Crawfords Ave Roma Immortalis is the book that has impressed me this autumn. [Helen](../persons.html#1613) has been reading the Marie Corelli[^2] She says there are fine things in it, but she does not like it much.

Miss Knight wants me to write a review of a book of [Miss Price](../persons.html#1209)’s from the [Sunday Magazine](../others.html#232) which I have not got, but I suppose it will come.

Poor [A D I](../persons.html#744), I wonder what has become of him!

His uncle’s offer was a good deal better than the division of £98 between creditors for £7000 - How could he go on so long?
I have had a nice ‘sharpeing of iron’ with [Annie Moberly](../persons.html#1024) but she could only stay three days. I am afraid the C Y scholar has not got another scholarship to help her to Oxford, only twice proxime accessit.[^3] I fancy her work had just the want that comes of the not being cultivated from the cradle.

It seems to have been rather ?fire ?ready.
I hope your [Mr Jacob](../persons.html#747) will be a man for schools.

The Code desires children to be taken out walking and made to observe.

They –ie- the 1st class, got 50 flowers out of the lane yesterday I went the day before, and had all the names to tell them - I then learnt that yarrow is ‘good for coughs[‘]
your affectionate

C M Yonge
The Cats article is very funny but the ladies will be at you for its disemprovingness and how could [Mrs Clay Finch ](../persons.html#302)leave out ‘our good old Cat Earl Tomlemyne’, and the Columbind and Poets Cat[^4]

[^1]: CMY had evidently been reading Sir Mountstuart Grant Duff, Notes from a Diary.

He describes, I, 192-3, a visit to Heath\'s Court in September 1887 when he discussed reading with John Duke Coleridge and mentions the treaty being signed.

[^2]: Perhaps Marie Corelli et aliae, The Modern Marriage Market (London: Hutchinson 1898).

[^3]: The first [Charlotte Yonge scholarship](../others.html#113) from Winchester High School seems to have been held by [Amy Aubrey Locke](../persons.html#893) (1881-1916) who is listed in the 1901 census as a student at Somerville College, and who was the daughter of Alfred L.

Locke, head porter of Winchester College.

She published several historical works.

[^4]: The ‘good old cat, Earl Tomlemagne’ occurs in Robert Southey, ‘Epilogue to the Dragon’.

