---
date: '1899-09-18'
display-date: Sept 18th [1899]
from-address: Elderfield Otterbourne
manuscript-location: MS  West Sussex County Record Office/ Add. 16,944/2
original-date: '2011-10-18 10:52:44'
title: To  Maria Edith Walker
wordpress-id: 3426
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Madam](../persons.html#2234)
I have found my Puzzle for a Curious Girl - 2d edition, 1805, given to my mother ‘Miss Fanny Bargus’ as her name is written.[^1] The illustrations are cuts, very tightly dressed, the father in knee breeches, the servant opening the carriage door in a cocked hat. I was guilty of painting the first cuts very badly indeed
I have also ‘the Little Queen’ in the Children’s Miscellany where are also Little Jack and Philip Quarl.[^2] I did not know that it had been attributed to Addison or an imitator.
‘The History of a Great Many little boys and girls’ has been the favorite [sic] of 4 generations.

Where Tommy Piper was put into a tub by Mr Makegood, and Miss Mary Anne Selfish placed in the pig stye- Miss Jenny Meek first appears in the Village School, in my books.

Was there a previous one?

These I have in a reprint, and I know an original Mrs Teachem, belonging to my cousin.[^3] I have also in a tiny gilt book, really old Memoirs of a Pincushion also Memoirs of a Peg top and The Holiday Present where the virtuous girl keeps her feet in the stocks when her mamma leaves the room, but the naughty one breaks her back and never grows any taller
[Mrs Davenport](../others.html#239) I have seen, but it did not belong to me. I think the West Indian girls were always naughty, being spoilt by their slaves

yours sincerely

C M Yonge

[^1]: CMY had earlier (9 September 1899) written to Walker about her reprinting of this book in A Storehouse of Stories: ‘I could lend it to you- or my own old copy of ‘the Puzzle for a curious girl’ which I inherited from my mother, and is somewhere in the house, though I cannot lay my hand on it without a search.

It has a red back, and illustrations at the top of the chapters, in the style of 1810-20, I should say - but of course they may have been made for the edition.’

[^2]: The Renier collection in the National Art Library, Victoria and Albert Museum, holds this duodecimo copy of The Infant’s Miscellany (?1801) with ownership inscriptions ‘F.M.

Bargus 13 February 1801’ and erased ‘C.A.

Colborne’ and the bookplate ‘From the Library of Charlotte M.

Yonge’.

[^3]: Perhaps Sarah Fielding, The Governess, or, Little Female Academy: Being the history of Mrs.

Teachum, and her nine girls.

With their nine days amusement.

Calculated For the Entertainment and Instruction of Young Ladies in their Education. (London: Millar 1749).

But perhaps the context suggests another book by one of the Kilners, or a contemporary?

