---
date: '1900-01-06'
display-date: Jan 6th 1900
from-address: Elderfield Otterbourne
manuscript-location: MS  West Sussex County Record Office/ Add. 16,944/6
original-date: '2011-10-14 19:41:19'
title: To  Maria Edith Walker
wordpress-id: 3438
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Miss Walker](../persons.html#2234)
Did people in 1800 think as much about war as we do?

In fact I think they had a respite then, while the Peace of Amiens prevailed. I knew the old [Dean of Winchester ](../persons.html#542)who had been at a levee of the [First Consul](../persons.html#2207) in that year with [Sir James Mackintosh](../persons.html#2208). I made my niece look at him (the Dean) he was 90, by way of making a link
I have a Peacock at Home with the badly painted pictures you describe /1807\, but the drawings were [Mulready](../persons.html#2206)’s and are excellent the poem is Mrs Dorset’s.
[Griffiths and Farran ](../others.html#233)republished it without the paint, and one sees how good they are.

The Butterfly’s ball by Roscoe was the first but the Peacock is much cleverer.

The Lion’s Masquerade is not quite equal to the others, nor is the Elephant’s Ball.

They had all fallen into the way of imitations

yours sincerely

C M Yonge

[^1]: Catherine Dorset, The Peacock ‘At Home’: A Sequel to The Butterfly’s Ball (London: Harris 1807).

[^2]: William Caldwell Roscoe, The Butterfly’s Ball and the Grasshopper’s Feast (London: Harris 1807); Catherine Dorset, The Lion\'s Masquerade: A Sequel to The Peacock at Home (London: Harris 1808); W.B, The Elephant’s Ball and Grand Fete Champetre (London: Harris 1807).

