---
date: '1900-02-01'
display-date: Feb 2d [1900]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/89
original-date: '2010-10-13 08:14:19'
title: To Christabel Rose Coleridge
wordpress-id: 3442
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
Your paper on Novels is excellent, I only got it yesterday, as our paper boy is a blunderer.

The three ladies are capital and the letting off the colourless novels without principles at all is quite true, and to the point. [Miss Blackburne](../persons.html#160) wrote me an account of her [Authors club](../others.html#234), I should not like to have such a thing to manage. [Miss Cholmondely](../persons.html#292) is the head I wonder whether she will be an influence I am vexed at that article about [E A Freeman](../persons.html#523) and have written to Miss Blackburne about it- He was a generous man but used strong language, and inaccuracy was alike a red rag to a bull to him
Poor Peewits! I am afraid my yellow pussy has gone the way of all cats here in the preserved woods- [Rosie](../persons.html#418)’s [Dove](../books.html#62) is not from my help – we do read it but only a chapter a week, and her answers have gone on far ahead[^1] She gets very high marks for her Church history but less high for St Mark, not mistakes but apparently not full enough - However though the Lusus Naturae does not go in for a prize, I don’t suppose she will get it.

She is at Henry V now, which is more difficult.
I think too little time is given for a class once a week.

Reading with Rose, we have only got to Henry VII and not very far into the Dove – and if I had a class of less quick girls I should not get on at all.

Poor Peewits!
your affectionate

C M Yonge

[^1]: Coleridge annotates a reference to Rosina (14 May 1900) ‘her kitchen-maid, whom she was preparing for the [G. F. S.

Reading Union](../others.html#211)’.

Rosina Dewsall (b.

Lambeth 1881), a housemaid to Maurice Yonge at Elderfield in the 1901 census, is probably referred to here. CMY\'s novel The Dove in the Eagle\'s Nest was one of the set texts for the Reading Union, and Coleridge may have suggested that the author\'s tuition gave Rosina an advantage.

