---
date: '1900-04-11'
display-date: April 11 [1900]
from-address: Elderfield
manuscript-location: MS West Devon Area Record Office Ac 1092/21
original-date: '2010-10-18 12:34:36'
title: To Mary Yonge
wordpress-id: 3451
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I have just heard from [Jane Moore](../persons.html#1042).

She is at Ramsgate, where her[ husband](../persons.html#1041) has been sent to get over an attack of bronchitis from 7 hours work at Aldershot!

She and I have had a great blow in the sudden loss of [Lady Susan Blunt](../persons.html#164).[^1] You know she was the General’s cousin, and the daughter of my [mother](../persons.html#1606)’s old friend, [Lady Nelson](../persons.html#2219) We always so enjoyed meeting as we did at[ G F S ](../others.html#23)and [Mother’s Union](../others.html#31) Meetings.

There are no children, and what will poor [Mr Blunt](../persons.html#2077) do at Highclere Vicarage She was such a thorough, parish worker, so good and like her good old mother
Jane says Frank is gone out to S Africa again, and Florence is at the Modder River with a detachment of the Army nurses.[^2]
My doctor took his leave of me yesterday and I may do anything but go out after 4 till May, or in bad weather and [Helen ](../persons.html#1613)keeps guard over me!

She stays till the middle of next week when [Maurice](../persons.html#1630) and [Maude](../persons.html#1629) come for a week- They have been seeing Jane at Aldershot
Such a wet evening
your affte
CMY

[^1]: Lady Susan (Nelson) Blunt died 8 April 1900.

[^2]: Frank and Florence were presumably relations of Jane Montgomery Moore, or perhaps of her husband.

