---
date: '1900-03-27'
display-date: March 27 [1900]
from-address: Elderfield Otterbourne
manuscript-location: MS West Devon Area Record Office Acc No 308
original-date: '2010-10-18 13:32:33'
title: To Mary Yonge
wordpress-id: 3454
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
I hope [ Sydney](../persons.html#2178) is as much better as I am, I believe I should be well if the East wind would mitigate itself, but we had showers of snow yesterday, and more looks possible today. [Helen ](../persons.html#1613)has been so good as to come down and look after me as her [mother](../persons.html#1604) has [Mrs Mansfield](../persons.html#952) (Georgina Halliday) staying with her Her husband is an army doctor, and ordered out – and she is a niece they are fond of.

She has been at Aldershot where the [Moores](../persons.html#1041) are in a temporary lodging, as [Lady Audrey Buller](../persons.html#2223) does not turn out of Govt House -–[^1] She – G Mansfield says it is very troublesome, having militia and volunteers who know nothing of real army discipline and don’t like being pulled up –
Helen had a nice courteous letter from [Princess Christian](../persons.html#2222) in her own hand to thank for the things she sent.

Fancy a lady sending for the soldiers a lot of old envelopes to be turned out and used to draw upon! I hope the useful things do get out and not delayed by government arrangements
What flowers [Charlotte](../persons.html#1587) must be seeing
your most affectionate

C M Yonge

[^1]: General Montgomery Moore had succeeded to the Aldershot command on the departure for South Africa of General Sir Redvers Buller.

