---
date: '1900-03-30'
display-date: March 30th [1900]
from-address: Elderfield
manuscript-location: MS West Devon Area Record Office Acc No 308
original-date: '2010-10-18 13:41:16'
title: To Mary Yonge
wordpress-id: 3455
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mary](../persons.html#1626)
You will like to hear that [Maurice](../persons.html#1630) and [Maude](../persons.html#1629) have had tea with [Jane Moore](../persons.html#1042) in her hufet at Aldershot, which Maude says is exceedingly pretty, but they are having very hard work for 40000 men are expected at Aldershot altogether, and it generally holds 15000 and those regular soldiers whereas all these have little notion of more than a summer diversion and are very hard to bring into discipline- I do not know if [Ulick](../persons.html#325) is with them.[^1]
I am to my own feeling quite well, only still hoarse, and they wont let me outside the house till the wind changes – and we had 10 degrees of frost last night - They have been having snow at Fleet –
So [Joubert](../persons.html#786) is dead. I believe he was more of a gentleman in his ways than old [Kruger](../persons.html#826) but I am afraid there is still a great battle to come-[^2]
I must have made a great blundering in directing letters to you and [Helen](../persons.html#1613) -- One place seemed to flow out of the Miss Yonge
I hope [Sydney](../persons.html#2178) is getting better
your affte

C M Yonge

[^1]: Ulick was probably Jane’s nephew Major the Hon.

James Ulysses Graham Raymond Colborne (1863- 1955), later 4th Lord Seaton.

[^2]: Piet Joubert (1834-1900), commander of the Transvaal army, and Paul Kruger (1825-1904) were leaders of the Boers.

