---
date: '1900-05-01'
display-date: May 2d 1900
from-address: Elderfield  Otterbourne Winchester
manuscript-location: MS Princeton University, Parrish Collection
original-date: '2010-10-18 13:57:41'
title: To Mrs Bothamly
wordpress-id: 3457
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear [Madam](../persons.html#176)
I am much perplexed about the article ‘Want of Confidence’ - I had two so called sent to me, purporting to be condensations of a lecture given at Winchester, one certainly written by [Mrs Field](../persons.html#507).

When it appeare[d] a gentleman wrote and claimed it as his own abstract but Mrs Field was able to prove it was hers, and as yours had the same title I am afraid the copy in type must have been broken up under the impression that it was the duplicate account of the lecture for I cannot find it either in proof or M S and it is the only way I can account for its disappearance.[^2]
I am very sorry not to be able to restore it
If you can tell me how many pages it occupied I will send you some small compensation,

Yours truly

C M Yonge

[^1]: Envelope addressed to \'Mrs Bothamly/ The Crossways/ Bromley\'.

[^2]: The contribution was evidently to [Mothers in Council](../others.html#82).

