---
date: '1900-05-12'
display-date: May 12 [1900]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/95
original-date: '2010-10-18 14:17:49'
title: To Christabel Rose Coleridge
wordpress-id: 3458
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
I have got a letter for [M in C](../others.html#82) from [Canon Lias](../persons.html#227) about Red Pottage, highly contrary to yours, and which the Sumners approve He goes on the unfitness of such subjects for women’s writing or reading, and certainly I should have thought ‘incline mine heart to keep this law’ went against either inventing or making people read them and so do you- At least I recognize you as Undine You will think I am very hard on your friends but at any rate we are perfectly agreed about [Mary Bramston](../persons.html#198), and I have been obliged to write an article about Higher Criticism and the Dawn of Revelation [Mrs Sumner](../persons.html#1381) and the Council were at it yesterday at Westminster I have not heard about them yet, the [Bishop of G](../persons.html#1382) could not go, having broken the bones of his wrist, falling down from catching his foot in a mat inside the transept door of the Cathedral.
I really think I am quite well now, as I don’t get tired with ordinary walks.

Everything is splendid, such dainty young green, such apple blossom, and my round tall clump has a circle of forget me nots like a giant Christmas card
your affte

C M Yonge
I profited by your advice to make [my missionary](../books.html#250)s mother marry again.

He is just going to [St Augustines](../others.html#13).

He will go to China and be well out of your man’s way
