---
date: '1900-08-24'
display-date: Aug 24 [1900?]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/103
original-date: '2010-11-04 10:29:01'
title: To Christabel Rose Coleridge
wordpress-id: 3468
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
Do you know that [Innes’](../persons.html#744)s stock has been taken by [Ward & Lock](../others.html#235)? I heard it second hand from a lady who has been enquiring after her goods. I suppose you had the letter asking creditors to accept 5 per cent. I asked what was become of the remains of what was [half mine](../others.html#160) and half theirs and was told that Tanner did not know. I think we are very ill used!
I am in a rage too for the conceited reader scored my [Making of a Missionary](../books.html#250) all over with most foolish corrections, which I fear confused mine, and then sent no revise, though I wrote Revise on it, and when I at last enquired for the 2o proofs, I found it was printed off. I think he must be a new hand, and have sent him word that it is quite unprecedented!

Tomorrow is our School Treat at the Grange, and we quake at the clouds.

Almost all the teachers are away- there is a very nice clergyman’s widow come to the new houses who teaches the SS boys and even sits with them.

She asked one if [Rolfe](../persons.html#1256) was the school master, and he answered ‘Yes and the best schoolmaster within 50 miles-‘ rather a large order! [Miss Finlaison](../persons.html#512) has let her house for the holidays to some Welsh people whose father was a Bond and his sister an Ovate.
[Mary Morshead ](../persons.html#28)spent a fortnight here, and is now gone to her sisters [Annie Moberly](../persons.html#1024) comes for a few days next week so I shall get shaken up a little.
your affectionate

C M Yonge
