---
date: '1901-02-04'
display-date: Feb 4th  [1901]
from-address: Elderfield
manuscript-location: MS Mrs Clare Roels/109
original-date: '2010-11-11 13:44:39'
title: To Christabel Rose Coleridge
wordpress-id: 3478
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [C C](../persons.html#329)
I had not read the Notes on Modern Thought and I don’t know what [Prof Collins](../persons.html#2250) is, though looking at them in a hurry on your letter, I don’t like the looks of them.

But would it be well for you and me, and perhaps [Lady Frederick Bruce](../persons.html#215) to remonstrate on the danger. I think [GIB](../persons.html#160) minds us, and I feel rather pledged to the ‘gates’ for [Reason’s Why](../books.html#252), which I have written on to 9 or 10 chapters and I think is wanted - if anyone reads the [Churchwoman](../others.html#64), I don’t so much mind Kg Charles his I think /the paper\ him exaggerated, and I never should belong to the White Rose in spite of [Mary Morshead](../persons.html#28), though I do wish for the Memorial.[^1] It is funny to remember what a radical GIB was when she wrote ZigZag! I believe it was Hawarden.

But she is under [Mr Villiers](../persons.html#2252) now, and has a charming class of his school children.

Are you sure [Mrs Halliday](../persons.html#616) is ill, we have heard nothing of it, and I expect it is the Russian scandal of [Mrs George Yonge](../persons.html#2116) at Bishopstoke (whence by the by the Hallidays are departed into Somersetshire).

She, poor thing, Mrs George Yonge is, I fear dying of complaint of the heart, and [Lottie](../persons.html#1588) is there doing what she can for poor broken hearted [George](../persons.html#1611) (her uncle)[^2] The direction is Stoke Lodge, Bishopstoke, Hants.

She carried off books to write your article if she has time, which I doubt. I think it will end in her living there.

We have had our Religious Inspection and my boys were perfectly senseless!

Tomorrow is the girls, and we hope for better things, I believe boys brains between 10 and 12 turn to cricket &c.

It rained furiously all Saturday here, I am glad it did not in London.

And the Navy came out beautifully – but it is only alas!

Did you hear of the little Dublin tramp whom a gentleman watched, laying down his only penny for a bunch of violets which he scattered over her name[^3]

your affte

C M Yonge

[^1]: This is evidently a discussion of the current issue of The Churchwoman (1897-1905), edited by Gertrude Mary Ireland Blackburne (1861-1951).

Mary Morshead was an enthusiastic supporter of [Charles I.](../persons.html#1768)

[^2]: George Edward Yonge (1824-1904) was CMY’s first cousin, son of her Eton uncle.

His wife was Lucy Acland and they had no children. ‘Lottie’ was Charlotte Fortescue Yonge, his niece.

[^3]: The state funeral of [Queen Victoria](../persons.html#1694) on 2 February 1901.

