---
date: '1884-12-26'
display-date: Decr 26th [after 1884?]
from-address: Elderfield Otterbourne
manuscript-location: MS Charlotte Mitchell/31
original-date: '2011-10-10 11:25:19'
title: To an Unknown Woman
wordpress-id: 3504
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

Dear Madam
I am very sorry not to have answered your letter sooner, I put it aside to enquire about [Mrs White](../persons.html#2392), and in the hurry of Christmas preparations it was forgotten.

She is not strictly an inhabitant of this parish, but of Compton- where I believe [her husband](../persons.html#2393) is man to [Mr Baldwin ](../persons.html#98)the maltster.[^1] I had heard that she took in washing, and I believe that she is respectable but I know nothing of her capabilities. [Mrs Baldwin](../persons.html#99) might be able to tell you
I remain &c

C M Yonge

[^1]: James Baldwin (b.

Tanworth, Warwicks. 1824/5) is recorded in the 1881 and 1891 censuses as a maltster living at Compton with his wife Josephine (b.

Solihull 1826/7), in the former year ‘employing 2 men & 2 boys’.

Mrs White might be Ann (b.

Michelmersh 1857/8), wife of Thomas White (b.

Michelmersh 1851/2), variously ‘steam ploughman’ and ‘engine driver’, living at Silkstead, Compton in 1891.

