---
date: '1865-01-01'
display-date: '[1865]'
from-address: ''
manuscript-location: MS fragment Charlotte Mitchell/13
original-date: '2010-06-26 10:33:26'
title: To an unknown person
wordpress-id: 3574
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

. . . [Barnacle](../others.html#89) article rather in the style of the Spring of the poets, and we wanted you to laugh with us. I think you know the [Gatty](../persons.html#549)s, so I conclude you do not want an autograph from that quarter.
I am glad [Dr Harris](../persons.html#629) was able to go to [George](../persons.html#625)’s wedding, but I shall be glad to hear that he is safe back again[^1] Poor Hursley has been very forlorn all the winter but its [squire](../persons.html#669) came back last week, and its [Vicar](../persons.html#798) comes on the 10th

yours sincerely

C M Yonge

[^1]: The Rev.

Joseph Hemington Harris (1799/1800-1881), Vicar of Tor Mohun, Torquay, was married to Jane Yonge, sister of the Rev.

John Yonge of Puslinch.

His son the Rev.

George Collyer Harris (1833-1874) married Percy Primrose in London in 1865 (June 1865).

