---
date: '1885-07-29'
display-date: July 29th [1885?[[footnote:1]]]
from-address: Elderfield
manuscript-location: 'MS Harvard University, Houghton Library '
original-date: '2010-03-02 14:15:44'
title: To Charlotte Fortescue Yonge
wordpress-id: 3587
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Lottie](../persons.html#1588)
Many thanks for the Water Soldier who came in excellent order.[^2] Fancy [Arthur Yonge](../persons.html#1583) being like [Julian](../persons.html#1624).

He was in a very different style in his younger days being very dark and always carrying his chin rather in the air but I think his beard must have made a difference and I know there always is a tendency in us to be more like the Duke Yonges than anyone else.

My [mother](../persons.html#1606) and [Aunt Duke](../persons.html#1591) were alike though no relations.

Did you see Arthur’s very pretty [daughter](../persons.html#1584) who is living with the Masons to go to the [High School ](../others.html#51)at Winchester[^3] The [Moberlys](../persons.html#1019) are quite uncertain what will become of them, as they have not yet been able to find a house.

We hoped to have the [Bowleses](../persons.html#182) here in August, but they cannot get their duty done, and have had to put it off. [Joan](../persons.html#388) is still with them. [Mrs Beck](../persons.html#130) is staying here till she goes to the Christening of her poor little grandson, who happily is a fine prosperous child[^4]
your affectionate cousin

C M Yonge

[^1]: This letter clearly postdates the marriage of Louisa Alethea Yonge to the Rev.

Henry Bowles in 1884 and since Arthur Duke Yonge’s only daughter was born in 1870/1 is unlikely to be later than 1888.

It seems most likely that it was written immediately after the death of the [Rt.

Rev.

George Moberly](../persons.html#1015) on 6 July 1885 and the death of Mrs Beck’s son [Edward Walter](../persons.html#1461) on 5 May 1885.

[^2]: A specimen of the plant stratiotes aloides.

[^3]: Alethea Yonge (b.

Italy 1870/1).

[^4]: Gertrude Walter’s stepmother Caroline Beck had two children, Edward Walter (1854-1885), an army officer who died in an accident, and [Herbert Simcoe Walter](../persons.html#1463) (1855-1897).

The grandson was perhaps born posthumously.

