---
date: '1893-01-01'
display-date: '[dated by Coleridge after 1893]'
from-address: ''
manuscript-location: MS location unknown.  Printed in Coleridge, <i>[[otherbook:40]Life]</i>
  p. 325-326
original-date: '2010-02-22 11:48:56'
title: To Charlotte Anne Elizabeth Moberly
wordpress-id: 3592
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Annie](../persons.html#1024)-
I can only be quite sure that [Mr.

Keble](../persons.html#798) never taught me at my Confirmation anything about Fasting Communion.

When he first came monthly celebrations began here at mid-day the last Sunday in the month, his idea then being that he would come over and assist.

So Hursley was fortnightly mid-day first and last Sundays; Ampfield began on the third.

Then it was begun at Hursley early on the intermediate Sundays, and I remember its being said that the poor women could come to it then.
I am sure he never commended Fasting Communion to me, nor lamented the omission, though I have a dim idea that once when talking about the expedience of the presence of non-communicants, which he deprecated as a rule, he mentioned the wishing to fast as a possible reason with some, but I am not sure.

Early celebrations were certainly never insisted on in this church in his time, but [Mr.

Wither](../persons.html#1544)'s refusal to me when I proposed it was after his death-- I do not think it was thought of before. I cannot tell about his own practice, the only time I spent a Sunday at Hursley being when I was very young.[Jimmy Young](../persons.html#1634) would know better.

It is quite possible that his habits grew more strict as time went on, but I am quite sure he did not teach me to practise it, and that he deprecated the attendance without communicating as a rule (for I discussed it with him), only wishing for it for children as part of their immediate preparation for First Communion.-
Your affectionate
C. M. YONGE.
