---
date: '1887-01-01'
display-date: '[January 1887]'
from-address: ''
manuscript-location: "MS location unknown. Printed in the <i>[[other:2]Girls\u2019\
  Friendly Society Associates\u2019 Journal and Advertiser]</i> (January 1887) 7."
original-date: '2010-05-19 09:29:18'
title: To the Editor of the <i>Girls' Friendly Society Associates' Journal</i>
wordpress-id: 7902
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

MADAM.
-‘A Berkshire Associate’ writes, that a girl was censured at the Winchester Conference for giving her premium to her mother, and that no one defended her.[^1]

Let me state that mention of the fact was not heard at the table where the members of Council sat, and it is not mentioned in the notes of the report.

If it had been heard there would have been some inquiry whether the mother was in any special need, such as would have rendered the act desirable and merciful.

If not it might have said that the [G.F.S](../others.html#23). was meant primarily for daughters not mothers; and that though the individual deed might be commendable and noble, it was not to be a precedent. A Member who spent her premium on an ostrich feather was mentioned; and perhaps the other case was lost in the shock thus created.

I remain
C. M. YONGE.

[^1]: Premiums were small loyalty payments by a branch to a member who stayed in her post for two or more years.

