---
date: '1894-01-01'
display-date: '1894'
from-address: ''
manuscript-location: MS location unknown.  Printed in <i>Friendly Leaves</i> (1894),
  180.
original-date: '2010-05-24 10:57:03'
title: To the members of the Girls' Friendly Society
wordpress-id: 8652
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

DEAR GIRLS,-
I have just been very much shocked by being told by a person, on the authority of her maid, that it is very seldom that maid-servants say any prayers in the morning, doing their devotions over-night, and sometimes thinking family prayer suffices. I know that there is often a terrible hurry in the morning, and that it is very hard for a sleepy girl to wake and dress tidily, with a mistress or upper servant hurrying her.

But surely you could say, as you got out of bed, within yourself, ‘O God, let me do all to Thy glory to-day!’ and hardly three minutes would be needful to whisper even the Lord’s Prayer and the Second Collect for morning prayer.

Then you would be far safer from doing or saying anything wrong, and be under God’s protection in the many dangers of the day with knives, glass, lamps, and all.

I do entreat you, as an earnest friend, to make this an unbroken habit, if you can do no more.

C. M. YONGE

[^1]: This letter appeared in the [GFS](../others.html#23) magazine [Friendly Leaves](../others.html#71)under the heading \'Morning Prayers\'.

It is signed in the way she normally signed letters, but not publications.

