---
date: '1896-04-04'
display-date: Easter Eve [4 April 1896]
from-address: Elderfield Otterbourne Winchester
manuscript-location: MS Charlotte Mitchell
original-date: '2010-05-27 10:08:03'
title: To Sarah Harriet Selwyn
wordpress-id: 9109
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

My dear [Mrs Selwyn](../persons.html#1297)
I have been begged to find out whence came a beautiful prayer that was given to all your friends at your first start to N Z.

It really seems like going into the last century, or the primitive Church, and I do not suppose there is anybody who could tell me now, not even [Fanny Patteson](../persons.html#1151), so I am venturing to ask whether you can remember.

The new [Bishop of Osaka](../persons.html#85) (Japan) has had it printed on his farewell cards sent to all his friends.

He was to land either last Monday or on Good Friday at Nagasaki, a considerable difference in speed since your time![^1]

I hope you are well.

This warm winter has been very kind to many and we have hosts of primroses for the decorations to which I am just going

yours affectionately

C M Yonge

[^1]: In fact it was reported in The Times (30 May 1896) that the Awdrys did not reach Japan until 27 April.

When Mrs Selwyn first went to New Zealand in 1842 she travelled by sailing ship round the Cape; by the 1890s the Suez Canal (1869) and the steamship had shortened the journey by several months.

