---
date: '1898-12-01'
display-date: ' [December 1898]'
from-address: ''
manuscript-location: "MS location unknown. Printed in the <i>[[other:72]Girls\u2019\
  \ Friendly Society Associates\u2019 Journal and Advertiser]</i>  (December 1898)\
  \ 256."
original-date: '2010-06-04 13:34:14'
title: "To the Editor of the <i>Girls\u2019 Friendly Society Associates\u2019 Journal</i>"
wordpress-id: 9348
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

SERVANTS AND EVENING CLASSES

Madam,-
I think the subject has been mooted before, but perhaps a reminder is wanted to Associates, especially in towns, to come to an understanding with mistresses, especially those of the upper classes, as to what evening invitations may be sent to their servants.

Evening entertainments and evening classes are most desirable for business girls, those living at home, and even those who have evenings out among domestic servants, but in a well-regulated household, where late outings are undesirable, it is unsatisfactory to have frequent invitations coming to unsettle a young servant.[^1] It is not an old story like some occasions, but really good mistresses object to hiring a [G.F.S.](../others.html#23) girl, because these invitations make a perplexity in the house.

Either the girl is disappointed, or the other servants are discontented because they are not allowed the same amount of outings.

The question should be settled once for all with the mistress.	

C. M.

Yonge.

[^1]: CMY was probably rather more flexible with her own servants than this letter would suggest.

After her death, her cousin, Charlotte Fortescue Yonge wrote in Mothers in Council 9 (July 1901): \'Her maid-servants and her gardener knew well that any household arrangements would be held subservient to Church and parish functions.

Were there to be any Special Services or Church Decorating, Penny Readings or Parish Concerts to be attended or taken part in, they all knew their mistress would wish they should be there.\'

