---
date: '1890-06-01'
display-date: June 1st, 1890.
from-address: ''
manuscript-location: "MS location unknown. Printed in the <i>[[other:72]Girls\u2019\
  \ Friendly Society Associates\u2019 Journal and Advertiser]</i>  (June 1890) 103."
original-date: '2010-06-04 19:43:02'
title: " To the Editor of the <i>Girls\u2019 Friendly Society Associates\u2019 Journal</i>"
wordpress-id: 9403
---

**Date:** {{< meta display-date >}}  
**From:** {{< meta from-address >}}  
**Manuscript Location:** {{< meta manuscript-location >}}  

OUR MAGAZINES

Dear Madam,-
To please every one is avowedly impossible, V.C.’s complaint of the stories of foreign life in [Friendly Leaves](../others.html#71) only convinces me that it would be well to amalgamate our two magazines, so as to afford scope for pleasing both those who can only take an interest in homely English life and those who have imagination enough to look beyond.[^1] I find my own village girls weary of a tale of cottage girls, and prefer something beyond their own experience.

The Children of the New Forest, The Little Stepdaughter (set in France), The Silver Skates (a Dutch tale), have been favourites of late when read aloud to them.

It will not do to confine ourselves to one class of tales for a wide a field of readers.

I remain, &c.,
C. M.

Yonge.

[^1]: This letter appeared on p. 87 of the June 1890 issue.

The author writes of the serial ‘Mademoiselle’: \'I much regret that for the second time during a very few years, a story of French life is being published in a magazine for English girls.

Thirty-three of my Members take in Friendly Leaves, and I hear from one of the elder ones that they do not care for it, and some will probably discontinue it.

Last year, on the contrary, the magazine was looked forward to from month to month and eagerly read.\' CMY is presumably suggesting that Friendly Leaves be amalgamated with [Friendly Work](../others.html#182) rather than with the Associates\' Journal.

