---
id: 225
reference-type: Topic
name: 70th Birthday Presentation to CMY
title: 70th Birthday Presentation to CMY
---

The presentation of an autograph album to CMY on her seventieth birthday, which was organized by the Moberly family, is described by Coleridge, [Life](/organisation/40), 281-2, and Battiscombe, [Charlotte Mary Yonge](/organisation/17), 159.

The following report appeared in The Times (16 August 1893), 8:

\'The 70th birthday of Miss Yonge has been marked by a presentation to her from admirers in all parts of the world. An album containing 5.000 autographs and criticisms of her writings was left on her birthday at her dwelling in the village of Otterbourne. On the front page is the following inscription in an illuminated border:- \"Charlotte Mary Yonge - We offer our hearty congratulations on your 70th birthday, and desire to express to you the great enjoyment we have received from your writings, and our belief that they have done much good in this generation. August 11, 1893.\" Amongst the signatures are those of the Archbishop of York, the Earl of Selborne, the Marquis of Salisbury, Viscount Wolmer, the Bishops of London, Manchester, Salisbury, Chester, Bath and Wells, Chichester, Leicester, Reading, Southwell, Cape Town, Connecticut, and St. Helena, Bishops Selwyn, Jenner and Hobhouse, the Deans of Winchester, Windsor and Salisbury, Canon Scott Holland, the Warden of Keble College, Mr. Balfour and several members of Mr. Gladstone\'s family, besides the local clergy and gentry. The Queen of Italy sent a large photograph of herself, bearing her autograph and accompanied by a congratulatory note. Local presentations were made to Miss Yonge on the eve of her birthday.\'
