---
id: 188
reference-type: Place
name: Church of the Resurrection, Eastleigh
title: Church of the Resurrection, Eastleigh
---

Built in 1868 with a donation of £500 from CMY.

The architect was G. E.

Street.

It was destroyed by fire in 1985 and reconstructed as social housing flats in 2003.

See Tim Lambert, A Brief History of Eastleigh, Hampshire at www.localhistories.org/eastleigh

The Hampshire Advertiser (15 August 1868), 3, noted:
The consecration of the Church of the Resurrection, Eastliegh, took place on Thursday, by the Bishop of Mauritius.

The church has been erected principally by the liberality of Miss Yonge, of Otterbourne, and Mr. - Chamberlaine, of Eastleigh Parish, together with other contributors.

The Rev. W. A.

Longlands, of Eling, near Southampton, has been appointed incumbent. A choir of amateurs has been trained by Mr.

Somerford, of Winchester Cathedral. . .

The services were intoned, or read, by the Rev. W. A.

Longlands, incumbent, the Rev. W.

Harrison, Vicar, Eastmeon, the Ven.

Archdeacon Jacob, of Winchester, the Rev. R. F.

Wilson, &c.
